### ISSUE TITLE
Adding a blank condition causes an error

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#10]
First logged as http://issues.umbraco.org/issue/CON-1464 using Umbraco 7.7.6 and Forms 6.0.5.

### What did you do?

On any field, click "Add condition", then "Submit", then "Save". In other words, add a condition without configuring it and try to save the form.

### What did you expect to happen?

Either the empty condition would be ignored, or a helpful error would be displayed when I click "Submit".

### What actually happened?

When I clicked "Save" the following message was displayed, which is not user-friendly.

![image](https://user-images.githubusercontent.com/1260550/45154715-658f3c80-b1d0-11e8-826a-173c7a182e78.png)

**Comment by warrenbuckley** [comment]
Tested & reviewed. All good :)
