### ISSUE TITLE
Forms in Umbraco Cloud: context.Record.IP does not contain users IP address

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Forms.Issues#1000]
I have noticed in Umbraco Cloud Forms `context.Record.IP` does not contain users IP address.
I am browsing https://www.idseefeld.de/meta/kontakt/ from Hamburg, Germany and log `context.Record.IP` within a custom workflow when a form get's submitted. But right now I have only received IP addresses form Amsterdam or Berlin. I have used https://iplocation.com/ to check the location. When I enter my real IP in https://iplocation.com/ I correctly get Hamburg as the location.

Actually I don't think this is really a bug. I guess it has something to do with the hosting environment. 
And regards data protection it is good not to store personal IP addresses, but the documentation needs to be explicitly clear about this behaviour.

Reproduction
------------
You need a Umbraco Cloud base form and log the `context.Record.IP` e. g. in a custom workflow.

You could use this as custom workflow:

```csharp
using Umbraco.Cms.Core.Composing;
using Umbraco.Forms.Core;
using Umbraco.Forms.Core.Enums;
using Umbraco.Forms.Core.Providers;

namespace UmbracoProject.Web.Extensions
{
    public class IpLoggerWorkflow : WorkflowType
    {
        private readonly ILogger<IpLoggerWorkflow> _logger;

        public IpLoggerWorkflow(ILogger<IpLoggerWorkflow> logger)
        {
            _logger = logger;

            this.Id = new Guid("7052e0c9-43ca-43fc-83aa-a2de0df64c1c");
            this.Name = "Ip Logger";
            this.Description = "Logs remote IP";
            this.Icon = "icon-chat-active";
            this.Group = "Services";
        }

        public override WorkflowExecutionStatus Execute(WorkflowExecutionContext context)
        {
            _logger.LogError("A record was submitted from IP {remoteIp} via the Form {name} with id {formid}",
                context.Record.IP, context.Form.Name, context.Form.Id);

            return WorkflowExecutionStatus.Completed;
        }

        public override List<Exception> ValidateSettings()
        {
            return new List<Exception>();
        }
    }

    public class IpLoggerWorkflowStartup : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.WithCollectionBuilder<WorkflowCollectionBuilder>()
                .Add<IpLoggerWorkflow>();
        }
    }
}
```

I have also set `Include Sensitive Data` in the workflow settings.

### Bug summary

`context.Record.IP` does not contain users IP address

### Expected result

I get my current IP from https://www.wieistmeineip.de/ and expect this to be logged.

### Actual result

I received IP addresses like 162.158.114.189 or 172.71.94.87, which are form Amsterdam or Berlin  according to https://iplocation.com/.

**Comment by AndyButland** [comment]
I've had a look at this and we are tracking here the IP obtained from `HttpContext.Connection.RemoteIpAddress`.  When requests are via a CDN (as in Umbraco Cloud, which uses CloudFlare), this won't be the users IP, but rather something from Cloudflare itself.

You can likely get the user's IP using one of the headers Cloudflare provides, using something like the technique shown [here](https://stackoverflow.com/questions/52190447/getting-users-ip-address-through-cloudflare-and-azure).  By handling the `RecordCreatingNotification` I'd expect you could update the `IP` property on the record to the correct value.

In terms of what we do in Forms itself, it's a bit more tricky.  If we implemented this directly we would need to handle other CDNs.  And the data/privacy landscape is different these days compared to back when this feature was added to Forms.

My thinking is that we should look to:

- Introduce a config option for IP recording:
    - `None` - no IP would be tracked
    - `RemoteIpAddress` - the current behaviour
    - `ClientIpAddress` - attempt to record and log the actual client's IP based on IP forwarding headers.

By default we'd have `RemoteIpAddress` so the current behaviour is maintained, perhaps switching this to `None` for the next major version.

**Comment by AndyButland** [comment]
The updates described above will be available in the next minor version releases.

**Comment by bjarnef** [comment]
@AndyButland would it possible to have `IP` property in `FormValidateNotification` as well?

**Comment by AndyButland** [comment]
To avoid confusion for anyone landing on this issue in future, the options described in https://github.com/umbraco/Umbraco.Forms.Issues/issues/1000#issuecomment-1499985556 were in the end not implemented.  Following review we felt the best option was to lean on Microsoft's middleware for handling this situation, and [recommend that in our documentation](https://docs.umbraco.com/umbraco-forms/developer/configuration#enablerecordingofipwithformsubmission).
