### ISSUE TITLE
The fields mapper using in the save as Umbraco node workflow does not support "magic string" placeholders

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Forms.Issues#1005]
This is a regression in recent releases of Forms 10 and 11, due to an omitted `SupportsPlaceholders` property setting on the field.

**Comment by AndyButland** [comment]
We're planning to get the next patch releases out next Tuesday, which will include the fix to this issue.

**Comment by ygrave** [comment]
Hi Andy, thanks for this information. I will wait until next Tuesday.
