### ISSUE TITLE
Can't edit 'Submit message / Go to page' workflow

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco.Forms.Issues#1007]
After upgrading Umbraco Forms on an existing project from 10.2.4 to 10.3.0 (or 10.3.1) I am unable to edit the default 'Submit message / Go to page' workflow in the Umbraco backoffice.

Reproduction
------------

### Bug summary

When I click the 'Submit message / Go to page' button in the workflow bar (bottom) I get an empty overlay with the following error message in the console:

```
angular.js:15697  TypeError: Cannot read properties of null (reading 'preValues')
    at umbraco.forms.js?d=7b554cc683abff4abcbff1a6bc32606ea13e0a2f:3498:37
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at k (angular.js:13473:36)
    at v (angular.js:13730:7)
    at y.onload (angular.js:13635:9) 'Possibly unhandled rejection: {}'
```

I can click the 'configure workflows' link to open the Workflows overlay. However, when I click the 'Submit message / Go to page' workflow in the Workflows overlay nothing happens and I get the following error message in the console:

```
angular.js:15697  ReferenceError: scope is not defined
    at umbraco.forms.js?d=7b554cc683abff4abcbff1a6bc32606ea13e0a2f:3767:32
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at HTMLDivElement.<anonymous> (angular.js:29127:13)
    at HTMLDivElement.dispatch (jquery.min.js?d=7b554cc683abff4abcbff1a6bc32606ea13e0a2f:2:43064)
    at y.handle (jquery.min.js?d=7b554cc683abff4abcbff1a6bc32606ea13e0a2f:2:41048) 'Possibly unhandled rejection: {}'
```

### Specifics

Umbraco version: Umbraco version 10.4.2
Umbraco Forms version: 10.3.0 and 10.3.1
Browser: Edge-chromium 112.0.1722.39

This issue occurs while creating a new form or when editing an existing form.
Downgrading Umbraco Forms to version 10.2.4 resolves the issue.

### Steps to reproduce

- Upgrade Umbraco Forms from version 10.2.4 to version 10.3.0 (or 10.3.1) on exising project
- Create a new form or edit an existing form
- Click the 'Submit message / Go to page' button in the workflow bar (bottom) or in the Workflows overlay

https://user-images.githubusercontent.com/161342/231535188-63bdfbf5-ebba-4fd7-83d8-4d8fe9a6eb1a.mp4

**Comment by AndyButland** [comment]
I think you may be running into a caching issue after upgrade here, as the bug you describe was found in 10.3.0, but was resolved in 10.3.1 (see duplicate issue [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/998)).

Please can you ensure you have [fully cleared the browser cache](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html), which I think should resolve the problem for you.

**Comment by creativesuspects** [comment]
@AndyButland Thanks for pointing out the other issue. I had searched the issues for the ‘preValues’ error before submitting mine, but couldn’t find anything based on that search term. 

I did open the developer tools and disabled the browser cache after upgrading from 10.3.0 to 10.3.1, but the problem persisted. I will try again today by closing and reopening Visual Studio first, clean and rebuild the project and run the backoffice in an incognito browser window to rule out any caching issues. I’ll report back here.

**Comment by creativesuspects** [comment]
@AndyButland I've upgraded Umbraco Forms from version 10.2.4 to 10.3.1 again. I've bumped the RuntimeMinification version, cleaned and rebuild the solution and completely deleted my browser cache. But I'm still getting the issue as described above (tested in Edge, Chrome and Firefox). Is there anything else I could try?

![image](https://user-images.githubusercontent.com/161342/231725408-883250f7-51d0-44df-94c3-a3bf40090141.png)

**Comment by AndyButland** [comment]
Maybe this is a different issue then, as I can see the error message you've posted this time differs from that above and the previously reported issue.

Still not something I'm seeing with 10.3.1 though, but I'll do some more tests to see if I can replicate it.  Is there any chance you could share your project with me so I can try to replicate directly on that please?  If so, I'm at _abl AT umbraco DOT dk_.

**Comment by creativesuspects** [comment]
It's the same error. The screenshot in my previous comment was taken from Firefox which reports the error differently, but it's on the same line of code:

Firefox:
![image](https://user-images.githubusercontent.com/161342/231741211-005e2459-b0d3-41cb-bd84-e0d6e44e1d4f.png)

Edge:
![image](https://user-images.githubusercontent.com/161342/231740866-7da8fc03-1d33-4355-b209-c2af8d904c73.png)

I cannot share the current project with you, but I will also try to replicate the issue on a different project or a clean install. I will keep you posted.

**Comment by AndyButland** [comment]
OK, thanks.  Yes, knowing if you can see it on a clean install would help (I've just tried that in case there was something up with my local setup, but all seemed to be as it should).

Looking at this code snippet though, it looks like you maybe don't have a rich text data type referenced correctly.  There is configuration for [this](https://docs.umbraco.com/umbraco-forms/developer/configuration#rich-text-field-type-configuration).

So perhaps you have that configuration, but are referencing a data type that doesn't exist.

Or you don't have it, but the default rich text data type has been removed from your installation (which has an Id of `ca90c950-0aff-4e72-b976-a30b1ac57dad`).

**Comment by creativesuspects** [comment]
When clicking the 'Submit message / Go to page' button the following request returns 'null':

/umbraco/backoffice/UmbracoForms/Field/GetDataTypeForRichTextField

**Comment by AndyButland** [comment]
Our messages crossed, but that makes sense based on what I was mentioning above.

**Comment by creativesuspects** [comment]
Awesome! After setting an existing DataTypeId the issue was fixed. Do you know if there's an easy way to can restore the default RTE data type with the original Id of `ca90c950-0aff-4e72-b976-a30b1ac57dad`? If not, does the RTE data type that is used for Umbraco Forms require specific settings?

**Comment by AndyButland** [comment]
Great.  Must admit I hadn't anticipated the failure here if the default data type had been removed, but you should be fine moving forward now you have one configured.

There's nothing special about the default one used for Umbraco Forms, it's just that it was the one we can (usually) expect to be there.

There are some features not supported - inserting macros for example - so it makes sense to create a data type that has just the rich text options available that work and are what you want your editors to use.

**Comment by AndyButland** [comment]
No problem, glad we got it sorted.
