### ISSUE TITLE
The title within the entries page encodes the & character.

### ISSUE THREAD

**Issue by Rockerby** [umbraco/Umbraco.Forms.Issues#1009]
The title within the entries page encodes the & character.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The title within the entries page encodes the & character.

### Specifics

Any Entries page for a form with an '&' in the title.

### Steps to reproduce

Create a form with the symbol & in the title, go to the entries page of that form.
Umbraco v10.4.2
Forms v10.3.0

### Expected result

To display the name as entered.

### Actual result

The ampersand is encoded and reads `&amp;`.

![image](https://user-images.githubusercontent.com/5808078/232632352-ecd86c07-94a3-4183-a535-127873129d4b.png)

---
_This item has been added to our backlog [AB#28542](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28542)_

**Comment by AndyButland** [comment]
Thanks @Rockerby - looks like this issue was introduced when we brought localization into the backoffice for Forms.  It seems a straightforward fix so we'll include that in the next round of patch releases.
