### ISSUE TITLE
Deleting Form fields that have Record values causes UniqueId to no longer exist

### ISSUE THREAD

**Issue by cswendrowski** [umbraco/Umbraco.Forms.Issues#101]
It seems that removing a Form field that has Record values in the database breaks the ability to render a link to those records. Deleting these records from the database that refer to the old field will resolve the issue and restore the ability to render Record links. This is obviously not ideal, as form editors are likely to want to delete a form field at some point in time without wiping out existing entries.

Related: 
https://github.com/umbraco/Umbraco.Forms.Issues/issues/96

Reproduction
------------

### Bug summary

`Record.UniqueId` is non-existent on a DynamicRecord returned by `Library.GetRecordsFromForm` when the Record contains a value for a field that no longer exists on the Form

### Specifics

Versions tested:
- Umbraco CMS 7.6.3, Forms 6.0.8
- Umbraco CMS 7.13.2, Forms 7.0.6 

### Steps to reproduce

- Create a new Form. It will be given a generated GUID - in this example, "ABC123"
- Add at least one field to the Form, such as "What is your favorite animal?". I tested with the short answer field, but it's likely this issue applies to all field types
- Render a list of Records for a Form using the following code:
```cs
foreach (dynamic record in Library.GetRecordsFromForm("ABC123"))
{
    <li>
         @if (!string.IsNullOrEmpty(record.UniqueId.ToString()))
          {
              <a href="/form?recordId=@record.UniqueId" target="_self">
                  Form Entry <span class="date">@record.Created.ToString("M/d/yy")</span>
              </a>
          }
    </li>
}
```
- Create a new entry as a Member and fill in a value for the question, such as "Cat"
- The record list will correctly render a link to your form entry for editing

Now, to introduce the bug:
- Delete the existing "What is your favorite animal?" question. Add other questions if desired
- Save the updated form
- Reload the page displaying the list of records - records will come back, but will now be missing the "UniqueId" field value and will Yellow-screen-of-death

### Expected result

`@record.UniqueId` exists and outputs a GUID for the Record

### Actual result

`UniqueId` is non-existent, causing a null pointer exception:

![image](https://user-images.githubusercontent.com/15639841/53902281-83feb500-4006-11e9-9b22-4cee82f460cb.png)

**Comment by sussexrick** [comment]
This is related to #5 - Umbraco Forms is in general not properly handling existing records when a field is subsequently deleted or updated.

**Comment by bergmania** [comment]
Hey @cswendrowski 
This issue should already be fixed in latest v7 of Umbraco.Forms.

Can you please try to update to `7.1.1` and verify the issue is resolved.

**Comment by cswendrowski** [comment]
@bergmania 
Using UmbracoForms v7.1.1 the bug seems resolved. I can now delete an existing question that had an entry value and still render the list of form entries. An entry that had a value for a now-nonexistent question shows up with the other still-existent questions filled in properly.

Thanks a ton for resolving this!
