### ISSUE TITLE
Ability to change field length especially for hidden fields

### ISSUE THREAD

**Issue by beingonlinedave** [umbraco/Umbraco.Forms.Issues#1010]
I am experiencing issues whereby I have a hidden field and seeing "String or binary data would be truncated in table" errors in the log.

It would be good to be able to specify the length of a hidden field.

**Comment by AndyButland** [comment]
Yes, "hidden field" is currently analogous to the "short answer" field type in that it stores data in the `UFRecordDataString` table which is limited to 255 characters.

If you need to store more information, I think you could likely solve this by creating your own custom field, that would be very similar to the core one but could be used to store longer values.

Something like this I think should work (for Forms 11):

```
using System;
using Umbraco.Forms.Core.Attributes;
using Umbraco.Forms.Core.Enums;

namespace MyProject
{
    [Serializable]
    public class LongHiddenField : FieldType
    {
        public LongHiddenField()
        {
            Id = new Guid("<insert Guid here>");
            Name = "Long Hidden";
            Alias = "longHidden";
            Description = "Renders a HTML hidden field suitable for storing long values";
            Icon = "icon-checkbox-dotted";
            DataType = FieldDataType.LongString;
            Category = "Simple";
            SortOrder = 121;
            FieldTypeViewName = "FieldType.HiddenField.cshtml";
            EditView = "textarea";
        }

        [Setting("Default Value", Description = "Enter a default value.", SupportsPlaceholders = true, DisplayOrder = 10)]
        public string DefaultValue { get; set; } = string.Empty;

        public override bool HideLabel => true;
    }
}
```

**Comment by beingonlinedave** [comment]
Okay, thanks.
