### ISSUE TITLE
Error when trying to capture a validation via Headless server-to-server. 

### ISSUE THREAD

**Issue by andersonrosilva** [umbraco/Umbraco.Forms.Issues#1012]
Error when trying to capture a validation via Headless. 

Is it really not possible to capture a validation via `INotificationHandler<FormValidateNotification>`?
Example: /umbraco/forms/api/v1.0/entries/0c1d33bb-a8b7-40c6-a639-f99f1bc85cfc

Using the same identifier via Component HTML, it was possible to enter the INotification.

Umbraco.Forms version: 10.3.2

---
_This item has been added to our backlog [AB#28935](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/28935)_

**Comment by AndyButland** [comment]
Looks like we don't have the hook to publish the notification on validation when processing via the API, as opposed to the usual web based form post.  But also no reason why we can't add it to support custom validation.  We'll take a look for the next release.

**Comment by andersonrosilva** [comment]
> Looks like we don't have the hook to publish the notification on validation when processing via the API, as opposed to the usual web based form post. But also no reason why we can't add it to support custom validation. We'll take a look for the next release.

Thanks, is there a schedule for publishing new releases?
I ask because we have 10 licenses that are also on our trail to implement this type of validation. If it is not possible soon we will follow another approach.

I would be very grateful to have that answer.

**Comment by AndyButland** [comment]
This is prepared now and will be available in the next minor release of Forms.
