### ISSUE TITLE
Configuration options Data Consent FieldType

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco.Forms.Issues#1013]
As a Umbraco Forms Editor i don't want to edit the dataconsent for every form. 

Our client want's to have the option to set the Accept Copy and Mandatory message for every record. In the current setup this is not possible. 

A further request is the option to reference a cookiepolicy page. Perhaps an RichTextEditor is a more suitable option. 

---
_This item has been added to our backlog [AB#29225](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29225)_

**Comment by AndyButland** [comment]
As of the next minor release, we'll add an abstraction to the behaviour of adding default fields to a form, which will allow you to register your own implementation to customize this behaviour.

It will work in a similar way to the existing `IApplyDefaultWorkflowsBehavior` as documented [here](https://docs.umbraco.com/umbraco-forms/developer/extending/customize-default-workflows#implementing-a-custom-behavior).  Once released this page will be updated to detail the behaviour for fields.
