### ISSUE TITLE
Adding WriterId/UserId to Form model

### ISSUE THREAD

**Issue by jamiepollock** [umbraco/Umbraco.Forms.Issues#1014]
Would it be possible to add the WriterId/UserId to the Form model? This would be similar to the Umbraco CMS WriterId on `IContentBase`  ([source ref](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Models/IContentBase.cs#L27)).

**Comment by jamiepollock** [comment]
The reason for this feature request is we have a custom auditing package which tracks Content and Media CMS changes with notification handlers. 

I had intended to add Forms to this system as there are a great set of handlers already in place but I noticed there isn't a WriterId to track the user who created/deleted/modified the form.

**Comment by AndyButland** [comment]
Could be possible yes, but we don't actually track this at the moment, so we'd need to start persisting it to the database as well.

What would you be looking for here though - the user that created the form, or the one that last edited it?

Sounds like given you are talking about auditing, it's the one who has made the last edit - so perhaps we can resolve this better by adding the back-office user Id as a new property to the notifications that are generated.

**Comment by jamiepollock** [comment]
@AndyButland yea, that would be great. I don't really expect a revisions history like with Umbraco CMS's Content. 

Having the current user id is the notification who did the event would be fine for now.

Just thinking, would this change to notifications also affect repo/service calls too as I know you have Save methods which don't provide a User ID overload. Just wondering how you'd provide the user ID is these cases to the notification?

I'm more than happy with the change suggested though.

**Comment by AndyButland** [comment]
Have just been having a play with this, and I think you can do do this within the notification handlers at the moment.  For example, the following looks to work for me to log the user who has made a particular update:

```
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Models.Membership;
using Umbraco.Cms.Core.Security;
using Umbraco.Forms.Core.Models;
using Umbraco.Forms.Core.Services.Notifications;

namespace Umbraco.Forms.Testsite
{
    public class FormSavedNotificationHandler : INotificationHandler<FormSavedNotification>
    {
        private readonly ILogger<FormSavedNotificationHandler> _logger;
        private readonly IBackOfficeSecurityAccessor _backOfficeSecurityAccessor;

        public FormSavedNotificationHandler(ILogger<FormSavedNotificationHandler> logger, IBackOfficeSecurityAccessor backOfficeSecurityAccessor)
        {
            _logger = logger;
            _backOfficeSecurityAccessor = backOfficeSecurityAccessor;
        }

        public void Handle(FormSavedNotification notification)
        {
            string updatedBy = "n/a";
            IUser? backOfficeUser = _backOfficeSecurityAccessor.BackOfficeSecurity?.CurrentUser;
            if (!string.IsNullOrEmpty(backOfficeUser?.Name))
            {
                updatedBy = backOfficeUser.Name;
            }

            foreach (Form form in notification.SavedEntities)
            {
                _logger.LogInformation($"Form '{form.Name}' updated by '{updatedBy}'.");
            }
        }
    }
}
```

Does this help for your use case?

**Comment by jamiepollock** [comment]
@AndyButland looking at the code I think that would do the trick. Thanks, Andy!

**Comment by AndyButland** [comment]
I'll close this one now then as seems we have a way to handle the use case using the existing features of the product.
