### ISSUE TITLE
When field is not in collection builder it is not possible to add new FieldType

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco.Forms.Issues#1015]
When a fieldtype gets removed from the FieldCollectionBuilder the picker for the questions which use that FieldType, cannot be reset to another fieldtype.  

![image](https://user-images.githubusercontent.com/22054828/236203465-eb40ace6-c05f-4e1e-8f01-7f0c1c53eb0b.png)

![image](https://user-images.githubusercontent.com/22054828/236203531-c5df3dd8-40a2-4c58-9fa7-98ef8763cd0c.png)

Reproduction
------------

### Steps to reproduce
- Remove a fieldtype from the  ```builder.WithCollectionBuilder<FieldCollectionBuilder>() ```
- Restart the application a
- Go to a Form
- Try to edit the question with the removed FieldType. 
-

### Expected result

I am expecting to be able to configure the question with another fieldtype. A poor workaround is to delete the question and re add it with a different fieldtype. With possible loss of aliasses. 

### Actual result

I am not able to pick another FieldType for the question which uses the removed FieldType

---
_This item has been added to our backlog [AB#29230](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29230)_

**Comment by AndyButland** [comment]
This looks to be mostly a UI issue - in that without a field type, the part you click on to open the overlay and select a different type isn't visible and clickable.

Well, actually part of it is...

![image](https://user-images.githubusercontent.com/1993459/236615776-337d8cb1-ccc5-422e-ab88-3c8bbe2ddc5a.png)

... if you click this area it will open.  So you can use that as a workaround whilst waiting for us to fix it up properly.
