### ISSUE TITLE
Typo in dialog label

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Forms.Issues#1017]
The dialog for editing a form field (question) has a typo in its Danish label: **Ret sprøgsmål** should be **Ret spørgsmål**

<img width="280" alt="Part of the Edit question dialog in Danish showing a typo in the label" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/5463/d279b9bf-33b4-4594-b2e3-c61aef35c593">

Looks like it's the `editQuestion` key in the language file (`staticwebassets/Lang/da-dk.xml`) that needs to be updated:

```diff
-<key alias="editQuestion">Ret sprøgsmål</key>
+<key alias="editQuestion">Ret spørgsmål</key>
```

This was noticed in Umbraco 10.x, but I've verified that the typo is still present in the latest version of `Umbraco.Forms.StaticAssets` (currently `v11.1.2`).

**Comment by AndyButland** [comment]
Thanks @greystate - have updated for the next releases.
