### ISSUE TITLE
Umbraco Forms 10.3.2: conditions not working

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Forms.Issues#1018]
Conditions in Umbraco Forms are not working. When setting conditions nothing is changed at the front-end

Reproduction
------------

1) create Umbraco Forms form
2) create field we want to use for condition (example: single choise with values 'yes' and 'now)
3) create conditional field, condion: 'show' when field is set to 'yes'
4) change radio on front-end to 'yes'
5) condition is not showing

Umbraco version: 10.3.2
Umbraco Forms version: 10.5.1

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/6d947bef-18ae-4921-94e2-3d639562edee)

When reviewing UmbracoForms.js file I noticted this code snippit, containing htmlFieldId:

```
for (fieldId in self.fieldConditions) {
                if (Object.prototype.hasOwnProperty.call(self.fieldConditions, fieldId)) {
                     htmlFieldId = self.formElementHtmlIdPrefix + fieldId;
                     if (document.getElementById(htmlFieldId)) {
                         handleCondition(document.getElementById(htmlFieldId).closest(".umbraco-forms-field"),// sadly we cant use querySelector with current mark-up (would need to prefix IDs)
                            fieldId,
                            self.fieldConditions[fieldId],
                            "Field");
                    }
                }
            }
```

self.formElementHtmlIdPrefix is always undefined!
Quick search brought me to this topic containing the solution: https://our.umbraco.com/forum/using-umbraco-and-getting-started/110900-umbraco-forms-conditions-with-custom-theme
Solution:  add this row to Script.cshtml file inside the 'formJsObj' object: `formElementHtmlIdPrefix = Model.FormElementHtmlIdPrefix`
After that, formElementHtmlIdPrefix is not undefined any longer.

Next issue was this line of code: ` handleCondition(document.getElementById(htmlFieldId).closest(".umbraco-forms-field")`
closest(".umbraco-forms-field") is always null. To fix this issue i've added to `Form.cshtml` this class to our div: `umbraco-forms-field`

Snippit of Form.cshtml containing fix:

```
@foreach (var c in fs.Containers)
                {
                    <div class="form__container @("col-span-" + c.Width)">
                        @foreach (FieldViewModel f in c.Fields)
                        {
                            bool hidden = f.HasCondition && f.ConditionActionType == FieldConditionActionType.Show;

                            <div class="form__field umbraco-forms-field" @{
                                if (hidden)
                                {
                                    <text>style="display: none"</text>
                                }
                            }>
```

After applying al changes the condition start to work.

**Comment by AndyButland** [comment]
Thanks for sharing your updates here.  I'll just add that we make available the default theme files available for download from [this link](https://docs.umbraco.com/umbraco-forms/developer/themes#obtaining-the-default-theme-files). So if anyone does have issues getting a form to work correctly using their own theme, whilst it does with the default, then a comparison can be made with these.
