### ISSUE TITLE
Umbraco form multiple choice field type throws exception

### ISSUE THREAD

**Issue by pniniG** [umbraco/Umbraco.Forms.Issues#1019]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco : 10.3.2 ,Umbraco Forms : 10.2.0

### Bug summary

Umbraco form multiple choice field type throws exception Unexpected value: 'false'. Expected one of these <my checkbox fields>
when the submit the form.

### Steps to reproduce

create a form with multiple choice field,
use it and try to submit.

### Expected result / actual result

Expected : saved the forms
Actual : the saved failed and throws exception Unexpected value: 'false'. Expected one of these <my checkbox fields>.

**Comment by ronaldbarendse** [comment]
Hi @pniniG! I've tried to replicate this issue, but don't get the exception when saving the form. Can you ensure your browser cache is cleared and that you see this Value/Caption editor for the prevalues:

![Multiple choice prevalues](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1051287/6282741c-c474-4ced-8452-e8bf6dcd8609)

If this is the case and you still get the exception, can you provide the prevalues you've used in the multiple choice field? And does this also happen on newly created forms or only on an existing one?

**Comment by pniniG** [comment]
hi @ronaldbarendse 
This does also happen on newly created form.
thanks pnina

**Comment by AndyButland** [comment]
Can you provide the specific prevalues (options) you've used in the multiple choice field please?  Perhaps there's some issue that comes up due to specific values being saved.

**Comment by pniniG** [comment]
I found the problem, the problem was in the custom theme that was connected to the form.
thanks @AndyButland @ronaldbarendse 👍
