### ISSUE TITLE
Forms boxes in dashboard in Umbraco 8

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#102]
In Umbraco 8 the forms boxes background is almost faded with the background color.

![image](https://user-images.githubusercontent.com/2919859/53942354-d4cfe580-40ba-11e9-8e85-12b8724b3e1f.png)

I would be great to update the colors of these, maybe re-use the `umb-box` component or use the styling of these boxes.
![image](https://user-images.githubusercontent.com/2919859/53942495-398b4000-40bb-11e9-91ba-5637cb8da9bf.png)

E.g. compare the boxes with LogViewer dashboard.
![image](https://user-images.githubusercontent.com/2919859/53942582-71928300-40bb-11e9-82a9-3aa09f683b56.png)

**Comment by bergmania** [comment]
Commit: https://github.com/umbraco/Umbraco.Forms.Issues/issues/102
