### ISSUE TITLE
Email workflow showing trail mode but custom workflow worked as expected

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco.Forms.Issues#1024]
Hi,

Email workflow for sending all the form fields to an email address all showed 

"Empty due to Umbraco Forms in trial mode"

We have a CRM workflow that worked successfully, and we don't store the records in forms. This has resolved itself since but we are just wanting to do some root cause.

Incident was on May 19th 1:17pm Chicago time

### Specifics

Forms - 10.3.0

### Steps to reproduce

We have not been able to replicate

### Expected result

Data is sent

### Actual result

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6782865/69c054b1-82a1-4bb6-be4e-89ac2e90be6b)
709

**Comment by lesley-w** [comment]
We have the same issue.
Licence is not showing any errors in the back-office and form entries are viewable in the back-office, but emails have all fields as "Empty due to Umbraco Forms in trial mode".

What domain does the licence check against when sending emails? Is it the website domain e.g xxxxx.com or the Azure web app domain e.g. xxxxxxxxxxxxxxxxxxxxxxx.azurewebsites.net?

**Comment by AndyButland** [comment]
You can check the domain it's using when executing a workflow by adding the following custom workflow to your project and then associating it with a form.  It uses the same method to retrieve the domain as the underlying licensing component does.

The workflow just retrieves the domain and logs it, so after submitting the form you can check in the backoffice "Log viewer", or the log file on disk, to see what it's picking up.

The workflow looks like this (for Forms 10/Umbraco 10):

```
using Umbraco.Forms.Core;
using Umbraco.Forms.Core.Enums;

namespace UmbracoProject.Business.Workflows
{
    public class LogDomainWorkflow : WorkflowType
    {
        public const string LogDomainWorkflowId = "6e2f4677-4161-4c70-aeff-cb9c64b4519b";

        private readonly ILogger<LogDomainWorkflow> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public LogDomainWorkflow(ILogger<LogDomainWorkflow> logger, IHttpContextAccessor httpContextAccessor)
        {
            Id = new Guid(LogDomainWorkflowId);
            Name = "Log Domain Workflow";
            Description = "A test workflow that writes a log line with the current domain used for the license check.";
            Icon = "icon-coffee";

            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
        }

        public override WorkflowExecutionStatus Execute(WorkflowExecutionContext context)
        {
            var domain = _httpContextAccessor.HttpContext?.Request.Host.Value ?? "n/a";
            _logger.LogInformation($"Domain for license check: {domain}");

            return WorkflowExecutionStatus.Completed;
        }

        public override List<Exception> ValidateSettings() => new List<Exception>();
    }
}

```

And you'll need to add a composer to register it:

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Forms.Core.Providers;
using UmbracoProject.Business.Workflows;

namespace UmbracoProject.Business
{
    public class SiteComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.WithCollectionBuilder<WorkflowCollectionBuilder>()
                .Add<LogDomainWorkflow>();
        }
    }
}
```

**Comment by lesley-w** [comment]
Turns out that because of the way the client implemented Azure Front-Door, the emails are being sent from the default Azure App service domain xxxxxxxxxxxxxxxxxxxxxxx.azurewebsites.net, not the website domain.

We added the Azure domains to the licence and this resolved the issue.

**Comment by AndyButland** [comment]
That's good to hear.  I'll close this then, and hopefully the above workflow can help anyone else in this situation.
