### ISSUE TITLE
10.3.3: RemoveProvidedEmailTemplate and RemoveProvidedFormsTemplates not working

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Forms.Issues#1025]
**Versions**
Umbraco version: 10.5.1
Umbraco Forms version: 10.3.3 (also tested 10.3.2)

When setting `RemoveProvidedFormsTemplates` and `RemoveProvidedEmailTemplate` nothing is changed in my backoffice.
According to the [docs](https://docs.umbraco.com/umbraco-forms/v/10.latest-lts-2/developer/configuration#removeprovidedemailtemplate), settings this properties will affect the 'Create a new form or folder' dialog inside Umbraco Forms.

Can someone please explain how to remove 'Comment form' and 'Contact form' from the create form dialog?

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/1fee132b-b6c2-4532-b066-d3d3f5e7aba5)

**Config inside appsettings.json's Umbraco object:**
```
"CMS": {
...
},
"Forms": {
      "FormDesign": {
        "Defaults": {
          "Indicator": "*",
          "MessageOnSubmit": "Thank you :)"
        },
        "DisableAutomaticAdditionOfDataConsentField": true,
        "DisableDefaultWorkflow": true,
        "RemoveProvidedEmailTemplate": true,
        "RemoveProvidedFormsTemplates": true
      },
....
}
```

**Docs:**
- RemoveProvidedEmailTemplate
From Forms 10.2, the provided template can be removed from the selection if you have created email templates for the "send Razor email" workflow. To do this, set this value to true.

- RemoveProvidedFormsTemplates
Similarly, from Forms 10.2, the provided form templates available from the form creation dialog can be removed from selection. To do this, set this configuration value to true.

**Comment by AndyButland** [comment]
Should be OK with `RemoveProvidedFormTemplates` (sorry, looks like we have a typo in our docs, which I'll get updated).

**Comment by AndyButland** [comment]
Yes, that should be OK... I tested it before posting to be sure.  Have you restarted?  Will be necessary if you have updated the configuration for this value.

**Comment by RunnicFusion** [comment]
hi @AndyButland yes I did. will run some more tests but for now the dialog is containing the same options as before.

**Comment by RunnicFusion** [comment]
@AndyButland sorry, i'm afraid I have to reopen this issue.
double checked my settings, they look fine to me.

Any other suggestions?
Did you use Umbraco Forms 10.3.3 and Umbraco 10.5.1?

**Comment by AndyButland** [comment]
One further thought - do you have these files on disk in `App_Plugins\UmbracoForms\Data\Templates`?  You might if you have upgraded from an older version of Forms.

If so, you just need to remove them.

If that does turn out to be it, this is the background.  Up to Forms 9, these files were just shipped on disk and as such if you didn't want to use them, you could just delete them.  With Forms 10+ we ship them as part of a Razor Class Library, and as such you aren't able to delete them from disk - which is why we introduced this configuration setting.

So perhaps if you've upgraded, previously you had them both in the RCL and on disk.  The configuration removes the ones from the RCL, but as they are on disk you still see them from there.

**Comment by RunnicFusion** [comment]
@AndyButland yeah, saw how this setting is/was working when decompiling Umbraco Forms dll's. Unfortunately I don't have a folder called `App_Plugins/UmbracoForms` in my project.

Was checking my `startup` file, toggeling `AddUmbracoForms` method doesn't work either.
I do use AzureBlob storage for pre value text files, but it doens't seams to make any difference removing this logic for debug purposes.

 `builder.AddAzureBlobFileSystem("Forms", options => options.VirtualPath = "~/forms")
				.Services.AddUnique<IPreValueTextFileStorage>(factory => new PreValueTextFileSystemStorage(
					factory.GetRequiredService<IAzureBlobFileSystemProvider>().GetFileSystem("Forms"),
					factory.GetRequiredService<IScopeProvider>(),
					"PreValueTextFiles"));`

**Comment by AndyButland** [comment]
I could replicate with a clean install @RunnicFusion and have fixed this issue, which we'll include in the next release.

**Comment by RunnicFusion** [comment]
Thanks for updating me + the fix :)
What date do you expect version 10.4.0 to be finished?

**Comment by RunnicFusion** [comment]
> I could replicate with a clean install @RunnicFusion and have fixed this issue, which we'll include in the next release.

Thanks for updating me + the fix :)
What date do you expect version 10.4.0 to be finished?
