### ISSUE TITLE
Umbraco Forms 10.X: issue when using conditions for pages - wrong page is displaying

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Forms.Issues#1026]
### Versions
Umbraco version: 10.5.1
Umbraco Forms version: 10.3.3

When creating a form out of 3 steps showing the steps after selection isn't working as expected.

### Form setup:
- Step 1: 
- 'Display step' with options: 'step 2' and 'step 3'

**- Step 2:**
- Short answer field

**- Step 3:**
- Short answer field

### Result:
- select 'step 2' -> step 2 (with Short answer field) displays
- select 'step 3' -> step **2** (with Short answer field) displays

### Expected result:
- select 'step 2' -> step 2 (with Short answer field) displays
- select 'step 3' -> step **3** (with Short answer field) displays

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/86444195-0dac-4162-9ece-556b62b00cc4)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/45e3bb89-0a2f-49bc-be45-419b9fbe5741)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/8efac7bc-586d-421a-a02b-6c30cf75a476)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/0bba446e-415c-4873-b6d4-5380ae4c7a5b)

Already tried different projects our company has, same result. When reverting forms.cshtml we can't also make it work.

Docs: https://docs.umbraco.com/umbraco-forms/v/10.latest-lts-2/editor/creating-a-form/conditional-logic#conditions-for-pages-and-fieldsets

**Comment by AndyButland** [comment]
I think this is working as expected how you have configured it.  You have asked to not show the "submit" or "next" button on the second page unless the value of the first question is "2", and that's what you see in your screenshot.

From the docs that you linked above... _When applying a condition to a page, effectively you are controlling the display of the submit button (for a single-page form) or the next/previous buttons (available on multi-page forms). In this way you can ensure that the entry so far is complete before accepting it or allowing the user to move onto the next page._

To get what I think you are looking for, you should likely use a single page form, add the questions and conditions onto the fieldsets/groups, something like this:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/0a091158-5451-4d2f-9935-1a9dd6c8f64b)

Or, if you do want the questions on multiple pages, do that, but still apply the condition to the groups.  When you submit page 1 and navigate to page 2, if no groups are configured for display, it'll skip on to step 3:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/b1d964e4-e0c3-4be4-ac37-5a54bdf16ec2)

**Comment by RunnicFusion** [comment]
closed.
