### ISSUE TITLE
Radio button list and checkbox list validation problem

### ISSUE THREAD

**Issue by brionymckenzie** [umbraco/Umbraco.Forms.Issues#1028]
The input-validation-error class does not get removed when it should be.

Reproduction
------------

### Bug summary

Having trouble styling radio and checkbox lists validation errors as the input-validation-error class is not removed from every input in each list when one is selected.

### Specifics

Using Umbraco Forms v11.1.1.
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/120108741/80d652ea-3197-4911-810d-fe92c2f8d331)

### Steps to reproduce

- Create a form with Single Choice and Multiple Choice field types.
- Make those fields Mandatory.
- Click the form submit button without touching the form.
- Select one radio button option and one checkbox option from each question.

### Expected result

I expected the input-validation-error class to be removed from each radio and checkbox input where the name matched the selected item.

### Actual result

The input-validation-error class is only removed from the input that was selected. The field-validation-error message text is removed as it should be, but the input-validation-error class isn't removed from all the elements in each list.

---
_This item has been added to our backlog [AB#30198](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30198)_

**Comment by AndyButland** [comment]
Hi @brionymckenzie - thanks for reporting this.  I've had a look and can replicate what you have found.

Here we utilise a third-party component for the client-side validation, and the behaviour you've found is the case within it.  It does seem there's a valid case for amending it though, so I've [submitted a PR](https://github.com/haacked/aspnet-client-validation/pull/40) to that library to do so.  If that is accepted, we can update to the newer version and provide it with Forms to resolve this issue.

In the meantime, I think you may be able to look at this at least from a presentation perspective with CSS.  `.input-validation-error` will be styled to indicate an error, but you may be able to target `.input-validation-error that is a child of a sibling of span.field-validation-valid` to override the style such that it is presented as valid.

**Comment by AndyButland** [comment]
The PR has been accepted [a new version of the aspnet-client-validation library released](https://www.npmjs.com/package/aspnet-client-validation).  We'll update to that for the next Forms release which looks to resolve this issue.
