### ISSUE TITLE
Duplicate "Add new page" button on form editor

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.Forms.Issues#1029]
When having a multi-step form or even a very long form and you decide to add a new page, it's a bit painful that you have to scroll all the way down to create one, then if you decide to move that page to the top, then it becomes a real pain.

I think a good solution would be to add another 'Add New Page' button to the top of the form.

Even better, if there is a way to add a choice whether we want to add the page to the top of bottom will make it super convenient, that way, the ordering becomes easier and faster.

---
_This item has been added to our backlog [AB#33506](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33506)_

**Comment by AndyButland** [comment]
We've added this additional button now which will be available from the next release.  It'll look like this:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/eca8f255-5a21-456e-9ab3-90bfa9f4831d)
