### ISSUE TITLE
Update forms fields design in Umbraco 8

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#103]
Consider to update the styling of the fields design in Umbraco 8 to match e.g. properties in document types, e.g. the preview of the fields and change the turquoise border.

![image](https://user-images.githubusercontent.com/2919859/53942697-b1f20100-40bb-11e9-914c-a9b65f0a711f.png)

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - this is going on the ideas list for a future update of the design.

**Comment by AndyButland** [comment]
Given this has been open for a while and we have the new back-office project on the horizon, I'll close this one.  When we re-implement Forms using this, we'll be re-using the elements from there and hence certainly be aligning much more closely.
