### ISSUE TITLE
'Umbraco Documents' prevalue source includes unpublished/trashed nodes

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco.Forms.Issues#1030]
Unpublished and trashed nodes are still visible in the 'Umbraco Documents' prevalue source.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

We're using an 'Umbraco Documents' prevalue source to populate a dropdown in Umbraco Forms. Unpublished and trashed nodes remain visible in the dropdown. It appears the prevalue source values are being cached. I don't know for how long. Re-saving the prevalue source appears to clear the cache, because the trashed nodes are no longer visible in the dropdown after re-saving. Unpublished nodes remain visible though.

In short:

Trashed nodes: visible in the prevalue source, no longer visible after re-saving the prevalue source
Unpublished nodes: visible in the prevalue source, even after re-saving the prevalue source

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/b9cab252-86d4-4194-8bcc-11bf479d1ac3)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/8ab32793-acdd-4929-befa-8eb3ce562e0f)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/3332d777-df7b-4653-b887-a80ae22781be)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/c1cd0003-a150-4159-b196-33d57a76ed15)

### Specifics

Umbraco: 10.5.1
Umbraco Forms: 10.3.3

### Expected result

Trashed nodes should not remain visible in the 'Umbraco Documents' prevalue source. And it should not be necessary to re-save the prevalue source in order to hide trashed nodes from the prevalue source values. In my opinion unpublished nodes should also not be visible in the prevalue source, but maybe this is by design?

I've also attached a test project with a clean install of Umbraco 10.5.1 and Umbraco Forms 10.3.3:

[PrevalueSourceTest.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/11665621/PrevalueSourceTest.zip)

Username: admin@example.com
Password: Test12345!

---
_This item has been added to our backlog [AB#30205](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30205)_

**Comment by AndyButland** [comment]
As of the next minor releases of Forms, we'll have an option to control the cache settings for prevalue sources:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/6f546789-74c2-46f1-b355-ca2fc7a40c85)

I've also managed to replicate the issue with making available unpublished nodes now, so that'll be resolved too.

**Comment by AndyButland** [comment]
> I've also managed to replicate the issue with making available unpublished nodes now, so that'll be resolved too.

This part of the resolution to this issue only has been ported back to Forms 8, as part of 8.13.11.  The prevalue caching feature will remain only in 10 and 12.
