### ISSUE TITLE
Data Consent not using text set in appsettings

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco.Forms.Issues#1034]
We are rewriting the Data Consent accept copy. However we encounter the following behaviour: 

- When opening a existing form, the data consent text is still the default text. 
- When creating a new form, the data consent text is still the default text. 

What we would expect that the text provided in the configuration below is used.

` "SettingsCustomization": {
          "FieldTypes": {
            "dataConsent": {
              "AcceptCopy": {
                "DefaultValue": "My text i expect to see in the backoffice and frontend.",
                "IsReadOnly": true
              },
              "ShowLabel": {
                "IsHidden": true
              }
            }
         }`

**However**
When removing and adding the dataconsent field to the form, the configuration values above are used. 

---
_This item has been added to our backlog [AB#30337](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30337)_

**Comment by AndyButland** [comment]
I've just tested this out and confirm what you are seeing, which I think is expected (or at least I can see why it's happening).  As you've found, when removing and adding the data consent field to the form, the configuration values above are used.

> When opening a existing form, the data consent text is still the default text.
This is as as designed.  If a value has previously been saved on an existing form, we aren't overwriting it with the defaults.  To fix this I think you would need to amend the forms to the correct values, and then after that set the defaults such that new fields are created to your requirements.

> When opening a existing form, the data consent text is still the default text.
Although I can see this is a bit confusing, it's also expected, as there is something else going on here.  When a new form is created Forms has some default behaviour defined that always adds a data consent field with particular values to a form.  So this isn't using the defaults.  Arguably it should, so I'll keep this issue open and see if we can look at that.  In the meantime you could look to implement and register your own `IApplyDefaultFieldsBehavior`, as is documented [here](https://docs.umbraco.com/umbraco-forms/developer/extending/customize-default-workflows).

**Comment by AndyButland** [comment]
As of the next releases the custom data consent copy will be used when creating new forms, as well as when adding the field to existing forms.
