### ISSUE TITLE
User Group Documentation Clarification

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.Forms.Issues#1035]
Maybe it should be clarified that a true value for ManageSecurityWithUserGroups should not be used with the "special" values (all and form-creator).

If you set ManageSecurityWithUserGroups to true and use 'form-creator' in "GrantAccessToNewFormsForUserGroups", you won't be able to access the form you create, even though in the form security, it shows that you have access to it.

Umbraco v10.5.1 with Forms v10.4.0

---
_This item has been added to our backlog [AB#30339](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30339)_

**Comment by AndyButland** [comment]
This seems to be OK in my tests.  I've got two users, one an admin and also in a custom "form creators" group, and another only in "form creators".

With these settings:

```
      "Security": {
        "ManageSecurityWithUserGroups": true,
        "GrantAccessToNewFormsForUserGroups": "form-creator"
      },
```

I do find that a form created by the first user is available to the second one.

Are you able to provide details of a similar test that you see not operating as expected please?  Thanks.

**Comment by TRexStark** [comment]
Hi @AndyButland

That is odd, I spent some time trying to figure out what's going on.

**Comment by AndyButland** [comment]
I'll close this one now given no further discussion.  Please feel free to re-open though if you have been able to establish the issue further.
