### ISSUE TITLE
Typo in the default FileUpload.cshtml theme

### ISSUE THREAD

**Issue by rickdoesburg** [umbraco/Umbraco.Forms.Issues#1039]
There's a typo in the [latest Forms 11 Default theme](https://docs.umbraco.com/umbraco-forms/developer/themes) template for the `FieldType.FileUpload.cshtml` file.

On line #14 there is a slash, which is also rendered as a /:
`<strong>Current File/s:</strong><br />`

Besides the typo, wouldn't it be better if this string is translatable?

---
_This item has been added to our backlog [AB#30708](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30708)_

**Comment by AndyButland** [comment]
As of the next release, the default text will be updated to "Current file(s): " and there'll be a setting on the field type to customize this label.
