### ISSUE TITLE
Change enable conditions to toggle

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#104]
It would be great to change the "Enable conditions" checkbox to a toggle using `umb-toggle`.

![image](https://user-images.githubusercontent.com/2919859/53942965-62600500-40bc-11e9-9a08-bedcd8e0471e.png)

Maybe also change to hover color on the columns here to match the styles in grid editor config.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco.Forms.Issues/issues/104.

I think the colouring should be in a separate issue for general colour alignment
