### ISSUE TITLE
Umbraco cannot start after installation of Umbraco Forms plugin (BootFailedException)

### ISSUE THREAD

**Issue by vkuybida** [umbraco/Umbraco.Forms.Issues#1041]
A brief description of the issue goes here.

I use the latest version of Umbraco (11.4.0), on-premises, SQL server database.
I'd like to install Umbraco Forms plugin v 11.2 (within VisualStudio 2019, nuget package). Installation works fine. However, when I run solution, I receive following error message: "Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database."

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

   1. Create new Umbraco project within Visual Studio and SQL Server database.
   2. Install Umbraco Forms nuget package.
   3. Run solution,

### Specifics

My connection string looks as follow:

"ConnectionStrings": {
    "umbracoDbDSN": "Server=.\\sqlexpress;Database=my_db_name;User Id=sa;Password='mypwd';Trusted_Connection=True;",
    "umbracoDbDSN_ProviderName": "Microsoft.Data.SqlClient"
  },

Log record:
{"@t":"2023-06-21T16:02:38.7498574Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.\n\n-> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.\n   at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()\r\n   at Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)\r\n   at Umbraco.Cms.Web.Common.Middleware.BootFailedMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)\r\n   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"4000001c-000a-f400-b63f-84710c7967bb","RequestPath":"/","ProcessId":14808,"ProcessName":"iisexpress","ThreadId":4,"ApplicationId":"4edd33ec64e6db30856ba2e916363bad66503a44","MachineName":"MRROBOT","Log4NetLevel":"ERROR"}

### Steps to reproduce

   1. Create new Umbraco project within Visual Studio and SQL Server database.
   2. Install Umbraco Forms nuget package.
   3. Run solution,

### Expected result

   Solution should run fine, Umbraco Forms creates all the tables at db and works as expected.

### Actual result

   Umbraco can't be loaded at all. Is it possible that Umbraco Forms do not like connection string format?

**Comment by vkuybida** [comment]
Found this article. It helped to solve the problem:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/111678-umbraco-11-forms

Adding of "TrustServerCertificate=true;" solved the problem, but it's not obvious at all

**Comment by AndyButland** [comment]
It looks like this issue has come up on the CMS tracker a couple of times:

- https://github.com/umbraco/Umbraco-CMS/issues/14111
- https://github.com/umbraco/Umbraco-CMS/issues/14272

The issue was recognised and resolved in CMS 12.  I understand it wasn't specific to adding Umbraco Forms.
