### ISSUE TITLE
v10.4.0 Conditions not working with custom prefix

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.Forms.Issues#1043]
Umbraco v10.5.1
Umbraco.Forms v10.4.0

When setting a custom prefix (**FormElementHtmlIdPrefix**) in appSettings, conditions do not work. Or am I missing something?

Verified that `Themes > default (and custom) > Script.cshtml` already has

`data-form-element-html-id-prefix="@Model.FormElementHtmlIdPrefix"`
in the `umbraco-forms-form-config` div

The latter is also mentioned here > https://our.umbraco.com/forum/using-umbraco-and-getting-started/110900-umbraco-forms-conditions-with-custom-theme#comment-343939

Reproduction
------------

1. In appsettings.json
- Add the following setting > Forms:FormDesign:FormElementHtmlIdPrefix with a value of "f_"
- As per the documentations:
https://docs.umbraco.com/umbraco-forms/developer/configuration#editing-configuration-values
And
https://docs.umbraco.com/umbraco-forms/developer/configuration#formelementhtmlidprefix

2. In the BackOffice
- Create a simple form
- Add a Single Choice fieldtype (Radio) with values (Yes and No)
- Add another FieldType (Short Answer)
- Add a condition to the Short Answer to Show when the 'Single Choice' is 'Yes'

3. Test the form in the Front-End and select "Yes" in the Single Choice field
- Result: Condition doesn't work

4. Go back to appsetting and remove the custom prefix we added in point 1 above

5. Test the form again in the Front-End by selecting "Yes" in the Single Choice field
- Result: Condition works

---
_This item has been added to our backlog [AB#30782](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30782)_

**Comment by TRexStark** [comment]
@AndyButland Has this been triaged and replicated?

**Comment by AndyButland** [comment]
Yes, we have a fix pending review that we'll make available in the next releases.
