### ISSUE TITLE
Move the Attachment Toggle

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#1044]
The "Send Email" WorkFlow item has an "Attachments" toggle. My understanding is that it is there to allow files uploaded by the form user via a "File upload" property editor (or "Answer") whether there has been a "File upload" property added or not.  

It would make more sense if the toggle were moved to the configuration pane of the "File upload" property editor.  

As presently constituted, the "Attachments" toggle appears to do nothing. It can also be misconstrued as giving the ability to attach a  file to the email. i.e. one might expect a file selection dialogue to appear.

**Comment by AndyButland** [comment]
Thanks, we'll update this label and description with the next releases.
