### ISSUE TITLE
Use unique names for database object

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#1049]
Hi!

We had issues starting up our site after installing a fresh Umbraco Forms.

Turns out that one of the issues was that the UFUserFormSecurity-table has a index named `Id` which one of our custom tables also had.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/f5e91f9d-5c27-41c3-bc47-18d77b0f69d9)

The problem is easy to solve for us by just renaming our index but maybe it would be better to be consistent with other tables in Umbraco forms and use `PK_{tableName}` as the name of the clustered index to keep them unique and avoid collisions.

Cheers!

---
_This item has been added to our backlog [AB#31347](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31347)_

**Comment by AndyButland** [comment]
Thanks for flagging this... I'd never noticed, but agree this isn't a very good name for something that should be unique across the database.  We'll adjust to the usual convention you have suggested for the next releases.
