### ISSUE TITLE
Umbraco Documents picker returns error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#105]
In prevalue sources when creating a new, selecting "Umbraco Document" and "Choose" it returns the following error in Umbraco 8.

![image](https://user-images.githubusercontent.com/2919859/53944416-9c7ed600-40bf-11e9-9b3b-dec1240d6793.png)

Furthermore the pickers styling should match other pickers, see also this issue for Umbraco core: https://github.com/umbraco/Umbraco-CMS/issues/4905

Also consider if the checkboxes here should use a toggle `umb-toggle`.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/254
