### ISSUE TITLE
Form Picker Edit/Open target path incorrect

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#1051]
## Brief Description
Umb 10.6.1, Forms 10.4.0, on Linux Mint.

Clicking on a Form Picker's Edit or Open link results in being redirected to the Forms section with a blank form editing pane displaying a red error bar.

Reproduction
------------

### Bug summary

Clicking on a Form Picker's Edit or Open link results in being redirected to the Forms section with a blank form editing pane displaying a red error bar.

### Specifics

In a page with a Block Grid that has a Form Picker:-

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1143883/5f75af4d-dae1-4c47-88ae-979aa8aeb487)

Clicking on the Form Picker's Edit or Open links results in being redirected to the Forms section with a blank form editing page displaying a red error bar:-

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1143883/0baaa38b-aae5-4071-93e0-3f403f1decfa)

On investigation, there is no such path as `/App_Plugins/UmbracoForms/backoffice/form/entries.html`

### Steps to reproduce

Build a page docType, add a Form Picker. Build a Form. In the page select the Form and save it.
Click the Form Picker's Open or Edit link.

### Expected result
Form Section opens with selected Form open in edit mode in the right hand pane.

### Actual result

Form Section opens with empty right hand pane displaying the red error bar shown above with error message :
 
```
Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/backoffice/form/entries.html
```

**Comment by AndyButland** [comment]
Thanks for the report, but looks like this duplicates #1040 which we'll have fixed for the next release.

**Comment by craigs100** [comment]
I did have a quick look but didn't find anything. That's great. Thanks for letting me know.
