### ISSUE TITLE
Validation summary renders a message for each of the field (3 fields - 3 different validation message)

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco.Forms.Issues#1053]
Umbraco Forms version: 10.4.0 

When enabling the "Show validation summary" option you will get a validation message for each field you have rather than a single message. If you have 4 fields you'll get 4 messages. See video:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/83580347/99513e20-0cf9-4d46-b7ec-986e94fbd0ba)

https://github.com/umbraco/Umbraco.Forms.Issues/assets/83580347/87b135ac-785e-4bd9-993f-ee8f8e331cd5

The problem seems to be somewhere in the ASPNET client validation: https://github.com/haacked/aspnet-client-validation 

### Steps to reproduce

- Create a simple form with both single and multiple-choice types.
- Set the fields as mandatory 
- Make sure to enable the "Show validation summary"
- Render your form
- Try to submit only one of the mandatory fields without selecting anything on the other one
- You'll see the error

### Expected result
You only get one validation message not one for each field

### Actual result
You get several messages for each field you have in your form

---
_This item has been added to our backlog [AB#31464](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31464)_

**Comment by AndyButland** [comment]
Thanks @sergiutesu - as discussed, and just for the record here, it looks like this issue lies in the [client-side validation library we are using](https://github.com/haacked/aspnet-client-validation).  I'm going to see if we can resolve it there and submit a PR which, if accepted and included in a new release, we can take a reference on to resolve this for future Forms releases.

**Comment by AndyButland** [comment]
PR for the client-side validation library has been created [here](https://github.com/haacked/aspnet-client-validation/pull/57).

**Comment by AndyButland** [comment]
The upstream library has been updated now, and we'll take a dependency on version 0.8.13 for the next releases that will include this fix.
