### ISSUE TITLE
EnableAntiForgeryToken setting ignored in v10

### ISSUE THREAD

**Issue by steve-crook** [umbraco/Umbraco.Forms.Issues#1054]
Setting EnableAntiForgeryToken to false has no effect in Forms v10.4

Reproduction
------------

### Bug summary

The __RequestVerificationToken is being rendered in the form when EnableAntiForgeryToken is set to false. The setting is working correctly in Forms 11.2.

### Steps to reproduce

Clean install of Umbraco 10.6.1 and Forms 10.4. Add a new form and render it in a page template. Add the following to appsettings.json:

```
"Forms": {
  "Security": {
    "EnableAntiForgeryToken": false
  }
}
```

View the source of the page containing the rendered form and search for "__RequestVerificationToken".

### Expected result

The __RequestVerificationToken hidden input would not be rendered on the page.

### Actual result

The __RequestVerificationToken hidden input is rendered on the page.

**Comment by AndyButland** [comment]
Thanks for the report, but I'll need close this as we've had it reported before and have actioned as far as we can.  The setting in V10 only works to disable the validation of the antiforgery token, not to prevent it's output in the first place.

If you have a read through the [previously reported issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/859) there's some discussion in there as to why we were able to fully remove it only in V11+.
