### ISSUE TITLE
The scheduled record deletion service for Forms 11.2.0 won't enable despite being set in appsettings.json

### ISSUE THREAD

**Issue by ocodia** [umbraco/Umbraco.Forms.Issues#1055]
We've enabled the Scheduled Deletion Service for Umbraco Forms (package version 11.2.0) using appsettings.json:

```
"Forms": {
        "Options": {
          "ScheduledRecordDeletion": {
            "Enabled": true,
            "FirstRunTime": "",
            "Period": "1.00:00:00"
          }
        }
      }
```
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1395678/1e34ba03-a6eb-49e0-bbbd-24ade3726813)

But in the Umbraco Form settings, it still says: "The scheduled record deletion service is not currently enabled. These settings will not take effect until it is enabled and running."

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1395678/b0196574-c848-4131-9027-20fe6bd5373b)

**Comment by AndyButland** [comment]
It looks to me from your screenshot that the configuration isn't quite right - the "Forms" element should be a sibling of "CMS" and not a child element.

**Comment by AndyButland** [comment]
I'll close this as it looks like the above explanation should resolve your issue, please feel free to re-open if not.
