### ISSUE TITLE
JavaScript error when loading any form

### ISSUE THREAD

**Issue by MrJackWilson** [umbraco/Umbraco.Forms.Issues#1056]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

I'm getting a JavaScript error whenever I try to load a form or it's entries. I only get this error when pushing it to our live server, on my local build it works just fine. It complains of an undefined `currentUserId` variable. The only place I can find this variable in the forms code is in umbraco.forms.js. It is mentioned twice, lines 1349 and 1823. Both times are an assignment to the variable, although the type of variable, `var, let, const`, is not specified, which I think would only be an issue if `use strict';` is being used, which I don't think it is.

### Specifics

```
ReferenceError: currentUserId is not defined
    at controller.js:2:13
    at umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:159:454
    at m.$digest (umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:171:67)
    at m.$apply (umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:174:484)
    at HTMLAnchorElement.<anonymous> (umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:218:276)
    at HTMLAnchorElement.dispatch (umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:2:39997)
    at v.handle (umbraco-backoffice-js.js.vc13c1b50dfd976ea4a1d823dc284e637b3dd57e8:2:37968) 'Possibly unhandled rejection: {}'```

### Steps to reproduce

Unsure

### Expected result / actual result

_No response_

---
_This item has been added to our backlog [AB#31691](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31691)_

**Comment by AndyButland** [comment]
If it's working locally and not in another environment, a couple of things come to mind.

Could be caching - perhaps you had an earlier version installed and have now upgraded.  If that's a possibility please make sure you have fully cleared the cache via the configuration setting discussed [here](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html).

If you've upgraded from Umbraco 9, could also be [some files you need to remove](https://docs.umbraco.com/umbraco-forms/installation/version-specific#version-10) from your upstream environment before deploying.

**Comment by MrJackWilson** [comment]
I tried clearing the cache in all the ways. I even created an entirely new site on the server so I could publish a clean copy, the problem persisted. I then tried creating an near enough empty project with forms. I published it to the server and got the same problem.

I ended up getting around the problem by creating a dummy JS file which runs `window.currentUserId = -1;`. This then allows forms to set the variable as it pleases. I'm fairly certain the problem lies on the two lines that I mentioned above. Changing those to include `window.` should solve the issue I think.

**Comment by AndyButland** [comment]
OK, perhaps there's some sort of race condition going on then... then happens fast enough locally to not see the problem but it manifests itself in a deployed environment.  Will see if I can track it down.

**Comment by AndyButland** [comment]
What version of Forms are you running please?  I can see you've provided the CMS version, but would be useful to know the Forms version too.

**Comment by MrJackWilson** [comment]
Ah sorry, though I included that. It's 11.2.0
