### ISSUE TITLE
Default Theme errors prevent build

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#1057]
Umb 10.6.1, UF 10.4.0 Rider on Linux Mint

Adding the Umbraco Forms Default Theme from umbraco-forms-default-theme-10.5.0-c1.zip prevents build.

Reproduction
------------

### Bug summary

In an otherwise healthy, running project, added the folders "MacroPartials and "Partials/Forms" in the "View" folder and then attempted to build the solution. The build failed.

### Specifics

The build failed with the following 8 errors:-

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.Recaptcha3.cshtml(10,38): error CS1061: 'Recaptcha3Settings' does not contain a definition for 'Domain' and no accessible extension method 'Domain' accepting a first argument of type 'Recaptcha3Settings' could be found (are you missing a using directive or an assembly reference?) [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/ScrollToFormScript.cshtml(2,67): error CS1061: 'FormViewModel' does not contain a definition for 'PageHandled' and no accessible extension method 'PageHandled' accepting a first argument of type 'FormViewModel' could be found (are you missing a using directive or an assembly reference?) [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(54,39): error CS1061: 'FormViewModel' does not contain a definition for 'UseSemanticFieldsetRendering' and no accessible extension method 'UseSemanticFieldsetRendering' accepting a first argument of type 'FormViewModel' could be found (are you missing a using directive or an assembly reference?) [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(56,53): error CS1061: 'FieldType' does not contain a definition for 'RenderInputType' and no accessible extension method 'RenderInputType' accepting a first argument of type 'FieldType' could be found (are you missing a using directive or an assembly reference?) [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(56,73): error CS0103: The name 'RenderInputType' does not exist in the current context [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(58,42): error CS0103: The name 'RenderInputType' does not exist in the current context [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(77,42): error CS0103: The name 'RenderInputType' does not exist in the current context [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

```/home/craig/DotNetCoreSites/VC10/Web/Views/Partials/Forms/Themes/default/Form.cshtml(96,42): error CS0103: The name 'RenderInputType' does not exist in the current context [/home/craig/DotNetCoreSites/VC10/Web/Web.csproj]```

### Steps to reproduce

Download the latest V10 default theme from https://docs.umbraco.com/umbraco-forms/developer/themes.  Unzip the downloaded file umbraco-forms-default-theme-10.5.0-c1.zip 

In an otherwise healthy, running V10.6.1 project, add the folders "MacroPartials and "Partials/Forms" from the unzipped folder into the "View" folder and then attempt to build the solution.

### Expected result

Normal, error free build enabling work to progress to copy and rename default theme and modify as normal.

### Actual result

Build failed with the errors detailed above. Work stopped.

**Comment by AndyButland** [comment]
Hi @craigs100 - I think this is expected.  You've downloaded and are using the them for 10.5.0-rc1 and above, but are running 10.4.  So there are properties and other code constructs that the 10.5 theme templates are looking for that won't exist in 10.4.

You'd need to either upgrade Forms to 10.5.0-rc1, or, if you want to stay on 10.4, use the theme available for the highest version that's less than the version of Forms you have installed.

You've likely followed the link to the latest theme to obtain the files you have, but you can access older releases from the "Source Code" tab [here](https://our.umbraco.com/packages/developer-tools/umbraco-forms/).

**Comment by craigs100** [comment]
Hi @AndyButland, this is absolutely not expected, because I followed the instructions and V10 link in the docs here: https://docs.umbraco.com/umbraco-forms/developer/themes and that ends up downloading an RC version which is definitely a surprise when dealing with an LTS umbraco version. People use LTS's for reliability, i.e. not to be on the bleeding edge.  I would suggest that the link be changed to supply people with the correct latest working (i.e. non-RC) version of the required files. Maybe then add a sentence to point out that if RC versions are required for whatever reason then they are available at the link mentioned. The point being to try not to wrong-foot the innocent developer in docs that are there to help rather than hinder ;)

Thanks.

**Comment by AndyButland** [comment]
Will see what I can do to clarify.
