### ISSUE TITLE
File in form submission not accessible unless "Manage Forms" is enabled under user permissions. 

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco.Forms.Issues#1058]
### Bug summary

When a backoffice user tries to access an attached file in a Form submission, they are met with a 403 error instead of downloading the file, if they do not have "Manage Forms" enabled under their user permissions.

The "Manage Forms" enabled setting should not be the setting that is needed to download form entry files, it should be possible with "View Entries" enabled

Reproduction
------------
This was reproduced on a v11 (however it is an issue on 9,10,11,12.)

Steps to reproduce:
- Make form with a file upload property
- Fill out form with a file (pdf in my case)
- Setup your user under "Users -> Forms Security -> Your user" with following permissions (make sure Manage Forms is disabled):
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/54025229/e304d2e6-7949-4784-b025-4bc1f4ccee85)
- Go to the form entry you submitted
- Click on the file submitted
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/54025229/28b0855e-1fe8-4bca-8075-df608daf1bf9)
- See 403 unauthorized screen.

- After confirming that, enable "Manage Forms"
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/54025229/de7ce385-fda9-40db-a056-f3f17f95f023)
- Go to the form entry again
- Click on file submitted
- Downloads successfully now.

### Specifics

This is a general Umbraco Forms issue, no specific url needed.
- Version Forms 11.2.0
- No error message, just a 403.
"Access to [site].euwest01.umbraco.io was denied
You don't have authorization to view this page.
HTTP ERROR 403"

### Expected result

When clicking on the file submitted in the forms entry, the user should be able to download the file.

Expected result would be access to the file in the forms submission within the Backoffice.

### Actual result

Gets directed to a page saying "You don't have authorization to view this page." instead.

---
_This item has been added to our backlog [AB#31748](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31748)_

**Comment by bjarnef** [comment]
@AndyButland I think there were another related issue fixed in autumn 2024 as our client had issues accessing files uploaded on form entries.

However with Umbraco 12.3.10 and Forms 12.2.4 it seems it is still an issue.
I recall it was something related to the auth cookie set as it no issue when logged in as admin.

**Comment by AndyButland** [comment]
This one maybe? https://github.com/umbraco/Umbraco.Forms.Issues/issues/11#issuecomment-2376788751 Fix was in 13.2.

**Comment by bjarnef** [comment]
@AndyButland thanks. Yes exactly. My search skills could find that one 😅 and a have submitted too many issues 🙈

Okay, you just mentioned:

> Yes, it looks like it. I can see we are doing something similar to the original code in the middleware used to protect the media requests here. Will have a look for the next patch releases.

But it seems it hasn't been included in Forms v12 release then, but only v13? Would it be possible to include in v12 of Forms?

**Comment by AndyButland** [comment]
Sorry, but I'm afraid Umbraco (and Forms) 12 are EOL from June last year, so we aren't planning to release any more updates for that.  Would be best to upgrade to the 13 LTS if you can.

**Comment by bjarnef** [comment]
Okay, so it would require to upgrade to Umbraco 13 as well right? :)
