### ISSUE TITLE
Disable HTML5 validation of name input

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#106]
Disable HTML5 validation of name input and use Angular validation.

For form name input it does seems to use Angular validation.

![image](https://user-images.githubusercontent.com/2919859/53944878-93dacf80-40c0-11e9-9d76-64a0eba5dca0.png)

But on datasources and prevalue sources it don't, but use HTML5 validation.

![image](https://user-images.githubusercontent.com/2919859/53945109-22e7e780-40c1-11e9-9a41-adfe667d63b1.png)

![image](https://user-images.githubusercontent.com/2919859/53944991-d8666b00-40c0-11e9-8dea-b3248d374919.png)

**Comment by bergmania** [comment]
PR https://github.com/umbraco/Forms/pull/253
