### ISSUE TITLE
Missing method after upgrade from 8.6

### ISSUE THREAD

**Issue by mhughes668** [umbraco/Umbraco.Forms.Issues#1061]
After upgrading from Forms from 8.6 to 8.13.8 I have an error in  UmbracoFormsExtensionsController.cs

"The name 'GoForward' does not exist in the current context"

I have compared the file between the 8.6 and 8.13.8 versions and they are the same - has the reference to 'GoForward' changed?

code for UmbracoFormsExtensionsController came from here - https://gist.github.com/lars-erik/7a0028f28b93385574b68ce11276bd7a

The only change that was made was upgrading from 8.6 forms to 8.3 forms using nuget. If I go back to 8.6 then I get no errors and the website works fine.

<img width="189" alt="goforward2" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/0ff1e574-61f2-4fc7-bdb7-a2f42881b928">

<img width="309" alt="goforward" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/79652e4f-8979-4ce2-9ba0-c95ae7f547ca">

---
_This item has been added to our backlog [AB#31793](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31793)_

**Comment by AndyButland** [comment]
It looks like this was made `private` as opposed to `protected` back in `8.7`.  It shouldn't have been as that's a breaking change, so we can look at reverting this.  It's a bit inconsistent as `GoBackward` is `private` in 8.6, so I can see why it got tidied up, but that change should have waited for the next major version.
