### ISSUE TITLE
Columns of Forms Entries

### ISSUE THREAD

**Issue by petr-vojtech** [umbraco/Umbraco.Forms.Issues#1062]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

The **Fields displayed** option is missing in the form settings for Umbraco Forms 10.4.0
According to the documentation
https://docs.umbraco.com/umbraco-forms/v/10.forms.latest/editor/creating-a-form/form-settings#fields-displayed
3 fields should be set for the Entries list.

### Steps to reproduce

Create form and try to set option by documentation.

### Expected result / actual result

The **Displayed fields** option will be displayed in the form settings.

**Comment by AndyButland** [comment]
I can't replicate this when looking into the issue I'm afraid.  Is it possible you have upgraded from an earlier version and might need to clear the backoffice cache?  There are some details of how to do that [here](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html).

**Comment by petr-vojtech** [comment]
My **appsettings.json**
<pre>
      "RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Timestamp"
      }
</pre>
My **appsettings.Development.json** - it is without Displayed fields option
<pre>
      "RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Version"
      }
</pre>
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/81760128/24ecb05b-110b-4660-8eb7-7f38e764985c)

My **appsettings.Staging.json** - it is with Displayed Fields option but I can't change it
<pre>
      "RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Version"
      }
</pre>
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/81760128/ae72b401-a388-4f2c-922d-cd1a02567831)

My **appsettings.Production.json** - it is without Displayed fields option
<pre>
      "RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Version"
      }
</pre>
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/81760128/0afe1637-63bf-47c7-9421-a98ab2aacb25)

It is not necessary to specify the "Version" configuration option according to the documentation:
https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/runtimeminificationsettings
What is wrong?
Thank you for your help.

**Comment by AndyButland** [comment]
I've found when packages are updated you can end up with cached versions of files, so it's certainly useful to set, at least to isolate caching from being an issues.  It's not necessary for CMS upgrades - as the CMS version is included in the cache hash value - but that doesn't take account of package upgrades.

I'm not 100% sure this is the problem but it's odd you are seeing different things in different environments, so please could you try providing a `Version` number to manually clear the cache (as discussed [here](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/runtimeminificationsettings#manually-changing-the-cache-buster-version))?

**Comment by petr-vojtech** [comment]
I changed all my appcongigs to recomended values, but nothing has changed for the better
<pre>
      "RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Version",
        "Version": "1235"
      },
</pre>

**Comment by AndyButland** [comment]
OK, so doesn't seem to be caching related.  I've just checked the logic for display of this element and can see we hide it if you don't have the "Store records" option checked (the option at the top of the "Settings" page).  Is that it perhaps - that you have this switched off for the form you are looking at?

We don't show the option for fields then as there's nothing to see on the "Entries" page anyway.

**Comment by AndyButland** [comment]
No problem, glad you got it sorted.
