### ISSUE TITLE
The score cannot be controlled in the reCAPTCHA V3 form question

### ISSUE THREAD

**Issue by petr-vojtech** [umbraco/Umbraco.Forms.Issues#1063]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

The reCAPTCHA V3 question for forms 10.4.6 still has score value control disabled.
I tried changing the settings as per the documentation
https://docs.umbraco.com/umbraco-forms/v/10.forms.latest/developer/configuration#settingscustomization
but the new default or IsReadOnly doesn't work either
<pre>
  "Forms": {
    "FormDesign": {
      "SettingsCustomization": {
        "FieldTypes": {
          "recaptcha3": {
            "ScoreThreshold": {
              "DefaultValue": "0.8",
              "IsReadOnly": false
            }
          }
        }
      }
    }
  }
</pre>

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/81760128/a5aac906-1c65-47df-9800-3fa4033cce8d)

### Steps to reproduce

Add a reCAPTCHA V3 question to the form and try to change the score value

### Expected result / actual result

The score for the reCAPTCHA V3 question will be activated for setting a value other than the default 0.5

**Comment by AndyButland** [comment]
I'm afraid that like with the last issue you reported I can't replicate with the latest Forms code.  Might again be a caching issue if you've upgraded, so let me know if clearing that solves it.  Otherwise maybe you can see something in the browser dev tools console that will give a clue as to what's happening here.

**Comment by petr-vojtech** [comment]
Production - Umbraco Forms 10.2.1
Staging - Umbraco Forms 10.4.0
I've tried and sent screenshots from production where it's not the latest version :-(
Corrections can be seen in the notes for individual versions:
https://docs.umbraco.com/umbraco-forms/release-notes
Sorry, my mistake, version 10.4.0 works as it should.
Thank you for your help
