### ISSUE TITLE
Field icon is too small

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1065]
I noticed the field icon seems to be a bit too small.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/6e40b170-d899-48a8-827f-e0c9ef1626f0)

Also the "button" elements should be a `<button type="button">` instead of `<a>`.

Eventually the newly changes made in CMS for properties or add `umb-node-preview__icon` class to the icon wrapper.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/143bd456-bd76-48b5-89f0-2c0a6bac01d0)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/4b216948-44a6-47d3-94ab-726d432bf8ab)

Umbraco 12.1.0
Umbraco Forms 12.0.0

**Comment by AndyButland** [comment]
Thanks @bjarnef - I'll add this class for the next patch release, can confirm that increases the size of the icon which looks better and more consistent.
