### ISSUE TITLE
Form anchoring upon form submission

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#1066]
At the moment when you submit a form you are taken to the top of the page, rather than to the part of the page where the thank you message appears.

It would be great if we could have something like [Form anchoring in Next & Previous buttons](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1037) for form submission please.  Upon submission you'd be scrolled to the thank you message.

---
_This item has been added to our backlog [AB#32140](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32140)_

**Comment by AndyButland** [comment]
Are you on the latest version @richarth?  As that should be in place, as it's part of the issue you linked to.

The scroll feature is looking for an element with one of the following classes, and should be scrolling to that: `umbraco-forms-submitmessage-html` or `umbraco-forms-submitmessage`.  So if you aren't using the default theme, might be you'll need to introduce those classes into your `Submitted.cshtml` partial view.

**Comment by richarth** [comment]
Thanks for the response @AndyButland.  I can confirm that we are on the latest version, I upgraded yesterday as we needed the previous/next anchoring.

We've grabbed a few of the files from the default theme and customised them but we are largely relying on the default theme.  Our `Forms.cshtml` file has `@await Html.PartialAsync("Forms/Themes/default/ScrollToFormScript")` in it.

I can confirm that when you submit a form the markup has `umbraco-forms-submitmessage` on the span wrapping the thank you message.

I can see that in `/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.min.js` there are references to `umbraco-forms-submitmessage-html` and `umbraco-forms-submitmessage`, I presume that is the JS for the scrolling.  I did notice that `umbracoforms.min.js` isn't included on the thank you screen, so I'm suspecting that's where the problem is.  We don't have our own version of `Submitted.cshtml`, we're relying on the default version.

**Comment by AndyButland** [comment]
Which option are you using for post-submission behaviour please @richarth?  I.e. "Message on submit" or "Go to page" from here:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/c957642a-f50a-473b-a1a5-4c37c325aecf)

**Comment by richarth** [comment]
We're using message on submit and leaving the message as HTML.  Thanks @AndyButland.

**Comment by richarth** [comment]
Thanks @AndyButland .
