### ISSUE TITLE
Impossible to create form when using screen reader

### ISSUE THREAD

**Issue by plannero** [umbraco/Umbraco.Forms.Issues#1067]
### Bug summary
With Umbraco v10.4.0 I find it impossible to use Umbraco Forms when I depend on a screen reader (necessary for people with reduced or no eyesight). 

### Specifics
Reason: The entire area where I am supposed to edit my form field (including several input fields and buttons and labels) is coded with `role="button"`. Because of this, my screen reader refuses to access the content of this area. This reaction from the screen reader is reasonable, since buttons are not supposed to CONTAIN other interactive elements.

<img width="932" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/2157085/f3fd2aed-4fc5-45a3-a3b1-0a27a6ebdd94">

### Proposed fix

Change from `role="button"` to `role="group"` and move button logic to a true button.

---
_This item has been added to our backlog [AB#32131](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32131)_

**Comment by AndyButland** [comment]
Thanks for reporting this issue.  We'll update that attribute and release the fix as part of the next round of patch releases.
