### ISSUE TITLE
Cannot delete form records programmatically in background job

### ISSUE THREAD

**Issue by JensDueO** [umbraco/Umbraco.Forms.Issues#1069]
### Bug summary

When trying to delete form records in a (Hangfire) background job, IRecordService.Delete() throws a httpContext null reference exception.

The problem was fixed in version 9.x in issue #779, but I am running forms version 8.13.7.

Reproduction
------------

When trying to delete form records in a (Hangfire) background job, IRecordService.Delete() throws a httpContext null reference exception. The method Delete takes two parameters; a form and a record, and both parameters are valid (and not null).
See stack trace below for more information.

### Specifics

Forms version 8.13.7
Calling IRecordService.Delete()

### Steps to reproduce

Call IRecordService.Delete() from a Hangfire task

### Expected result

Record is deleted

### Actual result

Throws exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: httpContext

Call stack:
   at System.Web.HttpContextWrapper..ctor(HttpContext httpContext)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode)
   at Umbraco.Forms.Core.Services.RecordService.Delete(Record record, Form form)
   at Brand.Energy.Core.Repositories.UmbracoFormsRepository.DeleteRecord(Form form, Record record) in Brand.Energy.Core\Repositories\DeleteFormReceiptRepository.cs:line 31

### Possible fix

In may 2022, you fixed the issue in version 9.4.2, but out solution is running version 8.13.7.

Look in issue #779 : Cannot delete form records programmatically in background job.

The old issue was handled by @AndyButland 

---
_This item has been added to our backlog [AB#32180](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32180)_

**Comment by AndyButland** [comment]
It looks like a related issue, but not quite the same.  In this case we are getting an exception in the processing of workflows that trigger on the delete of a record when not running within an HTTP context. Looks like we can apply a similar fix though.

**Comment by JensDueO** [comment]
Wow! That is fast bug-fixing. Less than an hour from I opened the issue, to a fix is added, and the issue is closed. Thanks.

**Comment by AndyButland** [comment]
Well, we still need to release it... but you can expect that with the next patch releases, likely in a couple of weeks.
