### ISSUE TITLE
Form Field Picker for current edited form

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#1071]
Hi!

I have a request for a feature that I think would benefit editors a lot when it comes to configuration of Workflows. Workflows often need to know about fields in form, for example when you want to send confirmation to a email entered in a form you could do something like this:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/138cba6f-50b7-43bf-b8d1-fb1b36b7ccfc)

While this works it's not super friendly for the editors. We have hacked together a dropdown that lists the fields from the form to make this experience more intuitive for our editors:

![2zJHBwTXep](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/496e3f58-4c3f-4474-9c73-c88a8d57f82d)

Here we're listing the fields from the form and providing a nice picker.

My idea here is that Umbraco Forms could be shipped with a field where the editor can choose between a constant value or a field, it could look something similar to this but will only "Constants" and "Field" as tabs:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1782524/0a4ac822-6941-411f-a7b4-2b2da2824267)

We have a working solution for this at the moment but with the new backoffice coming up where it's probably going to be harder to create "hacks" like this I wanted to raise this issue to see if HQ would be open to either shipping the field it self or making sure that the data is available so that package devs can create a picker like this.

We built this picker some years ago but feel free to let me know if you would like to see the source code, I'm happy to share and for you to use the code in the product.

Cheers!

---
_This item has been added to our backlog [AB#32729](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32729)_

**Comment by AndyButland** [comment]
Sounds a nice ideal @enkelmedia - I agree the "magic strings", whilst quite powerful, aren't the easiest of things to make intuitive to select.  If you are happy to contribute the code then I'm sure that would give us a good start with this.  Please feel free to mail it to abl AT umbraco DOT dk. And thank you very much (for suggestion and contribution).

**Comment by AndyButland** [comment]
This will be available for use by developers of custom workflows in the next release.

**Comment by enkelmedia** [comment]
Great news! =D
