### ISSUE TITLE
RenderUmbracoFormDependencies should allow you to specify additional attributes on the script tag (async/defer)

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco.Forms.Issues#1074]
RenderUmbracoFormDependencies currently just appears to produce hardcoded JS. I need to be able to specify async/defer attributes on these script tags, which currently is not possible.

Would it be possible to modify this method to allow specifying additional attributes on the script tags?

---
_This item has been added to our backlog [AB#32726](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32726)_

**Comment by umbracotrd** [comment]
We've added an overload to `RenderUmbracoFormDependencies` allowing you to provide these or other attributes for the script renderings. You'll find this available in the next minor release, which is expected to be `12.2.0`.

Please note too that when testing the results of this, we found a race condition with the check that Forms does to ensure a client-side validation framework is in place, and the forms dependency scripts when they have the `async` attribute added. On first request you would usually see this:

`Umbraco Forms requires a validation framework to run, please read documentation for posible options.`
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/145000730/5eb715a6-e2c0-4c83-885b-400a6c7e38b8)


Which goes away on a refresh as the browser has the dependency scripts cached.

To resolve this, we've added a configuration option to disable this check, which you will be able to do by setting the value of `Umbraco:Forms:Options:DisableClientSideValidationDependencyCheck` to true. For example:
```
"Umbraco": {
  "Forms": {
    "Options": {
      "DisableClientSideValidationDependencyCheck": true
    }
  }
}
```
