### ISSUE TITLE
Form fields set to receive only numeric input will accept the character "e".

### ISSUE THREAD

**Issue by LinearSix** [umbraco/Umbraco.Forms.Issues#1075]
Form fields set to receive only numeric input will accept the character "e".

### Bug summary

I have set up the field "Number of Employees" to expect numeric content and also selected the validation to "Validate as a Number" (^[0-9]*$), but the field allows a lowercase "e" to be entered in that field.

https://qa-get.nfp.com/scma-health-plan/

### Steps to reproduce

Go to page:
https://qa-get.nfp.com/scma-health-plan/

In the field "Number of Employees", type "e".

### Expected result

No letters should be entered

### Actual result

Letter "e" can be entered.

![e](https://github.com/umbraco/Umbraco.Forms.Issues/assets/39229698/22447e63-ce17-4b0a-b22c-08c9b2fec6c9)

**Comment by AndyButland** [comment]
That's an interesting one certainly, but I had a read up and can see why it's happening.  As well as applying a regular expression you've also set the "type" attribute to "number".  By doing that, the regular expression isn't being used, as the type of output considered client-side is a number, not a string, to which regular expressions don't apply.  Hence this is being ignored.

So the validation you do see client-side comes from the `type="number` setting on the form field.  That limits inputs to numbers, and, "e", [is actually a number](https://stackoverflow.com/a/31706796, so it does allow "e" to be entered.

In Chrome at least, even with JavaScript off, I do get a message shown when trying to submit the form, so you still can't enter an "e" value.  So there's something running later at least in that browser that blocks it.

And were I able to submit, server-side validation should also block it.

So all in all I don't think there's anything feasible we can do in Forms itself to get around this I'm afraid, and given the validation does at least run later in the rare case of a user attempting to enter this value, will have to put it down to slightly counter-intuitive browser behaviour.

**Comment by c9mb** [comment]
@AndyButland The issue appears to be one of Mask vs. Validation.
If there was the option to create an Input-Mask using regex, then perhaps it may have a chance of working ?
i.e. Stop 'e' from being entered in the first place, rather than relying on validation when submitting.
