### ISSUE TITLE
Cant export data on forms

### ISSUE THREAD

**Issue by EPDA-parky** [umbraco/Umbraco.Forms.Issues#1077]
What version you are running?
7.15.10

Specifically what you are doing to trigger the issue?
Trying export form entries

What might we need to replicate the issue?

Click on Export
Select format
Click Done

It should export a spreadsheet but it isnt.

Are there any errors reported in the logs or browser console?
No errors

**Comment by AndyButland** [comment]
I can see an error come up in the browser console when you click on the format you want.  It contains the following:

```
Could not load file or assembly 'EPPlus, Version=4.0.5.0`
```

It looks like you might be missing a dll file that should be in the `bin` folder of your Umbraco website.

If you have installed from NuGet this should be brought in, but perhaps it's been omitted.  You can see the version of Forms you are running [depends on a package called EPPlus](https://www.nuget.org/packages/UmbracoForms.Core/#dependencies-body-tab), which should provide that dll.

We also ship it with the zip file that you can get from [this URL](https://our.umbraco.com/packages/developer-tools/umbraco-forms/) - download the file called `UmbracoForms.Files.7.5.10.zip` and you'll find `EPPlus.dll` within that.

**IMPORTANT:** please note that you have shared the backoffice login for your website now on a public forum.  I've removed it now, but I'd suggest you change the password immediately.

**Comment by AndyButland** [comment]
It's there, I've just double-checked.

- Download the file `UmbracoForms.Files.7.5.10.zip` from https://our.umbraco.com/packages/developer-tools/umbraco-forms/ (you need to scroll down to the bottom).
- Open it and expand the `bin` folder
- In there is the file `EPPlus.dll`.

You should check to see if it's not already in your website's "bin" folder - I'm assuming not, but worth double-checking.

If not you should ensure it is - ideally via whatever means you normally use for deploying updates to your site in production.

**Comment by EPDA-parky** [comment]
Hi I still cant see it: 
<img width="493" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/92502473/a41f9a2a-cd7f-42df-b917-ad82ea0fc679">

**Comment by AndyButland** [comment]
Closing this now given no further discussion.
