### ISSUE TITLE
Workflow name input should be full width

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco.Forms.Issues#1079]
When using 11.1.3 I'd expect editing workflow would have the name field full with like other input fields.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/3933562/2a209cdc-2b83-4534-ba4d-27864bc7b71f)

However it's narrow making it difficult to read/edit.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/3933562/b270fb52-d813-4577-905a-b30fbaa87772)

---
_This item has been added to our backlog [AB#32723](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32723)_

**Comment by AndyButland** [comment]
This UI update will be included in the next round of patch releases.
