### ISSUE TITLE
Add Options to Workflow Conditions (Does Not End With, Does Not Contain)

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco.Forms.Issues#1081]
Umbraco Forms 10.5.0. Umbraco 10.6.1.

Currently, you can add conditions to a workflow to prevent it from running if certain conditions are met:

<img width="360" alt="existing-conditions" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/5933222/5e945b87-2128-4a76-8cb7-d08117138d2c">

My request is regarding the options available in that drop down. It would be ideal if "does not contain" and "does not end with" were options.

The use case is that I'm trying to do something like this:

<img width="542" alt="new-conditions" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/5933222/b03149dd-e43b-4bd3-a3bd-9c5f0c06f5fc">

In essence, preventing an email workflow from running if a given email is part of a specific domain. Side note: this only really works if these comparisons are case-insensitive, so that's another factor to keep in mind (otherwise, somebody can enter their email as "mclovin@SuPeRbAd.com" to bypass these conditions).

Note that I already have a way to achieve something similar using session variable magic strings, but that adds a fair amount of work (and has quirks), so in the long term this simple change could be useful to many to reduce custom code.

---
_This item has been added to our backlog [AB#32728](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32728)_

**Comment by tedlindholm** [comment]
Wouldn't it be great if you could manipulate the list (dropdown) by code? Just as you can with, for example,  field types. A composer class with add and exclude for "comparisons"... 
I get a feeling that the code for conditions UI are way older/less modern than the rest of Forms. Keeping my fingers crossed for some amazing upgrades with the upgrade to upcoming non angular solution.

**Comment by AndyButland** [comment]
We've added a few more options to the operator list that will be available from the next release.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/1064745e-bb4d-4ad5-865b-a7870e436b2f)
