### ISSUE TITLE
Make it possible to set PickAday ariaLabel

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Forms.Issues#1082]
Umbraco Forms: 10.2.1
Umbraco: 10.6.1

When working with Umbraco DatePicker fields the areaLabel isn't configurable and always displays 'Use the arrow keys to pick a date'.
Pickaday support setting the labelon init when calling `new Pikaday({ ariaLabel: "Custum label" });`
Details: https://github.com/Pikaday/Pikaday#configuration

Right now I updated the DatePicker.cshtml to use my own implementation of `~/App_Plugins/UmbracoForms/Assets/datepicker.init.js` so I can set the areaLabel myself.
Would be great if Umbraco would made this possible out of the box the same way as how the `umbracoFormsLocale` are working.
In my code i've injected an hidden input value coming from Umbraco's dictionary and get the hidden input by Id inside init.js file.

Possible solutions:
- Use dictionaryvalue for multi lingual setting of areaLabel
- Use UmbracoForms.config for multi lingual setting of areaLabel

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/95cacc8d-23dc-4431-a4fb-fc37901979f2)

**Comment by AndyButland** [comment]
We'll include this as a new setting available on the date picker field type in the next round of releases.
