### ISSUE TITLE
Validation remembered when changing answer  type

### ISSUE THREAD

**Issue by teacs** [umbraco/Umbraco.Forms.Issues#1083]
### Bug summary

If editor has a question type e.g. Short Text with validation and then change the type to Dropdown validation is remembered.

But it's not possible to clear validation on dropdown.

### Specifics

Umb. version: 10.4.2
Forms version: 10.2.4. 
Browser: Chrome

### Steps to reproduce

1. Create a short text field
2. Insert validation
3. Save
4. Change answer type to e.g. Dropdown
5. Save
6. Try to insert form on page. It's not possible to submit because form cannot validate

We fixed it the following way, after a lot of debug:
1. Open up dropdown field
2. Change answer type back to short field
3. Remove validation
4. Change back to dropdown (All entries has thankfully been remembered)
5. Save

### Expected result

I'd expect when changing answer type validation would be removed if validation is not possible.

### Actual result

When going to the database and checking table **dbo.UFForms** we could see the following regex for the dropdown field.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/36918114/42baf04b-39e1-4f16-adf4-79a18c5c3b4f)

And as you can see here it's not possible to change validation directly on the field:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/36918114/411e2146-a25c-4406-bc62-508de2831dad)

---
_This item has been added to our backlog [AB#33487](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33487)_

**Comment by AndyButland** [comment]
Thanks for reporting this along with the clear reproduction steps.  We've resolved this now by adding a check when the field type is changed, that if the new field type doesn't support pattern validation, any existing pattern and message will be removed.

This will be included in the next round of patch releases.
