### ISSUE TITLE
Short text of type time can't be used in a condition rule

### ISSUE THREAD

**Issue by geoffbeaumont** [umbraco/Umbraco.Forms.Issues#1084]
A condition rule which targets a short text field of type time (i.e. an HTML input with the type attribute set to "time") won't work - it will always return a match.

The reason for this is simply that time is missing from the list of type attributes in the front end JavaScript which gathers field values for use in conditions, so the value is never added to the scope.values object. The condition checking code then fails to a positive result when finding no matching value.

Reproduction
------------

Create a field of type Short text, set the type of this to "time".
Create a second field of any type and enable conditions, setting to "Show" and "all", then add a rule targetting the time field (e.g. time IsNot empty string).

The second field will be displayed regardless of the value of the time field. It should be shown only when a time is set.

Fix
---
This only requires the addition of one line of JavaScript, in umbraco.forms.staticassets /staticwebassets/Assets/themes/default/umbracoforms.js (at line 507 in version 12.1.0):

Existing code:
`if (field.getAttribute('type') === "text" ||
                    field.getAttribute('type') === "number" ||
                    field.getAttribute('type') === "email" ||
                    field.getAttribute('type') === "url" ||
                    field.getAttribute('type') === "tel" ||
                    field.getAttribute('type') === "date" ||
                    field.getAttribute('type') === "datetime-local" ||
                    field.getAttribute("type") === "hidden") {
                    formValues[field.getAttribute("id")] = field.value;
                    dataTypes[field.getAttribute("id")] = "text";
                }`

Needs to be:
`if (field.getAttribute('type') === "text" ||
                    field.getAttribute('type') === "number" ||
                    field.getAttribute('type') === "email" ||
                    field.getAttribute('type') === "url" ||
                    field.getAttribute('type') === "tel" ||
                    field.getAttribute('type') === "date" ||
                    field.getAttribute('type') === "datetime-local" ||
                    field.getAttribute('type') === "time" ||
                    field.getAttribute("type") === "hidden") {
                    formValues[field.getAttribute("id")] = field.value;
                    dataTypes[field.getAttribute("id")] = "text";
                }`

Alternatively, might be more future proof to exclude types (radio, checkbox) that are handled elsewhere?

**Comment by AndyButland** [comment]
Thanks for the report @geoffbeaumont, as well as finding the fix!  I can replicate the issue and confirm your suggestion will resolve it.

This will be in the next round of patch releases.

**Comment by geoffbeaumont** [comment]
That was quick! Thanks @AndyButland
