### ISSUE TITLE
Mandatory date field fails even if value entered

### ISSUE THREAD

**Issue by mhughes668** [umbraco/Umbraco.Forms.Issues#1085]
When I have an answer which is type "Date" on a form which is marked as mandatory, when filling out and submitting the form, even if the date field is populated, the mandatory error message pops up when I submit. If I do not alter the form and hit submit again, it works and the form is submitted.

Specifics - Umbraco Forms v.8.13.11

Steps to reproduce
Add an "answer" of type "Date" to a form.
Mark the "answer" as "Mandatory"
Fill in the form, add a value to the date field and submit the form
The mandatory validation will display the error message

Expected result
Form will submit

Actual result
The mandatory validation will display the error message even though the field has been populated

<img width="204" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/ccdbdd8d-b8e9-4e7c-9787-4e39de54f1a0">

<img width="388" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/9b166060-b365-4a1f-84d7-6c872ba9ddba">

---
_This item has been added to our backlog [AB#33093](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33093)_

**Comment by AndyButland** [comment]
We'll investigate, but first could you confirm if this is using the built-in date field please, or a custom one (from your own solution or a package)?  It's just what you've shown there doesn't look like the UI of the default date picker.  Thanks.

**Comment by mhughes668** [comment]
Thanks.

It's a custom field which is supposed to take mm,yyyy.

We also have one for dd,mm,yyyy.

I can share the code for the field if it helps?

It was working with forms 8.6 but has stopped working after upgrading to 8.13.11


Thanks,

Mary

**Comment by AndyButland** [comment]
OK, it's probably related to an update in the third-party client validation library that's occurred between the versions you have migrated between.  If you could share the code for your custom field we could take a look.  You can send it to me at _abl AT umbraco DOT dk_ if you prefer not to share it publicly here.

**Comment by mhughes668** [comment]
Thank you very much for this.

I will have a go now.


Kind regards,

Mary

Mary Hughes | Senior Consultant
Managed Services
Avanade UK&I
3 Godalming Business Centre, Woolsack Way, Godalming, GU7 1XW
Direct: (+44) 7585 701570
www.avanade.com<http://www.avanade.com/>

***@***.***

Advance Leave Notice:
18.08.23 - 22.08.23
29.08.23 - 30.08.23

At Avanade, we work flexibly. There is no expectation for you to read, respond or otherwise act on this email outside of your regular work hours.

**Comment by mhughes668** [comment]
Thank you - that has resolved it.
