### ISSUE TITLE
Roadmap for Umbraco FORMS and improvements suggestions

### ISSUE THREAD

**Issue by Marco-Rinia** [umbraco/Umbraco.Forms.Issues#1087]
Dear Umbraco FORMS support,

Is there a roadmap 2024 for Umbraco FORMS with further development functionalities and improvements available?

1. It would be very nice if, for example, new fields and functionality became available to create a form for booking events with dates and time slots that can be set in advance. 

2. It would also be useful if, for example, a selection field (drop down/radio buttons) had additional text displayed under or above and/or a tooltip field notification. 

3. Toggle buttons fields and/or multi-step forms would also be very cool.

4. I think being able to assign a separate workflow to a separate field could also be a nice addition.

5. FORMS securuty acces - select all of the  assigned forms to a user in one click (toggle enable/disable) or something. 
More efficient than manualy toggle all forms on/off for a user. 

Perhaps you can benefit from my product improvement ideas/suggestions.

I would like to hear your response.

Greetings,

Marco

**Comment by AndyButland** [comment]
Hi Marco -as and when we have larger things in the works, we publish them on the common Umbraco product roadmap [here](https://umbraco.com/products/knowledge-center/roadmap/).

We're also happy to accept feature requests via this issue tracker - though it's more useful if there can be one per request, so we can track progress and keep any discussion limited to a specific feature request.  Feel free to that with your suggestions if would like to, and perhaps you can flesh them out a little more.

I'll just note in case you weren't aware, it's possible to [create your own custom fields](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype) - either for your own solution or even to create as a package.  So even if we don't get to building a specific type of field as part of the core product, there are extension points so you aren't limited by what's shipped with the product itself.

I'll close this issue as hopefully I've answered your questions, but, as I say, if you would like to progress any of your suggestions that you think have general use for Forms customers, please feel free to create them as individual issues on the tracker.

**Comment by Marco-Rinia** [comment]
Hi Andy,

Thanks for your fast respond.

I have made 5 feature request FORMS in the issue tracker.

https://github.com/umbraco/Umbraco.Forms.Issues/issues/1093
https://github.com/umbraco/Umbraco.Forms.Issues/issues/1092
https://github.com/umbraco/Umbraco.Forms.Issues/issues/1091
https://github.com/umbraco/Umbraco.Forms.Issues/issues/1090
https://github.com/umbraco/Umbraco.Forms.Issues/issues/1088

Regards,

Marco

Van: Andy Butland ***@***.***>
Verzonden: vrijdag 22 september 2023 12:31
Aan: umbraco/Umbraco.Forms.Issues ***@***.***>
CC: Marco-Rinia ***@***.***>; Author ***@***.***>
Onderwerp: Re: [umbraco/Umbraco.Forms.Issues] Roadmap for Umbraco FORMS and improvements suggestions (Issue #1087)


Hi Marco -as and when we have larger things in the works, we publish them on the common Umbraco product roadmap here<https://umbraco.com/products/knowledge-center/roadmap/>.

We're also happy to accept feature requests via this issue tracker - though it's more useful if there can be one per request, so we can track progress and keep any discussion limited to a specific feature request. Feel free to that with your suggestions if would like to, and perhaps you can flesh them out a little more.

I'll just note in case you weren't aware, it's possible to create your own custom fields<https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype> - either for your own solution or even to create as a package. So even if we don't get to building a specific type of field as part of the core product, there are extension points so you aren't limited by what's shipped with the product itself.

I'll close this issue as hopefully I've answered your questions, but, as I say, if you would like to progress any of your suggestions that you think have general use for Forms customers, please feel free to create them as individual issues on the tracker.
