### ISSUE TITLE
Feature: payment field to add a form connection with a PSP like Mollie, Stripe etc

### ISSUE THREAD

**Issue by Marco-Rinia** [umbraco/Umbraco.Forms.Issues#1091]
Payment field to add a form connection with a PSP like Mollie, Stripe etc to make a order and complete payment process

**Comment by AndyButland** [comment]
I will close this one as I don't think we will be adding provider specific payment features to Forms itself.

We have previously released an integration with a payment provider - emerchantpay - that might give inspiration for anyone tackling a similar task with this or other providers.
