### ISSUE TITLE
Feature: FORMS security access - select/deselect all of the assigned forms to a user in one click

### ISSUE THREAD

**Issue by Marco-Rinia** [umbraco/Umbraco.Forms.Issues#1092]
FORMS securuty acces - select all of the assigned forms to a user in one click (toggle enable/disable) or something.
More efficient than manualy toggle all forms on/off for a user.

---
_This item has been added to our backlog [AB#33503](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33503)_

**Comment by AndyButland** [comment]
We've added a toggle for this that will be available in the next feature release.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/00c8fc95-0e8e-455e-bba0-f384b2a06674)
