### ISSUE TITLE
All forms are missing after updating to version 10.4.0

### ISSUE THREAD

**Issue by karlmacklin** [umbraco/Umbraco.Forms.Issues#1094]
When updating for Umbraco.Forms version 10.4.0 from any previous version between 10.2.0 and 10.4.0 all our forms disappear from the sidebar view.

From what we can tell in the database columns everything looks the same after the update, and we see the forms there in the dbo.UFForms table.

If we have a direct url to a form (copied when using the previous version of forms) we can still open and edit specific forms.
So it's "just" the listing of forms in the backoffice view that is broken.

Reproduction
------------

I cannot reproduce this in a fresh install, only with our client's database.
Copying our clients database to a local environment and updating Forms from 10.2.0 to version 10.4.0 triggers this effect.
At that point no forms are listed under the Forms section. So something specific happens at that version that breaks our install.

This is tested with Umbraco 10.2.0 when using Umbraco Forms 10.2.0, and Umbraco 10.4.0 when using Umbraco Forms 10.4.0.

### Expected result

See all forms under the Forms section:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/353806/631a337f-8e0e-47a9-b7e4-eb9cd1b05e09)

### Actual result

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/353806/61ac3b56-8496-414a-ba6f-b6f83958cfe3)

We can't see any forms in the sidebar at all.
However, the form FOLDERS are still visible.

Forms seems to be fetched with an XHR to:
`http://localhost:8080/umbraco/backoffice/umbracoforms/formtree/GetNodes?id=-1&application=forms&tree=&use=main&culture=`

On version 10.2.0 this request returns a JSON payload with 19 items, where 4 of them are folders.

On version 10.4.0 this only returns the 4 folders, which also all are empty.

**Comment by AndyButland** [comment]
I've not seen this or heard it reported previously.  Is it possible to share the database along with a backoffice login - appropriately cleaned if necessary - so we can similarly connect to it and debug to see what may be going wrong?  If so - I'm at _abl AT umbraco dot dk_.

**Comment by karlmacklin** [comment]
This would be great, I'm confirming with the client what we're allowed to do and get back to you.

**Comment by AndyButland** [comment]
I'm not sure if it'll be relevant here, but given you have upgraded, worth just making sure you don't have any cached client side assets via [this technique](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html).

**Comment by AndyButland** [comment]
Good to hear that you have a workaround, but I can't immediately think why this might happen I'm afraid.  I've tried to replicate again with an install that matches your CMS and Forms versions, but I could see the form listed as expected with both options for the configuration.  If the result you have is that the forms are now visible as expected, I guess that's good for you to proceed, but it still seems an odd one.

Perhaps it is caching related but issues in that area are usually more related to browser caching of client-side assets after upgrades, rather than caching of JSON responses from controllers, which seems to be what you experienced here.

**Comment by karlmacklin** [comment]
Since we have a workaround currently and the issue is so obscure I'll close this, and reopen if anything significant changes.

Thank you for the support!
