### ISSUE TITLE
Mandatory message formatting lost

### ISSUE THREAD

**Issue by mhughes668** [umbraco/Umbraco.Forms.Issues#1096]
Our message for Mandatory fields is formatted to display red text. This appears correctly if the user enters a value which is not valid and hits 'submit', but if they leave the field blank or enter an incorrect value a second time, the formatting of the text is lost.

Specifics - Umbraco Forms v.8.13.11

We recently upgraded from Umbraco forms 8.6, where this was working correctly.

Steps to reproduce
Mark a field as "Mandatory" and fill in a 'mandatory message'
Fill in the form, but leave field blank.
Submit the form
The mandatory validation will display the error message
Leave field blank and submit again
Mandatory validation message will not be formatted

Expected result
Format of message remains the same

Actual result
The mandatory validation will display the error message formatted the first time, and without formatting after a second attempt.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/5c71217f-ae5f-4998-8d77-fcf387ccfce2)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/141656991/89824454-6ab2-4bbb-b050-3ed742abc66a)

**Comment by AndyButland** [comment]
I've not been able to replicate this I'm afraid, at least using the latest Forms 8 and the default theme.  It's possible you have a custom theme that might be triggering this behaviour.  Or maybe you have some local changes you have made to the default theme.  I'm happy to have a look if you are able to share it with me, so I can set it up locally and see if I see the same issue.

You can find the themes under this path: `Views\Partials\Forms\Themes\`,  The `default` folder is the one that Forms ships with and any custom ones are in other folders.  If you can zip up and share the whole `themes` folder and let me know which you are using, then that'll help me investigate further.

It might also be useful if you can share the template - the `.csthml` file - that you are using to render the form too please.

Finally, if you can confirm please that this is the built-in "short answer" field you are using, or if it's a custom one.

You can use the same email address as where you send me some files for another issue last week.

**Comment by AndyButland** [comment]
Thanks for sharing.  Unfortunately this is difficult for me to replicate, as you have a heavily customised theme, with reference to various extension methods other classes that I don't have access to.  So I can't run it to see the error.

I would suggest that it's worth using the default theme temporarily, just to confirm that works as expected.

Then it's a case of carefully comparing the default theme files to your custom ones to see in what important ways they differ.

I can see for the default theme we have this for the rendering of field validation messages:

```
@Html.ValidationMessage(f.Id)
```

And in your custom theme you have:

```
<div aria-live="assertive">
    @Html.ValidationMessage(f.Id, new { @class = "govuk-error-message", id = f.Id + "-error-wrapper" })
</div>
```

Also I can see in the default theme the validation message sits within the `<div class="umbraco-forms-field-wrapper">` element, but in your custom theme it's outside.

I can't spot by eye what the specific difference is that causes the issue I'm afraid, but I think that's how to tackle it.  Confirm the behaviour is correct with the default theme.  Then make changes to adjust your theme such that it aligns with the default theme, and when you fix this specific issue reported, re-apply your customisations with the necessary amends that allow the rendering to continue working.

**Comment by mhughes668** [comment]
Thank you.
