### ISSUE TITLE
Unable to Correctly Copy Umbraco Form

### ISSUE THREAD

**Issue by oblongataconsultancy** [umbraco/Umbraco.Forms.Issues#1097]
When copying a form to the root of the forms folder, it does complete the action but, doesn't display the form in the tree until you resave permissions in your assigned form group.

Reproduction
------------

### Specifics

- Umbraco 10.7.0
- Umbraco.Forms 10.5.0
- Google Chrome 117.0.5938.132 (Not tested in other browsers)
- Azure SSO is enabled (this happens for SSO users and local accounts).

### Steps to reproduce

1. Find a form to copy, right click and select copy.
2. Provide a name for the copied form.
3. Select 'copy to a new folder?'.
4. Select the root 'Forms' folder.
5. Click copy.
6. The form animates off the bottom of the list but doesn't appear.
7. Navigate to 'Users' > 'Form Security' > 'User permissions' and then select the account your logged in with.
8. You'll notice the form does appear at the bottom of the listed and has 'Has Access' selected.
9. Toggle on and off and the save.
10. Navigate back to the main 'Forms' section and you'll see the form appear like it should.

### Expected result

The user should just be able to copy the form and immediately view the copied form in the selected folder.

### Actual result

The form gets copied but not displayed until you resave the permissions. It seems that it knows it should have access to view and display but it doesn't until you resave.

**Comment by AndyButland** [comment]
Could you share some further details about your permissions set up please?

- What values do you have in configuration for the settings `ManageSecurityWithUserGroups` and `GrantAccessToNewFormsForUserGroups` (or if you don't have them in your configuration, you can just confirm that)?
- Is the user you are using an administrator?
- If you are managing security with user groups in Forms (i.e. `ManageSecurityWithUserGroups` is `true`), what groups is your user in and what form security permissions to they have?
- Or, if you are managing security with users directly in Forms (i.e. `ManageSecurityWithUserGroups` is `false` or missing from configuration), what form security permissions does your user have?

**Comment by oblongataconsultancy** [comment]
Hi Andy,

Please see responses below.

- `"ManageSecurityWithUserGroups": true` and "GrantAccessToNewFormsForUserGroups": "admin"
 (and some others)
- Yes, user I'm using is an admin.
- User is in Administration and Sensitive Data. 
    - Admin has full permissions.
    - Sensitive data has no permissions enabled (I've tried to remove this but the issue still persists).

**Comment by AndyButland** [comment]
Thanks for the extra detail.  Unfortunately though having been testing this morning, I've not been able to replicate the issue.

**Comment by AndyButland** [comment]
Will close this one now since being unable to replicate and no further discussion .
