### ISSUE TITLE
Globalize validationService from aspnet-client-validation

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#1099]
I reckon this is probably an edge case, but this would make it a lot easier to control Umbraco Forms from Javascript.

We have some forms, that we want to submit using javascript/fetch, but to keep things simple, we let the editors define them in Forms, and we render them to page as regular forms. This has the benefit, that if JS is disabled or somehow fails, the browser is still able to submit the form.

In order to submit using javascript, we add an eventlistener to the forms submit event. In this eventlistener, we validate the form using aspnet-client-validation. But because the `validationService` is registered inside the forms script (/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js line 165), we can't access it, and we need to create our own, and manually copy/paste the custom validators from Umbraco Forms (requiredcb, required and umbracoforms_regex).

The event listener we add is like this (I've shortened it a bit)
```js
  this.$root.addEventListener("submit", async (e) => {
      const form = e.target;
      e.preventDefault();
      e.stopImmediatePropagation();

      var isValid = window.v.isValid(form); // window.v is our own instance of validationService from the library

      if (!isValid || this.submitting) {
          return false;
      }

      this.submitting = true;

      var response = await fetch(event.target.action, {
          body: new FormData(event.target),
          method: event.target.method,
      });

      this.submitting = false;

      // handle the response...
      
 ```
 
If the `validationService` created in umbracoforms.js were accessable, we could use that in stead. Not sure if it should be in `window` or somewhere else.
 

---
_This item has been added to our backlog AB#35059_

**Comment by skttl** [comment]
This is great news - thanks!

**Comment by james-whittington1** [comment]
Could this be added to the docs as a section when adding a custom field type? If someone lets me know if this is an offical and support extension point I will write it myself.

**Comment by AndyButland** [comment]
Please feel free @james-whittington1 if you are up for doing that.  Thanks.

**Comment by james-whittington1** [comment]
Just figuring out how to actually get it to work - I am using the aspnet-validation version and am having some issues getting it to use my validator. 

So far I have added the provider and I can see it there, but it doesn't seem to be triggering. 

Once I have a good working example I will do a pr for the docs :)
