### ISSUE TITLE
Entries selector - Selecting the same record multiple times returns a number above the amount of entries when switching entry pages

### ISSUE THREAD

**Issue by nclaursen** [umbraco/Umbraco.Forms.Issues#1100]
It's possible to select entries mulitple times when you switch pages. Ie if you have 40 entries and swtich page back to those you have selected before you can select the entries one more time. Resulting in 60/40 entries selected - even though there's only 40 entries. 

Reproduction
------------

Withing forms entries choose the top check mark to select all - Go to each individual page and select them all - it counts upwards. THen go back a page, and again select all. Now it adds those entries to the count. It remembers with the count number that they were selected - but visiually they were not checked. 

### Specifics

This happened on Umbraco 8.18.9 on Umbraco Cloud. 
Forms version : 8.13.10
I have not tested it in other browsers yet. 

![umbraco forms multiselect](https://github.com/umbraco/Umbraco.Forms.Issues/assets/43075566/5c831f49-6427-4cef-9578-80fd204da473)

---
_This item has been added to our backlog AB#33710_

**Comment by AndyButland** [comment]
Thanks @nclaursen, I've found the reason for this, so we'll have a fix in the next round of patch releases.
