### ISSUE TITLE
Multiple choice datatyp not updating

### ISSUE THREAD

**Issue by quadhenken** [umbraco/Umbraco.Forms.Issues#1101]
Multiple choice datatyp not updating after deleting a prevalue.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Install umbraco 12.2.0 + umbraco forms 12.1.1.
Create a form with multichoice datatype + prevalues and render it in a template.

@await Umbraco.RenderMacroAsync("renderUmbracoForm",
    new {FormGuid= Model.Formulaer,
        FormTheme="default"})

Delete one of the prevalues and save the form.

Reloade the page, the deleted prevalue is still there.

### Specifics

Umbraco 12.2.0
Umbraco Forms 12.1.1

### Expected result

The deleted prevalue should not show.

### Actual result

Prevalue is still there until you restart the site.

---
_This item has been added to our backlog AB#33696_

**Comment by AndyButland** [comment]
Thanks for reporting, we'll have this resolved for the next patch release.

**Comment by quadhenken** [comment]
> Thanks for reporting, we'll have this resolved for the next patch release.

Thanks Andy!
