### ISSUE TITLE
Return messageOnSubmit and redirect url when form is submitted with api

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#1104]
I have a workflow that needs to inject a link generated by a 3rd party resource into "messageOnSubmit." However, the [submit api](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms#submitting-a-form-entry) doesn't return any data, so this is currently impossible. It would be nice if the api could return the "messageOnSubmit" and "redirectUrl" after all the workflows have finished.

I don't think this is officially supported by the non ajax implementation either, though there is a way to hack around this with magic strings based on this [thread](https://our.umbraco.com/forum/umbraco-forms/80062-umbraco-forms-change-messageonsubmit-in-custom-workflow). Don't think that approach would work in my case though, as umbraco is being used as a headless cms.

Ideally, what I'd like to be able to do is something like
```csharp
public override WorkflowExecutionStatus Execute(WorkflowExecutionContext context) {
    context.Form.MessageOnSubmit = context.Form.MessageOnSubmit?.Replace("[externalLink]", GetExternalLink());
    return WorkflowExecutionStatus.Completed;
}

private string GetExternalLink() {
    ...
}
```

---
_This item has been added to our backlog AB#34090_

**Comment by AndyButland** [comment]
I had a quick look at this and it seems feasible.  You can apply the code you've suggested, but the problem is that we don't save the form as part of the workflow, so the change isn't persisted.  We wouldn't want it to be of course.

However stepping through the API route of submitting entries I can see the changes made in the workflows are available at the point we return from this request, so, as you suggest, we could provide an object result back at this point.  Currently we return "202 Accepted" with an empty body, but I'm thinking if we return an instance of the following that would meet this use case:

```
    public class EntryAcceptedDto
    {
        public string? MessageOnSubmit { get; set; }

        public bool MessageOnSubmitIsHtml { get; set; }

        public Guid? GotoPageOnSubmit { get; set; }
    }
```

**Comment by AndyButland** [comment]
We've added this now, so from the next release you'll have a response body looking something like the following:

```
{
    "gotoPageOnSubmit": "3cce2545-e3ac-44ec-bf55-a52cc5965db3",
    "gotoPageOnSubmitRoute": {
        "path": "/about-us/",
        "startItem": {
            "id": "ca4249ed-2b23-4337-b522-63cabe5587d1",
            "path": "home"
        }
    },
    "messageOnSubmit": "Thanks for your entry",
    "messageOnSubmitIsHtml": false
}
```

**Comment by jaandrews** [comment]
That's great. I'll keep an eye out for the new release.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/overwriting-the-default-thank-you-form-message-using-context-record-messageonsubmit/6790/4
