### ISSUE TITLE
Add support for custom data in settings object

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#1105]
I have some json data I'm trying to pass into a custom workflow setting. Unfortunately, there isn't a good way to do this at the moment (see documentation [here](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype)). The "Prevalues" property expects a comma separated list as a string, and so it would break up a serialized json string if I put it there. It's also not possible to inject the value by extending the Settings method, as that just creates a dictionary of Setting objects and so has the same limitations as the Setting attribute.

Would it be possible to add a property to the Setting attribute to allow custom data to be passed into the Setting class (located at Umbraco.Forms.Core.Attributes.Setting)? It is possible to work around this issue by creating an api to get the data, but it would be simpler to pass along the data directly.

**Comment by AndyButland** [comment]
Maybe I haven't quite followed the request here, but you can have more complex objects stored as settings.  For example in core we have the field mapper used in the "Send to URL" workflow.

The settings is defined like this:

```
        [Setting("Fields", Description = "Map the needed fields (if not mapped all fields will be sent)", View = "FieldMapper", SupportsPlaceholders = true, DisplayOrder = 40)]
        public virtual string Fields { get; set; } = string.Empty;
```

With the important part being the `View` property on the `Setting` attribute.

This maps to an angularjs view hosted at:

```
App_Plugins/UmbracoForms/backoffice/Common/SettingTypes/fieldmapper.html
```

Which in turn references a controller.

The data is stored like this:

```
{
   "name":"Post to URL",
   ...
   "settings":{
      ...
      "Fields":"[{\"alias\":\"Email\",\"value\":\"61bf1cd7-5169-4715-8bbc-0bdec1469101\",\"staticValue\":\"\",\"$$hashKey\":\"object:1286\"}]",
      ...
   },
   ...
}
```

**Comment by jaandrews** [comment]
@AndyButland I'm already doing that. What I'm trying to do is pass additional configuration to those settings. Here is an example of what I would like to be able to do (doesn't have to be done the way I've shown; just need a way to pass the data to the setting).

```csharp
private IEnumerable<ApiOption> _options = new List<ApiOption>() {
    new ApiOption {
       Name = "Api 1",
       Options = typeof(ApiParams1).GetProperties().Select(x => x.Name)
    },
    new ApiOption {
        Name = "Api 2",
        Options = typeof(ApiParams2).GetProperties().Select(x => x.Name)
    }
};

[Setting("Mappings",
    Description = "Maps fields to api parameters.",
    View = "apiMapper",
    AdditionalData = new Dictionary<string, object> { { "options", _options } } //new parameter to pass custom data into the setting
)]
public string Mappings { get; set; }
```

"apiMapper" is a custom setting I've created to map form fields to api parameters. It's similar to the built in fieldMapper setting, but it has the user select the api to send the data to from a dropdown and then limit's the alias options to just the parameters for that api. The urls of these apis vary by environment in my case, so it isn't safe to use the built in "Post to Url" workflow to handle this.

**Comment by AndyButland** [comment]
I don't think that's going to work unfortunately, as you are limited in what you can provide as parameter types for attributes.

I tried coding your example up just to see if it compiles but I get [this compiler error](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0655?f1url=%3FappId%3Droslyn%26k%3Dk(CS0655)).

**Comment by jaandrews** [comment]
@AndyButland I know it doesn't currently work, as "AdditionalData" isn't a property on the **Setting** class. That was just an example of how it could work if the **Setting** class was updated to include that property. The only option to pass data to a setting control is "PreValues," but this doesn't work for Json data because it splits the string by commas.

**Comment by AndyButland** [comment]
I added the `AdditionalData` property though - even with it I get the compile error.  You can try it in a sample - if you create a class that inherits from `Attribute`- like our `Setting` does - I think you'll see the same issue when you try to add and use a dictionary property.

**Comment by jaandrews** [comment]
@AndyButland It doesn't have to be a dictionary. It can also be a serialized string. I don't work much with attributes and so wasn't aware of this limitation (covered in docs [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#2224-attribute-parameter-types)).

**Comment by AndyButland** [comment]
Again I still think we might run up against the compiler... another restriction is that attribute parameters need to be [constants or similar](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0182?f1url=%3FappId%3Droslyn%26k%3Dk(CS0182)).  I was thinking you could use the `Prevalues` - that's a string, and we expect it to be a comma delimited one, but you could set anything.  But this for example, doesn't compile (not if you remove the `static` keyword):

```
        private static string Options = "test";

        [Setting("Test", PreValues = Options,)]
        public virtual string Test { get; set; } = string.Empty;
```

To be honest I think you might be on the right lines with your original idea of "creating an api to get the data".

**Comment by jaandrews** [comment]
@AndyButland It might be possible to work around this by injecting the dynamic data in the Settings method of the workflow, which does support overrides.
```csharp
public override Dictionary<string, Setting> Settings() {
	Dictionary<string, Setting> dictionary = new Dictionary<string, Setting>();
	PropertyInfo[] properties = GetType().GetProperties();
	foreach (PropertyInfo propertyInfo in properties) {
		Setting setting = propertyInfo.GetCustomAttributes<Setting>(inherit: true).FirstOrDefault();
		if (setting != null) {
			if (string.IsNullOrWhiteSpace(setting.Alias)) {
				setting.Alias = propertyInfo.Name;
			}
                        setting.AdditionalData = JsonSerializer.Serialize(_options); //added this line to inject the data
			dictionary.Add(propertyInfo.Name, setting);
		}
	}

	return dictionary;
}
```

Would still expose the property when adding a Setting as an attribute though, so probably not a good idea to do this. Just highlighting it as a possibility. I don't think there is a good way to address this without making breaking changes to how settings are configured, so I will move forward with the api solution instead.

**Comment by AndyButland** [comment]
OK, I'll close this one then given I don't see that we have a good way to meet the original request.
