### ISSUE TITLE
Umbraco Forms 8.13.10: ,Fieldtype labels containing magicstring not replaced in sended mail

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco.Forms.Issues#1107]
A brief description of the issue goes here.

Reproduction
------------

- Create Umbraco Forms form
- Add some properties, for example a 'short answer' fieldtype
- Set label to magicstring tag like `[%pageName]` or a custom one from session
- View form; label is replaced by magicstring value (name of the page form is on for example)
- Send form: label isn't replaced with magcstring but displaying '[%pageName]' as fieldtype label

### Bug summary

Expected result: Labels made out of magicstring will be replaced by their value
Actual result: Labels made out of magicstring are displaying magicstring key

Marked in yellow; our magicstrings inside a sended Umbraco Forms mail:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/19536dec-7719-4ac9-9176-70007fa46c79)

Marked in yellow; the replaced magicstring on page using Umbraco Forms form:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/0b1be6c5-f3cd-490b-84cb-01d666d3da41)

### Version info
Umbraco: 8.5.5
Umbraco Forms: 8.13.10

**Comment by AndyButland** [comment]
Thanks for reporting.  We'll have a fix for this in the next round of patch releases.

**Comment by RunnicFusion** [comment]
@AndyButland thanks for your update! When do you expect Umbraco Forms 8.13.12 to be released?

**Comment by AndyButland** [comment]
We're currently looking at November 14th for the next round of releases.
