### ISSUE TITLE
Mandatory/Required property on Setting-Attribute

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco.Forms.Issues#1108]
I would like the SettingAttribute to have a IsMandatory property. I have had to make my own overrides of dropdown and textfield fieldsetting-views just to add an ng-required=true.

---
_This item has been added to our backlog AB#34457_

**Comment by AndyButland** [comment]
We'll include this option with the next release.  There'll be an `IsMandatory` property on the `Setting` attribute available, which we'll have set on the core field and workflow types that are currently required.

This will be surfaced in the UI on settings types that accept the `ng-required` attribute, and visually presented as shown if you tab in and out of a required field, or if you set a value in a required field, delete it, and tab out:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/9c3fb46c-f817-47af-b84b-315874414e71)
