### ISSUE TITLE
Broken link in side panel

### ISSUE THREAD

**Issue by GerbenAxendo** [umbraco/Umbraco.Forms.Issues#1109]
When adding a question, the blue panel about Magic Strings contains a link that is dead.  "Read more" leads to https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Magic-Strings/index-v7 -  which is dead.

Reproduction
------------
UF Version: 8.13.11
Umbaco version: 8.18.8

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/101253874/193d6f65-1b08-459a-9e7b-1d75538ceac6)

**Comment by tedlindholm** [comment]
Perhaps it is time to remove the text about magic strings? 

I don't think there should be boxes with hints in the backoffice just because the implementation is non intuitive. Perhaps autocomplete or similar assistance when the user try to write a magic strings instead?

**Comment by AndyButland** [comment]
Thanks for reporting @GerbenAxendo - we'll fix that link for the next release.
