### ISSUE TITLE
Remove inline styles so content-security-policy for 'style-src-attr' doesn't require 'unsafe-inline'

### ISSUE THREAD

**Issue by snerpton** [umbraco/Umbraco.Forms.Issues#1110]
We have some enterprise sites whose InfoSec teams require the CSP to be set with no 'unsafe-inline' sources.

Forms sets `style="display: none"` in multiple locations in the default theme (verified by downloading the .cshtml files from https://docs.umbraco.com/umbraco-forms/developer/themes for v10 and v 12).

I see Umbraco Forms has previously addressed CSP issues with inline scripts (e.g. https://github.com/umbraco/Umbraco.Forms.Issues/issues/677), and I wonder if it is possible to remove the requirement on 'unsafe-inline' source for the 'style-src-attr' CSP?

Cheers,
Chris

---
_This item has been added to our backlog AB#34460_

**Comment by AndyButland** [comment]
We'll update the default them for the next patch release for Forms 10 and 12 to move any inline styles to the theme's stylesheet.
