### ISSUE TITLE
Formatting of guid constants in Umbraco.Forms.Core.Consants is not consistent

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#1112]
I have a workflow that needs to modify the data submitted to a form based on the field type. I tried doing something along the lines of 
```csharp
var record = context.Record.GetRecordField(fieldId);
switch(record.Field.FieldTypeId.ToString()) {
    case Constants.FieldTypes.Textfield:
        return ...
}
```
and noticed that the casing for this constant has a mix of lower and upper case characters for some reason (it's "3F92E01B-29E2-4a30-BF33-9DF5580ED52C"). It's not the only one either. Ideally all guid constants would be lower case, since that's what the guids use when calling ToString (at least in my environment), but having them all in upper case would also work (most of the keys are in upper case currently).

It's not difficult to work around this by manually entering the guid strings instead of using the constants, but it is best to use the constants to ensure they don't break if the keys for the field types change in the future (unlikely, but good practice to future proof it).

Also, just in case it's relevant I'm running **version 11.1.3** of umbraco forms in the environment I'm testing in.

**Comment by AndyButland** [comment]
Unfortunately we can't change this in a minor version, as it could be a breaking change for some people (if they have relied on the actual values).  But it makes sense to align for Forms 13, so given most are already in upper case I'll amend those that aren't to match.
