### ISSUE TITLE
Friendly names for Hubspot Forms

### ISSUE THREAD

**Issue by jpkeisala** [umbraco/Umbraco.Forms.Issues#1114]
I discovered that in Hubspot all forms are named based on what is on the `<form id="">`. But it seems Umbraco Forms names  the id="" as instance GUID of the form, so we see these GUID's in Hubspot at `Marketing > Lead Capture > Forms` that has no much of a meaning for a user. 
Would it not be possible to have form name passed as a name of the form so at `Marketing > Lead Capture > Forms` users could read form names?

---
_This item has been added to our backlog AB#34409_

**Comment by acoumb** [comment]
Hi @jpkeisala ,

We've moved this to the `Forms` issue tracker, as this fits best here, being out of the scope of the integration with `HubSpot`. 

Thank you,
Adrian

**Comment by AndyButland** [comment]
I've had a look at what we are doing in Umbraco Forms here, and we aren't explicitly setting either an `id` or a `name` attribute on the `<form />` tag.  There is an `id` rendered, but this is a random one provided by Umbraco itself when there isn't an explicit one set.

We could look to add some configurable options for this.  Could you confirm though what specifically you are looking for for this use case please?  I.e. is it an `id` or a `name` attribute, and maybe you can share an example of what you'd want to see in there?  Thanks.

Just to be clear - we aren't doing anything specific for HubSpot here or calling any APIs.  Our suspicion is that you have the HubSpot tracking code that @acoumb mentioned above installed, and it's that which is sending your form data to HubSpot,  So you might need to experiment with a hard-coded form to see what it picks up.

**Comment by jpkeisala** [comment]
Thank you, @AndyButland, for the clarification. It appears that what @acoumb mentioned is indeed the case. The HubSpot tracking code seems to be causing the issue in my situation. I've asked the customer about the possibility of disabling non-HubSpot Forms tracking, as it appears to be causing conflicts and confusion in HubSpot dashboard.

In the coming days, I plan to conduct tests both with and without form tracking using the extension to observe the differences. I will keep you updated on my findings.

**Comment by AndyButland** [comment]
Did you have any further on this please @jpkeisala?  If not I'll close the issue.  Thanks.
