### ISSUE TITLE
Forms under start-node not visible in tree if a single start folder is selected

### ISSUE THREAD

**Issue by GerbenAxendo** [umbraco/Umbraco.Forms.Issues#1118]
When using (group or user) security, and selecting a (one) specific start folder, forms directly under that start node don't appear in the tree for the user.

### Reproduction

Install Umbraco version 8.18.9
Install Umbraco Forms: 8.13.12
Settings in config:
- ManageSecurityWithUserGroups ="True" 
- GrantAccessToNewFormsForUserGroups ="form-creator,Administrators,admin,editor" 
- DefaultUserAccessToNewForms ="Deny" 

Create a folder "Folder"
Create a form in this folder
Give the user group "Editors" all permissions (Manage forms etc.) and set "Folder" as start folder, as per below
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/101253874/191e539b-9abc-4d0f-ac84-b28f164d91c7)
Create a user and add this user to the Group editors
Login as this user. 

### Expected result

You would expect the user to be able to expand "Forms" using the arrow. Then see all forms in the "Folder" node.

### Actual result
After clicking the arrow - child forms are not loaded in the tree. The forms are displayed as tiles on the right-side - but this doesn't allow access to form settings - only to enties.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/101253874/b4cf20e2-add4-4024-8ed7-332c463773a0)

Note that adding a second folder to the Start folders setting, causes both folder to be displayed in the tree and hence will solve the problem - but this is unwanted, since you would have to create and extra dummy folder with no user.

**Comment by AndyButland** [comment]
Thanks @GerbenAxendo - I can replicate and see the issue.  We'll resolve in the next patch release for Forms 8.

**Comment by GerbenAxendo** [comment]
Thanks @AndyButland !
