### ISSUE TITLE
Performance gets downgraded when number of forms grows

### ISSUE THREAD

**Issue by GerbenAxendo** [umbraco/Umbraco.Forms.Issues#1119]
When the number of forms grows to 200+, the performance of specific functionality gets slow.

### Reproduction
Install Umbraco version 8.18.9
Install Umbraco Forms: 8.13.12
Settings in config:
```
ManageSecurityWithUserGroups ="True"
GrantAccessToNewFormsForUserGroups ="form-creator,Administrators,admin,editor"
DefaultUserAccessToNewForms ="Deny"
```
Create 200 forms - either manually or coping records in database table UFForms
Open a form from the tree - this will take around 10+ seconds to open (tested on several hardware configurations)

### Expected result
You would expect a better performance, especially since Umbraco's focus on the (low/mid) enterprise market where Forms are used extensively

### Actual result
Downgraded speed/performance for the following functionality:
- Coping a form
- Saving a form
- Saving group permissions
- Saving user permissions

### Specifics
All seems to boil down to a request to GetForCurrentUser - that takes a long time to load.
https://our.umbraco.com/forum/using-umbraco-and-getting-started/112449-performance-issue-umbraco-forms-getforcurrentuser

**Comment by AndyButland** [comment]
Thanks for the report @GerbenAxendo - we did backport some performance optimizations back into Forms 8 for the last patch release, which you should have found has sped up the loading of the form's tree.  However there were some more we could bring back to help with the form loading speed too.  I've done that now so we'll make available in the next patch release.

**Comment by GerbenAxendo** [comment]
Thanks @AndyButland for the quick-fix! 
Oh and yes: I can confirm the speed improvements in the form's tree going to 8.13.12.

I have found on the Umbraco site that there is no official release cadence for Forms. What would be a logical release date for 8.13.13?

**Comment by AndyButland** [comment]
There's no cadence for patches, they are released as and when we have something to go and around other priorities.  We have a couple of minor releases to organise this week but I suspect we'll arrange the next patch release for 8 in the upcoming couple of weeks.
