### ISSUE TITLE
Umbraco V8 - Save as Umbraco Node not mapping text data to document type properties.

### ISSUE THREAD

**Issue by RobinHoody** [umbraco/Umbraco.Forms.Issues#112]
If I add a workflow step using Save as Umbraco content node to my form, only the Node Name & numerical values get mapped, none of the other content seems to work. All my text fields won't map to a document type with text fields.

![image](https://user-images.githubusercontent.com/4989076/54289986-16243180-45a2-11e9-98d6-8ba6ac3f9e84.png)

### Steps to reproduce

1. Create a form adding a numerical field and text field and a document type that mirrors the forms content.
2. Add the Save as umbraco content node workflow step, mapping to the document type you've also created.
3. Fill in the form with test data and sumbit.
4. Go to the back office and view the created unpublished node (Reload tree first) and you'll see only the node name and numerical type was mapped correctly.

If you look at the saved data for the form, all data was captured so it's getting the data, just not mapping it.

### Expected result

On form post, an unpublished content node should be created with mapped types.

### Actual result

An unpublished node is created but only the node name and numerical form data is mapped, all text fields aren't mapped to document type values.

**Comment by RobinHoody** [comment]
@bergmania Quite a critical one here, unless i'm going crazy. I can't see any errors in the log either, it's really strange. I haven't tested with 7, I assume there's a breaking change in 8.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/257

**Comment by RobinHoody** [comment]
Can I just check, is this going out on tuesday? I could really do with the fix for a client.

**Comment by RobertCopilau** [comment]
Hey @RobinHoody, "Hopefully the 26th of March, we couldn't fit it into next week's release any more."

**Comment by RobinHoody** [comment]
Thanks, I'll let my client know and work out a temporary fix until then.
