### ISSUE TITLE
12.1.2 Hiden Fields (ie, reCaptcha) are Not Hiden in Rendered Markup

### ISSUE THREAD

**Issue by paulsterling** [umbraco/Umbraco.Forms.Issues#1120]
After updating from 12.1.1 > 12.1.2 any reCaptcha3 fields in our Forms are rendering as visible input boxes. I see there is a small difference in the rendered markup with an addtional class (`class="umbraco-forms-hidden"`) applied to the `<div>` elemement surrounding the hidden field.

There does not appear to be any corresponsing CSS for the `umbraco-forms-hidden` class so possibly that is the issue?

Note this is in Umbraco Cloud, running Umbraco CMS 12.3.1.

Reproduction
------------

### Bug summary

After updating from 12.1.1 > 12.1.2 any reCaptcha3 fields in our Forms are rendering as visible input boxes. I see there is a small difference in the rendered markup with an addtional class (`class="umbraco-forms-hidden"`) applied to the `<div>` elemement surrounding the hidden field.

There does not appear to be any corresponsing CSS for the `umbraco-forms-hidden` class so possibly that is the issue?

### Steps to reproduce

- Install Umbraco CMS 12.3.1 with Forms 12.1.2. (Umbraco Cloud)
- Create a Form and add a reCaptcha3 field.
- Run the site and note the visible input box where the reCaptcha hidden field should be

### Expected result

12.1.1
![12 1 1](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/0e0841e8-1890-4057-807f-4a7a109a062f)

### Actual result

12.1.2
![12 1 2](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/87c471a7-e9fe-4bb2-bf00-6900a3b5c8f6)

**Comment by AndyButland** [comment]
Hi @paulsterling - yes, we made this update to address the issue raised in https://github.com/umbraco/Umbraco.Forms.Issues/issues/1110

You should have a style defined though for `umbraco-forms-hidden` which we provide in the default stylesheet.

I realise now though it is possible to switch off the default stylesheet from the default theme - via the option in form settings:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/d589d9ad-e78f-4edc-9e99-f04d52716c57)

So I guess that's your situation.

If you aren't using the default stylesheet, adding the following CSS to your custom one should sort out the issue:

```
.umbraco-forms-hidden {
  display: none;
}
```

And apologies for the oversight here.  I had figured that if we update both the stylesheet and the view files for the default theme in the same release, we'd be safe to make this update.  But I had forgotten about this option to disable it, meaning you'd get the CSS classes in your view but not the styling for it.

**Comment by paulsterling** [comment]
Hi @AndyButland 

Thanks for that explaination, makes sense and adding the CSS to our styles solves the issue, so all good with that work around.

Just in case there's another angle on this one, we actually use the Forms provided `bootstrap3-horizontal` theme rather than the default or no theme. Maybe that's a legacy artifact since these sites were upgraded to v12 from v10? Anyhow, just something to consider including in case you do still ship with the bootstrap theme.

bootstrap3-horizontal theme
![12 1 2-bootstrap](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/72314759-504b-469d-9621-317b3fdf92df)

**Comment by AndyButland** [comment]
OK, yes, that is still shipped, so we need to add a default stylesheet for that them with this new CSS rule.  Thanks for the help, we'll get that sorted for the next updates.
