### ISSUE TITLE
In the copy form dialog, the Copy button is not disabled after clicking, resulting in multiple clicks and thus created forms

### ISSUE THREAD

**Issue by GerbenAxendo** [umbraco/Umbraco.Forms.Issues#1121]
In the copy form dialog, there is no direct user feedback after the user has clicked the Copy button. (No spinner or disabling the button e.g.). In practice, this results in editors clicking multiple times, resulting in the multiple forms that are created. 

### Reproduction
Install Umbraco version 8.18.9
Install Umbraco Forms: 8.13.12
Settings in config:

```
ManageSecurityWithUserGroups ="True"
GrantAccessToNewFormsForUserGroups ="form-creator,Administrators,admin,editor"
DefaultUserAccessToNewForms ="Deny"
```

Open the copy a form dialog
After clicking the button Copy, it appears to the user as 'nothing happens' - causing the user to repeat the button clicking. This is specifically a risk on installations where the Copy form action is not 'instant' - e.g if you have large number of users/users groups and/or forms.

### Expected result
The Copy button could bedisabled after clicking or even better, transform into a spinnner, to be inline with buttons such as the "Save" button on the Edit form screen.

---
_This item has been added to our backlog AB#35620_

**Comment by AndyButland** [comment]
We've updated the implementation for the copy form dialog in the latest version, so this will be available from 12,2,

**Comment by wvankesteren-ax** [comment]
Please backport this issue to Umbraco Forms: 8.13!

**Comment by wvankesteren-ax** [comment]
Since this customer project is Umbraco Forms v8, please port the fix to Umbraco Forms v8.

This is mandatory to serve your customers at the best!

**Comment by AndyButland** [comment]
This update will be part of the next patch releases for Forms 8 and 10 too.

**Comment by wvankesteren-ax** [comment]
Great! Many thanx!
