### ISSUE TITLE
List of forms in Forms Security is sorted differently compared to tree

### ISSUE THREAD

**Issue by GerbenAxendo** [umbraco/Umbraco.Forms.Issues#1122]
When setting (group or user) security, the list of of forms in the edit screen, is sorted differently then in the form's tree. The tree sorts the alphabetically, where as the list in Form Security, is sorted by date. This makes it harder to find forms for editors. Also, the list doesn't show the folder structure. 

### Reproduction

Install Umbraco version 8.18.9
Install Umbraco Forms: 8.13.12
Settings in config:ManageSecurityWithUserGroups ="True" 

### Expected result
You would expected both things (tree and list) to follow the same sorting. Furthermore (though this probably won't be an 'easy-fix' and had some implications) the Form Security could show the form in the same folder structure (if applicable).

---
_This item has been added to our backlog AB#35618_

**Comment by AndyButland** [comment]
As of the next release we'll have this sorted by name, and also included clickable headers so you can sort by form name, creation data and whether or not the user has access.

**Comment by GerbenAxendo** [comment]
For those who are interested -  this is a casing issue in forms 8.13.12 and can be fixed by change FormName to formName

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/101253874/43afdd5b-c2aa-4c62-9829-89160597f2dd)

**Comment by wvankesteren-ax** [comment]
Since this customer project is Umbraco Forms v8, is it possible to backport this simple fix to Umbraco Forms 8 ?

**Comment by AndyButland** [comment]
Yes, we'll backport the casing bug fix to 8 and 10.

**Comment by wvankesteren-ax** [comment]
And again: Great! Many thanx!
