### ISSUE TITLE
Umbraco v8: Forms submitted at the same time produces triggered "Lock request timeout period exceeded" error

### ISSUE THREAD

**Issue by LeeActiveIS** [umbraco/Umbraco.Forms.Issues#1123]
### Bug summary

When users submit multiple simultaneously send requests to create, save, and publish a node via forms custom workflow in Umbraco V8. This causes an extended wait time for all the users and triggers a "Lock request timeout period exceeded" error.

It is worth mentioning that this does not happen in a V12 instance with the latest version of forms.

Reproduction
------------
Steps to reproduce

1. Setup a New Umbraco  8.18.8 installation
2. Install Umbraco forms 8.13.9
3. Create a custom forms workflow that will update a value of a property in a  node and then save and publish using the content service.
4. Create a Form and add in your custom workflow.
5. Browse to the form on 2 separate devices (I used my mobile and desktop machine) and submit the form both at the same time on each device.
6. A "Lock request timeout period exceeded" error will appear.

### Specifics
You will need the following

- Umbraco Version 8.18.8
- Umbraco Forms Version 8.13.9
- A document type with at least 1 custom property to be used by the custom workflow

### Expected result

I would expect that both submissions will be recorded in the entries table and that the node will have it's property updated twice.

### Actual result

There is only 1 record created inside Umbraco forms entries and the node is a only updated once

**Comment by AndyButland** [comment]
Will need to close this one now given Forms 8 is end of life.  If anyone lands on this and can reproduce in a supported version please create a new issue.
