### ISSUE TITLE
Checkbox fields are always `false` when used in conditional workflows

### ISSUE THREAD

**Issue by glombek** [umbraco/Umbraco.Forms.Issues#1124]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Checkbox fields are always `false` when used in conditional workflows.

### Specifics

Having decompiled the source, it looks like `FieldConditionEvaluation.GetFormFieldValuesForConditions` always returns `false` for checkbox fields no matter what.

### Steps to reproduce

* Create a checkbox field in a form
* Add a workflow with a condition that this field is `true`
* Check if workflow runs

### Expected result

* Workflow should run when the checkbox is ticked
* Workflow does not run when checkbox is unticked

### Actual result

* Workflow never runs, despite what the value of the checkbox is

---
_This item has been added to our backlog AB#35478_

**Comment by glombek** [comment]
Forms version 12.1.2
Umbraco version 12.3.1

**Comment by glombek** [comment]
Cheers @AndyButland  - glad to hear you can replicate and I'm not going mad! 🙃

**Comment by AndyButland** [comment]
This will be part of the next round of patch releases for supported older versions, and included in the upcoming 12.2.
