### ISSUE TITLE
Error submitting multi-page Umbraco forms and single page forms with a ReCaptcha field

### ISSUE THREAD

**Issue by CoryLagdon** [umbraco/Umbraco.Forms.Issues#1126]
Error submitting multi-page forms 

Reproduction
------------

### Bug summary

Hi all, Im part of a team building umbraco sites and as im creating forms i go to test one and it sends me an error. It occurs when we press next on multi page forms; single pages are fine unless we use recaptcha fields. We dont use custom field types and we haven't made any changes to the tempDataProvider. Were at a loss for any rhyme or reason it does this so i come here to you. Is this an existing problem with Umbraco and if so is there a work around while it gets fixed. Heres the link to the discord forum post containing the raw exception details and stack: https://discord.com/channels/869656431308189746/1179346378535735296

### Specifics

Were using Umbraco 10 with Umbaco forms 10.3.3
I am using Edge Version 119.0.2151.72 (Official build) (64-bit)
I have tried it in Chrome Version 119.0.6045.200 (Official Build) (64-bit) , and Firefox 120.0 (64 bit)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/148446123/74a9c597-f6cc-4618-b855-aabe455b98aa)
[Raw Exception Details.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/13500394/Raw.Exception.Details.txt)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/148446123/baacc1ae-e7dd-463d-a0cb-b367b823c3b2)

### Steps to reproduce

1. Make a form,
2. Give it fields,
3. Add a second page or a ReCaptcha field,
4. Test the form by hitting next when using multi page or submit if using single page with ReCaptcha,
5. Error Occurs

### Expected result

Go to the next page or submit the form and follow the workflow

### Actual result

Error message, Only occurs on this specific website but we havent done anything different with this one than the others weve worked on in the past.

**Comment by AndyButland** [comment]
I can't replicate this I'm afraid - this is what I've done, so perhaps you could see if you see the same or otherwise see what might be different in your case.

```
dotnet new install Umbraco.Templates::10.7.0
dotnet new umbraco --name FormsTest
cd .\FormsTest\
dotnet add package Umbraco.Forms -v 10.3.3
dotnet run
```

I think create a doc type with a form picker, rendered with the following template:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Sample Form Page</title>
</head>
<body>
<h1>Sample Form Page</h1>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}
@Html.RenderUmbracoFormDependencies()

</body>
</html>
```

Create a form with two pages, and was able to move to page 2 and then submit the form without any issues.

**Comment by CoryLagdon** [comment]
We found the problem. We have a helper function which puts information into the temp data  and that works completely fine but only when its in a master file and not in a template. We think its a timing issue between the two files but we don't know why this had the effect it did since they're both just partial views but if we find out ill let you all know. Thank you all for offering your time to help. Much love , stay safe this holiday season <3. Cory.
