### ISSUE TITLE
Entry view shows dictionary key of caption instead of the actual dropdown value

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco.Forms.Issues#1131]
Entry view shows dictionary key of caption instead of the actual dropdown value on a multilingual website.

### Specifics

I'm using Umbraco Forms 10.5.2 on Umbraco 10.8.2 in a multilingual setup.

### Steps to reproduce

The form contains a Dropdown that uses dictionary items for the prevalue captions:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/5654ab38-eb21-4cb9-ae3e-f97132ad22bb)

The email with form values shows the actual option value:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/c9d56151-1dff-48e3-bae8-e00b97488676)

But in the Umbraco backoffice the entry view shows the dictionary key instead of the value for the selected dropdown option:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/161342/1fdb056f-a3dc-4a20-ab2f-a79d9c6ec35a)

### Expected result

The entry view should show the actual value of the selected dropdown option.

### Actual result

The entry view currently shows the dictionary key for the caption of the selected dropdown option.

---
_This item has been added to our backlog AB#36005_

**Comment by AndyButland** [comment]
We'll have a fix for this with the next round of patch releases.
