### ISSUE TITLE
Graceful validation of fields with placeholders

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1132]
I noticed on one our Umbraco Cloud project, a multi-site / multi-language solutions, that a contact form failed rendering on the German site, but not on other sites.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/2cdb28e0-311f-48d9-afca-7e17e08f0668)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/3f818a9e-e3a8-4c7a-9912-c4a528787fc1)

First I though it was because of the German characters in error messages like `ü`, `ä` and `ö`, but after further investigation I found it was due a syntax error in the error message.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/615450d6-bc39-40f4-856d-2373c61f5254)

I wonder if we could either have some regex validation here in case the validation message contains `{0` or `0}` and maybe even `{{0}}`? 

or some graceful validation, when rendering the form. E.g. log the error message, but don't fail rendering the entire form.
It could eventually just fallback to default error message or just use the raw string, so it frontend one would just see `Bitte überprüfen Sie 0}` instead of the correct message `Bitte überprüfen Sie {0}` where `{0}` is replaced with the actual field name.

I think this is less critical as content editors sometimes make mistakes and often not familiar with `{0}` placeholder.

The description below "Mandatory Error Message" and "Invalid Error Message" can eventually mention this as well, because if one deleted it, it can be difficult to know it's an option to add.

Forms v12.1.2
Umbraco v12.2.0

---
_This item has been added to our backlog AB#36127_

**Comment by bjarnef** [comment]
Maybe something like this: https://stackoverflow.com/a/36642556

```
public static class StringExtensions
{
    public static bool HasPlaceholder(this string s)
    {
        return Regex.IsMatch(s, "{\\d+}");
    }
}
```

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/8011bd52-75f6-4eec-911e-3180ce7f6e61)

**Comment by dtng95** [comment]
Hi @bjarnef,
Thank you for reporting this issue.
A fix has been made and will be included in the next release/patch

**Comment by AndyButland** [comment]
We'll include a basic check for a valid format string, as expected for these validation messages, with the next round of patch releases for the versions indicated.
