### ISSUE TITLE
Form field value "magic string" not working in "show message"

### ISSUE THREAD

**Issue by shropgov-neil** [umbraco/Umbraco.Forms.Issues#1133]
When rendering a "thank you" message with the default "show message" workflow, form field "magic strings" appear as plain text ("{myUmbracoFieldName}" or "{record.ip}") rather than the expected value.

However, the square bracket magic strings however ([@Url], [#pageName], etc) are all replaced with the expected values.

It's also working in the "send email" workflows, this is only affecting the "show message" workflow.

I'm using Umbraco 12.3.5 and Umbraco Forms 12.2.0.

---
_This item has been added to our backlog AB#36197_

**Comment by dtng95** [comment]
Hi @shropgov-neil ,
Thank you for reporting this issue.
A fix has been made and will be included in the next release/patch
