### ISSUE TITLE
Missing Package Files

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco.Forms.Issues#1134]
https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-type

It says under Backoffice View::

_If you do not have the original \wwwroot\App_Plugins\umbracoforms\ folders/files they can be downloaded. This can be done from the 'Package Files' section of the [Umbraco Forms Package](https://our.umbraco.com/packages/developer-tools/umbraco-forms/#tab-package). It will typically be named UmbracoForms.Files.{version}.zip._

However, the link does not have the latest file version files.

**Comment by AndyButland** [comment]
Looks like the documentation is out of date here, I'll get it updated.

These files are now shipped as part of a "razor class library" with Forms, so you won't find them on disk.  However if you do want to reference any angularjs client-side assets shipped with Forms you can view and extract them from the [Umbraco.Forms.StaticAssests NuGet package](https://nuget.info/packages/Umbraco.Forms.StaticAssets/13.0.0).
