### ISSUE TITLE
Cannot delete a form in Umbraco Forms

### ISSUE THREAD

**Issue by richard-arkom** [umbraco/Umbraco.Forms.Issues#1135]
Cannot delete an Umbraco Form in the backoffice.

### Specifics

Umbraco 10.8.2
Umbraco Forms 10.5.2

Tried on Edge and Chrome

### Steps to reproduce

Create a new test Umbraco form
Try to delete the form

### Expected result

The form just gets deleted

### Actual result

Red Umbraco error message at the bottom of the browser window:

Request error: The URL returned a 404 (not found):
backoffice/UmbracoForms/Form/DeleteByGuid

**Comment by AndyButland** [comment]
I'm not able to replicate this I'm afraid,  Let me just play back what I've done in case you spot any differences, and if not, maybe you can see what might be different with your setup:

```
dotnet new install Umbraco.Templates::10.8.2
dotnet new umbraco --name TestFormDelete
cd .\TestFormDelete\
dotnet add package Umbraco.Forms --version 10.5.2
dotnet run
```

Then clicked through the installed (using SQLite), logged in, created a form and confirmed I could delete it.

**Comment by richard-arkom** [comment]
Steps seem right.

I’ve got it on 2 customer sites now, where we’ve just updated them to Umbraco 10.8.2 and Forms 10.5.2 and neither can delete forms.


***@***.***

**Comment by richard-arkom** [comment]
![form delete](https://github.com/umbraco/Umbraco.Forms.Issues/assets/94534018/e5e5f2e5-837b-4efc-891c-df39df9a1957)

**Comment by richard-arkom** [comment]
It lets me delete the form locally, but not on the server

**Comment by AndyButland** [comment]
Maybe some caching going on then following the upgrade?
https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html

**Comment by richard-arkom** [comment]
Tried altering the the Version: but still the same.  However just tested a form delete on another Umbraco Forms site which is on Umbraco 10.6.1 and Forms 10.3.3 and that also won't let us delete a form.

**Comment by richard-arkom** [comment]
Tested a fresh Umbraco 10.8.2 / Forms 10.5.2 on our server.  Looks like our IIS server is blocking the 'DELETE' verb which the form delete seems to be using a 'DELETE' request (should it be ??)

**Comment by AndyButland** [comment]
That is what is being issued from the front-end, so makes sense:

```
return $http.delete(apiRoot + "DeleteByGuid?guid=" + id);
```
