### ISSUE TITLE
Umbraco.Forms 13.0.0 The reference to "umb://forms" uses a relation type "umbForm" that is not an automatic relation

### ISSUE THREAD

**Issue by PBHansen** [umbraco/Umbraco.Forms.Issues#1143]
### Bug summary
When saving Umbraco Forms in a block grid editor, we see the following error in logs:
The reference to "umb://forms-form/468e0434-d1ad-497a-80f8-8b512a5b19ca" uses a relation type "umbForm" that is not an automatic relation.
Error occurred executing "workItem".
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/8962756/468e0434-d1ad-497a-80f8-8b512a5b19ca)

The form is saved correctly, and works as it should, the relations are however missing.

### Specifics
* Umbraco started as Umbraco 12 project
* Forms are added to the page using the Form Picker data type, within a Block Grid data type.
* Error when inserting or editing an already existing form (https://github.com/umbraco/Umbraco.Forms.Issues/issues/1129)
* Upgraded to Umbraco 13.0.3 and Umbraco.Forms 13.0.0
* Forms can be edited and 'works', and errors only showing up in logs
* Form relations are missing

### Steps to reproduce
Add a form to a page.
Publish the page.

### Expected result
Expected form relations to show up, and no error in log.

### Actual result
Form relations are not added, and error is logged:
The reference to "umb://forms-form/468e0434-d1ad-497a-80f8-8b512a5b19ca" uses a relation type "umbForm" that is not an automatic relation.
Error occurred executing "workItem".

**Comment by rcisneros138** [comment]
We are also having this issue after the upgrade to 13.

**Comment by AaronSadlerUK** [comment]
Also having this issue in the 13.0.1

**Comment by AndyButland** [comment]
The fix for this will come in the CMS from the PR linked above.  In the meantime if you prefer to turn off the Forms relation tracking you can do, via [this configuration setting](https://docs.umbraco.com/umbraco-forms/developer/configuration#disablerelationtracking).
