### ISSUE TITLE
"Message on Submit" expects a string but gets an object - Returns 400 Bad Request 

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco.Forms.Issues#1145]
We have a website which as on Umbraco 10.7.0 and Forms 10.3.1 - We upgraded to Umbraco 13.0.1 and Forms to 13.0.0.

We are currently setting up a new part of the website, where we are heavily using Forms, where we have encountered some strange issues with the "Message on Submit".

When we edited the field, the object is updated and we think that "Message on Submit" requires a string but it gets an object, like this.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/9005889/f23b10a8-e31e-432d-bf5a-456af38b24c7)

Which results in an 400 Bad Request error, like the following on a POST to /umbraco/backoffice/UmbracoForms/Form/SaveForm

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/9005889/45432021-85a4-45c4-ae96-c268cb756923)

This is the error we are getting,

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/9005889/4651301c-1c46-414d-a433-9662b4840717)

My guess is that this is releated to the PR which allows blocks in the RTE (https://github.com/umbraco/Umbraco-CMS/pull/15029), but we'll have no use of that.

**Comment by AndyButland** [comment]
I haven't been able to replicate the specific error, but I can see some issues here when switching between plain and rich text.  As you have suspected, we haven't updated this to reflect the changes in the rich text property value now being an object.  We'll get that fixed up for the next patch release - due next week - and hopefully that'll sort the problem you've found too.

**Comment by AndersBrohus** [comment]
Sounds great @AndyButland, let's hope it fixes our issue aswell :)
