### ISSUE TITLE
Webhooks for WorkflowExecution

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco.Forms.Issues#1151]
Is it a good idea to add a number of webhook events for Umbraco Forms? For example, I would like to set up a webhook for when a workflow fails, so that we are notified and can check what is wrong.

It would be great if something like this could be configured in the same way as within the CMS. Something like this: 

```csharp
public class ApplicationComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.WebhookEvents()
            .AddForms(formsBuilder => formsBuilder.AddWorkflow());
    }
}  
```

This would then add webhook events for the following notifications, for example:

`WorkflowExecutionFailedNotification`
`WorkflowExecutionCancelledNotification`
`WorkflowExecutionCompletedNotification`

---
_This item has been added to our backlog AB#37295_

**Comment by AndyButland** [comment]
Webhooks for workflow execution will be part of the next feature release, 13.1.
