### ISSUE TITLE
Saving form with duplicate alias

### ISSUE THREAD

**Issue by ludwighedebynltg** [umbraco/Umbraco.Forms.Issues#1152]
When saving a form that has has 2 questions with the same alias. You get no error message, the save button spinner just keeps spinning.

Reproduction
------------

1. Go to the forms tab and create a new form.
2. Give the form a name.
3. Add 2 questions (any type) and give them the same alias.
4. press save

### Specifics
Umbraco 13.0.3
Umbraco.Forms 13.0.1
https://localhost:44341/umbraco#/forms/Form/edit/-1?template=&create=true

### Expected result

An error message or some kind of indication that the its not possible to save the form when 2 questions have the same alias.

### Actual result
The save button spinner just keeps on spinnin forever.
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/155434196/8dc26453-cbde-4261-a795-66051645bebb)

The error from the saveform post:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/155434196/14d70442-19fd-44e4-81f2-5ba077ad119d)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/155434196/47adced9-ddb3-49a5-a697-adeb9fab5af3)

---
_This item has been added to our backlog AB#37077_

**Comment by AndyButland** [comment]
Looks like this was a regression from a previous patch as part of the fix to [issue 1002](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1002).  We'll fix this in the next round of patch releases to ensure the error messages for this state are properly displayed.
