### ISSUE TITLE
Umbraco 14: How are you going to handle the UI changes?

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Forms.Issues#1153]
Hello!

A client of mine is considering using Umbraco Forms for the immediate future. However, he's concerned about Umbraco 14 and the new backoffice UI. His question is as follows: 
- Are you going to be using an Angular bridge to get the old UI working ASAP?
- Are you rewritting the UI into Web Components?
- Are you rewritting the UI into a different framework that is going to be loaded up as a Web Component?

The reason we/he would like to know is what this means for the extensibility of the Forms logic in the UI. Web Components and whatever has already been shown what is possible in the new Backoffice, is obviously the preferred way.

**Comment by nathanwoulfe** [comment]
Hey @LennardF1989

Quick and easy for the three bullet points:
- No Angular bridge - Forms for Umbraco 14 will be a new UI layer
- Yes to web components - Lit all the way
- No to different framework - Forms will be written on the same stack as the new Backoffice

As for impacts on extensibility, that remains to be seen. Intention would be like-for-like, how that works in practice will become clearer as we progress the v14 build.
