### ISSUE TITLE
Handling dropdown values with quotation marks and conditions

### ISSUE THREAD

**Issue by D0LBA3B** [umbraco/Umbraco.Forms.Issues#1164]
I have a dropdown that contains a value with a quotation mark.
Item -> "Bon d'achats" (Voucher)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/99276828/08975dfe-4155-40ee-945a-c9cf51bd0984)

I have created a condition on this value, to display another dropdown named "Liste de magasins" (shop list).

Condition:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/99276828/2919ea3e-1c83-41d9-b334-bda809dd4f23)

When I select the value subject to the condition, this condition is activated but declares an error in the console

### Specifics

Chrome Version 121.0.6167.161 (Official Build) (64-bit)
Umbraco.Forms 7.5.9
Umbraco version 7.15.10 assembly: 1.0.8321.19798

### Actual result

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/99276828/6572672b-6eb6-4f2e-b28d-13634e9f3542)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/99276828/6c03c22c-0249-432a-b86c-332efe79a2ea)

**Comment by AndyButland** [comment]
I'm afraid Forms 7 is now "end of life" and we aren't working on any bug reports or releasing patches for this version.  Hence I'll have to close this as an issue we won't be looking at, unless it's reopened with a similar report for a supported version (currently 8, 10, 12 and 13).
