### ISSUE TITLE
E-mail not sent to recipient listed in BCC Email field on Send email with template (Razor) workflow task

### ISSUE THREAD

**Issue by mrhighstone** [umbraco/Umbraco.Forms.Issues#1165]
When using the Send email with template (Razor), the email is not sent to the recipient listed in the BCC Email field.
This was discovered in Umbraco 8.18.9 with UmbracoForms 8.13.13

Reproduction
------------

- Create a simple form, add the Send email with template (Razor) workflow.
- Fill in the Recipient Email, CC Email and the BCC Email fields with different e-mail addresses.
- Submit the form and note that the e-mail is delivered to the recipients listed in the Recipient Email and CC Email fields, but not to the recipients listed in the BCC field.

**Comment by AndyButland** [comment]
What version of Forms are you using please @mrhighstone?

**Comment by mrhighstone** [comment]
> What version of Forms are you using please @mrhighstone?

This was discovered in Umbraco 8.18.9 with UmbracoForms 8.13.13

**Comment by mrhighstone** [comment]
Never mind. Due to a hiccup the settings were not saved correctly. Just verified the BCC email was received.
