### ISSUE TITLE
Version control on all default Umbraco Forms

### ISSUE THREAD

**Issue by paulkok** [umbraco/Umbraco.Forms.Issues#1167]
We are using Umbraco forms for a lot of clients who design their own Umbraco Forms with it. There is no version control on the forms. Therfor we can never see if anyone/who changed a form or revert it to a previous version. Adding version control will give a lot of value because you can temporarily make additions to a form and revert it, but also gives us the possibility to train users more based on their changes.

**Comment by AndyButland** [comment]
Agree this would be a nice feature to look into adding at some point and it's been requested for some time.

I'll close this issue though and associate it with https://github.com/umbraco/Umbraco.Forms.Issues/issues/5 which is where the request was first logged.
