### ISSUE TITLE
Umbraco Form Theme picker bug with "Close" tab button

### ISSUE THREAD

**Issue by SeananG1246** [umbraco/Umbraco.Forms.Issues#1174]
A brief description of the issue goes here.

There is currently a bug when trying to use the Umbraco Forms theme picker the button to close the theme picker tab does not work making it so you have to select a theme then remove that theme.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

There is currently a bug when trying to use the Umbraco Forms theme picker the button to close the theme picker tab does not work making it so you have to select a theme then remove that theme.

### Specifics

I am currently using: 
- Umbraco Version 13.1.1
- Umbraco Forms Version 13.0.2

### Steps to reproduce

To reproduce the steps:
- Create a doc type
- Add the property UmbracoForms.ThemePicker
- Use newly created property (I used it within a BlockList) and then click on the button to select a theme
- Try to click the close button in the bottom right hand corner of the tab

### Expected result

Expected result would be for the tab to close.

### Actual result

Nothing happens when clicking the button.

**Comment by AndyButland** [comment]
Thanks for the report - we'll fix this up in the next release.
