### ISSUE TITLE
Translation uses Default language instaed of context language

### ISSUE THREAD

**Issue by yawkale** [umbraco/Umbraco.Forms.Issues#1175]
Translation on field labels or magic strings uses Default language instaed of context language, testet on version 13.0.1 and 13.0.2

### Steps to reproduce

1. Create sample form
2.  change label to use dictionary
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/ad324d45-9a2f-47d2-9a89-3ae8254e37b0)
3. Add language - FRANCH is default 
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/0bf0c848-cd04-4c31-bd54-2d6a39f989ef)
4.  Add translation 
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/1c1eee86-6bfa-4419-b83a-081e14499ccc)

5.  add from to view in RTE or template![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/d5c7d4a7-b148-4806-8ece-cf0f5a478285)
6. Define hostname and culture
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/4151d1ce-9221-4ffa-a4ba-7b0cec72d091)

7. Regular dictionary show as expected, form show by default language 
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/10168594/13ca1f28-7448-4ec9-b05c-a461f2d72ddc)

### Expected result

label shown in english

### Actual result

label shown in french

**Comment by AndyButland** [comment]
Thanks for the report.  We had a similar issue raised last week via support channels and will be including a fix in the upcoming 13.1.
