### ISSUE TITLE
Make it easier to see which workflow has been applied

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1183]
I noticed on a project it we difficult to see which mail workflow was used as "Send email" and "Send email with template (Razor)" use same icon. However when more familiar with these one will noticed the fields are different.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/b81b8103-266c-4721-bad9-46637eca5c6f)

Perhaps it could show the workflow type in the dialog as label?

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/74ca931e-639d-4fee-8555-002c74fa6cfa)

**Comment by AndyButland** [comment]
Good point that this isn't obvious once you've created it.  We'll add details of the type from the next releases:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/c21f1245-8b45-463b-a817-0b8b9d1ee6ed)

**Comment by bjarnef** [comment]
@AndyButland was this released in v13.2.0 but on an Umbraco Cloud project with Forms v13.5.0 I can't see this.

**Comment by AndyButland** [comment]
This specific implementation got reverted and modified to do something similar, to better align with other dialogs.

**Comment by bjarnef** [comment]
Yes, it is displayed as description.

**Send Razor Email**

<img width="553" height="75" alt="Image" src="https://github.com/user-attachments/assets/b7e46c14-4bf1-4f51-824e-8cd8ef65abca" />

**Custom (inheriting razor email template workflow)**

<img width="296" height="78" alt="Image" src="https://github.com/user-attachments/assets/28c433b5-4a55-4766-8fc4-63516d34c8f7" />

It use workflow `Description` property though and not the workflow `Name`:

<img width="796" height="450" alt="Image" src="https://github.com/user-attachments/assets/7eb1d80c-ea85-406d-803e-b157edd5b2b9" />

I still think it would make sense to show workflow name in a field below, but it can't show it in heading name field as it is editable and filled with whatever value one may want here.
