### ISSUE TITLE
Copy workflow to other forms

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1185]
I needed to add a "Send email to user" workflow to existing forms, but it was a bit tedious to do for a lot of forms.

For new forms we can configure default workflows, but I think copy of workflow could be useful as well.
https://docs.umbraco.com/umbraco-forms/developer/extending/customize-default-workflows

---
_This item has been added to our backlog AB#46024_

**Comment by AndyButland** [comment]
I can see the value certainly.  There is a complication in that workflows have dependencies on the form (e.g. those that allow you to pick field for the form).  If copying, the fields won't exist (at least with the same IDs).  But we'll give it some thought - maybe for these we can match by alias and if missing then just that workflow setting remains empty.

**Comment by skttl** [comment]
I think it would be fair to nullify settings that have dependencies on the form the workflow is copied from.
