### ISSUE TITLE
dotnet add package Umbraco.Forms is NOT adding forms to my project

### ISSUE THREAD

**Issue by Developing4thePelican** [umbraco/Umbraco.Forms.Issues#1188]
I have a project im trying to add umbraco forms to. I've done the install - and received the following confirmation:

C:\Umbraco Sites\SFMDev>dotnet add package Umbraco.Forms
  Determining projects to restore...
  Writing C:\Users\P00000000A\AppData\Local\Temp\tmp7D13.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Umbraco.Forms' into project 'C:\Umbraco Sites\SFMDev\SFMDev.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/umbraco.forms/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/umbraco.forms/index.json 220ms
info : Restoring packages for C:\Umbraco Sites\SFMDev\SFMDev.csproj...
info : Package 'Umbraco.Forms' is compatible with all the specified frameworks in project 'C:\Umbraco Sites\SFMDev\SFMDev.csproj'.
info : PackageReference for package 'Umbraco.Forms' version '13.0.2' updated in file 'C:\Umbraco Sites\SFMDev\SFMDev.csproj'.
info : Assets file has not changed. Skipping assets file writing. Path: C:\Umbraco Sites\SFMDev\obj\project.assets.json
log  : Restored C:\Umbraco Sites\SFMDev\SFMDev.csproj (in 1.33 sec).

When I run the project per instructions - I do not see "create a form" i only see the "Read more" option that redirects me back to the https://our.umbraco.com/packages/developer-tools/umbraco-forms/ page.

Any help would be greatly appreciated as we have purchased a license for forms, but can't even install it to test it out.

**Comment by AndyButland** [comment]
What version of Umbraco CMS are you running please?

**Comment by Developing4thePelican** [comment]
Umbraco version 11.2.0

**Comment by AndyButland** [comment]
OK, so you'll need to install a version of Forms compatible with that version, the most recent of which is [11,2,1](https://www.nuget.org/packages/Umbraco.Forms/11.2.1).

**Comment by Developing4thePelican** [comment]
Thank you - will try this shortly.

**Comment by AndyButland** [comment]
That should work OK, but it's worth noting Umbraco and Forms 11 are now out of support, so you won't be getting the latest bug-fixes and releases.  If you can, it might be worth you also upgrading your project to Umbraco and Forms 13, which are the latest long-term support versions.  More on this [here](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/).

**Comment by AndyButland** [comment]
I'll close this issue now given it looks to be just trying to install the wrong version.
