### ISSUE TITLE
DatePicker.cshtml is not picked up by themes

### ISSUE THREAD

**Issue by StefanoChiodino** [umbraco/Umbraco.Forms.Issues#119]
As per https://github.com/umbraco/Umbraco.Forms.Issues/issues/46.

We would like `DatePicker.cshtml` to be themable because pickaday has a few accessibility issues that we would like to fix, and to do that we plan on copying the file and changing it.

Also, as per #109 not allowing this to be vendored in themes means that certain changes in Umbraco Forms may not be compatible with certain themes.

**Comment by bergmania** [comment]
PR: 
- V7: https://github.com/umbraco/Forms/pull/261
- V8: https://github.com/umbraco/Forms/pull/260
