### ISSUE TITLE
Forms dashboard doesn't show entry statistics when users can't manage forms

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco.Forms.Issues#1192]
### Bug summary

Users who don't have `Manage forms` permissions but do have permission to `View entries` don't see the number of entries in the Forms dashboard. The list stays empty.

Reproduction
------------

### Specifics

Umbraco 10.8.2
Umbraco Forms 10.5.3

### Steps to reproduce

- Create a user who can only view form entries.
- When viewing the Forms section, notice there are no blocks shown that show the amount of entries for each form.

### Expected result

![afbeelding](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6131869/46d79296-345c-44bf-9896-900de16725e1)

### Actual result

The section on the right stays empty.

**Comment by AndyButland** [comment]
Thanks for reporting @SteveVaneeckhout - we'll get this fixed in the next round of patch releases.
