### ISSUE TITLE
Call a javascript function on form submission.

### ISSUE THREAD

**Issue by Namrata-V2** [umbraco/Umbraco.Forms.Issues#1193]
Can someone please share their insights on how can we call a javascript function during form submission in Umbraco frontend. 

Since, I am implementing an invisible recaptcha we have to trigger `grecaptcha.execute();` to generate a client token.

I have to execute this script on form submission so that the recaptcha token gets generated.

```
<script type="text/javascript">
        function  onSubmit(event){
            event.preventDefault();
            grecaptcha.execute();
        }
    </script>
```

And then in the `ValidateField` method using

```
 var reCaptchaResponse = context.Request.Form["g-recaptcha-response"].ToString();
```

I can get the client token for validation.

Any leads are appreciated !

**Comment by Namrata-V2** [comment]
What worked for me was adding ``` Html.AddFormThemeScriptFile("https://www.google.com/recaptcha/api.js"); ``` in the custom field type triggered the javascript function and adding a data-callback attribute in the div.

```
 <div class="g-recaptcha"
             data-sitekey="@siteKey"
             data-callback="onSubmit"
             data-size="invisible">
        </div>
```

**Comment by AndyButland** [comment]
You can see how we've implemented this in the existing reCAPTCHA field by looking at the file `staticwebassets/Assets/recaptcha.v3.init.js` which you can find within the `Umbraco.Forms.StaticAssets`  NuGet package (viewable online [here](https://nuget.info/packages/Umbraco.Forms.StaticAssets/13.1.1)).

Hope that helps, but I'm going to close this as the issue tracker isn't really intended as a place for general questions, I'd suggest going to the [Umbraco forum](https://our.umbraco.com/forum/umbraco-forms/) for the product where you'll likely get a wider audience for questions you have.

**Comment by Namrata-V2** [comment]
Thanks @AndyButland for sharing the great insights. I have followed similar approach of using a timer function and works quite well for my use case.
