### ISSUE TITLE
Add "body" rich text copy field for Razor email workflow in addition to "header" and "footer"

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1198]
I noticed on a Umbraco Cloud project, where the customer have forms with worksflows, they have two workflows assigned.

**New website request** which use the standard email workflow and has a message field. This is sending an email internally to notify their marketing department.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/bbca0a42-f1ce-42d1-ad55-9cee2fb2ca2e)

**Send email to user** which use the send email (razor) workflow, which send a copy of the form submission to customer. This has fields for header and footer. However there it no field to write a message in "body" of email.

The header and footer text are often a smaller text in header and footer of email template. I think a body text could be useful as well, e.g. inserted above form submission and the customer requested this feature.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/6af97e15-9165-4429-9d4a-b99ade50c87b)

We could of course create our own workflow extending the default one.

A side note is that I think the form email template, should use a picker similar to template picker in macros to be consistent with most other pickers in core.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/1c0742cc-9434-4589-b0a9-11eefea30819)

Umbraco 12.3.9
Forms 12.2.3

**Comment by bjarnef** [comment]
Yes, I guess it depends on the design: https://popupsmart.com/encyclopedia/email-header-body-footer

If the email template has a dedicated header and footer one may want to use the header and footer fields here, while having a message field in the regular body text.

**Comment by AndyButland** [comment]
I see.  Yes, agree you could have a design where you want to have separation between the header and body, even if both are above the form submission detail.

**Comment by AndyButland** [comment]
We'll include this additional field on the workflow in the next minor releases for Forms 13 and 14.
