### ISSUE TITLE
Forms: Magic string for form field does not use alias

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#120]
According to the documentation, the current form field values can be replaced using the magic string format `{myAliasForFormField}` (https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Magic-Strings/#parsing-umbraco-form-field-items), but that is not the case.

Reproduction
------------
Create a field with different text in the caption and alias and use the magic string format `{myAliasForFormField}` in a workflow or in the submit message. This magic string is not replaced using the alias, but a re-formatted caption (lowercase, spaces removed, etc.).

### Expected result
Actually use the field alias and have the field value in the resulting string.

### Actual result
The correct field value can't be found and is replaced with an empty value.

---
_This item has been added to our backlog [AB#5705](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5705)_

**Comment by MrCosmo** [comment]
I'm experiencing the same issue when I use a magic string to send an email to the form submitter.

Fieldalias: email
workflow: send email
receiver email: {email}

**Comment by ronaldbarendse** [comment]
A fix would probably be quite easy to do, as it just needs to use the alias instead of the caption (and probably also skip the re-formatting, as aliases can only contain any of the `StringExtensions.UmbracoValidAliasCharacters`).

The difficulty will be in not breaking existing workflows, as the names could change and therefore not replace the magic string with the correct value anymore. So that would mean this should be marked as a breaking change and correctly documented.

The other option is to opt-in to the change via a configuration setting (in `UmbracoSettings.config`). New installs could enable this setting by default and use the alias, but upgrades would still use the caption, unless manually enabled. This setting should (off course) also be documented and be referenced in the linked Umbraco Forms documentation page.

**Comment by Ultradata-CXP** [comment]
Also lost a lot of time with this one.  Also following: https://our.umbraco.com/forum/umbraco-forms/94589-magic-strings-not-appearing. :-)

**Comment by AndersBrohus** [comment]
Same issue we got, hopefully this would get some attention soon. If looking at the same forum post as above the forum post is back from november :)

**Comment by AndersBrohus** [comment]
We are using Umbraco 7.14 and Forms 7.0.6 on Umbraco Cloud :)

**Comment by ronaldbarendse** [comment]
Not sure why this isn't included in the upcoming bugfix releases (7.1.2 and 8.1.2) and the documentation also isn't updated to reflect the current functionality (e.g. using the caption instead of the alias). Seems like an easy thing to fix: add a setting for backwards compatibility and an `if` statement in the replacement logic...

**Comment by xsiruse** [comment]
Hi to all!
is there any solution to this issue?
it seams that this bug occurs not only in magic strings ... I've noticed, that the same behavior occurs in native workflows regarded to XML like Post as XML, Save to XML and so on - the node in XML is parsed from caption, but not alias.

P.S.: I'm using Umbraco 7.10 with Forms 7.0.0

**Comment by mzajkowski** [comment]
And we got hit by the same issue now. Bumping it up.

**Comment by hfloyd** [comment]
Yep, I've come across this one several times.

**Comment by FransdeJong** [comment]
I ran in to the same issue now. Would be great if this could be looked at.

**Comment by TimGeyssens** [comment]
so any update so far...? Seems like an easy fix... and serveral gold partners are running into this issue

**Comment by TimGeyssens** [comment]
![Tumbleweed](https://thumbs.gfycat.com/ObviousBlandJoey-size_restricted.gif)

**Comment by nul800sebastiaan** [comment]
Unfortunately I have no updates. the workaround is to lower-case the caption and use it for now.

From what I can read quickly this would be a breaking change? People who are already using the caption would now need to switch it out. I'm sure it can be fixed by looking at both the caption or else the alias.. not ideal but could work.

I'll see if we can fit this into the next sprint (we just started a new one this week, so hold the tumbleweed... 😉)

**Comment by TimGeyssens** [comment]
Yes but when lowercasing the name/caption you run into this: https://github.com/umbraco/Umbraco.Forms.Issues/issues/35 (so if you have 2 with the same caption you can never access them both)

**Comment by TimGeyssens** [comment]
Also check out gold support ticket 38700, I outlined a possible solution(s) that would be backwards compatible

**Comment by TimGeyssens** [comment]
@nul800sebastiaan sorry if this is mentoined somewhere but can't seem to find it, how can we see what is part of current sprint? And how can we influence what will be part of future sprints?

**Comment by nul800sebastiaan** [comment]
@TimGeyssens - I have properly documentating this on the list but there's some descriptions on the `state/` labels: https://github.com/umbraco/Umbraco.Forms.Issues/labels?page=2&sort=name-asc

**Comment by TimGeyssens** [comment]
@nul800sebastiaan thanks, and how can we as clients/partners/gold partners have any impact on what will be part of the next sprint? Cause now it's been reported by a gold partner to support in 2018, considered not a prio (so ended up on issues here on github), then backed by several (gold) partners in the following months on here (that are also facing the issue)...  update after months is a workaround... then when getting the attention of Niels on twitter it get's some possible love... (still to confirm)...

**Comment by nul800sebastiaan** [comment]
@TimGeyssens We are currently working on several forms initiatives, this issue getting more attention is unrelated to any conversations on twitter. The best way for partners to reach out is through your regular partner channels with HQ or directly to our product team at product@umbraco.com.

**Comment by TimGeyssens** [comment]
@nul800sebastiaan sure but that still doesn't answer how as we (gold) partners can have some impact on what we consider necessary bug fixes...as a gold partner you are supposed to have influence on Umbraco dev https://umbraco.com/partners/become-a-partner/gold/ but if you can't even have a bug fixed on a commercial product (that is effecting multiple gold partners)... I kinda doubt that selling point

**Comment by nul800sebastiaan** [comment]
@TimGeyssens I think you're referring to "bug fix warranty"? The details of that program are listed here: https://umbraco.com/umbraco-cms-pricing/bug-fix-warranty/. For additional questions on that I will have to refer you to the partner channel.

**Comment by TimGeyssens** [comment]
Ok will take it to that 'closed' channel, but what severity would this bug be cataloged in? I'm guessing Severity 3 or 4... so maximum 40 business days... and this one has been reported (by gold partner) 17 Oct 2018.... maybe an idea to also tag the bugs with a severity label, at least that way we can have a transparent fix date....

**Comment by nul800sebastiaan** [comment]
I am not the one responsible for that, so that's why I need to redirect you to the right channel.

**Comment by TimGeyssens** [comment]
@nul800sebastiaan okido got in touch, will post back when I get more info... ow and I misread the Gold partner bug fix warranty, it's 7 days for security vulnerabilities, site stability issues, and bugs resulting in loss of data... for the rest it's only Umbraco Enterprise support that give a 40 day bug fix warranty https://umbraco.com/umbraco-cms-pricing/

**Comment by TimGeyssens** [comment]
Ah wait Custom Enterprise support plans... and it's just a fictional example... on https://umbraco.com/umbraco-cms-pricing/bug-fix-warranty/ so the 40 days isn't right

**Comment by TimGeyssens** [comment]
The Gold Partner Support ticket 
![UmbracoFormsBug](https://user-images.githubusercontent.com/2988648/76758391-e4801080-6789-11ea-8b27-c31f0f5a97d4.png)
(dunno why it has the status solved)

**Comment by TimGeyssens** [comment]
And it seems it was reported even 2 years earlier https://issues.umbraco.org/issue/CON-1208#tab=Comments 10 Nov 2016

**Comment by nul800sebastiaan** [comment]
Thanks @TimGeyssens - as said before we are currently working on several forms initiatives. 👍

**Comment by nul800sebastiaan** [comment]
I saw your tweet around this Tim.. Maybe you didn't get the message the first time you asked: 

- This issue is marked as `state/sprint-candidate`
- That means we're trying to get it fixed in one of our next few sprints
- We do sprint planning every other week 
- The next sprint planning is Monday next week

I know we're all sad that this has not gotten any attention but we also can't drop all of our work every time there's a tweet, I hope you understand that we need to follow our process as well.

**Comment by TimGeyssens** [comment]
Of course I totally understand that, just a bit more transparency would be nice :) Since I get conflicting info from the different 'official' channels... so that's why I asked a couple of additional questions.... but I'll wait it out, few weeks extra to the almost 4 years won't have a lot of impact

**Comment by TimGeyssens** [comment]
@nul800sebastiaan and to be fair, the first time I asked you went quite https://github.com/umbraco/Umbraco.Forms.Issues/issues/35

**Comment by nul800sebastiaan** [comment]
I think we've been very transparent that this has not been a big priority for us. 🙈

> to be fair, the first time I asked you went quite #35

Okay, of course I meant I've been responding to your questions and remarks about this for the last 5 days now. 

I really don't want to do this "he said, she said" thing here, it's not very productive. We're on it.

**Comment by TimGeyssens** [comment]
Perfect, keep us updated :)

**Comment by TimGeyssens** [comment]
And sorry but acting like a jerk seems to be the only way to get things moving... since the folks before 12 Feb didn't even get a response... but I've taking that up with major friends maker Anders and the product team.

**Comment by nul800sebastiaan** [comment]
I totally understand the reason why you are frustrated, as has been mentioned before, we're working on improvements and that takes some time to gear up as well. I expect we'll see some more results of that over the next few weeks.

**Comment by warrenbuckley** [comment]
Fixed in upcoming 7.4.0 & 8.4.0

**Comment by Frost117** [comment]
Just tested this out on version 8.4 and it doesn't seem to work.

I've had a version running 8.3.1 where it did work and now in 8.4 it doesnt.

Here are the images from 8.3.1
![image](https://user-images.githubusercontent.com/32164310/78348390-3b675180-75a2-11ea-9e36-bba4db739a01.png)

![image](https://user-images.githubusercontent.com/32164310/78348407-415d3280-75a2-11ea-8048-e09381aa7347.png)

![image](https://user-images.githubusercontent.com/32164310/78348418-4621e680-75a2-11ea-9c3c-ae8e0d53b21b.png)


And now in version 8.4.0, it looks like this:
![image](https://user-images.githubusercontent.com/32164310/78348473-5b971080-75a2-11ea-9891-3f6281178e95.png)

**Comment by jevgenigeurtsencolours** [comment]
In addition to @Frost117 his findings, I've debugged the new Umbraco.Forms.Core.dll of the 8.4.0 patch and noticed the following method (namespace `Umbraco.Forms.Core.Data.Helpers.StringExtensions`):

		// Token: 0x0600062D RID: 1581 RVA: 0x00012A78 File Offset: 0x00012A78
		public static string ParsePlaceHolders(HttpContext context, Record record, Form form, string value, Hashtable pageElements)
		{
			string text = value;
			text = DictionaryHelper.GetText(text);
			bool flag = pageElements != null;
			if (flag)
			{
				text = StringHelper.ParseContextPlaceholders(context, text, pageElements);
			}
			// snip
		}

The `StringHelper.ParseContextPlaceholders` method is responsible for resolving the actual value using the magic string. Although, the method call is never hit, as `pageElements` is always null. I'll try to do some more debugging and see if I can find out why it doesn't pass the `pageElements`.

**Comment by TimGeyssens** [comment]
Oh noes... also small q, now that it is fixed, does it fall back to how it was? So it doesn't break existing installs?

**Comment by ronaldbarendse** [comment]
@TimGeyssens I have the same question, as all my suggestions from https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-481703810 are left unanswered and @nul800sebastiaan confirmed this will likely be a breaking change in https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-597638399.

Now @warrenbuckley only commented this issue is fixed, but I don't see any breaking changes or other type of documetation (not in the [blog post](https://umbraco.com/blog/product-update-april-2nd-2020/) and [Our Umbraco package](https://our.umbraco.com/packages/developer-tools/umbraco-forms/)).

If it's fixed by using the alias instead of the caption, upgrading will break existing placeholders (I know I've used them, as I really needed data from the fields and the alias/caption weren't equal). Having it replace placeholders for both caption and alias would at least need a clarification, especially in what order they're replaced. Therefore, I already recommended adding a setting to specify whether the caption or alias should be used (and set it to caption on upgrade, leaving it to the default of alias on new installs).

**Comment by TimGeyssens** [comment]
Yup some details from HQ team would be appreciated... since now I assume it will fall back to the old way to avoid breaking existing installs...

**Comment by nul800sebastiaan** [comment]
I do believe the intention was to use the current ("wrong") way of using the lower-cased field name and if that doesn't give a result then to use the alias so as to be backwards compatible. 

We'll have to investigate all your comments above. Please note that this will take a while as most people are on Easter holiday, so we'll get back to this as soon as we can after Easter.

I'll close this issue and create a new one to track the bugs resulting from the changes in 8.4.0 so that we can make a distinction between the changes made for 8.4.0 and 8.4.1, issues should not be re-opened after a release has been made so that we can track new changes in the next version.

We'll track updates over here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/321

**Comment by TimGeyssens** [comment]
Ok thanks @nul800sebastiaan could you just let us know the following: ow that it is fixed, does it fall back to how it was? So it doesn't break existing installs?

**Comment by nul800sebastiaan** [comment]
I don't know Tim

> I do believe the intention was to use the current ("wrong") way of using the lower-cased field name and if that doesn't give a result then to use the alias so as to be backwards compatible.
> We'll have to investigate all your comments above.

**Comment by TimGeyssens** [comment]
Hey @nul800sebastiaan any update on what works and doesn't? Since we want to upgrade some sites... thanks

**Comment by TimGeyssens** [comment]
@nul800sebastiaan just the code snippet from before and after would also be appreciated, since now I don't even now what to test...

**Comment by nul800sebastiaan** [comment]
As mentioned before, we've moved this to a new issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/321 an update is posted there. Make sure to follow along on that issue!

**Comment by TimGeyssens** [comment]
If I need to follow all issues around this bug :p keeping track of the original makes more sense imho but ok following that one instead now
