### ISSUE TITLE
Date field label associated with hidden input

### ISSUE THREAD

**Issue by deadlyeyeball** [umbraco/Umbraco.Forms.Issues#1200]
The markup generated for a date field is like the following:

```
<label for="6d38f416-8a53-46ef-beed-30fa63eadb96" class="umbraco-forms-label">Date</label>
<div class="umbraco-forms-field-wrapper">
    <input type="hidden" id="6d38f416-8a53-46ef-beed-30fa63eadb96">
    <input type="text" id="6d38f416-8a53-46ef-beed-30fa63eadb96_1">
</div>
```

The label's _for_ attribute needs to reference the text input id with the _1 suffix.

**Comment by AndyButland** [comment]
Thanks for reporting this, and I agree it looks that these IDs should be reversed such that the label lines up with the text input.  We'll prepare that and release in the next round of patch releases for supported versions.
