### ISSUE TITLE
Magic Strings leaves a "}" in the result of the ReplyTo Email setting

### ISSUE THREAD

**Issue by keba74** [umbraco/Umbraco.Forms.Issues#1201]
I am using a magic string to fill the reply to email address.

I have a textfield called mejladress, and in the ReplyTo im using {{mejladress}}, when i receive the email, outlook shows me in the To field

This image shows the values i send in to the api (not using standard umbraco forms, im rendering my own form via the api)

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/c8ce202b-39a9-48ac-996e-e9594fea78f5)

Reproduction
------------

Create a form with a field to accept your email address, and in the replyto field use the magic string {{yourfieldname}}

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I have no condition or validation or field type on the form field

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/782cc62d-c541-47ec-99d6-80e6e5306a8d)

### Specifics

Umbraco 12.3.7
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/fe0e4439-a2c7-4dca-ab18-98f873803f57)

Forms 12.2.3 
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/960a9be1-629a-4b6f-99d8-aa338d195b76)

AND Forms 12.2.2
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/a7f34ae3-d75f-4605-9252-731b37803e2f)

### Expected result

A mail with the result of the input fields value as the reply to email address

### Actual result
See images above,

### HACK FIX

removing one of the } when using the magic string works, but this is not the correct way to use the magic strings.
Doing this works
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6916080/8c7dc69e-fd46-45cc-8909-6dfb4a0d42ac)

**Comment by AndyButland** [comment]
It looks like [we document using single curly braces for magic string that replace field types](https://docs.umbraco.com/umbraco-forms/developer/magic-strings#umbraco-form-field).  Is there a reason why you've found or read that the correct way is to use double braces please? Might be something historical I'm not aware of.

**Comment by keba74** [comment]
This was absolutely not an bug at all. using {{}} double squigglies must have just come out due to angular muscle memory. 

NO this has nothing to do with angular, but writing those squigglies so many times has been the culprit here.
