### ISSUE TITLE
Workflow triggers and executes even though conditions are not met

### ISSUE THREAD

**Issue by appstractkim** [umbraco/Umbraco.Forms.Issues#1206]
I have set up a form which includes a couple of fields that are visible based on conditions and I have a workflow which has three conditions - some of the workflow conditions are related to fields that have visibility conditions.

The issue is that the workflow triggers even though the conditions for the workflow to trigger are NOT met rendering the workflow conditions useless.

**So the BUG being reported here related to the workflow conditions.**

Reproduction
------------

### Bug summary

I am quite certain the bug relates to workflow conditions.

### Specifics
I am using Umbraco 12.3.9 and Umbraco Forms 12.2.4, but the bug has been present in earlier versions as well.
I am using Google Chrome (though quite sure this is irrelevant as the bug is a server side workflow related bug).
I have not checked on other browsers.
There are no error messages, but I can see the workflow is triggered even ALL if the condition are not met.

### Steps to reproduce
To reproduce create a form containing the following fields:

- Name (Short Answer - Mandatory)
- Concern (Single Choice - Mandatory - Concern 1, Concern 2)
- Select category (Single Choice - Mandatory - Category 1, Category 2, Category 3 - Show if Concern = Concern 1)
- Select department 1 (Single Choice - Mandatory - Department 1, Department 2, Department 3 - Show if Select category = Category 1)
- Select department 2 (Single Choice - Mandatory - Department 1, Department 2, Department 3, Department 4 - Show if Select category = Category 2)
- Consent (Data Consent - Mandatory)

![Screenshot 2024-04-17 at 10 46 13](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/4299d046-3a6f-4e2b-9973-fe3c98cc547e)

Added a workflow (Send email with template (Razor). The workflow has three conditions enabled and is set to RUN if ALL match:

- Concern IS Concern 1
- Select category IS Category 1
- Select department 1 IS department 1

![Screenshot 2024-04-17 at 11 13 26](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/f4ba4d9a-ff20-4c4d-accc-81cba63f5d95)

Now add the form to a content page and test filling in the form and submitting it. 

Do the following two form submissions:
- Submission 1
-- Name - "Test"
-- Concern - "Concern 1"
-- Select category - "Category 1"
-- Select Department 1 - "Department 1"

![Screenshot 2024-04-17 at 11 15 15](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/af046c76-41ab-487b-9c0b-5d53a736c651)

- Submission 2
-- Name - "Test"
-- Concern - "Concern 1"
-- Select category - "Category 1"
-- Select Department 1 - "Department 2"

![Screenshot 2024-04-17 at 11 15 07](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/0ef73e8f-985f-4f48-b408-625840dc60ad)

### Expected result
As the workflow is set up to (ONLY) RUN if ALL conditions match I would expect:
- Submission 1 to trigger the workflow to RUN
- Submission 2 to NOT trigger the workflow

### Actual result
What I see is the following:
- Submission 1 triggers the workflow to RUN (expected)

![Screenshot 2024-04-17 at 11 16 44](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/f0f2dc66-68cb-4f65-829e-44fc0cf98406)

- Submission 2 triggers the workflow to RUN (NOT expected - BUG)

![Screenshot 2024-04-17 at 11 17 12](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2151387/f5bdee94-3c9b-4630-9020-7f8318357a85)

There are no error messages in the logs.

**Comment by appstractkim** [comment]
For good measure I also receive the emails from the workflow in both cases - Submission 1 and Submission 2, where I only expect to receive the email in Submission 1.

**Comment by AndyButland** [comment]
Could you export your test form please and attach it to this issue?  That'll help ensure I have the same setup locally to try to replicate and resolve.  Thanks.

**Comment by AndyButland** [comment]
Don't worry about that - I've set it up, and can replicate.  It's going wrong somewhere in the checks we have in place to try to detect circular conditions.  Will be a bit of a head-scratcher to solve, but I think looking at your setup, couldn't you just create your workflow condition on only the "Department" selection?  Given that only appears when the conditions on the other two fields are met, you don't really need to replicate them in your workflow condition too.

**Comment by AndyButland** [comment]
Having reviewed I think we were unnecessarily checking for circular conditions for workflows. For fields we need this - field A could have a condition on field B, as well as vice versa, and this could lead to infinite loops - so we check for circular conditions.

With workflows we don't need this - workflows depend on fields, not on each other - so this was unnecessarily transferred over when we prepared conditions for workflows.

We'll update this with the next round of releases which should resolve the issue you've reported.  In my tests on a replica of your setup I'm now seeing the appropriate workflows executed.
