### ISSUE TITLE
Add e-mail sendername

### ISSUE THREAD

**Issue by Sibren** [umbraco/Umbraco.Forms.Issues#1207]
Right now, you can only specify the 'from' in Umbraco with an emailaddress, lets say 'mybeautifulemail@address.com'
Which means Gmail (and perhaps others) only show 'mybeautifulemail' as a name in your inbox and not a decent name.
I'd like to have the option to use a name too.

C# has this built in, but it seems Umbraco doesn't use it:
https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddress?view=net-8.0

My proposition would be something like this:
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/3531618/e9b262ec-0196-433b-a11f-33efae4f0b49)

**Comment by AndyButland** [comment]
I think you probably need to create this as a feature suggestion on the CMS issue tracker [here](https://github.com/umbraco/Umbraco-CMS/discussions).  What you've proposed is making changes to the CMS SMTP settings, that Forms will use, but need to be updated in the CMS itself.

I'll close this but would suggest you recreate over on that repository assuming you can't find discussion of the request already there.
