### ISSUE TITLE
RTE Link Picker creates localLink in email

### ISSUE THREAD

**Issue by wvduffelen** [umbraco/Umbraco.Forms.Issues#1208]
When an editor is configuring Header and Footer text in the workflow and wants to link to an internal page on their website it doesn't render in the mail and gets a a `/{localLink:umb://document/{guid}}`. 

When editing the source code you can see the (wrong) link is there already. 
![afbeelding](https://github.com/umbraco/Umbraco.Forms.Issues/assets/34159733/2638aa0f-c67e-42a8-a962-0c9444090d6b)

When rendering the email this is a `@Model.FooterHtml` and isn't parsing the URL to the right one. As alternative I tried to fill in the absolute URL (because it isn't working now) but that doesn't work as well. When the absolute URL is on the same domain as the website it removes this part and only has the relative part. 

We can edit the source code and edit the URL there but this isn't the way to go for an editor. Is there a way to parse to `localLink` to the right URL?

**UPDATE**: Even when editing the source code and add the absolute URL to the `href` part it removes the absolute path and only shows the relative part

**Comment by AndyButland** [comment]
We'll resolve this for the next minor release of Forms 13 and 14.  For 14, the functionality will only be available though once [this CMS issue](https://github.com/umbraco/Umbraco-CMS/issues/16631) is also fixed and released.
