### ISSUE TITLE
Issue #99 not resolved in version 7.1.0 - Incorrect casing of UFRecordFields still a problem

### ISSUE THREAD

**Issue by pmeliesIology** [umbraco/Umbraco.Forms.Issues#121]
Incorrect casing of UFRecordFields table in code.  Originally reported in Issue #99 

Reproduction
------------

### Bug summary

The Umbraco.Forms.Data.Storage.RecordFieldStorage class (in the Umbraco.Forms.Core assembly) references the UFRecordFields table name as "UFrecordFields" in the InsertRecordField(RecordField) and UpdateRecordField(RecordField) methods. The actual table name is UFRecordFields ("R" in "Records" is capitalized). This causes a "Table 'database_name.UFrecordFields' doesn't exist" error when using a MySQL database on a Linux flavor whose file system is case sensitive. The RecordFieldValueStorage class correctly uses "UFRecordFields". Please update the RecordFieldStorage class to use the proper casing.

### Specifics

We originally reported this bug as issue #99 (closed about 3 weeks ago).  After downloading version 7.1.0 this morning we found the issue still exists.

### Steps to reproduce

Use a MySQL database on a Linux system whose file system is case sensitive. This is not an issue in SQL Server or on Linux systems whose files systems are NOT case sensitive.

Setup a basic contact us form and try to submit the form. See the attached file to view the asp.net error page reporting this unhandled exception.

I am able to replicate the same error by issuing a basic 
```
SELECT * FROM UFrecordFields
```
 query directly against the database using DBeaver. Executing 
```
SELECT * FROM UFRecordFields
```
 works as expected.

### Expected result

No errors when using an Umbraco Forms form.

### Actual result

See attached error page with call stack. Rename to .html extension to view it in a browser".
[Table.Iology_CMS.UFrecordFields.doesn.t.exist.html.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/3009965/Table.Iology_CMS.UFrecordFields.doesn.t.exist.html.txt)

**Comment by pmeliesIology** [comment]
What are the odds that we can get this fix included and a new build produced relatively quickly?

**Comment by bergmania** [comment]
Damn the fix are rolled back in a merge (conflict) :(

I don't know a date for next release. But I can build a custom dll for you if you are interested?

New PR: https://github.com/umbraco/Forms/pull/265

**Comment by bergmania** [comment]
There is a nighly build with the fix available here 
http://nightly.umbraco.org/?container=umbraco-forms-nightlies
 
Name `7.1.1-alpha-20190327-004`. E.g take the dll's from https://umbraconightlies.blob.core.windows.net/umbraco-forms-nightlies/UmbracoForms.Files.7.1.1-alpha-20190327-004.zip and copy into the `bin` folder.

**Comment by pmeliesIology** [comment]
Thanks @bergmania - this will work.  I feel better knowing we're not the only ones who sometimes have issues with merge conflicts :)

**Comment by ronaldbarendse** [comment]
And that's why you should run integration tests 😜 Might be worthwile, as it could reduce a lot of bugs in new releases...
