### ISSUE TITLE
Email workflow incorrectly formatting dates

### ISSUE THREAD

**Issue by AlexAtVista** [umbraco/Umbraco.Forms.Issues#1214]
When using the "Send Email" workflow on a form that contains a date field, it appears in American date format and includes a time of 12am. It does not appear this way in the Umbraco Backoffice.

Reproduction
------------

### Versions

Umbraco.Cms: 13.2.0
Umbraco.Forms: 13.1.2

### Steps to reproduce

1. Create a blank form with a single date field
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/129270794/4a3df53e-2e8e-4c01-a325-405738822b7c)

2. Add a "Send Email" workflow to this form
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/129270794/1289f5df-0f7d-40d8-8999-e596cd3750cd)

3. Navigate to a page with this form and submit any date value

4. Check the form entry in backoffice is correctly showing the date value only
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/129270794/4cb25a6b-2e7d-40af-91b0-6beed304115a)

5. Check the received email is showing the incorrect date format
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/129270794/4d791397-3fdc-4834-9b40-60d17b4797ad)

### Expected result

The date format in the email should match the appearance on the date in the backoffice, or be configurable by some other means.

The date string should not include a time value of "12:00:00 AM"

### Actual result

Dates appear using the American date format and includes a time of "12:00:00 AM"

**Comment by AndyButland** [comment]
This workflow I would suggest is more for internal notification that anything that should be public facing (using the one that allows you to provide a template would likely be better for that, and would give you more control over the output).

That said, I see we can improve things here.  Determining the ideal date format to use is a little tricky - as we don't know what the recipient would prefer - but at the very least we should make it unambiguous and remove the irrelevant time part.

So I'm proposing we'll resolve this to output as per the following example:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/919c034d-2efd-44fe-be8f-9a9ef4dd7d37)

**Comment by AndyButland** [comment]
This will be part of the next round of releases.
