### ISSUE TITLE
Magic string page field in workflow with Form Delivery API

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1215]
Working with workflow we can use magic string, e.g. `{email}` or page field `[#myProperty]`.
However with Forms Delivery API, I wonder how to handle this?

I have a custom workflow inheriting `SendRazorEmail` and `[#employee]` in recipient email.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/6bdf0c73-29bd-4f63-b789-12b19fc810c9)

I tried with the following inside workflow:

```
string? value = _placeholderParsingService.ParsePlaceHolders(Email, false);
```

Employee property is in this case a single MTNP picker, so I would expect a Guid, which I could resolve looking up the content node from cache or define a custom format function.

Forms API only contains a few endpoints:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/d09926a4-9b00-4820-9398-88d76d70b49a)

**Comment by AndyButland** [comment]
I haven't checked in detail here yet, but first can I check you are passing in the page ID when you submit the form (via the `contentId` parameter)?

https://docs.umbraco.com/umbraco-forms/developer/ajaxforms#submitting-a-form-entry

The intention here was that you could provide this such that when the form is submitted via the headless API it's processed as if it was hosted on the page provided - such that this information is available to workflows, entry records etc.

**Comment by bjarnef** [comment]
@AndyButland no, it didn't originally pass in `contentId`, but after I included that, I can access the page data:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/578#issuecomment-2100087920

However in my use-case when using magic string for a Content Picker / MNTP property on page it resolved to `Umbraco.Cms.Web.Common.PublishedModels.Employee` as string, which wasn't useful :)

and a custom format function wasn't any help here and the property value (or type or property) was returned as string value:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/1216

It would be nice it magic strings could resolve the picker as `Guid` (or array or `Guid` for multi picker), but I guess it only works for simple property editors like textstring, textarea, number (int and decimal), date...

**Comment by AndyButland** [comment]
Yes, that's right.  In which case I'll close this one since remaining point you raise you mention already has a separate issue. Thanks.
