### ISSUE TITLE
Field setting for text string array

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1217]
Currently there are the following setting types / views.
https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-type/setting-types

However it doesn't seem there are something similar to [Repeatable Textstrings](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/multiple-textbox) in Umbraco core, which could be useful for lists ids to subscribe in newsletter signup or the like, where multiple values are needed.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/f8f2e33c-aa03-487d-982c-678c69f595a8)

**Comment by AndyButland** [comment]
Good suggestion, thanks @bjarnef.  We'll include this in the next releases.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/7afab18b-c894-4b26-9804-779ddee11bb4)
