### ISSUE TITLE
Inline/horizontal setting for checkboxes and ratiobuttons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1218]
When rendering checkbox or radiobutton lists the options can be listed vertically, but when there are only 2-3 options some may prefer a setting to render the inline/horizontally instead.

Example:
https://getbootstrap.com/docs/5.3/forms/checks-radios/#inline

**Comment by AndyButland** [comment]
Good suggestion @bjarnef, thanks.  We'll have this available as an option on the field type and rendering update in the themes that ship with Forms in the next minor releases.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/90b9448f-3326-462e-a381-da82dd18e990)
