### ISSUE TITLE
[13.1.2] When using RecordService.ApproveAsync() from a Workflow the Record is Approved Twice

### ISSUE THREAD

**Issue by paulsterling** [umbraco/Umbraco.Forms.Issues#1223]
When using `RecordService.ApproveAsync()` from a custom workflow the Record is approved twice and any workflows triggered by _On Approve_ are also executed twice. Oddly, from the same custom workflow using `RecordService.RejectAsync()` does not reject twice. The Form has _Enable post moderation set to ON_

According to the log entries, the _Form Entry Approved_ happens twice, about 1-second apart, with the identical set of log information except the `ThreadId` is sometimes different.

Reproduction
------------
Umbraco Cloud
Umbraco CMS 13.3.2
Umbraco Forms 13.1.2
Custom Workflow
Form has _Enable post moderation set to ON_
Form _DisableDefaultWorkflow_ set to True

Configuration
```
    "Forms": {
      "FormDesign": {
        "DisableDefaultWorkflow": true
      }
```

Custom Workflow 
```
        public override async Task<WorkflowExecutionStatus> ExecuteAsync(WorkflowExecutionContext context)
        {
            // Assume this is a valid email, set the redirect to a 'THANK YOU' page
            _httpContextAccessor.HttpContext.Items[Constants.ItemKeys.RedirectAfterFormSubmitUrl] = "/thank-you";

            string email = context.Record.ValueAsString("email");

            // check if the email is a disposable email address and redirect to a 'NO thank you' page if matched
           // or something else that returns True
            if (_disposableEmailService.IsDisposableEmail(email))
            {
                // This is a spam email, redirect to a 'NO thank you' page, return early
                _httpContextAccessor.HttpContext.Items[Constants.ItemKeys.RedirectAfterFormSubmitUrl] = "/no-thank-you";

                // set the Form status to 'Rejected' and return
                _recordService.RejectAsync(context.Record, context.Form).Wait();

                return await Task.FromResult(WorkflowExecutionStatus.Completed);
            }
            else
            {
                // if we made it this far , the email is valid, Approve the record
                _recordService.ApproveAsync(context.Record, context.Form).Wait();
            }
            return await Task.FromResult(WorkflowExecutionStatus.Completed);
        }
```

### Steps to reproduce
Attach the custom workflow to Form's _On Submit_ trigger and also add any other workflow to the _On Approve_ trigger. We are using the _Send Email_ workflow here.

### Expected result
The _On Approve_ workflow is not run when the form is rejected (that works as expected) and is run one time when the form is approved.

### Actual result
When approved, the _On Approve_ workflow is run twice, also logged twice. See log entries below with identical data except for the timestamp.
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/fe1cc735-a152-4fed-affe-bef83c8fe800)
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/f75733b3-5c02-4882-8fcf-9555e0f18d89)

### The Workflow Audit shows the custom workflow run once and the _Send Email_ workflow run twice
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1653490/d2d8d1e5-2952-4bc0-a262-7fa4cbe8bb86)

**Comment by AndyButland** [comment]
Thanks for reporting @paulsterling - we have found a bug here and resolved for the next releases.
