### ISSUE TITLE
Non Sensitive users - can add sensitive fields

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco.Forms.Issues#1233]
A brief description of your feature request goes here.

I think it would be nice for non-Sensitive users to be able to add Sensitive data fields to a form.
Some users maybe hired to create content/forms, but are not allowed to se sensitive data.

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/6445636/7dfec2df-b992-4afa-8916-dbeb62506399)

---
_This item has been added to our backlog AB#42304_

**Comment by AndyButland** [comment]
Agree that this makes sense - there's no harm in a user without this permission from setting a field to be sensitive, only we just need to ensure they can't reset it if the field is already defined as sensitive.

We'll include these in the next releases.

**Comment by thomashdk** [comment]
Sweet! Thanks 🙌🏻

**Comment by bme-novaware** [comment]
@AndyButland This issue is now present again in a new Umbraco Cloud project with the latest LTS versions of Umbraco (17.5.3) and Forms (17.4.7).

**Comment by rickbutterfield** [comment]
Hey @bme-novaware! We had a similar issue raised in https://github.com/umbraco/Umbraco.Forms.Issues/issues/1415, and a fix for this is coming in 17.5 / 18.1, which will be released as an RC on Thursday 6th August and a final release two weeks after that

**Comment by rickbutterfield** [comment]
Following up on my last comment: the fix landing in 17.5 / 18.1 also covers the edge case you ran into @bme-novaware - you will now be able to switch the toggle on and back off freely before saving, and it only locks once actually saved. Full details in #1762.
