### ISSUE TITLE
Always display total entries as 0 on V14.0.2

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco.Forms.Issues#1236]
A brief description of the issue goes here.
V14.0.2
<img width="1290" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/116753400/ab919178-10a1-458f-a084-ea2afb07cea8">

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
Total entries always displays as 0 even Form has data.

### Specifics
https://github.com/umbraco/Umbraco.Forms.Issues/assets/116753400/a5b0ce2c-8e11-4451-800b-2a30348213c3

### Steps to reproduce
1. Create a new Umbraco Form v14.0.2 include multiple fields with different types:
Short Answer
Long Answer
Date
File Upload
Multiple Choice
Password
Title and Description
Rich Text

2. Render Form to view like this
<img width="891" alt="image" src="https://github.com/umbraco/Umbraco.Forms.Issues/assets/116753400/6c63b5a7-9706-4a8a-9b63-9bf4403a2465">
3.  Submit Form

4. Go to Form in BackOffice and check

### Expected result
Displays the correct number of entries

### Actual result

---
_This item has been added to our backlog AB#41977_

**Comment by AndyButland** [comment]
I'm not able to replicate this one with the latest code, so possibly it's been resolved and the fix will be in 14.1.

At least in my tests if I submit an entry, then navigate to the forms dashboard, I see the number incremented.
