### ISSUE TITLE
messageOnSubmit not translated when submitted via api

### ISSUE THREAD

**Issue by wiedikerli** [umbraco/Umbraco.Forms.Issues#1238]
When the form is submitted via the api, the response is not translated at all.
```
{
  "messageOnSubmit": "#form.MessageOnSubmit",
  "messageOnSubmitIsHtml":false
}
```
Umbraco: 13.3.2
Forms: 13.1.2

---
_This item has been added to our backlog AB#41981_

**Comment by AndyButland** [comment]
Thanks for reporting.  Can confirm I can replicate the issue and we'll resolve for the next releases for Forms 13 and 14.
