### ISSUE TITLE
Can not view data entries when click from "View entries"

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco.Forms.Issues#1239]
A brief description of the issue goes here.
V14.0.2

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
Can not view data entries when click from "View entries"

### Specifics
I have a "Secret Form", that have submitted 1 data , when click from "View entries", then it goes to Entries table. The table does not show any data

### Steps to reproduce

https://github.com/umbraco/Umbraco.Forms.Issues/assets/116753400/1c197a99-195f-44a5-adb5-56921f1e0afb

### Expected result
Datas should be displayed after click "View entries"

### Actual result
No data is viewed

**Comment by AndyButland** [comment]
Thanks for reporting this @NguyenThuyLan.

I think we had a form of race condition here, as I found I could see this sometimes, but not always.  I've made some changes to the order of events now and no longer seem to see the issue when testing, so will consider this resolved for the pending 14.1 release.
