### ISSUE TITLE
DatePicker.cshtml from Default theme is used, if the form has multiple pages, and Date field is not located on the first page

### ISSUE THREAD

**Issue by OlePc** [umbraco/Umbraco.Forms.Issues#124]
Reproduction
------------
### Bug summary
I noticed that the feature https://github.com/umbraco/Umbraco.Forms.Issues/issues/119 added in forms 7.1.0, where DatePicker.cshtml is moved to themes folder, does not work if your form is split up into multiple pages, and the Date field os not located on the first page.

### Specifics
I've reproduced on a fresh install of Umbraco v7.14.0 using Forms v7.1.0. Didn't test for v8, but it's probably the same.

### Steps to reproduce

1. Create a form with multiple pages
2. On the second page, add a Date field
3. Create a new theme folder under Views/Partials/Forms/Themes, and copy the DatePicker.cshtml from the default theme into your new theme folder
4. Add an indicator to your new DatePicker.cshtml file and the default one, so you know when which one is used (console.log i the script section or something)
5. Add the form to a page, and make sure the new theme is chosen
6. Go to step 2, and notice that the indicator for the default DatePicker.cshtml shows up
7. Delete step 1, and reload the page
8. Notice that the new indicator now shows up

### Expected result
The DatePicker.cshtml in my theme folder should be used on all pages

### Actual result
The DatePicker.cshtml in my theme folder is only used on the first page

**Comment by bergmania** [comment]
Workaround:

Add the following line
```@Html.HiddenFor(x => Model.Theme, new {id=(string)null})```
just below of
```
@Html.HiddenFor(x => Model.PreviousClicked, new {id=(string)null})
```

in the following files:
- `\Views\Partials\Forms\Form.cshtml`
- `\Views\Partials\Forms\Theme\*\Render.cshtml`

**Comment by bergmania** [comment]
PR:
- V7: https://github.com/umbraco/Forms/pull/267
- V8: https://github.com/umbraco/Forms/pull/266

**Comment by warrenbuckley** [comment]
All merged in
