### ISSUE TITLE
Umbraco.Forms 13.1.2: Date field throws a console error on blur when no value is selected

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco.Forms.Issues#1241]
### Bug summary

The Umbraco Forms date field throws a console error on blur when no value is selected.

### Specifics

Observed in multiple solutions running Umbraco.Forms 13.1.2.

```
Uncaught TypeError: Cannot set properties of null (setting 'value')
    at HTMLInputElement.<anonymous> (umbracoforms.min.js?v=13.1.2:1:7837)
```

This seems related to issue #1200 wherein the id attributes of the `datepickerfield` and `datepickerfieldshadow` fields were swapped in the .cshtml view. I suspect part of the umbracoforms.js script was not updated to match, i.e.:

```
var hiddenDatePickerField = id.substr(0, id.length - 2);
```

should be:

```
var hiddenDatePickerField = id + "_1";
```

### Steps to reproduce

1. Create a solution running Umbraco.Forms 13.1.2.
2. Create a form with a _Date_ field and add it to a page.
3. On said page, focus the _Date_ field to show the date picker.
4. **Without selecting a date**, blur the _Date_ field to hide the date picker.
5. Observe the error in the browser console window.

### Expected result

No error is thrown.

### Actual result

The above error is thrown.

---
_This item has been added to our backlog AB#41969_

**Comment by AndyButland** [comment]
Thanks for the report here both (as well as the diagnosis and fix... bot of which look correct to me).  We'll resolve this for the next releases of 13 and 14.
