### ISSUE TITLE
Umbraco 14 Form Picker null and empty in Umbraco backoffice

### ISSUE THREAD

**Issue by Mdwolff** [umbraco/Umbraco.Forms.Issues#1244]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When selecting a form using the form picker in a block list it works and you can select the form. When you then try to load the form into the view the value is null. And after reloading the page in Umbraco the field where you select the form is empty and you also cant delete of select another form. Als tried to add the picker to a page type, this gives the same result.

### Specifics

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/173349157/ae78d5b8-a3a8-426c-8f5a-dce9d6eab497)

### Steps to reproduce

Add a form picker property to a page or block (they both have the same issue).
Select a form and then reload the page, the picker is then empty and not available.

The console also gives an error saying;
 TypeError: selection.filter is not a function

### Expected result / actual result

Selecting a form returns the Guid in the view and you an change or remove the form in Umbraco using the picker.

**Comment by ronaldbarendse** [comment]
Hi @Mdwolff! I haven't been able to replicate this on a clean install (CMS 14.0.0 and Forms 14.0.2): I can add a new block and select a form, refresh, save and refresh, etc. If the page is not saved, I can re-select the form again (and the new block dialog even opens back up):

![Block editor dialog](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1051287/017ae67e-6411-4c95-8d98-ba63100eeccc)

I've even changed the backoffice language to Dutch (as I could see that might be the only difference), but that doesn't break it either:

![Dutch block editor dialog](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1051287/b220d7d7-12fd-4ca7-a506-47221b19aacd)

Can you verify you're on the latest Forms patch version and provide additional details (full stack trace of that console error, user group permissions, any customizations, etc.)?

One thing I did notice, is that you can't select a form if you don't have access to the Forms section. We should probably make this a little less strict and allow any backoffice user to access the item endpoints in the Forms Management API.

**Comment by AndyButland** [comment]
> One thing I did notice, is that you can't select a form if you don't have access to the Forms section. We should probably make this a little less strict and allow any backoffice user to access the item endpoints in the Forms Management API.

This issue will be resolved in the upcoming patch release.
