### ISSUE TITLE
Conditional Action Select Dropdown not functioning

### ISSUE THREAD

**Issue by kahkean3** [umbraco/Umbraco.Forms.Issues#1248]
Environment of Issue:
1.	Umbraco Version: 14.0.0
2.	Umbraco Forms Version: 14.0.2

Description of Issue
I am experiencing an issue with Umbraco forms conditions where I am unable to select the condition to be chosen from the select dropdown. Attached below are further images and descriptions.
![Picture1](https://github.com/umbraco/Umbraco.Forms.Issues/assets/171549548/40583a9a-e067-48a2-a082-2b78ecb2e04d)
My test form includes only 1 page, 1 group and only 3 questions, which are “Consent for storing submitted data”, “Favourite Food” and “Flavour”.

![Picture2](https://github.com/umbraco/Umbraco.Forms.Issues/assets/171549548/67178785-e7bf-43e6-9ba2-53f569f1e307)
Attached above is the screenshot for the question “Favourite Food”, it is a dropdown with two options: Ramen, Rice. 

![Picture3](https://github.com/umbraco/Umbraco.Forms.Issues/assets/171549548/cb58934c-91b8-4bba-ad06-04c3258320db)
Attached above is the screenshot of the question “flavour”, it is a dropdown with two options: Shoyu, Spicy. 

![Picture4](https://github.com/umbraco/Umbraco.Forms.Issues/assets/171549548/95f4cbd8-ca37-454e-9318-e474f1979057)

However, when I click on the Select dropdown to choose an option from Favourite Food to set it to Rice, the Select dropdown shows a small blank rectangle with no options for me to choose from despite having previous questions set up. 

Expected Behavior:
Select dropdown expands with options of Ramen and Rice.

Actual Behavior:
Blank dropdown with no options.

Steps to Reproduce:
Although through multiple attempts of testing, occasionally the Select dropdown functions as expected, however we are unable to identify the issue or pattern that causes the problem, as such, we are unable to recreate the issue whenever possible, but this issue occurs a large majority of the time.

Below is a word doc of the issue as well:
[Amber Creative Umbraco Forms Issue Report.docx](https://github.com/user-attachments/files/16157898/Amber.Creative.Umbraco.Forms.Issue.Report.docx)

**Comment by AndyButland** [comment]
I can't immediately replicate this with the latest code, so could I ask a couple of things please?

- Would you be able to try this with 14.1.0-rc1 (released yesterday)?  I can't think of specifically what, but perhaps this has got fixed along with other updates, and hence I don't see it.
- Please could you export and attach your test form?  Your instructions are quite straightforward to follow but just perhaps there's something different in my setup that hides the problem.

Thanks.

**Comment by AndyButland** [comment]
Closing this now given no further discussion.
