### ISSUE TITLE
Typo in French Translation of Umbraco Forms

### ISSUE THREAD

**Issue by ericforgues** [umbraco/Umbraco.Forms.Issues#1251]
### Bug summary
There is a typo in the French translation of Umbraco Forms. Specifically, in the Umbraco.Forms.StaticAssets, file staticwebassets/fr.fr.js, an accidental "G" has been included at the beginning of a sentence.

### Specifics
**Version:** 13.1.0

**Steps to reproduce**
Open the Umbraco.Forms.StaticAssets file located at staticwebassets/fr.fr.js.
Navigate to line 484.
Observe the typo in the manageDatasourcesDescription string.

**Expected result**
The text should be: Accorder ou refuser l'accès à la gestion de toutes les sources de données pour tous les formulaires.

**Actual result**
The text currently is: GAccorder ou refuser l'accès à la gestion de toutes les sources de données pour tous les formulaires.

**Comment by AndyButland** [comment]
Thanks for the report - this will be resolved in the next releases.
