### ISSUE TITLE
Add support for AllowedFileUploadExtensions

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Forms.Issues#1252]
Hello 

In Umbraco forms  13.1.2 it is possible to set `DisallowedFileUploadExtensions`. See https://docs.umbraco.com/umbraco-forms/v/13.forms.latest-lts/developer/configuration

Is it possible to add support for `AllowedFileUploadExtensions`. We have a client that takes security very seriously and is pulling together a very long list of extensions that aren't allowed, when really all they want to do is allow word documents, text documents and images.

This was a feature of Perplexforms On Steriods, it would be lovely if it could be added to Umbraco Forms

Many thanks

Rachel

---
_This item has been added to our backlog AB#42298_

**Comment by AndyButland** [comment]
Yes, this seems a sensible idea to add.  We've implemented for the next release which is due next week (and will be out in 13.2.0-rc2 a bit later in the day).

The new configuration will look like this:

Default configuration now looks like this:

```
    "Forms": {
      "Security": {
        "AllowedFileUploadExtensions": "",
        "DisallowedFileUploadExtensions": "config,exe,dll,asp,aspx,js"
      }
    }
```

That you can adjust as necessary.

We'll then allow an extension if it's NOT in `DisallowedFileUploadExtensions` and EITHER `AllowedFileUploadExtensions` is empty OR the extension is in `AllowedFileUploadExtensions`.

**Comment by RachBreeze** [comment]
Thank you for picking this up so quickly @AndyButland
