### ISSUE TITLE
Add support for manipulating user security via the IFormsSecurity service

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Forms.Issues#1253]
Hello

Umbraco Forms v13.1.2

Hopefully I've missed a service. But looking at `Umbraco.Foms.Core.Services` and `Umbraco.Forms.Core.Security` it is not possible to manipulate user security. This would be really handy in the case of migrating Perplex Forms on Steroids from Umbraco 7 which has a table `perplexUmbracoUser` which details the start nodes for every forms user.

Appreciate this is probably not a strong argument for adding but am ever hopeful :-)

**Comment by AndyButland** [comment]
The services that Forms uses internally for manipulating user security records in the database are exposed as public interfaces, so I think if you wanted to do something with this programmatically you could.

See `IUserSecurityStorage`, `IUserStartFolderStorage` and `IUserFormSecurityStorage`; and `IUserGroupSecurityStorage`, `IUserGroupStartFolderStorage` and `IUserGroupFormSecurityStorage` (all in the `Umbraco.Forms.Data.Storage` namspace).

**Comment by RachBreeze** [comment]
Hi @AndyButland 

Thank you so much I didn't check the `Umbraco.Forms.Data.Storage` namespace
