### ISSUE TITLE
Umbraco.Forms 13.1.2 reCAPTCHA v3 "Error message" does not show when validation fails

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco.Forms.Issues#1257]
### Bug summary

Umbraco.Forms 13.1.2 reCAPTCHA v3 "Error message" does not show when validation fails.

### Specifics

Observed in multiple solutions running Umbraco.Forms 13.1.2.

### Steps to reproduce

1. Create a solution running Umbraco.Forms 13.1.2.
2. Create a form.
3. Add a _reCAPTCHA v3 with score_ question to the form and populate its _Error message_ property.
4. Submit the form in such a way that the calculated reCAPTCHA v3 score is below the configured threshold.

### Expected result

- The Umbraco logs show the following error message `The Google reCAPTCHA v3 score {RecaptchaScore} did not meet the user defined threshold of {FieldThreshold} for the field {FieldAlias} on {FormName}`.
- The user sees the error message configured in step 3 above.

### Actual result

- The Umbraco logs show the following error message `The Google reCAPTCHA v3 score {RecaptchaScore} did not meet the user defined threshold of {FieldThreshold} for the field {FieldAlias} on {FormName}`.
- The user sees a page with no error message.

**Comment by AndyButland** [comment]
Could you check that you are displaying the validation summary in your rendering please?  It could be switched off in the form settings:

![image](https://github.com/user-attachments/assets/f40bfa57-f653-4a0f-8bf3-76b8956ea7f0)

As this is where the error message will display.  Unlike other fields, there's no visual representation of the reCAPTCHA 3, so no field to display the validation error message against.  So can only really be rendered in the summary.

**Comment by stephen-sherman** [comment]
Thanks Andy, that makes a lot of sense. I can confirm that the reCAPTCHA validation message is displayed as long as the form's _Show validation summary_ setting is enabled.
