### ISSUE TITLE
Empty prevalues outside of request context

### ISSUE THREAD

**Issue by jmf-umbraco** [umbraco/Umbraco.Forms.Issues#1258]
When attempting to get prevalues from a document source in code, an empty collection is returned when running outside of a request.

Reproduction
------------
* Create a prevalue source from documents
* Specify a static root node & document type - do not select "Use current page as root"
* Save the prevalue source and verify it has some values from nodes in the tree
* Create a dropdown field on a form, using the new prevalue source
* In code and outside of request context (see note below), attempt to get the prevalues for the field, using something like the following:

```
var preValueSource = _fieldPreValueSourceService.GetById(field.PreValueSourceId);
if (preValueSource != null)
{
    var preValueFieldType = _fieldPreValueSourceTypeService.GetById(preValueSource.FieldPreValueSourceTypeId);
    if (preValueFieldType != null)
    {
        preValueFieldType.LoadSettings(preValueSource);
        return preValueFieldType.GetPreValues(field, form);
    }
}
```

### Specifics

The issue only occurs outside of any contexts in which an `IUmbracoContextAccessor` can retrieve a context - For our example we have an internal rebus queue that handles messages asynchronously after a request and any notifications are fired. It's in this handler we are attempting to get prevalues.

It looks like the call to `GetPreValues(...)` is triggering an early termination clause that returns an empty collection if no `UmbracoContext` can be retrieved. This makes sense if using a dynamic root document (i.e. "Use current page as root"). However for the case where we need to retrieve values from a static root, the context shouldn't be necessary.

### Expected result

The call to `preValueFieldType.GetPreValues(field, form);` returns a set of prevalues retrieved from children of the root node specified in the prevaue source config.

### Actual result

The call to `preValueFieldType.GetPreValues(field, form);` returns an empty collection.

**Comment by AndyButland** [comment]
Thanks for the clear description of the issue @jmf-umbraco.  You are right in that we shouldn't be early returning here, as we only need the Umbraco context in the case where "use current page" is used.

This will be resolved in the upcoming releases for Forms 13 and 14.
