### ISSUE TITLE
Export Entries function not working

### ISSUE THREAD

**Issue by waltersmu** [umbraco/Umbraco.Forms.Issues#1259]
When trying to export the entries a exception is raised please see below:
![FormsException](https://github.com/user-attachments/assets/6760fe94-6ec3-49e1-aaf7-af164134bb72)

Reproduction
------------

Trying to export any form entries with any of the two options.

### Specifics

Windows Server 2019
.Net Core 8
No previous versions installed on the server.
Umbraco version 13.0.3
Umbraco Forms: 13.1.2
### Actual result

---
_This item has been added to our backlog AB#42544_

**Comment by AndyButland** [comment]
Thanks for reporting @waltersmu.  We did [have this before](https://github.com/umbraco/Umbraco.Forms.Issues/issues/761), but it was in theory resolved by doing an operating system check.

There's a feature used by the export to Excel library we have to auto-fit the columns, which has a dependency on the component reporting in the exception you have shared.  It's nice format the export in this way, but non-essential, and didn't work on Linux.  So we have a check for a Windows operating system before calling the method.

From your report it seems like at least some flavours of Windows don't support it either.

As it's a non-essential feature we will put a try/catch around this to catch the not supported exception, and skip over if the operation can't be completed.

This will be in the next round of patch releases.
