### ISSUE TITLE
CheckBoxList view changes between v13.1.2 and v13.2.0 – Breaking change?

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Forms.Issues#1261]
We upgraded an Umbraco Cloud site, including to the latest version of Forms v13.2.0.

This inadvertently brought with it entirely new markup for the CheckBoxList field view. As these are now shipped as part of the Forms Razor Class Library there is seemingly no way to know if these change between versions...

In this particular site there was some specific CSS to make the checkbox list work, that naturally broke with the upgrade. My solution for now was to include the old version of `FieldType.CheckBoxList.cshtml` in the project.

I had a quick look at the [Forms release notes](https://docs.umbraco.com/umbraco-forms/v/13.forms.latest-lts/release-notes) and couldn't see anything related listed, but perhaps I missed it...

This has made me wonder how these kinds of changes could be best communicated... Should "significant" changes to any of the Umbraco Forms output markup be considered breaking changes and handled accordingly? _(by significant I mean structural changes, addition or removal of elements; adding attributes should be okay...?)_

**Comment by AndyButland** [comment]
Hi @callumbwhyte - sorry for the issue you ran into here. I thought we'd been careful enough introducing this in ensuring class names etc. were retained, but I can see there are some changes that could have impact depending on exactly how CSS is targeting the elements.

You are right that this strictly should be considered a breaking change.  I'm a little loathe to commit to making no changes to these, just as that limits us to introducing features or fixing issues that depend on them to majors, but at very least we'll ensure to call out changes in the release notes more clearly.  The specific issue that led to the change was [this one](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1218) - linked from the release notes, but not with any detail about the changes to partial views.  I'll add this for anyone else upgrading.

**Comment by AndyButland** [comment]
PR for update to release notes is here: https://github.com/umbraco/UmbracoDocs/pull/6296

I'll close this one now as don't think there's anything further to do... but points noted.  Will try to be more careful when considering these changes in future and make sure to flag in release notes if changes to these files are made.
