### ISSUE TITLE
Include Sensitive Data flag missing for custom workflow (V14)

### ISSUE THREAD

**Issue by arcjawsh** [umbraco/Umbraco.Forms.Issues#1262]
### Issue

The Include Sensitive Data flag is missing from the edit custom workflow form. It appears in Umbraco/Forms V13 but not in V14. Does not appear to have any reference in the rendered html either.

V14

![uf14_missingsensitive](https://github.com/user-attachments/assets/82937bb3-59d6-417f-8fcf-8c257688a6c4)

V13

![uf13_sensitivedata](https://github.com/user-attachments/assets/c7bb83df-92dd-4bed-9ea0-1c8221ed2677)

### Reproduction

Create a custom workflow and apply to an Umbraco form. Navigate into the custom workflow settings.

### Specifics

Umbraco 14.0.0
Umbraco Forms 14.1.0
Edge / Chrome / Brave

---
_This item has been added to our backlog AB#42555_

**Comment by AndyButland** [comment]
Thanks for flagging this @arcjawsh - an oversight from the work done to update Forms for Umbraco 14.  We've resolved now and it'll be part of the next patch release.
