### ISSUE TITLE
Forms backoffice UI not translated when user Culture is en-GB

### ISSUE THREAD

**Issue by DGibbsCrafted** [umbraco/Umbraco.Forms.Issues#1267]
**Brief description**

`Umbraco.Forms 14.1.0`

The Umbraco Forms backoffice tab is not translated when a users UI Culture is set to `en-gb`.

**Reproduction**

- Install [uSync](https://github.com/KevinJump/uSync)
- Set your users UI Culture to `English (GB)`
- Go to the `Forms` tab
- Refresh the page

**Specifics**

This issue seems to be an interaction with the [uSync](https://github.com/KevinJump/uSync) package which adds an `English (GB)` culture to the `UI Culture` field against a user:

![image](https://github.com/user-attachments/assets/bb542966-d80b-480b-a38f-05c4f8e2c8c0)

If I select this as a users culture and then browse to the `Forms` tab, the page is not translated:

![image](https://github.com/user-attachments/assets/bb00d43f-4fd2-476a-82f1-c49ea37a9e17)

I can see that an `en-gb.js` resource file matching the users culture is being loaded by the forms plugin and this file is missing the keys shown in the above screenshot:

![image](https://github.com/user-attachments/assets/dd0a83b5-ccde-4d48-8303-b1382d2a932f)

Comparing this with other resource files, I can see that it's missing quite a few keys e.g. compare to `es-es.js` in the `staticwebassets` folder:
https://nuget.info/packages/Umbraco.Forms.StaticAssets/14.1.0

Should `en-gb.js` include the complete set of resource strings/keys, or should it merge with `en-us.js` for any missing keys?

Note that this is not an issue with a fresh Umbraco installation that **does not** have uSync installed and where the users UI culture is set to `English (UK) / en`.

My assumption here is that Umbraco.Forms is loading the fallback `en-us.js` resources since it doesn't provide a localization file for `en.js` which is what that culture maps to.

**Expected result**

The Umbraco Forms UI should be translated when a users UI Culture is set to `en-GB`:

![image](https://github.com/user-attachments/assets/a6043216-a98c-4697-a937-8ee74c49e63c)

**Actual result**

The forms UI is not translated when a users UI Culture is set to `en-GB`:

![image](https://github.com/user-attachments/assets/9672928c-acf6-4483-b09e-e6cb4fee55d9)

---
_This item has been added to our backlog AB#42648_

**Comment by AndyButland** [comment]
Thanks for flagging this - will have a look next week to see what's going on here.  With Forms 13 I we only needed the keys in `en-gb` that we wanted to override the default of `en-us`, but perhaps we haven't got that right for 14.  As I understand fallback should work, but could be we need an `en.js` to to do.

Anyway, will investigate and get this updated in a coming patch release.

**Comment by DGibbsCrafted** [comment]
@AndyButland - Thanks Andy

**Comment by AndyButland** [comment]
Thank again for the feedback, this will be resolve din the next patch release.
