### ISSUE TITLE
Datepicker is showing 1. january 1753 after validation error on Data concent field

### ISSUE THREAD

**Issue by Oxygen-cl** [umbraco/Umbraco.Forms.Issues#127]
Hi Umbraco

We are getting an error on the datefield in combination with the DataConcent field. We get a "DateMin" value after validation. 

The error only occures when we have validation errors on the "Data Concent" field. 
The date changes to 1. januar 1753 after validating the data concent field. 

It looks like the validation fires a page load. But it's only on the data concent field. As you can see in the video below, the validation of a text field does not break the datefield.

I have tested this on a clean solution, and the same error excists ther (Cloud: Sprogklar) 

You can  see a video of the issue here: https://www.screencast.com/t/V7PDnFMN

**Comment by bergmania** [comment]
Hi, @Oxygen-cl..

I can confirm the issue. Here's a workaround until next release.

In the file `\App_Plugins\UmbracoForms\Assets\datepicker.init.js` change the line:

```
minDate: new Date('1753-01-01T00:00:00') //Min value of datetime in SQL Server CE
```
to
```
minDate: new Date('1753-01-01T00:00:00'), //Min value of datetime in SQL Server CE
defaultDate: new Date(field.value),
setDefaultDate: true
```

**Comment by bergmania** [comment]
PR: 
- V7: https://github.com/umbraco/Forms/pull/269
- V8: https://github.com/umbraco/Forms/pull/268

**Comment by warrenbuckley** [comment]
All merged in
