### ISSUE TITLE
Form create/ edit field type preview for date autocompletes with login information

### ISSUE THREAD

**Issue by git-wizard** [umbraco/Umbraco.Forms.Issues#1271]
When I add a date field in a new form in the backoffice, the field autocompletes with my Umbraco login email.

Reproduction
------------

### Bug summary

The date field preview in the forms section in the backoffice is currently built using type="text" without an autocomplete attribute. This causes the date field to autocomplete with Umbraco login information.

### Specifics

Umbraco version: 13.4.1
Umbraco forms version: 13.1.2
Browsers: Chrome, Firefox

![image](https://github.com/user-attachments/assets/580a1ff8-052a-48d4-be3a-b3b4a1625298)
![image](https://github.com/user-attachments/assets/944ef69b-c402-4d42-8a88-2780a6ccc60f)

### Steps to reproduce

Add a Date field in a form within the backoffice. Set a placeholder date. Submit it, save the form and refresh. 

To replicate you will need to have your details saved within Chrome/ Firefox for the browser to autocomplete the form field. 

### Expected result

I expect this to display the placeholder value only

### Actual result

The field is populated with my login username by the browser autocomplete.

**Comment by AndyButland** [comment]
I wasn't able to replicate this, but agree there's no need for autocomplete on these read-only previews.  So I've explicitly set the autocomplete attribute to off on the date picker and other relevant previews.  Will be released in an upcoming patch.
