### ISSUE TITLE
Missing Workflow Description Label after upgrading to 13.2.0

### ISSUE THREAD

**Issue by Alkaersig** [umbraco/Umbraco.Forms.Issues#1272]
After upgrading to v13.2.0 all workflows looks like this:
![image](https://github.com/user-attachments/assets/49bc81b0-3558-4f14-b5cc-52c8c1c3e1b0)

Reproduction
------------
Upgraded from v13.1.2 to v13.2.0 and the label for the Workflow Description Field seems to be missing.

**Comment by AndyButland** [comment]
It doesn't look to me that you are viewing the latest from your screenshot.  Please could ensure you have [fully cleared your cache](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html)?

**Comment by Alkaersig** [comment]
Hi @AndyButland 

I bumped our RuntimeMinification Version as the first thing and it did not resolve it.
