### ISSUE TITLE
Umbraco Forms v14 dashboard UI labels in backoffice

### ISSUE THREAD

**Issue by Gavin5656** [umbraco/Umbraco.Forms.Issues#1274]
The Forms UI labelling only handles Umbraco users whose UI Culture is set to English(US). Any other culture and you get the label placeholders e.g. formsDashboard_editForm formsDashboard_viewEntries

Reproduction
------------

Edit your Umbraco user and change the UI Culture to something other than English(US). View the Forms dashboard and confirm the labelling has reverted to the placeholder text.

### Expected result

Forms UI labelling uses fallback default English(US) text if no other text configured.

### Actual result

Forms UI labelling text is missing/no fallback so labels display their internal names.

**Comment by AndyButland** [comment]
I believe [we've resolved this in 14.1.1](https://docs.umbraco.com/umbraco-forms/release-notes#id-14.1.1-august-6th-2024) @Gavin5656 - which was only released this morning, so I'm assuming you aren't running it yet.

I'll close this as there was a specific change to resolve this, but if you still have trouble after upgrading please re-open and let us know.
