### ISSUE TITLE
Make it possible to configure the date format for the Date field

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco.Forms.Issues#1276]
At the moment, I can't find any obvious way to configure the date format for the Umbraco Forms date picker. In addition, the documentation says if you want to use another date picker library you can, but It also doesn't appear to be possible to **stop** the Pikaday and moment libraries from loading if you do, which seems wasteful.

It would be great if it could either be added to the main date picker config options that exist already, or maybe as a data attribute on the datepicker input field.

The former I think would be a case of adding it to the `umbracoFormsLocaleFromConfig` options in the `datepicker.init.js` and  `Forms:FieldTypes:DatePicker` appsetting options.

The later could be handled in the `init` of the same file, when getting the individual fields, before creating the Pikaday instance.

---
_This item has been added to our backlog AB#42954_

**Comment by AndyButland** [comment]
We'll add an option for this with the next minor release of Forms 13 and 14 (and 15).

As you've suggested, we've added a new setting to the `DataPicker` configuration in app settings, that you would apply like this:

```
    "Forms": {
      "FieldTypes": {
        "DatePicker": {
          "DatePickerFormat": "DD-MM-yyyy",
          "DatePickerFormatForValidation": "dd-MM-yyyy"
        },
```

As you can see there are actually two settings:

`DatePickerFormat` - is the momentjs date format that'll be used client-side.
`DatePickerFormatForValidation` - is the equivalent C# date format that's used for validation on the server-side.  I found we needed this as unfortunately momentjs and C# date formats aren't the same. In theory it's possible to convert from one to the other, but [it's very complicated](https://stackoverflow.com/a/41653618), and I figured safer to just apply correctly in configuration.
