### ISSUE TITLE
Umbraco Forms workflow type not working

### ISSUE THREAD

**Issue by MrPels** [umbraco/Umbraco.Forms.Issues#1278]
Reproduction
------------

### Bug summary

Using the latest version of Umbraco Forms 14.1.1, i am trying out the workflow type "Send email", but i can not fill out the required message field as it is not shown/visible, and as such it prevents me from using the workflow type.

![image](https://github.com/user-attachments/assets/61280d15-c9f4-4a87-a9c0-38641e267f70)

![image](https://github.com/user-attachments/assets/fbc3a1be-e539-4c55-a438-3ba34d8c0d1e)

### Specifics

Browser: Chrome 127.0.6533.89
Umbraco 14.1.1
Umbraco.Forms 14.1.1

### Steps to reproduce

1. Spin up a new Umbraco project on version 14.1.1
2. Install the nuget "Umbraco.Forms" on version 14.1.1
3. Log in to the backoffice and navigate to the form section, and create a "new form..." (empty form)
4. Try to setup the workflow type "Send email"

### Expected result

I expected to be able to use the "Send email" workflow type.

### Actual result

Workflow type is not possible to use in current state when the field "Message" can not be defined as it is required, stopping the creation of the workflow type.

---
_This item has been added to our backlog AB#43074_

**Comment by AndyButland** [comment]
Thanks for reporting this - an oversight on our part when preparing up all the settings on the field and workflow types.  Will be resolved in the next patch release for 14.
