### ISSUE TITLE
Forms security needs some love

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#128]
In Umbraco 8 and Umbraco Forms 8.1 the forms security view need some love to match the backoffice UI.

Furthermore when selecting a user node under "Forms Security" is node highlight the tree (sync tree).

![image](https://user-images.githubusercontent.com/2919859/55148812-4266b300-5149-11e9-99f5-df4cfbe9c1f2.png)

**Comment by ronaldbarendse** [comment]
Adding support for groups would also be nice!

**Comment by bjarnef** [comment]
@AndyButland I think we can close this 👍 

Looks much better in recent versions, here v8.7.6

![image](https://user-images.githubusercontent.com/2919859/130224240-90ccf2ac-63f7-48a8-a462-cf067a49c57d.png)
