### ISSUE TITLE
Additional markup in submit buttons does not submit or validate when JavaScript is enabled

### ISSUE THREAD

**Issue by karltynan** [umbraco/Umbraco.Forms.Issues#1280]
**Version:** 13.2.1

## Bug summary

If you add any markup to the submit button(s) in the `Form.cshtml` theme file, such as a `span` around the text, or an `svg` icon alongside the text, it is not possible to click the button if you happen to click the additional elements. If you manage click outside of the elements but inside the button (if it has padding on the button for example), then you can submit the form or trigger validation as expected.

I believe this is perhaps the JavaScript validation click event attachment and handling?

### Steps to reproduce

1. Create a custom theme (or edit the default theme partial files)
2. Click the text of the button in the browser and the form submits (as expected)
3. Add a span around the text of the submit button
4. Click the text of the button in the browser and the form no longer submits

_Note: JavaScript must be enabled - this does not happen when JavaScript is disabled._

Example submit button markup:

```
<button type="submit" value="@Model.SubmitCaption" name="__next" data-form-navigate="next" data-umb="submit-forms-form">
    <span>@Model.SubmitCaption</span>
</button>
```

### Expected result

When you click any additional markup inside the button in the browser - the form should submit or trigger validation as expected.

JavaScript events should not stop the button from submitting the form if it contains other markup and that markup is clicked instead.

### Actual result

When you click any part of the button, including any additional markup inside the button, in the browser - the form does not submit or trigger validation.

---
_This item has been added to our backlog AB#43272_

**Comment by dtng95** [comment]
Hi @karltynan ,
We are working on this issue and the fix will be included in the next release.
Thanks!

**Comment by karltynan** [comment]
Amazing, thanks! #h5yr
