### ISSUE TITLE
Form entry result in custom examine index get the submitted form entry appended in the custom index. Forms version 13.2.1

### ISSUE THREAD

**Issue by swws23** [umbraco/Umbraco.Forms.Issues#1282]
Versions:
Umbraco: 13.4.1
Umbraco Forms: 13.2.1

Reproduction:
Install Starterkit in version: 13.4.1
Create a Form to be picked on Home page
Create custom index: https://docs.umbraco.com/umbraco-cms/reference/searching/examine/indexing#creating-your-own-index - with a little tveak: set CanAddToIndex to "author", just so we can add a document to the custom index with minimal effort

Start up the site.
We can see the index will be filled with the one author from Starterkit. If it's not there, rebuild custom index manuel.
![image](https://github.com/user-attachments/assets/dcc8bd60-e3e7-4dd5-9fa4-8f7e49827d69)

Now create a entry from the Form on the Home page. Then we can see the custom index a filled with 2 documents, and more fields.
![image](https://github.com/user-attachments/assets/c027c8de-f2cd-4392-929e-8425d106dbc1)

So now the entry is both in the UmbracoFormsRecordsIndex and the custom ProductIndex
![image](https://github.com/user-attachments/assets/f59ac31b-b0b2-4c8c-a9fd-b652e8616f60)
![image](https://github.com/user-attachments/assets/97a5ce9e-4915-4a50-933a-6d5ab9f93853)

I think it is because the ProductIndex inherits from UmbracoExamineIndex which use interface IUmbracoIndex, then Umbraco Forms put the entries in indexes with TypeOf IUmbracoIndex

---
_This item has been added to our backlog AB#43274_

**Comment by AndyButland** [comment]
We missed updating this issue at the time, but the problem was replicated and fixed in 13.2.2 and 14.1.2.
