### ISSUE TITLE
Unexpected concatination on fieldset classes when using SetFormFieldWrapperClass() method

### ISSUE THREAD

**Issue by james-whittington1** [umbraco/Umbraco.Forms.Issues#1284]
when using the @Html.SetFormFieldWrapperClass("my-class") on Umbraco 13 the default rendering method is rendering it joined with the fields css. 

umbraco-forms-default-theme-13.2.0/partials/forms/themes/default/form.cshtml:line57
                                   `<div class="@Html.GetFormFieldWrapperClass(f.FieldTypeName)@f.CssClass @{ if (hideFieldWhenRendering) { <text> umbraco-forms-hidden</text>  } }">`
                                   
umbraco-forms-default-theme-12.2.4/Partials/Forms/Themes/default/Form.cshtml:line59
` <div class="@Html.GetFormFieldWrapperClass(f.FieldTypeName) @f.CssClass @{ if (hideFieldWhenRendering) { <text> umbraco-forms-hidden </text>  } }">`

This means that the last class set via the method will be joined to the first class of the f.CssClass variable, which in our case broke the conditional logic of radio buttons, as the our rendered markup was output as class="my-classuumbraco-forms-field", which meant the element no longer matched the closest(".umbraco-forms-field") query. 

 

---
_This item has been added to our backlog AB#43409_

**Comment by AndyButland** [comment]
Looks like this was a regression introduced in an earlier release of Form 13.  We'll restore the space in between the custom and built-in class for the next releases.
