### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, the File Upload field can't be added.

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1286]
Am currently using Umbraco 14 and Umbraco Forms 14.1.1.

The File Upload field doesn't seem to be able to be added into the Umbraco Forms UX, and attempting to insert one will throw validation errors, even when the fields are valid. The selector for determining file types allowed seems to be broken, the validation kicks in regardless of which options are selected.

![file-upload-field](https://github.com/user-attachments/assets/2faea9bb-c17e-4b7a-9ee9-f60a58835c8e)

Reproduction
------------

1. Create a form
2. Add a 'File upload' field
3. Try to save it with any combination of allowed files. The validation will always try to stop it.

### Expected result

Selecting 'Allow all files' or a combination of file types should pass the validation and allow the field to be added.

![image](https://github.com/user-attachments/assets/ea4d9ca9-c1c2-4bae-b040-e5ce869e80c1)

Am also wondering if 'Select all files' should perhaps be toggling the other file types to 'off' and clearing the custom file types field. I'd imagine disabling them instead would be enough?

### Actual result
Selecting no file types, or 'Select all files' or any combination of files will not allow the field to be added.

**Comment by AndyButland** [comment]
Thanks for reporting @Jollus174.  This was a regression in 14.1.1 which we've resolved and will update in the next patch release.
