### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, list items added to a field will only appear in the form after saving the form and refreshing.

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1287]
When adding new items to an existing field with an items repeater, such as **Single Choice** or **Multiple Choice**, those items will only appear in the form UI after saving the field, saving the form, then refreshing the page.

![image](https://github.com/user-attachments/assets/4b24d490-19c2-4b53-84af-f7fdcc725545)

This also leads to UX quirks like conditionals (which are normally dynamically populated) not showing newly added items even though they should.

![image](https://github.com/user-attachments/assets/7ee909c4-2a9d-483c-9971-210022f10a1d)

This was not the case in Umbraco 13 running Umbraco Forms 13, and the form UI would update automatically when new list items were added.

Reproduction
------------

### Bug summary

Adding new items to a field such as such as **Single Choice** or **Multiple Choice** does not update the form UI.

### Specifics

Am running Umbraco 14.2.0 and Umbraco Forms 14.1.1. This issue does not occur in Umbraco 13.0.3 running Umbraco Forms 13.0.1.

### Steps to reproduce

1. Create a **Single Choice** or **Multiple Choice** field, and add items to it. Save the field.
2. Edit the field, and add/remove some items. Upon saving, the form UI does not update.

### Expected result

The form UI should accurately reflect what items are in a **Single Choice** or **Multiple Choice** field, without needing to save the form and refresh the page.

### Actual result

Editing the items in a **Single Choice** or **Multiple Choice** field and saving the field does not update the form UI.

**Comment by AndyButland** [comment]
Thanks for reporting @Jollus174.  We've resolved and will update in the next patch release.
