### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, copying a field will also copy the alias exactly the same

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1288]
When clicking the copy icon for a field, the field will be copied successfully, but the alias will also be copied exactly the same. This behaviour will lead to form bugs where multiple fields have the exact same alias.

![image](https://github.com/user-attachments/assets/a58cad9e-563a-4edc-aa86-f8f0869bac67)

In Umbraco 13, when a field was copied, it would _iterate a number at the end of the alias_ to prevent duplicate aliases. If there was no number, it would append it.

![image](https://github.com/user-attachments/assets/aa0d1b1a-bba0-4ead-845e-7198cfd6899b)

Reproduction
------------

Copy a field, and the alias will be unchanged.

### Bug summary

Copying a field should either append a number to the end of the new alias, or iterate it if one exists.

### Specifics

Am running Umbraco 14.2.0 and Umbraco Forms 14.1.1. This issue does not occur in Umbraco 13.0.3 running Umbraco Forms 13.0.1.

**Comment by AndyButland** [comment]
Thanks for reporting @Jollus174.  We've resolved and will update in the next patch release.
