### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, conditions dropdown sometimes appearing blank.

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1289]
This one might be part of a larger Umbraco 14 issue.

When attempting to add conditions to a field in Umbraco Forms 14.1.1, I was noticing that dropdown for selecting fields was returning as empty.

![image](https://github.com/user-attachments/assets/3644e67f-611e-4932-8ed5-b90772868730)

This is because my Umbraco login had timed out, but that wasn't obvious in the CMS. Only upon refreshing the page and my login token did the dropdown populate.

![image](https://github.com/user-attachments/assets/780a72f3-dd4f-4716-a154-99149d7c57c4)

Reproduction
------------

Open a form, let your Umbraco login expire, try to add conditions. The dropdown will be empty.

### Bug summary

Umbraco 14 doesn't seem to notify when the login token has expired, which can lead to unexpected behaviour when making edits, such as the conditions dropdown being empty.

### Expected result

If a user's Umbraco 14 login has expired, then the user should be brought to the login dashboard. Upon logging in, they can be redirected back to where they were. Their page session shouldn't persist without any notification, since it could lead to unexpected behaviour when interacting.

### Actual result

When a login has expired, the user can still interact with the form UI, even though some parts which require CMS endpoints are locked out.

**Comment by AndyButland** [comment]
Thanks for reporting @Jollus174.  I will need to close this one though I think, as, as you note, this is likely something that needs to be resolved in the CMS itself.  You might want to see if something similar it's already reported on the CMS issue tracker, and if not, report there.
