### ISSUE TITLE
In Umbraco 14.2.0 and Umbraco Forms 14.1.1, can't turn validation off for a field once it's turned on.

### ISSUE THREAD

**Issue by Jollus174** [umbraco/Umbraco.Forms.Issues#1291]
Once validation is turned on for a field (validate as number, as email, etc), it's not obvious how to turn it back off, as there's no blank option.

Currently the workaround is to select **...enter a custom validation**, clear the field, then save.

![image](https://github.com/user-attachments/assets/1f1cba37-9613-4263-86f5-72af002bdbb5)

In Umbraco Forms 13 there's a 'blank' option, which allows us to turn it back off. This seems to be removed in UF 14, can it please be restored?

![image](https://github.com/user-attachments/assets/1f591c66-0483-4a8a-a775-55702e474e26)

**Comment by AndyButland** [comment]
Thanks for reporting this (and the other) issues @Jollus174.  We've resolved and will update in the next patch release.
