### ISSUE TITLE
Unable to create form conditions

### ISSUE THREAD

**Issue by bnaDiagram** [umbraco/Umbraco.Forms.Issues#1301]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0-RC1

### Bug summary

When creating a form question with conditions, the "Select" dropdown does nothing. It does not display any option for me to choose a previous question. I can't save the form if it has conditions, either. I get the "ApiError:Not Found" error message.
![image](https://github.com/user-attachments/assets/995569c0-2d85-4105-ad21-65f07037a19c)

### Steps to reproduce

Create form questions and turn on the conditions option for the last question.

**Comment by AndyButland** [comment]
Thanks for flagging this.  Seems the issue is that this list where you select the fields wasn't updating unless you saved the form, so you can do that as a workaround at the moment.  But we'll get this fixed for the next patch release.
