### ISSUE TITLE
User able to delete entries with only view access

### ISSUE THREAD

**Issue by benbracedigital** [umbraco/Umbraco.Forms.Issues#1303]
In the Users section > Form Security I have set a user to have View Entries.

However, this also allows the user to be able to delete entries. I would expect a user to be able to delete entries if they had the Edit Entries options. 

Or better still, there is a new option that toggles whether a user has delete permission or not.

### Bug summary

User can delete entries with only view access.

### Specifics

Umbraco Forms version 13.1.2

### Steps to reproduce

1. Create a user
2. Give user access to view form entries
3. Browse to form entries and attempt to delete a form entry.

### Expected result

User should not be able to delete entries unless they have edit entries or there should be a permission to toggle delete entries.

### Actual result

User can delete entries.

---
_This item has been added to our backlog AB#44904_

**Comment by AndyButland** [comment]
Yes, it's a fair point with the current iteration of the product.  If you know the history, you can see why it came about this way. Previously there was no option to edit entries in the back-office, only view (and delete) them.  So when we introduced the feature to allow edit, we brought in the new permission - but left the old one unchanged (both in name and function).

To avoid a breaking change in functionality, probably best would be to introduce an additional permission as you suggest - we could default it so we maintain the current behaviour, but allow administrators to separately allow or disallow view, edit and delete operations.

**Comment by AndyButland** [comment]
We'll add this additional permission in the next minor releases.
