### ISSUE TITLE
Conditions on a checkbox don't feed through to further pages

### ISSUE THREAD

**Issue by harryfleetwood-cti** [umbraco/Umbraco.Forms.Issues#1304]
When using a multi-page form, if a condition to show a field is on, for example, page 3 and the condition is to match on if a checkbox is checked on page 1, then the condition doesn't get matched.

Other inputs such as short answers work as expected if I set a condition to display a form input on page 3 if a short answer has an input of "Yes".

I've attached a video and an example form of what I've tested against.

Umbraco Version: 13.4.1
Umbraco Forms: 13.2.0

[form-2a8f27d1-c6bf-403a-9a48-17690928639d.json](https://github.com/user-attachments/files/17306669/form-2a8f27d1-c6bf-403a-9a48-17690928639d.json)

https://github.com/user-attachments/assets/17446ef0-9666-49c2-8c7c-5a774350f22c

Reproduction
------------

Create a multi-page form.

Add a checkbox to page 1, and any form input to page 2. Set a condition on the input on page 2 to show if the checkbox on page 1 is "true". 

The input on page 2 does now show even though the condition is matched. 

If setup the input on page 1 to be an input that shows a form input on page 2 if the input is matched as "Yes", then the expected behaviour occurs.

**Comment by AndyButland** [comment]
Thanks for reporting and providing such clear replication steps.  I've found the issue here and will prepare it for fix in the next releases (likely the next minors, but if we put out a patch for other reasons in the meantime I'll re-label to include this too).
