### ISSUE TITLE
Nested pages UI bug when reordering pages in a form

### ISSUE THREAD

**Issue by krusomaj** [umbraco/Umbraco.Forms.Issues#1307]
In Umbraco forms there is a UI bug related to **Reordering** pages in a form.
When reordering page you can drag **Page 2** inside of **Page 1** and it looks like one page is nested in the other. This should probably not be possible. But it is possible in the UI.
When you save and reload. **Page 2** will jump back to not being nested again.
![449d6af3-f305-49c4-8c66-0ad4bf43d57e](https://github.com/user-attachments/assets/d41e55a2-beba-444e-8075-3501083bb760)

Reproduction
------------

### Specifics

Forms version: 13.2.1
Chrome version: Version 129.0.6668.101 (Official Build) (64-bit)

### Steps to reproduce

Create a form
Create Page 1 and Page 2
In Page 1 insert Group 1 with a question/field
In Page 1 also insert Group 2 with a question/field
Now click the reorder button
Drag Page 2 between the Group 1 and Group 2 inside of Page 1.
This might take a bit of wiggling around but it is possible. See the attached GIF.
After placing Page 2 nested inside of Page 1. When you press **Done reordering** and save and then reload. 
Page 2 will now return to not being nested.
This is why I think it should not be possible to move Page 2 into Page 1.

### Expected result

I expected that it would not be possible to drag **Page 2** inside of **Page 1** in the UI.

### Actual result

It was possible to drag **Page 2** inside of **Page 1** in the UI.

**Comment by AndyButland** [comment]
Will close this as it duplicates #822.
