### ISSUE TITLE
Umbraco Forms 10.5.7 - Multi Step form stopped working

### ISSUE THREAD

**Issue by rickbracedigital** [umbraco/Umbraco.Forms.Issues#1313]
When using a Multi Step form (3 steps), I can navigate between Step 1 and Step 2 but not passed Step 2. The "Previous" and "Next" buttons are greyed out (disabled).

To get this working, I've rolled back to Umbraco Forms 10.2.3.

We have recently upgraded from Umbraco Forms 10.1.1 to solve an issue with email attachments not being attached in the email workflow. However, upgrading to Umbraco Forms 10.5.7 has now introduced the problem below.

Reproduction
------------

To re-produce, I've done the following:

- Create an Umbraco Form with multiple steps
- Add basic form fields on all steps
- Add the form to an Umbraco page

- When the user fills out all the fields on Step 1, they click "Next"
- The user is then presented with all the fields on Step 2 which they then fill in
- When the user clicks "Next", nothing happens (there is no loading of the page) - the only thing that occurs is the "Previous" and "Next" buttons are greyed out (disabled)

To fix, I've rolled back to Umbraco Forms 10.2.3 and followed the above steps. However, on Step 2, when the user clicks "Next", the next Step (Step 3) is presented to the user. After that is filled in, clicking "Submit", submits the form as expected.

Many thanks for looking

Rick

**Comment by AndyButland** [comment]
I'm not seeing this with a clean install I'm afraid, so would suggest the following.

After the upgrade, be sure that you've cleared your cache (I'm wondering for example if the front-end assets for the form rendering on the website aren't updated to match the partial views that are being used).

If you have a custom theme, try it with the default theme.  If that works, you might need to carefully examine the differences between your custom one and the default one and see if there's a difference you need to apply to yours.  The latest themes for Forms 10 are available [here](https://umbra.co/umbraco-forms-default-theme).

Maybe verify yourself to confirm what I say that it works in a new project.  Perhaps there's some difference in form setup I missed that means you do still see the issue.  For reference I did the following.

Installed via:

```
dotnet new install Umbraco.Templates::10.8.7
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 10.5.7
dotnet run
```

Then installed Umbraco, created a document type with simple template:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Sample Form Page</title>
</head>
<body>
<h1>Sample Form Page</h1>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}
@Html.RenderUmbracoFormDependencies()
</body>
</html>
```

Created a form with three pages, added it to the content item and rendered the page.

**Comment by AndyButland** [comment]
I'll close this one now since there was no further discussion.
