### ISSUE TITLE
Umbraco Forms - Add persmissions on folders

### ISSUE THREAD

**Issue by AnnaTornroth-NLTG** [umbraco/Umbraco.Forms.Issues#1314]
We have a need from our operations at NLTG to enter permissions on folders in Umbraco Forms.
Several people work in Umbraco Forms and there is a risk that someone changes or deletes a form incorrectly.

**Comment by AndyButland** [comment]
Maybe this won't cover all your requirements, but it is possible already to set "Start Folders" for each user or user groups.  If you do that, the user would be restricted to just the folders they have been given access too.

https://docs.umbraco.com/umbraco-forms/developer/security

Could you confirm if you have tried using that and,  if so and it comes up short, what specifically you are missing please?

**Comment by AndyButland** [comment]
I'll close this one now since there was no further discussion.
