### ISSUE TITLE
Workflow Stage Displays [formEntries_workflowExecutionStageRejected] When Stage is Rejected

### ISSUE THREAD

**Issue by paulsterling** [umbraco/Umbraco.Forms.Issues#1316]
Workflow Stage Displays [formEntries_workflowExecutionStageRejected] When Stage is Rejected when viewing the Workflow Audit from a form record entry. When viewing the form entries lsit view the State displays "Rejected." This is specific to the form **Stage** rather that the form **State**.

Reproduction
------------
If a form State is set Rejected, the form Stage displays as [formEntries_workflowExecutionStageRejected] in Workflow Audit. The other Stages - Submitted, Approved - display correctly.

We are setting the form State to Rejected in our custom form workflow

`_recordService.RejectAsync(context.Record, context.Form).Wait();`

![Screenshot 2024-11-14 105211](https://github.com/user-attachments/assets/689fb40d-fed3-4791-a469-e8ed43ce9fd2)

The State is displayed correctly in the entries list view
![Screenshot 2024-11-14 105155](https://github.com/user-attachments/assets/5f03113f-a3ea-4673-b471-4644b82b5bee)

### Specifics
Umbraco CMS 13.5.2
Umbraco Forms 13.3.0

###Expected Result
The form Stage should display Rejected as it does for other form Stages like Approved.

![Screenshot 2024-11-14 105224](https://github.com/user-attachments/assets/0979905c-ab04-4415-abc1-2fd0c6e16bea)

---
_This item has been added to our backlog AB#46011_

**Comment by AndyButland** [comment]
Thanks for reporting this. We'll fix up for the next patch releases.
