### ISSUE TITLE
FormPrePopulateNotification - file upload doesn't work

### ISSUE THREAD

**Issue by nexwork-percy** [umbraco/Umbraco.Forms.Issues#1317]
When you register even a dummy, empty FormPrePopulateNotification handler, any form with a File Upload will not work.

Reproduction
------------

Setup a new empty project 

```
dotnet new -i Umbraco.Templates::13.5.2
dotnet new umbraco -n "FormsPrePopulateBug"
dotnet new sln -n FormsPrePopulateBug
dotnet sln add .\FormsPrePopulateBug\FormsPrePopulateBug.csproj
dotnet add Umbraco.Forms::13.3.0
```

Add a FormPrePopulateNotificationHandler

```
public class FormsComposer : IComposer
{
    /// <summary>
    /// Register event handlers for Umbraco Forms.
    /// <see href="https://docs.umbraco.com/umbraco-forms/developer/extending/adding-an-event-handler" />
    /// </summary>
    /// <param name="builder"></param>
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<FormPrePopulateNotification, FormsPrePopulateNotificationHandler>();
    }
}

public class FormsPrePopulateNotificationHandler : INotificationHandler<FormPrePopulateNotification>
{
    public void Handle(FormPrePopulateNotification notification)
    {
        // Empty
    }
}
```

Create a form and name it 'Test Form' with a File Picker.
Create a doctype and name it 'Home', allow Root, add a Form Picker and name it 'A Form', and allow the 'Test Form' to be picked.
Home can have a very simple template:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}

@await Component.InvokeAsync("RenderForm", new { formId = @Model.AForm, includeScripts = true })
```

### Specifics

Using Umbraco 13.5.2
Umbraco.Forms 13.3.0

When commented out the line ```builder.AddNotificationHandler<FormPrePopulateNotification, FormsPrePopulateNotificationHandler>();```, the File Upload works.

When not commented out, the file upload does not work.

### Expected result 

Form Entry contains the uploaded file.

### Actual result

Form Entry does not contain the uploaded file.

---
_This item has been added to our backlog AB#46015_

**Comment by nexwork-percy** [comment]
That's great news! Thanks @AndyButland !

**Comment by nexwork-percy** [comment]
That's great news! Thanks @AndyButland !

**Comment by nexwork-percy** [comment]
Hi @AndyButland ,

Many thanks for fixing this issue fo the 13.3.1, much appreciated.
Do you by any chance have a ETA on when the 13.3.1 will be available (on NuGet.org)?

Many thanks!
- Percy

**Comment by AndyButland** [comment]
Hopefully tomorrow - I'm preparing the releases today so as long as I don't run into any issues then they'll be out in the morning.

**Comment by nexwork-percy** [comment]
Awesome! You rock!

**Comment by MagnusWLarsenGormAgency** [comment]
@AndyButland 
The same issue seems to still be present for the "Image Upload" field. 
Tested in version 13.8.1
