### ISSUE TITLE
Umbraco Form - root user can't view entries or security folder

### ISSUE THREAD

**Issue by MrPels** [umbraco/Umbraco.Forms.Issues#1318]
### Bug summary

I have observed that after we upgraded Umbraco Forms from 14.1.1 to 14.2.0 that i no longer can edit or view entries for a form. Furthermore the security folder is also not showing any dashboard of each user. 
There are no console errors showing, and the Umbraco log is not reporting any errors.

**I am logged in as the root user (-1 id).** I have checked with another user and they do not have this problem they can view both entries of all form, but also have access to the security folder and can view the settings on each user as normal.

As a sanity check we also checked the database table "UFUserSecurity", to ensure ViewEntries, EditEntries and DeleteEntries was set to 1. Which it was for the root user.

Image 1 - displays and empty view for entries when a form is selected 
<img width="1912" alt="image" src="https://github.com/user-attachments/assets/e7503a73-5206-49fb-a2d1-3e0c5e2ad447">

Image 2 - no user settings are showing for security folder, also only select the first user clicked afterwards it never change
<img width="1923" alt="image" src="https://github.com/user-attachments/assets/8b5e546c-560e-481c-ade9-1e15723534ec">

Image 3 - the initial Forms dashboard loads as expected showing entries does exist on each form, but also viewing entries from "View entries" produce the same bug as shown in image 1.
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/646c8d86-dbb5-4fcd-a43a-db027315f969">

### Specifics

Browser: 130.0.6723.119
Umbraco Forms 14.2.0
Umbraco CMS 14.3.1

### Steps to reproduce

Prerequirements
1. Spin up a new Umbraco project on version 14.3.1
2. Install the nuget "Umbraco.Forms" on version 14.2.0
3. Log in to the backoffice with the root user (id -1)
4. (optional) create a new user and use it to see the difference

Entries not showing case:
1. Navigate to the form section, and create a simple form with "new form..."
2. Make some submissions to a form to ensure some entries 
3.a try and open the "Entries" tab in the upper right corner when a form is selected
3.b else in the Form overview dashboard showing all forms click "View entries" instead from the list view.

Security folder users not showing case:
1. Simply just click on a user, even the root user itself is not showing

### Expected result

As the root user i expect to be able to see entries from all forms, and also edit, view or delete user security rights when using Umbraco Forms.

### Actual result

All normal users that have Forms rights have access to view entries and see security details of users. 

However after going from Umbraco forms 14.1.1 to 14.2.0 the root user (id -1) no longer seem to be able to view entries or security details of form users. But can still create forms.

---
_This item has been added to our backlog AB#46013_

**Comment by nexwork-percy** [comment]
Hi @MrPels 
Did you check the Users Forms Security? I thought even for the 'root' user this has to be set (there may be an appsetting, but I'm not sure).
![afbeelding](https://github.com/user-attachments/assets/dbae4462-b330-41a3-8c0d-f0a98e9f3c73)

Just trying to be helpful

**Comment by nexwork-percy** [comment]
Ah, worth a try...
Maybe somebody else can help you further.

Best wishes,
Percy

**Comment by AndyButland** [comment]
I haven't been able to replicate this one I'm afraid.  I've tried your replication steps as follows:

```
dotnet new install Umbraco.Templates::14.3.1
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 14.2.0
dotnet run
```

Then installed with default options, logged in and could create forms, view entries and view the security details of the user.

Please could you review and confirm you do see the issue if you follow these steps, or if you don't and you did something slightly different when you detailed the steps above, let me know what I've missed please?

Maybe also if there are errors in the browser console that may give a clue as to what's going on too.  Thanks.

**Comment by MrPels** [comment]
I can confirm that running the setup steps, does in fact end up working for the root user.

```
dotnet new install Umbraco.Templates::14.3.1
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 14.2.0
dotnet run
```

So the problem might have occurred through migration from Umbraco Forms 14.1.1 to 14.2.0, and Umbraco Cms 14.2.0 to 14.3.1

So instead if i try and reproduces our migration, i do the following

```
dotnet new install Umbraco.Templates::14.2.0
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 14.1.1
dotnet run
```

After install with default options, i can log in and could create forms, view entries and view the security details of the user, with the root user.

However after i bump up the packages with
```
dotnet add package Umbraco.Cms --version 14.3.1  
dotnet add package Umbraco.Forms --version 14.2.0
dotnet run
```
I experience a lot of errors in the Forms section after migration, close to the problem i experience against our own sql database (not sqllite). (However no errors in my real solution are produced, as in the manner of this local solution console).

However after running this new solution a second time the problem seem to disappear ? ? 

There also seems to be a migration button displayed under "Packages" section that produces errors and a infinity spinner.
<img width="850" alt="image" src="https://github.com/user-attachments/assets/b8f8f82e-33d0-49c7-9256-3b70c65eee8a">

Some extra information about my real setup is we use external AD providers, and basically disable normal user logins. Could this cause problems when migration (and be related to the root user) ?

**Comment by AndyButland** [comment]
I believe these latter issues you mention are caused by [this open issue](https://github.com/umbraco/Umbraco-CMS/issues/17436) with the CMS (where a migration of the CMS and the package won't work until you restart).

You'll see some discussion about it there and on the linked issues from it.

**Comment by MrPels** [comment]
Update: 
I just ran my own solution locally again, which has all its resources hosted in Azure, with the restart in mind, now everything works again for the root user.

The case you reference is very much in line with what we did, as we bumped both the Cms and Forms at once :)

I still find it strange that what we experienced regarding the Forms section, only effected the root user, and not everyone else.

**Comment by AndyButland** [comment]
It does seem odd, I agree, but I can also expect errors if the front-end is working against a database that hasn't been migrated.  Given you've resolved it in your solution and the cause does seem to be related to this open issue, I'll close this one now.
