### ISSUE TITLE
Umbraco Forms v15 formProviderFieldTypes_recaptcha2ShowLabelLabel

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco.Forms.Issues#1319]
When you add (or edit) a Recaptcha2 field, this is shown as-is:
formProviderFieldTypes_recaptcha2ShowLabelLabel
Together with:
formProviderFieldTypes_recaptcha2ShowLabelDescription

---
_This item has been added to our backlog AB#46009_

**Comment by AndyButland** [comment]
Thanks for reporting this.  We'll fix up for the next patch releases.
