### ISSUE TITLE
NuGet package includes EPPlus.dll and dependency

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#132]
Because the `UmbracoForms.Core` packages includes the EPPlus.dll assembly (version 4.0.5) **and** a dependency on EPPlus >= 4.0.5, conflicting versions will result in compilation errors. E.g. updating to the latest EPPlus and then re-installing (or updating) UmbracoForms.Core updates the project reference to the included EPPlus version (4.0.5).

This issue was brought to attention 2 years ago and still not fixed: https://issues.umbraco.org/issue/CON-1278.

**Comment by ronaldbarendse** [comment]
Any progress on this? Looks like this is fixed for Forms version 8, but still not for 7.1.1.

**Comment by nul800sebastiaan** [comment]
This is now fixed for the next release (such a joy, doing a deep dive into our old nant build definitions! 😅).
