### ISSUE TITLE
Multiple-choice not working on a multipage form, when using FormPrePopulateNotification

### ISSUE THREAD

**Issue by leonfranken** [umbraco/Umbraco.Forms.Issues#1320]
When using Umbraco 13 with Umbraco Forms, and implementing your on notification handler based on the FormPrePopulateNotification, then the multiple-choice question doesn't saves the (multiple) answer correctly, when the form contains more then 1 page.

Reproduction
------------
- Configure your own handler for the FormPrePopulateNotification handler 
- Add a form via the Umbraco backoffice
- Add at least two fields, one per page
- Add at least one multiple choice question
- Add the form to a page
- Fill in the form and select at least two options for the multiple choice question
- Submit the form (save record to the database)
- See that only the first answer of the multiple choice is saved to the database

This only happens when you implement the FormPrePopulateNotification.
When that custom notification handler is removed, the form saves multiple answer for the multiple choice question.

**Comment by AndyButland** [comment]
Thanks for reporting this along with the clear reproduction steps.  We've been able to replicate and resolve it so will include in the next round of patch releases.

**Comment by ZiporaD** [comment]
how can i get the patch releases?

**Comment by AndyButland** [comment]
Forms is released via NuGet:, so you can update from there: https://www.nuget.org/packages/Umbraco.Forms

**Comment by AndyButland** [comment]
I'm afraid Umbraco 12 (and Forms 12) is now "end of life", so we aren't releasing updates any more for that version.
https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/

I'd suggest trying to get onto Umbraco 13, which is a long term supported version.  The upgrade from 12 to 13 should be fairly straightforward as major Umbraco upgrades go.
