### ISSUE TITLE
Export dialog should be closeable using `esc` shortcut

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#1321]
In export dialog is isn't possible to close dialog using `esc` shortcut.

![image](https://github.com/user-attachments/assets/17334bcf-a7d2-4afd-8f22-627fb0467590)

The button is missing `hotkey="esc"`.

![image](https://github.com/user-attachments/assets/20ca434f-f281-4c98-ae08-ce73cb2c0c41)

Besides that the button should be a `<button>` element and with "link" style as in core.

![image](https://github.com/user-attachments/assets/5244ea91-d5cd-44f7-8608-749b5407a09a)

Umbraco 13.5.2
Forms 13.3.0

**Comment by AndyButland** [comment]
Thanks @bjarnef, good spots.  We'll include this update in tomorrow's patch release.
