### ISSUE TITLE
v15 not rendering labels/descriptions for custom workflows

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco.Forms.Issues#1322]
For example, override BaseEmailWorkflowType (just an empty class is enough with the basics (Id/name/etc)) and then add this workflow in the backend.
What you'll see:
![image](https://github.com/user-attachments/assets/97fcf705-020f-454f-a64b-c05aaccb8b94)

**Comment by AndyButland** [comment]
This is expected I believe - one of the changes for 14+ was the localization becoming a front-end concern.  There's some details about registering a localization manifest here:
https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-fieldtype#language-files

And also in the general CMS documentation here if you prefer to do it with JavaScript (which is probably best if it's the only front-end customization you need):
https://docs.umbraco.com/umbraco-cms/customizing/extending-overview/extension-types/localization#registering-localization

I'll close this but please re-open if having followed the above you are still having trouble.

**Comment by PhyxionNL** [comment]
Thanks Andy, that seems to work, but the Alias you set to the Settings attributes is always ignored, it's always using the property name itself? The alias should be able to change the used name I think? Similar to the Alias of the WorkflowType.

**Comment by AndyButland** [comment]
Yes, that's right, it uses the property name. Agree it would probably be more consistent if the alias of the setting could be used, but in practice I think just using the property name is sufficient.  Please feel free to raise a separate issue for that if you think there's value in having that option.
