### ISSUE TITLE
V15 workflow conditions uses "Show/hide this field" instead of "Run/ignore this workflow"

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco.Forms.Issues#1323]
Accidentally submitted this...

In V13 workflow conditions:
![image](https://github.com/user-attachments/assets/e3d27d63-8fa0-4f27-96fa-ca1dc63dd65a)

In V15 workflow conditions:
![image](https://github.com/user-attachments/assets/e32c4f7e-44a6-4d61-be98-1f99ade86bb0)

**Comment by AndyButland** [comment]
Thanks - can see we've not correctly "localized" this element when used as a condition for the different features they can be applied to.  We'll resolve this in the next patch releases for 14+.
