### ISSUE TITLE
V15: Rich text field type lacks rich text formatting

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco.Forms.Issues#1326]
The _Rich text_ field type lacks an HTML editor in Umbraco Forms 15. It looks to be using TinyMCE, which was replaced with TipTap in Umbraco CMS 15.

![image](https://github.com/user-attachments/assets/8415cad3-4d3f-4b9e-b677-216da6b4c24a)

---
_This item has been added to our backlog AB#46236_

**Comment by AndyButland** [comment]
Thanks for reporting this... it is indeed an oversight for Forms 15.  We'll get this updated for the next patch release.
