### ISSUE TITLE
Allow for file upload field error messages to be customized/translated

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco.Forms.Issues#1327]
Currently, when using the upload field, any kind of server validation of the selected files are using hardcoded, english texts, eg:
![image](https://github.com/user-attachments/assets/39193acf-10cd-47c1-ad36-590c5bbf90d3)

These texts should be able to be translated and customized by the dev/user in some way.

---
_This item has been added to our backlog AB#46304_

**Comment by AndyButland** [comment]
We'll add support for this via new settings on the file upload field type in the next minor releases of Forms.

**Comment by sniffdk** [comment]
A bit late here but thank you @AndyButland for this fix 🙏 👍

**Comment by AndyButland** [comment]
You're welcome!
