### ISSUE TITLE
Forms fail with Content Type error after Umbraco Cloud automatic upgrade

### ISSUE THREAD

**Issue by Alkaersig** [umbraco/Umbraco.Forms.Issues#1328]
After an automatic forms upgrade to our sites on tuesday, we starting getting reports that forms were failing on customer sites.

We were seeing this error:
"One or more errors occurred. (This request does not have a Content-Type header. Forms are available from requests with bodies like POSTs and a form Content-Type of either application/x-www-form-urlencoded or multipart/form-data.)"

It seems that v13.3.x introduced a change to how ProcessSubmittedValue is used. The description of the field says:
"Triggered when the form's viewmodel has been posted back to the server and validation has passed."

But now the method is also triggered at render time with a request of type "GET".

The only default field that uses this seems to be the FileUpload field type. The field type had a new check implemented that checks the Content Type of the request:
`if (!context.Request.HasFormContentType)
{
    return list;
}`

This feels like a breaking change that at least should be documented in the release notes and not automatic rolled out to cloud sites, since this breaks all custom field types that overrides the ProcessSubmittedValue method.

I am not sure why this method is now triggered at render time, but i guess there's a good reason for it.

**Comment by AndyButland** [comment]
Hi @Alkaersig - sorry for you running into this.  I've had a look back over the changes made for this patch - which in this area were done looking to resolve https://github.com/umbraco/Umbraco.Forms.Issues/issues/1317.

I think this part of the update is an error to be honest.  We shouldn't need to call this unless we're in the context of a form POST, and can fix the original issue without this update, so I'm expecting we'll revert this for the next patch once I've confirmed that.

In the meantime I'm afraid you will need to add this check to your custom field type.
