### ISSUE TITLE
TipTap Rich Text Editor missing in Umbraco Forms custom workflows and fields

### ISSUE THREAD

**Issue by thf-09** [umbraco/Umbraco.Forms.Issues#1329]
It appears that the new TipTap Rich Text Editor is missing as a view in custom created fields and workflows in Umbraco 15. I have tried the following views and nothing shows up: "Umb.PropertyEditorUi.TipTap", "richText" and "Umbraco.RichText". 

Reproduction
------------
To reproduce, create a new workflow and add a setting that could look something like this:

        [Setting("Test", Description = "Test", View = "Umb.PropertyEditorUi.TipTap")]
        public string MyTestField { get; set; }

---
_This item has been added to our backlog AB#46603_

**Comment by AndyButland** [comment]
What version are you running please?  As I believe we resolved this in the latest release for 15 which is 15.0.2:
https://docs.umbraco.com/umbraco-forms/release-notes#id-15.0.2-november-28th-2024

**Comment by thf-09** [comment]
Yeah, I noticed that. I just now updated to 15.0.2, and the issue was still there. The standard RTE field used in a form seems to use TipTap (although the styling buttons are missing):

![image](https://github.com/user-attachments/assets/0191e4be-ff7d-4443-92d3-2f4eda39d307)

But in custom workflows and fields, it seems to still not work.

**Comment by AndyButland** [comment]
The missing buttons might be something you need to do if you've upgraded from 14... not sure, but I'd suggest using the same data type [that's configured for use for Forms](https://docs.umbraco.com/umbraco-forms/developer/configuration#rich-text-field-type-configuration) in some normal Umbraco content and see if you get the toolbar rendered there.

This is what we have for the built-in field:

```
        [Setting("Rich text", Description = "Enter your formatted text", SupportsPlaceholders = true, SupportsHtml = true, HtmlEncodeReplacedPlaceholderValues = true, View = "Umb.PropertyEditorUi.Tiptap", DisplayOrder = 10)]
        public virtual string Html { get; set; } = string.Empty;
```

Can you confirm you have the same?  As I can't immediately see why it wouldn't work in the same way for custom fields.

**Comment by AndyButland** [comment]
I'll update the docs here - looks like in source it is `Umb.PropertyEditorUi.Tiptap`.

**Comment by AndyButland** [comment]
Docs updated... https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor

I'll keep this open for now in case you are able to report back further as to whether you see this only with the rich text issue on Forms, or if it's similar in your use of the rich text in content.  If the latter, then it's likely better handled as a CMS issue.  But if you do see this only with the rich text features of Forms, could be there's something we need to fix in the product.

**Comment by thf-09** [comment]
I've been clicking around a lot in our solution now, and it never happens in normal Umbraco RTE fields in the CMS. However, it happens pretty consistently in any Umbraco Forms Rich Text Editor fields. It also happened with the TinyMCE fields. 

I tried to test it in a completely new solution. It works fine in the normal CMS, but in Forms it's shown like this:  

![image](https://github.com/user-attachments/assets/994acb2a-43d6-48ae-964e-cfdd7f84c385)

**Comment by nathanwoulfe** [comment]
I've been trying to replicate this with no success - I've installed a clean v15 site, with Forms 15.0.2, and no issues with TipTap in views shipped with Forms, or in custom fields.

@thf-09 are you able to share your exact setup for the new solution? Did you do anything other than installing CMS + Forms?

**Comment by thf-09** [comment]
The project I was testing it in wasn't a brand new project, but just a basically empty Umbraco project. When creating an entirely new project, I can't replicate it either. 

In my existing solution, I do still get the issue, though. It seems very inconsistent. If I refresh the page, usually the first, and sometimes second time, it works. But after that it doesn't, and I'll have to refresh the page. I know it's probably hard to figure out, but do you have any suggestions to what the issue could be or how I could attempt to fix it? 

![Animation](https://github.com/user-attachments/assets/d5a4a8fe-80ea-4bae-b102-d107dd4ebaf1)

**Comment by thf-09** [comment]
@nathanwoulfe I also noticed in that, in the project that I updated from 14 to 15, whenever I'm trying to create a link, it fails and I get the following error in the console: 

![image](https://github.com/user-attachments/assets/61c451d4-cf2b-4feb-99ef-fac450b6d4df)

I'm not getting that error in a brand new project. Maybe these issues are connected? Am I possibly missing something in my solution?

**Comment by AndyButland** [comment]
Unfortunately - or fortunately, I'm not sure - I've spent a bit of time trying to replicate this but am still unable to I'm afraid.  Maybe as one further step I could ask if you could export a form where you experience this please?  It doesn't sound like it's specific to any form data really, but if we test with that maybe there's something interfering with it.

**Comment by AndyButland** [comment]
Thanks again @thf-09 - I've been able to replicate and think I've identified the race condition that's causing this, and been able to find a fix.  We'll include this in the upcoming releases.
