### ISSUE TITLE
clientside validation using aspnet-cient-validation library is not working (Umbraco 13.5.2 / Forms 13.3.2)

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco.Forms.Issues#1330]
A brief description of the issue goes here.

Setting up Umbraco Forms with Client-validation by following the documentation will always results in a post on submit, client validation will not stop a submit attempt.

Reproduction
------------

### Specifics

- Umbraco 13.5.2
- Umbraco Forms 13.3.2
- Tested on Chrom(ium) and Edge browsers

![image](https://github.com/user-attachments/assets/9f244c74-b40b-4661-a4ac-f9eb2dd723bc)
 

### Steps to reproduce

1. Clean install Umbraco 13.5.2
2. Create a doctype with a single RTE field.
3. Create a form (the contact preset will do) 
4. Add form to RTE via macro, default theme, set exclude scripts to true
5. Create a view for your doctype and add the relevant helper in the page head section.
6. load the page and click submit without entering any form fields, notice a submit when running developer tools on network tab.

### Expected result

Following the guide at https://docs.umbraco.com/umbraco-forms/13.latest/developer/prepping-frontend, I'd expect the apnet-clientside-validation script to validate the form and stop submission.

### Actual result

No indication of clientside validation actually occuring, the page posts back and reloads after serverside validation, validationmessages are shown on the page, and if the form is placed one a page with vertical scroll the page will "hard" refresh and load at the top (losing scroll position)

**Comment by AndyButland** [comment]
Thanks - I think you are missing the steps described on this page:
https://docs.umbraco.com/umbraco-forms/13.latest/developer/rendering-scripts

If you choose to "exclude scripts" from the rendering of the form via the macro, you still need to include them somewhere on the page.  Hence you need one of the snippets shown on the docs page I've linked.

**Comment by niekvanderreest** [comment]
@AndyButland It seems you are correct, when i set the exclude stcripts to false, the client vamidation works as expected. I guess this was a misunderstanding of all requirements on my part.

Unreleated question, how can you assure the forms scripts are always loaded where you place the snippet if an editor can still choose to keep the "Exclude Scripts" checkbox disabled?

**Comment by AndyButland** [comment]
There's not an easy technical way to do that that I can see, so would say it's more in editor training.  For most sites I'd expect it would be best to include this snippet in the place you want the scripts to be rendered, and ask editors to always exclude them if they are adding via a macro.
