### ISSUE TITLE
Copying Form with Mandatory Workflow - Removes Workflow

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco.Forms.Issues#1331]
If you implement a mandatory workflow for forms using IApplyDefaultWorkflowsBehavior

Then it is really cool, every new form has a Mandatory workflow applied and the editors can't remove it.

But if they copy the form, and don't tick 'copy workflows' then they have the form they originally created but without the mandatory workflow!

and it's hard to explain what has happened to the mandatory thing!

Reproduction
------------

Implement a mandatory workflow following the documentation here:

https://docs.umbraco.com/umbraco-forms/developer/extending/customize-default-workflows

key thing on your FormWorfklowWithTypeSettings is to set IsMandatory to True the explanation in the docs is:

// Optionally set the default workflow to be mandatory (which means editors won't be able to remove it
                // via the back-office user interface).

Now run your site and create a new form, and marvel that your mandatory workflow is automatically appended to the form.

Save the form

Choose to copy the form

don't tick the box 'copy workflows'

you'll get a new form and no mandatory workflow...

an an editor you will have been able to remove the workflow via the back-office user interface!

### Bug summary

When you copy forms, and choose not to copy workflows, mandatory workflows are not added to the copied version of the form.

This might be by design? we want editors to always be able to create a clean copy of the form and strip all workflows? - in which case we ought to rename the IsMandatory flag to be clearer, eg IsSometimesMandatory ?? so the intent is clear?

But if it isn't by design, then I'd expect copied forms to have mandatory workflows added regardless of how you tick that box.
We could put a message after the checkbox about whether to include workflows to say (All mandatory workflows will be copied) so it's clear what will happen.

### Specifics

    * Mention the URL where this bug occurs, if applicable
/umbraco/forms
    * What version are you using
  Forms: 13.2.2
Umbraco: 13.3.2
    * What browser and version you are using
   Chrome 128.0.6613.120
    * Please mention if you've checked it in other browsers as well
   I haven't checked in other browsers
    * Please include *full error messages* and *screenshots* if possible
No errors it just copies the form without the mandatory workflows

### Steps to reproduce

see reproduction section above.

### Expected result

I'd expect the form to be copied with the mandatory workflows applied as if the form had been created afresh...

### Actual result

A new copy of the form is created without mandatory workflows.

---
_This item has been added to our backlog AB#46849_

**Comment by AndyButland** [comment]
Thanks Mark, yes, I agree the best option here would be that mandatory workflows are copied whether or not you've chosen to copy the workflows to the new form.

**Comment by AndyButland** [comment]
We'll have this in place for the next minor releases of Forms.

**Comment by marcemarc** [comment]
Thanks Andy!

The workaround I have for now involves subscribing to the 'Creating' notification to check whether the FormCreatingNotification form reference has a CreateDate > DateTime.Min, as this seems to indicate a copy is taking place, so then I add 'isCopy' to the state.

Then in the FormCreatedNotification, I can check to see if it's a copy, check to see if the workflow exists and if not create it

However, if the editor ticks the 'copy workflows' option you end up with duplicate workflows (because these are presumably added 'after' the FormCreatedNotification occurs. This makes sense I think, but as we have a restriction on the editor adding multiple versions of the mandatory workflow, the duplicate (or the one without settings updated, gets removed).

But it will be great to be able to take all of those shenanigans out with the fix!

(not that it would be necessary, but it could be good to include something in the 'state' for when a form is 'copied' like you do when a form is moved? - although other than this, I'm not sure what the use case would actually be! - notify if someone has copied a form?)

Thanks again!

regards

Marc
