### ISSUE TITLE
name and description of settings in custom field not rendered correctly

### ISSUE THREAD

**Issue by sirreini1** [umbraco/Umbraco.Forms.Issues#1332]
### Issue: Custom Form Field Settings Not Rendered Correctly

I created a custom form field and added it via a composer. However, the name and description of the settings for the field are not rendered correctly.

![Issue Example](https://github.com/user-attachments/assets/00fe6a12-a055-4f4e-976f-0a14e8962f9c)

---

### Reproduction Steps

1. **Created a new class for a custom form field:**

```csharp
using Umbraco.Forms.Core.Enums;

namespace UmbracoProject.Composers;

public class TestFieldType : Umbraco.Forms.Core.FieldType
{
    public TestFieldType()
    {
        Id = new Guid("31d557f2-9747-4db5-b2ec-d0c4b5d8df72");
        Name = "test";
        Alias = "test";
        Description = "";
        Icon = "icon-link";
        DataType = FieldDataType.String;
        SortOrder = 10;
        SupportsMandatory = false;
    }

    [Umbraco.Forms.Core.Attributes.Setting(
        "setting name",
        Description = "setting description",
        Alias = "testSetting",
        DisplayOrder = 10)]
    public string? TestSetting { get; set; }
}
```

2. **Added the custom field via a composer:**

```csharp
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;

namespace UmbracoProject.Composers;

public class CustomizeFormsComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.FormsFields()
            .Add<TestFieldType>();
    }
}
```

3. **Observed issue:**  
   When trying to edit the settings of the field, the name and description are not rendered correctly.

![Settings Issue](https://github.com/user-attachments/assets/2a564b7f-9054-4f11-9d8a-c2b50824dc38)

---

### Specifics

- **Umbraco Version:** 14.3.1
- **Umbraco.Forms Version:** 14.2.3
- **Browser Console Warning:**  

```plaintext
UUI-INPUT needs a `label` 
<uui-input pristine="">
```

---

### Expected Result

The label and description for each setting should display the values defined in the `Setting` attribute.

---

### Actual Result

![Actual Result](https://github.com/user-attachments/assets/2a564b7f-9054-4f11-9d8a-c2b50824dc38)

**Comment by AndyButland** [comment]
Looks like your question is duplicating [this one](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1299) that I've previously responded to, so I'll just refer you to there if that's OK.

**Comment by sirreini1** [comment]
thank you
