### ISSUE TITLE
The setting FormDesign:RemoveProvidedEmailTemplate has been removed from Umbraco Forms 15

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco.Forms.Issues#1333]
The [version specific upgrade notes](https://docs.umbraco.com/umbraco-forms/upgrading/version-specific) for Umbraco 15 state:

> The setting FormDesign:RemoveProvidedEmailTemplate has been removed (as adding and removing email templates can be more consistently handled using EmailTemplateCollection).

This setting was a quick and simple means of removing the default Umbraco-branded email template, so its removal is a bit unfortunate.

Where can I find information about `EmailTemplateCollection` and how to use it to remove the default email template?

**Comment by AndyButland** [comment]
You would use the following in a composer:

```
  builder.EmailTemplates()
    .Exclude<DefaultEmailTemplate>();
```

There are details on registering additional email templates here: https://docs.umbraco.com/umbraco-forms/developer/themes#email-templates

I'll have a look at updating the documentation here to show how to remove as well.

**Comment by stephen-sherman** [comment]
Thanks Andy, I've had a go at this myself but haven't been able to get it to work - will await further guidance via the documentation update.

I note that the section you've linked to is regarding the use of Razor Class Libraries for form themes. Does removing the example template require use of this pattern?

**Comment by AndyButland** [comment]
No, RCLs for themes aren't required, it's just that if you do use them you have to use this pattern for registering them.  But it's similar for removing them.  Could you share your composer and I'll have a look?  I didn't see any issues when I tried it earlier today, but it's possible I missed something.

**Comment by stephen-sherman** [comment]
My mistake - I didn't realise that `DefaultEmailTemplate` was an existing class in `Umbraco.Forms.Core.Providers.EmailTemplates`, and was over-complicating things.

The below successfully removes `Example-Template.cshtml` from the _Email Template_ options in the Umbraco back office.

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Forms.Core.Providers.EmailTemplates;
using Umbraco.Forms.Core.Providers.Extensions;

namespace Umbraco15.Composers
{
    public class DefaultEmailTemplateComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.EmailTemplates()
                .Exclude<DefaultEmailTemplate>();
        }
    }
}
```
