### ISSUE TITLE
Store complex Provider Settings-value from Property Editor UI

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#1335]
I'm working on a WorkflowType with a setting where I would like to reuse an existing PropertyEditorUI-component.

In older versions of Umbraco Forms I could send a JSON value to the server to be stored as a string-property.

I'm trying to get this to work on v15.0.3 and I'm getting this error when the properties are validated:

![image](https://github.com/user-attachments/assets/cf0f87ae-52cd-4f9d-9e27-025c5bbd0071)

It's probably an error from the model binder, since the value is a object and not just a string. 

I've tried a couple of things:

* To use the `SupportsHtml`-option but that did not work.
* Change the property from string to `List<MyType>` (the stored value is an array). Did not work but would be really cool if it was supported.

Is there a way around this or would I have to create propertyEditorUi specifically Umbraco Forms? 

The [docs](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-type/setting-types#built-in-setting-types) indicates that this should work:

> Each setting type can have it's own user interface. So a string can use a text box but a more complicated JSON structure can use a more appropriate user interface.

Maybe you could use `JSON.stringify` if the value is a object?

Cheers!

// Markus

**Comment by AndyButland** [comment]
Will respond to this and https://github.com/umbraco/Umbraco.Forms.Issues/issues/1334 on the linked issue.
