### ISSUE TITLE
Umbraco Forms 13.2.5 - Multi Step form won't go to previous step

### ISSUE THREAD

**Issue by TobyPerplex** [umbraco/Umbraco.Forms.Issues#1340]
Reproduction
------------

### Bug summary

The Multi Step form won't go to the previous step likely because the previous button is a `<input type="submit">` instead of a `<button type="button">`

### Specifics

Where applicable:
* Version 13.2.5
* Chrome Version 131.0.6778.140 (Official Build) (arm64)
* Also happens in Firefox and Safari
* Screenshots:
Step 1:
<img width="671" alt="Screenshot 2024-12-17 at 15 39 57" src="https://github.com/user-attachments/assets/88e27d84-5099-439d-93b6-1019e446c105" />

Step 2:
<img width="671" alt="Screenshot 2024-12-17 at 15 40 15" src="https://github.com/user-attachments/assets/39483b7b-b93d-4315-874a-3a5eff7560fb" />

When clicking 'previous' button in step 2 the form is submitted and shows the 'thank you' message':
<img width="669" alt="Screenshot 2024-12-17 at 15 40 27" src="https://github.com/user-attachments/assets/4ffab10e-d53b-4646-86cf-b5cd74006c92" />

### Steps to reproduce

* Go to step 2 of a Multi Step form
* Click the 'previous' button

### Expected result

* To see step 1

### Actual result

* The form tries to submit, if all fields are valid it will submit and then shows the 'thank you' message

**Comment by AndyButland** [comment]
Are you using a custom theme here perhaps?  If so, could you share the relevant portion of your `Form.cshtml` file, with the mark-up for the buttons please?  Thanks.

**Comment by TobyPerplex** [comment]
Yes, it seems the newer versions require some data-attributes for this to work. Got it working now. Closing this issue.
