### ISSUE TITLE
Ability to find pages with forms on them

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Forms.Issues#1341]
Hello

Would it be possible to extend the forms so that it is possible to find pages with UmbracoForms on them?

I see it working like the media section which details pages on which the media items can be found.

This would help both content authors track down which forms can be removed, and also QAs who just get told "test forms" are working.

Thank you

**Comment by AndyButland** [comment]
You should fine that on the "Info" tab of a form, where you [see the references](https://docs.umbraco.com/umbraco-forms/13.latest/editor/creating-a-form/form-info#relations), similar to what you see when looking at the details of a media item.  Is that what you are after?

**Comment by RachBreeze** [comment]
Hi @AndyButland 

How did I miss that? Thank you for your help

**Comment by AndyButland** [comment]
You're welcome... a nice easy one before Christmas!
