### ISSUE TITLE
Issue with Multi-Step Form “Go” Button(Mobile) Click/Enter(Desktop) Causes Unexpected Behavior

### ISSUE THREAD

**Issue by NikolaSliFL** [umbraco/Umbraco.Forms.Issues#1343]
A brief description of the issue goes here.

We are using Umbraco Cloud version 13.5.2 and are encountering an issue with a multi-step form (v13.3.3).

Reproduction
------------

When using the mobile "Go" button, that appears on the mobile keyboard, on any step other than the first one (i.e., a step with both a "Previous" and "Next" button), the form redirects us to the previous step. The same issue occurs if we are focused on a radio button and press Enter. It seems that clicking the "Go" button or pressing Enter triggers the submit action for the first submit button in the DOM, which in this case is the "Previous" button.

### Bug summary

Multi-page form redirecting to the previous page in the following scenarios:
on mobile by pressing the "Go" button
on PC by using "Tab" to navigate to the radio button (or checkbox) selection, and choosing an option by clicking "Enter".

### Specifics

The bug has been confirmed by the Umbraco Cloud Support team. We were in communication with Karita, and she directed us to create a ticket here.

The URL where the bug can be reproduced: https://www.gambleaware.org/donate/

**Comment by AndyButland** [comment]
I've had a look and read into this.  It seems what happens here is the same as a return press with the keyboard, in that it'll look for the first submit button on the form and click that - which for a multi-page form will be the previous button.

I think the best solution to this is if we just add another, hidden, submit button to the form - which will act as the "next" or "submit" button - that's first in the DOM so takes precedence.

I'll include this in the upcoming 13.4 and 15.1 updates.  In the meantime if you wanted to do this yourselves, you could override the `Form.cshtml` file - which you would get from [the published theme files for your version](https://docs.umbraco.com/umbraco-forms/developer/themes) and place at `\Views\Partials\Forms\Themes\default\Form.cshtml` in your own solution.

The modify to add the additional button as per the update we'll be making to this file from the next release:

```
                if (!Model.IsFirstPage)
                {
                    @* When rendering the previous button, make sure there's also a next/submit button first in the DOM.
                       Otherwise the previous submit button will take precedence when the form is submitted via a return key
                       press or a mobile Go button.
                    *@
                    <input type="submit"
                           hidden
                           name="__next"
                           data-form-navigate="next"
                           data-umb="@(Model.IsLastPage ? "submit" : "next")-forms-form" />

                    <input class="btn prev cancel"
                           type="submit"
                           value="@Model.PreviousCaption"
                           name="__prev"
                           formnovalidate
                           data-form-navigate="prev"
                           data-umb="prev-forms-form"/>
                }
```

**Comment by NikolaSLI** [comment]
Hi @AndyButland 

Thank you for the quick response.

This has resolved the issue for Enter, but we are still experiencing the same problem with Go on mobile. Could we also get a solution for this case?

Also, could you please reopen the ticket as the issue is not resolved for the mobile case?

**Comment by NikolaSliFL** [comment]
Hi @AndyButland

Thank you for the quick response.

This has resolved the issue for Enter, but we are still experiencing the same problem with Go on mobile. Could we also get a solution for this case?

Also, could you please reopen the ticket as the issue is not resolved for the mobile case?

**Comment by AndyButland** [comment]
I've installed this update here https://andy-v13-test-28-2-2024.euwest01.umbraco.io/ and created a simple multi-page form.  It seems OK to me when I use return key press or the "go" button on my mobile (using the Chrome browser on Android).  Could you give it a try and see if you see different please?

**Comment by NikolaSliFL** [comment]
Hi Andy, it's working for us now as well. It’s possible that it was a cached version. 
That’s it, thanks a lot for your help! Enjoy the rest of your day!

**Comment by AndyButland** [comment]
Great, good to hear, thanks.
