### ISSUE TITLE
Show form entry in boxes

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#135]
On a form entry the details on left and on right could be wrapped in a `umb-box` which makes the background of these boxes white.

![image](https://user-images.githubusercontent.com/2919859/55469480-e5b23f00-5605-11e9-9a91-f71ac594c887.png)

Furthermore instead of "close" link, consider to add a back-link, e.g. similar to the back link here: https://github.com/umbraco/Umbraco-CMS/pull/5116 next to the heading name.

**Comment by bjarnef** [comment]
Another example where it would make sense to add the back button (which also is used in users section) and makes it consistent.
https://github.com/umbraco/Umbraco-CMS/pull/5158

**Comment by nul800sebastiaan** [comment]
Hey there

First of all, my apologies for the delay in replying here. We've been a bit busy with the last releases of Umbraco 7 and 8 that Forms got a little less attention than we wished we could give it.

We love your suggestion! This one is going on our ideas list for new features to implement in the future. Please [keep an eye on our roadmap](https://umbraco.com/products/roadmap/), it will give you an idea of where our software products are going.

Thanks, Sebastiaan on behalf of Umbraco HQ.

**Comment by AndyButland** [comment]
Fix for this has been merged and will be available in the next minor release.

**Comment by bjarnef** [comment]
better late than never! 😅🥳🚀
