### ISSUE TITLE
Setting descriptions are not visible / used

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#14]
First logged by Timo as http://issues.umbraco.org/issue/CON-859. Still true on Forms 6.0.6.

When adding a setting via a custom FieldType the description entered is not visible in the backoffice.

```
         [Setting("Allowed file types", description = "Description test",
        view = "TextField")]
        public string AllowedFileTypes { get; set; }
```

![image](https://user-images.githubusercontent.com/1260550/45161694-59ad7580-b1e4-11e8-9876-1fb9d9a08bb4.png)

**Comment by bergmania** [comment]
Hi,

I just tested in current version (7.0.4) and the description are visible in this version:

![image](https://user-images.githubusercontent.com/1561480/48198894-9e779900-e35a-11e8-8e7e-5323b0973870.png)
