### ISSUE TITLE
Workflow "Send email" error

### ISSUE THREAD

**Issue by MrCosmo** [umbraco/Umbraco.Forms.Issues#143]
Send email workflow can't email due to an error:
There was a problem sending an email to "valid@email.com" from Workflow for Form "Test form" with id "xyz" for Record with unique id "abc".

Reproduction
------------
### Steps to reproduce

Installed a clean Umbraco V8.0.1 website without the starter kit. After installation I installed Umbraco Forms via the backend. Create a simple form (content doesn't matter).
After that edit the workflow to send an email (without template) to a pre-defined email of your choice. 

Create some document type in order the view and submit the form on the frontend and submit the form.

In the Umbraco backend logviewer you will notice there is an error

### Specifics

Umbraco v8.0.1
Forms: 8.1.1

### Expected result

I expected the email to be send to the email address I configured in the workflow

### Actual result

Error:
There was a problem sending an email to "valid@email.com" from Workflow for Form "Test form" with id "xyz" for Record with unique id "abc"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Forms.Core.Services.XmlService.ToXml(RecordField recordField, XmlDocument xmlDocument)
   at Umbraco.Forms.Core.Services.XmlService.ToXml(Record record, XmlDocument xd)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail.Execute(Record record, RecordEventArgs e)

---
_This item has been added to our backlog [AB#2250](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2250)_

**Comment by dmnscreativetech** [comment]
I am seeing this issue as well.  Same configuration v8.0.1 with forms 8.1.1, same error as OP.  I can share any all info that would be helpful in resolving this.  Running with build mode set to "DLL" if that makes any difference.  So far have deleted/recreated the forms in the Backoffice, unistalled/reinstalled Forms, moved the form from a Macro in an RTE to be embedded on the Template and lots of playing with the mailsettings/smtp in web.config.  Another interesting thing which may or may not be related, I can not get the thank you message to appear from the workflow. The redirect option does seem to work.  Form submits/entries are being created in the Entries folder.  Complete Error from the logs is below.

{"@t":"2019-04-23T01:50:35.8169065Z","@mt":"There was a problem sending an email to {Email} from Workflow for Form {FormName} with id {FormId} for Record with unique id {RecordId}","@l":"Error","@x":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Umbraco.Forms.Core.Services.XmlService.ToXml(RecordField recordField, XmlDocument xmlDocument)\r\n   at Umbraco.Forms.Core.Services.XmlService.ToXml(Record record, XmlDocument xd)\r\n   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail.Execute(Record record, RecordEventArgs e)","Email":"validEmail@gmail.com","FormName":"Contact form","FormId":"b2ed8850-52a7-49e4-9bbd-a5cbd6322d34","RecordId":"25aa305d-27df-4c21-9b29-8ee4425a1ff9","SourceContext":"Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail","ProcessId":68548,"ProcessName":"w3wp","ThreadId":171,"AppDomainId":9,"AppDomainAppId":"LMW3SVC211ROOT","MachineName":"A2NWVPWEB115","Log4NetLevel":"ERROR","HttpSessionId":"dfszx3ickdtatgsfhg14n5pr","HttpRequestNumber":7,"HttpRequestId":"312bad58-90a7-4002-88ff-cbd29e073306"}

Thanks,
-Roger

**Comment by dmnscreativetech** [comment]
Just wanted to add an update to help with diagnosis...  The problem I described above is still an issue for us, however when I changed my workflow step from Email to Email with Template it started working

**Comment by FransdeJong** [comment]
Can confirm the default workflow is broken

**Comment by christopherrobinson** [comment]
Also encountering this on a fresh build... wondering if I made the jump too soon against better judgement.

As this is a paid product could we secure an ETA on a fix/patch being pushed out?

**Comment by iuliaionescu** [comment]
I am facing same issue as the one described above, am using Umbraco Forms:8.1.1
"send email with template (razor)" - works fine
"send email" - doesn't send any email and throws an error

Message:
There was a problem sending an email to "iulia@crumpled-dog.com" from Workflow for Form "Talk to us" with id 2c1aa0bc-4fef-4837-9f50-07b91124bd3c for Record with unique id ec595ace-2b9f-4613-8489-d059e009d981									
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Forms.Core.Services.XmlService.ToXml(RecordField recordField, XmlDocument xmlDocument)
   at Umbraco.Forms.Core.Services.XmlService.ToXml(Record record, XmlDocument xd)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail.Execute(Record record, RecordEventArgs e)

**Comment by nul800sebastiaan** [comment]
Thanks for the reports, we're working on the issue soon and will keep you updated here.

**Comment by FransdeJong** [comment]
Why is this issue closed? Is it fixed in the next version?

**Comment by nul800sebastiaan** [comment]
Ah, I didn't realize you could not see this but it was closed with a PR that was merged! 👍 So no panic, it will be in the next release. 
I'll post a nightly here so you can benefit from it now while we get a release ready.

**Comment by FransdeJong** [comment]
Great, no panic but it was a strange moment to see this issue closed. Thanks for the info. Maybe you could add the released label in this issuetracker like in the CMS one so we can see in what version it will be released?

**Comment by nul800sebastiaan** [comment]
I will, give me some time to figure out what the version number will be mate. 😅

**Comment by FransdeJong** [comment]
Ah right, that would be a required variable indeed.

**Comment by nul800sebastiaan** [comment]
Attached is a nightly build of the upcoming 8.1.2 version (no release date yet, I need to talk to some people for more info).

For now, this is the same release as 8.1.1 but with an extra null check to fix the workflow error:
[UmbracoForms.Files.8.1.2-gamma.10106.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3493363/UmbracoForms.Files.8.1.2-gamma.10106.zip)
