### ISSUE TITLE
Ability to reorder workflows

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#15]
First logged as not possible in http://issues.umbraco.org/issue/CON-1247 using Umbraco 7.6.12 and Forms 6.0.6. According to that issue it used to be possible.

It would be useful to reorder workflows, eg by drag and drop (though there should also be an accessible method). We want to do this on every form, because we want to keep the default email workflow but have one before it that makes additional info available for use in the email.

Currently if we want to insert a workflow before an existing workflow we have to delete the existing workflow, add the new one, then re-add the old one remembering all of the details.

**Comment by bergmania** [comment]
Hi, 

Reordering is available in current version (7.0.4).

![image](https://user-images.githubusercontent.com/1561480/48199155-86ece000-e35b-11e8-9bd2-7aa64c9f6d79.png)
