### ISSUE TITLE
Empty date field causes emails not to send.

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco.Forms.Issues#155]
Umbraco Forms 7.1.1

Create a date field that is not mandatory. If form is submitted without this field being completed email work flow errors with:

ERROR Umbraco.Forms.Core.Record - Error parsing record with Razor view
System.FormatException: String was not recognized as a valid DateTime.

I have added a fix to ~/Views/Partials/Forms/Emails/Example-Template.cshtml

Update case statement:

```
case "FieldType.DatePicker.cshtml":
   DateTime dt;
   var dateValid = DateTime.TryParse(field.GetValue().ToString(), out dt);
   var dateStr = dateValid ? dt.ToString("f") : "";
   <p style="margin-top: 0;">@dateStr</p>
   break;
```

**Comment by warrenbuckley** [comment]
All fixed & merged in for V7 & V8 @bergmania

**Comment by nikro412956** [comment]
Hi, i have this same issue on umbraco forms 7.0.7. Is it possible to apply this fix to this version too?
