### ISSUE TITLE
Forms should support a content security policy that disallows 'unsafe-inline' script

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#16]
First logged as http://issues.umbraco.org/issue/CON-1181. Tested with Umbraco 7.6.12 and Forms 6.0.5.

If you add an content security policy HTTP header to an Umbraco Forms site which does not allow inline scripts, Umbraco Forms doesn't work. A minimal example header is (in web.config):

```
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <remove name="Content-Security-Policy" />
        <add name="Content-Security-Policy" value="default-src: 'none'; script-src 'self' https:;" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
```
To get it to work you need to change built-in files to use a nonce wherever the opening tag `<script type="text/javascript">` appears. The nonce is added to the tag and to the Content-Security-Policy header. 

This change is required twice in `~\Views\Partials\Forms\Script.cshtml`. For this we can create a separate copy of it in a theme folder, but this has to be manually reconciled when Forms is updated. It is also required in `~\Views\Partials\Forms\DatePicker.cshtml` , and in this case there is not the option to use a separate copy within the theme folder so the change can be overwritten by an upgrade to Umbraco Forms.

To fix this in the core product the solution would be to alter the scripts to be external dependencies which read server-side data in some other way, eg from data-* attributes. The nonce approach could be used but would be more prone to bugs where the user's existing content security policy needs to be modified.

**Comment by nul800sebastiaan** [comment]
I think this is currently possible, have a look at my comment here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/46#issuecomment-472824269

**Comment by sussexrick** [comment]
@nul800sebastiaan Yes it's possible to work around. My point was that it could be a lot easier if Forms fit in with secure practices by default by using external js files rather than dynamically-generated inline scripts. If you put the dynamic values into data-* attributes it's easy to have an external js file and not break the rule which is recommended for any site using a content security policy.
