### ISSUE TITLE
Bug when editing records with file uploads

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco.Forms.Issues#160]
When loading a form record using `?recordId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`, 
A YSOD appears due to the file upload.

**Comment by warrenbuckley** [comment]
PR for this is here
https://github.com/umbraco/Forms/pull/289

**Comment by warrenbuckley** [comment]
V8 fix was done as part of this PR - https://github.com/umbraco/Forms/pull/288

**Comment by warrenbuckley** [comment]
V7 PR merged in now too - https://github.com/umbraco/Forms/pull/289
