### ISSUE TITLE
FormID

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#163]
We would like to be able to include the FormID in our workflows (specifically when sending emails).  The UnquieId is not user-friendly and we do not want to show this to our customers.

Unfortunately the FormID is not generated until after all of the workflows have executed and the form record is stored.

Would it be possible to generate the FormID on submit, rather than at the end of the workflow execution so that we can include it?  

Forum discussion here: https://our.umbraco.com/forum/umbraco-forms/95837-sending-id-with-email-when-form-is-filled-out

**Comment by bergmania** [comment]
The ID you are referring to is the `RecordId` - Not the `FormId`.

This integer `RecordId` is generated when by the database when inserted and not the codebase it self, like the `UniqueId`.
For performance reasons, we don't want to go to the database to get the Id before we know what to save (Workflows can change values).

### Workaround:
If you add the workflow under "On Approved", the record has the integer `RecordId` when executing the workflows.
![image](https://user-images.githubusercontent.com/1561480/57830331-144d3900-77b2-11e9-90f8-535e0394478b.png)
