### ISSUE TITLE
Hidden Answer Type

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#164]
The Hidden Answer Type is a great feature.

However we would like the default value to post based on responses to previous form question.

If I set Conditions against the Hidden Answer type which are not met, the default value is still posted to the completed form record.

Would it be possible for the default value to only post if the Conditions applied within the Hidden field are met?

Thanks!
:-)

**Comment by bergmania** [comment]
Hi @Ultradata-CXP, this would be a breaking feature.
I suggest you implement you own field type, with this behavior. 

It should be possible by overring the `ProcessSubmittedValue` method and use the `HttpContextBase` to inspect the other values.
