### ISSUE TITLE
Field aliases can exceed column length

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#168]
We had a client that created a form that was erroring on submission.  The error was an SQL error because one of the values being stored was too long for the column and would be truncated.

It turned out this was caused by the aliases of a few fields being excessively long.  What had happened is the client had pasted two paragraphs of text into the enter question field and this generated an enormous alias.

It would be good if when the aliases are generated they are capped to a sensible length to avoid this column overflow.

**Comment by NikRimington** [comment]
This has just caught me out when a client created a form of over 100 fields and multiple pages. They have questions who's aliases are in excess of 300chars causing the same exception above.

**Comment by NikRimington** [comment]
Hack to allow forms to be submitted when this is the case is to increase the column size of the Alias column in the UFRecordFields table

```
  ALTER TABLE [dbo].[UFRecordFields] ALTER COLUMN [Alias] nvarchar(1024)
````

This is very ugly and doesn't actually remove the problem, just increases the length of value that can be stored there.

**Comment by NikRimington** [comment]
More Details: This is on v7 of Forms, not tested if the issue still occurs on v8 of forms, but I'd imagine it probably does.

**Comment by NikRimington** [comment]
**How to reproduce**

1. Install Umbraco
2. Install Umbraco Forms
3. Create a form and add a question with the following as the question text - Let the alias be auto generated:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id diam maecenas ultricies mi eget. Ipsum dolor sit amet consectetur. Condimentum lacinia quis vel eros donec ac odio. Cras ornare arcu dui vivamus arcu felis bibendum ut. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Nulla porttitor massa id neque.

4. Put the form on a page and then try and complete the form

**What will happen**

It should throw a YSOD regarding SQL truncation

**Comment by nikolajlauridsen** [comment]
This has been fixed some time in V8 :D
