### ISSUE TITLE
Paging on form entries not always working

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#174]
I noticed in Umbraco v8.0.1 and Umbraco Forms v8.1.0 that paging on form entries not always work correct and it stays on the current page.

I noticed this console error when this happens.

![image](https://user-images.githubusercontent.com/2919859/59411699-1fe54d00-8dbc-11e9-98a3-6bf2070b1152.png)

For this page e.g. page 1-5 works, but e.g. page 6-10 returns this console error.

**Comment by nul800sebastiaan** [comment]
Pretty weird. Any chance you can set debug=true for a little bit and see if you can find a better error in the console? When debug=false, the real source of the error is quite hidden in DependencyHandler.axd.

**Comment by bjarnef** [comment]
@nul800sebastiaan with debug=true I get this console error.

![image](https://user-images.githubusercontent.com/2919859/59600408-619a2e80-9101-11e9-9e36-c6baf7faeb6d.png)

**Comment by bjarnef** [comment]
For example this view `entries.html` has this without `track by`:
`ng-repeat="row in records.results"`

**Comment by bjarnef** [comment]
You might be able to reproduce it by submitting the form more than once and e.g. use same value for `Name`, `Email`, `Phone`, etc. (maybe even same message submitted).

**Comment by bjarnef** [comment]
Okay, it seems the issue is fixed after upgrading Umbraco to v8.1.1 and Umbraco Forms v8.1.1

Recently these changes have been made to the pagination component.
https://github.com/umbraco/Umbraco-CMS/commit/c12bdaacbf510024183e840735ef6b1e1c9b92db#diff-881302ba8ee7b24e366ab0aa1b71a5b8

https://github.com/umbraco/Umbraco-CMS/commit/977c1d9585fedad69f67213e2a3cea7aec4b499e#diff-da4f6fee13c458cc1b6d879235e20149

I guess it is the latter one that fixed this issue.

**Comment by nul800sebastiaan** [comment]
Happy to hear it works now! 👍
