### ISSUE TITLE
Umbraco Form submission throws "The anti-forgery cookie token" error

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Forms.Issues#175]
When a user submits the form that's inside a RTE editor it returns "The anti-forgery cookie token and form field token do not match" in some browser sessions.

Reproduction
------------
### Bug summary
Umbraco form submission often throws anti-forgery token mismatch error. It looks like the cookie with the __RequestVerificationToken is not created correctly each time. When you check the dev console and storage you can see this one the first time you open the form
![image](https://user-images.githubusercontent.com/42831978/59925875-50bb2700-9439-11e9-9e27-90c0da5bfaa2.png)

While in another browser or incognito it will be empty
![image](https://user-images.githubusercontent.com/42831978/59925896-603a7000-9439-11e9-86ad-b6268bc92e25.png)

### Specifics
Specifics
Umbraco version 8.0.2
Umbraco Forms 8.1.1
Chrome Version 75.0.3770.90 (Official Build) (64-bit)
Firefox 67.0.4 (64-bit)

```

[HttpAntiForgeryException (0x80004005): The required anti-forgery cookie "__RequestVerificationToken" is not present.]
   System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken) +636
   System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext) +119
   Umbraco.Forms.Core.Attributes.ValidateFormsAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext) +181
   System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor) +156
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState) +1082
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +463
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +45
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +73
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +789
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +633
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +99
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +73
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +524
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +1122
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +131

```

### Steps to reproduce
1. Create a Form
2. Set up a Document type with a RTE that allows macro
3. Create a Node with the RTE and pick the form as a macro and publish
4. Go to the form in the Front-end and submit.
5. Open up an incognito window or a different browser. Go to the form and submit.
6. This will result in an error
![image](https://user-images.githubusercontent.com/42831978/59925521-93c8ca80-9438-11e9-8506-e001e0454822.png)

### Expected result
After the form submission, there should be a Thank you message by default.

### Actual result
After the form submission, it throws an error.

**Comment by emmaburstow** [comment]
I'm getting  this error and it's taking out my form around every fortnight. I've actually had to put a recurring to-do list item that reminds me to delete and put my form back in before the client has to get in touch again.

Em

**Comment by emmaburstow** [comment]
Ok i'm having to redo the form daily now. It's getting worse. I'm going to have to re-build the form a different way.

**Comment by 77littleking** [comment]
Same issue. The form provides the cookie once. Will not work on any other browsers or devices until environment is restarted. Will continue working on the browser that received the cookie until cache is cleared, then will not work on that browser until the environment is restarted.

**Comment by beingonlinedave** [comment]
Just to add that I too have experienced this. 
Hosting in Azure in case that's a factor. 
Umbraco version 8.1.0
Forms 8.1.1

**Comment by tyradeveloper** [comment]
We are having the same issue. 
Umbraco version 8.0.2 and Forms 8.1.1

**Comment by nul800sebastiaan** [comment]
Oh my! 🙈  I have just realized what the actual problem is and it turns out it is a macro caching error that affects you if you put the Forms macro in a rich text editor. The good news is that this will be fixed in Umbraco 8.1.4, if you need a workaround for now, I've added a dll to this comment that you can use https://github.com/umbraco/Umbraco-CMS/issues/5987#issuecomment-525691187

Apologies for the long delay on this one, we had no idea what the issue could be here, but now it all makes total sense. 🤦‍♂️

**Comment by beingonlinedave** [comment]
Not a problem. Thanks. Happy to wait for 8.1.4.

Best regards
Dave


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

**Comment by RunnicFusion** [comment]
Hi,

Currently having this issue in Umbraco Forms 8.4.1 running Umbraco 8.5.5.
Anyone else having this too or is it just me?
