### ISSUE TITLE
@using Umbraco.Forms.Mvc.DynamicObjects Umbraco 8

### ISSUE THREAD

**Issue by Geek-5** [umbraco/Umbraco.Forms.Issues#178]
I cannot find the following library:
@using Umbraco.Forms.Mvc

I want to use the class "DynamicObjects" in Umbraco 8, however it is not available. Is there an alternative?

---
_This item has been added to our backlog [AB#2597](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2597)_

**Comment by AmadeuAntunes** [comment]
I got this problem also and I guess that is a bug!

**Comment by Robiwahn23** [comment]
Hi, 
could someone from the Umbraco team make a statement about this problem?

In the meantime I found the interface `IRecordStorage ` to get Forms data. It includes a method `GetAllRecords()`. But this method requires a "`Umbraco.Forms.Core.model.Forms`" instance as parameter. Where can I get such an instance if I am not in the context of a WorkflowType (i am implementing a IComponent)?

**Comment by bergmania** [comment]
Hi..

We plan to add an alternative in next release.
We need to implement a good version that uses the examine index, and not a version like in v7 that uses the database.

**Comment by bergmania** [comment]
Documentation is available here: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Working-With-Data/
