### ISSUE TITLE
Cannot delete a form entry

### ISSUE THREAD

**Issue by khraibani** [umbraco/Umbraco.Forms.Issues#179]
I am trying to delete a form entry, but I get this error. Umbraco v7.6.13 and Umbraco Forms v4.4.6

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
Cannot delete a form entry, once I have deleted i am getting a 500 internal server error
http://localhost:55195/umbraco/backoffice/UmbracoForms/Record/PostExecuteRecordSetAction 500 (Internal Server Error)

### Specifics
I have updated umbraco.modelsbuilder to version 3.0.10
as someone has mentioned in below:
https://our.umbraco.com/forum/umbraco-forms/76904-unable-to-delete-form-entries
I have updated Umbraco form from version 4.3.4 to version 4.4.6
### Steps to reproduce
delete a form entry

**Comment by nul800sebastiaan** [comment]
Hey there @khraibani - I see you're using Umbraco 7.6.13, that version requires you to upgrade your Forms version to version 6, the newest version available is 6.0.7. Make sure to upgrade and try again!
