### ISSUE TITLE
Umbraco 8.1 + Forms enteries list selection not visible anymore

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#183]
Since the Umbraco 8.1 update, there has something changed with how selected row styling works.
In the list views this is updated, but in forms this is not, making it now impossible to see which rows are selected.

Umbraco 8.1 list overview with selected items:
![image](https://user-images.githubusercontent.com/4798968/61033820-81e9a000-a3c4-11e9-9bd9-cf87c118826f.png)

Umbraco 8.1 with Forms entries list with selected items:
![image](https://user-images.githubusercontent.com/4798968/61033751-5f578700-a3c4-11e9-83c2-56ea38cb01c1.png)

---
_This item has been added to our backlog [AB#1685](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1685)_

**Comment by bergmania** [comment]
Thanks for reporting..

Workaround is to add the following in the end of `~/App_Plugins/UmbracoForms/css/umbraco.forms.css`

```
.umb-table-row--selected .umb-table-body__fileicon {
  display: none;
}
.umb-table-row--selected .umb-table-body__checkicon {
  display: inline-block;
}
.umb-table-row--selected::before {
  content: "";
  position: absolute;
  z-index: 1;
  top: 1px;
  left: 1px;
  right: 1px;
  bottom: 1px;
  border: 2px solid#f5c1bc;
  box-shadow: 0 0 2px 0 rgba(245, 193, 188, 0.8);
  pointer-events: none;
}

```

**Comment by bjarnef** [comment]
It would also be great to consider adding `umb-checkmark` component for "Select All" as in content, media  and member listview in list layout using `umb-table`.
https://github.com/umbraco/Umbraco-CMS/blob/417b270f59462ceb9267d4f1454060a2e8904f16/src/Umbraco.Web.UI.Client/src/views/components/umb-table.html#L9
