### ISSUE TITLE
RecordStorage class in V8

### ISSUE THREAD

**Issue by miackers** [umbraco/Umbraco.Forms.Issues#186]
After trying to follow the sample at https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype, I realised that the RecordStorage class is not available. I did a search using object explorer in VS, and only found an interface.

I did the same in V7, and seems to be working.

I need to be able to create a custom workflow with changing some form values - I would like to use it in the email confirmation email sent out.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Classes and methods missing

### Specifics

See summary

### Steps to reproduce

Try create custom workflow using version 8

### Expected result

Should be able to change / add form values as part of the workflow

### Actual result

The classes is missing

**Comment by bergmania** [comment]
Hi @miackers 

Sorry about the wrong doc, we will take a look at that.

You don't need the actual service. You have to use dependency injection in the constructor of the interface. Then Umbraco's IOC container resolves the actual internal `RecordStorage`, and you can use that.

From the top of my head, it should be something similar to this:
```
using System;
using System.Collections.Generic;
using umbraco.BusinessLogic;
using Umbraco.Forms.Core;
using Umbraco.Forms.Core.Enums;
using Umbraco.Forms.Data.Storage;
using Umbraco.Forms.Web.Services;

/// <summary>
/// Summary description for Class1
/// </summary>
public class TestWorkflow : WorkflowType
{
   private IRecordService _recordService;
   private IRecordStorage _recordStorage;
   public TestWorkflow(IRecordService recordService, IRecordStorage recordStorage)
   {
       this.Id = new Guid("ccbeb0d5-adaa-4729-8b4c-4bb439dc0202");
       this.Name = "TestWorkflow";
       this.Description = "This workflow is just for testing";
       this.Icon = "icon-chat-active";
       this.Group = "Services";
       _recordService = recordService;
       _recordStorage = recordStorage;
   }
   public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
   {
       // first we log it
       Log.Add(LogTypes.Debug, -1, "the IP " + record.IP + " has submitted a record");

       // we can then iterate through the fields
       foreach (RecordField rf in record.RecordFields.Values)
       {
           // and we can then do something with the collection of values on each field
           List<object> vals = rf.Values;

           // or just get it as a string
           rf.ValuesAsString();
       }

       // If we altered a field, we can save it using the record storage
       _recordStorage.UpdateRecord(record, e.Form);

       // we then invoke the recordservice which handles all record states // and make the service delete the record.
       _recordService .Delete(record, e.Form);

       return WorkflowExecutionStatus.Completed;
   }

   public override List<Exception> ValidateSettings()
   {
       return new List<Exception>();
   }
}
```

**Comment by miackers** [comment]
Amazing, thanks! (and thanks for responding relatively quickly as well!)

I like the move to force the user to use dependency injection. Good work!

**Comment by miackers** [comment]
Hi @bergmania 

Just an update - that essentially worked. I had an additional problem that the record didn't want to save because of some issue with a date (SQL exception saying the a date was out of range). Noticed the created date on the record object wasn't correct, so added:

`record.Created = DateTime.Now;`

to make it work.

Also - I had a Umbraco startup issue when I had both the RecordService and RecordStorage in the constructor. I realised I didn't need both, and it worked after removing the RecordService (it might have just been some caching etc, but I thought I would mention it)

Since 8.1 is out now, I must mention I am still using 8.0.2, which might impact things a bit. (I will be upgrading to 8.1 later today)
