### ISSUE TITLE
Groups should be reorderable

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#189]
When you reorder your form you can reorder the fields within a group and move them between groups. You can't reorder the groups.

You would expect groups to be reorderable as well.

**Comment by nul800sebastiaan** [comment]
Thanks @ArnoldV - it's a great feature request we'll put on the list for the future!

**Comment by thomasknielsen** [comment]
I just added https://github.com/umbraco/Umbraco.Forms.Issues/issues/341 as it was possible in Umbraco 7 so I thought it was a bug.

You can close the other request if needed.

**Comment by nul800sebastiaan** [comment]
Actually I'll close this one, as it's a bug in v8!
