### ISSUE TITLE
[8.1.1] Unable to prevalue source based on datatype (deploy issue?)

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#190]
steps:

1. Create prevalue source
2. Set type to 'Umbraco Data Type Prevalues"
3. Choose any datatype
4. press save

--> Prevaluesource failed to save

The error is:

{"Message":"An error has occurred.","ExceptionMessage":"Don't know how to map Umbraco.Forms.Core.Interfaces.IFieldPreValueSource to Umbraco.Deploy.Forms.Artifacts.PreValueSourceArtifact." (etc)

Although after refresh of the tree it seems to be created in forms, so it might be deploy only issue.

**Comment by bergmania** [comment]
Hi @ArnoldV 
Thanks for reporting.. I can repro, an I can see it is a deploy issue, so I move the issue to another tracker

**Comment by ArnoldV** [comment]
@bergmania want me to create a new issue on the deploy issue tracker?

**Comment by bergmania** [comment]
@ArnoldV no that is not necessary :)

**Comment by bergmania** [comment]
@ArnoldV, FYI I have made a PR that resolves the issue on the Deploy tracker (private).

**Comment by bergmania** [comment]
Related to  https://github.com/umbraco/Umbraco-Deploy/issues/375
