### ISSUE TITLE
7.1.1 Allow editing of PreValues

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#193]
It would be good to be able to edit Prevalues once you've added them to a question, rather than having to add new values and then deleting the old ones.

**Comment by nul800sebastiaan** [comment]
Hey there @richarth,

Unfortunately we're currently not planning to build this as a feauture. 

However, we like the suggestion. This one is going on our ideas list for new features to implement in the future. Please [keep an eye on our roadmap](https://umbraco.com/products/roadmap/), it will give you an idea of where our software products are going.

Thanks, Sebastiaan on behalf of Umbraco HQ.

**Comment by FransdeJong** [comment]
I'd like to bring this issue back to the attention. It's kinda a pain that a editor needs to delete a answer when he made a typo. That's not (user-) friendly.

**Comment by TimGeyssens** [comment]
Yup would be a nice one to have on the new feature list.... (if bug fixing is done)

**Comment by warrenbuckley** [comment]
This is due for upcoming 8.6.2 release
