### ISSUE TITLE
Selected form entries are not highlighted

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#196]
In Umbraco v8.1.1 and Umbraco Forms v8.1.1 the form entries doesn't seem to be highlighted when any of these are selected.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Form entries doesn't seem to be highlighted, when any of these are selected.

![image](https://user-images.githubusercontent.com/2919859/62189558-8e339e00-b36f-11e9-8acf-be3141ec38aa.png)

### Specifics

Umbraco v8.1.1
Umbraco Forms v8.1.1

### Steps to reproduce

Select any number of form entries under a form in the Umbraco forms section. The selected entries doesn't seem to be highlighted.

### Expected result

The form entires should be highlighted and consistent with selection of entries in listview in content, media and member section.

### Actual result

Selecting form entries show the selected number of form entries, but doesn't highlight these.
Previous it looked like this: https://github.com/umbraco/Umbraco.Forms.Issues/issues/136

**Comment by bjarnef** [comment]
The form entries (rows) does get the class `umb-table-row--selected` but it hasn't any style for this class in Umbraco v8.1.1.

![image](https://user-images.githubusercontent.com/2919859/62190006-a2c46600-b370-11e9-8bf0-e66209ee90ce.png)

**Comment by bjarnef** [comment]
It seems the class name was changed in this commit https://github.com/umbraco/Umbraco-CMS/commit/bd8f950ba1e05fb3c98d2792c9a81740e01a2de9#diff-dec8439b90f62c0b86cacd83ea5dee00

So there is no styling in Umbraco core target the class `umb-table-row--selected`, but the class `-selected`  on the element with class `umb-table-row`.

**Comment by ArnoldV** [comment]
Duplicate: https://github.com/umbraco/Umbraco.Forms.Issues/issues/183
