### ISSUE TITLE
Show overlay instead of traditional confirm

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#197]
When deleting a form entry, it shows a traditional javascript confirm popup. Can we replace this with an overlay confirm similar to many other part of the backoffice UI now, e.g. when deleting items in listviews, nested content, language, media etc.

Here is an example of this.
https://github.com/umbraco/Umbraco-CMS/pull/5487

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - this is going on the ideas list for a future update of the design.

**Comment by nikolajlauridsen** [comment]
Just merged a PR implementing this, should be in next release

**Comment by bjarnef** [comment]
@nikolajlauridsen great :)
There are some generel UI issues in Umbraco Forms which isn't consistent with latest changes in core, e.g. form picker, create dialog and others.
