### ISSUE TITLE
Option to copy form fields

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#202]
In Contour there used to be an option to copy form fields.  Is this something you would consider adding to Umbraco Forms?

**Comment by nul800sebastiaan** [comment]
Hey there,

Unfortunately we're currently not planning to build this as a feauture. 

However, we like the suggestion. This one is going on our ideas list for new features to implement in the future. Please [keep an eye on our roadmap](https://umbraco.com/products/roadmap/), it will give you an idea of where our software products are going.

Thanks, Sebastiaan on behalf of Umbraco HQ.

**Comment by warrenbuckley** [comment]
Fixed in PR https://github.com/umbraco/Forms/pull/442
Due for release in 8.7.0
