### ISSUE TITLE
Option to ignore empty fields

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#204]
We have a client that would like the email notification of a form submission not to include a question if the user didn't give an answer to the question.  In short they only want to see filled in fields.  Is that something you would consider adding?

**Comment by nul800sebastiaan** [comment]
Hi @richarth - I believe that would be something that you can build into your own custom email templates, some documentation about that is here: 

https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Email-Templates/

I would imagine some update like: `if(string.IsNullOrWhiteSpace(field.GetValue() == false) { // render value }` could work. So only render the value if it's not empty.
