### ISSUE TITLE
WorkflowExecutionStatus.Failed ignored in Custom Workflow

### ISSUE THREAD

**Issue by bythewiseman** [umbraco/Umbraco.Forms.Issues#205]
I have created a Custom Workflow Type. If there is an error with the submitted data, I return "WorkflowExecutionStatus.Failed;", however the form still posts, the data is still saved to Umbraco Forms, and the thank you message is still displayed.

Reproduction
------------
Create a Custom Workflow Type.
In the override Execute() method have the following lines only:

```
e.Form.InvalidErrorMessage = "This form is invalid.";
return WorkflowExecutionStatus.Failed;
```

Compile code.
Edit your form within Umbraco Forms and select "configure workflow". 
Select the Custom Workflow Type you created.
Save workflow and form.
In whatever method you use within your website, select the form with the custom workflow.
Have form rendered on a webpage.
Submit form.
See form still submit and then return with either the thank you message.
See data saved within your form's entries area.

Expected result
------------
Form should not have submitted.
Data should not have been saved.
Invalid message should appear.

Actual result
------------
Form is submitted.
Data is saved.
Thank you message is displayed.

**Comment by nul800sebastiaan** [comment]
Hey there @bythewiseman - this is a bit of a confusing part of Forms I'm afraid. Workflows ALWAYS fire after a Form has been submitted and successfully saved. The thing I assume you want to do is some sort of custom validation. For that you would need to use a custom `FieldType` overriding the `ValidateField` method, more info here:

https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype

**Comment by bythewiseman** [comment]
In this instance it is not custom validation. I don't want to add an element to my form that will be validated on post back. 

In this instance if the leisure centre has not entered a default email address, the form should fail and inform the user that we cannot submit their request. So the form itself is valid, but I cannot email the details to someone thus the workflow has failed, so I want to set the correct status and inform the user.

So can you tell me or point me in the direction of what the point of setting the workflow status to failed or canceled then if it does not affect anything and all future steps in the workflow are executed anyway?

**Comment by ronaldbarendse** [comment]
Currently the workflows are indeed a 'fire and forget' way of executing some logic after submitting a validated form (before version 7.1.2 and 8.1.2, this is even in a random order: https://github.com/umbraco/Umbraco.Forms.Issues/issues/149).

It would be great if the workflow status is saved (optionally with an exception message, if that's thrown, and date/time/duration), so you can check in the back-office whether the workflow has executed. Adding additional data would be great too: https://github.com/umbraco/Umbraco.Forms.Issues/issues/55.

Maybe even add a setting to specify whether subsequent workflows must be skipped when the current fails **and/or** is cancelled (instead of just executing regardless). The next step would be to be able to chain workflows based on the returned status (e.g. post a message using Slack if sending the mail failed).

**Comment by bythewiseman** [comment]
These are great ideas. And I was probably stumped by it all because they
are called Workflows, but maybe should be called Execution Points
or something along those lines as currently it feels like things should be
all joined up. Sure if I personally add multiple workflows I can manage
that, and even override some of the basic ones that come with Umbraco Forms
(which I may do here) and store the status in Session. And if it fails then
delete the record on the last step of my custom set of workflows. But that
feels like out of the box code that I'm writing.

That said, Umbraco forms out of the box is seriously the best piece of kit
I've used. It might be worth doing it myself.

Thanks all.

**Comment by skartknet** [comment]
I can't see the original question has been answer here. Why is 'WorkflowExecutionStatus.Failed' ignored? What's the difference between sending that and 'WorkflowExecutionStatus.Completed'?
I want to send my submited data to Salesforce but return a failure if for some reason Umbraco cannot send the data. I can't make any validations in the form for that. So what can I do?
