### ISSUE TITLE
The property "Sensitive data" on fields is not accessible from FieldViewModel

### ISSUE THREAD

**Issue by facingdigital** [umbraco/Umbraco.Forms.Issues#211]
Hi,

For the creation of a GDPR compliant web application, we use Umbraco Forms to create content types in which a part of fields must be editable and visible only by members of Sensitive Data groups.

The problem is that the property "sensitive data" cannot be retrieve from FieldViewModel to manage the visibility of the field.

We would like to adapt the view "Form.cshtml" or "fieldtype.xxx.cshtml" to take in consideration this property.

How can we do that with Umbraco Forms 8.1.1 ? 

If it's not possible, I hope that it will be possible with Umbraco Forms 8.1.2 because it's a real problem to be GDPR compliant, the property is there but we cannot use it...

Thank you for your help.

Kind regards

**Comment by nul800sebastiaan** [comment]
I am not sure what you mean, you want to make fields Sensitive on the frontend of your site? 

The Sensitive Field option is ONLY meant to make sure to hide the data from users in the backoffice who are not in the "Sensitive data" user group. Anything you want to do on the front-end of your site is not covered. We are trying to make sure that you don't give access to private data to all of your users in the Umbraco backoffice.

**Comment by facingdigital** [comment]
yes, I understand that "sensitive data" is used to protect data for users from the backend but we would like to use this property to protect field on the front end side also thanks to a custom code on our form theme. We would like to hide sensitive field if the current connected member is not in the sensitive member group.
Inside the view of a fieldtype, we can retrieve additional information as "placeholder, default value, conditions, mandatory, etc..." but the boolean to indicate if the field is set "sensitive"..
