### ISSUE TITLE
Multiple choice question gives 'Unexpected value'

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Forms.Issues#215]
When using a Multiple choice data type it will start giving errors if it's not answered, even if the question is not mandatory. 

![image](https://user-images.githubusercontent.com/42831978/64013540-52335a80-cb20-11e9-8052-8279d89f95fb.png)

If there is a comma in the answer, it will also break.
![image](https://user-images.githubusercontent.com/42831978/64013626-84dd5300-cb20-11e9-8e8c-a22314ca7055.png)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Since the lates update to 7.1.2 there seems to have been some changes to how Forms expects the answers. They have also become mandatory for some reason.

### Specifics
Tested on Umbraco Cloud.
Umbraco 7.14.0
Forms 7.1.2
Google Chrome 
Version 76.0.3809.132 (Official Build) (64-bit)

Not checked in other browsers

### Steps to reproduce
1. Create a form and use the Multiple choice data type. 
2. Add some pre-values. Don't check Field is mandatory.
![image](https://user-images.githubusercontent.com/42831978/64014011-5dd35100-cb21-11e9-932c-32476fc4bb52.png)

3. Save it and try to submit the form
![image](https://user-images.githubusercontent.com/42831978/64013980-52802580-cb21-11e9-9b7d-213b9bee8042.png)
4. Fails unless you pick something

### Expected result
Should not have pick anything, the form should submit.

### Actual result
Can't submit unless I pick and if there is a comma in the pre value then you can't submit.

---
_This item has been added to our backlog [AB#2499](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2499)_

**Comment by HalldorLyngmo** [comment]
Also seeing the same issue on other data types. Such as Dropdown and Single choice. 
![image](https://user-images.githubusercontent.com/42831978/64014553-b8b97800-cb22-11e9-8da4-abfa457c5883.png)

**Comment by jgettrup** [comment]
I'd like to up-vote this issue for attention. Some forms on our site won't submit following the upgrade from v7.1.1 to 7.1.2. Our issue is that if there is a comma in a multiple choice prevalue, then the client-side validation blocks the form from submitting.

![2019-09-02](https://user-images.githubusercontent.com/13960896/64119296-63cf6900-cd91-11e9-8261-03ac9c5da398.png)

**Comment by annatraversrose** [comment]
![Capture](https://user-images.githubusercontent.com/54810872/64122994-03452980-cd9b-11e9-9d4d-22bca45d9f33.PNG)

Please help with this issue. Thank you.

**Comment by frydenholm** [comment]
A rollback to Forms 7.1.1 have temporarily solved our issues.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/301

**Comment by bergmania** [comment]
Hotfix dll's if anyone can't wait for the official release (will be scheduled soon):
- [V7 - UmbracoForms.Files.7.1.2-ci-20190903-001.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3569345/UmbracoForms.Files.7.1.2-ci-20190903-001.zip)
- [V8 - UmbracoForms.Files.8.1.2.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3569409/UmbracoForms.Files.8.1.2.zip)

In practice, only the `bin/Umbraco.Forms.Web.dll` is changed

**Comment by OlePc** [comment]
@bergmania  I just tried the hotfix, and it solved it for radiobuttonlist and checkbuttonlist, but seems like the issue also exist on dropdownlists. Should I create a new issue for this?

**Comment by iuliaionescu** [comment]
Hi,
I had same issue as the ones described above. Changed the dll and that fixed some of my issues but there is still one though the one with the dropdownlist. If no option picked and submit the form I get the error from the screenshot.
![Screenshot_1588](https://user-images.githubusercontent.com/28090656/64188769-abcaba80-ce7b-11e9-8ae7-16eedcfe959e.png)

**Comment by warrenbuckley** [comment]
@bergmania & @nul800sebastiaan it seems like it's this commit that has caused the problem, as its acceptable to not pick/set a value

https://github.com/umbraco/Forms/commit/de0455dd162f58b2ed5ed21d977745fe3403f86f

Will amend the PRs you have done Bjarke to allow an empty string as a valid value

**Comment by iuliaionescu** [comment]
@warrenbuckley thank you for the patch fix. 
It works well ( v8 tested ) 👍

**Comment by OlePc** [comment]
@warrenbuckley Works for v7 also 👍

**Comment by JordinKee** [comment]
We also experienced this bug when Umbraco Cloud updated Umbraco Forms from 7.1.1 to 7.1.2. We fixed it by reverting the update. But, with the update to 7.1.3 yesterday, the issue is back again. This seems strange to me, because the fix of this issue was supposed to be part of 7.1.3.

Perhaps our situation is different, in that translations seem to be a part of it:
![UmbracoForms_unexpectedValue](https://user-images.githubusercontent.com/8670964/64684356-43846600-d485-11e9-96b4-d17efacfbd8b.png)
"#[contactSubject] General" should translate to "Algemeen".

Anyone else experiencing this? Is there another fix possible besides reverting yet again?

**Comment by ronaldbarendse** [comment]
Just like @JordinKee commented, we're seeing the same `Unexpected value: 'Dhr.'. Expected one of these: '#SalutationMr', '#SalutationMrs'` validator error since Forms 7.1.3! The question is configured with translated values, but not mandatory:

![Single choice](https://user-images.githubusercontent.com/1051287/64761822-43e03800-d53d-11e9-962c-882c970ca972.png)

Please make sure these kind of patches are correctly tested and code reviewed, as this isn't the first time a patch completely breaks Forms (and having it automatically updated on Cloud makes that a nightmare, even with all the magic that's behind it 😪)...

**Comment by bergmania** [comment]
Created a new task for the issue when using "magic strings" in the prevalues:

See: #231

**Comment by teeto** [comment]
This still happens in Umbraco Forms 7.2

**Comment by bergmania** [comment]
@teeto, see https://github.com/umbraco/Umbraco.Forms.Issues/issues/237 there is also a hotfix

**Comment by teeto** [comment]
thanks @bergmania i have instead downgrade to 7.1.3 and now it works.
I will wait for the next official version instead of the hotfix

**Comment by tyradeveloper** [comment]
We are using Umbraco forms 7.2.0 and having a similar issue where we have a comma in prevalue under multiple choice and the form stops to submit. the umbraco version is 7.15.3 and we are using cloud. I tried to use the hotfix but it didn't fix the issue.

**Comment by ashkrishan** [comment]
Happened to one of my installs running 7.2. The workaround I have come up with is to use prevalue text files which renders blanks perfectly as before and unexpected validation error is not thrown on optional fields.

**Comment by ProNotion** [comment]
> thanks @bergmania i have instead downgrade to 7.1.3 and now it works.
> I will wait for the next official version instead of the hotfix

Good idea since the hotfix doesn't address the problem either, unfortunately.

**Comment by DavidChristiansen** [comment]
Please reopen this @bergmania as the issue has not been resolved.  Let me know if I can assist in the fix.

**Comment by MichaelNielsenDK** [comment]
This is still an issue on Umbraco Cloud 
- Umbraco 8.6.1
- Umbraco Forms 8.4.1

**Comment by lukehook** [comment]
I too am now experiencing this. Was working fine with Umbraco Forms 8.1.1 but now doesn't seem to be working with 8.4.1 - does anybody have a work around?

**Comment by RunnicFusion** [comment]
Think the issue i'm experiencing is related to this issue as well.


**My setup:**

- [Form A]
Guid: 123a
fieldtype: datepicker
returns validation message _Unexpected value: '2020-09-03'. Expected one of these: '3 januari Happy New Year' (...)_

- [Form B]
Guid: 123a 
fieldtype: dropdown
 uses values like _3 januari Happy New Year_ and so one


So it looks like Form A is showing the validation message of Form B because the share the same GUID? Even when changing the Form A fieldtype to hidden input the error message is returend on js validation and submit.


Using Umbraco Forms 8.4.1 on top of Umbraco 8.5.5 and 8.1.1.

**Comment by markwemekamp** [comment]
I ran into this problem while updating from 7.1.1 to 7.1.3, after the upgrade some checkboxes returned a validation error with the Unexpected value message.

I got the forms working again by manually emptying the prevalue arrays for the checkbox fields in the form .json files

**Comment by Andrei-** [comment]
Is this fixed? I just hit this problem in Umbraco.forms 8.4.2

**Comment by RunnicFusion** [comment]
Any updates on this? Still expecting validation issues when using magicstrings.
Currently single choise list is displaying correct value but validation is using the placeholder's to validate on.

- Running Umbraco Forms 8.4.4 and Umbraco 8.5.5

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/11329216/73da1cf7-6853-4850-b1eb-77aa021a7b93)

**Comment by AndyButland** [comment]
I've tried to replicate this on the latest version of Forms 8, and don't see a problem, so it does look like this was resolved at some point - but possibly later than the version you are currently using.

**Comment by enkelmedia** [comment]
Just ended up here again =D This time I think I understand what happened. I think it might be related to forms that have been copied. We are on a old versions so can't really check if it has been fixed in later versions.

Creating a new form from "scratch" solved the problem for me.
