### ISSUE TITLE
Overriding default field types not possible anymore in V8

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#216]
For some reason, since Umbraco Forms 8.0.0 all default field types (in the namespace `Umbraco.Forms.Core.Providers.FieldTypes`) are now `sealed` and can't be inherited/overridden anymore: https://our.umbraco.com/documentation/add-ons/umbracoforms/Developer/Extending/Adding-a-Type#overriding-default-providers-in-umbraco-forms.

This makes it quite cumbersome to just add a single setting to an existing field type, as you need to inherit from `Umbraco.Forms.Core.FieldType` and duplicate the existing code (keeping the same ID) to replace/extend a default field type.

**Comment by ronaldbarendse** [comment]
Also, when you add a custom field type with the same ID, both the built-in and custom one will show up in the 'Choose answer type' dialog. After selecting one, the correct settings for that field type are shown, but after saving the form, it will load the settings from the first field type.

**Comment by nul800sebastiaan** [comment]
Interesting, might be an oversight or a deliberate choice, but if it's deliberate we shouldn't allow items to have the same ID. I'll have to ask the team and get back to you.

**Comment by ronaldbarendse** [comment]
The possibility for having duplicate IDs seems to be caused by switching the `ProviderCollection<FieldType>` (based on GUIDs) to the `FieldCollectionBuilder` (based on types).

So to fix this, the collection builder should filter types that have the same ID and probably remove the inherited type (so the deepest type of the inheritance hierarchy is used).

For now, duplicating and removing the built-in field type seems to work:
```c#
public class FormsComposer : IUserComposer
{
   public void Compose(Composition composition)
   {
      composition.WithCollectionBuilder<FieldCollectionBuilder>().Exclude<Textfield>();
   }
}
```

**Comment by bergmania** [comment]
Unsealed the following FieldTypes:
- CheckBox
- CheckBoxList
- DataConsent
- FileUpload
- HiddenField
- Password
- RadioButtonList
- Recaptcha2
- Text
- Textarea
- Textfield

**Comment by ronaldbarendse** [comment]
@bergmania Also make sure inherited field types (with same IDs) are correctly resolved, so the example in the linked documentation works as intended!

So the `FieldCollectionBuilder` should group the field types by ID and only keep the inherited type (e.g. deepest in the inheritence chain). It's probably also best to throw an exception if it still contains duplicate IDs (with a message it couldn't automatically figure it out and you should manually remove one of the types), as you otherwise get this issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/216#issuecomment-527885554.

**Comment by bergmania** [comment]
@ronaldbarendse this is also fixed now.
Would you be interested in an nightly build such that you can test it works as expected.

**Comment by ronaldbarendse** [comment]
@bergmania If you can supply the nightly build, I'll try to test it before it's released next Tuesday 👍

**Comment by bergmania** [comment]
@ronaldbarendse 
The RC is here:
[UmbracoForms.Files.8.2.0.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3658911/UmbracoForms.Files.8.2.0.zip)

**Comment by ronaldbarendse** [comment]
@bergmania I just tested the RC: inheriting is now possible again and built-in field types get replaced if the ID is the same:

```c#
public class Textfield : Umbraco.Forms.Core.Providers.FieldTypes.Textfield
{
    public Textfield()
    {
        this.Name = "Short answer (custom)";
    }
}
```

Inheriting and changing the ID also works as expected, so creating a new field type based on a built-in one also works now 👍
