### ISSUE TITLE
Clean up field type prevalues UI

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#218]
The prevalues within a field type configuration contains some UI glitches:

![Prevalues](https://user-images.githubusercontent.com/1051287/64261095-4256b480-cf2c-11e9-81f6-668ba2690a63.png)

- Hovering the trash-can shows an underline
- Removing shows a plain/browser confirmation dialog
- The add button isn't aligned with the text input
- The prevalue source select is shown after the title, instead of below
- The prevalue source initially contains an empty option (and could probably just be hidden if no sources are available)

---
_This item has been added to our backlog [AB#5505](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5505)_

**Comment by ronaldbarendse** [comment]
The confirmation could be updated as part of https://github.com/umbraco/Umbraco.Forms.Issues/issues/197.

**Comment by nikolajlauridsen** [comment]
These has been fixed, and should be in the next release 👍
