### ISSUE TITLE
Clean up form picker UI

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#219]
The form picker contains some UI glitches:

![Form picker](https://user-images.githubusercontent.com/1051287/64262019-c2314e80-cf2d-11e9-8c4f-5c26a863d7ed.png)

- Spacing of the filter and forms
- Hovering the form shows an underline (and no other visible change, see screenshot)
- No message is displayed when no forms are found (using the filter)

**Comment by enkelmedia** [comment]
I do see that this issue is not a very prioritized one, but I was actually embarrassed about this when teaching our client about Umbraco Forms today - please add this 20 mins fix to the backlog for next sprint =D

**Comment by nul800sebastiaan** [comment]
:-) We'll work at some backoffice UX updates at some point, we're bundling them together to make it easier to focus on similar thing together.

Not sure when that is yet, first we're trying to fix actual bugs.

**Comment by enkelmedia** [comment]
Thank you for getting back so fast @nul800sebastiaan =D 

Mean while I'll share my "backoffice css/less" hack if someone want's to use it

```
div[ng-controller="UmbracoForms.FormPickerOverlayController as vm"] {
    
    ul.umb-actions {
        margin-top:10px;
        li {
            a {
                display: flex;
                padding: 8px 2px;
                border-bottom: 1px solid #e6e6e6;

                &:hover {
                    background: #f9f7f5;
                    color: #2152a3;
                    text-decoration: none;

                    span {
                        color: #2152a3;
                    }
                }
            }
        }
    }
}
```
