### ISSUE TITLE
"Umbraco Docs from xpath" Prevalue options not automatically updated when node names are changed.

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#221]
### Bug summary

Prevalue sources created using "Umbraco Docs from xpath" then added as a radio button list or whatever to a form will display all the nodes names, as expected. However, if you then change a node name, that change is NOT reflected in the Umbraco Form when rendered on the site UNTIL you manually go into the Form editor and Re-save the form. 

### Specifics

Umbraco version: 7.14.0
Umbraco Forms version : 7.1.2
Site running on Umbraco Cloud

### Steps to reproduce

1. Create a new prevalue source of type "Umbraco Docs from xpath". Point it to a valid collection of nodes.
2. Create a Form, add a Question of type "Single choice" or "multiple choice"  utilizing the new prevalue source.
3. You should see a representation of all the node names in a list in the form editor.
4. Save the form.
5. Put it on a page, view the page (you will see all the nodes listed as options), submit the form.
6. If you check the form Entry, you should see the node name(s) you selected stored as text.
7. In the Content tree, rename one or more of the nodes which are used for the prevalues. 
8. View the form page again - **the option names have NOT changed.**
 If you then go to the Form editor view via the back-office and re-save the form, THEN view the form page again - now the options have been updated to match the current node names.

### Expected result

I would expect that changing a node name in the Content section would be the only thing required to update the list of options on a form. Having to KNOW that you need to now Re-save the Form is obscure and not editor-friendly.

**Comment by nul800sebastiaan** [comment]
That sounds like a caching issues. Please note that we'll never change the values that you have already saved from other form submissions.

But yes, this is a bug and needs to be fixed! 👍

**Comment by hfloyd** [comment]
Yes, I wouldn't expect existing form submissions to get changed, but would expect the current form to be up-to-date :-)

**Comment by warrenbuckley** [comment]
Additional repro from a support request:

* Create content type with nested content with 2 textstring properties: name and mail.
* Then create a new custom prevalue source, see attachment for the code. In short this prevalue source reads a content object from step 1 and tries getting the values added to the nested content.
* The final step is creating a new Umbraco form with a default dropdown fieldtype with the custom prevalue source attached.

```csharp
public class MailadressesPreValueSource : FieldPreValueSourceType
{
    [Setting("Contact page", alias="contactPage", description = "Select an contact page that contains a nested content with category/mail pairs", view="pickers.content")]
    public string ContactPage { get; set; }

    public MailadressesPreValueSource()
    {
        Id = new Guid("e0fbe98f-add5-46cc-ab3d-aacadc81c25b");
        Name = "Mail adresses";
        Description = "Mail adresses groups by category";
    }

    public override List<PreValue> GetPreValues(Field field, Form form)
    {
        var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);

        if (!string.IsNullOrEmpty(ContactPage))
        {
            var contactPage = umbracoHelper.TypedContent(ContactPage);
            if (contactPage != null && contactPage.HasValue("categories"))
            {
                var categories = contactPage.GetPropertyValue<IEnumerable<IPublishedContent>>("categories");

                return categories.Select(x => new PreValue()
                {
                    Id = x.GetKey(),
                    Value = x.GetPropertyValue<string>("name")
                }).ToList();
            }
        }

        return new List<PreValue>();
    }

    public override List<Exception> ValidateSettings()
    {
        var excp = new List<Exception>();

        return excp;
    }
}
```

**Comment by bergmania** [comment]
Hey @hfloyd..

This is a caching issue we really can't resolve in a good way, without making performance bad for everyone, because we don't have an easy way to know that you have a prevalue source that could change the content.

I suggest you use the following workaround:
-  Implement a simple ApplicationEventHandler that clears the cache of all Prevalues.
```
using System.Collections.Generic;
using System.Linq;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Forms.Core.Cache;

namespace Whatever
{
    public class WhateverEventHandler : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication,
            ApplicationContext applicationContext)
        {
            ContentService.Trashed += (sender, args) => ClearCache(args.MoveInfoCollection.Select(x => x.Entity));
            ContentService.Moved += (sender, args) => ClearCache(args.MoveInfoCollection.Select(x => x.Entity));
            ContentService.Published += (sender, args) => ClearCache(args.PublishedEntities);
            ContentService.UnPublished += (sender, args) => ClearCache(args.PublishedEntities);
        }

        private void ClearCache(IEnumerable<IContent> items)
        {
            ApplicationContext.Current.ApplicationCache.RuntimeCache.ClearCacheByKeySearch(CacheKeys.PreValuePrefix);
        }
    }
}
```

You can optimize the ´ClearCache´ method based on the xpaths you use. But this should resolve your issue.

**Comment by bergmania** [comment]
@hfloyd, I think that would work, but be aware that you don't get the new prevalue options if they occur on the list returned by the xpath.
