### ISSUE TITLE
DropDown FieldType Items - Separate Value and Description fields

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Forms.Issues#222]
Currently items in DropDownList FieldTypes can only be defined with a single value, which means that dropdown select options are rendered with both the value and inner-html being the same. 

You either have a terse description to achieve a short value, to a long value to achieve a meaningful description. This is awkward for many applications, particularly if you want to use the option value as a 'magic string' but provide a meaningful description for the user.

Prior to 7.1.2 it was possible to deal with this limitation by using delimited item values and a Themed FieldType.DropDownList partial-view, to parse and separate values and descriptions for the rendered select option html.

Since 7.1.2 it appears that a change has been implemented that breaks this approach, and requires that the selected option value for dropdown on a submitted form, match one of the item values in its DropDownList FieldType definition (presumably a client-server match-check for validity) and it seems that the submitted form is now silently discarded at the host if it fails to find a match.

I've been able to code around this problem for the time being by using dictionary values for item descriptions, and some look-up code in the Themed FieldType.DropDownList partial-view, to add custom inner-html descriptions for each select option... clunky and fragile, but it works for now.

However, this is obviously not CMS-Admin friendly, and can be easily broken by them, so a better alternative would be to solve it at the source, by allowing both value and description to be defined when adding items to a DropDownList FieldType in the Umbraco-Forms manager, so that each has its own option property to access when assembling the html in the FieldType.DropDownList partial-view.

**Comment by nul800sebastiaan** [comment]
Hey there @c9mbundy - it looks like you found a way around this. If you need more flexibility than this, we would recommend you build a custom fieldtype to support your specific needs. :-)

https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype
