### ISSUE TITLE
bug in FieldType.DatePicker.cshtml

### ISSUE THREAD

**Issue by DannyHile** [umbraco/Umbraco.Forms.Issues#225]
I just found a bug in FieldType.DatePicker.cshtml
this line:
if (Model.ValueAsObject != null && Equals(Model.ValueAsObject, string.Empty))
should be:
if (Model.ValueAsObject != null && !Equals(Model.ValueAsObject, string.Empty))

or else the date is "forgotten" :-)

**Comment by nul800sebastiaan** [comment]
Thanks, we're working on it, this is a duplicate of https://github.com/umbraco/Umbraco.Forms.Issues/issues/214
