### ISSUE TITLE
Extending validation types

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco.Forms.Issues#226]
Hey Umbraco Forms team,

I have a (I think small) feature request for Umbraco Forms. We want to extend the validationtypes with more defined ones. I know we can have a custom one, but we would like to add our own validation types to this aswell. 
I know I can add my own validationtype in the frontend like this:
```
vm.validationTypes = [{
                "name": labels[0],
                "key": "email",
                "pattern": "[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+",
                "enableEditing": true
            }, {
                "name": labels[1],
                "key": "number",
                "pattern": "^[0-9]*$",
                "enableEditing": true
            }, {
                "name": labels[2],
                "key": "url",
                "pattern": "https?\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}",
                "enableEditing": true
            }, {
                "name": labels[3],
                "key": "custom",
                "pattern": "",
                "enableEditing": true
            }, {
                "name": "test",
                "key": "thevalley",
                "pattern": "url",
                "enableEditing": true
            }];
```

But this will break when the file updates. Can you guys add a way to extend on this? To me it seems like I need a way to add to the array without editing the umbraco.forms.js.

**Comment by AndyButland** [comment]
We had this one reported again under issue [#936](https://github.com/umbraco/Umbraco.Forms.Issues/issues/936) and have implemented the feature to include in the next releases of Forms 10+.

As such I'll close this one as a duplicate.
