### ISSUE TITLE
File Uploaded is not saved when UmbracoFormsController.FormPrePopulate event is implemented

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#229]
Issue Description:
We have implemented the Umbraco.Forms.Web.Controllers.UmbracoFormsController.FormPrePopulate event.
When using a File Upload answer type on a form, the uploaded file is not saved when the form submitted

Tested on:
Our current enviroment - Umbraco CMS 7.12.3 and Umbraco Forms 7.0.4
Testing environment - Umbraco CMS 7.15.0 and Umbraco Forms 7.1.1

Reproduction
------------
1. Implement Umbraco.Forms.Web.Controllers.UmbracoFormsController.FormPrePopulate event and include the dll into the bin directory.
2. Create a form with File Upload answer type.
3. Load the new form and upload a file
4. Summit the form, and the uploaded file is not saved.

### Expected result
The uploaded file should be saved

---
_This item has been added to our backlog [AB#12547](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12547)_

**Comment by nul800sebastiaan** [comment]
Duplicates https://github.com/umbraco/Umbraco.Forms.Issues/issues/177

**Comment by ronaldbarendse** [comment]
Although this issue duplicates #177, we'll try to back-port the fix to v7 and track process on this issue 👍🏻

**Comment by AndyButland** [comment]
Backport of this fix is completed and will be in the next patch release.
