### ISSUE TITLE
Form is not processed after submitting

### ISSUE THREAD

**Issue by simoneldevig** [umbraco/Umbraco.Forms.Issues#230]
### A brief description of the issue goes here.
When submitting a form it actually submits the form but nothing happens after it reloads the page. Data is not saved in Umbraco an no workflows are hit.

Reproduction
------------

### Bug summary

We are running a Umbraco Forms 8.1.3 on a 8.1.4 Umbraco and have some issues with submitting a form. When submitting the form it sends of the data and then just reloads the form with the same content. There is not saved anything to the form entries and the workflows are not executed. We don't get any errors and nothing in the log either.

Here is a screenshot of the form after submission with the data that is sent:
![image](https://user-images.githubusercontent.com/6176830/65022910-1840c180-d932-11e9-909b-fd66d1ce6fe9.png)

### Steps to reproduce

Try running a installing and submit a form with the following installed.
- Umbraco 8.1.4
- Umbraco Forms 8.1.3
- [Umbraco-Forms-Bootstrap-4-Theme](https://github.com/marceldigital/Umbraco-Forms-Bootstrap-4-Theme) - We are using the Vertical theme in the example

**Comment by nul800sebastiaan** [comment]
That sounds like a problem in your project, this basic usage of Forms works for everyone else.

Have you prepared your frontend as described? https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/

Maybe some custom code that's getting in the way?

**Comment by simoneldevig** [comment]
Yes, everything is set up and there is no custom code, but maybe it has something to do with the Bootstrap 4 theme. I will try and set up at clean installation with only Forms installed. 

Is there a way to debug what happens after the submission since I Can't debug the compiled DLL's?

**Comment by simoneldevig** [comment]
@nul800sebastiaan - just found out that the problem was due to the use of a pickup directory instead of a real SMTP. Switching to SMTP made everything work correct.

Closing issue :-)
