### ISSUE TITLE
Multiple choice question gives 'Unexpected value' when using magic strings

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco.Forms.Issues#231]
Relates to https://github.com/umbraco/Umbraco.Forms.Issues/issues/215

This bug is about the comments from here https://github.com/umbraco/Umbraco.Forms.Issues/issues/215#issuecomment-530296503

This issue is because the placeholders is not parsed in the prevalues before validation

---
_This item has been added to our backlog [AB#2833](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2833)_

**Comment by bergmania** [comment]
PR: 
- V7: https://github.com/umbraco/Forms/pull/309
- V8: https://github.com/umbraco/Forms/pull/307

**Comment by warrenbuckley** [comment]
Merged in V7 & V8 PRs above

**Comment by perplexroy** [comment]
Hi! Still expecting validation issues when using magicstrings right now.
Currently single choise list is displaying correct value but validation is using the placeholder's to validate on.

Running Umbraco Forms 8.4.4 and Umbraco 8.5.5
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/140381982/144ea5c1-edb0-419e-860c-9532766d2f26)
