### ISSUE TITLE
Unable to edit fields with custom workflows attached

### ISSUE THREAD

**Issue by Alkaersig** [umbraco/Umbraco.Forms.Issues#232]
This could be the same error as https://github.com/umbraco/Umbraco.Forms.Issues/issues/2, but since that is more than a year old and no action has been taken i will report our problem in a separate bug as it is causing our customers a lot of problems.

We have developed a lot of custom workflows that integrate to external services like MailChimp and fetches data that we use to populate the Settings property with prevalues. 

When one of these workflows are added to a form a script error is thrown (in the backend) and you are unable to edit the form. With a bit of luck and a lot of page refreshes you can sometimes make the form load correctly.

The issue seems to be caused by the loading of external data that might delay the loading of the workflow, even though this is very fast as in a few 100 ms.

This is an example of the overriden Settings property for our MailChimp workflow, that will cause the error to happen. The workflow works as expected and the prevalues are loaded fine into the workflow, it just breaks the form editing abilities:

```
    public override Dictionary<string, Setting> Settings()
    {
      var settings = base.Settings();
      
      if(!string.IsNullOrEmpty(Constants.APIs.MailChimp.ApiKey))
      {
        IMailChimpManager manager = new MailChimpManager(Constants.APIs.MailChimp.ApiKey);
        var lists = manager.Lists.GetAllAsync().Result;
        settings["Lists"].prevalues = string.Join(",", lists.Select(d => d.Name));
      }

      return settings;
    }
```

And this is the error thrown in the backend as a result:
![image](https://user-images.githubusercontent.com/12032054/65578330-e359ed80-df75-11e9-8682-9ca0d8dffcef.png)

---
_This item has been added to our backlog [AB#2986](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2986)_

**Comment by nul800sebastiaan** [comment]
Thanks @Alkaersig - we'll give it a look and let you know!

**Comment by joevandebilt** [comment]
We had similar, if not the same, problem in house (and same as #2). We found that in the umbraco.forms.js file - the following function 

```
//we are editing so get the content item from the server
formResource.getWithWorkflowsByGuid($routeParams.id)
	.then(function (response) {
            editorState.set($scope.form);
	}
```
was completing _after_ the functions in the child controller. 

```
formResource.getPrevalueSources().then(function (resp) {
	vm.prevaluesources = resp.data;
	formResource.getAllFieldTypesWithSettings().then(function (resp) {
		vm.fieldtypes = resp.data;
		vm.ready = true;
	});
});
```

Our forms and workflows we're not particularly big or complex, but took around 400ms to return (possibly due to the storage device) 

The order of these functions completing seems to be the cause of this issue. We've added our own workaround to ensure these execute in the right order - but thought I'd add let you know what we found while debugging to help with a more permanent official fix.

**Comment by Alkaersig** [comment]
Thanks for the detailed feedback @joevandebilt, it will probably allow for us to make a temporary workaround as well for a better user experience for our customers!

**Comment by bergmania** [comment]
@Alkaersig: 
I have also looked into this one. From my findings it should be enough to update the `ng-if` in `\App_Plugins\UmbracoForms\Backoffice\Form\views\design\design.html` from 
```
 ng-if="vm.ready && vm.security"
```
to
```
 ng-if="vm.ready && vm.security && model"
```

Can you confirm this fix?

**Comment by Alkaersig** [comment]
@bergmania 
I have tested it on 3 different customer sites that have the issue and it resolved it on all 3. So it seems to be a fix.

**Comment by bergmania** [comment]
Thank you so much for testing - I will add the fix for the next releases
