### ISSUE TITLE
Issue saving umbraco document, forms workflow 

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco.Forms.Issues#234]
There is a form with a dropdown, the content in the dropdown is set from prevalues. Those prevalues are based on a document type which has a content picker.
The workflow from the form creates a content node when saving. When that gets saved and stored in backoffice, you get an error - because of the content picker.

Step by step to reproduce

Here's the form with the workflows.
![image](https://user-images.githubusercontent.com/54025229/65663254-8e31e080-e036-11e9-875e-79ee7a5b48b5.png)

The prevalues are created from this generic document type
![image](https://user-images.githubusercontent.com/54025229/65663940-6ba0c700-e038-11e9-8df7-c9f85ae293b8.png)

The workflow is based of a document type:
![image](https://user-images.githubusercontent.com/54025229/65663671-c4239480-e037-11e9-9342-3b71ccfe2541.png)

Which looks like this:
![image](https://user-images.githubusercontent.com/54025229/65663704-d4d40a80-e037-11e9-92b2-95ba7d1e0c04.png)

The content picker in the document type looks like this:
![image](https://user-images.githubusercontent.com/54025229/65663781-14025b80-e038-11e9-91fc-c13d570bb336.png)

When it's all setup, and you fill out the form on front-end, you get this error when you log into backoffice.

![image](https://user-images.githubusercontent.com/54025229/65664119-e79b0f00-e038-11e9-8840-fe11ad2c9426.png)

`An error occured
Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController

Exception Details
System.InvalidOperationException: Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController
Stacktrace
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at Umbraco.Web.Editors.ParameterSwapControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()`

### Bug summary

The api call in the backend, to get data stored in the picker fails due to wrong type of data stored on the property.

### Specifics

Where applicable:
* What version are you using
Umbraco 7.14.0
Forms 7.1.3
* What browser and version you are using
Chrome
    * Please mention if you've checked it in other browsers as well
I have not

### Steps to reproduce

Already posted.

### Expected result

    * What did you _expect_ that would happen on your site?
Being able to pick some content in the content picker without - but instead get immediate error.
after closing the error you can pick content, but it wont saved the content you picked.
    * Describe the intended/desired outcome after you did the steps mentioned.
Being able to pick content in the created content node and save it.

### Actual result

![image](https://user-images.githubusercontent.com/54025229/65664119-e79b0f00-e038-11e9-8840-fe11ad2c9426.png)

`An error occured
Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController

Exception Details
System.InvalidOperationException: Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController
Stacktrace
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at Umbraco.Web.Editors.ParameterSwapControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()`

**Comment by nul800sebastiaan** [comment]
This is the same problem as https://github.com/umbraco/Umbraco.Forms.Issues/issues/156

There's more info in https://github.com/umbraco/Umbraco.Forms.Issues/issues/162 with the advise not to use a content picker (I think that's the conclusion, not sure?).
