### ISSUE TITLE
Implement option to search for forms

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#236]
At the moment when using backoffice search in Umbraco v8 it search for e.g. ontent, media, document types, data types, templates, but not forms.

It would be great to be able to find forms via backoffice search as well (and maybe by guid as well).
For example a search on "contact" would return form with name "contact form", "contact us", etc.

Shannon suggest Umbraco Forms should implement `ISearchableTree` to make this possible.
https://github.com/umbraco/Umbraco-CMS/pull/4829#issuecomment-537467662

---
_This item has been added to our backlog [AB#3197](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3197)_

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco.Forms.Issues/issues/236
