### ISSUE TITLE
Umbraco Forms 7.2.0 - forms with conditions not 'sending'

### ISSUE THREAD

**Issue by OMPensionSolutions** [umbraco/Umbraco.Forms.Issues#238]
I have Umbraco 7.15.3 and just updated to Forms 7.2.0 this week.  A few weeks prior to the update being deployed all forms on my website that had conditions applied to questions/answers stopped 'sending' with the page on the website simply refreshing and the contents of the form not being sent to my recipient email inbox.  I was told that I needed to update my version of Umbraco and then update to forms 7.2.0.  This has been done however the issue with forms that have conditions is still happening. I also have forms on my site which do not have conditions applied and they work fine with the contents being sent to my email inbox and the 'sent message' showing on the web page once the Submit button has been selected on the web page.

**Comment by nul800sebastiaan** [comment]
Hi @OMPensionSolutions - is this the same issue as https://github.com/umbraco/Umbraco.Forms.Issues/issues/239?

**Comment by OMPensionSolutions** [comment]
Hi

Yes looks like the same issue!

**Comment by OMPensionSolutions** [comment]
Hi,

Do you know when this issue will be fixed?

Thanks

Shaun Barton

From: Shaun Barton
Sent: 15 October 2019 09:17
To: umbraco/Umbraco.Forms.Issues <reply@reply.github.com>; umbraco/Umbraco.Forms.Issues <Umbraco.Forms.Issues@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [umbraco/Umbraco.Forms.Issues] Umbraco Forms 7.2.0 - forms with conditions not 'sending' (#238)

Hi

Yes looks like the same issue!

**Comment by nul800sebastiaan** [comment]
We believe the problem may be that your rendering the form with `ExcludeScripts="0"`, as detailed in this comment: https://github.com/umbraco/Umbraco.Forms.Issues/issues/239#issuecomment-541520796

Is that the case for you as well? In order for conditions to work. you're required to not exclude the scripts.

**Comment by OMPensionSolutions** [comment]
Hi

I very much doubt that we have set ExcludeScripts=”0” as the forms worked with conditions for months before it stopped working – and during that time we have not changed any aspects of our site or scripts

**Comment by Alkaersig** [comment]
@OMPensionSolutions if you have any of the fieldtypes Dropdown or xxx Choice hidden behind a condition, there's a bug in 7.2.0 where validation fails if no value is selected for these. So Forms fail validation for these fields, the validation error is just not visible since the fields are hidden behind a condition.

https://github.com/umbraco/Umbraco.Forms.Issues/issues/250

**Comment by OMPensionSolutions** [comment]
Thanks for that!  What is the solution - will a fix be deployed by Umbraco?

**Comment by Alkaersig** [comment]
There's a hotfix available in this issue:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/237

 It's also fixed in 7.3.0 whenever it is released.

**Comment by nul800sebastiaan** [comment]
I'll close this as fixed in 7.3.0.
