### ISSUE TITLE
Umbraco forms conditions not working

### ISSUE THREAD

**Issue by natashadecanha** [umbraco/Umbraco.Forms.Issues#24]
Reproduction
------------
### Bug summary
When adding conditions to a field in umbraco forms the field will be hidden, but never shows when triggerd.

Specifics
I just pulled the latest Umbraco version 7.12.2 with Umbraco Forms: "7.0.4" to see if the bug exists (yes it does)
Clean install - I made no changes to the code at all
Umbraco version 7.12.2
Umbraco Forms 7.0.4

Steps to reproduce

1. In the Umbraco contact form I added a new property "Do you have a phone?" with single choice answers "yes" and "no".

2. In the existing phone numer property I enabled the conditons and added the following:
![45484883-fa0c1880-b755-11e8-8985-9859703f49d9](https://user-images.githubusercontent.com/40452146/45692697-b94c3f00-bb5b-11e8-8adc-1eb43447f1d9.png)

3. Submit and save

4. Result:
![45484920-1314c980-b756-11e8-8c6b-8ea2b988c845](https://user-images.githubusercontent.com/40452146/45692894-28299800-bb5c-11e8-8129-129bbfa0c229.png)

5. In the front-end:
![45484975-3ccdf080-b756-11e8-8d79-033c93c69c19](https://user-images.githubusercontent.com/40452146/45692768-e00a7580-bb5b-11e8-9881-b54ac8761f6e.png)

6. Phonenumber is hidden as expected

7. Check yes to the querstion "Do you have a phone?"

8. Phone number texbox does not show up
![45484993-53744780-b756-11e8-8f3c-c80cb2f07675](https://user-images.githubusercontent.com/40452146/45692822-016b6180-bb5c-11e8-90d5-d8d8e00028e5.png)

### Expected result
I expected the textbox to be displayed when I checked yes to the question of the condition.

### Actual result
The phonenumber texbox does not show up when I checked yes to the condition of the question

**Comment by greystate** [comment]
Same issue were having on an upgraded site - this worked before the upgrade.

**Comment by bergmania** [comment]
Hi @natashadecanha,

I have looked into the issue. There are thrown an error in Javascript because there is no default value in the "Do you have phone?" question.  I think it will work as expected if you set "No" as default.

I have made a fix for it, but that's not released yet.

**Comment by bergmania** [comment]
Same issue as #1

**Comment by natashadecanha** [comment]
Hi bergmania, 

Thanks for replying. I tried your solution, but unfortunately even adding a default answer doesn't solve the problem. 

- I tried adding the default value 'No' in umbraco, then in the front end the no box was checked. But when I check 'Yes' the conditional is still not working.
- I tried adding the default value 'Yes' in umbraco, then in the front end the yes box was checked. But the conditional input doesn't work.

**Comment by bergmania** [comment]
Hi @natashadecanha,

Can you confirm, that the folloing javascript error are in the console, if you have developer tools open when reloading the page

> Cannot read property 'split' of undefined [...]

**Comment by natashadecanha** [comment]
Hi @bergmania 

No I do not recieve the 'Cannot read property 'split' of undefined [...]' error in the console.

**Comment by bergmania** [comment]
@natashadecanha, not even when you don't have a default value for the "Do you have phone?" question?

**Comment by natashadecanha** [comment]
@bergmania No sorry :( I tried everything, I do not get that error. Only errors I get is the '404 not found for favicon' and the 'billing error for google maps'.

**Comment by bergmania** [comment]
@natashadecanha, I am sorry, but I really have trouble reproducing, if it should not be the "split" error.

Can you try to debug the javascript in _umbracoforms.js_ line 220. That line should be executed on reload. As you can see in my screenshot the value is undefined, and thats why I get the "split"-error in line 223.

![image](https://user-images.githubusercontent.com/1561480/48249144-58721200-e3fa-11e8-8ef0-9d8e121f9a37.png)

**Comment by natashadecanha** [comment]
Hi @bergmania 

I think the problem that i'm having with the forms lies somewhere else. At first I couldn't find the umbracoforms.js and thought maybe that was the problem. After a little experimenting I found out that if I add a form on the homepage -> content -> insert macro -> insert form with theme -> contact form, then follow the steps from https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/Prepping-Frontend/ to add the scripts, the form, the conditions work perfectly. 

But if I add the form on the contact page -> form -> pick a contact form (which uses the Form Picker property editor) -> contact form, then it doesn't work. And I checked, the umbracoforms.js doesn't get loaded in the page. So I think that it's probably the page or the form picker property editor not rendering properly.

**Comment by bergmania** [comment]
Hi @natashadecanha.

Now I can reproduce - As you say it is because the scripts are not loaded.

If you insert `ExcludeScripts="0"` into the macro in the content template (`/Views/Contact.cshtml`) it should work.

The line should be

`@Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ContactForm.ToString(), ExcludeScripts="0"})`

instead of the original 
`@Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.Content.ContactForm.ToString()})`

**Comment by natashadecanha** [comment]
Yes, that works! Thank you

**Comment by AlexWoollard** [comment]
We got a new case of this problem 
https://umbraco.zendesk.com/agent/tickets/54518

They are on Umbraco version 7.15.5 and Umbraco Form version 7.4.1

**Comment by hfloyd** [comment]
I have just come across this same issue on a v7 Umbraco Cloud project:
Umbraco 7.15.6
Forms 7.4.1
Deploy 2.1.1

Specifically getting the JS error "Uncaught TypeError: Cannot read property 'split' of undefined" (as detailed here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/1)

**Comment by nul800sebastiaan** [comment]
I'm closing this as this split seems to not give errors in Forms 7.5 any more.
