### ISSUE TITLE
Select with comma in value fails validation

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco.Forms.Issues#243]
### Bug summary
I have a select box with several options which include a comma in the value. When I post the form, I get a validation error. It looks like it's splitting it at the comma. 

Unexpected value: '$20'. Expected one of these: 'Under $10,000', '$10,000- $15,000', '$15,000 - $20,000', '$20,000 and up' 

### Specifics
![image](https://user-images.githubusercontent.com/13674761/67408219-8bf76f00-f56d-11e9-9ebe-2bb2d51c2b28.png)

### Steps to reproduce
Create a select which includes validation and a comma in the prevalues. 

### Expected result
The form should be submitted

### Actual result
The field is marked as invalid. 

---
_This item has been added to our backlog [AB#4190](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4190)_

**Comment by alandraper** [comment]
Hi -- thanks for taking a look. To me it looks like server validation... the form does post, and returns a new page with the error message in the source (rather than angular-created validation). 

The (snipped) posted data looks like this:
a14a8e13-8d5e-4b84-a373-2b0853c1e024: open house style reception
7df91522-d5b1-4e46-c155-9164c941b74f: $15,000 - $20,000
5bf2a21d-79a9-41d7-fbc3-7f06b9bdd764: test

UmbracoCms 7.12.4
UmbracoForms 7.1.2

**Comment by alandraper** [comment]
Hi there. I was able to recreate this on a clean Umbraco installation. 

Steps to recreate
1. Blank solution 
2. Added empty MVC project
3. Added UmbracoCMS Nuget
4. Build and run to create sample site. 
5. Clicked on Forms in the Umbraco backend, agreed to install Forms
6. Edited the pre-build "Comment Form" and added a "How much money would you like" question with the prevalues of $100, $1,000, $1,000,000
7. Added the form to a new page
8. Save and publish
9. Submit fails due to comma. 

![image](https://user-images.githubusercontent.com/13674761/68982968-d27f6880-07bd-11ea-9417-8a4b85918d91.png)

I added the whole project including the forms data into source control here:
https://ascii-interactive.visualstudio.com/_git/TestUmbracoForms

Any suggestions? I'm trying to get my client updated from Umbraco Forms 4.4.2 and this is stalling the update.

**Comment by bergmania** [comment]
I can repro on v7.2. This is already fixed for v8.2

**Comment by bergmania** [comment]
PR https://github.com/umbraco/Forms/pull/316

**Comment by warrenbuckley** [comment]
This is fixed in this PR here - https://github.com/umbraco/Forms/pull/316

**Comment by alandraper** [comment]
Looks like that is a private repository. Is 7.2.1 being released soon? Or could you share a patch here? Client getting antsy.

**Comment by alandraper** [comment]
Hi any word on this? Is there any way to get the patch or update?
