### ISSUE TITLE
Forms - Cross-site scripting XSS vulnerability

### ISSUE THREAD

**Issue by iishnz** [umbraco/Umbraco.Forms.Issues#245]
A penetration test by an external company on one of our sites running Umbraco forms revealed cross-site scripting vulnerabilities.

Umbraco 8.1.4
Forms 8.1.3
Tested with Form 8.2 with the same result.

Also tested in Umbraco 7.10.4 with Forms 6.0.8 and this issue did not occur.

### Steps to reproduce

* Install Umbraco and use the starter template.
* Install Umbraco Forms
* Create a form with one Question of type Short Answer
* On the same form, create a "New Page" and add another question of type Short Answer
* In the content section, create a test page.
* Add a Full Width row, add a Macro - select "Insert Form with Theme" and then choose your test form, the theme field can be left blank.
* Save+Publish
* Navigation to your test page and paste in the following test:
`</scRipt><scRipt>alert('ugh')</scRipt>`
* click next, and the script is executed.

![image](https://user-images.githubusercontent.com/8585977/67992088-51de4980-fca0-11e9-9079-3fe315367f46.png)

![image](https://user-images.githubusercontent.com/8585977/67992095-5f93cf00-fca0-11e9-9c4a-d4812c2efe91.png)

---
_This item has been added to our backlog [AB#3802](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3802)_

**Comment by Jonno-A** [comment]
FYI - we also have this issue.

**Comment by simonech** [comment]
we have the same issue also on Umbraco 7
