### ISSUE TITLE
EPPlus dll is missing when installing Forms v8.0.0 - v8.2.0 via the backoffice or by downloading the package

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Forms.Issues#248]
When you install Forms through the Umbraco backoffice or by downloading the Forms package from [Our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/), it will be missing the EPPlus.dll file. 

That becomes a problem when you want to use this function for your entries
"Exports all data to excel"
![image](https://user-images.githubusercontent.com/42831978/68377867-695b7d80-014b-11ea-82dc-e423b768445b.png)

Instead of a downloaded Excel sheet, you are met with this error in the Dev console.
`Possibly unhandled rejection: {"data":{"Message":"An error has occurred.","ExceptionMessage":"Could not load file or assembly 'EPPlus, Version=4.5.3.1, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified."`

### Workaround
There is a simple workaround. From [Our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/), you can download a zip file with the Umbraco Forms files. That zip file will contain the EPPlus.dll in the bin folder. Find the same version of Forms as you are using and download it. Then copy the EPPlus.dll over to the bin folder of your project.

Reproduction
------------
Umbraco v8.0.0 - v8.2.2
Forms v8.0.0 - v8.2.0

1. Boot up Umbraco v8 and then install Forms via the backoffice or by downloading the package from  [Our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/). 
2. Create a Form and output it on the front-end.
3. Create a form entry from the front-end so there is some data to export.
4. Try to export all data to Excel.

### Expected result
Downloaded Forms entries

### Actual result
Error message in the dev console and no entries downloaded
```
"Message": "An error has occurred.",
        "ExceptionMessage": "Could not load file or assembly 'EPPlus, Version=4.5.3.1, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.",
        "ExceptionType": "System.IO.FileNotFoundException",
        "StackTrace": "   at Umbraco.Forms.Core.Providers.Export.ExportToExcel.ExportToFile(RecordExportFilter filter, String filepath)\r\n   
at Umbraco.Forms.Web.Editors.ExportController.PostGenerateExport(RecordExportFilter model)\r\n   
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
```

**Comment by bergmania** [comment]
Thanks for reporting..
Will be fixed from next version

**Comment by Myster** [comment]
I still get this issue in UmbracoForms v8.7.0 umbraco v8.12.2
There is no indication of anything happening in the UI.
In the console I see the POST to https://example.com/umbraco/backoffice/UmbracoForms/Export/PostGenerateExport
This request is returned with status code 500 and the body below: (prettified and trimmed)
```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Could not load file or assembly 'EPPlus, Version=4.5.3.2, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.",
  "ExceptionType": "System.IO.FileNotFoundException",
  "StackTrace": " at Umbraco.Forms.Core.Providers.Export.ExportToExcel.ExportToFile(RecordExportFilter filter, String filepath) ... snipped ..."
}
```

**Comment by HalldorLyngmo** [comment]
Hi @Myster 

I can't reproduce this issue with UmbracoForms v8.7.0. In the package and the zip I get the `EPPlus.dll`.

My initial theory was that maybe the file wasn't added if you upgrade from Forms v8.0.0 - v8.2.0 using the Forms package and the backoffice, but that wasn't the case. This worked fine and the `EPPlus.dll` gets added.

If you have any way for me to reproduce I would be all ears 🙂

In the meantime, here is the Umbraco Forms V7 files. If you unzip it and copy the EPPlus.dll to your `/bin` folder the issue should be resolved.
[UmbracoForms.Files.8.7.0.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/6546767/UmbracoForms.Files.8.7.0.zip)

**Comment by Myster** [comment]
I have an older project that stopped working because The package is no longer on nuget:
WARNING: Unable to find version '4.5.3.2' of package 'EPPlus'.
