### ISSUE TITLE
Error while adding Umbraco forms to rich text editor

### ISSUE THREAD

**Issue by merinkalapurackal** [umbraco/Umbraco.Forms.Issues#249]
A brief description of the issue goes here.

while adding adding umbraco forms to my website i got this error: 'Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.
But the issue is solved by adding form directly to template.

**Comment by nul800sebastiaan** [comment]
Hi @merinkalapurackal, luckily that is not the experience most people have, so there seems to be something wrong for you. Could you be a bit more specific please? Which versions of Umbraco and Forms are you using, what have you tried, has it ever worked, etc.

**Comment by nul800sebastiaan** [comment]
I'll close this for now, let us know when you have more details on how to reproduce this issue! 👍
