### ISSUE TITLE
File upload doesn't work on multi page form

### ISSUE THREAD

**Issue by benbracedigital** [umbraco/Umbraco.Forms.Issues#25]
A brief description of the issue goes here.

On a multi page form when you go back to a page with a field upload field, you get a YSOD with an error on live 
`foreach (Dictionary<string, string> dictionaryObject in Model.Values)` 

The value that is returned is a string but even when this is fixed, the values that have been uploaded are lost.

Reproduction
------------

1. Create a form with more than one page.
2. Add a file upload field on page 1 and other fields on page 2
3. View the form on the frontend, select a file on the upload field and click next to go to the next page
4. Return to the first page and you will get a YSOD

### Bug summary
I updated the code so it was
```
foreach (string thisFile in Model.Values)
        {
            string currentDir = Environment.CurrentDirectory;
            DirectoryInfo directory = new DirectoryInfo(currentDir);
            FileInfo file = new FileInfo(thisFile);

            <input type="hidden" name="@(Model.Name)_file_@(file.Name)" value="@file.DirectoryName" />
        }
```
This removes the YSOD but when you proceed and complete the form, the file is not saved to the form entry.

### Specifics
Version 7.0.3 of Umbraco Forms

### Steps to reproduce
As detailed above

### Expected result

Forms pages shouldn't YSOD and files should be uploaded to the form entry even if you go back a page

### Actual result
YSOD or no file is uploaded to the form entry

**Comment by nul800sebastiaan** [comment]
Thanks @benbracedigital and sorry for the late reply! 🙈

This bug was fixed in version 7.0.4, make sure to upgrade! 👍
