### ISSUE TITLE
Include IP in submissions export

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#254]
We have a client that would like to include the user's IP address in the export of form submissions like Contour used to do.  Is this something you would consider adding?  I guess there could be a checkbox to include the IP address in the export.

**Comment by nul800sebastiaan** [comment]
Thanks @richarth - at the moment we don't track the IP in Forms any more. Currently this is not on our roadmap to add either, but I've marked it as an idea to look into for the future. 

For now I would recommend you implement a custom fieldtype that can submit the user's IP address, or a workflow should probably be able to capture an IP address as well.

I will close this issue as we're not planning to work on it in the near future, but when we do select new features to implement we run through any closed issues with the `idea` label added, like I've done here.
