### ISSUE TITLE
Umbraco Forms 7 - Camera 'File Upload' from Apple Device camera overwrites "image.jpg"

### ISSUE THREAD

**Issue by mike-connolly-xentrall** [umbraco/Umbraco.Forms.Issues#257]
A user of Umbraco Forms has identified an issue with using a File Upload on an Apple device (iPhone or iPad).
( for example; form for a Bus Pass and invites user to upload a photo )

When a user uses their camera to upload an image, it saves it as “image.jpg" on any Apple device.

The form entry image URL becomes something like this….
/media/forms/upload/form_f3032961-b84c-413e-a228-1bd9acfca3b6/7a6afffd-c14d-4402-8f19-338b3d4741f1/image.jpg

The format is…..
/media/forms/upload/form_**{GUID OF FORM}** /**{GUID OF FORM FIELD}**/image.jpg

The issue, when the next person uploads a new photo via an Apple device; they are overwriting the current “image.jpg” file on record for a previous entry.

**Comment by nul800sebastiaan** [comment]
This was fixed in #261
