### ISSUE TITLE
Separate Database for Umbraco Forms

### ISSUE THREAD

**Issue by ealse** [umbraco/Umbraco.Forms.Issues#262]
We would like to have a separate database for Umbraco Forms. 

The reason for this is that we could separate Umbraco content data en user input data from each other. This would allow us to ensure that our high available site does not lose any form data during a release.

**Comment by nul800sebastiaan** [comment]
Thanks @ealse for this feature request. 

We're not currently planning to work on a new feature as describe. It's good idea though and we'll put it on our list of ideas for when we start working on new features related to databases! 👍

**Comment by AndyButland** [comment]
Still valid and something I'd like to look at in future, but will close this as we have a duplicate at issue #363.
