### ISSUE TITLE
V8: Macro form can't render in backoffice

### ISSUE THREAD

**Issue by joepvtl** [umbraco/Umbraco.Forms.Issues#263]
When adding the  "Insert Form With Theme" macro to a RTE. It can't render because of the fixes that were added in #176 It will give a nullref exception because you don't have a publishedcontent request in the backoffice.

Reproduction
------------

Insert the "Insert Form With Theme" macro into a RTE and select any form. Then you will see it gives a error that it can't render the partial.

Umbraco forms version 8.2.0

**Comment by nul800sebastiaan** [comment]
Thanks, this will be fixed in v8.2.1 which is due out in the next few weeks, for now there's a hotfix available here which you can use to overcome this problem: https://github.com/umbraco/Umbraco.Forms.Issues/issues/235#issuecomment-537412133
