### ISSUE TITLE
Backoffice not localized

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco.Forms.Issues#267]
I just noticed that the Umbraco Forms backoffice is not localized. Not only are there no translations provided, all text is actually hardcoded in English, which makes it impossible for me to do a manual translation.

I find this strange, given that the rest of Umbraco is localized - particularly given that Forms is a commercial add-on.

This is Umbraco Forms 8.2 on Umbraco 8.4.

### Steps to reproduce

Install Forms and change to the language of the Umbraco backoffice to another language (such as Danish). Go to the Forms section and notice that the UI is still in English.

### Expected result

The UI is translated, consistent with the rest of the Umbraco backoffice.

At least text should not be hardcoded, so that I can provided a language file, should I need to.

### Actual result

The UI remains in English.

All text is hardcoded, so that I cannot manually supply a translation.

**Comment by nul800sebastiaan** [comment]
This is currently not a feature we have for Forms unfortunately. To set some expectations, we're not working on it in the foreseeable future unfortunately, but I'll put this on the list of ideas to look at in the future, thanks!

**Comment by woldringarjan** [comment]
Hi,

Wondering what the status is for this issue. We have Umbraco backend completely translated in Dutch. So it looks very weird that all of sudden the Umbraco Forms part is in English.

We would really love to have the localization keys in place!

Thanks in advance!
Cheers,
Arjan

**Comment by AndyButland** [comment]
No immediate updates yet @woldringarjan I'm afraid, but it's still on the radar.  I'm hoping that post the summer, when hopefully the migration to V9 is done and bedded in, we'll be able to look at some of the larger but long-standing asks like this one.

**Comment by woldringarjan** [comment]
> No immediate updates yet @woldringarjan I'm afraid, but it's still on the radar. I'm hoping that post the summer, when hopefully the migration to V9 is done and bedded in, we'll be able to look at some of the larger but long-standing asks like this one.

Thank you Andy. It's so great that you are now working on Forms! It's much needed.

**Comment by AndyButland** [comment]
At the very least a "localizable" - i.e. with all strings no longer hard-coded in UI templates but drawn from the usual Umbraco language files - back-office will be released with the 8.10 and 9.2 releases.  What languages we'll ship with out of the box is still to be determined.
