### ISSUE TITLE
Missing data consent field type partial

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#27]
I created a form which contained a data consent field using Umbraco Forms 7.0.4.  I then inserted the form into a page using the insert form (legacy) macro.

When I run the site in debug mode and visit the form page I get an error.  The error is that there isn't a data consent field type partial in /partials/forms/fieldtypes/.

There is a data consent field type partial in /partials/forms/themes/default/fieldtypes/, it looks like this just needs copying to the legacy path.

**Comment by warrenbuckley** [comment]
Connects https://github.com/umbraco/Forms/pull/224
