### ISSUE TITLE
Umbraco Forms

### ISSUE THREAD

**Issue by ArunVROfficial** [umbraco/Umbraco.Forms.Issues#271]
When i tried to add custom scripts to the umbraco forms fields, i noticed that the validation field became empty each time (but functionality works as given previously, but in the case of custom regex its not possible to see which expression is given or whether this field is validated)

**Comment by nul800sebastiaan** [comment]
Hey there @ArunVROfficial - can you be a bit more specific about what you're trying to do? I'm not sure what it is you're trying to achieve here.

**Comment by nul800sebastiaan** [comment]
Since we haven't heard back, we'll close this for now, but leave a comment with the specifics if when you can! 👍

**Comment by ArunVROfficial** [comment]
Hi @nul800sebastiaan 
Really sorry for the delay in replying.. : (
What the issue i faced was,

I'm using umbaco forms
I have a field for Name and i give a regex inside custom regular expression in validation field to ensure only alphabets will be inserted (^[A-Z]+$)

After saving the expression i moved to another activities and later i came back to the same form and checked the same field again and i found that the field look alike empty.
(but the validation works as given earlier, ie only texts are being inserted)

**Comment by nul800sebastiaan** [comment]
Ah no problem! This is the same issue as described here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/274 
Make sure to follow that issue for updates! 👍

**Comment by ArunVROfficial** [comment]
@nul800sebastiaan 
Yes it is..
Is there any solution right now.?

**Comment by ArunVROfficial** [comment]
Yeahh...
Thank you
