### ISSUE TITLE
8.3.0 readme says installed version is "8.2.0"

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco.Forms.Issues#272]
Updated Umbraco Forms via nuget to 8.3.0 and when Umbraco Forms is finished installing it shows the  \packages\UmbracoForms.8.3.0\readme.txt file which lists the version as "8.2.0".

![umbraco forms 8 3 nuget](https://user-images.githubusercontent.com/32468062/73349596-615f3580-4283-11ea-91bc-6ebd6a2c141c.PNG)
![umbraco forms 8 3 readme](https://user-images.githubusercontent.com/32468062/73349597-615f3580-4283-11ea-89fd-9c71d2c3b288.PNG)

**Comment by bergmania** [comment]
Hi @Wiggee11 

Thanks for reporting.. We clearly forget to update the readme :(

Will be fixed for next release..
