### ISSUE TITLE
Conditional Logic no longer working after upgrade to forms 8.3.0

### ISSUE THREAD

**Issue by yorky002** [umbraco/Umbraco.Forms.Issues#273]
We just upgraded our version of forms from 8.2.0 to 8.3.0 and conditional logic has stopped working.

Have tried saving a change to an existing form.

No js errors are thrown.

---
_This item has been added to our backlog [AB#4905](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4905)_

**Comment by yorky002** [comment]
An update on this:
When conditional logic is applied to a value with spaces the logic does not fire. When a single word value is used in the codition it works fine.

**Comment by nul800sebastiaan** [comment]
Thanks for reporting @yorky002, we'll have to investigate. Are you sure this used to work in 8.2.0 with spaces?

**Comment by lukehook** [comment]
@yorky002 @nul800sebastiaan I'm also seeing this and it was working in 8.2.0 for me also (I'm 99% sure). In my instance I've noticed the following in the console. I don't know if this is related or not

![image](https://user-images.githubusercontent.com/7995797/73557733-9fa65180-4449-11ea-8381-fdeafab8578e.png)

**Comment by yorky002** [comment]
Hi @nul800sebastiaan ,

Yes 100% it used to work prior to the upgrade from 8.2.0 to 8.3.0. Working just before upgrade, not working afterwards.

Cheers,
Kate

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/319

**Comment by bergmania** [comment]
## Workaround: 

In `/Views/Partials/Forms/Themes/default/Script.cshtml` use `Uri.EscapeUriString` instead of `HttpUtility.UrlEncode`.

The difference is that space is encoded as `%20` instead of `+`. And the javascript in the condition logic decodes `%20` back into space.

**Comment by Gavlar50** [comment]
Just experienced the unexpected JSON token issue after upgrade to 8.3.0, worked fine on earlier version. Found that line 25 in App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js has been updated to:
`init({ form: JSON.parse(unescape(formsCollection[i]))});`

changed back to
`init({ form: formsCollection[i]});`

and now the conditional logic works with no js errors

**Comment by danielconner** [comment]
> Just experienced the unexpected JSON token issue after upgrade to 8.3.0, worked fine on earlier version. Found that line 25 in App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js has been updated to:
> `init({ form: JSON.parse(unescape(formsCollection[i]))});`
> 
> changed back to
> `init({ form: formsCollection[i]});`
> 
> and now the conditional logic works with no js errors

Spent hours trying to the conditions to work trying work-arounds and this finally worked for me! thank you
