### ISSUE TITLE
Group condition settings clearing on close of infinite window

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco.Forms.Issues#276]
### Bug summary

After configuring group conditions on Umbraco Forms - reopening the settings for that configuration and closing the infinite editing panel that shows causing the conditions to reset to their original defaults. If the form is then saved the settings are wiped out

### Specifics

- Umbraco Forms 8.3.0
- Adding form group condition configurations

### Steps to reproduce

1. Create an Umbraco Form with more than 1 group of fields on a page
2. Configure a group to show/hide based on a given conditions
3. Save this condition configuration
4. Re-open configuration settings
5. Close infinite editing panel with settings (Close, not save)
6. Re-open again to see conditions have cleared
7. IF the form is saved, settings are wiped out (defaults saved) - If the form is reloaded before saving the original settings are maintained

### Expected result

Closing the infinite editing panel should not erase the settings in the UI

### Actual result

Closing the editing panel causes the settings to reset in the UI (they appear reset after re-opening). Saving the form at this point saves these reset settings

![UmbracoFormsGroupConditions](https://user-images.githubusercontent.com/7995797/73681207-c668c000-46b5-11ea-8889-2966fc7b4fe9.gif)

**Comment by lukehook** [comment]
(apologies in advance if infinite editing window isn't the correct terminology)

**Comment by nul800sebastiaan** [comment]
Oh yes, I can reproduce this in 8.2.0 as well, that's annoying!
