### ISSUE TITLE
Date Picker selection not validating as matching a field condition

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco.Forms.Issues#277]
### Bug summary

When setting a field condition to match if a Date Selection field IS NOT empty - the selection of a date doesn't meet the condition criteria until further interaction is made.

### Specifics

- Umbraco Forms 8.3.0
- Field condition to match if a Date field type IS NOT empty

### Steps to reproduce

1. Create an Umbraco Form with one Date field and another field (short answer is fine)
2. Configure second field (short answer) to only 'show' if the Date field IS NOT empty
3. Save this condition configuration
4. Add form to a page to view
5. Select a date using the date picker
6. Second field doesn't show as condition is not matched
7. Interact with date field (add a character on the end of the date string for example)
8. Second field should now appear

### Expected result

Selecting a Date and therefore populating that field should cause the condition to validate

### Actual result

Selecting a date doesn't meet the condition, further input in to the field causes the condition to be met

### Suggested issue / solution

*** VERY MUCH GUESS WORK HERE ***
I'm presuming the condition validation checks for the value of the input on keypress or something. The binding of the onclick event, although populating the input value, is not registered in the condition as a valid event. Can the condition detect the onclick of the calendar control to check the input?

![UmbracoFormsDatePickerConditions](https://user-images.githubusercontent.com/7995797/73682215-d41f4500-46b7-11ea-99f3-4109146746fa.gif)

**Comment by nul800sebastiaan** [comment]
Thanks, can also reproduce this on v8.2.0 of Forms!
