### ISSUE TITLE
Deleting a form in Forms seemingly times out with no ux indication but apparently still deletes the form

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Forms.Issues#28]
_From @sniffdk on October 3, 2018 7:17_

When trying to delete a form with 280+ entries, Forms will hang and after close to 4 minutes throw a 500 error stating the the operation has timed out.
The ux does not reflect that, and there is no "deletion in progress" indication, so for normal users it just seems like nothing is happening, often aborting the request early.
Even though Forms throws a timeout exception, the form is still deleted from both disk and database, if the request is allowed to "complete".

At least, the ux for deleting forms and error handling, including logging, should be improved.

The site in question is running on Azure as a webapp with an Azure SQL database running S2 with 50 DTUs, just to give a performance indication.
Umbraco is running v 7.12.2 and Forms is running v. 7.0.3.

_Copied from original issue: umbraco/Umbraco-CMS#3128_

**Comment by bergmania** [comment]
Hi @sniffdk

The reason this is slow can be many things. Did you have other forms with many records?
If so, a missing index can be the reason. This index is added by default from forms v8.

```
CREATE INDEX [IX_record_recordfield] ON [UFRecordFields] ([Record] ASC);
```

Also if there are files uploaded, the delete can be very slow. Can you give me some more information about the form, to let me reproduce easier.

**Comment by sniffdk** [comment]
Hi @bergmania 

I did see something a while back about adding an index to speed up deleting, haven't testet it yet though, as it hasn't been prioritized by the customer.
Would be a good starting point indeed 👍 

None of the forms contains file uploads though, most of them contains 6-8 properties with mostly small text, radio buttons and checkboxes.
Don't know how much that helps 😅

**Comment by bergmania** [comment]
@sniffdk, just do give an update:
- We have added an spinner to the delete button, such that the user can see work is progress.
- We optimized heavily in the delete flow, but this is still a very heavy operation. Expect ~1-2 seconds for each ~150 records. I tested forms with up to 10.000 records, and that works as expected.

This will be released as part of the next versions of v7 and v8.

**Comment by sniffdk** [comment]
@bergmania thanks for the update, great work 😃
