### ISSUE TITLE
Entries Table and Entry Detail views are not localized

### ISSUE THREAD

**Issue by samgooch** [umbraco/Umbraco.Forms.Issues#282]
When using dictionary items for form field labels, they do not get translated using the dictionary. It works when browsing the form on the front-end. However, when someone accessing the entries in the backoffice, it doesn't.

Umbraco v8.5.3
Umbraco Forms v8.3.0

Reproduction
------------

### Bug summary

- Browse to the entries table, the columns are not translated and still read as if they were taken as-is
- Click into an entry, the headings are not translated and still read as if they were taken as-is

### Specifics

![image](https://user-images.githubusercontent.com/3908022/74229919-3e894400-4cbb-11ea-8de8-b4cfe27b2025.png)

### Steps to reproduce

- Create a dictionary item for your current logged in language
- Create a form and add a property using the dictionary item e.g. #Email
- Add the form to a page and submit the form
- Browse to the entries table, the columns are not translated and still read as #Email
- Click into an entry, the headings are not translated and still read as #Email

### Expected result

The column / heading names should be localized to the current user's backoffice language. As per the behaviour on the front-end for a user filling out the form.

### Actual result

The column / heading names don't translate using the Dictionary.

**Comment by nul800sebastiaan** [comment]
Thanks! Probably almost nothing in Forms is localized unfortunately, make sure to keep track of this issue for updates! 👍  https://github.com/umbraco/Umbraco.Forms.Issues/issues/267
