### ISSUE TITLE
Non-JS / Server-side validation messages are not localized

### ISSUE THREAD

**Issue by samgooch** [umbraco/Umbraco.Forms.Issues#283]
When filling out a form as a user with no-javascript enabled or after failing some specific server-side validation. A user sees the non-localized field name in the errors.

Umbraco v8.5.3
Umbraco Forms v8.3.0

Reproduction
------------

### Bug summary

- This only happens for forms which have form field labels using dictionary items

### Specifics

![image](https://user-images.githubusercontent.com/3908022/74230523-72189e00-4cbc-11ea-8d37-bc3ce34a55e3.png)

### Steps to reproduce

- Create a dictionary item such as Email
- Create a form with a form field for the email, set the label to #Email
- Add the form to a page and submit the form
- Disable JS and submit the form without entering any details

### Expected result

The validation message should also translate the form field label.

### Actual result

The validation message has the form field label as-is without trying to translate via a Dictionary item.

Workaround
------------
It's not ideal as it should be a part of the main product, but something like the below works for me. It loops through the errors and finds the Umbraco dictionary notion of #{Dictionary_Key}

    var regex = new Regex(@"\B(\#[a-zA-Z_]+\b)(?!;)");
    foreach (var value in ViewData.ModelState.Values)
    {
        for (int i = 0; i < value.Errors.Count; i++)
        {
            var newError = value.Errors[i].ErrorMessage;
            var result = regex.Match(newError);
            if (result.Success)
            {
                var capture = result.Groups[0].Captures[0].Value;

                var dictionaryValue = Umbraco.GetDictionaryValue(capture.TrimStart('#'));
                value.Errors[i] = new ModelError(newError.Replace(capture, dictionaryValue));
            }
        }
    }

**Comment by nul800sebastiaan** [comment]
I can't seem to reproduce, note near the end that I'm taking out the JS libraries so a full postback needs to happen. Maybe I'm doing something differently? For now I'll close this issue, let me know if you have additional steps to reproduce.

![283](https://user-images.githubusercontent.com/304656/74311962-eca2f580-4d70-11ea-9d8e-c9691b923f37.gif)

**Comment by samgooch** [comment]
Ah, the only difference with your steps is that I didn’t add a custom validation message. I used the default which uses the string.format notion to place the field label within the space. And it was the dictionary key being replaced and not the dictionary value
