### ISSUE TITLE
Ability to sort Entries by column

### ISSUE THREAD

**Issue by samgooch** [umbraco/Umbraco.Forms.Issues#284]
It would be good to be able to sort the entries by column like you currently can with Umbraco list views.

**Comment by nul800sebastiaan** [comment]
Thanks @samgooch - we currently have no plans to introduce new features in the entries list, we recommend you use the export feature to do sorting in Excel / Google Sheets for now.

I'll put this on the list of ideas which we review regularly when we start working on new features.
