### ISSUE TITLE
Ability to filter Entries by field

### ISSUE THREAD

**Issue by samgooch** [umbraco/Umbraco.Forms.Issues#285]
It would be good to be able to filter by a particular field as opposed to a blanket text search within the record JSON.

You could still potentially use the JSON search, and extend the filter to include the field type GUID. For example: `WHERE RecordData LIKE "%'@fieldTypeId':'@text'%`. But I suppose the most performant way would be to actually search the relational record tables.

**Comment by nul800sebastiaan** [comment]
Thanks @samgooch - we currently have no plans to introduce new features in the entries list, we recommend you use the export feature to do more advanced filtering in Excel / Google Sheets for now.

I'll put this on the list of ideas which we review regularly when we start working on new features.
