### ISSUE TITLE
Copying forms does not assign a new GUID for copied fields

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco.Forms.Issues#287]
Initially reported as [CON-1532](https://issues.umbraco.org/issue/CON-1532) and [on the forum](https://our.umbraco.com/forum/umbraco-forms/91769-multiple-copied-forms-on-the-same-page).

Basically, whenever a form is copied its fields get the same GUID. This is an issue when multiple forms need to be present on the same page, with the duplicate ids causing issues (e.g. with validation).

CON-1532 is reported as resolved, but the issue remains for me in Umbraco 7.12.5 with Forms 7.3.1 (and on the Forum someone reported the same issue on v8).

### Steps to reproduce

The same as in CON-1532:

- Create form A with fields.
- Copy form A, name it B.
- Place both form A and B on your page. Duplicate IDs are now present on the page (e.g. Chrome will log warnings in console)

### Expected result

- When a form is copied, new GUIDs are generated for every item

### Actual result

- Fields of form A and B share the same GUID.

**Comment by rbottema** [comment]
Is there any update on this?

**Comment by garpunkal** [comment]
We're experiencing this issue too..  We copied the original form and have two copies of the form on the same page. It causes problems on the frontend. Is there any update?

**Comment by wjamieson** [comment]
We're also encountering this - On a page we have a form with conditional fields and a copy of that form with a reduced fieldset (no conditions). The copied form only shows the "Submit" button, the fields themselves do not render at all, even when the conditions on the original form are fulfilled and fields all display there.

**Comment by warrentheranga** [comment]
Any update or known workaround for this?

**Comment by rbottema** [comment]
Hi @nikolajlauridsen, why was this ticket closed? Is a fix on its way?

**Comment by nikolajlauridsen** [comment]
Yes, this has been fixed, and will be in the next release 😄 

I apologize for forgetting to let you know here, there were a couple of issues with this and I must have missed this one, sorry about that.

**Comment by rbottema** [comment]
Awesome, thanks! Now that I look at it, I see there was a duplicate(?) issue #476, which has also been closed =)
