### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by lesley-w** [umbraco/Umbraco.Forms.Issues#288]
Why is there no ability to add a label/text to go with the default single checkbox?

A checkbox by itself is meaningless..

**Comment by nul800sebastiaan** [comment]
I think there may be something wrong with the rendering of your checkbox, indeed just a checkbox with no label would make no sense. Seems to work for me: 

![image](https://user-images.githubusercontent.com/304656/74716048-1905b880-522e-11ea-9fdc-6f84f3bb5824.png)

I would recommend you get more help on the forums where our friendly community can help you find the best solution for your requirements.
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by lesley-w** [comment]
Thanks for the clarification. I hadn't realised that the caption was used as the label. This does, however, make it unusable for our purposes.

We were hoping to create a checkbox field like this: 

![checkbox2](https://user-images.githubusercontent.com/23325280/74772527-0dc99000-52f5-11ea-937f-bca6d0fe971b.png)

However, the default checkbox field would need to have the caption set to a large block of text and would then appear like this (with default Umbraco Forms styles). It also means the class name is ridiculously long which makes it awkward to apply custom styles to specific field:

![checkbox](https://user-images.githubusercontent.com/23325280/74772610-36ea2080-52f5-11ea-86b9-8915b4735e17.png)

Any chance of considering adding a label to the default checkbox field? In the meantime we will have to look to create a custom field.
