### ISSUE TITLE
RecordFetching event not triggering in the backoffice

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco.Forms.Issues#29]
Hi guys,

I've been working with my colleague Dennis on some new features of our awesome "Umbraco Forms on Steroids"-package to make it more GDPR-compliant. We have been working to realize some important parts of my blogpost and HTML mockup (https://skrift.io/articles/archive/i-have-a-nightmare-dream-about-umbraco-and-gdpr/, http://downloads.perplex.eu/umbraco/gdpr/settings2.html). 

Specifically we've been working on "delete data after x period" and encryption of the data.

The "delete data after x period" is already fixed with a workflow, and we will also do the encryption with a workflow. But when retrieving the data in the backoffice we have a problem and hopefully you can take a look shortly, so we can fix this and release the new and improved package. 

We hoped that we could decrypt the data when plugging into the event 

RecordStorage.RecordFetching += RecordStorage_RecordFetching;

So if we clicked on "Entries" in the backoffice forms-section this would get called and we could decrypt every record. But this isn't triggered and if we sneakpeek into the dll we see that the functions GetAllRecords and GetRecords in RecordStorage.cs do not dispatch this event (it does in GetRecord and GetRecordByUniqueID), and that is why we can't decrypt data.

Could you think for just a moment how we could achieve the decryption in the backoffice without rewriting whole parts of the work you've done?

=== 
Submitted a Ticket to ZenDesk and Dennis asked me to add this to the issue:

The change is fairly simple as it just involves dispatching the event in those two methods of RecordStorage.cs (you can leave a note for whoever picks up the issue that it's line 76 and 132).

I'd however like that someone with Forms knowledge verifies that this approach is okay and that we do not cause any performance issues by triggering this as separate single events for each record, instead of batching it up with a new event type.

I don't think there will be any major issues though, as we also currently fetch the data for every single record through a foreach loop but would just like to be sure ;)

=== 
Hopefully this can be fixed soon!

Jeffrey

**Comment by warrenbuckley** [comment]
@bergmania This looks OK, I am not sure if we will need to create a new bulk event. Let's get this out & see if the gold partner is happy/content with this solution @JeffreyPerplex  

If its a concern with perf then we could batch it with a single event instead if needed.

**Comment by JeffreyPerplex** [comment]
Hi guys, thanks for fixing this. Please let me know when / how I can test this!

**Comment by DennisBoonkP** [comment]
Hi everyone,

I tried different Umbraco Forms versions for Umbraco 7. But still the fetching event isn't triggerd when loading the backoffice or exporting the data. Can this ticket be reopend?
