### ISSUE TITLE
Forms: Store/retrieve field values in single SQL batch

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#294]
This is a seperate issue based on https://github.com/umbraco/Umbraco.Forms.Issues/issues/125#issuecomment-478883689.

The record fields are stored/retrieved as seperate rows (`UFRecordFields`), in different tables per field type (`UFRecordDataBit`, `UFRecordDataDateTime`, `UFRecordDataInteger`, `UFRecordDataLongString` and `UFRecordDataString`) and as JSON value in `UFRecords.RecordData`. This probably causes the slow POST response-time, as it has to create/update/read multiple tables to keep the data in sync. And looking at the SQL queries it generates, it fetches each field value in a seperate query, instead of using a single query with inner-joins or even grouping them per table/type...

---
_This item has been added to our backlog [AB#5657](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5657)_

**Comment by nul800sebastiaan** [comment]
Thanks, looks like there's plenty to win perf-wise.

**Comment by warrenbuckley** [comment]
@nul800sebastiaan the PR has before & after results from mini-profiler if you need them
https://github.com/umbraco/Forms/pull/343#issuecomment-601126152

**Comment by warrenbuckley** [comment]
OK tested a form with 19 fields before & after on a local copy of the site using a slower SQLCE DB

## Before
Total: 918.8ms
46 SQL statements executed

## After
Total: 161.4ms
27 SQL statements executed
