### ISSUE TITLE
Forms: unescape() added to 8.3.1 is deprecated

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco.Forms.Issues#295]
With the update to 8.3.1 the `/App_Plugins/UmbracoForms/Assets/Themes/Default/umbracoforms.js`
is now using `unescape`

```
 function initCollection(formsCollection) {
        configureUmbracoFormsValidation();

        for (var i = 0; i < formsCollection.length; i++) {
            init({ form: JSON.parse(unescape(formsCollection[i]))});
        }
    }
```
changed back to

```
init({ form: formsCollection[i]});
```
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

Also raised on https://github.com/umbraco/Umbraco.Forms.Issues/issues/273#issuecomment-589629054 but it was on a closed issue.

---
_This item has been added to our backlog [AB#5612](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5612)_

**Comment by nul800sebastiaan** [comment]
Yikes! We'll fix 👍
