### ISSUE TITLE
Cache-settings for custom FieldPreValueSourceType

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#297]
We're looking for a way to implement a custom "dropdown" with different values depending on what page the form is placed at. Similar to this one:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/99265-dynamic-custom-prevalue-source-caching-issue

Our first approach was to try with a custom FieldPreValueSourceType but as far as I can see the method GetPreValues() on our custom PreValueSourceType is only called once and then cached, I tried with <setting key="DisableFormCaching" value="True" /> in UmbracoForms.config but that does not really seem to have any impact.

So I'm wondering if this is a to consider a bug or maybe a feature-request - maybe there should be a way to explicitly say that GetPreValues should not be cached for a given FieldPreValueSourceType? Using a attribute or something? 

I guess that we could get around this by implementing a custom Field Type but it would have been ever better for us to use a prevalue source.

Cheers!

**Comment by nul800sebastiaan** [comment]
Thanks @enkelmedia, I can see from a previous investigation into this that we can't offer a good way to fix this in forms specifically - https://github.com/umbraco/Umbraco.Forms.Issues/issues/221
So from our point of view, this is what the limitation of `GetPreValues` is.

However your use case is a bit different, you specifically want to use data from the current page, correct? I think a custom field type would be much preferred in that scenario anyway, it gives you more control over what's happening and I believe you can set the `FieldTypeViewName` to be the default dropdown so you don't have to add a custom view file (not sure about that one).
