### ISSUE TITLE
Forms: Condition with field containing "éè..." is not working

### ISSUE THREAD

**Issue by cleanflow** [umbraco/Umbraco.Forms.Issues#300]
We use Umbraco form in different culture environment and it seems that putting condition on field that contains some special caracter like é or è or ù is not working.

Reproduction
------------

To reproduce, create a form, create a single choice question. Add “héllo” to value, add “hello” to value.
 
Create another question with condition and set a condition based on field “héllo” from first question.
 
Then go to see the form and click on Héllo from first question. The second question is not showing up. The condition is not woking.
 
On the other hand if I put the condition on “Hello” and the condition is working.

No special custom code used. The form is rendered directly with the macro.

### Bug summary

The bug comes from the way é è ù are handled in the js (umbracoform.js)
See in debug what's happening on line 216

### Specifics

This happens with version 8.3.1 of umbraco forms
We use umbraco  8.3.0
This happens on all browser (firefox, chrome, ie)

---
_This item has been added to our backlog [AB#5763](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5763)_

**Comment by thomasandresen** [comment]
This will be fixed in 8.4.0, thanks to the changes in [#295](https://github.com/umbraco/Umbraco.Forms.Issues/issues/295)
