### ISSUE TITLE
Forms: ValidateSettings for FieldTypes

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#301]
The documentation states that we can override "ValidateSettings" to validate settings on any type that is implemented using the "ProviderModel",

https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-type#validate-type-settings-with-validatesettings

I'm trying to validate a setting on a FieldType that inherits from Umbraco.Forms.Core.FieldType but there is no method to override neither on the basetype or in the interface IFieldType.

What I'm I doing wrong here..? Or is this an error in the docs?

---
_This item has been added to our backlog [AB#5761](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5761)_

**Comment by enkelmedia** [comment]
Maybe I should add this this: What I'm trying to do is to make one of our settings mandatory.

**Comment by enkelmedia** [comment]
Also turns out that when I'm creating a custom view for my settings it's possible to make the setting mandatory on the clientside (in the backoffice) by using something like:

```
<input type="text" required />
````

That would validate on the client side but as far as I can see there is no serverside validation for the settings.

**Comment by nul800sebastiaan** [comment]
I just don't think there is any way to make a setting mandatory from what I can tell, you just need to throw an exception when the value is incorrect or empty?

**Comment by enkelmedia** [comment]
Okey, we’ll where should I throw that exception so that the editor can adjust the settings when configuring the field in the backoffice? 

I guess i could throw in the cshtml-view but that Would be on the front end website and the editor would not notice until they’ve added the form to page and tries to visit that page.

**Comment by nul800sebastiaan** [comment]
I don't actually know but it looks like from the sample code you can check each field?

```csharp
public override List<Exception> ValidateSettings() {
    List<Exception> exceptions = new List<Exception>();
    int docId = 0;
    if (!int.TryParse(Document, out docId))
        exceptions.Add(new Exception("Document is not a valid integer"));
    return exceptions;
}
```
I'll admit, I am not sure what `Document` is, but I assume that's the name of the setting?

**Comment by enkelmedia** [comment]
Maybe I was unclear in my first post, but the thing is that the ValidateSettings-method is not there for FieldTypes, it works great for WorkflowTypes but not for FielsTypes.

**Comment by nul800sebastiaan** [comment]
Aah alright! Apologies, I haven't used this stuff for a long time so I am just trying to make sure you didn't miss anything obvious. We'll have to have a look at it.

**Comment by warrenbuckley** [comment]
Hi @enkelmedia this has been fixed for an upcoming release of 7.5.0 and 8.5.0, field type validate settings were never implemented it seems but the documentation made it sound like it was available for every provider type.

**Comment by enkelmedia** [comment]
@warrenbuckley  Sweet =D

**Comment by markwemekamp** [comment]
@warrenbuckley Should this still work in the current version (8.5.3)?

- I've created a custom FieldType with a custom Setting field
- Overriden the ValidateSettings method to validate the setting field
- Now when I save the field to the form or when I save the form itself, the field doesn't seem to validate, also my breakpoint never gets hit

Am I doing something wrong?

**Comment by bjarnef** [comment]
@nul800sebastiaan I guess `Document` is a custom setting, maybe a node picker?

I tried this on Umbraco Forms v8.6.0.
When I set a breakpoint in ValidateSettings method, it doesn't hit this.

```
public override List<Exception> ValidateSettings()
{
        List<Exception> exceptions = new List<Exception>();

        if (string.IsNullOrWhiteSpace(Action))
            exceptions.Add(new Exception("Action is required"));
        return exceptions;
}
```

But it doesn't seem to validate this field.

![image](https://user-images.githubusercontent.com/2919859/108493507-b1ea6c00-72a6-11eb-9065-aef475adb243.png)
