### ISSUE TITLE
Make RenderViewToString on ControllerExtension public?

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#302]
When creating a custom Workflow it would be nice to be able to use the build in Razor-rendering for the email views.

So, the only thing stopping us from that today is the fact that the RenderViewResultAsString is internal, would it be possible to consider making these public so that we can use them?

Also, I could inherit from ie. the "SendRazorEmail"-workflow but that would also give me a ton of settings that I don't need/want to show to the editor.

**Comment by nul800sebastiaan** [comment]
That would be a CMS issue (since it uses `Umbraco.Web.Mvc.ControllerExtensions.RenderViewToString`). 

However there is also `Umbraco.Forms.Web.Helpers.ViewHelper.RenderPartialViewToString` that might do what you need?

**Comment by enkelmedia** [comment]
=D You're so right =D Thank you very much for pointing me in the right direction, as a reference I ended up using the SendRazorEmail-workflow inside my own like so:

```csharp
var test = new SendRazorEmail(_httpContextAccessor,_fieldTypeStorage,_contentSection,_umbracoContextAccessor);
test.Email = "foo@test.se";
test.Subject = "Hallo World";
test.RazorViewFilePath = "Forms/Emails/Example-Template.cshtml";
test.SenderEmail = "foo2@test.se";

test.Execute(record, e);
```

This let's us remove some of the settings for the editor and have constants for them. I'm closing this issue. Thanks again @nul800sebastiaan!
