### ISSUE TITLE
Styling for Workflow-picker and "Create"-action dialog

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#303]
Seems like something is quite off with the styling of the workflow-picker, there is a lot of top padding for the options.

![image](https://user-images.githubusercontent.com/1782524/76410309-ff204700-638f-11ea-842d-c9e271d50826.png)

There is a "padding-top:100%"-css rule that probably has something to do with this.. 

![image](https://user-images.githubusercontent.com/1782524/76410386-1c551580-6390-11ea-9997-386c45d7272c.png)

Another thing is the "create"-dialog next to the tree where the styling also seems a bit of:

![image](https://user-images.githubusercontent.com/1782524/76410596-7e157f80-6390-11ea-9ab2-cfdfe3e016f2.png)

**Comment by nul800sebastiaan** [comment]
Thanks, it all needs some updating at some point yep. See related issues as well: 
 https://github.com/umbraco/Umbraco.Forms.Issues/labels/project%2Fbackoffice-ux

**Comment by nikolajlauridsen** [comment]
This has been fixed and will be in the next release 😄
