### ISSUE TITLE
Forms: Umbraco forms placeholders cannot use dictionary values

### ISSUE THREAD

**Issue by Splinx** [umbraco/Umbraco.Forms.Issues#306]
When creating a form and using the # syntax for translating fields ( f.e. #requestTitle -> dictionary item: requestTitle) the placeholder is not translated. So i'm using #requestTitlePlacholder in the placeholder setting field but the rendered form is showing #requestTitlePlaceholder as placeholder instead of the value of my dictionary item.

Reproduction
Bug summary
Placeholder is not being translated

Specifics
Version: UmbracoForms v7.3.1 , Umbraco 7.12.3
Browser: Chrome

Steps to reproduce
Create a form with a field, use #requestTitlePlaceholder as placeholder value, create a dictionary with the same name ( without #) and render the form.

Expected result
I expected to see the value of the dictionary item in the placeholder (like the name, default value etc...)

Actual result
The text I wrote in the dictionary field.

---
_This item has been added to our backlog [AB#5741](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5741)_

**Comment by Splinx** [comment]
I would like to add that I added a comment to the bottom of the previously resolve issue that presumably was fixed on forms v8:

https://github.com/umbraco/Umbraco.Forms.Issues/issues/185 

The trouble is I need this working on version 7 please.

**Comment by Splinx** [comment]
Oh no!

Thanks for looking and this and updating Warren.

Can you please let me know what we should be doing to use forms and provide options for localised sites.

Is it just that this feature is not (and will never be supported) in localised sites?

Thanks,
Splinx

**Comment by warrenbuckley** [comment]
Sorry @Splinx I forgot to leave a note before closing this issue up :)
This was a bug in V7 of Forms but was fine in V8 and it was missing the code to parse magic strings for placeholder text of form fields.

This is fixed in an upcoming version of 7.5.0

**Comment by Splinx** [comment]
haha - OK Warren.  Thanks for your super-speedy reply :)
