### ISSUE TITLE
Forms: Unchecked a CheckBox is save as true in form entry when UmbracoFormsController.FormPrePopulate event is implemented 

### ISSUE THREAD

**Issue by kbtan-uda** [umbraco/Umbraco.Forms.Issues#307]
Issue Description:
Unchecked a CheckBox answer type in multiple pages form is saved as true in form entry after the form has been submitted
We have implemented the Umbraco.Forms.Web.Controllers.UmbracoFormsController.FormPrePopulate event.

Tested on:
Our current enviroment - Umbraco CMS 7.12.3 and Umbraco Forms 7.0.4
Testing environment - Umbraco CMS 7.15.3 and Umbraco Forms 7.2.0

Steps to reproduce the issue:

1. Implement Umbraco.Forms.Web.Controllers.UmbracoFormsController.FormPrePopulate event and include the dll into the bin directory.
2. Create 2 pages form in back office
3. Add Checkbox answer type on page 1 and set default value to on.
4. Load the new form and uncheck the checkbox on page 1.
5. Click next and then previous button.
6. The checkbox in page 1 is till checked
7. Uncheck the check button again and continue to summit the form.
8. The form entry is showing true for the Checkbox answer type

---
_This item has been added to our backlog [AB#5743](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5743)_

**Comment by c9mbundy** [comment]
Please note the current version of V7 forms is 7.3.1 and changes were made to fix a bug regarding checkboxes and dropdowns that was the subject of a few regressions until finally fixed in 7.3.1 so you might want to check/test the current code first.

**Comment by kbtan-uda** [comment]
Tested version 7.3.1. 
Issue still persist.

**Comment by nul800sebastiaan** [comment]
I've tried this out and can reproduce, this behavior exists even without a `FormPrePopulate` event.

I haven't looked at the code but I think it might be really difficult for us to determine if that checkbox should be checked or not. Normal checkboxes are not checked on by default so if you change it and make it checked by default, then load the page again.. it goes: oh look, this checkbox is not checked, let's check it on. 
Not sure how much of the state we store between pages and if we can have a "I touched this checkbox" property to look at.

For now, might I suggest that you work around the problem by phrasing your question on the form differently or making it a radiobutton instead? 

I'll see if we can get this fixed.

**Comment by kbtan-uda** [comment]
Hi @nul800sebastiaan,

I would like to propose a code fix fro this issue.  It is only applicable when FormPrePopulate event is implemented.
The unchecked checkbox value will not appear in  Request.Form.AllKeys. 
So in function ExtractAllPagesState function, search for fields that are expected to has a submitted value on current page.  If it is not in the Request.Form.AllKeys, assume its submitted value is not available and overwrite and clear the value stored in form currentState.
Please let me know whether this is an acceptable fix and will not have side effect or cause new bug.

```
private Dictionary<string, object[]> ExtractAllPagesState(FormViewModel model, ControllerContext context, Form form)
        {
            var currentState = RetrieveFormState(model);

            if (currentState == null)
            {
                return null;
            }

            foreach (var field in form.AllFields)
            {
                object[] finalValues = new object[0];


                var prePopValues = form.AllFields.First(f => f.Id == field.Id).Values == null ?
                    new object[0] : form.AllFields.First(f => f.Id == field.Id).Values.ToArray();


                if (context.HttpContext.Request.Form.AllKeys.Contains(field.Id.ToString()))
                {
                    var postedvalues = context.HttpContext.Request.Form.GetValues(field.Id.ToString());

                    bool isEmpty = true;
                    if (postedvalues != null)
                    {
                        foreach (var postedvalue in postedvalues)
                        {
                            if (string.IsNullOrEmpty(postedvalue) == false)
                            {
                                isEmpty = false;
                                break;
                            }
                        }

                        // If the postedValues is empty, it means that the pre-populated field has been
                        // manually cleared and it can be pre-populated, otherwise keep the values as it is, we do this as
                        // the postedValues can hold a value that has been pre-populated or entered by a user, and because
                        // it could be a user input we always keep it, unless is empty.
                        finalValues = isEmpty ? prePopValues : postedvalues;
                    }
                }
                else if (context.HttpContext.Request.Files.AllKeys.Contains(field.Id.ToString()))
                {
                    //Handle file upload answer type
                    var fieldSchema = form
                                .AllFields
                                .First(f => f.Id == field.Id);

                    finalValues = fieldSchema.FieldType
                        .ProcessSubmittedValue(fieldSchema, finalValues, context.HttpContext).ToArray();
                }
                else
                {
                    //search for field that you expect to be returned on current page   
                    FieldViewModel fieldView = null;
                    foreach (var fs in model.CurrentPage.Fieldsets)
                    {
                        foreach (var c in fs.Containers)
                        {
                            fieldView = c.Fields.FirstOrDefault(x => x.Id == field.Id.ToString());
                            if (fieldView != null)
                                break;
                        }
                        if (fieldView != null)
                            break;
                    }
                    if (fieldView != null)
                    {
                        //e.g. handle checkbox type submitted value.  Not in Request.Form.AllKeys mean the checkbox is unchecked. 
                        finalValues = new object[0];
                    }
                    else
                    {
                        finalValues = prePopValues;
                    }
                }

                if (currentState.ContainsKey(field.Id.ToString()))
                    currentState[field.Id.ToString()] = finalValues;
                else
                    currentState.Add(field.Id.ToString(), finalValues);
            }

            return currentState;
        }  
```

**Comment by nul800sebastiaan** [comment]
@kbtan-uda We'll have to have a look in our upcoming sprint. Please note that the behavior you describe is also wrong (in 7.3.1) when there's absolutely no `FormPrePopulate` event defined.

![307](https://user-images.githubusercontent.com/304656/76867257-93dde580-6865-11ea-9ca5-89fc2d32c1f8.gif)

**Comment by warrenbuckley** [comment]
This has been merged in for V7 & V8 next releases

**Comment by kbtan-uda** [comment]
Hi @warrenbuckley and @nul800sebastiaan, 

I found a minor UI behavior issue during testing on the above PR.
- Clicking the label of the check box does not check or uncheck the check box anymore.

Regards,
Kwok
