### ISSUE TITLE
reCaptcha Privatekey not loaded  + Mixed content blocked (UmbracoForms v4.4.7)

### ISSUE THREAD

**Issue by lemieuxs** [umbraco/Umbraco.Forms.Issues#308]
A brief description of the issue goes here.

I am using Umbraco 7.6.13 with UmbracoForms 4.4.7. I added a reCaptcha control to my form, but it is not showing when redenred. The label is but not the control.

I have set the RecaptchaPublicKey & RecaptchaPrivateKey in umbracoForms.config. But it always load the default value for the public key (6LeqoNsSAAAAAOQrdqDFE5KAzDESxxxODLpOeJjh)
I decompiled the Umbraco.Forms.Web.dll to see that the RecaptchaPublicKey is never loaded from the configuration 😲 ...

Also the request to load the reCaptcha is done over http. Since my page is in https it's generating a mixedContent request which is blocked by Chrome 🤦‍♂ 

**Error Message**
(index):1 Mixed Content: The page at 'https://***********.***.ca/' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/challenge?k=6LeqoNsSAAAAAOQrdqDFE5KAzDESxxxODLpOeJjh&hl=&'. This request has been blocked; the content must be served over HTTPS.

**Specifics**
Umbraco 7.6.13
UmbracoForms 4.4.7

**Steps**
Create a basic form with a reCaptcha.
Set the RecaptchaPublic and Private key in umbracoForms.config
Load the web page with the form in https.

**Actual result**
Recaptcha is not shown, if you inspect the request, you shall see the public key is the default one, and that the request is blocked for cause of mixed content.

**Expected result**
Recaptcha should be shown

**Comment by nul800sebastiaan** [comment]
That's a pretty old configuration of version together there 🙈 

We highly recommend you plan an upgrade to a newer version.

In the mean time, you might want to try this package out, which looks like it should be compatible with your version combination. https://our.umbraco.com/packages/collaboration/recaptcha-field-for-umbraco-forms/ 
If that doesn't work for you then it's still possible to write your own custom fieldtype, you could even base the code on what you find in that package.

I'm going to close this issue with another recommendation to upgrade if you can so you can continue to benefits from updates and bugfixes for bot Forms and Umbraco.
