### ISSUE TITLE
Email not sent to multiple email with ; at end

### ISSUE THREAD

**Issue by yawkale** [umbraco/Umbraco.Forms.Issues#31]
Email not sent to multiple email with ; at end
Reproduction
------------
create email workflow, fill email like xxx@aaa.com;yyy@aaa.com;

when ; appears at the end workflow will not send email

### Bug summary

Email not sent to multiple email with ; at end

### Specifics
tested on forms 6.0.8 + umbraco 7.12.3

### Steps to reproduce

create email workflow, fill email like xxx@aaa.com;yyy@aaa.com;

### Expected result

2 emails sent to xxx@aaa.com and yyy@aaa.com

### Actual result
no email sent

**Comment by nul800sebastiaan** [comment]
Thanks for the report, the obvious workaround is to not have a `;` at the end of course :)

**Comment by warrenbuckley** [comment]
Connects https://github.com/umbraco/Forms/pull/225
