### ISSUE TITLE
Cannot remove Umbraco Forms fields in 8.6.0-rc

### ISSUE THREAD

**Issue by TheMirzai** [umbraco/Umbraco.Forms.Issues#317]
Not 100% sure this should be posted here or the Umbraco Forms repo.

Whenever I try to remove a field created in Umbraco Forms, I instead get redirected back to the main Content node, and the field has not been deleted.

## Umbraco version

Happening against the 8.6.0-rc package

Reproduction
------------

- Fresh VS 2019 (Empty) project, standard install of Umbraco 8.5.5 & Umbraco Forms 8.3.2
- Create Form in CMS, add test field and can then delete the same test field.
- Upgrade Umbraco to 8.6.0-rc
- From the same form, add test field, then try to delete. Get redirected to Content tree, a test field is still on the form.

Nothing is appearing in console or network that would explain this - have replicated twice to make sure it's not me! Let me know if you have any questions, thanks.

**Comment by nul800sebastiaan** [comment]
Just as an update: issue has been identified as a Forms issue, so I've move this one to the Forms tracker instead. Working on a fix.

**Comment by nul800sebastiaan** [comment]
Alright, this is fixed for the upcoming Forms 8.4.0 but if need be you can update this manually as well:

In `App_Plugins\UmbracoForms\Directives\umb-forms-designer-new.html` modify the following lines:

- Line 31 change `<a href="">` to `<span>`, on line 39 change `</a>` to `</span>`.
- Line 69/77: do the same 
- Line 149/157: do the same -note: line 149 contains `ng-click=""` which can be removed, only `<span>` should remain.

In `App_Plugins\UmbracoForms\css\umbraco.forms.css` modify the following lines:

- 1163: turn `.umb-forms__actions a {` into `.umb-forms__actions a, .umb-forms__actions span {`
- 1170: turn `.umb-forms__actions a:hover {` into `.umb-forms__actions a:hover, .umb-forms__actions span:hover {`
- 1188: turn `.umb-forms__page-actions a {` into `.umb-forms__page-actions a, .umb-forms__page-actions span {`
- 1194: turn `.umb-forms__page-actions a:hover {` into `.umb-forms__page-actions a:hover, .umb-forms__page-actions span:hover {`

Finally, go into your `ClientDependency.config` file and bump the version so your browser will pick up the changes on next reload.
