### ISSUE TITLE
Disable automatic Data Consent?

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#318]
I've noticed that Forms always adds a "DataConsent"-question to new forms and reading the docs indicates that this is not something that we can control?
![image](https://user-images.githubusercontent.com/1782524/78118081-c1e72c00-7406-11ea-8708-9658de238cea.png)

While this is a "nice" thing to do I would hope that there would be a way to turn this off? 

Some use cases where one probably don't want this:

- I've created a custom Template-Form (json-file) with a different consent-setup compared to this.
- I need to validate the consent in another way thay this or with a another type of question
- Forms are shown to logged in visitors that has already made a consent during registration.

So my question is: How can I turn this off? And if I can't, would you consider adding this "feature" =D

**Comment by nul800sebastiaan** [comment]
Sure, we'll have a chat about it at HQ. Might take a bit of time.. holiday season has already kicked in over here!

**Comment by enkelmedia** [comment]
But to be clear, as of today there is no way to disable this?

**Comment by nul800sebastiaan** [comment]
Not that I know of!

**Comment by enkelmedia** [comment]
Nope, not at the moment, seems like its added in the controller it self.

Until then, I'll continue to post my hack-solutions if any one else need them.

A workaround is to create a interceptor, by creating a file ie "formsInterceptor.js" and making sure that this is loaded using a package.manifest-file,

```javascript
angular.module('umbraco.services').config([
   '$httpProvider', function ($httpProvider) {
       $httpProvider.interceptors.push(['$q','$injector', function ($q, $injector) {
           return {
               
               'response': function(response) {

                   // Overrides the response from the API-endpoint that created the Forms, 
                   // The controller is hardcoded to always append the "data consent"-field as the last field in the collection
                   // So by running pop() on the field-collection we'll remove the last field.

                   // Does the returned content match the endpoint for GetScaffoldWithWorkflows?
                   if (response.config.url.indexOf('backoffice/UmbracoForms/Form/GetScaffoldWithWorkflows?template=') > -1) {
                       response.data.pages[0].fieldSets[0].containers[0].fields.pop();
                   }

                   return response;
               }               
           };
       }]);
   }]);
```

Disclaimer: Works on my machine on Umbraco Forms 8.4.0 with the default templates in Umbraco Forms.

**Comment by warrenbuckley** [comment]
Fixed in PR https://github.com/umbraco/Forms/pull/418 and due for release in 8.7.0

**Comment by AndyButland** [comment]
This will be added to documentation of course, but for reference also against the issue, this feature can be disabled by adding the following configuration value to `UmbracoForms.config`.:

```
<setting key="DisableAutomaticAdditionOfDataConsentField" value="True" />
```

If this value is `False` (the default from `8.7.0`) or the key is missing, the consent field will continue to be added by default.  Only if the key is present and the value is `True` will it not be added to new forms.
