### ISSUE TITLE
Glaring typos on settings screen

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Forms.Issues#32]
Originally reported here: https://issues.umbraco.org/issue/CON-1500

Too many to list here :)

As stated on the original issue it would be so nice to be able to edit localized versions of these labels just as we can with the main Umbraco UI.

**Comment by warrenbuckley** [comment]
Connects https://github.com/umbraco/Forms/pull/214

**Comment by warrenbuckley** [comment]
@greystate yes we need to go through the entire UI and make it localizable but for now the typos have been fixed up

**Comment by greystate** [comment]
💯 🥇 🙌 

Thanks Warren! :)
