### ISSUE TITLE
Changes to improve "magic strings" usage in 7.4.0/8.4.0 don't work as expected

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Forms.Issues#321]
The comments after the release of 8.4.0 can be found here for more info on what is not working;

https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-608346198

**Comment by nul800sebastiaan** [comment]
This issue might be related: https://github.com/umbraco/Umbraco.Forms.Issues/issues/320

**Comment by nul800sebastiaan** [comment]
Alright, this is what the team has tested, following [the docs on Our](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Magic-Strings/#parsing-umbraco-form-field-items)

- form fields as a label, description or default value
  - things like `[$pageTitle]` to get the page title property from the current document

**Comment by nul800sebastiaan** [comment]
Alright, this is what the team has tested for a v8 fix, following [the docs on Our](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Magic-Strings/#parsing-umbraco-form-field-items)

- form fields as a label, description or default value
  - things like `[#pageTitle]` and `[$pageTitle]` to get the page title property from the current document or get it recursively
  - items from the request collection like `[@Url]` and `[@Http_User_Agent]`
  - items from the session and cookies, like `[%dismissAvatar]` and `[%test]` (a session item)
- workflow settings - on the workflow `Send email with template (Razor)`
  - In the subject of the email - things like `[#pageTitle]` and `[$pageTitle]` to get the page title property from the current document or get it recursively
  - In the subject of the email - items from the request collection like `[@Url]` and `[@Http_User_Agent]`
  - In the subject of the email - items from the session and cookies, like `[%dismissAvatar]` and `[%test]` (a session item)
  - In the "email receiver" and "email from" fields - items from the form, importantly: 
    - `{email}` being the name of the email field (the caption, not the alias), as it was before: lower cased, spaces and non alphanumeric characters removed
    - and `{emailAddress}`, being the alias of the email field, it matches on exactly the casing of the alias

In the bin folder for this zip are updated dlls that can be dropped into an existing Forms 8.4.0 install if you need a solution right now. 
[UmbracoForms.Files.8.4.0-alpha.20200421.3.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4510043/UmbracoForms.Files.8.4.0-alpha.20200421.3.zip)

We're still doing some more tests and making sure v7 of Forms works the same, but there's no test dlls for that available.

**Comment by TimGeyssens** [comment]
follow

**Comment by nul800sebastiaan** [comment]
A v7 build has now been made as well with the same changes and team has tested the same scenarios as above. Again, the dlls of the attached file can be copied into a site with Forms 7.4.0 installed to get the working functionality. 

[UmbracoForms.Files.7.4.0-ci-20200422.4.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4515013/UmbracoForms.Files.7.4.0-ci-20200422.4.zip)

We're hoping to get final releases out next week.

**Comment by TimGeyssens** [comment]
Nice, thanks for the testing and details! Just to be 100% sure, it is possible to use the alias now and it will fall back to the old method (of the name with some rules)...so upgrading would be fine...

**Comment by nul800sebastiaan** [comment]
Correct.

**Comment by nul800sebastiaan** [comment]
Testing has concluded, issue is fixed for 7.4.1/8.4.1 due for release as soon as possible (tentatively next week).

**Comment by TimGeyssens** [comment]
Sweet!

**Comment by ronaldbarendse** [comment]
> * In the "email receiver" and "email from" fields - items from the form, importantly:
>     * `{email}` being the name of the email field (the caption, not the alias), as it was before: lower cased, spaces and non alphanumeric characters removed
>     * and `{emailAddress}`, being the alias of the email field, it matches on exactly the casing of the alias

Just to be totally clear: the values are replaced based on the caption before the alias, right?

In any case, this will still result in unwanted behaviour, as can be demonstrated with this simple example:
| Caption       | Caption (cleaned) | Alias        | Value            |
|---------------|-------------------|--------------|------------------|
| Email address | emailaddress      | email        | test@example.com |
| Email         | email             | emailaddress |  _null_           |

Using `{email}` and `{emailaddress}` will replace values based on the caption (_null_ and test@example.com respectively), but whenever an editor changes both captions, would result in replacing based on the alias, swapping the values! This is especially bad when workflows are configured using the aliasses and the editor (unknowingly) changes a caption so it overlaps with the configured alias. This could even result in broken workflows (as the field isn't required anymore or contains an invalid value type) or even sending emails to the wrong address!

I've commented on the original issue multiple times to make this configurable as a setting, as that seems to be the only way to correctly fix this issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-481703810 and https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-524289128.

**Comment by nul800sebastiaan** [comment]
@ronaldbarendse Have you tested this and this with the attached build and this is the result? That is not my experience.
