### ISSUE TITLE
Email workflow, make it possible to set sender name & title/intro from workflow

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#323]
Now only email is possible, adding name would be ace!

To make the default template email workflow even more usefull (and reusable) would be great if you could set the title/intro as workflow settings...

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request. We're working on fixing bugs for the foreseeable future, but we'll put this on the list for when we are ready to work on new fieldtypes. 

For now, you can implement your own custom fieldtypes to achieve this functionality. https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Extending/Adding-a-Fieldtype

**Comment by AndyButland** [comment]
We are adding a header and footer rich text field to the email workflow as part of [issue 853](https://github.com/umbraco/Umbraco.Forms.Issues/issues/853), planned for the next minor releases of Forms 10+, which I believe covers this feature request too.

As such will close this as now a duplicate.
