### ISSUE TITLE
Make it possible to swap out jquery

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#330]
Seems like jquery is a dependency you can't get away with currently, would be nice if core moved to vanilla js and people have the option to plugin something else for client side validation

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request. We're mainly working on fixing bugs for the foreseeable future, but we'll put this on the list for when we are ready to work on new validation options.

**Comment by Matthew-Wise** [comment]
Its a bit old but has been achieved - https://github.com/elglogins/Umbraco-Forms-Without-Jquery

**Comment by TimGeyssens** [comment]
Ow nice!

**Comment by AndyButland** [comment]
Yes, I thought I remembered seeing this released last year... will close now.
