### ISSUE TITLE
Template email workflow, make it possible to set title/intro from workflow

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#333]
To make the default template email workflow even more usefull (and reusable) would be great if you could set the title/intro as workflow settings...

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request. We're mainly working on fixing bugs for the foreseeable future, but we'll put this on the list for when we are ready to work on workflow updates.

For now, you can implement your own custom workflows to achieve this functionality. https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype

Additionally, Perplex has made a plugin for Forms that does this

**Comment by nul800sebastiaan** [comment]
Merged with https://github.com/umbraco/Umbraco.Forms.Issues/issues/323

**Comment by TimGeyssens** [comment]
Yup I know about the plugin but that is only for umbraco v7 sites...
