### ISSUE TITLE
Make it possible to remove workflows

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#334]
Now you can only put them in non active state

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request. We're working on fixing bugs for the foreseeable future, but we'll put this on the list for when we are ready to work on new workflows.

For now, you can implement your own custom workflows to achieve this functionality. our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype

**Comment by ronaldbarendse** [comment]
It's possible to remove workflows, but only from the `configure workflow` dialog:

![Workflows dialog](https://user-images.githubusercontent.com/1051287/90633917-33ddd780-e227-11ea-988b-0f9dabf45e8d.png)

There are some issues with this dialog though:
- The icons aren't square;
- Sorting only works on the icon (and that's only visible by the move cursor on hover);
- The workflow gets edited after cancelling the sorting (start dragging, but not change the order);

The 'Add new page' button is also displayed below the workflows panel, which is a little strange (Umbraco Forms 8.5.1).

**Comment by TimGeyssens** [comment]
Ah cool, didn't spot that, yeah can use some UI/UX love

**Comment by warrenbuckley** [comment]
Fixed in PR
https://github.com/umbraco/Forms/pull/558

Due for release in 8.8.0
