### ISSUE TITLE
Make it clear in the UI that a workflow is inactive

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#335]
Currently all workflows are "green" in the ui, would make sense that non active ones are greyed out

---
_This item has been added to our backlog [AB#6217](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6217)_

**Comment by nul800sebastiaan** [comment]
Makes sense to me, we'll see if we have time to update this some time in the next few weeks.

**Comment by AndyButland** [comment]
Looks like this was duplicated in #464 which has a fix planned for the next minor release, and so has been closed and tagged.  So I'll update this issueto match.
