### ISSUE TITLE
Make it possible to select which fields/columns are visible in the records viewer

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#336]
Now I don't know which ones are shown...and you can not add additional ones it seems

**Comment by nul800sebastiaan** [comment]
Thanks for your feature request. We're mainly working on fixing bugs for the foreseeable future, but we'll put this on the list for when we are ready to work on the entries viewer.

**Comment by buskol** [comment]
Also hope that this feature will be in a future update ;-)

**Comment by AndyButland** [comment]
This will be available in the next minor releases of Forms 10+.  We'll be adding a section under the form settings to allow you to select the fields you want to display for that form on the entries screen, similar to how list view form fields are selected in the CMS.
