### ISSUE TITLE
Umbraco Forms Validation

### ISSUE THREAD

**Issue by thomasknielsen** [umbraco/Umbraco.Forms.Issues#340]
We are experiencing that Umbraco forms does not save when adding validation of eg. e-mail or number in a field.

Reproduction
------------
### Bug summary

When adding validation on a field and saves the field. The validation is missing when loading the field editor again.

### Steps to reproduce
- Create a form
- Create a field
- Add validation for e-mail
- Save the field
- Click the settings cog again
- See that nothing is saved

### Expected result
I would expect the validation was saved

### Actual result
The validation is not saved

SETUP:
- Umbraco Cloud
- Umbraco 8.4.2
- Umbraco Forms 8.3.2

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates #276 - fixed in 8.4.0 (you might want to wait a little before upgrading since we have a bug in 8.4.0 that is fixed for the upcoming 8.4.1 - https://github.com/umbraco/Umbraco.Forms.Issues/issues/321)
