### ISSUE TITLE
Can't see that you can sorting groups

### ISSUE THREAD

**Issue by thomasknielsen** [umbraco/Umbraco.Forms.Issues#341]
In Umbraco 8 it is no longer possible to sort groups in a Form.

In Umbraco 7 it was possible when clicking the reorder, you could sort both fields, groups and pages.
Now it is only possible to sort fields and pages.

Don't know if it is a feature or a bug though.

---
_This item has been added to our backlog [AB#6333](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6333)_

**Comment by nul800sebastiaan** [comment]
Ah well funnily enough it is still possible if you click pretty far to the left on the groups:

![341](https://user-images.githubusercontent.com/304656/80081991-f8bae880-8553-11ea-856c-3c69b6ffb931.gif)

I think it's just that the icon is there, but it is white so you can't see it. A bug we should be able to fix pretty easily! 👍

**Comment by RobinAssidi** [comment]
I actually just discovered when you hover over that element you can see that the icon is there but it's colored as white:
[https://gyazo.com/16b804290978354fae6fbcf4b1435d13](url)

as you can see in the css: 

.umb-forms__fieldset-sort-handle {
    color: #ffffff; 
}

if you remove the color formatting you can see the icon again :)

**Comment by warrenbuckley** [comment]
Due in release 8.7.0
