### ISSUE TITLE
Magic strings are not working

### ISSUE THREAD

**Issue by thomasknielsen** [umbraco/Umbraco.Forms.Issues#347]
After the latest update of Umbraco Forms, we have an issue with "magic strings" aka. [#alias] are getting saved in fields.

This have been working up until now.

--
Umbraco 8.6.1
Forms 8.4.0
Deploy 3.4.3

**Comment by thomasknielsen** [comment]
@nul800sebastiaan I would mark this as critical as this functionality is used on a lot of our clients

**Comment by CTRPaul** [comment]
@thomasknielsen this is listed as fixed in forms 8.4.1 See here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/321

:-)

**Comment by thomasknielsen** [comment]
perfect, you can close the case :)
