### ISSUE TITLE
Unable to pick xslt files when using the "Send xslt transformed email" workflow

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Forms.Issues#348]
When using the "Send xslt transformed email" workflow you have the option to select an xslt file. But when you try to select a file and submit nothing happens except there is a JS error in the browser console.

![image](https://user-images.githubusercontent.com/42831978/80718720-caf91500-8afa-11ea-855c-2e9bab5ddbdb.png)

```
angular.min.js?cdv=1667401606:63 TypeError: Cannot read property 'value' of undefined
    at populateFile (umbraco.forms.js?cdv=1667401606:262)
    at Object.submit (umbraco.forms.js?cdv=1667401606:240)
    at a.scope.submitForm (umbraco.directives.js?cdv=1667401606:6569)
    at angular.min.js?cdv=1667401606:74
    at Object.d.<computed> [as action] (angular.min.js?cdv=1667401606:44)
    at angular.min.js?cdv=1667401606:74
    at angular-mobile.js?cdv=1667401606:270
    at Object.$eval (angular.min.js?cdv=1667401606:92)
    at Object.$apply (angular.min.js?cdv=1667401606:92)
    at HTMLButtonElement.<anonymous> (angular-mobile.js?cdv=1667401606:269)
```

Reproduction
------------

### Specifics
Tested on v7 and v8.

**v8**
- Umbraco 8.6.1
- Forms 8.4.1

**v7**
- Umbraco 7.15.4
- Forms 7.4.1

**Browser**
Chrome: Version 80.0.3987.163 (Official Build) (64-bit)

### Steps to reproduce

1. Create a form
2. Select the "Send xslt transformed email" workflow
3. Try to select a xslt file at the bottom
![image](https://user-images.githubusercontent.com/42831978/80719493-d731a200-8afb-11ea-900a-b015d896ebde.png)

### Expected result

The file path to be saved successfully with the workflow.

### Actual result

Nothing happens except an error so the workflow is not usable without workarounds.

---
_This item has been added to our backlog [AB#6636](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6636)_

**Comment by pmpontes** [comment]
I can confirm this issue. I've already encountered it twice, once with Umbraco CMS/Forms 7.15.5/7.4.1  and on 8.3.0/8.2.1.

**Comment by dangander** [comment]
I can confirm too - it actually happens with EVERY use of the File settingtype, even those in custom workflowtypes - I just raised #375 with some more details

**Comment by skttl** [comment]
I've got this in Forms 8.6.0 too

**Comment by skttl** [comment]
And 8.6.1

**Comment by skttl** [comment]
This workaround fixed it for me
![image](https://user-images.githubusercontent.com/3726467/108828973-dc4e6900-75c7-11eb-8a21-450de3c5ada7.png)

But #477 is still bugging for me in 8.6.1

**Comment by warrenbuckley** [comment]
Fixed in PR https://github.com/umbraco/Forms/pull/417
Due for release in 8.7.0

**Comment by JoakimValtech** [comment]
> This workaround fixed it for me ![image](https://user-images.githubusercontent.com/3726467/108828973-dc4e6900-75c7-11eb-8a21-450de3c5ada7.png)
> 
> But #477 is still bugging for me in 8.6.1

Thank you! You saved my day! You're a hero
