### ISSUE TITLE
Workflow Fieldmapper not saving last item

### ISSUE THREAD

**Issue by kirziga** [umbraco/Umbraco.Forms.Issues#350]
Hi, the Fieldmapper datatype isn't saving the last item, only workaround would be to set the last item as a dummy to be ignored when saving.

![image](https://user-images.githubusercontent.com/64761227/80932026-0001b200-8df0-11ea-86bd-4d01e2ed7b4c.png)

I am using UmbracoForms v8.4.1 with UmbracoCms v8.6.1 (the latest as of now).

---
_This item has been added to our backlog [AB#6751](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6751)_

**Comment by thenexus00** [comment]
Any ETA on this fix?
I should add your workaround from another issue:

"For now the workaround is to add a new blank mapping after the last one and then save."

Another variation on this issue...
If you Add a mapping and select the "Form value" first and then add the Alias and hit save the Alias will not save. It will only save if you do the Alias first, then the form value.

**Comment by thenexus00** [comment]
8.5.2 Stil has the issue that if you create a field mapping with default value it does not save.

**Comment by AndyButland** [comment]
This has been resolved and a fix provided in the next minor release.
