### ISSUE TITLE
Insert Test Form into Rich Text Editor Umbraco Forms 7.4.1

### ISSUE THREAD

**Issue by Kinaetron** [umbraco/Umbraco.Forms.Issues#355]
I updated Umbraco Forms manually to 7.4.1 and tried to refer to the form again RTE and got the exact issue I reported in this ticket 

https://github.com/umbraco/Umbraco.Forms.Issues/issues/354#issue-616620035

**Comment by nul800sebastiaan** [comment]
Let's keep the conversation on issue #354 instead of starting a new thread about the same thing. 👍
