### ISSUE TITLE
Marking a field as Sensitive data doesn't save to the database.

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco.Forms.Issues#356]
We recently upgraded Umbraco 8.1.4 and Forms 8.2.0 to U8.6.1 and UF8.4.0

Preupgrade, we had a field on a form marked as Sensitive data and everything was fine. After the upgrade, if any data was added to the sensitive data field, it's not saved in the database. 

Support ticket Id: #51768

Reproduction
------------

### Specifics

Umbraco 8.6.1
Forms 8.4.0

### Steps to reproduce
Create a form and add a field, such as a short string. Complete the form and you will see that the data is stored in the backoffice. Now mark this same field as sensitive data. Complete the form again and then check the backoffice, you will see no data is visible, it doesn't matter if you are an admin with permission to see sensitive data or not. If you check the database table, you will see the data hasn't been saved at all. It's gone. 

If you now change that field back to non-sensitive, fill out the form again, your data is now saved as expected. 

### Expected result

The data should be saved in to the database and visible in the backoffice. 

### Actual result

No data saved in the database table or visible in the backoffice.

---
_This item has been added to our backlog [AB#6694](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6694)_

**Comment by aaron-sadler-activeis** [comment]
I am also having this issue!

**Comment by nul800sebastiaan** [comment]
Yikes! We're looking into it.

**Comment by OwainWilliams** [comment]
Great, thanks @nul800sebastiaan - a bit of a GDPR issue if we can't mark things as sensitive. I sent a screen capture with my support ticket if you need help to reproduce. Didn't want to share it on github as it was a live site.

**Comment by aaron-sadler-activeis** [comment]
As above, I have a ticket worked through with support yesterday with Derek. (#51863) This also contains screenshots and examples.

**Comment by nul800sebastiaan** [comment]
Alright, just got a fix for this from my colleagues:

[UmbracoForms.Files.8.4.2-alpha.20200515.7.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4634120/UmbracoForms.Files.8.4.2-alpha.20200515.7.zip)

It's enough to update the dlls, that's where the fix is located. We do apologize for the inconvenience!

**Comment by rickbutterfield** [comment]
I know this issue is closed (so I'm happy to log this somewhere else) but thought it might be worth noting that the DLLs fix also resolves an issue where sensitive fields weren't available in a custom workflow `Record`.

**Comment by nul800sebastiaan** [comment]
I have an updated version available, as @aaron-sadler-activeis pointed out that the previous version would not allow him to update any fields from his own custom workflows.

So the rules now are as you would expect:

- If the user sets `Include sensitive data` to `true` in the workflow settings then that workflow will receive sensitive data field and they can be updated from your custom workflow code.
- If the user set `Include sensitive data` to `false` in the workflow settings then that workflow will not receive sensitive data fields and they can not be updated from that workflow. The values will be saved on the record as-is. 

[UmbracoForms.Files.8.4.2-alpha.20200525.16.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4677305/UmbracoForms.Files.8.4.2-alpha.20200525.16.zip)

@aaron-sadler-activeis we'd love to hear back if this now fully works again as you expected!

**Comment by nul800sebastiaan** [comment]
@rickbutterfield that's basically the same issue, we accidentally broke that part. :(

**Comment by AaronSadlerUK** [comment]
> I have an updated version available, as @aaron-sadler-activeis pointed out that the previous version would not allow him to update any fields from his own custom workflows.
> 
> So the rules now are as you would expect:
> 
> * If the user sets `Include sensitive data` to `true` in the workflow settings then that workflow will receive sensitive data field and they can be updated from your custom workflow code.
> * If the user set `Include sensitive data` to `false` in the workflow settings then that workflow will not receive sensitive data fields and they can not be updated from that workflow. The values will be saved on the record as-is.
> 
> [UmbracoForms.Files.8.4.2-alpha.20200525.16.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4677305/UmbracoForms.Files.8.4.2-alpha.20200525.16.zip)
> 
> @aaron-sadler-activeis we'd love to hear back if this now fully works again as you expected!

I can confirm this is working for my workflow now!

Many thanks!

**Comment by Emetico** [comment]
@nul800sebastiaan i spoke to Darek from the support about this. He suggested i let you know that this fix only works for new entries. For the older entries, the sensitive data does not show, ill guess its not saved in the database.

**Comment by nul800sebastiaan** [comment]
@Emetico Correct, before this fix the data was never saved 😢
