### ISSUE TITLE
Recaptcha v2 valid response not recognized

### ISSUE THREAD

**Issue by shrthnd** [umbraco/Umbraco.Forms.Issues#36]
Recaptcha v2 field response is not recognized on submit (the page reloads and the form data is not saved.)

Reproduction
------------

### Specifics
Running a fresh installation of Umbraco 7.12.3 and Umbraco Forms 7.0.5, both installed into an empty project with Nuget. Tested with both IIS and IIS Express

### Steps to reproduce

1. Create an empty .NET application, install the latest release of Umbraco and Umbraco Forms via nuget. 
2. Add valid API credentials to umbracoForms.config, and add a recaptcha v2 to the sample form. 
3. Add the sample form to a page with the Umbraco Forms macro
4. Navigate to the page with the embedded form, fill out any required fields, and complete the recaptcha field. 
5. Press submit

### Expected result

The form should be submitted and saved when the recaptcha checkbox is checked (and the hidden textarea containing the postback value is present.) 

### Actual result

A valid captcha response is recognized in the UI (green checkbox), and an apparently valid token is added to the hidden textarea (#g-recaptcha-response). But, the form is not submitted/saved, and the recaptcha field prompts you to revalidate.

**Comment by craigs100** [comment]
Having similar trouble with Forms 7.0.4 in a 7.12.3 site in that it doesn't have client side validation out of the box. Refers: https://issues.umbraco.org/issue/CON-1552. It needs to integrate into the UF validation schema as that is it's primary purpose. Client wants it in but I may have to tell them its not possible using UF.

**Comment by nul800sebastiaan** [comment]
@shrthnd  Unfortunately I've not been able to reproduce this problem, I installed the default Umbraco starter kit, Forms, added recaptcha to the contact form and everything works just fine. Let me know if you have other steps to replicate.
