### ISSUE TITLE
Deleting questions in Forms redirects to Content

### ISSUE THREAD

**Issue by etharion** [umbraco/Umbraco.Forms.Issues#366]
Deleting questions results in a redirect to Content, which means none of the changes made on the form is saved. So at the moment we cant remove fields.

## Umbraco version
CMS: 8.6.0+
Forms: 8.3.1+

Reproduction
------------
Have a solution with Forms installed and a form with any questions.

### Steps to reproduce

1. Go to your form
2. Delete any question

### Expected result
Expected to stay on the forms page with the changes I've made.

### Actual result
Instead, gets redirected to Content.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @etharion, this is a problem in Forms which can be fixed by upgrading to the latest version, 8.4.1: https://github.com/umbraco/Umbraco.Forms.Issues/issues/317

**Comment by etharion** [comment]
Hi @nul800sebastiaan 

Thanks for replying. We are still experiencing this on 8.4.1 of Forms with Umbraco 8.6.x.

I have tried to mix versions abit and to be sure I'm not doing something wrong, I've checked version number on .dll's.
Umbraco: 8.5.5 | Forms: 8.3.1 - ✔
Umbraco: 8.5.5 | Forms: 8.4.1 - ✔
Umbraco: 8.6.2 | Forms: 8.3.1 - ✖
Umbraco: 8.6.2 | Forms: 8.4.1 - ✖

8.6 of Umbraco seems to be the problem for me at least.

**Comment by nul800sebastiaan** [comment]
@etharion I fear there might be something wrong with your upgrade process then, or you may have installed a package that might conflict? 

On a clean install of Umbraco 8.6.2 and Forms 8.4.1 this is the result for me:

![Forms366](https://user-images.githubusercontent.com/304656/84122165-4e7e1e00-aa38-11ea-9d8d-31c905f6b804.gif)

**Comment by etharion** [comment]
Alright. I might need to do some more testing then.

**Comment by runegronkjaer** [comment]
An update on this one. I'm a colleague of @etharion.
We ended up uninstalling Umbraco forms with nuget, deleting alle the files manually and then reinstalling the nuget package. That worked and a few files where changed. Now everything seems to work again.
