### ISSUE TITLE
Make it possible to navigate to the form entries/editor from the form picker property

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#368]
Especially in a large site with some forms it would be nice if you could navigate from the form picker property to the form entries or form editor (if your user has access).

Now you have to swith to the forms section and look for the form manually...

**Comment by nul800sebastiaan** [comment]
Thanks @TimGeyssens - I am not sure what the purpose is? I understand you're working on content and then want to check what the form/entries look like? A use case scenario would be good for my understanding.

**Comment by TimGeyssens** [comment]
Sure, imagine you have a rather bit site with 50-60 forms...

The forms tree is just a flat layout...

So now if you want to check the design or entries of a certain form that is used on the site you always need to go the the forms section and manually locate that for that is being used... if folks aren't that good in naming you could have a couple with the same name...

To avoid confusion and a faster way of getting to form designer/entries from the content page you are own, a simple update to the form picker would be nice... (2 extra options depending on your user permissions, edit form, view form entries)

**Comment by nul800sebastiaan** [comment]
Sure, seems like a great idea! It's not currently something we can actively pick up, but we'll put it on the list of ideas to have a look at in the future! 👍

**Comment by TimGeyssens** [comment]
Yes, that is what I was happing to add... for content apps, yes I made one for a custom form tool https://24days.in/umbraco-cms/2018/content-apps-gold-rush/

**Comment by warrenbuckley** [comment]
Due for 8.7.0 release
