### ISSUE TITLE
DefaultStoreRecordsLocally is not available as a configuration option

### ISSUE THREAD

**Issue by yawkale** [umbraco/Umbraco.Forms.Issues#369]
Reproduction
------------

Add DefaultStoreRecordsLocally with value False and create new form, setting doen't apply for StoreRecordsLocally  setting

### Expected result

StoreRecordsLocally set to value from config like all default values

### Actual result

StoreRecordsLocally  always true

**Comment by nul800sebastiaan** [comment]
I am not familiar with this feature @yawkale - can you please explain what you're trying to achieve and where I can find `DefaultStoreRecordsLocally` please?

**Comment by yawkale** [comment]
Umbraco Form has default values for new form - based on https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Configuration/ section Default

Looks like all properties DefaultManualApproval,DefaultDisableStylesheet and another are  popuplated by default values. only Store Records is not populated. I tried define DefaultStoreRecordsLocally=False in UmbracoForms.config but it down;t affect for new forms

**Comment by nul800sebastiaan** [comment]
Ah I see what you mean now, that if not something you can set as a default for all forms at this time no, indeed. 

While we're not ready to work on this at the moment, I'll put this on the list of ideas for future features for forms.

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
