### ISSUE TITLE
Forms not loading for newly created user

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#37]
When I as an admin create a new user, who belongs to user group editors (content, media, forms), then after logging in a this editor user and opening Forms nodes, no forms nodes are shown. Also reoad nodes and clearing browser cache, doesn't seem to have effect on this.

![image](https://user-images.githubusercontent.com/2919859/47155543-47475100-d2e5-11e8-8d98-d30208951cb6.png)

If I log out as the editor and log back in as admin, go to Users > Forms Security > [the editor user] and the save the form security for this user.

After this change when I log in again as the editor user, I now have access to the forms.

Tested with Umbraco v7.12.3 and Umbraco Forms v7.0.4

**Comment by dzordzs** [comment]
Hey @bjarnef I can't seem to reproduce this, just to confirm the steps:
1. Create a form in the forms section
2. Create a user who belongs to content editor group
3. Log in as Content Editor and expand Forms section 
4. In your case no forms show up?

**Comment by bjarnef** [comment]
@dzordzs yes, exactly.

**Comment by dzordzs** [comment]
Might be one of those indeed. Happy it worked out in the end. 
I'll close this down :)

Cheers
