### ISSUE TITLE
Want: Conditional Workflows

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Forms.Issues#370]
Pretty much this: https://github.com/a2wd/UmbracoForms.ConditionalWorkflows

For example, a dropdown can be created with options for a "Customer Service" department and a "Sales Department". This extension allows an email to be sent to the relevant department conditional upon the value set in this dropdown.

**Comment by nul800sebastiaan** [comment]
Thanks! Great that there's a custom solution for it for now. 

We love your suggestion! This one is going on our ideas list for new features to implement in the future.

**Comment by TimGeyssens** [comment]
Cool! Don't think the custom one still works on v latests

**Comment by AaronSadlerUK** [comment]
Just want to add that this should include all workflows, not just email workflows.

As it would be good to send to an api etc...

**Comment by AndyButland** [comment]
Conditions on workflows will be available from the next minor releases.
