### ISSUE TITLE
Umbraco Forms Consent Warning Translations

### ISSUE THREAD

**Issue by kansubaydede** [umbraco/Umbraco.Forms.Issues#376]
Hello,

We are having problems translation the Umbraco Forms Consent Check Box's warning messages into any other language. Folks in support center could not reproduce the issue therefore could not help. We use the following setup:
Umbraco 8.6.1
Forms 8.4.0

We try to insert a warning message for a consent checkbox and here is the result we get: 

![download (1)](https://user-images.githubusercontent.com/304656/89165782-57432a00-d579-11ea-8516-70c8f281ba32.png)

Can you please help us

Best regards,
Kansu

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Hi there @kansubaydede, I see that this value is indeed hardcoded. I would recommend that for now you work around this issue by adding a regular checkbox, make it mandatory and then you can provide a localized text.

**Comment by kansubaydede** [comment]
Hello @nul800sebastiaan 
Will you be providing a solution to this problem? Until then we can of course continue with the workaround

**Comment by nul800sebastiaan** [comment]
I've flagged it up with the Forms team who will look into it, it's probably going to take a few weeks but for now we have a workaround indeed! 👍

**Comment by kansubaydede** [comment]
Thank you, we will be waiting for the solution. 
Best regards,
Kansu

**Comment by kansubaydede** [comment]
Hello There,
Is there an update to the solution here? 
Thanks a lot

**Comment by koenverburg** [comment]
Hi @nul800sebastiaan,

I'm also noticing this issue. I'm going to add a workaround for now.

In the meantime could you give me a guesstimate on when this will be resolved or picked up?
And do you know in which Umbraco Cloud version this will be included?

With kind regards,

Koen

**Comment by kansubaydede** [comment]
Hello @nul800sebastiaan 
Is there an update for this problem? Can you please update us? 
Thank you

**Comment by kansubaydede** [comment]
Hi @koenverburg 
What is the workaround that you applied? Can you please help me with that?

**Comment by koenverburg** [comment]
Hi @kansubaydede, we created a custom field type and added a translation. Hope that helps you.

**Comment by kansubaydede** [comment]
Hello @koenverburg 
We have tried that as well, but the English error message does appear with the new added translation. I can not hide it.

**Comment by mjlmo** [comment]
> 
> 
> Hello @koenverburg
> We have tried that as well, but the English error message does appear with the new added translation. I can not hide it.

Following @kansubaydede advice, I performed the tasks given on the [Forms documentation](https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype) and included a custom validation you can check out at [this gist](https://gist.github.com/mjlmo/e379389e73fd352996ea524c6762a716).

It does work! :)

**Comment by AndyButland** [comment]
Checking over this one with the latest code, I can't replicate, so believe it has been fixed at some point since forms 8.4.  Hence will close and label this as included in the upcoming 8.7.0 release.  Following that if there do still seem to be any issues, please do re-open - but, as I say, with the latest version of the code this looks to be correctly picking pu the configured custom message.

**Comment by iuliaionescu** [comment]
Hi,
I am running Umbraco Forms 8.7.0(RC) version and I get this issue as well. I don't see it in the upcoming update which will be in April neither I got it in the version I have atm. Let me know if I can help in any way to replicate it your side.
![Screenshot_3453](https://user-images.githubusercontent.com/28090656/113011301-53a48900-9182-11eb-89ed-bc0d3e620cf8.png)

**Comment by AndyButland** [comment]
Hmm... thanks for checking back on this.  Just to show to start with showing I'm not going crazy in missing this, here I'm seeing for this form:

![image](https://user-images.githubusercontent.com/1993459/113022284-bbf46a00-9184-11eb-9abf-905d778842e0.png)

This rendering:

![image](https://user-images.githubusercontent.com/1993459/113022373-d3335780-9184-11eb-881e-8b8b9a94c125.png)

Which looks right.

You should have a file on disk called `FieldType.DataConsent.cshtml` - it's in two places: `Views\Partials\Forms\Fieldtypes` and `Views\Partials\Forms\Themes\default\Fieldtypes`.  Would you mind checking those and sharing the contents please?

**Comment by iuliaionescu** [comment]
Hi Andy,

Thank you for having a look at this issue.

![Screenshot_3455](https://user-images.githubusercontent.com/28090656/113025486-ae44e180-9190-11eb-9fea-d8d7df9a6a1f.png)
![Screenshot_3456](https://user-images.githubusercontent.com/28090656/113025492-af760e80-9190-11eb-942b-ed700e5f4a66.png)

**Comment by AndyButland** [comment]
That looks fine, but I've got it now.  What I'm seeing is the client-side validation, which is working correctly.  But if I disable JavaScript or otherwise opt-out of the client-side checks, the field is validated server-side and it's that that's not picking up the custom error message and using the default one.

Looks a straightforward fix so I'll get this in for the 8.7 full release expected next week.

**Comment by iuliaionescu** [comment]
I haven't referenced the client side validation files and this is why the data consent was showing the hard coded message. Now it works perfect.
Thank you Andy for looking into this issue! :)
