### ISSUE TITLE
Default First Name, Last Name, Full Name and Email field properties

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#378]
When creating a subject line or email template to create things like "Dear xxx" or "XXX asked a question" etc it is based on that field. Since umbraco forms are so good that clients of sites as well as developers can use them they fall over when it comes to the email side still.
With default name fields you can ensure an email template can include the "Dear xxx" based on that core field.
With these the email field for example can have various things like email validation option pre-selected as well.
I know you get this from the Form template option but it would be nice to have these as options on a fresh form

**Comment by nul800sebastiaan** [comment]
@thenexus00 sorry, I don't exactly understand what your request is, what is it you want to do that you can't do now?

**Comment by thenexus00** [comment]
> @thenexus00 sorry, I don't exactly understand what your request is, what is it you want to do that you can't do now?

The critical problem with Umbraco forms is that you can not really have unique content per form. That would require a unique template in each use case and not something a client/site owner/content editor can manage.

Trying to work around this in various forms one issue is being able to do the ..

Dear Liam,
Thanks for reaching out to us...
Because other systems you have a content element to the form which can insert tags based on form fields you can do this. You can not do so in Umbraco. In some other CMS/solutions their are a variety of preset field types such as Name fields, Email Fields, Captcha field (which Umbraco forms has), and others like address etc which can often tie into system end points for person, customer, CRM person etc.

It is hard to target a field if a client builds the form and they may not name that field correctly. So if the property picker had more default defined fields so you know an email and name was known you can then work your email templates accordingly.

But if the full solution is for forms to properly have an email content editor component which can have a picker for custom field values created in the form to output and that content element be called in templates - This is the ultimate solution.

**Comment by nul800sebastiaan** [comment]
I see what you mean now, editors can give fields any name they want and they don't know the code behind the email templates so they don't consider the naming, forcing a developer to adjust the email template based on the defined fields.

For now I would advise you to help the editors by asking them to name these fields in a consistent way. 

I agree that an email template designer would be the ideal solution for this. I don't think we want to add "default" fields, they are going to be unused at the best of times and abused at the worst of times.

We currently don't have plans for adding an email template designer feature but it's a great idea I've put on the list of future features we could work on.
