### ISSUE TITLE
Update forms security page

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#380]
At the moment with Umbraco v8.6.3 (and latest changes in `v8/contrib` branch) and Umbraco Forms: 8.4.0 the security page under users section doesn't quite match the rest of the backoffice UI.

Some changes that could be done:

- Use `<umb-editor-view>`, `<umb-editor-header>`, `<umb-editor-container>`, `<umb-box-content>` and `<umb-editor-footer>` like this: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/languages/edit.html#L5
This would also ensure the header looks right and the button is at bottom.

- Use `<umb-toggle>` for the settings: Manage Forms, Manage Workflow, Manage Data Sources, Manage PreValue Sources or maybe `<umb-toggle-group>`.

- Use `<umb-checkbox>` for Has Access checkbox

- Highlight of user node work, but not for super user (it might be because super user has id -1, which I think is the same root level has).

![image](https://user-images.githubusercontent.com/2919859/89534308-00498900-d7f5-11ea-850f-07656f82fff3.png)

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef, I've put it on the list of things to look into when we're ready to work on ui/ux issues.
