### ISSUE TITLE
Use checkbox and radiobutton component

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#382]
At the moment in Umbraco Forms 8.4.0 `<umb-toggle>` directive is used a few places.
It would also be great to use `<umb-checkbox>` and `<umb-radiobutton>` components in e.g. Forms settings to make it more consistent with Umbraco core.

![image](https://user-images.githubusercontent.com/2919859/89540387-3db21480-d7fd-11ea-891c-b93e628cb941.png)

If it is a setting property (something you enable/disable) it can be considered to use `<umb-toggle>`, e.g. for "Enable Post Moderation".

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef, I've put it on the list of things to look into when we're ready to work on ui/ux issues.

**Comment by warrenbuckley** [comment]
Fixed in https://github.com/umbraco/Forms/pull/439 and due for 8.7.0 release
