### ISSUE TITLE
8.5.1 Upgrade Exception

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#387]
So I ran the NuGet upgrade from 8.4.2 to 8.5.1 and got the rather unhelpful below error message:

```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.NullReferenceException: Object reference not set to an instance of an object.
  at Umbraco.Forms.Core.Migrations.V_8_X_X.WorkflowFilesToDb.Migrate()
  at Umbraco.Forms.Core.Migrations.V_8_X_X.AddFormsDbStorage.Migrate()
  at Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate()
  at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger)
  at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger)
  at Umbraco.Forms.Core.Components.UmbracoFormsComponent.Initialize()
  at Umbraco.Core.Composing.ComponentCollection.Initialize()
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)
```

All the forms seem to work on 8.4.2, without knowing what is null this is hard to debug

---
_This item has been added to our backlog [AB#7766](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7766)_

**Comment by nul800sebastiaan** [comment]
Hey there @AaronSadlerUK! Sorry about this! We have introduced a feature in v8.5 to optionally move the form definition files on disk to the database instead, this was supposed to be disabled by default. However, it seems like the nuget upgrade actually overwrote your FormsSettings.config file. The setting `<setting key="StoreUmbracoFormsInDb" value="True" />` needs to be set to `False`. 

However, I am also worried that our migration seems to have a bug! Is there any chance you can send me the forms definitions you have on disk in the `~\App_Data\UmbracoForms\Data` as `sj at umbraco dot dk` please? We'd love to have a look and figure out what we did wrong. Thanks in advance!

**Comment by AaronSadlerUK** [comment]
Ah ok thanks for that, I was unaware of that setting!

I will send over the json files later on today.

Many thanks!

**Comment by nul800sebastiaan** [comment]
You're excused, it's a brand new setting 😉 and clearly it needs some tweaking! 😅

**Comment by nul800sebastiaan** [comment]
@AaronSadlerUK If you get a chance to send these file then that would be super helpful! 🙏 👍

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan I've just sent 3 over to you now.

Sorry about the delay!

**Comment by nul800sebastiaan** [comment]
Thanks @AaronSadlerUK - the problem was that some of your workflows were not in use, which we weren't anticipating. Put in an extra check for that for the upcoming 8.5.2 version. Thanks very much for sending the definitions, that helped a lot! 👍

**Comment by AaronSadlerUK** [comment]
Ok thanks

Happy to test & confirm the DLLs fix the problem

**Comment by nul800sebastiaan** [comment]
Cool! We have a few more little things to fix before that, I'll can add a nightly here when we get those things sorted!

**Comment by nul800sebastiaan** [comment]
Ah strange that you managed to get that release @OwainWilliams I though we delisted it from NuGet while we fix some upgrade bugs! 😱 I've now delisted 8.5.x, sorry about that! 

Of course, if you just stick with the files on disk for now you should be fine..

**Comment by OlePc** [comment]
@nul800sebastiaan Perhaps set the StoreUmbracoFormsInDb to False as default if it's not a fresh install of Forms (if that's possible?). It's a dangerous setting as it's not revertable, and not mentioned at all in the changelog [https://our.umbraco.com/packages/developer-tools/umbraco-forms/](url) .

I use azure blop storage on my current project to host and share my forms across all enviromnents. If the upgrade had moved them all to the db instead, I would be screwed!

**Comment by nul800sebastiaan** [comment]
That's exactly what we're working on, setting it to False when there is already forms definitions available.

**Comment by nul800sebastiaan** [comment]
> If the upgrade had moved them all to the db instead, I would be screwed!

Just as a note, you can go back and set this to False and the existing definitions in blob storage would be used again, however any changes made to the definitions in the mean time would not be applied any more.

**Comment by ronaldbarendse** [comment]
If you upgraded to Umbraco Forms 8.5.x (that's now unlisted from NuGet.org) and downgraded back to 8.4.x, you will get the following `BootFailedException`:
> The migration plan does not support migrating from state "1d084819-84ba-4ac7-b152-2c3d167d22bc".

This can be fixed by manually reverting the changes done by the migration:

```sql
DROP TABLE UFForms;
DROP TABLE UFWorkflows;
DROP TABLE UFPrevalueSource;
DROP TABLE UFDataSource;
UPDATE umbracoKeyValue SET [value] = '{forms-init-complete}' WHERE [key] = 'Umbraco.Core.Upgrader.State+UmbracoForms' AND [value] = '1d084819-84ba-4ac7-b152-2c3d167d22bc';
```

Just keep in mind that Forms will use the data stored in the JSON files below `~\App_Data\UmbracoForms\Data` again and this might be out-of-date: in that case, you'd need to manually copy the data from the database tables back into the JSON before running the above SQL command!

Just as a side-note: the `UFPrevalueSource` and `UFDataSource` tables are singular, while `UFForms` and `UFWorkflows` are plural. Looking at the (de-compiled) migration plan, this isn't used consistently! Umbraco uses singular table names (with the exception being `cmsTags`)...

**Comment by ronaldbarendse** [comment]
Looking at the `NullReferenceException` from `WorkflowFilesToDb.Migrate()`, this tries to migrate a workflow that's returned by the `IWorkflowStorage` but can't be found by the `IWorkflowServices` (again a singular/plural inconsistency in the naming).

This might be caused by a legacy/invalid JSON file in `~\App_Data\UmbracoForms\Data\workflows` and could be easily patched by adding a null-check and some additional logging, instead of pulling the 8.5.x versions from NuGet...

**Comment by nul800sebastiaan** [comment]
@ronaldbarendse Thanks, yes we fixed that but we have more problems around upgrades that need to be addressed.

**Comment by ronaldbarendse** [comment]
> Just keep in mind that Forms will use the data stored in the JSON files below `~\App_Data\UmbracoForms\Data` again and this might be out-of-date: in that case, you'd need to manually copy the data from the database tables back into the JSON before running the above SQL command!

So, before downgrading (e.g. using NuGet `Install-Package UmbracoForms -Version 8.4.2`) and removing/dropping the new database tables, you can add the following code into a website (e.g. into `App_Code\FormsMigrationComponent.cs`) to create/update all JSON files with the version stored in the database (on application startup):

```c#
using System.Collections.Generic;
using System.IO;
using System.Web.Hosting;
using Newtonsoft.Json;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Forms.Core.Interfaces;
using Umbraco.Forms.Core.Services;

public class FormsMigrationComposer : ComponentComposer<FormsMigrationComponent>, IUserComposer
{ }

public class FormsMigrationComponent : IComponent
{
	public void Initialize()
	{
		var basePath = HostingEnvironment.MapPath(@"~\App_Data\UmbracoForms\Data");

		foreach (var entities in new Dictionary<string, IEnumerable<IType>>
		{
			{ "forms", Current.Factory.GetInstance<IFormService>().Get() },
			{ "workflows", Current.Factory.GetInstance<IWorkflowServices>().Get() },
			{ "prevaluesources", Current.Factory.GetInstance<IPrevalueSourceService>().Get() },
			{ "datasources", Current.Factory.GetInstance<IDataSourceService>().Get() }
		})
		{
			var path = Path.Combine(basePath, entities.Key);
			Directory.CreateDirectory(path);

			foreach (var entity in entities.Value)
			{
				var contents = JsonConvert.SerializeObject(entity, Formatting.Indented);
				var filePath = Path.Combine(path, Path.ChangeExtension(entity.Id.ToString(), "json"));

				File.WriteAllText(filePath, contents);
			}
		}
	}

	public void Terminate()
	{ }
}
```

Make sure to remove this code again after the downgrade, as the new services (`IFormService`, `IWorkflowServices`, `IPrevalueSourceService` and `IDataSourceService`) don't exist anymore and that will result in a compilation error 😉
