### ISSUE TITLE
7.1.3 Older submission's attachment being overwritten by newer submission's attachment if file uploaded has the same file name

### ISSUE THREAD

**Issue by sotirisf** [umbraco/Umbraco.Forms.Issues#389]
Umbraco Forms 7.1.3 on Umbraco 7.13.2 (Cloud)

Upon submission of a form that contains uploaded files, if someone uploads a file with the same file name as an older submission, then the new file seems to "overwrite" the older submission's data and the older submission points to the new file. (Verified via the back office). 

There seems to be no way to recover the older file, especially if notification emails are set up to not contain attachments (which happened in our case).

In detail:
Visitor A submits the form and uploads a file named "aaa.doc". File "aaa.doc" is available via the submissions interface on the back office.
Visitor B submits the form and also uploads a file named "aaa.doc". File "aaa.doc" is available for visitor B's submission, but now the link to file "aaa.doc" on visitor A's submission data points to the NEW "aaa.doc" file. The originally submitted file is not accessible.

**Comment by nul800sebastiaan** [comment]
Thanks, this was fixed in 7.3.0 (https://github.com/umbraco/Umbraco.Forms.Issues/issues/261), I would recommend you upgrade to the latest version.

**Comment by sotirisf** [comment]
So...this is on Umbraco Cloud, and there's no option to upgrade to 7.3.0 on my dev environment. Am I missing something?

**Comment by nul800sebastiaan** [comment]
@sotirisf That is great question! I have the option to upgrade it from the Cloud portal on my 7.15.5 site but I'm guessing you don't have the upgrade button? 

![image](https://user-images.githubusercontent.com/304656/90778286-bc7a7780-e2fc-11ea-97ae-3b3fa4508ef5.png)

I've asked the Cloud team how to handle it, of course you can upgrade manually by taking the 
`UmbracoForms.Files.7.4.1.zip` from Our and copying in the relevant files, but automated would be better!

**Comment by sotirisf** [comment]
I apologize if I'm taking this thread a bit out of scope - So I've only got the option to upgrade Umbraco from 7.13.2 to 7.15.6 and nothing else at the moment - maybe the option to upgrade Forms comes after the CMS upgrade?

**Comment by nul800sebastiaan** [comment]
No problem! Yes, I was afraid of that! I'm asking my colleagues if it's possible to do the automated upgrade, I thought it was.
