### ISSUE TITLE
Multiselect not validating properly

### ISSUE THREAD

**Issue by monkii-dev** [umbraco/Umbraco.Forms.Issues#390]
If you create a Multiple Choice field in a form and make it required it never passes the validation.

The issue seems a regression bug. The `div.check-boxes` in the file FieldType.CheckBoxList.cshtml:6 should have the class 'checkboxlist' aplied.

Reproduction
------------

### Steps to reproduce

- Create a new field of type Multiple Choice and create a few options.
- Make it mandatory
- Go to the page where you inserted the form.
- Select one of the options
- Submit

### Expected result

When I click on an option the validation should pass.

### Actual result

Validation message comes up indicating you must select one option.

**Comment by nul800sebastiaan** [comment]
What version of Forms are you using please?

**Comment by AndyButland** [comment]
I've re-tested this on the latest version (8.7.1) and not seeing any issues with mandatory check-box lists, so will close this issue,
