### ISSUE TITLE
Change the Infinite editor blade to size Medium on workflows.

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco.Forms.Issues#392]
Currently the blade that comes out from the right hand side is set as size small. This works in most cases but when working with the workflow to Save as Umbraco Content Node, the UI breaks because there isn't enough room to display some fields when working with a DocType

Example:
![image](https://user-images.githubusercontent.com/9438758/90879232-81308500-e39e-11ea-9073-0fb5a53067c5.png)

By changing the file /App_Plugins/UmbracoForms/js/umbraco.forms.js so that all instances of  `size:"small"` are changed to ` size:"medium"`, the UI works much better and there is plenty of room for all the other settings. 

![image](https://user-images.githubusercontent.com/9438758/90879640-1fbce600-e39f-11ea-93a7-06ff068c4fde.png)

It also makes the entire experience much better as everything isn't squeezed in to the small blade. 

After the update: 

![image](https://user-images.githubusercontent.com/9438758/90879573-05830800-e39f-11ea-87a9-d08a473281fb.png)

Additionally, a change to the /App_Plugins/UmbracoForms/css/umbraco.forms.css is needed to tidy up the columns and rows, on line 1950, `display: flex` needs to be removed. 

![image](https://user-images.githubusercontent.com/9438758/90883004-e4bdb100-e3a4-11ea-991c-e6ff3d3b12c8.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the help @OwainWilliams - your suggestions have been implemented for the upcoming 8.5.4 version!
