### ISSUE TITLE
Content tree missing for users added to the "Sensitive data" group 

### ISSUE THREAD

**Issue by thomasddn** [umbraco/Umbraco.Forms.Issues#394]
Reproduction
------------

### Bug summary

The content tree is missing when a user is added to the `Sensitive data` group in combination with another custom group. Adding another predefined group like `Editors` makes it work again.

Here's a summary of my test results:

Sensitive data | Editors | Custom group | Result
--------------- | ---------|-----------------|-------
Y|Y|Y|OK
Y|Y|N|OK
N|Y|Y|OK
N|N|Y|OK
Y|N|Y|BUG

A `Y` means the user has been added to this group, `OK` means the content tree is visible.

The issues only arises when using `Sensitive data` in combination with a custom group. I also tested by creating a new group with the same settings as `Sensitive data` and combining that with my custom group, but even then I could still see the content tree. 

### Specifics

Umbraco: v8.5.5
Umbraco Forms: v8.5.1

### Steps to reproduce

1. Create a custom security group with these settings
   1. Sections: Content, Media, Forms, Translation
   1. Content start node: Content root
   1. Media start node: Media root
   1. Default permissions: all, except Culture & Hostnames, Create Content Template, Permissions
   1. Granular permissions: [none]
1. Add a user to this new group and to the `Sensitive data` group only.
1. Sign in with that user.

### Expected result

The content tree should be visible.

### Actual result

Only the "Recycle Bin" node is visible. All other nodes are missing. Navigating to a node URL does open the editor for that node. E.g. browsing to `/umbraco#/content/content/edit/1100` would allow that user to edit and publish the node, even though the content tree is not visible.

`Media`, `Forms` and `Translation` nodes are visible as expected.

**Comment by nul800sebastiaan** [comment]
Hi @thomasddn and thanks for the report! This doesn't seem to have anything to do with Forms but just regular old Umbraco. I tried your steps on Umbraco 8.6.2 and couldn't reproduce, therefore I am assuming this has been fixed along the way and I would encourage you to upgrade to the latest (8.6.4 currently).

**Comment by thomasddn** [comment]
When filing this issue I wasn't entirely sure if it was related to Forms, but as the problem occurred only in combination with the `Sensitive data` group, I thought to go ahead and create the issue here.

Anyway, now that I had some spare time to install a vanilla Umbraco, I can also confirm this isn't an issue in Umbraco v8.6.4.
