### ISSUE TITLE
Extend Workflow window width

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#395]
A number of the workflow options have to work within a very constrained window width and thus hard to use. Increasing this makes a BIG difference in workflow management.

Example POST URL workflow window:

Current:
<img width="238" alt="Screen Shot 2020-08-26 at 10 43 51 am" src="https://user-images.githubusercontent.com/4312656/91242005-9b48d980-e789-11ea-8e35-478fc17c7604.png">

Example of the change (Increasing width to 840px here but it could be a percentage or even viewport width of the window)
<img width="662" alt="Screen Shot 2020-08-26 at 10 44 41 am" src="https://user-images.githubusercontent.com/4312656/91242035-aef44000-e789-11ea-9354-c322dd39e1b8.png">

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco.Forms.Issues/issues/392

**Comment by thenexus00** [comment]
Can you merge as both elements are relevent

**Comment by nul800sebastiaan** [comment]
Github doesn't have an ability to merge! 

> both elements are relevent

I am not sure what you mean.. but please leave a comment on #392 with what you think is missing from that report.
