### ISSUE TITLE
Separate option for Reply To field

### ISSUE THREAD

**Issue by beingonlinedave** [umbraco/Umbraco.Forms.Issues#396]
From a deliverability point of view it would be useful to have separate fields for From and Reply To. 

The scenario a website with Umbraco Form for customer complaints.
From a deliverability point of view it would be nice to send the email to the customer service department from one address which can be whitelisted but allow the person in customer service to simply hit reply to the email to respond to the customer.

**Comment by nul800sebastiaan** [comment]
Thanks @beingonlinedave - it's on our list of ideas to implement in the future: https://github.com/umbraco/Umbraco.Forms.Issues/issues/51

At the moment to achieve this you could implement a custom fieldtype that has the logic you are looking for.
