### ISSUE TITLE
Post to URL sensitive data issue

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#397]
When marking fields as sensitive data and setting up a post url workflow I am getting the following errors in the log:

> Workflow {WorkflowName}: The field mapping with alias, {FieldMappingAlias}, did not match any record fields. This is probably caused by the record field being marked as sensitive and the workflow has been set not to include sensitive data

-------------

I do not want the fields showing up in emails and why they are marked sensitive.

I have ticked the "Include sensitive data" option on the workflow but this does not appear to be working.

<img width="2263" alt="Screen Shot 2020-08-28 at 10 11 30 am" src="https://user-images.githubusercontent.com/4312656/91507292-ccefab00-e917-11ea-811c-ad87adf1e2cb.png">

**Reproduction**
------------
- Create form with sensitive data. Include a "Send form to URL" workflow mapping to the sensitive data fields
- Tick include sensitive data
- Test the form and view the log

### Bug summary

- Send form to URL does not seem to allow sensitive data to map despite option being ticked
- Errors in log indicate to sensitve data and to tick option but it is ticked
- Removing sensitive data option from the field allows the workflow to fire

### Specifics

Umbraco version 8.6.2
Umbraco Forms 8.4.1

### Required result
If tick option to include sensitive data is ticked and those fields are used in mapping it should come through

**Comment by nul800sebastiaan** [comment]
Hi @thenexus00, unfortunately you're running into this issue: https://github.com/umbraco/Umbraco.Forms.Issues/issues/356

Make sure to upgrade to v8.4.2 and then try again!
