### ISSUE TITLE
Configure a default theme

### ISSUE THREAD

**Issue by thomasddn** [umbraco/Umbraco.Forms.Issues#398]
Now the default theme is `default` and this theme is used when the content editor is not explicitly picking another theme. Unless I'm overlooking this in the documentation, there is no way to use a custom theme by default. 

I'm hoping to see this functionality:

- Developers can create a custom theme (already possible)
- Developers can configure to use this custom theme as the default theme when a form is rendered, unless the content editor has explicitly chosen another theme, if any.
- If, for instance, a field type was *not* overridden in the custom theme (that was configured to be the default), it would still fallback to the theme named `default`.

---
_This item has been added to our backlog [AB#13110](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13110)_

**Comment by nul800sebastiaan** [comment]
Thanks @thomasddn! While this is not something that's on our roadmap at the moment, we'll add it to our list of ideas for consideration in the future.

**Comment by warrenbuckley** [comment]
All merged in and due in 8.8.0
