### ISSUE TITLE
Misplacement of the form field 

### ISSUE THREAD

**Issue by MaikelVeen** [umbraco/Umbraco.Forms.Issues#399]
After upgrading Umbraco Forms to the latest version 8.4.2 on Umbraco version 8.6.2 we noticed that the confirmation popup is misplaced. Please see the screenshot attacted.

![Knipsel](https://user-images.githubusercontent.com/23436704/91582050-92096980-e94f-11ea-929f-4f0766a24894.JPG)

What is weird is that on the locally running version of project this does not happen. I inspected the HTML of both sites: the local and live version.

**Local:**
`<div class="umb_confirm-action__overlay ng-scope ng-isolate-scope -left" ng-class="{ '-top': direction === 'top', '-right': direction === 'right', '-bottom': direction === 'bottom', '-left': direction === 'left'}" on-outside-click="clickCancel()" ng-if="field.deletePrompt" direction="left" on-confirm="removeField(fieldset, container, field)" on-cancel="hidePrompt(field)"> <button class="umb_confirm-action__overlay-action -confirm btn-reset" ng-click="clickConfirm()" localize="title" title="Confirm" type="button"> <i class="icon-check"></i> </button> <button class="umb_confirm-action__overlay-action -cancel btn-reset" ng-click="clickCancel()" localize="title" title="Cancel" type="button"> <i class="icon-delete"></i> </button> </div>`

**Live:**
`<div class="umb_confirm-action__overlay -left" ng-class="{ '-top': direction === 'top', '-right': direction === 'right', '-bottom': direction === 'bottom', '-left': direction === 'left'}" on-outside-click="clickCancel()" ng-if="field.deletePrompt" direction="left" on-confirm="removeField(fieldset, container, field)" on-cancel="hidePrompt(field)"> <button class="umb_confirm-action__overlay-action -confirm btn-reset" ng-click="clickConfirm()" localize="title" title="Confirm" type="button"> <i class="icon-check"></i> </button> <button class="umb_confirm-action__overlay-action -cancel btn-reset" ng-click="clickCancel()" localize="title" title="Cancel" type="button"> <i class="icon-delete"></i> </button> </div>
`

Both sites(local and live) are running from the same codebase. The difference seems to be that 'ng-scope ng-isolate-scope ' is present local but not on the live version. I do not know where this difference comes from.

We have the following app Plugins running. However I do not believe they are conflicting with the Forms.

- uSync 8.3.1
- Modelsbuilder

Reproduction
------------

### Bug summary
Misplacement of delete confirmation prompt.

### Specifics
Umbraco Forms: 8.4.2
Umbraco: 8.6.2

### Steps to reproduce
1. Open Form manager
2. Open a form
3. Try to delete a Form field

### Expected result
The delete prompt opens left of the thrashcan

### Actual result
The delete prompt opens next to form field to the left.

**Comment by nul800sebastiaan** [comment]
Hey there @MaikelVeen, in my case with 8.4.2 and Umbraco 8.6.2 it seems to work just fine: 
![image](https://user-images.githubusercontent.com/304656/91874292-52f25580-ec7a-11ea-9771-13ffe7a60a37.png)


I can only imagine that not all you files in `~/App_Plugins/UmbracoForms` are up to date. I recommend you download `UmbracoForms.Files.8.4.2.zip` from https://our.umbraco.com/packages/developer-tools/umbraco-forms/ and make sure that all files in your App_Plugins folder are the same as in the zip, that these files are included in your deploy pipeline and then on the environment where it doesn't work I'd bump the version in ClientDependency.config (just make it 1 higher) to bust the frontend cache.
