### ISSUE TITLE
Group columns is based on 12 column grid, but allows more columns to be added

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#404]
You can currently only specify how much columns you want in a group, e.g. 2 or 13:

![2 columns](https://user-images.githubusercontent.com/1051287/93207517-5e09b300-f75b-11ea-9f50-f72deb8575c6.png)
![13 columns](https://user-images.githubusercontent.com/1051287/93207485-4fbb9700-f75b-11ea-894c-f6c7692a9ef9.png)

This is exposed as a `Width` property on the `FieldsetContainerViewModel`, which is a calculated integer that uses a static 12 column grid. With 2 columns, the width of both groups is 6, but because you can add more than 12 columns, the width can be calculated as 0 (12 / 13 = 0.923... = 0). It's also not possible to configure non-equal columns, e.g. 3 - 3 - 6.

If the group column configuration would work the same as as the [grid row configuration](https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/grid-layout/configuring-the-grid-layout-datatype#row-configurations), the width doesn't have to be a calculated value, non-equal columns can be configured and the 12 column grid doesn't have to be hard-coded!

Reproduction
------------
### Specifics
Umbraco Forms 8.5.3
Umbraco 8.6.4

**Comment by nul800sebastiaan** [comment]
Sure thing, will be good to limit to 12 at some point. 👍

**Comment by AndyButland** [comment]
This has been limited to a configurable number now, defaults to 12, so will close this one and tag the release.
