### ISSUE TITLE
Exceptions when parsing multiple email addresses

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#406]
Because recursive Umbraco page fields don't work as expected (https://github.com/umbraco/Umbraco.Forms.Issues/issues/405), an additional receiver email address wasn't found and replaced with an empty value, so:

`info@example.com; [$formEmail]` resulted in `info@example.com; `, causing the following exception:
```
System.ArgumentException: The addresses parameter is an empty string.
   at System.Net.Mail.MailAddressCollection.Add(String addresses)
   at Umbraco.Forms.Core.Services.WorkflowEmailService.SendEmail(String sender, String sendTo, String subject, String body, String replyTo, IEnumerable`1 attachments)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail.Execute(Record record, RecordEventArgs e)
```

`info@example.com, [$formEmail]` resulted in `info@example.com, `, causing the following exception:
```
System.FormatException: The addresses parameter contains an email address that is invalid or not supported.
   at System.Net.Mail.DotAtomReader.ReadReverse(String data, Int32 index)
   at System.Net.Mail.MailAddressParser.ParseDomain(String data, Int32& index)
   at System.Net.Mail.MailAddressParser.ParseAddress(String data, Boolean expectMultipleAddresses, Int32& index)
   at System.Net.Mail.MailAddressParser.ParseMultipleAddresses(String data)
   at System.Net.Mail.MailAddressCollection.ParseValue(String addresses)
   at System.Net.Mail.MailAddressCollection.Add(String addresses)
   at Umbraco.Forms.Core.Services.WorkflowEmailService.SendEmail(String sender, String sendTo, String subject, String body, String replyTo, IEnumerable`1 attachments)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail.Execute(Record record, RecordEventArgs e)
```

Reproduction
------------
### Specifics
Umbraco Forms 8.5.3
Umbraco 8.6.4

### Expected result
I would expect Umbraco Forms to split the receiver/to and reply-to email address (why are there no CC and/or BCC fields?) on both `;` and `,` and only add non-empty values, so the above use-case doesn't throw unnecessary exceptions.

**Comment by nul800sebastiaan** [comment]
Alright, good point, we should strip entries that are just whitespace. We'll have to look into that at some point! 👍

**Comment by nul800sebastiaan** [comment]
Oh and there's feature requests for CC/BCC and of course the workaround for all this at the moment before we fix anything is to build a custom email workflow that supports all your needs. 💡

**Comment by ronaldbarendse** [comment]
> the workaround for all this at the moment before we fix anything is to build a custom email workflow that supports all your needs

That seems to be the only way to get around all issues indeed 😢

Would be great if the `SendRazorEmail` workflow was split up into protected virtual methods, so you can hook into the right things (e.g. adding a CC/BCC or include a plain text version using alternate views).

**Comment by ronaldbarendse** [comment]
Looking at the exception stack trace, there's a `WorkflowEmailService` that could be replaced with a custom `IWorkflowEmailService` that properly parses the `sendTo` and `replyTo` parameters... This could then also properly use the `Umbraco.Core.IEmailSender` to send the `MailMessage`, although it's a shame this interface doesn't accept parameters for CC/BCC 😉

**Comment by ronaldbarendse** [comment]
I've done some more testing and when there's no space between the semicolon seperator and addresses, it skips adding the empty address 👍 So `info@example.com;[$formEmail]` works, while `info@example.com; [$formEmail]` doesn't.

I've had the additional requirement of only adding an email address once (deduplicating), so I've created a custom `IWorkflowEmailService` and registed that in a composer using `composition.RegisterUnique<IWorkflowEmailService, WorkflowEmailService>();`:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using Umbraco.Core.Configuration.UmbracoSettings;
using Umbraco.Forms.Core.Services;

public class WorkflowEmailService : IWorkflowEmailService
{
	protected readonly IContentSection contentSection;

	public WorkflowEmailService(IContentSection contentSection)
	{
		this.contentSection = contentSection;
	}

	public void SendEmail(string sender, string sendTo, string subject, string body, string replyTo = null, IEnumerable<Attachment> attachments = null)
	{
		using (var mailMessage = new MailMessage())
		{
			mailMessage.From = new MailAddress(string.IsNullOrWhiteSpace(sender) ? this.contentSection.NotificationEmailAddress : sender);

			if (!string.IsNullOrWhiteSpace(sendTo))
			{
				foreach (var item in this.ParseMailAddresses(sendTo))
				{
					mailMessage.To.Add(item);
				}
			}

			mailMessage.Subject = subject;

			mailMessage.IsBodyHtml = true;
			mailMessage.Body = body;

			if (!string.IsNullOrWhiteSpace(replyTo))
			{
				foreach (var item in this.ParseMailAddresses(replyTo))
				{
					mailMessage.ReplyToList.Add(item);
				}
			}

			if (attachments != null)
			{
				foreach (var attachment in attachments)
				{
					mailMessage.Attachments.Add(attachment);
				}
			}

			using (var smtpClient = new SmtpClient())
			{
				smtpClient.Send(mailMessage);
			}
		}
	}

	private MailAddressCollection ParseMailAddresses(string addresses)
	{
		var mailAddresses = new MailAddressCollection();

		foreach (var address in addresses.Split(new[] { ';', ',' }).Where(to => !string.IsNullOrWhiteSpace(to)))
		{
			var mailAddress = new MailAddress(address);
			if (mailAddresses.Any(m => string.Equals(m.Address, mailAddress.Address, StringComparison.OrdinalIgnoreCase)))
			{
				continue;
			}

			mailAddresses.Add(mailAddress);
		}

		return mailAddresses;
	}
}
```

I've tried using `Umbraco.Core.IEmailSender`, but that's not registered in Umbraco and after manually registering the service, it didn't send the message, so this just uses the `SmtpClient` directly...

**Comment by nul800sebastiaan** [comment]
Strange, we were already removing empty entries. I've added commas, deduplication and a check if an email address contains an `@` sign now, hope that helps. Will be available in v8.5.4.

![image](https://user-images.githubusercontent.com/304656/96121760-cb426c80-0ef0-11eb-8e76-41c3763326ee.png)

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan The `StringSplitOptions.RemoveEmptyEntries` only removes empty strings, not if the entry only contains whitespace.

Also note that the seperate values are parsed when adding it to the `MailAddressCollection` (the `To` and `ReplyToList` properties), so even though the following values are distinct, it would end up adding the same address twice: `test@example.com` and `Display name <test@example.com>`. This is why the above code checks the `Address` property of the parsed/added addresses.

And silently skipping invalid email addresses will cause hard to debug issues (no way of knowing why an address isn't added), so I would recommend skipping the check on the `@` character (and make sure to replace it with a check on empty or _whitespace_ values).

Feel free to copy the code from my previous comment, as it does all the above in the correct way (and it's already tested on a customer project).

**Comment by nul800sebastiaan** [comment]
> The StringSplitOptions.RemoveEmptyEntries only removes empty strings, not if the entry only contains whitespace.

Correct, thanks! I've ammended with an `IsNullOrWhiteSpace` check before adding emails to the list.

>Also note that the seperate values are parsed when adding it to the MailAddressCollection (the To and ReplyToList properties), so even though the following values are distinct, it would end up adding the same address twice: test@example.com and Display name <test@example.com>. This is why the above code checks the Address property of the parsed/added addresses.

Cool, good one! Little did I know you could add a display name! 🙈 

> And silently skipping invalid email addresses will cause hard to debug issues (no way of knowing why an address isn't added), so I would recommend skipping the check on the @ character (and make sure to replace it with a check on empty or whitespace values).

I've added errors to the log now when there's a non-empty invalid address (sender, send to and reply to).

![image](https://user-images.githubusercontent.com/304656/96150012-42d0c580-0f0a-11eb-8ab5-93162adf8e7a.png)


> Feel free to copy the code from my previous comment, as it does all the above in the correct way (and it's already tested on a customer project).

Thanks! I've adapted it a bit but most of it is there now! 👍

**Comment by ronaldbarendse** [comment]
I just want to quickly mention that the `IWorkflowEmailService` has changed in version 8.7 (RC), so the code from https://github.com/umbraco/Umbraco.Forms.Issues/issues/406#issuecomment-694861579 will need a slight change to implement the newly added overload that accepts a single `SendEmailArgs` parameter 👍🏻
