### ISSUE TITLE
Server side validation fails to run if you put conditions on fieldsets

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco.Forms.Issues#41]
Server side validation fails to run if you put conditions on fieldsets.

UmbracoFormsController.ValidateFormState line two needs to do this:

    var allValues = form.AllFields.ToDictionary(f => f.Id, f => String.Join(", ", model.FormState[f.Id.ToString()] ?? new object[0]));

The current use of f.Values always yields empty values, since it's a "dead" property.

**Comment by warrenbuckley** [comment]
Works as expected after some clarification/testing @bergmania

**Comment by lars-erik** [comment]
Whoops. There's a nullref exception hidden in there. Right code inc. Monday.

**Comment by lars-erik** [comment]
Replace

            var allValues = form.AllFields.ToDictionary(f => f.Id, f => String.Join(", ", model.FormState[f.Id.ToString()] ?? new object[0]));

with

            var allValues = form.AllFields.ToDictionary(f => f.Id, f => String.Join(", ", (
                model.FormState.ContainsKey(f.Id.ToString())
                ? model.FormState[f.Id.ToString()]
                : new object[0]
            ) ?? new object[0]));

**Comment by bergmania** [comment]
Hi @lars-erik,

I ended up resolving the issue in another way, instead of using the line you provided.
I don't think there is null-reference issues in the merged code.

**Comment by lars-erik** [comment]
OK. Will do some testing in production during next week, so crossing my fingers. :)
