### ISSUE TITLE
8.5.3 - RenderUmbracoFormDependencies Html Helper Extension - Typo In 'jquery.validate.unobtrusive.min.js'

### ISSUE THREAD

**Issue by DarkSummon** [umbraco/Umbraco.Forms.Issues#415]
When using the HTML helper extension method "RenderUmbracoFormDependencies", I receive a 404 due to the "jquery.validate.unobtrusive" JS rendering as ".j" instead of ".js".

Reproduction
------------

### Steps to reproduce

In a view i.e. master layout, add the following (i.e. in the head section):
`@Html.RenderUmbracoFormDependencies()`

Ensure the following reference is added and used:
`@using Umbraco.Forms.Mvc`

### Expected result

The following should render in the markup:

```
<script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.js'></script>
```

### Actual result

```
<script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.j'></script>
```
**Note:** The last JS reference ends in ".j" - this is the error.

---
_This item has been added to our backlog [AB#8728](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8728)_

**Comment by nul800sebastiaan** [comment]
Thanks, this is fixed for the upcoming 8.5.4 release.
