### ISSUE TITLE
Query about Forms 7.5 release

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#418]
Hi,

The Forms page on Our mentions that version 8.5 of Forms has fixes for a few issues with 8.4/7.4.  There are also a few issues on here tagged with 7.5 but this hasn't been released yet.

Is there a plan to release 7.5 with the bug fixes on 7.4?

**Comment by nul800sebastiaan** [comment]
That is a great question, of course we will release it but I'm not sure why it hasn't yet, I'll get back to you!

**Comment by AndyButland** [comment]
7.5 is now released (and 7.5.1 is due on Tuesday next week, which I'd suggest waiting for if you haven't already upgraded), so I'll close this one now.
