### ISSUE TITLE
Busy indicator when exporting to Excel

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#419]
When a form has many entries to export (lets say +500 entries) , it takes a while to generate the export to Excel. We've noticed that users hit the export link/button multiple times because they can't see that the export is busy generating the Excel output. This results in an error that the file is already in use.
It would be nice that there is a indicator that the Export is busy.

---
_This item has been added to our backlog [AB#12890](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12890)_

**Comment by nul800sebastiaan** [comment]
Makes sense to me! To set some expectations, we're not working on it in the foreseeable future unfortunately, but I'll put this on the list of ideas to look at in the future, thanks!

**Comment by inetzo** [comment]
Right after your reaction we've added this functionality with only a few lines (i think 5-10) of code in de angular controller and a loader element in the view. 

Now Forms finally gets some improvements, especially in the UI, isn't this something for an upcomming release @AndyButland ?
If you want we can share our lines of code.

**Comment by AndyButland** [comment]
By all means, if you are happy to share that'll certainly save me a bit of time - and can consider this for the next update.

**Comment by warrenbuckley** [comment]
The loading indicator PR fix is here https://github.com/umbraco/Forms/pull/551 and due for 8.8.0
