### ISSUE TITLE
Workflow Field layout change suggestions

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#422]
Send form to URL layout changes:

1. Url field Style changes to give the URL field more space:

.umb-property[label="Url"] .control-label {
    width: 100%;
    float: none;
}

.umb-property[label="Url"] .controls {
    margin-left: 0;
}

<img width="489" alt="url-field-layout" src="https://user-images.githubusercontent.com/4312656/95943828-94a61c80-0e32-11eb-8361-5a971a443b82.png">

2. Field Mapping layout updates:
This should give the fields Alias, Form Value and Static value more visible space so you can actually see the values you put in:

.umb-property[label="Fields"] label {
    float: none;
    width: 100%;
    margin-bottom: 20px;
}

.umb-property[label="Fields"] .controls {
    margin-left: 0;
}

<img width="469" alt="Screen Shot 2020-10-14 at 3 39 10 pm" src="https://user-images.githubusercontent.com/4312656/95944206-6aa12a00-0e33-11eb-964f-be89ab5914c2.png">

If the button is aligned to the right as well, this also looks better.

-------------

The CSS may not be exact best way to target but you can input to visually see the improvements

**Comment by nul800sebastiaan** [comment]
Thanks, it's an active wish we have, make sure to follow this issue for updates: https://github.com/umbraco/Umbraco.Forms.Issues/issues/392
