### ISSUE TITLE
Workflow: Send form to URL User and Password field auto complete issue

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#423]
Browsers try to auto populate the User and Password fields which are optional. If you do not catch it even when editing a workflow it will add these in and can cause issues if the sending location does not like that data

Reproduction
------------

Have the auto complete for domain such as login

### Expected result

Fields remain empty

### Actual result

Fields auto populated all the time if you have what the browser thinks should be auto populated for that domain

### Suggested fix

For these two fields set autocomplete off.

**Comment by nul800sebastiaan** [comment]
I assume it's fields that you've added to your form named username and password?

For now you can create a custom theme: https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Themes/

This will allow you to update any of the rendered form fields and set autocomplete to false based on certain conditions like the field name. So you'd take the default theme files and copy them into your custom theme, update `FieldType.PasswordField.cshtml` and  `FieldType.Textfield.cshtml` to include this condition.

It would be good to be able to set a boolean on form fields called "Allow autocomplete" and the default theme would use that setting on the field.

**Comment by thenexus00** [comment]
> I assume it's fields that you've added to your form named username and password?
> 
> For now you can create a custom theme: https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Themes/
> 
> This will allow you to update any of the rendered form fields and set autocomplete to false based on certain conditions like the field name. So you'd take the default theme files and copy them into your custom theme, update `FieldType.PasswordField.cshtml` and `FieldType.Textfield.cshtml` to include this condition.
> 
> It would be good to be able to set a boolean on form fields called "Allow autocomplete" and the default theme would use that setting on the field.

Hi, I am not referring to the front end.
I am referring to these fields:
<img width="519" alt="Screen Shot 2020-10-15 at 10 47 14 am" src="https://user-images.githubusercontent.com/4312656/96057084-df2ba580-0ed3-11eb-8ed0-cf331b0ea822.png">

**Comment by nul800sebastiaan** [comment]
Ah I see! Will be fixed in the upcoming 8.5.4, thanks!
