### ISSUE TITLE
Umbraco Forms Workflow Send to URL Not Working

### ISSUE THREAD

**Issue by HTDL-Andrew** [umbraco/Umbraco.Forms.Issues#424]
I've set up a workflow with the send to url option which maps a simple form to post the data to a workbooks CRM. I've checked the API using Postman and this works fine. I have also installed the Postman extension in Chrome to record the post data but nothing is sent to the API. There are no errors in the logs either.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Thanks, I am successfully able to use that workflow to trigger https://webhook.site/  so there's most likely something wrong on your receiving end.

![formss424](https://user-images.githubusercontent.com/304656/96002818-d7b7be00-0e39-11eb-9f69-a30a5bde5e5c.gif)

Unfortunately I can't be of much help with that one, but might be good to check against https://webhook.site/ what is being sent and in which format, might help you track down the problem.
