### ISSUE TITLE
Long text field -  Default Value and placeholder fields

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#427]
The Default value and placeholder fields are different positions compared to a short field.
They should be consistent?

Short field:
<img width="558" alt="Screen Shot 2020-10-15 at 11 34 31 am" src="https://user-images.githubusercontent.com/4312656/96059847-b529b180-0eda-11eb-8fe5-a44c7bb54c8b.png">

Long field:
<img width="485" alt="Screen Shot 2020-10-15 at 11 34 38 am" src="https://user-images.githubusercontent.com/4312656/96059860-b955cf00-0eda-11eb-94dd-a57723ec32a0.png">

**Comment by nul800sebastiaan** [comment]
Hmm, might have already been fixed, looks like the same order to me in Forms 8.5.3

![2020-10-15_135300](https://user-images.githubusercontent.com/304656/96119799-cb8d3880-0eed-11eb-964f-9caf05fdf97a.png)
![2020-10-15_135312](https://user-images.githubusercontent.com/304656/96119801-cb8d3880-0eed-11eb-8376-18735b173149.png)
