### ISSUE TITLE
RenderUmbracoFormDependencies has wrong script

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco.Forms.Issues#430]
The RenderUmbracoFormDependencies tries to render a 404 script: https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.j This is because it should end on .js

![image (1)](https://user-images.githubusercontent.com/11466511/96239493-11a2d480-0fa0-11eb-8348-d0906e13a6cf.png)

Happens in Forms 8.5.3

**Comment by nul800sebastiaan** [comment]
Thanks, this is fixed for the upcoming version 8.5.4 - https://github.com/umbraco/Umbraco.Forms.Issues/issues/415
