### ISSUE TITLE
Server-side validation persists with TinyMCE - regression in 8.5.4

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#441]
Using Umbraco Forms 8.5.4 and enabling TinyMCE on a textarea field, if mandatory field validation fails once it continues to fail even once you fill in the field. TinyMCE may be incidental to this; it may trigger the error only because it causes validation to happen server-side rather than client-side.

Although it's not included in the reproduction below, I also saw a validation message for one short answer field displayed as the mandatory field error for another field, even when I'd set specific custom error text for the second field.

Reproduction
------------
I've created a minimal reproduction of the problem with instructions on the steps to reproduce the error at https://github.com/sussexrick/umbraco-forms-854-regression

I was using Umbraco 8.8.1 or 8.9 and Umbraco Forms 8.5.4. This does not happen in Umbraco Forms 8.5.3. I was using Firefox Developer Edition or Google Chrome latest on Windows 10 to test.

![image](https://user-images.githubusercontent.com/1260550/97805598-f77b1e80-1c4e-11eb-8c64-f8b7301fee87.png)

**Comment by nul800sebastiaan** [comment]
Thanks @sussexrick for the detailed repro, I have reproduced and this is definitely a regression. We will fix asap!

We're reviewing a PR and have a nightly build if you need a temporary fix, it worked in tests with your example and I added some more fields as well, which worked too: [UmbracoForms.Files.8.5.4-alpha.20201103.3.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5481289/UmbracoForms.Files.8.5.4-alpha.20201103.3.zip) (you'll only need the files in the bin directory)


Would love to hear back if it also works for you!

**Comment by timeverts** [comment]
I can definately confirm that there is a validation issue in 8.5.4 that affects other fields too, like @sussexrick alluded too, as shown below

![image](https://user-images.githubusercontent.com/15150632/98192041-437ed980-1f55-11eb-9bf8-95092822fae2.png)

@nul800sebastiaan, after testing with that nightly build I can confirm that the issue seems to be resolved, as shown below:

![image](https://user-images.githubusercontent.com/15150632/98193315-d9b3ff00-1f57-11eb-9555-3466d0b5b253.png)

@nul800sebastiaan, when might we expect the 8.5.5 release?

**Comment by nul800sebastiaan** [comment]
@timeverts I hope you can test the attached build above, we're hoping to release that one next Tuesday, would be good if you can confirm it indeed helps, plus you can run this until we release a final version.

**Comment by nul800sebastiaan** [comment]
Ah I see that you wrote that you tested the build, that extra sentence was difficult to spot between the images! 😉
We'll most likely have it out by Tuesday.

**Comment by sussexrick** [comment]
@nul800sebastiaan I can confirm the nightly fixes it in my full solution, not just the repro. Thanks for fixing it.
