### ISSUE TITLE
Conditional Statements not firing

### ISSUE THREAD

**Issue by brightspectrum-da-bomb** [umbraco/Umbraco.Forms.Issues#443]
A brief description of the issue goes here.

I have  the form setup to show/hide a field when a particular country is selected but it does not fire. 

The selection field is a dropdown. One of the show/hide fields is a textbox, the other is a drop down.

The logic is as follows. Show 'states' dropdown if 'Countries' dropdown value is 'USA' or 'Canada'. Show 'region' textbox if 'Countries' dropdown value is NOT 'USA' or 'Canada' 

I am using pre-value sources to populate the countries field and the states field

I have ran through this with Dennis in tech support and he confirmed that it was an issue. This also does not seem to be the same issue as previous reports of conditional statements not firing.  

Also the scripts that Dennis in tech support used were
 ```
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.0.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
```

When using the  @Html.RenderUmbracoFormDependencies()  the scripts that get rendered are: 
 ```
<script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js'></script>
<script src='https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.js'></script>
```

I've used both and that doesn't seem to make a difference. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

My environment is - Umbraco 8.9.0 and Forms 8.5.4

Create a dropdown using prevalues for countries 
[CMS_Countries.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/5484115/CMS_Countries.txt)

Create a dropdown using prevalues for states - Set USA as default value
[CMS_States.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/5484118/CMS_States.txt)

Create a textbox for region

Set the condition for States to: Show if Countries value IS USA OR Canada

Set the condition for Region to: Show if Countries value IS NOT USA and IS NOT Canada

Add form dependencies code as referenced in Umbraco documentation

![image](https://user-images.githubusercontent.com/58373297/98042724-e6f6af80-1dd8-11eb-8aa0-6732cafd5763.png)

Run page.  

My page example - https://dev-chidozie-s-powerful-sloth.s1.umbraco.io/get-a-quote/

### Expected result

It is expected that when the page loads with the default value for Country being USA the form would be showing the State dropdown and hiding the Region textbox. When the Country value is changed to something other than USA or Canada, the State dropdown would disappear and the Region textbox would be visible. 

### Actual result

Nothing happens - The State dropdown does not even show by default (the dropdown in the screenshot is for packages not states)

![Screenshot_2020-11-03 https dev-chidozie-s-powerful-sloth s1 umbraco io](https://user-images.githubusercontent.com/58373297/98042121-e14c9a00-1dd7-11eb-903d-a82a0ba7e4e4.png)

**Comment by nul800sebastiaan** [comment]
Hi @brightspectrum-da-bomb - apologies for the long delay on this one! 

I tried replicating this and it took me a while to figure out why none of my conditions were working, it turns out that for conditions to work it's required to have a theme selected for your form. So either the default bootstrap theme or another custom one. The reason is that the theme includes the Script.cshtml partial which does all the magic with the conditions.

I've now tried the conditions that you're trying to set up and they seem to work as expected:

![Forms443](https://user-images.githubusercontent.com/304656/99383517-44592900-28ce-11eb-85fc-1f5c34a0d6a2.gif)

Hope this helps!
