### ISSUE TITLE
Form Entries 

### ISSUE THREAD

**Issue by lori698** [umbraco/Umbraco.Forms.Issues#444]
Is it possible to have form entries go to a separate database rather than the main Umbraco database.

**Comment by nul800sebastiaan** [comment]
No, not at this time. While we don't have plans currently to implement this functionality, we'll keep this open as a feature request for the future.

**Comment by lori698** [comment]
Thanks for coming back to me

**Comment by thenexus00** [comment]
> Thanks for coming back to me

You can build a workflow for this.
If it is just all in your own code you can read the data and store in another database.
If it is a 3rd party of some kind you can post as XML to a given location or just as a URL as well and read the data coming in and store into the database that side.

**Comment by AndyButland** [comment]
Going to close this one - it's an idea I'd like to consider, but we have it already in the tracker here: #363
