### ISSUE TITLE
Google ReCapatcha being bypassed issue

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#446]
Google ReCapatcha being bypassed?

As an agency we are seeing a huge spike with client reports of spam in the last month or so across multiple different sites.
- Some from Umbraco 7 and the last Umbraco forms update for the 7 version down to the oldest of 7.0.3 (about 7 sites)
- Under Umbraco 8 with the last 3 versions across 6 sites so far.

- All recaptcha is on and we are not able to submit the forms in testing ourselves without the server side validation errors
- These sites are all under Amazon AWS
- All sites under https

They are 99% All Russian content based:
_Букмекерская контора Париматч. Делайте онлайн интернет ставки на футбол, теннис, баскетбол и другие виды спорта. Ставки на спорт - БК <a href=https://parimatch.cyou/>Parimatch</a>. Так же есть ПМ казино, которое имеет лицензированные игровые автоматы!_ 

- If you remove the form from a page the spam stops. 
- Removing the captcha the spam level does increase or decrease
- Reiteration that we have yet to be able to bypass the forms ourselves
- Forms can either be going to the same page or a custom thank you page - there appears to be no difference in the spam from either
- Unique recaptcha keys for every site

Some sites are older with zero spam which have started to get them as the same time as newly launched sites.

Reproduction
------------

Not something that is replicated because we are not able to submit the forms but we are seeing huge spam.

### Bug summary

Multiple forms across multiple clients and forms and umbraco versions receiving mass increase in spam in the last 4 weeks.

Is there a particular nuget package umbraco forms uses for reCaptcha or its own code base for that? IF not the latter maybe this has a vulnerability?

### Expected result

No spam

### Actual result

Increasing amount of spam

### Summary

My concern is there may be a vulnerability somewhere and maybe specifically on AWS?

**Comment by nul800sebastiaan** [comment]
Thanks for the report @thenexus00 - unfortunately there's nothing I could tell you about this, as you've found, it's not possible to get past the Recaptcha check when trying this out. On the server side we verify by asking the Recaptcha API if the recaptcha response was valid before we store anything.

The only thing I can think of is that spammers might be using actual people to fill in the Recaptcha challenge, it's certainly a tactic they sometimes use. Maybe switch to an alternative check like hCaptcha, might help for a while? A plugin for that can be found here: https://our.umbraco.com/packages/website-utilities/umbracoformsucaptcha/

I'll close this one and recommend you open a support issue with Google if the problem persists, maybe they can see something.

**Comment by thenexus00** [comment]
> Thanks for the report @thenexus00 - unfortunately there's nothing I could tell you about this, as you've found, it's not possible to get past the Recaptcha check when trying this out. On the server side we verify by asking the Recaptcha API if the recaptcha response was valid before we store anything.
> 
> The only thing I can think of is that spammers might be using actual people to fill in the Recaptcha challenge, it's certainly a tactic they sometimes use. Maybe switch to an alternative check like hCaptcha, might help for a while? A plugin for that can be found here: https://our.umbraco.com/packages/website-utilities/umbracoformsucaptcha/
> 
> I'll close this one and recommend you open a support issue with Google if the problem persists, maybe they can see something.

Thanks for the reply.

Can I ask in the recaptcha process code you have do you have something like:

`var error = field.Settings["ErrorMessage"];
`
I am told this can have an issue  with a bypass in terms of tricking the error.
A solution provided to me by someone was along the lines of:
`var error = (field.Settings.ContainsKey("ErrorMessage")) ? field.Settings["ErrorMessage"] : string.Empty;
`

**Comment by thenexus00** [comment]
I just wanted to also raise that we have 4 more clients come to us with Umbraco forms and recaptcha being bypassed. I honestly believe there is a critical issue and the bot that can bypass it with the sites on the same AWS hosting is able to target the IP range and hit the sites.

**Comment by c9mbundy** [comment]
reCaptchaV2 is known to be vulnerable - resources exist for creating a bot that can bypass the current patch level.

reCaptchaV3 is not vulnerable to the same attacks, but unfortunately this is not implemented in either UMB-Forms 8 or 7.
