### ISSUE TITLE
Forms 7.0.5 has the readme for 6.0.0

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#45]
Reproduction
------------
I just created a new blank ASP.NET WebApplication project on .NET Framework 4.7.2 and installed UmbracoForms 7.0.5 using NuGet. The readme that opened at the end of the process is part of the Forms 7.0.5 package but has this content:

=== Version 6.0.0 ===

*New* Form Markup customisation with Themes
*New* Email Workflow - Send HTML emails with Razor
*New* Compatabilty with Umbraco Deploy & Umbraco Cloud & requires a minimum of 7.6.0+

=== Upgraded? ===

If you have upgraded Umbraco Forms please ensure you read the following documentation on our.umbraco.org
https://our.umbraco.org/documentation/Add-ons/UmbracoForms/Installation/Version-Specific

Umbraco Forms runs the following migration tasks in Version 6.0.0

* Moves Umbraco Forms JSON data files from /App_Plugins/UmbracoForms/Data/ to /App_Data/UmbracoForms/Data
* Moves any Forms PreValues that uses text files stored in the Media Section to Umbraco Forms Data storage /App_Data/UmbracoForms/Data/

**Comment by nul800sebastiaan** [comment]
Thanks! We should work in that readme, doesn't really need to have a list of changes I think,

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Forms/commit/5518d6d47a8a0dcaabef1d23837cceeeb734dc11
