### ISSUE TITLE
Open for from macro-picker

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#450]
When a form is picked on a page using the Macro-picker it would be great to be able to navigate to that form so that the editor don't have to go to the forms-section and look for the form by name.

Something like this:

![umbracoforms open from picker](https://user-images.githubusercontent.com/1782524/98922098-5b64d900-24d2-11eb-8ae8-033a2248a93c.PNG)

I hacked around in the source a little to get this working, maybe it can be used as inspiration:

formpicker.html: add allow-open and open-url to the umb-node-preview
```html
        allow-open="true"
        open-url="vm.openUrl"
```
So it looks like this:
```html
    <umb-node-preview
        ng-if="vm.selectedForm.name"
        name="vm.selectedForm.name"
        icon="vm.selectedForm.icon"
        description="vm.selectedForm.fields"
        allow-remove="true"
        on-remove="vm.remove()"
        allow-open="true"
        open-url="vm.openUrl"
    >
    </umb-node-preview>
```

In the controller:

```javascript
  formPickerResource.getPickedForm($scope.model.value).then(function (response) {
                    console.log(response);
                    vm.selectedForm = response;
                    vm.selectedForm.icon = "icon-umb-contour";
                    vm.openUrl = '/umbraco/#/forms/form/edit/' + response.id;

}...
```

**Comment by nul800sebastiaan** [comment]
Thanks @enkelmedia - this duplicates https://github.com/umbraco/Umbraco.Forms.Issues/issues/368 and probably https://github.com/umbraco/Umbraco.Forms.Issues/issues/108 as well.
