### ISSUE TITLE
Send Email workflow deleted when changing Subject line

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco.Forms.Issues#452]
Send Email workflow change of "Subject" causes workflow to be deleted on save.
Results in https://github.com/umbraco/Umbraco.Forms.Issues/issues/407 

**Reproduction**
----------------------
1. Create a new form.
2. Add a workflow  of type "Send Email"
3. Save
4. Configure workflow and change "Subject" field
5. Save
6. Reloading form results in -> Could not find file 'xxx.json' in the folder workflows 

The form kan be made available again by deleting the workflow guid from the form json via KUDO powertools, the workflow however is lost forever. 

**System and versions**
Umbraco Cloud - CMS version 8.9.1
Umbraco Forms - 8.5.5
Umbraco Deploy - 3.5.1

**Expected result**
A change to the subject line of the Send Email workflow

**Actual result**
Deletion of the workflow from app_data folder

**Comment by nul800sebastiaan** [comment]
Thanks @niekvanderreest - I have tried to reproduce with your steps but wasn't able to.

![Forms452](https://user-images.githubusercontent.com/304656/99900743-a7bdcf00-2cb1-11eb-9cb9-a6b7f3c02e75.gif)


I'm probably doing something a bit different, let me know what I missed!

**Comment by niekvanderreest** [comment]
Hi @nul800sebastiaan, 

I'm currently trying to reproduce the error myself, i'm only able to reproduce it on 2 (cloud)projects.
It seems to occur when adding a 3rd workflow, the emptyform template adds 2 workflows so when I added one extra this results in 3 workflows.

Could you try with 3 workflows? and sory for the late reply :)

**Comment by AndyButland** [comment]
Given you've reported this fixed in 8.6 and it wasn't reproducible on the latest version and the time of reporting., will close.  Do please  let me know and/or re-open though @niekvanderreest if you see it again and we can investigate some more.  Thanks.
