### ISSUE TITLE
Add "CC" field to send email with template (razor)

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco.Forms.Issues#457]
Our use-case was that the client wishes to notify the selected store and CC the selected functional group the same feedback “eg email store-a@example.com, and cc online-orders@example.com” or “email store-b@example.com, and cc stock-requests@example.com”

Other email fields that should also be there: reply-to, BCC etc... 
I think we should also be able to add multiple emails in those fields, perhaps like  {field1},{field2},{field3} if these are blank it should not fail, even if after the template runs it ends up with one email followed by several commas and spaces.

we are using Umbraco Forms v6.0.2

**Comment by nul800sebastiaan** [comment]
Thanks @Myster, in the latest version of Forms you could add multiple addresses in the receiver email field, not sure if that's also the case for v6. 

For now the functionality you want can only be created by implementing a custom workflow.

**Comment by warrenbuckley** [comment]
This is fixed in PR https://github.com/umbraco/Forms/pull/436
and is due for 8.7.0 release
