### ISSUE TITLE
Issue with reorder the workflow 

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco.Forms.Issues#459]
Umbraco version 7.14.1
Forms are version 7.0.3

There is a bug within Umbraco forms which means that when workflow steps are re-ordered, it only alters the display order in the admin, not the order that the steps are executed on submission of the form i.e. you can change the order in the UI for the workflow steps but they are still being executed on another order.

 
This causes issues when integrating w/ third-party CRM systems, for example, Pardot.

So, if the Content Editor re-orders steps in the workflow and clicks save & publish in Umbraco, Enquiries are not pulling through to Pardot. Instead, the Content Editor has to delete steps and then place them back in again.

### Steps to reproduce
Create a workflow in the Umbraco Forms. Save & publish. Reorder.

### Expected result

Should be executed in the order displayed on the UI.

### Actual result
This changes the order in the UI, but they are being executed in another order.

**Comment by nul800sebastiaan** [comment]
Thanks @Aaen, make sure to test this on the latest version of Umbraco 7 and Forms 7. We can re-open if it's still an issue there.
