### ISSUE TITLE
Themeable DatePicker.cshtml

### ISSUE THREAD

**Issue by kows** [umbraco/Umbraco.Forms.Issues#46]
At this moment, if you want to update the datepicker's format used for "Date" defined fields in Umbraco Forms, you have to do this in "Partials/Forms/DatePicker.cshtml".
However, these changes are lost when updating Umbraco Forms.
This makes me look towards applying this inside a custom theme,
however this view doesn't seem to be picked up.
Would make sense to me that this does work.

**Comment by sussexrick** [comment]
This would also help to work around #16 without losing changes when Umbraco Forms is updated.

**Comment by nul800sebastiaan** [comment]
Not sure what version you've tried this in but in the current version you copy the `FieldType.DatePicker.cshtml` to your own `MyTheme/FieldTypes/FieldType.DatePicker.cshtml` file and customize it there.

**Comment by kows** [comment]
@nul800sebastiaan that might be true for the HTML rendering for the DatePicker fieldtype,
however I am looking to modify the pikaday initialisation / Javascript part for datepicker, which is located in another file some levels above, which I mentioned in my initial post.

**Comment by StefanoChiodino** [comment]
I have this problem too! Because this is not themable the breaking changes of 7.0.6 couldn't be worked around by "vendoring" that file into the theme. At the same time our frontend dev was fixing some accessibility issues and found the same problem himself!
