### ISSUE TITLE
SaveAsUmbracoNode workflow steps doesn't save property values for properties derived from compositions

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco.Forms.Issues#463]
### A brief description of the issue goes here...
If you use the SaveAsUmbracoNode workflow step to create a content item based on a specified DocType, and populated with values from the posted form records, then this all works ok, unless the properties on the DocType are derived from an underlying composition, and aren't explictly on the Doc Type itself.

### Reproduction
Create a Document Type, called FormEntry give it a property of TextString type called 'FirstName'

Create another Document Type, called CommonFormEntryProperties, create a property of TextString type called 'LastName'

Update your FormEntry to be 'composed of' the 'CommonFormEntryProperties' DocumentType

And allow content based on the FormEntry Doc type to be created underneath a 'Standard Page' or wherever you can insert an Umbraco Form.

Create an Umbraco Form, with fields FirstName and LastName, add the workflow step 'SaveAsUmbracoNode' specify the FormEntry to be type of node to create.

Add the form to page, and fill it in, you'll find the workflow step creates a new node based on the details filled in in the form, but only the FirstName will be populated, the LastName will be skipped.

### Possible solution

I suspect the workflow step works like the following:

All of the posted Form Field records are retrieved in the workflow step 'SaveAsUmbracoNode'

The ContentTypeService is probably used to get the ContentType of the DocType you are trying to create eg FormEntry

Then I reckon the ContentService is used to create a new content item instance based on the ContentType specified.

Then it must loop through all the properties of the newly created content item (which will include all the properties from compositions too )...

and try to use the alias of the property to pull the value from the posted Umbraco form fields that match the alias...

... however, it will need to know 'what type' of property, each one is to know how to parse the form field correctly, eg if it's a date field - and so it needs to find the corresponding PropertyType for the property (to find it's DataType), but from the content item it will only have the property alias.

And so here's the bug

It will be looking up the PropertyType for a property alias, by using the ContentType definition retrieved initially. The ContentType entity has a PropertyTypes property... and it will be using this to find the underlying DataType by filtering on property type alias - but if it doesn't find a PropertyType it will just skip the mapping attempt, and move on to the next property...

But the PropertyTypes property of a ContentType only includes Properties from the actual ContentType and not any underlying Compositions...!!!

So all properties from underlying compositions are not being mapped in the workflow step!

But there is a property on ContentType called **CompositionPropertyTypes**, 

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Models/ContentTypeCompositionBase.cs#L79

which could be used instead to lookup the PropertyTypes by alias to find the DataTypes of properties defined on compositions and successfully map them from the form fields instead of skipping them!

## Expected result

In the example above, both FirstName and LastName should be populated from the posted form values for the freshly created FormEntry node.

**Comment by nul800sebastiaan** [comment]
Thanks @marcemarc, that's annoying. I don't have a workaround for you at the moment I'm afraid, but this is a good one to fix when we look at workflows next.

**Comment by nikolajlauridsen** [comment]
This has been fixed, and will be in the next release 👍 

Also might I add that those are some impeccable bug notes 🎉
