### ISSUE TITLE
Workflow Steps that are disabled to have an indicator to show they are disabled.

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Forms.Issues#464]
Current functionality:
When you disable a workflow step by unticking the "Active" option there is no indication that this step is now inactive.

Suggestion:
Could a class be added to the umb-forms-workflow-preview or child anchor that issues a simple greyed out style

<img width="552" alt="Screen Shot 2020-12-15 at 3 06 12 pm" src="https://user-images.githubusercontent.com/4312656/102170661-fc3b1f80-3ee8-11eb-939b-5bf7469cb0f7.png">

**Comment by nul800sebastiaan** [comment]
Thanks @thenexus00, that is a great suggestion to look at when we work on the UI of workflows next.

**Comment by nikolajlauridsen** [comment]
This has been fixed and will be in the next version 8.6.1
