### ISSUE TITLE
Umbraco Form Picker should return a guid

### ISSUE THREAD

**Issue by busrasengul** [umbraco/Umbraco.Forms.Issues#465]
When picking form picker property editor, it returns an object instead of Guid.
The data is a string, the type is an object but I really need to get the Guid. When I need to do a null check, I can't do string.IsNullOrEmpty check as it's an object, I need to do a lot of work to cast it to turn into a Guid. 
Just wanted to raise this as an issue because picker type property editors are returning Guid already but the form picker as far as I know now :)

**Comment by nul800sebastiaan** [comment]
Thanks @busraparnell, for now, keep doing what you're doing. :) We'll have to have a look at this in the future. Might be a difficult one as changing this now will probably break existing pickers, so we'll need to find a way to do it without breaking everything.

**Comment by ronaldbarendse** [comment]
Adding a property value converter for the Forms picker that returns a `Guid?` would be a breaking change (like @nul800sebastiaan mentioned), but we could include this a part of the next major version! We could do the same for the Forms Theme picker to return a `string` 👍🏻 

The following code should change the return type for the Forms picker (and could be added to your own projects right now):

```c#
using System;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.PropertyEditors;

namespace Umbraco.Forms.Core.PropertyEditors
{
    public class FormsPropertyValueConverter : PropertyValueConverterBase
    {
        public override bool IsConverter(IPublishedPropertyType propertyType)
            => propertyType.EditorAlias == "UmbracoForms.FormPicker";

        public override Type GetPropertyValueType(IPublishedPropertyType propertyType)
            => typeof(Guid?);

        public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType)
            => PropertyCacheLevel.Element;

        public override object ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, object source, bool preview)
            => Guid.TryParse(source?.ToString(), out var formId) ? formId : null;
    }
}
```

**Comment by AndyButland** [comment]
Will close this issue now as we've shared the code that can be added to individual V8 projects if people want it, but because of the breaking change will not be able to add out of the box for V8.  It has been added to V9 though, so this will be the default behaviour moving forward.
