### ISSUE TITLE
Internet Explorer JavaScript error (v8.6.0)

### ISSUE THREAD

**Issue by miackers** [umbraco/Umbraco.Forms.Issues#466]
Getting JavaScript error message on Internet Explorer 11

Reproduction
------------

Visit a page with an Umbraco Form on Internet Explorer 11. Error in Console says: "Expected ';'". Line number 107. Can stop other JavaScript on page from executing.
 
### Bug summary

Error in Browser console says: "Expected ';'". Line number 107 of \App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js. Can stop other JavaScript on page from executing.

I've fixed this by removing the word "async", since not supported by Internet Explorer 11. Also, an additional error afterwards on line 118 where => syntax not support by IE11 either.

### Specifics
- Umbraco v8.6.5
- Umbraco Forms v8.6.0 (not tested on previous versions)
- Internet Explorer 11 (works on other browsers I've tried)

### Steps to reproduce

Visit any page with an Umbraco Form (v8.6.0), or a page that includes \App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js.

### Expected result

No error in console, and allow other JavaScript to execute

### Actual result

Error in console

**Comment by miackers** [comment]
Forgot to mention that I am aware Microsoft's support for IE11 is nearing its end. So if this is not a browser Umbraco Forms specifically supports, then I am happy for this to be a non-issue.

**Comment by nul800sebastiaan** [comment]
Yeah I'm sorry to say but Umbraco 8+ (and therefore Forms 8+) does not support IE any more, so I'll close this one. 👍
