### ISSUE TITLE
Typo in umbracoforms.js, line 380 (Umbraco Forms 8.6.0)

### ISSUE THREAD

**Issue by janekelin** [umbraco/Umbraco.Forms.Issues#467]
There is a typo in `Assets/themes/default/umbracoforms.js` on line 380 in the name of the method `getElementsById` (should be [getElementById](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById))

Reproduction
------------

The bug is discoverable only on forms where Date Picker is used.

### Bug summary
A typo in Assets/themes/default/umbracoforms.js on line 380 in the name of the method `getElementsById`.

### Specifics

Detected in UmbracoForms 8.6.0.
Seen on Chrome 87, Firefox 84, but should be present in other browsers as well, since it is not browser-specific.
![image](https://user-images.githubusercontent.com/34571709/103491556-20718880-4e25-11eb-9ce7-4fa8e9c23de0.png)

### Steps to reproduce

1. Create a form with a date picker field.
2. Select the date picker field.
3. The error appears in console.

### Expected result

`getElementById` should be used instead or the logic of how the element is selected needs to be tweaked.

### Actual result

An error in the console.
So far, we did not manage to create a use case, where this bug has a severe impact on how the form functions. This bug does not prevent submission of the form, or recording the submitted answers.

**Comment by nul800sebastiaan** [comment]
Hi @janekelin! Thanks for reporting this one and good find! This will is now fixed for the next release. 👍
