### ISSUE TITLE
Labels not showing on forms after upgrading to Forms 7.4.1

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#468]
On the backoffice we cant see the labels of the form and neither the placeholders.
The problem began when updating from Umbraco 7.15.6 and Umbraco Forms 7.1.3, to v7.4.1.
The update was using UmbracoForms.Files.7.4.1.zip and copying all the contents but merging UmbracoForms.config
Following the steps here: https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Installation/ManualUpgrade-v7

This issue is related to this https://github.com/umbraco/Umbraco.Forms.Issues/issues/460
I had to reopen it again as it was closed and i now i can reproduce it:

This is what i have done to reproduce it:

1. install a new instance of Umbraco v7.15.6 (select SQL CE database version for quickness)
2. go to forms section, install. It will install UF 7.4.1
3. create a new form, name it "Test form", add a short answer. Save it, it works and it shows all labels.
4. reload page, it shows all labels.
5. copy all files inside App_Data\UmbracoForms\Data folder from the problematic project.
6. Increase version on ClientDependency.config file.
7. Restart the app and refresh Umbraco Forms section.
8. All the forms appear, some of them get error on opening: "Unable to load form: No provider with id xxxxxx" i think that may have to do with some provider required on UmbracoForms in database? anyway, i dont get that error on the problematic project.
9. Try opening the Test form created previously, labels are hidden.

I think the problem is due to some forms having been created on an older version but i can get what it is.
Note we have lots of forms, around 130, it could be a "too much forms" issue?

If i delete all the forms from "App_Data\UmbracoForms\Data\forms" folder but the form created with the new version and refresh the application it works again. I have tried copying groups of forms again from the old folder until the problem happens again, but i cant see where exactly starts to happen. 
If i downgrade to 

If you let me an email i can send you a zip file with the "App_Data\UmbracoForms\Data" contents so you can reproduce it.

**Comment by nul800sebastiaan** [comment]
I'll reopen #460 once I can reproduce the problem 👍
