### ISSUE TITLE
Missing reorder icon on groups

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco.Forms.Issues#472]
If I have multiple groups, and want to reorder, the icon to show that groups can be reordered too is missing. I can see the icon to reorder fields, but not groups.
The groups can still be reordered, but you have to guess where to click.

![image](https://user-images.githubusercontent.com/21119705/103850401-b9302e80-50d9-11eb-80c2-04ef8972b007.png)

Umbraco 8.10.1
Forms 8.6.0
Cloud

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco.Forms.Issues/issues/341
