### ISSUE TITLE
Multi-select dropdown for Umbraco Forms.

### ISSUE THREAD

**Issue by fahadmahmood20** [umbraco/Umbraco.Forms.Issues#473]
Currently Umbraco Forms do not provide Multi-select dropdown option. Can you please add it?

**Comment by nul800sebastiaan** [comment]
Thanks, at the moment we have no plans to add extra fieldtypes but I'll put this on the list to work on in the future when we start work on fieldtypes again. 

In the mean time I would suggest you can develop your own fieldtype, there's documentation about that here: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype

**Comment by bjarnef** [comment]
This could probably be a single/multiple option similar to file upload:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/499

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
