### ISSUE TITLE
Copied Form - IDs are kept the same

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco.Forms.Issues#476]
Hello,

When you copy a form to duplicate it, the GUIDs of the form fields are also duplicated which means they are not unique. 

Example scenario - you have a landing page with a form in the hero area. The client then wants the same form further down the page. If you use a HTML Ordering/CSS trick to style custom radio buttons or checkboxes, when you add the same form, the IDs for the input/label combination need to be unique for each form element. So you go into Umbraco Forms and click copy and rename your second form to "Hero Landing Page Form" and add it to the page - the GUIDs used for the fields are still the same. 

Which in this case defeats the purpose of copying the form and you end up having to manually recreate it.

The GUIDs should be regenerated for each item when the form is copied (naturally, the code will need to then reassign conditional logic based on these IDs). 

This issue was identified in Umbraco Forms: 8.4.0 on Umbraco version 8.6.3.

Hope that makes sense?

Cheers
Ric

**Comment by nikolajlauridsen** [comment]
This has been fixed and will be in the next release
