### ISSUE TITLE
Date picker field needs to disable autocomplete

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#48]
When you use a date picker field more than once, the previous dates that you entered appear in a browser autocomplete which partially obscures the date picker, making the date picker difficult to use.

Reproduction
------------

Using Umbraco 7.9.0 and Forms 7.0.5 and Chrome 69, create a minimal form with just a date picker. Fill in the date and submit the form. Go back to the form and click into the field again, and the autocomplete appears.

![image](https://user-images.githubusercontent.com/1260550/48956844-29f14c80-ef4d-11e8-8f6a-0bb3723b7344.png)

### Expected result

I would expect to see just the calendar without the previous entries. The input field needs autocomplete="off" to achieve this.

**Comment by bergmania** [comment]
Connects: https://github.com/umbraco/Forms/pull/226

**Comment by RobertCopilau** [comment]
No autocompletion anymore, merging.
