### ISSUE TITLE
Unable to delete form properties

### ISSUE THREAD

**Issue by SRandomName** [umbraco/Umbraco.Forms.Issues#480]
Option to delete a property is not showed when clicking the bin icon on a property.

Versions: 
- Umbraco v8.8.0
- Forms v8.6.0

Steps to reproduce:
Clean install of Umbraco Forms v8.6.0 on a Umbraco v8.8.0 instance.

More info in a gif: 
![UmbracoFormsProblem](https://user-images.githubusercontent.com/48089189/105167358-eab4eb00-5b18-11eb-9f7b-45ffe03d7584.gif)

Any ideas how to fix this? Thanks!

**Comment by nul800sebastiaan** [comment]
@SRandomName This was fixed in Umbraco 8.8.1, make sure to upgrade: https://our.umbraco.com/download/releases/881
