### ISSUE TITLE
Render placeholder text in preview

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#483]
On Umbraco Forms fields it is possible to specify the placeholder text. However this isn't reflected in the preview.
I think it would be great to show these values in the previous values - just as placeholder text on the input fields in the previews.

Tested on Umbraco v8.11.1 and Umbraco Forms v8.6.0

![image](https://user-images.githubusercontent.com/2919859/107022190-606db780-67a5-11eb-8358-d2bc295badf8.png)

**Comment by nul800sebastiaan** [comment]
Fixed for the upcoming v8.7.0.
