### ISSUE TITLE
bootstrap3-horizontal theme doesn't render form-control class

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#484]
With Umbraco v8.11.1 and Umbraco Forms 8.6.0 there are by default the following themes `default` and `bootstrap3-horizontal` does however not overwrite either Text and Textarea fields.

However when rendering the form with default theme `<textarea>` has the class `form-control` which I think shouldn't be in default theme - it is more specific to Bootstrap theme.
Furthermore the `<input type=text" />` only has the class `text` and doesn't use `class="@Html.GetFormFieldClass(Model.FieldTypeName)"` like Textfield partial does in default view.

I have added a custom theme, but I think the default themes need some updated to ensure no bootstrap specific classes are added in default theme and the bootstrap theme use the standard classes when working with forms in a Bootstrap theme.

![image](https://user-images.githubusercontent.com/2919859/107026743-73838600-67ab-11eb-9043-6120ae29b890.png)

**Comment by nul800sebastiaan** [comment]
Unfortunately, this has shipped for too long like this now and we can't just start removing classes since people might already be relying on them being there. We'll keep it in mind for the vNext version though so we'll have a better, clean, default. For now, you can always implement your own theme of course and mark it up exactly to your wishes. :-)

**Comment by bjarnef** [comment]
@nul800sebastiaan it is not about removing classes, it is about adding a missing class.

FieldType.TextArea includes `form-control` , FieldType.Textfield doesn't.

It should be simple enough to update this view, without removing the existing `text` class.

```
class="text @Html.GetFormFieldClass(Model.FieldTypeName)"
```

**Comment by bjarnef** [comment]
This is still valid in Umbraco Forms v9.0.0

Unlike other field it just has the class `text` instead of `class="@Html.GetFormFieldClass(Model.FieldTypeName)"` ... or at least `class="text @Html.GetFormFieldClass(Model.FieldTypeName)"`.

**Comment by AndyButland** [comment]
I've added this update to the class now - will be in the next minor releases of V8 and V9.
