### ISSUE TITLE
aspnet validation does not validate radio inputs

### ISSUE THREAD

**Issue by james-whittington1** [umbraco/Umbraco.Forms.Issues#487]
the function that validates required fields has a specific check for checkboxes but neglects to check radio boxes.
![image](https://user-images.githubusercontent.com/37091895/108276282-6ec3c680-71dc-11eb-86c9-b8ec88a5852d.png)
The issue appears to be in \App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js at line 81
In my screenshot i have added an or check to fix the problem.

### Steps to reproduce
Note: you must be running the aspnet-validation javascript - jquery validate is not effected.
I used the   @Html.RenderUmbracoFormDependencies()  method to render the dependencies and it automatically loaded aspnet-validation, I don't know how this method determines what to load.

Create a new form with a radio list input field and make it mandatory.
Submit the form.
 

### Expected result
The front end validation tells the user that the field is required.

### Actual result
The form submits and the back end validation runs, the form is then rendered with the backend validation showing

**Comment by nul800sebastiaan** [comment]
Thanks for the report @james-whittington1 - we'll have to have a look at this! Good that you found a workaround for now, we'll probably add that to the code as well, thanks! 👍

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Forms/pull/445 and is due for 8.6.2 release
