### ISSUE TITLE
Multiple workflow email steps added and cannot delete in Forms

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco.Forms.Issues#489]
We had an instance, when one of our forms had an email workflow step multiplied in the workflow section. We could not delete the additional entries until all workflow steps with the same name were deleted. We could then re-add it, and only a dingle on persisted. 

https://drive.google.com/file/d/14Mv1QO5AwdSWx3wU0_vMtAG6m-9oiQ00/view?usp=sharing

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

As above. Single email workflow step was duplicated in the admin interface.. 

### Specifics

In the back office, when viewing a form, under the workflow entries. THe workflow step that was replicated was an email step.  

### Steps to reproduce

Not sure how to reproduce. 

### Expected result

Single email workflow step to display, not multiples of the same one. 

### Actual result

Multiple workflow steps displayed, and could not be removed unless all of them were removed.

**Comment by nul800sebastiaan** [comment]
Hey there @gabador-mof, that sounds annoying. I have a feeling I've seen this problem before but I can't find a related issue, could you tell us which version you're running on currently and if you're using forms on disk or in the database? Also, which version of Umbraco are you using with that please?

**Comment by nul800sebastiaan** [comment]
I've tried this out on now myself and can't find any problems with deleting workflows. I will close this for now but let us know when you have some more information to go on so we can give it another look.
