### ISSUE TITLE
Date picker field crashes with dates before 1753

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#49]
SQL Server's datetime field cannot handle dates before 1753 and if you enter one in a date picker field, the page crashes with the error `System.Data.SqlTypes.SqlTypeException SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.` 

Reproduction
------------

Using Umbraco 7.9.0 and Forms 7.0.5 and Chrome 69, create a minimal form with just a date picker. Fill in the '1 Jan 1700' and submit the form. 

### Expected result

I would expect it to accept the date. If the form were dealing with an historical subject the early date might be useful.

At the very least it should validate and reject the date so that the user does not lose their data.

**Comment by sussexrick** [comment]
I've added a workaround as part of this package:
https://www.nuget.org/packages/Escc.Umbraco.Forms.FieldTypes/1.1.0
https://github.com/east-sussex-county-council/Escc.Umbraco.Forms/blob/master/Escc.Umbraco.Forms.FieldTypes/DatePicker.cs

**Comment by bergmania** [comment]
Connects: https://github.com/umbraco/Forms/pull/226
