### ISSUE TITLE
Console error in umbracoforms.js

### ISSUE THREAD

**Issue by rubenberendsen** [umbraco/Umbraco.Forms.Issues#490]
Hi,

In UmbracoForms version 8.6.0 and 8.6.1 i get an error in the console. The code seems to work correctly (even if the form contains a datapicker field).

![image](https://user-images.githubusercontent.com/38040580/108825197-04879900-75c3-11eb-9614-863dbc48318f.png)

---
_This item has been added to our backlog [AB#10592](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10592)_

**Comment by nul800sebastiaan** [comment]
When do you see this error please? Backoffice, frontend? What are you doing at the time?

**Comment by rubenberendsen** [comment]
I open the frontend with a form (doesn't matter what the fields are).
I have an example here: http://umbraco.frontislab.nl/contact

**Comment by nul800sebastiaan** [comment]
Thanks @rubenberendsen! It seems like Forms incorrectly assumes that forms will always have multiple pages (when you add a new  group in the forms builder, it will output a div with class `umbraco-forms-page`).

This starts to go wrong on line 54: `var page = form.querySelector('.umbraco-forms-page');` when there's only one page this selector is wrong. Changing it to `var page = form.querySelector('form');` for now seems to do the trick, but we'll have to look into a proper fix.

**Comment by nul800sebastiaan** [comment]
@rubenberendsen Question: which theme do you use? The default bootstrap theme seems to wrap everything in a div with class `umbraco-forms-page`.

**Comment by rubenberendsen** [comment]
@nul800sebastiaan We have sovled the problem by changing the class in the wrapping div. 

Thanks for your help

**Comment by skartknet** [comment]
This just happened to me on version 10.4.0 . The line is `var datepickerfields = self.form.querySelectorAll('.datepickerfield');`
