### ISSUE TITLE
Script src integrity check

### ISSUE THREAD

**Issue by Domitnator** [umbraco/Umbraco.Forms.Issues#492]
Our client used www.threadstone.eu to scan the site for potential scurity issues.

One thing threadstone came up with is:

![image](https://user-images.githubusercontent.com/13468638/109003995-6cfc7600-76a8-11eb-8dcb-364ca01c94ea.png)

My guess is that threadstone.eu is complaining about the missing "integrity" attribute for the external scripts needed by the forms module.

Is this something we can fix ourself or does the umbraco forms module needs to fix this?

**Comment by nul800sebastiaan** [comment]
This won't be a problem with Forms 8.6 any more where we don't rely on an external jQuery library any more for validation.

You can replace the `@Html.RenderUmbracoFormDependencies` yourself, you're not required to use it, the only thing it does is the following:


```csharp
        public static IHtmlString RenderUmbracoFormDependencies(this HtmlHelper html)
        {
            var sb = new StringBuilder();
            sb.Append("<script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js'></script>");
            sb.Append("<script src='https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js'></script>");
            sb.Append("<script src='https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.js'></script>");

            return html.Raw(sb.ToString());
        }
```

So instead, you can add those scripts to your template with the integrity attribute. Same for recaptcha, which is being added in the rechaptcha fieldtype cshtml file, it can be updated to add an integrity attribute.
