### ISSUE TITLE
Field mapping does not save changes / new entries / swallows updates with regards to static values

### ISSUE THREAD

**Issue by vavdb** [umbraco/Umbraco.Forms.Issues#494]
Umbraco forms 8.6.1 - Umbraco 8.11.1

Customer complains they can't change Field Mapping values. Changing a static value does not seem to persist after saving. Adding a new static value does not seem to persist.

The only way to get static changes to persist is to add a new mapping that binds to a form value.
After saving this extra mapping can be removed.

# Reproduction
------------
Enter field mappings, press submit, save workflow, re-open workflow.

## Sample 1:
Open previously stored values:
![image](https://user-images.githubusercontent.com/1478794/109313827-ed59dd00-7848-11eb-8836-4144257b624f.png)

Change them:
![image](https://user-images.githubusercontent.com/1478794/109313874-fa76cc00-7848-11eb-9a99-1626f311dc0d.png)

Submit, save, re-open:
![image](https://user-images.githubusercontent.com/1478794/109313921-05316100-7849-11eb-913c-b95560641e3d.png)
All changes have disappeared

Workaround for previous Sample;
![image](https://user-images.githubusercontent.com/1478794/109314009-1aa68b00-7849-11eb-8792-534bd7a520e5.png)
Add a new alias+form value mapping

Submit, save, reopen:
![image](https://user-images.githubusercontent.com/1478794/109314061-2abe6a80-7849-11eb-83c9-115bc3fd0032.png)

## Sample 2:
Entered values:
![image](https://user-images.githubusercontent.com/1478794/109313231-45441400-7848-11eb-967e-194a28a8180c.png)

Pressed submit, save, and re-open:
![image](https://user-images.githubusercontent.com/1478794/109313285-51c86c80-7848-11eb-9bf6-873ffab6f6fc.png)
The last static value is missing

## Sample 4:
Enter values:
![image](https://user-images.githubusercontent.com/1478794/109313332-60168880-7848-11eb-9114-4848fa784f61.png)

Pressed submit, save, and re-open:
![image](https://user-images.githubusercontent.com/1478794/109313361-6a388700-7848-11eb-90b3-fc30ab322829.png)
The last static value is missing

## Seemingly working workaround, another example:
Enter the requested values, and make the last mapping map to a form value:
![image](https://user-images.githubusercontent.com/1478794/109313468-8c320980-7848-11eb-9ce7-7330c3b97ebe.png)

After re-opening the values are still there:
![image](https://user-images.githubusercontent.com/1478794/109313508-994ef880-7848-11eb-853e-e23c5d7d0cbc.png)

Now you can delete the last value, and re-open:
![image](https://user-images.githubusercontent.com/1478794/109313561-a66be780-7848-11eb-9b83-37a901fc674b.png)

**Comment by vavdb** [comment]
Seeing the same issue on Umbraco Forms 8.6.0 + Umbraco 8.9.1

**Comment by AndyButland** [comment]
Thanks for reporting @vavdb.  I believe this has been resolved as part of the work in fixing #350, and have tested the latest code and confirmed static values now do save.  Hence will close and label this as due in the next minor release.

**Comment by vavdb** [comment]
@AndyButland thanks, any eta on this?
I had seen the linked report, but it was closed without any comment(a comment would have been good)  and was slightly different in report.

**Comment by AndyButland** [comment]
Agreed, I've added a comment for anyone else following on that issue.  As you say, it descrinbed a slightly different issue but it seems to me it was the same underlying cause and so the fix should resolve both issues.  I can't give a date yet for the next release but watch out for at least an 8.7 release candidate in the next few weeks.
