### ISSUE TITLE
"Do something else" on the Forms dashboard doesn't work

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Forms.Issues#496]
The "Do something else" on the Forms dashboard does open the menu like it should.

Reproduction
------------
### Bug summary

https://user-images.githubusercontent.com/304656/110312018-d9f70080-8004-11eb-9092-29602540ec3d.mp4

### Specifics

Umbraco 8.11.1
Forms 8.6.1
Deploy 3.5.4

Tested on:
Brave
Chrome
Edge

Same result on the all.

### Steps to reproduce

1. Go to the Forms dashboard.
2. LEFT click on the ellipsis next to "Forms"
![image](https://user-images.githubusercontent.com/56826332/110225256-1c74ec00-7ee4-11eb-8e53-d1b7431ffa3c.png)
3. Click on the "Do something else" button.

### Expected result

Well, given the name, I would expect it to do something 😆 but seriously, it should open this menu:
![image](https://user-images.githubusercontent.com/56826332/110225280-783f7500-7ee4-11eb-86a1-03e1ac6b4a0b.png)

### Actual result

It does something else which is nothing.

---
_This item has been added to our backlog [AB#10817](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10817)_

**Comment by nul800sebastiaan** [comment]
Yeah, definitely a Forms issue, I've moved it. Not sure if we can hide that button but there is nothing else you can do there so there shouldn't be a button.

**Comment by RyuLindow** [comment]
Well, it does have a purpose.

Clicking on the button should switch you to the menu that opens when you right click on the 3 dots.

The ones I screenshotted in the "Expected result" section.

That's how the other dashboards behave.

**Comment by nul800sebastiaan** [comment]
Oh duh yeah you're right, I am being a little bit thick here!

**Comment by RyuLindow** [comment]
I mean, it's Monday :)

**Comment by AndyButland** [comment]
This appears to work as expected in the latest version of forms, so believe must have been fixed at some point since reporting, so will close.
