### ISSUE TITLE
Ability to edit form entries from Backoffice.

### ISSUE THREAD

**Issue by daljitkaur9** [umbraco/Umbraco.Forms.Issues#498]
Hi, Is there any way to edit/update the form from backoffice by the admin ?

**Comment by emma-hq** [comment]
Hi @daljitkaur9 

That's entirely possible, yes. Take a look at our [docs on forms](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/) and that should shed some light on the issue for you. If you need further support though, please visit our forum [Our.Umbraco.com](https://our.umbraco.com/). 

Emma

**Comment by daljitkaur9** [comment]
Thank you, Emma.

**Comment by daljitkaur9** [comment]
Hi Sebastian,
Yes i already saw this example.
But my use case was : Something like, an admin should be able to add some comments to the submitted form, before approving or declining it.

**Comment by detsroh** [comment]
Hi all,

This has been the most requested and voted (and promised 🙈) feature for years, but been overlooked numerous times. See just a few of the requests...

[https://github.com/umbraco/Umbraco.Forms.Issues/issues/146](https://github.com/umbraco/Umbraco.Forms.Issues/issues/146)
[https://issues.umbraco.org/issue/CON-786](https://issues.umbraco.org/issue/CON-786)
[https://issues.umbraco.org/issue/CON-920](https://issues.umbraco.org/issue/CON-920)
[https://our.umbraco.com/forum/umbraco-pro/contour/75003-edit-forms-entry](https://our.umbraco.com/forum/umbraco-pro/contour/75003-edit-forms-entry)
And plenty of other forum requests...

We use umbraco Forms for contact forms, but mostly for event signup. Often people submit incorrect data and we need to be able to correct typo mistakes, update their selections etc. We made our own implementation years ago, where our editors can edit umbraco Form entries on the related/specific event content page (in its own tab) using the forms datatypes - maybe it can be used as inspiration for implementation...

![chrome-capture](https://user-images.githubusercontent.com/3941249/114021226-c1cb0900-9870-11eb-8c58-ee4f366d0430.gif)

Ofcause this doesn't need to be possible in a content page like above, but in the Forms section. A datatype to also be able to do it on a content page would be killer bonus feature though :-)
 
We also like the option to create a new entry (it's the magicwand icon, left to the 'søg' field) from the backend, if people signup by phone, mail or in person...

![chrome-capture (2)](https://user-images.githubusercontent.com/3941249/114023093-be388180-9872-11eb-89e8-8a4bf37754c7.gif)

I think there are lots of other scenarios where beeing able to create/edit a form entry in the backend would be usefull, as people use umbraco Forms for lots of things besides contact forms. For instance we also use the form entries data for creating printed nametags for events and often people write their name in only lowercase, so we need to be able to correct this before printing. 

(Another usefull feature would be Import - bulk import of entries, just like can Export, but thats a whole other story/feature and editing (and creating) an entry is more important :-)

It would be much appriciated if HQ will prioritized these feature requests and they would be added to the roadmap... 

Thanks in advance!

**Comment by detsroh** [comment]
Very pleased that 'Editable entries for Umbraco Forms' has been added to the roadmap and ETA is Q1 2022 - Andy you are a rockstar 🥳 Merry christmas to all of you 🎅🎄

**Comment by AndyButland** [comment]
Due in the next minor releases, 8.11.0 and 9.3.0.
