### ISSUE TITLE
Single / Multiple File Upload

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#499]
Currently with Umbraco Forms v8.5.6 (but checked in v8.6.0 as well) it seem to be possible to upload multiple files. But currently it always allow multiple files via the `multiple` attribute.

Since this is already added multiple file upload is default, but maybe they should be a "allow multiple" toggle (which on the File Upload field type is enabled by default)?

![chrome_kcQpdVr9J2](https://user-images.githubusercontent.com/2919859/110443174-ed18d780-80bb-11eb-8a6e-c4fee535c8ee.png)

---
_This item has been added to our backlog [AB#10964](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10964)_

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Forms/pull/458
Due for release in 8.7.0
