### ISSUE TITLE
Fix issue with loss of "message on submit" setting for form

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#502]
When configuraton an Umbraco Forms workflow using "Send email with template (Razor)" submitting without selecting a razor template, you'll get an validation error, but behind the overlay.

I think the specific field which in invalid should always be highlighted like in Umbraco core as multiple field can be invalid. The notification error could be an addition, but not a great help to editors compared to highlighting the invalid property.

It also happens if not filling other required fields like "Subject", where you will get a notification error per invalid field.

Tested on Umbraco v8.8.4 and Umbraco Forms v8.5.6

![8DBlf4Wh06](https://user-images.githubusercontent.com/2919859/111361738-51283680-868e-11eb-9e5f-676e4ba2e549.gif)

---
_This item has been added to our backlog [AB#10960](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10960)_

**Comment by bjarnef** [comment]
Even worse I noticed the error actually cause it has changed the message in "Message on submit" workflow from "Thanks for your message" to "0" 🙊😬

![image](https://user-images.githubusercontent.com/2919859/111365170-73bc4e80-8692-11eb-9e72-7833182501d2.png)

**Comment by bjarnef** [comment]
If a "Go to page" previous was selected it has now changed the message to that node id.

![image](https://user-images.githubusercontent.com/2919859/111365624-00670c80-8693-11eb-92a5-b26a70015254.png)

**Comment by AndyButland** [comment]
We may take this as two issues @bjarnef .. the validation doesn't work too badly it seems to me so long as the screen you are editing on is wide enough, though I do agree it would be better inline.

Are you able to provide steps to trigger the issue you've found where the "Go to page" setting gets swapped into the "Message on submit" though please, as that's perhaps more important to fix.  I have seen this too, but haven't yet been able to reliably replicate (and from there hopefully it would be easy to fix).  Thanks if so.

**Comment by bjarnef** [comment]
@AndyButland currently I am working from laptop 1280 x 720 which is a common screen resolution and barely notice the invalid message behind the overlay 🙈
The inline validation would be much more consistent with the Umbraco validation e.g. combined with the invalid "tooltip". The notification errors could be useful in some cases and it may require some styling updates in Umbraco core.

Regarding the values in "Message on submit" workflow was swapped, I simply did the following.

- Add a message and/or select a node under "Message on submit" workflow
- Add a new workflow using "Send email with template (Razor)"
- Entered a name "Test"
- Submit overlay
- Without leaving page click the "Submit message / Go to page" action at bottom to open/edit the workflow
- Now the "Message on submit" input is "0" or node id of the "Go to page" node (if any selected)

**Comment by AndyButland** [comment]
Thanks, have resolved the "message on submit" issue but we'll keep the issue open for the UX issues that was the original topic.

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Forms/pull/461
Due for release in 8.7.0

**Comment by AndyButland** [comment]
Thanks @warrenbuckley - I'd considered doing this the other way around, but now the tagging, titling and issue update is done, we do still want to make sure we don't lose the UX issue that was originally raised on this ticket.  As we've only fixed the "message on submit" issue in the PR.

@bjarnef - sorry to be a pain, but would you mind opening a new one with just the UX/validation issue you originally raised on this ticket please?  Obviously I could but if you do it you'll be associated with it for any future comms.  Thanks.

**Comment by bjarnef** [comment]
@AndyButland sure, I have submitted a new issue here regarding the UX/validation: https://github.com/umbraco/Umbraco.Forms.Issues/issues/503
