### ISSUE TITLE
Backoffice Forms Security errors

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Forms.Issues#505]
Errors in the backoffice under "Users" -> Forms Security and then click the 3 dots ". . ." to see errors pop up.
_Server error: Contact administrator, see log for full details.
Failed to retrieve data for a node's menu 1_

Reproduction
------------

### Specifics

Umbraco version: 8.12.1
Umbraco Forms version: 8.6.1
Umbraco.Deploy Version: 4.0.2

Tested in:
Chrome Version: 89.0.4389.90
Firefox Version: 86.0.1

### Steps to reproduce

1. Create an Umbraco Cloud Project
2. Go the the backoffice.
3. Go to the "Users" tab and click on Forms Security
4. Click on the three dots ". . ." on the user when you hover or select it
5. See errors occur like on the image below

![users Forms security error 2](https://user-images.githubusercontent.com/2794633/111776586-7eedc500-88b2-11eb-91d4-6c5e3ca0fe24.png)

This error occured at one point as well:
![Users forms security error](https://user-images.githubusercontent.com/2794633/111776670-96c54900-88b2-11eb-8f1f-f86b909061a4.png)

### Expected result
No errors occuring

### Actual result
Backoffice errors:
_Server error: Contact administrator, see log for full details.
Failed to retrieve data for a node's menu 1_

---
_This item has been added to our backlog [AB#11001](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11001)_

**Comment by AndyButland** [comment]
I don't think it's possible to remove the elipsis - even with no menu items it still shows (though clicking on it doesn't do anything).

Going to transfer this to the Deploy tracker though as seems like if there is an error it's occuring in there.
