### ISSUE TITLE
8.7RC: Use range slider component in reCAPTCHA V3

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#507]
In the new reCAPTCHA V3 form field consider to use `<umb-range-slider>` component instead on the traditional HTML slider.
https://github.com/umbraco/Umbraco-CMS/search?q=umbRangeSlider

![image](https://user-images.githubusercontent.com/2919859/112270063-77933680-8c79-11eb-87ea-d429f0093541.png)

It ensures consistency with Umbraco core UI and should look something like this:

![image](https://user-images.githubusercontent.com/2919859/112270617-32233900-8c7a-11eb-9f70-4297abc059db.png)

**Comment by AndyButland** [comment]
Great feedback as usual @bjarnef - thanks.  Going to work through the points you've raised.

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463

**Comment by bjarnef** [comment]
@AndyButland it would be great to update the reCAPTCHA v3 screenshot here https://umbraco.com/blog/umbraco-forms-87-release/ to match the final release 👍

**Comment by AndyButland** [comment]
Good idea, I've taken a new screenshot and provided it to the comms team, so that'll get updated.
