### ISSUE TITLE
8.7RC: Consider using toggle for enabled/disabled settings properties

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#508]
Something often discussed when it comes to UX: Should a toggle of checkbox be used.
I don't think that there's a silver bullet for this, but a general rule of thumb is that a toggle works well for settings that can be enabled/disabled, while checkbox is useful for something that is optional.

There are several articles about this topic out there. Here are  a few examples:
https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8
https://www.nngroup.com/articles/toggle-switch-guidelines/

For example in the "Active" property on a workflow I think a toggle makes perfectly sense to use:

![image](https://user-images.githubusercontent.com/2919859/112271589-69deb080-8c7b-11eb-8b4e-0d3adab734f8.png)

An example where a toggle already is used.

![image](https://user-images.githubusercontent.com/2919859/112272280-4bc58000-8c7c-11eb-9e17-11cdb08c1e67.png)

![image](https://user-images.githubusercontent.com/2919859/112275147-9268a980-8c7f-11eb-86b2-9364813a4569.png)

**Comment by bjarnef** [comment]
I think it makes sense to use toggles for "manage" properties.
Regarding "Has Access" I think it might be okay to use a checkbox for this or alternatively maybe this could use toggle group like in permissions overlay on content (but not sure if this is a bigger change).

![image](https://user-images.githubusercontent.com/2919859/112446284-54878600-8d50-11eb-94c1-6e17872c6aca.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
