### ISSUE TITLE
8.7RC: Ensure overlays can be closed using ESC key

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#509]
In the various overlays we should ensure these can be closed via `esc` shortcut, e.g. in workflow overlay.

It should simple have `shortcut="esc"` on the close button.
https://github.com/umbraco/Umbraco-CMS/blob/d966e89fd97edb9986516259456465f2fad03261/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html#L32

Currently I can't close any of the overlays in the workflow configuration overlay, field overlay, column/group settings.

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
