### ISSUE TITLE
8.7RC: Caret is a bit off in conditions overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#510]
In the conditions overlay the caret/arrow isn't aligned in the dropdown.
It would be great to have this vertically aligned in the dropdown.

It would also be great to align the fields dropdowns with the text input fields.

![image](https://user-images.githubusercontent.com/2919859/112272560-a8289f80-8c7c-11eb-98d5-09e4474c712e.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
