### ISSUE TITLE
8.7RC: Change turquoise color

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#511]
Currently Umbraco Forms is still using the turquoise color a few places, but in Umbraco v8 I think this has pretty much been removed from UI.

Could we update these colors to match the Umbraco v8 UI?

![image](https://user-images.githubusercontent.com/2919859/112273066-369d2100-8c7d-11eb-88bc-26281f5430e9.png)

![image](https://user-images.githubusercontent.com/2919859/112273825-13bf3c80-8c7e-11eb-84da-10363e7f3842.png)

![image](https://user-images.githubusercontent.com/2919859/112274291-97792900-8c7e-11eb-9135-0fbb2fc00fd4.png)

Perhaps something like this or variants of the purple color?

![image](https://user-images.githubusercontent.com/2919859/112273254-6cdaa080-8c7d-11eb-9263-26de0095a56e.png)

**Comment by AndyButland** [comment]
You've a better eye than me I'm sure, and have proably looked a lot closer at conventions in the Umbraco back-office - can you let me know what HEX colour you think best to use here please?  Not sure about the reddish one above though, as red tends to suggest validation error or similar.

**Comment by bjarnef** [comment]
@AndyButland yeah it should probably be another color variant than the pink/red as it looks too much like an validation error.
Maybe have a look at the variables here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/variables.less

I think something like a lighten version of a color + a darker color as border.

**Comment by AndyButland** [comment]
Then perhaps the purple is best as you also suggested:

![image](https://user-images.githubusercontent.com/1993459/112302917-f26d4900-8c9b-11eb-9b6d-c1f7ca9149f5.png)

Look OK to you?

**Comment by bjarnef** [comment]
Yeah, I think that fits better than the turquoise color at least :)

Also this issue here is a bit related, but would be great the ensure the "Add Condition" button always start on next line:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/512

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
