### ISSUE TITLE
8.7RC: Clear line before add condition

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#512]
Could we clear the line here before the "Add Condition" button.
Currently it is jumping a bit from no condition to one or more conditions.

![image](https://user-images.githubusercontent.com/2919859/112273644-da86cc80-8c7d-11eb-8f4a-a1a399665f32.png)

![image](https://user-images.githubusercontent.com/2919859/112273676-e4a8cb00-8c7d-11eb-829a-09b9a2c40950.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
