### ISSUE TITLE
Update style of root node picker in data source

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#513]
In prevalue sources consider to update the style of root node picker to match the style in MNTP configuration.

![image](https://user-images.githubusercontent.com/2919859/112274609-fa6ac000-8c7e-11eb-84cd-111dab7bac4f.png)

also here in worflow:

![image](https://user-images.githubusercontent.com/2919859/112277985-a2ce5380-8c82-11eb-8fde-1ae5c6b07d23.png)

![image](https://user-images.githubusercontent.com/2919859/112274896-4d447780-8c7f-11eb-9e47-f1e78d38587c.png)

![image](https://user-images.githubusercontent.com/2919859/112274942-559cb280-8c7f-11eb-97e1-ed240d5ca921.png)

**Comment by AndyButland** [comment]
Thanks again for all the feedback @bjarnef.  I've resolved all apart from three - of which this is one - which are now in a PR for review.  So we should be able to get them all in for the 8.7 release.

As this isn't strictly an issue with the RC, rather an improvement on what's existing already, I'm going to leave this for the backlog and we'll tackle another time. // @nul800sebastiaan

**Comment by AndyButland** [comment]
I'll close this one now for a similar reason to an earlier issue updated today.  We'll be re-implementing the Forms UI as part of the new back-office project and in doing that we'll be reusing elements from the CMS, and hence will at least start off again aligned with the CMS UI patterns.
