### ISSUE TITLE
Use editor service to open form picker in datatype configuration

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#514]
In form picker datatype configuration the "allowed forms" picker it seems to use the old `<umb-overlay>` instead of editorService / infinite editor.
 
![image](https://user-images.githubusercontent.com/2919859/112275276-bb893a00-8c7f-11eb-88cb-e1e747698a4d.png)

It seems to be the same picker used in content section.

![image](https://user-images.githubusercontent.com/2919859/112275845-56821400-8c80-11eb-833f-8f267f6f549c.png)

**Comment by AndyButland** [comment]
Thanks again for all the feedback @bjarnef.  I've resolved all apart from three - of which this is one - which are now in a PR for review.  So we should be able to get them all in for the 8.7 release.

As this isn't strictly an issue with the RC, rather an improvement on what's existing already, I'm going to leave this for the backlog and we'll tackle another time. // @nul800sebastiaan

**Comment by bjarnef** [comment]
Just checked this in Umbraco Forms v8.8.0

![image](https://user-images.githubusercontent.com/2919859/133927519-dfddc72f-184b-4b36-8568-cbf44f4f7950.png)

It would be great to use infinite editing here instead and remove the `<umb-overlay>` used in view. It should probably add an `formpicker` infinite editor if it not already exists. Developers could re-used this if needed.

Furthermore it should use `<button>` element instead for the add button:

```
<a ng-if="!vm.selectedForm.name" class="umb-node-preview-add" href="" ng-click="vm.openFormPicker()" prevent-default="">
      <localize key="general_add">Add</localize>
</a>
```

should be this instead:

```
<button type="button" ng-if="!vm.selectedForm.name" class="umb-node-preview-add" ng-click="vm.openFormPicker()">
      <localize key="general_add">Add</localize>
</button>
```

**Comment by AndyButland** [comment]
I'll close this one now for a similar reason to an earlier issue updated today. We'll be re-implementing the Forms UI as part of the new back-office project and in doing that we'll be reusing elements from the CMS, and hence will at least start off again aligned with the CMS UI patterns.

The point about the infinite editor may or may not be handled when we do this implementation, but if not, it's tracked in another issue [108](https://github.com/umbraco/Umbraco.Forms.Issues/issues/108).
