### ISSUE TITLE
Update styling of node picker in "Message on submit"

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#515]
In the "Message on submit" overlay consider updating the "Go to page" button the match most other pickers in the Umbraco UI, e.g. using `<umb-node-preview>`.

![image](https://user-images.githubusercontent.com/2919859/112276010-8204fe80-8c80-11eb-9e61-19ffc679c009.png)

**Comment by AndyButland** [comment]
Thanks again for all the feedback @bjarnef.  I've resolved all apart from three - of which this is one - which are now in a PR for review.  So we should be able to get them all in for the 8.7 release.

As this isn't strictly an issue with the RC, rather an improvement on what's existing already, I'm going to leave this for the backlog and we'll tackle another time. // @nul800sebastiaan

**Comment by AndyButland** [comment]
It seems there was a reason historically to create a custom content picker for forms - i.e. `<umb-forms-content-picker />`.  I've kept this in place but updated to add the feature that was missing - the path to the selected items - which was done as part of resolving #931.  So will close this as I don't think we'll look at updating this further until the time of the major back-office rewrite.
