### ISSUE TITLE
8.7RC: It is possible to add empty extension in File Upload field

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#516]
In the File Upload field you will get an error if trying to add an empty extension (however the validation could be improved here).
But if you then an extension "test" an remove this again, it is possible to an empty extension.

![Ha4NrLsm9D](https://user-images.githubusercontent.com/2919859/112278933-a1515b00-8c83-11eb-949c-fd50a719bc46.gif)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
