### ISSUE TITLE
8.7RC: Update UI for Allowed file upload types

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#517]
Currently in the File Upload field there's a "Allowed file upload types" checkbox.
However I would like if this could be changed to a toggle instead. It should probably still show the extensions, so it is possible to see when a new extension is added.
Furthermore this could be on a separate line so it clears the line before listing the checkboxes.

When the "Allow all files" toggle is enabled, we could disable the extension checkboxes and maybe check/uncheck the checkboxes as this toggle is enabled/disabled?

![image](https://user-images.githubusercontent.com/2919859/112279797-9814be00-8c84-11eb-8720-e7b93c7cc51f.png)

Furthermore I think there should be enough space in overlay to fit 3/4 columns instead of just 2 to list the extensions. The placeholder text "Add new allowed filed type" should probably be changed to "Add new allowed file type".
It could look something like this:

![image](https://user-images.githubusercontent.com/2919859/112281602-88967480-8c86-11eb-846f-d2d9a9a0ced1.png)

or this:

![image](https://user-images.githubusercontent.com/2919859/112281985-f2168300-8c86-11eb-8aab-c21d085ddd82.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
