### ISSUE TITLE
8.7RC: Prevent password manager on group name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#518]
It seems a password manager like LastPass mark the group name input field.
In Umbraco core we have a `noPasswordManager` directive. Could we add this to the input? :)
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/util/noPasswordManager.directive.js

```
<input type="text" no-password-manager />
```

![image](https://user-images.githubusercontent.com/2919859/112304996-73c5db00-8c9e-11eb-999d-9eb7bf6d204b.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
