### ISSUE TITLE
8.7RC: Update styling of reorder

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#519]
It would be great if the styling of reorder could be updated a bit to match the Umbraco core UI.
For example the button style in "Reorder" / "I am done reordering".

![image](https://user-images.githubusercontent.com/2919859/112306141-c94eb780-8c9f-11eb-84ec-d30ed1ce49a3.png)

![image](https://user-images.githubusercontent.com/2919859/112305958-93a9ce80-8c9f-11eb-8086-5da3f1597372.png)

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463

**Comment by bjarnef** [comment]
The button has been updated.

![image](https://user-images.githubusercontent.com/2919859/113735529-9d4e2000-96fc-11eb-97dd-938fc7814b90.png)

But it would also be great to update the styling of the fields to match core, where also a larger part of the row is draggable.

![image](https://user-images.githubusercontent.com/2919859/113735670-bfe03900-96fc-11eb-9dfd-c818a179cfad.png)
