### ISSUE TITLE
8.7RC: Set upper limit of number of columns in group

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#520]
I wonder if there should be a upper limit for the number of columns in group to be added?
Currently there isn't a restriction.

I guess in most cases 12 - 20 columns should be sufficient?

![image](https://user-images.githubusercontent.com/2919859/112307333-1e3efd80-8ca1-11eb-99c1-3d366aff198a.png)

**Comment by nul800sebastiaan** [comment]
@AndyButland This relates to https://github.com/umbraco/Umbraco.Forms.Issues/issues/404 - not sure what would be best to do here?

**Comment by AndyButland** [comment]
Yes, I noticed that it was linked to that issue - have added a configurable limit, defaulted to 12, in the PR for review linked above.

**Comment by warrenbuckley** [comment]
Fixed in this PR & due for 8.7.0
https://github.com/umbraco/Forms/pull/463
