### ISSUE TITLE
8.7RC: Recaptcha v3 expect input submit

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#521]
I noticed in the new Recaptcha v3 field type that the javascript expect an input using `type=submit`. This is fine, but it doesn't take into account that you might want to use a custom them overriding the Form partial view to use `<button type="submit"`>Submit</button>` instead. This is sometimes useful if you e.g. want to add an inline `<svg>` icon or another child element, which `<input type=submit` />` doesn't allow.

We an of course override the `Fieldtype.Recaptcha3.cshtml` in our custom theme, but I wonder if we can modify the following the support `<button>` element as well?

```
hiddenField.form.querySelector('input[type=submit]').removeAttribute('disabled');
```

It could be something like:

```
hiddenField.form.querySelector('[type=submit]').removeAttribute('disabled');
```

or

```
var btnSubmit = hiddenField.form.querySelector('input[type=submit]') || hiddenField.form.querySelector('button[type=submit]');
btnSubmit.removeAttribute('disabled');
```

**Comment by warrenbuckley** [comment]
Fixed in this PR due for 8.7.0
https://github.com/umbraco/Forms/pull/464
