### ISSUE TITLE
 Adding a condition on either a question or group within Umbraco forms does not work

### ISSUE THREAD

**Issue by TrissM** [umbraco/Umbraco.Forms.Issues#522]
Adding a condition on either a question or group within Uno Umbraco forms does not work.

Reproduction
------------

1. Create a new form within Uno Umbraco Forms
2. Create a dropdown with yes/no values question within group, let's label it Question A 
3. Create another group within page
4. On group just created, click the settings cog and check enable conditions
5. Condition should be **show this fieldset if all of the following match:** Question A is Yes
6. Click Submit
7. Save Form
8. Add Form to a test page
9. Preview Form

### Bug summary

The form isn't adhering to conditions and within the developer console I can see the following error:

![image](https://user-images.githubusercontent.com/4612862/112627484-9801f300-8e29-11eb-9856-c67d117cf4e8.png)
 
it appears to be this reported error

https://our.umbraco.com/forum/using-umbraco-and-getting-started/102784-conditional-logic-in-umbraco-forms-841

**Comment by AndyButland** [comment]
Looks like this is related too: https://github.com/umbraco/Umbraco.Forms.Issues/issues/273
