### ISSUE TITLE
Disable add column button when limit has been reached

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#526]
In Umbraco Forms v8.7.0 the column functionality has now been updated, so it has a max limit. https://github.com/umbraco/Umbraco.Forms.Issues/issues/520

However when max limit is reached, it would be great to disable the button "Add Column", e.g. use `ng-disabled`.
Otherwise editor may wonder why nothing happens when clicking the "Add Column" and 12 columns are added.

![image](https://user-images.githubusercontent.com/2919859/113736237-354c0980-96fd-11eb-874f-e5142c609534.png)

---
_This item has been added to our backlog [AB#11274](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11274)_

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I've added it to the list for @AndyButland to have a look at when he has some time. 👍

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
