### ISSUE TITLE
Update placeholder text in copy form

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#527]
When copying a form the placeholder text may be a bit misleading "Copy of [Form Name]" and since the placeholder text isn't the default if left empty, where it will get the name "[Form Name] (1)".
Furthermore it could be confused with a filter/search input.

![image](https://user-images.githubusercontent.com/2919859/113774621-cdf77f00-9727-11eb-9394-7ab44289d36e.png)

It would probably be better to use a placeholder text like "Enter name of form" or a label like when creating a document type folder.

![image](https://user-images.githubusercontent.com/2919859/113775146-9210e980-9728-11eb-8b68-6d3622b94bf7.png)

---
_This item has been added to our backlog [AB#11275](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11275)_

**Comment by nul800sebastiaan** [comment]
Makes sense to me, I would say you should still get this default name if you leave it empty, not quite what we do anywhere else, but we wouldn't want to break people's existing workflows.

**Comment by bjarnef** [comment]
Yeah, but at first sight I didn't know what the input was for, but then I recall it was the name of the copied form 😅
A default name like now when leaving it empty is fine though 👍

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
