### ISSUE TITLE
Update delete button color

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#528]
When deleting a form, the confirm button currently doesn't match rest of backoffice UI, which are using a red button.

![image](https://user-images.githubusercontent.com/2919859/113775407-f16ef980-9728-11eb-930c-dbabde3a9f33.png)

![image](https://user-images.githubusercontent.com/2919859/113775344-d8fedf00-9728-11eb-8345-40fcbd0ff75a.png)

---
_This item has been added to our backlog [AB#11276](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11276)_

**Comment by nul800sebastiaan** [comment]
Good one! 👍

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
