### ISSUE TITLE
Slow performance when using the RenderForm action

### ISSUE THREAD

**Issue by mikkelhm** [umbraco/Umbraco.Forms.Issues#53]
When inserting a form on a page in Umbraco, we do it by calling the Macros `InsertUmbracoForm` or `InsertUmbracoFormWithTheme`

Those macros calls the `RenderForm` action on the `UmbracoFormsController`.

In some circomstances the renderform method takes up way too long time to do what it needs - On a specific site, the method takes 1 second in its own (found via the MiniProfiler) - The site has one or more forms on each page, therefore slowing down performance overall on their site.

For this site in particular, they seem to have a ok amount of forms in their backoffice, 32, but they are also large forms. Their json representations are taking up 6.58MB in the App_Data/UmbracoForms/Forms folder.

The size of the forms seem to relate to the issue, as on a site with almost no forms, the methods are more or less instant.

**Comment by nul800sebastiaan** [comment]
PR was merged long time ago, closing this one.
