### ISSUE TITLE
Add the ability to toggle the field labels

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#530]
It would be extremely useful to be able to toggle the field labels.

I have been able to achieve this in my uCaptcha plugin with the code below, which should be usable.

```
[Setting("Show Label", Description = "Show the property label", View ="~/App_Plugins/UmbracoForms/Backoffice/Common/SettingTypes/checkbox.html")]
        public string ShowLabel { get; set; }

public override bool HideLabel => !Parse.Bool(ShowLabel);
```

---
_This item has been added to our backlog [AB#12725](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12725)_

**Comment by nul800sebastiaan** [comment]
Thanks! We'll have to have a look for which, if not all field types this makes sense. 👍

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Forms/pull/533 and is due for release in 8.8.0
