### ISSUE TITLE
V8.7 Recaptcha -  Cannot set property

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Forms.Issues#533]
A brief description of the issue goes here.

Reproduction
------------
### Bug summary

When setting up a form with the new Recaptcha you either get a console error where the property is not defined, like this:

![image](https://user-images.githubusercontent.com/32164310/114162603-8c362680-9929-11eb-9f2f-1426dac0e202.png)

If you got more fields than one, then each field will report this error:
![image](https://user-images.githubusercontent.com/32164310/114164078-2d71ac80-992b-11eb-82ee-c48f9d095306.png)

![image](https://user-images.githubusercontent.com/32164310/114164095-32cef700-992b-11eb-8777-8ddc80f96bf4.png)

### Specifics

Umbraco 8.12.2
Forms 8.7.0

Chrome, Firefox, IE, and Brave

### Steps to reproduce

Spin up a 8.12 site with 8.7 Forms install.
Apply reCapv3 keys to formssetting.

Do the following: 

Make doctype to serve as rootnode.
Set forms picker in.

Create a form, containing one or more questions and the new reCapv3 field.

Set in the form with the macro form picker.

### Expected result

Expected behaviour: that the form submits without any errors in the console.

### Actual result

The form does submit the entry. However if your form contains 15+ fields you can easily get lost in the console, when trying to debug.

**Comment by AndyButland** [comment]
Thanks for reporting @Frost117 - I've had a quick check and don't think this is actually Recaptcha related, rather the same issue as is reported here:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/531

I've resolved this for an 8.7.1 release which will be available on Tuesday next week.  Meantime there's a workaround in the linked issue - a small update to the `umbracoforms.js` file - which hopefully you can apply if you need the update before then.  Apologies for the error on this one but should be quick to resolve.
