### ISSUE TITLE
Magic Strings for member properties do not reflect updates

### ISSUE THREAD

**Issue by pmeliesIology** [umbraco/Umbraco.Forms.Issues#534]
Per support request #59163 I'm submitting this bug report.

We're using Umbraco Forms and a custom WorkflowType to build a "Update profile" page for members. On the form itself we're using Magic Strings to display current member properties as they exist at the time the form is loaded. ex - {member.FirstName}, etc.

The workflow is operational. It properly updates the member properties based on what's submitted from the form. However, when the form is reloaded the default values from the Magic Strings aren't showing the updated member property values.

Reproduction
------------

### Bug summary

Umbraco Forms fields set with member Magic Strings are not showing updated values after a member updates their profile.

### Specifics

Umbraco version: 8.11.2
Umbraco Forms: 8.6.1

### Steps to reproduce

1. Create an Umbraco Form for updating a member profile.
2. In each of the fields of the form set the default value using member magic strings, such as {member.email}.
3. Create a custom workflowtype to update the member profile based on the values of the form.  I suspect you could also go directly into the back office and update member properties there - we didn't test this path though.
4. When the member views the form in the UI after changing their profile values the form is still displaying the old values. It's behaving as if the original form values are being cached somewhere. 

### Expected result

Form displays correct values for member properties after those properties have been updated while the member is logged in.

### Actual result

Old, "cached" values are being displayed.

**Comment by nul800sebastiaan** [comment]
Thanks @pmeliesIology, I'll have a look at what's going on here and will get back to you.

**Comment by AndyButland** [comment]
Have had a look at this - we have a cache in place for the member data, presumably to optimise retrieving them if several profile values are used on the form.  This isn't cleared currently on member save though - whether through the API in a workflow, or via the back-office - but we can add that.
