### ISSUE TITLE
Date Picker is missing placeholder

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#537]
The date picker should have the placeholder configuration setting.

On forms which do not use labels, the field is completely blank, the placeholder is a supported attribute for this input type.

---
_This item has been added to our backlog [AB#11452](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11452)_

**Comment by nul800sebastiaan** [comment]
Thanks, not sure why it's not implemented at the moment. Would you expect there to be a text in it, or a default date/time? Just looking for the practical use case here.. not sure I've seen date fields with a placeholder before. 🤔

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan On this particular clients form there are no labels, only placeholders.

I have created by own custom field type to solve this, however for what is 2 lines of code in the filedtype definition, I feel it should be there...

```[Setting("Placeholder", Description = "Enter a HTML5 placeholder value", View = "TextField")]
        public string Placeholder { get; set; }
```

![image](https://user-images.githubusercontent.com/9937803/114556800-f79d3280-9c60-11eb-8a5b-af4723a6528a.png)

**Comment by nul800sebastiaan** [comment]
Cool! I didn't realize the date field by default just looks like an empty textbox, definitely nice to allow a placeholder text there! 👍

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
