### ISSUE TITLE
Option to keep historical field data

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#538]
If I modify an existing form by removing a field, there should be an option to keep any historical data captured by this field, and keep it visible within the back office.

For example, if I had a field called "Full Name" but then I later decide to split this into "First Name" "Last Name", the data captured from the historical data is still required within "Full Name" and should not be lost.

**Comment by nul800sebastiaan** [comment]
This currently "works" just fine, rename the existing "Full Name" field to "First Name" (or "Last Name") and the full name that was already in there gets preserved. 

What I am hearing here, however, is that you would love a "refactor form" feature. We at HQ have a wish for that as well (just like we would LOVE to have a "refactor document type" feature). 

Unfortunately this is not something we have on the roadmap at the moment but it would be great to have in the future. I'll put this on the list of ideas.

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan Thinking outside the box there, I never would have thought of that 🤯 thanks! 😁

**Comment by AndyButland** [comment]
I'll close this issue as the original request was already handled, and the further discussion leads to a much bigger issue that needs it's own scoping/feasibility.
