### ISSUE TITLE
Mini RFC: On whether to support "forms on disk" in V9

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Forms.Issues#540]
With the V9 of Umbraco running on .NET Core on it's way, we've started the work for migration of the Forms package to run on the new version.

It'll be a breaking change of course, so a new major version of Forms too - V9.

Over the course of V8 development, the ability to store form and other entity definitions in the database, rather than files on disk, [was introduced](https://umbraco.com/blog/umbraco-forms-85-release-forms-in-the-database/).  The old way was internally obsoleted, but still supported, and a [migration was made available](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Forms-in-the-Database/) to move to the new database storage option.

From the HQ view, the database storage is the better option to use - mainly due to being more appropriate for load balancing setups, and aliging with how other Umbraco object schema definitions are stored.

As such we are considering whether to make this storage option the only one available from V9 onward.  It would simplify things somewhat of course in terms of maintenance and testing to just have one storage method to support.

I'd like to ask the community though via comments on this issue whether anyone sees significant benefit in maintaining the ability to store forms on disk, so we can consider that input in making the decision.  Many thanks in advance for your views.

**Comment by NikRimington** [comment]
Hey Andy.

So my initial thoughts are:

1. This sounds like a good idea to me.
2. If people aren't happy about it, could it be this way: the "Form Storage" mechanism be something that could be replaceable? For example, OOTB in v9 it ships with DB storage, but if someone wanted to store the definitions somewhere else in a different format, e.g. the old XML format, they could replace the storage mechanism with their own/community implementation.

**Comment by Matthew-Wise** [comment]
Hi Andy,

I think the database is definitely the place to be, I would like to be able to use a different database than the main Umbraco database though. So we can leave form entries in a live environment, easily for GDPR when doing database restores to other environments.

Matt

**Comment by skttl** [comment]
I'm with Matt, would be great if you could have a seperate database for forms.

**Comment by AndyButland** [comment]
Thanks so far...

> could... the "Form Storage" mechanism be something that could be replaceable

@NikRimington - yes, there'll be an `IFormService` and similar for the other entities, so in theory this could be swapped

> I would like to be able to use a different database than the main Umbraco database

@Matthew-Wise @skttl - agree, this would be nice, and there's at least a couple of long-standing feature request issues for this in the issue tracker.  The bigger reason for this I'd imagine though is for the form submissions rather than the definitions (and these have always been in the database).

Without wanting to side-track this topic too much... I have started some discussions on this but I think to do it right it needs to be supported in CMS.  Rather than rolling it's own, Forms leans quite heavily on CMS code for data access and migrations etc., and there's not a way supported there to add in a different connection string for certain operations.  I can see it would be valuable for core features like members and likely other packages too so hopefully it'll get some traction.

**Comment by BatJan** [comment]
Definently go with the database option. Not sure why the file based approach was ever a thing - It's created some headaches for the companies I've been working with during the years. So happy to see they're back in the database where they belong IMHO 👍🏻

**Comment by c9mbundy** [comment]
+1 for DB only - Repository changes every time a form is altered is just a pain-point for me with Umbraco-Cloud and Baseline configs - touch a form on a Baseline-Master and it wants to deploy that to every Baseline-Child.

**Comment by hfloyd** [comment]
I agree with the general consensus here - If the intention of Umbraco Forms is to allow Editors to create forms via the back-office - like they can manage Content and Media, then those form definitions should be treated like Content/Media - stored in the DB, transferable via Deploy, etc.

I can also see the advantage of having things like form ENTRIES and Member data stored in a separate DB, FWIW.

**Comment by skartknet** [comment]
I think we should be able to configure where to store them, either DB or files.

Personally, I have never had issues storing them as files. We normally use Azure Storage for them so we don't have issues with load-balanced setups.

One benefit of having them in files is that if the client changes anything on production we can replicate any changes to development just by copying the file. Also, we can keep them on source control if we want.

**Comment by dampee** [comment]
The only use case which I can imagine is on a test scenario with local databases if you do integration testing. 

But to be honest, I never understood why they where stored on disk.

**Comment by AndyButland** [comment]
Thanks for the feedback on this issue all - it seems there's a general consensus that it would be reasonable to only support database storage moving forward.  As @BatJan summarises, it does make things simpler moving forward to only have one way to support - which otherwise needs to be accounted for in testing different features, as well as making supporting tools like Deploy more complicated than is otherwise necessary.

@skartknet - you've raised really the only dissenting points, which are reasonable ones.  There are other tools - Umbraco Deploy, uSync Complete - that will help with the source control and replication between environments - but of course I do realise that means an additional cost for this purpose.

I'm wondering though if we could consider adding a simpler import/export function for forms as part of the package itself, for anyone not using one of these tools.  So you can right-click a form and export it to, and similarly browse to import a form from a file.  Similar to how you can do with document types in the back-office.  If we had that, seems we could meet the requirements you've noted you'd still like to be able to support.

**Comment by AndyButland** [comment]
Closing this issue now, and have a raised a new issue for the specific feature of creating an import/export feature for V9.
