### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#541]
Email is not being sent for a form with sending email in workflow

Reproduction
------------

Create a form with a workflow that includes sending email.

SMTP can be set in web.config as follows to test in dev. The issues happens for any smtp settings.
```
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory" from="noreply@domain.com">
        <specifiedPickupDirectory pickupDirectoryLocation="c:\mail" />
      </smtp>
    </mailSettings>
  </system.net>
```

### Bug summary

Email should be sent but email is not sent

### Specifics

The issue only happens in v7.5 of UmbracoForms.Core

I tried downgrading to 7.4.2 with no other changes and emails works with 7.4.2

### Steps to reproduce

See above under reproduction

### Expected result

email sent

### Actual result

email not sent

**Comment by nul800sebastiaan** [comment]
Hey there @russellshome, I just had a look and there's an unfortunate problem in the code, we currently only send the email if you enable the checkbox to send attachments! 🙈 Sorry about that, we're on it, but for now you can work around it by checking attachments on.

![image](https://user-images.githubusercontent.com/304656/115205798-36683800-a0fa-11eb-8b3c-553f05dd122b.png)

**Comment by AndyButland** [comment]
This has been resolved in the above linked PR and tested, due in the next patch release (currently planned for Tuesday 27th April).  Thanks for reporting.
