### ISSUE TITLE
Javascript "Submit" corrupted on all forms after Auto Upgrade Umbraco Forms v7.5.0 on 09 April 2021

### ISSUE THREAD

**Issue by NicolaSA** [umbraco/Umbraco.Forms.Issues#542]
Urgent: Javascript "Submit" corrupted on all forms after Auto Upgrade Umbraco Forms v7.5.0 on 09 April 2021

Looks related to:
Date: 09 April 2021 09:14:53
Committer: Umbraco Cloud
Upgrade files for Umbraco Forms version 7.5.0

Can anyone assist on the  javascript error please?
Screenshot attached

Reproduction
------------
E.g. Submit a form, nothing happens after Submit  button is clicked. 
See dev tools for javascript error F12. 

https://www.stonewater.org/get-involved/making-a-complaint/#complaintform
Shorter form: https://www.stonewater.org/find-a-home/retirement-living/north-east/abbey-lodge-lenton-abbey-nr-nottingham/

![AllForms_Broken_after_Umbraco Forms v7 5 0 uprade](https://user-images.githubusercontent.com/4188727/115223070-b34fdd80-a10b-11eb-9846-f2f128118c7a.png)

**Comment by NicolaSA** [comment]
Hi Dev Team,
My colleague has found the culprit.
please could you aid with an emergency patch, our initial patch attempts are not quite there yet.

"
Related to FieldType.Checkbox.cshtml changes - before patch it was 1 input, post patch it's 2 inputs but one is missing a 'name' attribute, jquery validate lib attempts some parsing by name, since name was missing null was returned for object hence 'x undefined'
"

Standing by,
Nix

**Comment by nvisage-gf** [comment]
Adding a name attribute to the second checkbox (e.g. `name="ftCheckbox_@Model.Name"` resolves jquery.validate issue with finding checkbox, however validation messages currently not displaying if checkbox required.

**Comment by nvisage-gf** [comment]
We are downgrading to 7.4.2 since #541 is critical issue too.

**Comment by AndyButland** [comment]
This has been resolved in the above linked PR and tested, due in the next patch release (currently planned for Tuesday 27th April).  Thanks for reporting (and diagnosing!).
