### ISSUE TITLE
When copy a form, also copy workflow configuration

### ISSUE THREAD

**Issue by galaxxy22** [umbraco/Umbraco.Forms.Issues#543]
At the moment, copying a form will not copy over the workflows you have added. 

![760dda0e7baea15944de1f3c85dece12](https://user-images.githubusercontent.com/16100922/115233649-763e1800-a118-11eb-8d23-0fa3078a03bf.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request @galaxxy22, I'm not sure why this hasn't been requested before.

I do want to point out that this could potentially be "dangerous", you might end up accidentally sending data to people that you didn't realize were in the "Send email" workflows or something like that. Maybe we need a toggle saying: "Also include these workflows"..

**Comment by inetzo** [comment]
Coincidentally, I was also just pointed this out by a colleague. I thought this was a bug but apparently a feature ;-)

+1 for this feature!

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
