### ISSUE TITLE
Previous button not behaving correctly in multi page forms

### ISSUE THREAD

**Issue by itsliamprowse** [umbraco/Umbraco.Forms.Issues#547]
Paged Umbraco Form goes to the next page instead of the previous when clicking the previous button

Reproduction
------------

### Bug summary

The previous button on multi page forms does not take you to the previous page, but takes you to the next/submit

### Specifics

Umbraco 8.12.2
Umbraco forms 8.7.1

### Steps to reproduce

Create a multi page form, render it on a page complete the first page, then on the second page press the previous button, you will be taken to the third page instead of being taken back to the first

### Expected result

For the user to be taken back to the previous page

### Actual result

The form behaves as if the next/submit button has been pressed

**Comment by AndyButland** [comment]
Hi @itsliamprowse - I've tried to replicate this one, but I'm not able to.  I've got a simple 3 page form, with one text string question on each page.  And with JavaScript disabled and enabled, it looks to work as expected.

Are you able to share any more details of your setup (or even a link to the form if it's live somewhere) so I can take a look further please?  Thanks.

**Comment by itsliamprowse** [comment]
Hi @AndyButland I created this issue because Dennis in your support was able to reproduce it, he asked me to create this issue, is there a way for me to share a link privately? as this is a clients site and needs confidentiality.
Thanks

**Comment by AndyButland** [comment]
Sure, if you don't mind me only seeing it - I won't share it further - you can email me at _abl at umbraco dot dk_.

**Comment by itsliamprowse** [comment]
@AndyButland Sorry for the delay, have emailed you a link :)

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
