### ISSUE TITLE
Validation is retained when answer type is changed

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#548]
When an answer type is changed it should not keep any validation associated with the previous answer type.

Reproduction
------------

Create a form with a Multiple choice answer.
Set the multiple choice answer to mandatory
Set the items to "choice 1" and "choice 2"
Submit and Save

Change the answer type of the Multi choice answer to Long answer
Submit and Save

### Bug summary

Add the form to a page
View the page and attempt to submit a value of "test" as the Long answer

Outputs an error "Unexpected value: 'test'. Expected one of these: 'choice 1', 'choice 2'"

### Specifics

v8.7.1 But I suspect this behaviour is the same for any version

### Steps to reproduce

See above

### Expected result

Any error message should relate to the answer type - not a previously set answer type.

### Actual result

When multi choice is changed to Long answer then an error is output for valid content

---
_This item has been added to our backlog [AB#11607](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11607)_

**Comment by nul800sebastiaan** [comment]
Thanks @russellshome, that's definitely a bug! We'll have to have a look at how we can fix that one.

**Comment by AndyButland** [comment]
Resolved in the linked PR and due in 8.7.2,
