### ISSUE TITLE
Cant update a record field from workflow since updating from 7.4.1 to 7.5.0

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#549]
I update a record field (a hidden field) from a workflow setting it to a calculated value.
It worked ok, but since updating from 7.4.1 to 7.5.0 the value is saved on the database as empty value.
This is the code (simplified) i use to store the value:

`
public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)

        {

            if (record.RecordFields.Any(f => f.Value.Alias == "fieldAlias"))

            {

                var fieldObj= record.RecordFields.First(r => r.Value.Alias == "fieldAlias");

                 fieldObj.Value.Values.Clear();

                  fieldObj.Value.Values.Add("new value");

            }

          }
`

**Comment by AndyButland** [comment]
Thanks for reporting, can confirm there has been an issue introduced here - will resolve the patch release due on Tuesday next week.
