### ISSUE TITLE
EPPlus dll is missing when updating to Forms v7.4.2 via nuget on UmbracoCms 7.15.7

### ISSUE THREAD

**Issue by timeverts** [umbraco/Umbraco.Forms.Issues#550]
I've recently updated an Umbraco Forms installation from 7.4.1 to 7.4.2 and deployed that to Azure. Now when I try to use the "Export" functionality on Entries, instead of a downloaded Excel sheet, the following error is output in the logs:

```
ERROR Umbraco.Forms.Web.Editors.ExportController - Unhandled controller exception occurred
System.IO.FileNotFoundException: Could not load file or assembly 'EPPlus, Version=4.0.5.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.
```

The strange thing is that I see `<package id="EPPlus" version="4.0.5" targetFramework="net451" />` listed in my `packages.config` but the `epplus.dll` file does not exist in my `bin` folder.

There's a hint that other users are perhaps experiencing this issue too as per [this](https://our.umbraco.com/forum/using-umbraco-and-getting-started/85035-umbraco-forms-440-not-exporting#comment-328146) Umbraco forum comment from Feb 2021.

### Workaround
There is a simple workaround. From [Our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/), you can download a zip file with the Umbraco Forms files. That zip file will contain the EPPlus.dll in the bin folder. Find the same version of Forms as you are using and download it. Then copy the EPPlus.dll over to the bin folder of your project.

Reproduction
------------
### Specifics
UmbracoCms 7.15.7
Umbraco.Forms 7.4.1 to 7.4.2

### Steps to reproduce
1. Open solution in Visual Studio
2. Use package manager console to update UmbracoForms via nuget using `Update-Package UmbracoForms -Version 7.4.2`
3. Build solution
4. Fire up Umbraco and create a Form 
5. Output form on the front-end and submit an entry. 
6. Back in Umbraco, try to export all data to Excel for that form.

### Expected result
Excel file output

### Actual result
Error logged in log files:

```
ERROR Umbraco.Forms.Web.Editors.ExportController - Unhandled controller exception occurred
System.IO.FileNotFoundException: Could not load file or assembly 'EPPlus, Version=4.0.5.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.
File name: 'EPPlus, Version=4.0.5.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1'
   at Umbraco.Forms.Web.Providers.Export.ExportToExcel.ExportToFile(RecordExportFilter filter, String filepath)
   at Umbraco.Forms.Web.Editors.ExportController.PostGenerateExport(RecordExportFilter model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

**Comment by nul800sebastiaan** [comment]
Sorry you're experiencing this, I'm afraid we can't be of much help, NuGet should be downloading and installing this for you as it's a hard dependency for version 7.4.2 as you can see here when expanding "Dependencies": https://www.nuget.org/packages/UmbracoForms.Core/7.4.2

We don't have much we can do if NuGet doesn't do the right thing I'm afraid. I'll close this one and maybe you could file a bug report with NuGet instead.

Ps. Version 7.5.1 is out already, we would recommend an upgrade!

**Comment by timeverts** [comment]
So this has happened again, this time on a site when updating UmbracoForms 6.0.8 to 7.4.2 using nuget.

This time I examined what happened a bit closer. As part of the update, I noticed that the EPPlus reference is removed from the `.csproj` file, because it's no longer bundled with the UmbracoForms.Core package (like it was in older versions). 

![EPPPlus_reference_removed](https://user-images.githubusercontent.com/15150632/117776889-9de35480-b26e-11eb-9c43-88f2f87e81bf.png)

Since the reference is removed from the project, that's why the DLL no longer exists in the bin directory after the next build. 

A workaround is to manually add the reference back into the project for the EPPlus library, but it still seems a bit odd that this did not happen automatically as part of the version update.

**Comment by tomvanenckevort** [comment]
The reason that EPPlus doesn't get restored is because all v4.0.x releases of EPPlus on Nuget have been marked as [deprecated](https://www.nuget.org/packages/EPPlus/4.0.3).

And I'm guessing it's not automatically installing the nearest live version (v5.0.3) because the license has changed to LGPL with additional license requirements for commercial use.
