### ISSUE TITLE
No configuration options for default captions/labels

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco.Forms.Issues#554]
The UmbracoForms.config file does not contain a setting for any of the items in the captions category:

- 'Submit' button label
- 'Next' button label
- 'Previous' button label

Other similar text based settings can be set from there, so it seems like a good addition especially for small single-language sites.
It doesn't seem to be mentioned on the [configuration](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Configuration/) page of the docs, but I could have missed it elsewhere.

**Comment by nul800sebastiaan** [comment]
Hey there @krebil! This is actually something you can do on each Form, there's a "Settings" button to be able to configure the text of each of those buttons: 

![image](https://user-images.githubusercontent.com/304656/117997967-bec9a980-b343-11eb-92ee-c8e4aa2920ff.png)

**Comment by krebil** [comment]
Hey @nul800sebastiaan 
Indeed, it is configurable for each individual form, but unlike the fields in the validation category. The default values of the captions (when you create a new form) cannot be set in the configuration file.
