### ISSUE TITLE
Filtering Entries bug with language Dutch

### ISSUE THREAD

**Issue by rubenberendsen** [umbraco/Umbraco.Forms.Issues#560]
Hi,

We are using UmbracoForms 8.7.1 and the user in Umbraco has language Dutch.

If i want to filter on the entries:
![image](https://user-images.githubusercontent.com/38040580/117927119-104d4680-b2fa-11eb-9897-0322367b86eb.png)

In every prefilter it wil select januari:
![image](https://user-images.githubusercontent.com/38040580/117927182-222ee980-b2fa-11eb-936f-1a81ac53a214.png)

If i switch to English (US) this works fine.

This also is not working in Umbraco Forms version 8.6.1. 

---
_This item has been added to our backlog [AB#11984](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11984)_

**Comment by AndyButland** [comment]
Resolved by simply retaining default locale for the data filter (on the reasoning that the back-office for Forms isn't yet localised, so it doesn't really make sense to have just this one part in the local user's language).
