### ISSUE TITLE
Validation framework error message showing erroneously in the RTE (when dependencies are present)

### ISSUE THREAD

**Issue by rowenajbellamy** [umbraco/Umbraco.Forms.Issues#562]
Forms required dependencies message is being shown in the Rich Text Editor despite them being correctly present in the site.  Have been asked to raise this issue following a conversation with support. 

Reproduction
------------

### Bug summary

When a form is loaded via a Macro in the Rich Text Editor in the CMS, an error message is displayed alerting that "Umbraco Forms requires a validation framework to run, please read documentation for possible options". This is despite the required dependencies being loaded in the front-end (manually and not via the Razor helper). 

The front-end is working fine, with no error message being displayed, and the forms are functioning. 

### Specifics

This issue has appeared only following the forms upgrade to version 8.7.2 which rolled out automatically on the 12th of May. It was not present in the previous version. 

### Steps to reproduce

Open a page and edit the content via a Rich Text Editor. Add a form to the content using the Macro. 
The error is shown in the RTE.

### Expected result

No error should be rendered if the dependencies are correctly present on the site (either manually added or via the helper). We have them loaded in the <head> and all are working correctly on the front-end of the site. 

### Actual result

Error as shown in the attached screenshot. 

![image](https://user-images.githubusercontent.com/64252533/118171607-5225dc00-b423-11eb-84ac-95bb45db9cdc.png)

**Comment by madsenemark** [comment]
I am having the same issue where we are using jQuery (unobtrusive) for frontend validation.

I tried the aspnet validation which is injected from the Razor helper but the error message still appears in my RTE form macro.

Could be a false-possitive as everyhing is working as it should even though the message appears in the back-office?

**Comment by rowenajbellamy** [comment]
I suspect so Mads, I can't find anything actually not working (though there was a small moment of panic). Good to know actually that using the Razor helper doesn't help as I'd been tempted to try that to see...

**Comment by AndyButland** [comment]
Hi both - I've had a look at this this morning, and believe it's only an issue with rendering in the rich text editor in the back-office (so no concern on the front-end of the website).  I'm not sure it's a regression issue as can't find anything changed in the area to have caused this to only appear in recent versions, but having looked it's fairly clear why the problem occurs.

We have some logic to display this message if no validation framework is available on the front-end, and some checks to see if the rendering is occurring in the back-office (and if so, even if the validation framework is unavailable as may be expected, to not display the message).

This wasn't accounting for rich text editors though, which, although used in the back-office, are actually effectively rendering in their own document, via an IFRAME created by Tinymce.  So in the PR linked above I've added another check for this situation.

Assuming review and testing goes OK we'll get this out in a patch release shortly.

**Comment by rowenajbellamy** [comment]
Brilliant, thanks Andy :) very strange it's only appeared in the last release in that case.
And yep - everything seems to be working ok other than the heart rates of our content editors :) 
Thanks again!

**Comment by Trikcode** [comment]
checking "exclude scripts" removed the warning
