### ISSUE TITLE
Primary Key on Table Missing / Foreign Key Missing

### ISSUE THREAD

**Issue by afinn-tech** [umbraco/Umbraco.Forms.Issues#568]
![image](https://user-images.githubusercontent.com/65241024/118659501-48b2c000-b7e5-11eb-9b66-d80309c8e5f7.png)

How do you address these issues ? in report >? I tried following the guide https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Healthchecks/ , but it only mentions  CONSTRAINTs  ? 

I assume its something like this 
ALTER TABLE [UFRecordDataLongString] ADD CONSTRAINT [FK_UFRecordDataLongString_UFRecordFields_Key] FOREIGN KEY ([Key]) REFERENCES [UFRecordFields] ([Key])

But couldnt get that to work either ? 
If cant be added ? what affect does it have > 
Forms 8.7.3  / Umbraco 8.10.1

Andy

**Comment by AndyButland** [comment]
Hi Andy - you'll find a couple of scripts linked from that documentation page, which will give you the SQL scripts that create these keys, constraints and indexes.  So you should be able to apply the specific ones you see are missing.

That said - if these are reported missing by the healthcheck it suggests they weren't able to be automatically added via the migration that ran when version 8.7 was installed.  And that'll be because there are existing data integrity issues - e.g. duplicates, orphaned records - that will need to be resolved first.

Not having these constraints in place won't immediately cause any issues, but the reason for adding them is to avoid any chance of data getting saved that doesn't match the expected schema rules, so they are worth having in place.

**Comment by afinn-tech** [comment]
@AndyButland  Thanks Andy , i didnt check the other file in documentation , but i understand So fixed the duplicate in UFUserSecurity , but not sure what the issue with the other is . 
I get this message : 
The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_UFRecordFields_UFRecords_Record". The conflict occurred in database "***DB", table "dbo.UFRecords", column 'Id'.

tried this command : 
ALTER TABLE dbo.UFRecordFields
ADD CONSTRAINT
	FK_UFRecordFields_UFRecords_Record FOREIGN KEY
	(
	Record
	) REFERENCES dbo.UFRecords
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO

I checked for duplicated and none found . ? any thought s?

**Comment by AndyButland** [comment]
In this case it may not be a duplicate, rather an orphaned record.  For example, if you have a record in `UFRecordFields` that has a `Record` field value that's not in `UFRecords`, you'll not be able to apply this constraint.

This SQL statement...

```
select * from UFRecordFields where Record not in (select id from UFRecords)
```

... should reveal if that's the case (i.e. if you get any rows back).

**Comment by afinn-tech** [comment]
Hmm , Thanks Andy , but maybe the fields are missing something as it returned 96000 results :( ,
UFRecords look like this 
![image](https://user-images.githubusercontent.com/65241024/118701609-d30e1a80-b80b-11eb-89c2-f6b10a8f8a72.png)

and UFRecords look like this 
![image](https://user-images.githubusercontent.com/65241024/118701700-ef11bc00-b80b-11eb-9d85-ff291ac48e43.png)

**Comment by afinn-tech** [comment]
This might explain why the forms index cant run ( times out) :)

**Comment by AndyButland** [comment]
That suggests you have a lot of orphaned field records - i.e. at some point it sounds like data was deleted from the `UFRecords` table but the related records in `UFRecordsFields` weren't.  Obviously be careful, take backups etc. but it does seem there's some data issues in your local installation that would ideally be resolved, and then you can add the constraints and have some protection against a similar thing happening in future.

**Comment by afinn-tech** [comment]
Thanks @AndyButland  , removed the orphaned files and looks much better . thanks again

**Comment by AndyButland** [comment]
You're welcome, glad you got it sorted.

**Comment by afinn-tech** [comment]
@AndyButland  do u know a good way to programmically remove entries from the DB 
The DELETE statement conflicted with the REFERENCE constraint "FK_UFRecordFields_UFRecords_Record". The conflict occurred in database "DB", table "dbo.UFRecordFields", column 'Record'.< i use to run a SQL script to do this but get this error ?

**Comment by AndyButland** [comment]
That explains then why you had so many orphaned records before.  Sounds like the SQL script you were running previously was deleting records from `UFRecords`, but leaving the related data in `UFRecordFields` untouched.  Now you have the data integrity constraints in place, you can't delete records from a table that would leave orphaned records in another.

To write a script to do this now, you need to work up from the child table to the parent, deleting from the child first.

So for example, to fully delete a record with the Id of 99, you could do:

```
DECLARE @recordId int
SET @recordId = 99

DELETE FROM UFRecordDataBit
WHERE [Key] IN (
	SELECT [Key]
	FROM UFRecordFields
	WHERE Record = @recordId
)

DELETE FROM UFRecordDataDateTime
WHERE [Key] IN (
	SELECT [Key]
	FROM UFRecordFields
	WHERE Record = @recordId
)

DELETE FROM UFRecordDataInteger
WHERE [Key] IN (
	SELECT [Key]
	FROM UFRecordFields
	WHERE Record = @recordId
)

DELETE FROM UFRecordDataLongString
WHERE [Key] IN (
	SELECT [Key]
	FROM UFRecordFields
	WHERE Record = @recordId
)

DELETE FROM UFRecordDataString
WHERE [Key] IN (
	SELECT [Key]
	FROM UFRecordFields
	WHERE Record = @recordId
)

DELETE FROM UFRecordFields
WHERE Record = @recordId

DELETE FROM UFRecords
WHERE Id = @recordId
```

Obviously usual caveats apply before you run SQL scripts on your data... make sure you understand what it's doing, have tested on a backup copy and have a production backup before running it there.

**Comment by afinn-tech** [comment]
Thanks @AndyButland  , i see what u mean we have been doing by date 
    DECLARE @DeleteDate AS DateTime
    SET @DeleteDate = DATEADD(DAY, -@Days, GETDATE())
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON;

    -- SELECT @DeleteDate; 
    -- databit
    DELETE db
    FROM dbo.[UFRecords] AS r 
    INNER JOIN dbo.[UfRecordFields] AS rf 
        ON r.Id = rf.Record
    INNER JOIN dbo.[UFRecordDataBit] AS db
        ON rf.[Key]    = db.[Key]
        WHERE r.[Updated] < @DeleteDate;

For example : But the last step is only deleting the record 

	DELETE r    
    FROM UfRecords AS r 
    WHERE r.[Updated] < @DeleteDate;

So we are missing the 
DELETE FROM UFRecordFields
WHERE Record = @recordId

So this will need to be changed i think to do it by date
