### ISSUE TITLE
Data privacy require seperation of user permissions for Form Editors and Complete Form Processors in Users > Form Security

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#57]
As an agency, we create and manage the website and forms of our clients on an ongoing basis.  Our clients also create their own forms once the site has gone live.

Data security is a significant issue for us.  Therefore we would like to request additional controls regarding access to completed form data within Users > Form Security.

Whist we could build the forms with every field marked as 'secure', this is not intuative and there is no way for us to ensure form editors use this feature.

Idealy we should seperate form creation and editing permissions form access to the completed form data.  The role of creating and editing forms is undertaken by a different team of people who should not be able to see the completed form data post go live unless bug fix is required.

![image](https://user-images.githubusercontent.com/32289029/49555478-26e65b00-f954-11e8-9962-9bf7322d84d3.png)

**Comment by sussexrick** [comment]
This duplicates #3. You might find my workaround listed in that issue useful until this gets done.

**Comment by nul800sebastiaan** [comment]
Closing as duplicate of #3
