### ISSUE TITLE
Form Submitted TempData

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#572]
It would be nice to have a TempData["SuccessfullySubmitted"] which can be picked up anywhere.

In my case I have a form in a Modal which after submission returns to the current page, but without the modal shown, and so I need to display the success message elsewhere on the page.

**Comment by warrenbuckley** [comment]
Fixed by this PR
https://github.com/umbraco/Forms/pull/556

Due for release in 8.8.0

**Comment by AndyButland** [comment]
Just to add that the specific change here has been to implement a "POST / REDIRECT / GET" pattern for form submissions, whether you are using the "redirect to page" or "message on submit" behaviour.  

For both, we now have a `TempData` variable with a key of `UmbracoFormSubmitted` and a value containing the Guid identifier for the submitted form.
