### ISSUE TITLE
'record.CurrentPage' returns an empty guid in a custom work flow

### ISSUE THREAD

**Issue by ribsdigital** [umbraco/Umbraco.Forms.Issues#574]
we've created a custom workflow inheriting from the `WorkflowType` class and need details of the page the form has been submitted from.

however the `record.CurrentPage` available from the `Execute` method is an empty guid.

reproduction
------------

    * create a custom workflow
    * attempt to get the value of the `CurrentPage` property for the record

for example:

```
public class ConfirmationEmailWorkflow : WorkflowType
{
	public ConfirmationEmailWorkflow()
	{
		Id = new Guid("12f3999b-7b52-4fa6-9d81-5f077791b67e");
		Name = "Send confirmation email";
		Description = "Send the result of the form to an email address with a message";
		Icon = "icon-message";
		Group = "Email";
	}

	[Setting("Email", Description = "Enter the receiver email", View = "TextField")]
	public string Email { get; set; }

	public override WorkflowExecutionStatus Execute(Record record, RecordEventArgs e)
	{
		var currentPage = record.CurrentPage;

		//more logic...

		return WorkflowExecutionStatus.Completed;
	}

	public override List<Exception> ValidateSettings()
	{
		var exceptionList = new List<Exception>();

		if (string.IsNullOrEmpty(Email))
		{
			exceptionList.Add(new Exception("'Email' setting has not been set"));
		}

		return exceptionList;
	}
}
```

### specifics

    * umbraco forms 8.7.3
    * umbraco 8.6.4

### steps to reproduce

    * create a workflow similar to the above, debug the site and view the `CurrentPage` property value

### expected result

    * the guid of the page the form is on

### actual result

    * the value for the `CurrentPage` property is an empty guid

![image](https://user-images.githubusercontent.com/22835873/119803956-42c68880-bf23-11eb-9f07-f5a978f5f7e1.png)

**Comment by AndyButland** [comment]
Must admit I'm not entirely sure what `CurrentPage` is intended to represent here - given it's a Guid, and Umbraco pages have integer Ids.  So that might be something we need to review.

However there is an `UmbracoPageId` property of a record, that looks to be populated, so I think you should be able to refer to and use that.

**Comment by AndyButland** [comment]
Will close this one now as believe the functionality you are looking for is best served by the `UmbracoPageId` property.  If that doesn't work or misses part of your requirements please do re-open and let us know.
