### ISSUE TITLE
Support custom SVG icons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#579]
Currently based on latest Umbraco Forms v8.7.3 the icons for e.g. field types are based on the legacy font icons using `<i>` element.

Depending on minimum required Umbraco version, it would be great to use `<umb-icon>` component instead.
That way we can use custom SVG icons in field types and workflows.
https://github.com/umbraco/Umbraco-CMS/pulls?q=is%3Aopen+is%3Apr+author%3Abjarnef+custom+svg+

For example we could use an Slack SVG icon https://worldvectorlogo.com/logo/slack-new-logo instead of the current `icon-chat-active`.

The `<umb-icon>` component has been available since Umbraco v8.8.0:
https://github.com/umbraco/Umbraco-CMS/pull/5606

**Comment by AndyButland** [comment]
This has been added now for field and workflow types (see discussion under [issue 610](https://github.com/umbraco/Umbraco.Forms.Issues/issues/610).
