### ISSUE TITLE
Umbraco 8 Cloud Forms - Pulling in customers name from form into razor email template

### ISSUE THREAD

**Issue by harrietbutcher** [umbraco/Umbraco.Forms.Issues#585]
i am trying to pull in the customers 'firstName' from the 'firstName' form field in my form into the 'thank you' submission email which is using a razor template. I have managed to pull in the customers name into the subject line using magic strings but i am wanting to customize the thank you email so that it has the customers name in the body of the email but i cant seem to work out how i do that. can anyone help on this issue?

**Comment by c9mbundy** [comment]
I believe that the example-template gives a guide in the comments? - @Model.GetValue("aliasFormField")

**Comment by AndyButland** [comment]
Hi @harrietbutcher - if you open up the Razor template for the email, you should be able retrieve this value for display.

I've just tested this code which looks to work:

```
    @{
        var customerName = "Customer";
        var customeNameField = Model.Fields.SingleOrDefault(x => x.Alias == "name");
        if (customeNameField != null)
        {
            customerName = customeNameField.GetValue().ToString();
        }
    }
    Dear @customerName
```

But @c9mbundy beat me to it and his version if much more succinct, so I'd suggest you go with that.

**Comment by AndyButland** [comment]
I'll close this on the assumption that one of the above suggestions has resolved your question @harrietbutcher, but please let me know if not.
