### ISSUE TITLE
Forms 8.7.3 - Deleting of Questions and PreValues doesn't work 

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco.Forms.Issues#586]
### Description
Umbraco CMS: 8.12.2
Umbraco Forms: 8.7.3

When clicking the delete/trash icon on a Question in a Form, the delete confirmation doesn't show. The same goes for PreValues in for example a Multiple Choice questions type. PreVales also can't be edited. This happens with both existing and new forms.  

I saw this issue, which should be fixed in my CMS version: https://github.com/umbraco/Umbraco.Forms.Issues/issues/480
So I don't know if the same issue came back again, or this is something else. 

See the following video (this should be a GIF, click the video, if the GIF doesn't play automatically):
https://imgur.com/a/ZKLfjXV

### Reproduction
Create a new form, click the delete/trash icon in the DataConsent question that is automatically added, for me nothing happens. The same goes for when I add another questions, for example "SingleChoice", add PreValues for this questions, and try to clic the edit/delete icons, for me nothing happens.

When I submit the questions, I also can't delete it.

**Comment by AndyButland** [comment]
Hi @JeroenRoos - I've heard other reports of this, but I'm not able to replicate it.  What I've advised and seems to have helped in other cases is to make sure to [bump the client dependency version](https://adolfi.dev/blog/umbraco-bump-cdf/), just to make sure you don't have any cached views that aren't picking up the updates made in recent versions.  Could you give that a try please?

**Comment by JeroenRoos** [comment]
Hi @AndyButland, thanks for the quick reply. Unfortunately bumping the Client Dependency version didn't fix the issue. I also tried removing all cached data in Chrome, Incognito mode, and other browsers that I normally don't use. But I keep having the same issue.

**Comment by AndyButland** [comment]
Hmm... very odd.  Grasping at straws a bit but please would you mind please zipping up and sending me your `App_Plugins\UmbracoForms` folder please?  I'm wondering perhaps if something hasn't got updated in an upgrade, so might be worth me doing a compare with that.  I'm abl at umbraco dot dk.  Thanks.

**Comment by JeroenRoos** [comment]
Hi @AndyButland, I have sent the "App_Plugins/UmbracoForms" files to your specified email.

**Comment by JeroenRoos** [comment]
Nevermind @AndyButland, your email provider seems to block the email message.

**Comment by JeroenRoos** [comment]
I sent the files using WeTransfer @AndyButland, hopefully it works that way!

**Comment by AndyButland** [comment]
Thanks, they arrived - and I can see the same issue if I copy your files over into my installation.  A process of elimination leads to the difference being the file in `js\umbracoforms.js`.  It doesn't seem to match the version provided with 8.7.3.

I'm not quite sure why you haven't got the latest, but if you go to the [package page on our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/), download the `UmbracoForms.Files.8.7.3.zip` file, extract the `umbracoforms.js` file and copy it into your installation, I _think_ that'll sort out the issue.

**Comment by JeroenRoos** [comment]
Yes it seems to work after taking the files from the `UmbracoForms.Files.8.7.3.zip`. Apparently not only the JS file was behind, but also some of the views and CSS files.

Thanks for the help @AndyButland!

**Comment by AndyButland** [comment]
You're welcome.  I'll close this then, but I guess worth keeping an eye on for future upgrades though.
