### ISSUE TITLE
Conditional logic not working

### ISSUE THREAD

**Issue by Sven883** [umbraco/Umbraco.Forms.Issues#588]
Hello!

We've recently added Umbraco Forms V8.5.6 to our Umbraco v8.8.4 project.
In our test form we've added some conditional logic, but it does not work.
There are no console errors.

I've added the following 3 scripts in the head tag: 

```
<!--StartFragment-->
&lt;script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.0.0.min.js"&gt;&lt;/script&gt;
--
&nbsp; | &lt;script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"&gt;&lt;/script&gt;
&nbsp; | &lt;script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"&gt;&lt;/script&gt;

<!--EndFragment-->

```

I'm rendering the form by using the Umbraco.RenderMacro: 
`@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Form, FormTheme = "custom-form", ExcludeScripts = "1" })`

Custom forms is copy of default form with some css changes.

Any idea what i'm doing wrong?
Thanks!

**Comment by nul800sebastiaan** [comment]
Hi @Sven883 - please try the latest version (currently 8.7.3) instead. This version also no longer uses jQuery, which requires a slightly different approach in setting up your frontend: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/

**Comment by Sven883** [comment]
Hey @nul800sebastiaan  - I've tried that aswell using the @Html.RenderUmbracoFormDependencies() in the head. But conditional logic doesn't work there either.

**Comment by Sven883** [comment]
@nul800sebastiaan  - I've upgraded again to the latest version and re-added @html.renderUmbracoFormDependencies() in my header.
I still render my form using: 
@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Form, FormTheme = "custom-form", ExcludeScripts = "1" })

I get the following error in console now: 
`[Vue warn]: Error compiling template:

Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

540|  </div>
541|  
542|      <script>
   |      ^^^^^^^^
543|          document.onreadystatechange = function () {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
544|            
   |  ^^^^^^^^^^
545|              if (document.readyState == "complete") {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
546|                  var validationsDivs = document.querySelectorAll(".field-validation-error, .umbraco-forms-submitmessage");
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
547|                  var scrollY = 0;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
548|                  for (var i = 0; i < validationsDivs.length; i++) {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
549|  
   |  
550|                      var node = getNode(validationsDivs[i]);
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
551|                      var offset   = node.getBoundingClientRect().top;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
552|                      
   |  ^^^^^^^^^^^^^^^^^^^^
553|                      if (0 < offset && (offset < scrollY || scrollY === 0)) {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
554|                          scrollY = offset;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
555|                      }
   |  ^^^^^^^^^^^^^^^^^^^^^
556|                  }
   |  ^^^^^^^^^^^^^^^^^
557|          
   |  ^^^^^^^^
558|                  if (scrollY > 0) {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
559|                      window.scrollTo(0, scrollY);
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
560|                  }
   |  ^^^^^^^^^^^^^^^^^
561|              }
   |  ^^^^^^^^^^^^^
562|          }
   |  ^^^^^^^^^
563|          
   |  ^^^^^^^^
564|          function getNode(node) {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
565|              var runner = node;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
566|              while (runner.tagName !== "BODY") {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
567|                  if (runner.classList.contains("umbraco-forms-field")) {
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
568|                      return runner;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
569|                  }
   |  ^^^^^^^^^^^^^^^^^
570|                  
   |  ^^^^^^^^^^^^^^^^
571|                  runner = runner.parentNode;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
572|              }
   |  ^^^^^^^^^^^^^
573|  
   |  
574|              return node;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^
575|          }
   |  ^^^^^^^^^
576|      </script>
   |  ^^^^^^^^^^^^^
577|  <input name="ufprt" type="hidden" value="D94B08F6C9C9F3D51706882E9FB4BF26A39F4651F5F4E8CA56087E4A58332E817E24C70BCDF6C06F07040458D11F6D303104D6FC341A64BF9CE8B41CF13B098D2043878F959B6CF83C3BA4FFADBC177719C2933978A93C2A20BA37F5AC89B7F27589D20A9FA4D07EF482E6D45AAACF856269A14A3A22FEB802E82E53C29D8427B021A18B215760EDE0C4183B144C1D06"></form>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
578|  
   |  
579|          
   |  ^^^^^^^^
580|      </div>            </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
581|          </div>
   |  ^^^^^^^^^^^^^^
582|      </div>
   |  ^^^^^^^^^^
583|  </div>
   |  ^^^^^^
584|          </main>
   |  ^^^^^^^^^^^^^^^
585|  
   |  
586|  <footer class="footer">
   |  ^^^^^^^^^^^^^^^^^^^^^^^
587|      <div class="footer__main">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
588|          <div class="container">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
589|              <div class="row">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
590|                  <div class="col-lg-3">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
591|  
   |  
592|                              <picture>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
593|                                  <source media="(min-width: 992px)" srcset="/Assets/images/logo.png">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
594|                                  <img src="/Assets/images/logo.png" alt="" loading="lazy" class="footer__logo">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
595|                              </picture>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
596|  
   |  
597|                  </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^
598|                  <div class="col-lg-3 d-none d-lg-block">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
599|                      <h2 class="footer__title">wtcb.be</h2>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
600|                      <p class="footer__text">About WTCB - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec ultrices arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse non eleifend lacus.</p>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
601|  
   |  
602|                          <h3 class="footer__subtitle">Taal</h3>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
603|                          <div class="select select--footer" data-component="dropdown" data-direction="up">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
604|                              <button class="select__cur" data-dropdown-trigger="" aria-expanded="false">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
605|                                  <span>Nederlands</span>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
606|                                  <svg class="select__cur__icon"><use xlink:href="#chevron" data-direction="down"></use></svg>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
607|                              </button>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
608|  
   |  
609|                              <ul class="select__list" data-dropdown-dropdown="">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
610|                                      <li class="select__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
611|                                          <a href="http://www.cstc.local/content-blocks-testing-fr/" hreflang="fr">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
612|                                              <span>français</span>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
613|                                          </a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
614|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
615|                                      <li class="select__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
616|                                          <a href="/content-blocks-testing/" hreflang="nl">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
617|                                              <span>Nederlands</span>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
618|                                          </a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
619|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
620|                              </ul>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
621|                          </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
622|                  </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^
623|  
   |  
624|                  
   |  ^^^^^^^^^^^^^^^^
625|                      <div class="col-lg-3 d-none d-lg-flex">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
626|                          <nav aria-label="footer main">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
627|                              <ul class="footer__nav">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
628|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
629|                                          <a href="#" target="" title="Onderzoek &amp; Innovatie" class="footer__nav__item__link">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
630|                                              <svg class="footer__nav__item__icon icon-chevron" data-direction="right" focusable="false"><use xlink:href="#chevron"></use></svg>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
631|                                              Onderzoek &amp; Innovatie
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
632|                                          </a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
633|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
634|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
635|                                          <a href="#" target="" title="Certificering &amp; Normalisatie" class="footer__nav__item__link">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
636|                                              <svg class="footer__nav__item__icon icon-chevron" data-direction="right" focusable="false"><use xlink:href="#chevron"></use></svg>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
637|                                              Certificering &amp; Normalisatie
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
638|                                          </a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
639|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
640|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
641|                                          <a href="#" target="" title="Expertise &amp; Ondersteuning" class="footer__nav__item__link">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
642|                                              <svg class="footer__nav__item__icon icon-chevron" data-direction="right" focusable="false"><use xlink:href="#chevron"></use></svg>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
643|                                              Expertise &amp; Ondersteuning
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
644|                                          </a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
645|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
646|                              </ul>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
647|                          </nav>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
648|                      </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
649|                                      <div class="col-lg-3 d-none d-lg-flex">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
650|                          <nav aria-label="sub menu">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
651|                              <ul class="footer__nav footer__nav--secondary">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
652|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
653|                                          <a href="/over-wtcb/" class="footer__nav__item__link">Over WTCB</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
654|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
655|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
656|                                          <a href="#" class="footer__nav__item__link">Ambities 2025</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
657|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
658|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
659|                                          <a href="#" class="footer__nav__item__link">Agenda</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
660|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
661|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
662|                                          <a href="#" class="footer__nav__item__link">Publicaties</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
663|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
664|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
665|                                          <a href="#" class="footer__nav__item__link">Tools</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
666|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
667|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
668|                                          <a href="#" class="footer__nav__item__link">Veelgestelde vragen</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
669|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
670|                                      <li class="footer__nav__item">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
671|                                          <a href="#" class="footer__nav__item__link">Jobs</a>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
672|                                      </li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
673|                              </ul>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
674|                          </nav>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
675|                      </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
676|  
   |  
677|              </div>
   |  ^^^^^^^^^^^^^^^^^^
678|          </div>
   |  ^^^^^^^^^^^^^^
679|      </div>
   |  ^^^^^^^^^^
680|      <div class="footer__legal">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
681|          <div class="container">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
682|              <div class="row">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
683|                  <div class="col-12 d-flex align-items-center justify-content-between flex-column flex-lg-row">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
684|                      <div class="footer__copyright">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
685|                          <span class="footer__legal__text">© 2021 www.wtcb.local</span>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
686|                      </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
687|                      <nav class="footer__legal__wrapper" aria-label="legal menu">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
688|                          <ul class="footer__legal__list">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
689|                                  <li class="footer__legal__item"><a href="/algemene-voorwaarden/" class="footer__legal__text">Algemene voorwaarden</a></li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
690|                                  <li class="footer__legal__item"><a href="/privacybeleid/" class="footer__legal__text">Privacybeleid</a></li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
691|                                  <li class="footer__legal__item"><a href="/cookiebeleid/" class="footer__legal__text">Cookiebeleid</a></li>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
692|                          </ul>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
693|                      </nav>
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
694|                  </div>
   |  ^^^^^^^^^^^^^^^^^^^^^^
695|              </div>
   |  ^^^^^^^^^^^^^^^^^^
696|          </div>
   |  ^^^^^^^^^^^^^^
697|      </div>
   |  ^^^^^^^^^^
698|  </footer>    </div>
   |  ^^^^^^^^^^^^^^^^^^^

(found in <Root>)`
