### ISSUE TITLE
Conditional logic not working

### ISSUE THREAD

**Issue by Sven883** [umbraco/Umbraco.Forms.Issues#589]
Using Umbraco V8.8.4 and Umbraco Forms latest version V8.7.3 the conditional logic is not working.
We've added `@Html.RenderUmbracoFormDependencies()` and render the form by using the 
`@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Form, FormTheme = "custom-form, ExcludeScripts = "1" })` method.

The conditional fields are there with display none. But the js doesn't seem to be doing anything.

Reproduction
------------
Fresh install of umbraco V8.8.4 with latest umbraco forms.
Add `@Html.RenderUmbracoFormDependencies()` in the header and render a form with conditional logic.

**Comment by AndyButland** [comment]
Have been looking into this with the same setup you have @Sven883.  I think you can fix it with changing your code to `ExcludeScripts = "0"`.  As well as the dependencies that you have a reference for, you will also need to render the Forms scripts themselves if they aren't already on the page.

**Comment by Sven883** [comment]
Hey @AndyButland, thank you for your answer. I've tried this but we're getting the following console error: 
![image](https://user-images.githubusercontent.com/77729251/121896617-c7861480-cd21-11eb-96fe-5b0c239765c2.png)

**Comment by AndyButland** [comment]
Then I guess we need to figure out what's different between our setups.

This is the basic form I'm testing with:

![image](https://user-images.githubusercontent.com/1993459/121899719-f81b7d80-cd24-11eb-9078-6af0bed7a7df.png)

And I have a very stripped down view containing this:

```
@using Umbraco.Forms.Mvc
@using ContentModels = Umbraco.Web.PublishedModels;

@inherits UmbracoViewPage<Contact>

@{ Layout = null; }

<!doctype html>
<html>
<head>
    <title>Test Form</title>
    @Html.RenderUmbracoFormDependencies()
</head>

<body>
    @Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.ContactForm.ToString(), ExcludeScripts = "0"  })

</body>

</html>
```

And, as I say, this looks to work as expected (and no console errors).

You say this is a clean install hence I shouldn't expect any upgrade issues, but still perhaps worth you confirming you definitely have the latest version of `umbraco.forms.js` such as that extracted from the `UmbracoForms.Files.8.7.3.zip` zip file downloaded from [here](https://our.umbraco.com/packages/developer-tools/umbraco-forms/).

Otherwise, are you able to add any more detail now how your form setup differs from mine please?

**Comment by nul800sebastiaan** [comment]
I don't know if we still require `<div class="umbraco-forms-page">` around the form as described here? https://github.com/umbraco/Umbraco.Forms.Issues/issues/24#issuecomment-765605808

**Comment by Sven883** [comment]
@nul800sebastiaan  - Error is gone when I add this class around the form. But conditional logic is still not working. Here are some screenshots: 
![image](https://user-images.githubusercontent.com/77729251/121901306-90fec880-cd26-11eb-96aa-963494d95476.png)
![image](https://user-images.githubusercontent.com/77729251/121901356-9d832100-cd26-11eb-9231-576ea2e81ed6.png)
![image](https://user-images.githubusercontent.com/77729251/121901406-aa077980-cd26-11eb-99f2-0f1c4be72e3c.png)
![image](https://user-images.githubusercontent.com/77729251/121901457-b4c20e80-cd26-11eb-9fd0-9ffd1d111edc.png)

**Comment by nul800sebastiaan** [comment]
I don't know how Email and Phone are presented on the frontend, they might be an id? Have a look at the `value` attribute for that radio button to make sure that matches the condition.

**Comment by AndyButland** [comment]
It does look like somehow you don't have the latest version of Forms there @Sven883.  I can see for example that you don't have the ability to edit the pre-values, which we introduced in 8.7.0.

I.e. I'd expect you to see this interface:

![image](https://user-images.githubusercontent.com/1993459/121902690-d7a0f280-cd27-11eb-9013-bb9bc7954289.png)

**Comment by Sven883** [comment]
@AndyButland  - This is my umbraco forms version: 
![image](https://user-images.githubusercontent.com/77729251/121903007-25b5f600-cd28-11eb-96ef-c1d837535f31.png)

**Comment by nul800sebastiaan** [comment]
The version is being read from the `App_Plugins\UmbracoForms\version` file so that seems up to date. 

Two things you can try:

Update the version in ClientDependency.config (just make it 1 higher or lower), that should invalidate all browser caching and upon reload hopefully give you fresh frontend files that match Andy's screenshot.

If that doesn't help, download  `UmbracoForms.Files.8.7.3.zip` from https://our.umbraco.com/packages/developer-tools/umbraco-forms/ I would at the very least try to unzip the `App_Plugins` folder into your existing one and overwrite everything, but it doesn't hurt to overwrite all the other files as well (in bin and Views). Then go back to step one and update the ClientDependency version and refresh.

**Comment by Sven883** [comment]
@nul800sebastiaan  - There is no app_plugins folder in the zip file. Or am I looking at the wrong zip file ?

**Comment by nul800sebastiaan** [comment]
Most likely the wrong file 

https://user-images.githubusercontent.com/304656/121906020-ff458a00-cd2a-11eb-988d-cf60744c80ea.mp4

**Comment by Sven883** [comment]
@nul800sebastiaan  - Got it! One file (App_Plugins/UmbracoForm/directives/umb-forms-file-upload-editor.html)  has been updated and i can now see the edit icon. But the condition logic is still not working :/

**Comment by nul800sebastiaan** [comment]
Any javascript errors? There's not a whole lot we can do from here, it should work, so something in your setup is different..

Is your frontend set up correctly? Make sure to double check: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/

Also check WHERE in the html you've put the Razor helpers.

**Comment by Sven883** [comment]
@nul800sebastiaan - No js errors anymore. I'm checking the values in code: 
Id of dropdown is same as Id of field given here. But is it normal that Id = 0000-000... ? 
![image](https://user-images.githubusercontent.com/77729251/121908618-77ad4a80-cd2d-11eb-8a1d-70fb5dc05bcb.png)

Other problem might be that my scripts are just not loading for some weird reason.

**Comment by AndyButland** [comment]
I'd suggest also that you make sure you've replaced _all_ files from the zip - as if you had one not updated, there's a fair chance there were others.  In particular a comparison of `umbraco.forms.js` to be sure you have the latest would be a good idea.

Then to avoid any caching issues, [bump the client dependency number](https://adolfi.dev/blog/umbraco-bump-cdf/).

**Comment by Sven883** [comment]
@AndyButland  - Yes i've indeed replaced all files from the zip. Only change I got was that one file.

**Comment by nul800sebastiaan** [comment]
@Sven883 - sorry, my suggestion to check for Id's was a mistake. I forgot that the conditions were dropdowns, so they're fine!


https://user-images.githubusercontent.com/304656/121909538-4bde9480-cd2e-11eb-9393-16a19dd993a4.mp4

I've replicated your scenario, works. Maybe clear browser cache thoroughly  and as suggested bump the client dependency number before doing so.

**Comment by nul800sebastiaan** [comment]
Your HTML source should contain:


```

<script src='/App_Plugins/UmbracoForms/Assets/Themes/Default/umbracoforms.js' defer='defer' ></script><link rel='stylesheet' href='/app_plugins/umbracoforms/assets/defaultform.css' />    </div>
<p> </p>

<script src='/App_Plugins/UmbracoForms/Assets/promise-polyfill/dist/polyfill.min.js'></script><script src='/App_Plugins/UmbracoForms/Assets/aspnet-validation/dist/aspnet-validation.min.js'></script>
```
before `</html>`

and `<script src='/App_Plugins/UmbracoForms/Assets/promise-polyfill/dist/polyfill.min.js'></script><script src='/App_Plugins/UmbracoForms/Assets/aspnet-validation/dist/aspnet-validation.min.js'></script>`

before `</head>`

**Comment by nul800sebastiaan** [comment]
I've just spotted a mistake in your opening post: ` ExcludeScripts = "1" ` should be ` ExcludeScripts = "0" `

**Comment by Sven883** [comment]
This is my front-end code. Deleted all sensitive data.

`
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />

    <title>Test</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">


    <script src='/App_Plugins/UmbracoForms/Assets/promise-polyfill/dist/polyfill.min.js'></script><script src='/App_Plugins/UmbracoForms/Assets/aspnet-validation/dist/aspnet-validation.min.js'></script>
    <link href="/Assets/css/style.min.css?v=20210611035653" rel="stylesheet" type="text/css"></link>

</head>
<body>



    <div id="app">




        <main id="main">
<div class="section section--title">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-10 col-xl-7 offset-lg-1">
                <h2 class="heading-2 heading-dark">Test</h2>
                <p>test</p>
            </div>
        </div>
    </div>
</div>

<div class="section section--no-margin form">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-10 col-xl-7 offset-lg-1">
<div id="umbraco_form_c2cad780557b46e7a6dda83bb6920a3b" class="umbraco-forms-form gaathetlukkenform umbraco-forms-test-form">

<form action="/content-blocks-testing/" enctype="multipart/form-data" method="post"><input name="__RequestVerificationToken" type="hidden" value="FRDs_9_YcjIJJJBCq_Z8gjJN6vggxsOJrrTzGdJxBpSdybSFJBW0q7n_OQNl3Y6kUHEN1Dt1TvBo-xIIjHK222QYJnVhmGDzFCSPtA-Wx4Q1" /><input data-val="true" data-val-required="The FormId field is required." name="FormId" type="hidden" value="c2cad780-557b-46e7-a6dd-a83bb6920a3b" /><input name="FormName" type="hidden" value="Gaat het lukken form" /><input data-val="true" data-val-required="The RecordId field is required." name="RecordId" type="hidden" value="00000000-0000-0000-0000-000000000000" /><input name="PreviousClicked" type="hidden" value="" /><input name="Theme" type="hidden" value="test-form" />            <input type="hidden" name="FormStep" value="0" />
            <input type="hidden" name="RecordState" value="N0M2QkQ1MUNGMDAwNjk5MkY0MDcyMEMwMjQwMDhBMTYwNjAyQjMyQUU4M0JGNDQ1NkMyRjE5QjUyREE3NjhFQzQ5MjdBMkI4NTc3QUM4N0M2MDAxNzA1OEFCODAwNTQ3NjA0Q0EwRkY4NjUyRTYzQjk4M0I0RTM3N0Y5NDQ0MzlCQTc5QjZBNEY2MzIxQzNFNEJDQjdGMkYwOTU1RTc2Q0UzNjUwMkJBNkJGMkRFRjEyRkQ3NkQ4MDNBQzY1QUQ4RTA1QTg0RTM2NUVGRUJDRDMyQkY0MUM0QUFDM0YzMjI1RkMwQUI2QTFFMkNEMDVCQ0Y2OUQyRTgzREY1NzAxNTFCMDIyQkNCQUExMTdBNTExRDdEOTY1Mjg2NEUwOUJGNjJFRDZCMjhGNUEyRUMwNEE5QTEyN0NFOTlDMDAzNkNENkYzQjNDODQwMjc3M0M0MDYxOTAzNjQ5QTVGRjNCMjQyNDdBRTE1RDFDRjQzNjg1MTNBOUJBOUJEMjkwODREMzIxMTE5MEU4RkM1OURDN0EzMUEyQTlDNDg2NDlCREFBMTE1MzNFMzRDMTlENzk0RTVERDFEMTM2RjZCRDQ1MkNENTU2MEU2QjI1RTBFRTZEMENFMzUyQzdBNkYyMTM4RkFGNDYzNEEzQTk4NTc4MjEwQ0Y3RTI3MTBGMzhGRjdDOTVCM0UyRURFOTY5NTdGMkRGRjdBMjJCN0ZFNUYzMTE2RUMyQjJDRjE0MTQzMUJCMzkzQTQ5MUI1Qjc3MjAyOUIwQTk5ODkwQzI3Qzg2NzZDMzlCMzhDQ0JERjRBMUQyMTM2QTc4MzVDMTcwQURFOTAyQzdDNDgyQzQxN0E4NzI2MjBFNDI4RDdBQjI3RTFCQjZDRDdFMDE2MDY3RDA4" />

<div class="umbraco-forms-page form__container">
        <fieldset class="umbraco-forms-fieldset" id="cca45466-0f32-4c3f-9784-4f7b40360435">
            <div class="form__group">

                    <div class="form__item">

                            <div class="form__item__wrapper" >

                                        <label for="6346f881-7b06-4179-d163-7cc27cfe6eab" class="form__label control-label umbraco-forms-label">
                                            Gaat het lukken?
                                                <span class="umbracoForms-Indicator">*</span>
                                        </label>

                                <div class="umbraco-forms-field-wrapper">




<div class="form__group" id="6346f881-7b06-4179-d163-7cc27cfe6eab">
		<label class="form-control radio form__item">
			<input type="radio" class="radio__input" name="6346f881-7b06-4179-d163-7cc27cfe6eab" id="6346f881-7b06-4179-d163-7cc27cfe6eab_0" value="Ja" data-val="true" data-rule-required="true" data-msg-required="Please provide a value for Gaat het lukken?">
			<span class="radio__checkmark"></span>
			<span class="radio__text">Ja</span>
		</label>
		<label class="form-control radio form__item">
			<input type="radio" class="radio__input" name="6346f881-7b06-4179-d163-7cc27cfe6eab" id="6346f881-7b06-4179-d163-7cc27cfe6eab_1" value="Nee" data-val="true" data-rule-required="true" data-msg-required="Please provide a value for Gaat het lukken?">
			<span class="radio__checkmark"></span>
			<span class="radio__text">Nee</span>
		</label>
</div>

<span class="field-validation-valid" data-valmsg-for="6346f881-7b06-4179-d163-7cc27cfe6eab" data-valmsg-replace="true"></span>
                                </div>


                            </div>
                            <div class="form__item__wrapper"   style="display: none"   >

                                        <label for="952fefc4-184f-42f9-fa85-0110b3a0234c" class="form__label control-label umbraco-forms-label">
                                            Als het lukt
                                        </label>

                                <div class="umbraco-forms-field-wrapper">

                                    <input type="text" name="952fefc4-184f-42f9-fa85-0110b3a0234c" id="952fefc4-184f-42f9-fa85-0110b3a0234c" data-umb="952fefc4-184f-42f9-fa85-0110b3a0234c" class="text" value="" maxlength="255"




/>

<span class="field-validation-valid" data-valmsg-for="952fefc4-184f-42f9-fa85-0110b3a0234c" data-valmsg-replace="true"></span>
                                </div>


                            </div>
                            <div class="form__item__wrapper"   style="display: none"   >

                                        <label for="e5b0c584-559d-4882-c3ec-c408aa1aa9c6" class="form__label control-label umbraco-forms-label">
                                            Als het niet lukt
                                        </label>

                                <div class="umbraco-forms-field-wrapper">

                                    <input type="text" name="e5b0c584-559d-4882-c3ec-c408aa1aa9c6" id="e5b0c584-559d-4882-c3ec-c408aa1aa9c6" data-umb="e5b0c584-559d-4882-c3ec-c408aa1aa9c6" class="text" value="" maxlength="255"




/>

<span class="field-validation-valid" data-valmsg-for="e5b0c584-559d-4882-c3ec-c408aa1aa9c6" data-valmsg-replace="true"></span>
                                </div>


                            </div>

                    </div>
            </div>

        </fieldset>


    <div style="display: none">
        <input type="text" name="c2cad780557b46e7a6dda83bb6920a3b" />
    </div>

    <div class="umbraco-forms-navigation row-fluid">

        <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" class="btn btn-primary" value="Submit" name="submitbtn"/>
        </div>
    </div>
</div>

<input name="ufprt" type="hidden" value="F9AE989A8875E6F265A8D72410FC4608DC98C9FB816DA554BAF7C3EE8AE638A46A9426BF338FF2793FEC2081C1D62B0415C276FF761CC45A4C6FCA342790E2151E49C294CBE40A6BAFBA86BC37E1B0C2AA6C5DD7EE66E0FF2443262602C5B3D5079F9298339253F4570650EEF71EB0D3DA52AB9004142D2BE3EE7BD8FEA73E7341B88E6EF96597ED3A5F008962224ADE" /></form>

<script>
    if (typeof umbracoFormsCollection === 'undefined') var umbracoFormsCollection = [];
    umbracoFormsCollection.push('%7B%22formId%22:%22c2cad780557b46e7a6dda83bb6920a3b%22,%22fieldSetConditions%22:%7B%7D,%22fieldConditions%22:%7B%22952fefc4-184f-42f9-fa85-0110b3a0234c%22:%7B%22id%22:%2200000000-0000-0000-0000-000000000000%22,%22actionType%22:%22Show%22,%22logicType%22:%22All%22,%22rules%22:[%7B%22id%22:%2200000000-0000-0000-0000-000000000000%22,%22fieldsetId%22:%22cca45466-0f32-4c3f-9784-4f7b40360435%22,%22field%22:%226346f881-7b06-4179-d163-7cc27cfe6eab%22,%22operator%22:%22Is%22,%22value%22:%22Ja%22%7D]%7D,%22e5b0c584-559d-4882-c3ec-c408aa1aa9c6%22:%7B%22id%22:%2200000000-0000-0000-0000-000000000000%22,%22actionType%22:%22Show%22,%22logicType%22:%22All%22,%22rules%22:[%7B%22id%22:%2200000000-0000-0000-0000-000000000000%22,%22fieldsetId%22:%22cca45466-0f32-4c3f-9784-4f7b40360435%22,%22field%22:%226346f881-7b06-4179-d163-7cc27cfe6eab%22,%22operator%22:%22Is%22,%22value%22:%22Nee%22%7D]%7D%7D,%22recordValues%22:%7B%7D%7D');
</script>


<script src='/App_Plugins/UmbracoForms/Assets/Themes/Default/umbracoforms.js' defer='defer' ></script><link rel='stylesheet' href='/app_plugins/umbracoforms/assets/defaultform.css' />    </div>            </div>
        </div>
    </div>
</div>
        </main>

<footer class="footer">

</footer>
    <script src='/App_Plugins/UmbracoForms/Assets/promise-polyfill/dist/polyfill.min.js'></script><script src='/App_Plugins/UmbracoForms/Assets/aspnet-validation/dist/aspnet-validation.min.js'></script>
    </body>
</html>
`

**Comment by Sven883** [comment]
@nul800sebastiaan  - Changed it to  @Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.Form, FormTheme = "custom-form", ExcludeScripts = "0" })

With above output. But didn't change anything :/

**Comment by nul800sebastiaan** [comment]
Okay, so now you're using checkboxes.. also no problem here. 

https://user-images.githubusercontent.com/304656/121914770-dde89c00-cd32-11eb-976a-9148052411fd.mp4

And you're checking the right conditions? `true` / `false`:


![image](https://user-images.githubusercontent.com/304656/121914935-02dd0f00-cd33-11eb-83da-b812c8a842bf.png)

![image](https://user-images.githubusercontent.com/304656/121914940-040e3c00-cd33-11eb-8d03-e81b14630d04.png)

**Comment by nul800sebastiaan** [comment]
You're also using a custom form, I have assume it works with the regular theme : `FormTheme="bootstrap3-horizontal"`?

**Comment by Sven883** [comment]
@nul800sebastiaan - Tried that aswell but doesn't work either. 
I'm using the following setup: 
- Website
-       Contentpage --> With master template where i've added @Html.RenderUmbracoFormDependencies()
-               Block list with 'FormBlock' --> I'm rendering the form here

**Comment by Sven883** [comment]
@nul800sebastiaan  - Using Umbraco Forms in a Blocklist breaks conditional logic for some reason. I've made exactly the same form in a normal template and conditional logic works there.

**Comment by Sven883** [comment]
@nul800sebastiaan - Issue can be closed. Our custom js is somehow interfering with the forms js.

**Comment by Sven883** [comment]
@nul800sebastiaan  - I thought it had to do with our custom javascript. But the problem is elsewhere. I've made a forum post with all the information: https://our.umbraco.com/forum/using-umbraco-and-getting-started//106334-umbraco-forms-conditional-logic-not-working

**Comment by Sven883** [comment]
@nul800sebastiaan  & @AndyButland - We've found the problem in another issue: 
https://github.com/umbraco/Umbraco.Forms.Issues/issues/311 
Sadly there is no solution given yet.

**Comment by AndyButland** [comment]
Will close this one again given the solution provided for issue #311 that it's understood that it is related.
