### ISSUE TITLE
Groups: visual indication of a condition

### ISSUE THREAD

**Issue by tcmorris** [umbraco/Umbraco.Forms.Issues#590]
When providing a condition for a group, there is currently no indication in the overview for the form editor that a condition has been added.

![image](https://user-images.githubusercontent.com/2123628/121892267-6f94e100-cd14-11eb-9813-f74b0a1f5c43.png)

Whereas, when providing a condition for a field, the details about the conditions are displayed alongside the field name.

![image](https://user-images.githubusercontent.com/2123628/121892734-082b6100-cd15-11eb-8d1d-32768d17651d.png)

Suggestion: add same concept to groups that is used for fields.

---
_This item has been added to our backlog [AB#12462](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12462)_

**Comment by AndyButland** [comment]
Seems this is rendered... just in white text on a white background 🤦‍♂️... but have fixed this up in the linked PR.  We'll get this out in a release shortly.

**Comment by tcmorris** [comment]
Ah good spot! Thanks Andy.

**Comment by nikolajlauridsen** [comment]
This has been fixed and is scheduled for the next release, thanks for reporting 😃
