### ISSUE TITLE
Only the first form is submitted successfully

### ISSUE THREAD

**Issue by UnicornSez** [umbraco/Umbraco.Forms.Issues#593]
Creating 2 separate forms on the same page results in a rather interesting bug where you can only submit the first form correctly.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I don't actually know what is causing this, but if you create two entirely different forms on the same page, you can only submit one of them successfully.. then you will have to reload to submit the other one, and this will cause the previous one to be "un-submitable".

### Specifics

URL: https://dev-unoversionupgrade.d1.rainbowsrock.net/second-forms-test/
Versions: CMS 8.12.2 | Forms 8.7.4 | Deploy 4.0.4
![image](https://user-images.githubusercontent.com/53556473/122040670-60776700-cdd8-11eb-90a3-2047cd4399d7.png)
I am using Google Chrome version 91.0.4472.101.
I tried Edge as well.

### Steps to reproduce
1. Create any two forms
2. Add those forms to the same page
3. Go to the page and try to submit both

### Expected result
I expected that I would be able to submit both forms, on after the other.

### Actual result
The actual result is that I am only able to submit one form, then I have to reload the page to submit the other one.
![Recaptcha V3](https://user-images.githubusercontent.com/53556473/122040708-6ff6b000-cdd8-11eb-8d85-fdf4bad50328.gif)

**Comment by warrenbuckley** [comment]
Fixed by this PR
https://github.com/umbraco/Forms/pull/556

Due for release in 8.8.0
