### ISSUE TITLE
Spelling mistake in FormViewResolver deprecation warning

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco.Forms.Issues#596]
Hi,

In Umbraco Forms 7.5.2 there is a deprecation warning on the FormViewResolver class which says:

Use the the formthemeresolver instead

The duplicate 'the' just needs deleting.

**Comment by AndyButland** [comment]
Thanks - I've fixed this up in the code base.  It's missed the boat for the next release due on Tuesday, but it'll go out in the next one.
