### ISSUE TITLE
Static values are not passed to the destination URL in the "Send to URL" workflow

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Forms.Issues#597]
As discovered in the discussion on #569. any field mappings created with a "static value" aren't being passed on to the destination URL in the "Send to URL" workflow.

This should also be checked in the "Post as XML" workflow.

---
_This item has been added to our backlog [AB#12474](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12474)_

**Comment by nikolajlauridsen** [comment]
This has been fixed, and is ready for the next release 👍
