### ISSUE TITLE
Manage forms in folders, like in Umbraco Forms on Perplex Steroids

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#598]
We use Umbraco Forms on an Intranet. Every backoffice user can create a form and due that reason we've got a lot of forms.
It is difficult to determine to which department or project a form belongs. It would be much clearer if forms could be divided into folders, where it would be ideal if users could be assigned rights to a folder. 

Umbraco Forms on Perplex Steroids did exactly this only is Perplex, hoping this would be picked up by Umbraco HQ, stopped developing this. 
https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/

![](https://our.umbraco.com/media/wiki/152418/635942414341668898_folder-optionspng.png)

https://www.youtube.com/watch?v=vaQsr2uY3bA

It would be very nice if this functionality was adopted by Umbraco HQ.

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco.Forms.Issues/issues/75

Unfortunately we have no update on when and if this will happen, currently it's not on the roadmap.
