### ISSUE TITLE
Members in workflows best practice

### ISSUE THREAD

**Issue by No1sBothered** [umbraco/Umbraco.Forms.Issues#599]
We are using Workflows to create members and running into a few problems. The first one being that we need to get an instance of the MembershipHelper, we have tried injecting the helper but Lightning Inject throws an error.

What is the best way to do member operations from a Workflow, is it advisable to use the IMemberService?

**Comment by nul800sebastiaan** [comment]
Hi there @No1sBothered, depending on what you're trying to do the `MemberService` could be suitable (it's for writing, if you're doing stuff that only needs to read then always avoid using the `Service`s and go for cached items). 

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by No1sBothered** [comment]
Thanks @nul800sebastiaan  i will throw this open to the wider community. 

In the meantime, do you know why the MembershipHelper is not being injected into Workflows, is it me or is this by design?
