### ISSUE TITLE
 Can't clear choices from content and media pickers in field settings

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#6]
First logged as http://issues.umbraco.org/issue/CON-1505 using Umbraco 7.6.12 and Forms 6.0.6:

### What did you do?

Create a custom field type and use it as the answer type for a question. Configure the answer type and select a page and a media item for the two settings. Now try to deselect them.

```
public class Example : FieldType
{
    public Example()
    {
        Id = new Guid("4e39274e-576e-4860-897a-d273d259da0c");
        Name = "Example";
        // etc...
    }

    [Setting("Pick an Umbraco page", view = "pickers.content")]
    public string RelatedContent { get; set; }

    [Setting("Pick a document", view = "file")]
    public string RelatedMedia { get; set; }
}
```

### What did you expect to happen?

There would be a little red cross I could click on to clear my selection.

### What actually happened?

There's a little red cross for content, but it doesn't work; it just closes the overlay. There's no control to click to clear the media selection. You can change the page or document you've selected, but not remove it.

**Comment by bergmania** [comment]
PR:

* V7: [umbraco/Forms#250](https://github.com/umbraco/Forms/pull/250)
* V8: [umbraco/Forms#249](https://github.com/umbraco/Forms/pull/249)

**Comment by bergmania** [comment]
Connects: https://github.com/umbraco/Umbraco.Forms.Issues/issues/78
