### ISSUE TITLE
umbraco forms causing verbose errors.

### ISSUE THREAD

**Issue by lori698** [umbraco/Umbraco.Forms.Issues#600]
The qualys security scan is appending items to the formId and theme on the umbraco forms causing verbose errors.

Although I have a custom 500 page there its able to get through to the YSOD.

Is there any way to stop this happening?

My 500 page is set up as follows

```
  <system.web>
<customErrors mode="Off" redirectMode="ResponseRewrite" defaultRedirect="~/500.aspx">
    <error statusCode="400" redirect="~/400.aspx"/>
    <error statusCode="404" redirect="~/404.aspx"/>
    <error statusCode="500" redirect="~/500.aspx"/>
</customErrors>
```

  ```
 System.webServer
          <httpErrors errorMode="Custom" existingResponse="Replace" > 
              <remove statusCode="404" subStatusCode="-1" />
                 <remove statusCode="500" subStatusCode="-1" />
                <error statusCode="404" path="404.html" responseMode="ExecuteURL"/>
                <error statusCode="500" path="500.html" responseMode="File"/>
        </httpErrors>
  <location path="media">
        <system.webServer>
            <httpErrors errorMode="Custom" existingResponse="Replace">
                <remove statusCode="404"/>
                <error statusCode="404" path="404.html" responseMode="File"/>
            </httpErrors>
        </system.webServer>
    </location> 
```

**Comment by nul800sebastiaan** [comment]
I guess you need to set `<compilation debug="false"`? For follow up questions, I'll refer you to the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by lori698** [comment]
Hi  had the question up since Feb no answers

**Comment by lori698** [comment]
> I guess you need to set `<compilation debug="false"`? For follow up questions, I'll refer you to the forums where our friendly community can help you find the best solution for your requirements.
> Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

Hi had the question up since Feb no answers - only happens during the qualys scan. It can interfer with the hidden formId field which causes the error 500
https://our.umbraco.com/forum/using-umbraco-and-getting-started/104945-umbraco-forms-qualys-scan-formid-theme-editable

also another user had the same issue but I have their solution already implemented
https://our.umbraco.com/forum/using-umbraco-and-getting-started/104502-verbose-error-message
Any further thoughts than just sending me to the forums which I know are usually great

**Comment by nul800sebastiaan** [comment]
I am afraid I have no thoughts, but maybe lodge an issue with Qualys as well as they seem to be doing naughty things they shouldn't. 🙈  

As a tip: it might help to also show what in the DOM is being changed by Qualys.
