### ISSUE TITLE
Icons for answer types are too small

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco.Forms.Issues#610]
when choosing an answer type the icons are very small

Reproduction
------------
Add a Form
Add a question
Choose answer type

### Bug summary

in the previous version the css below is applied but not on the new version

```
.umb-card-grid i {
    font-size: 30px;
    line-height: 20px;
    margin-top: 6px;
    margin-bottom: 10px;
    display: block
}
```

### Specifics

Version 8.7.6 of Forms

Version 8.15.0 of [Umbraco]

**Comment by russellshome** [comment]
![Icons in v 8 7 5](https://user-images.githubusercontent.com/8239408/126401998-017ce336-6d27-42bf-bedf-7a699dfe4320.png)
![Icons in v 8 7 6](https://user-images.githubusercontent.com/8239408/126402000-0cf172ae-71c1-4ead-946f-f4d274156ac4.png)

**Comment by AndyButland** [comment]
Thanks for reporting.  It looks like this is some CSS that was removed in the CMS for 8.15 - see [here](https://github.com/umbraco/Umbraco-CMS/pull/10344/files#diff-23578583adad73901d1af27aa77420027c59305f3f8fd90d72d7be58d08c7e1dL220).

I'll check first to see if that's planned for restore there before adding it back for Forms.

**Comment by AndyButland** [comment]
I've reapplied this in forms, under a Forms-specific CSS selector, so the visual display is restored in Forms and we don't apply this styling to other areas of the back-office where it seems it's not longer necessary or wanted.

Expected to be released with 8.8.0.

**Comment by bjarnef** [comment]
@AndyButland I adjusted part of this in Umbraco core to use `<umb-icon>` instead  so it is also possible to use custom SVG icons.
Forms should probably use this as well.
https://github.com/umbraco/Umbraco.Forms.Issues/issues/579

`<umb-icon icon="icon-document" class="icon-document"></umb-icon>`

**Comment by AndyButland** [comment]
Thanks @bjarnef, that seems to work so will go with that rather than porting over the CSS I think.  To your knowledge has `<umb-icon>` been around for a while though?  I need to consider latest version of Forms running on an older version of CMS V8.

**Comment by bjarnef** [comment]
Yes, since Umbraco v8.8.0 as mentioned at bottom in the linked issue 🙂

**Comment by AndyButland** [comment]
Yes, works nicely:

<img src="https://user-images.githubusercontent.com/1993459/127486324-1ecc7d51-9d0b-43e3-98e9-ffad01db05eb.png" width="200">

**Comment by bjarnef** [comment]
@AndyButland note it also need to set icon namr in class attribute to be backward compatible with font icons as in case people are using a custom font icon.

`<umb-icon icon="icon-document" class="icon-document"></umb-icon>`
