### ISSUE TITLE
Workflow settings are applied when clicking "Close" button

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#613]
When you adjust the settings of a workflow, it doesn't matter if you click the Submit or the Close button of the dialog. In both cases, the settings are applied to the workflow.

Reproduction
------------

- Open the "Send template email" workflow and change the Recipient Email.
- Click the "Close" button.
- Open the "Send template email" workflow again, the settings are still applied

### Expected result

I would expect that  when clicking the "Close" button, the settings are not applied (only when clicking "Submit"). 

---
_This item has been added to our backlog [AB#13054](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13054)_

**Comment by warrenbuckley** [comment]
Fixed in this PR
https://github.com/umbraco/Forms/pull/557

Due for release in 8.8.0
