### ISSUE TITLE
Regex not validating at client

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Forms.Issues#622]
More likely a misconfiguration on my part, than a bug, but I'm finding that field regex validations are not being tested at the client, and are allowing an invalid entry to be apparently submitted, but is never recorded by the server, and no log-entry is recorded to indicate failure. This leaves the sender believing the message was sent, while the recipient never receives anything.

e.g. a textbox for an email address with simple regex validation: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$

An empty value will result in the client barking at the user, and not submitting, but an invalid match such as "fred" will not be tested, and will be submitted as valid only to disappear into the ether. i.e. not recorded.

In this example, the rendered field contains the attribute: data-regex="^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$"  but it is not actually used to validate the field at the client.

I've checked that jquery.validate and jquery.validate.unobtrusive are loaded and that the versions are current.

**Comment by c9mbundy** [comment]
Forgot the important bit - Forms 7.5.4 running on Umbraco 7.15.7

**Comment by AndyButland** [comment]
I'm afraid I'm not able to replicate this @c9mbundy.

Just to cross-check, in my test site, my field, when I have a text box both marked as mandatory and with an email check regex, is generating like this:

```
<input type="text" 
       name="903ce28e-afe2-4571-88f6-3b5632ef504a" 
       id="903ce28e-afe2-4571-88f6-3b5632ef504a" 
       class=" text" 
       value="" 
       maxlength="500"
       
data-val="true"
 data-val-required="Enter an email"
 data-val-regex="Not an email" data-regex="[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+"
/>
```

And I have these references at the base of the file:

```
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
```

**Comment by c9mbundy** [comment]
Thanks for testing it - looks like the problem is with me.

I'm submitting forms using jquery-ajax, and when I disable that, the field is validated and rejected, so I'll need to do some more digging to find out why. I suspect the ajax-enabled submission is testing and failing, but not coming back for re-entry for some reason.

**Comment by c9mbundy** [comment]
Ugh! - I don't know how many times I've fallen for that one... 

InsertUmbracoFormWithTheme  has an argument: includeScripts = includeScripts - which does exactly as it says on the lid.
`Html.RenderAction("RenderForm", "UmbracoForms", new {formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });`

However, this is set as the boolean inverse of a received argument: ExcludeScripts = 0/1
`includeScripts = Model.MacroParameters["ExcludeScripts"].ToString() == "0";`

So, if using the standard Macro to render the form:
`@Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = formGuid, FormTheme = formTheme, ExcludeScripts = 0 })`

If you don't include the ExcludeScripts = 0 argument, then the default action is to Exclude them, because an empty-string does not equal "0"

Once I tracked down the offending view that was calling the macro without the ExcludeScripts = 0 argument, then it worked as expected, and the reason it worked with the non-ajax form was simply that the views were different, and that one was correct.
