### ISSUE TITLE
Mandatory fields with conditional logic breaks site on Submit

### ISSUE THREAD

**Issue by PBHansen** [umbraco/Umbraco.Forms.Issues#623]
Issue description
------------

I have a form with 2 mandatory fields.
Both fields have a conditional logic to hide if the other fields value is greater than 0.

If I only fill out one field and submit the form, my local website shuts down and I get a "localhost refused to connect". If I try it on a website running on Azure I get a 502 Gateway Error.

Reproduction
------------

Create a new form
Create 2 fields, both mandatory with datatype Short Answer.
Update each field with a conditional to hide if the other field is greater than 0.
Insert form on new website.
Fill out first field OR second field and press submit, site then stops responding.

Umbraco Version 8.15.1
UmbracForms Version 8.7.6

I have re-created this in a new clean Umbraco website using the following steps:
1) Create clean .NET Framework 4.7.2 solution
2) Install UmbracoCMS 8.15.1 from Nuget
3) Build
4) Startup solution from VS (ctrl + f5)
5) Install Umbraco, SQL CE, No starter Kit
    - Username: test@test.test
	- Password: umbraco4tw
6) Install UmbracoForms 8.7.6
7) Build and Run
8) Backoffice -> Create new form
9) Create 2 fields, both mandatory, both with a condition to hide if the other value is greather than 0

Public Github repo: 
https://github.com/PBHansen/FormsTest
(See credentials to log into SQL CE in stop 5 above)

I expected the form to be submitted without a problem, since the first field being mandatory and the second field being hidden with the conditional
![UmbracoForms](https://user-images.githubusercontent.com/8962756/129580849-79d45d98-2c46-4867-934e-8a3b8460528e.gif)

**Comment by AndyButland** [comment]
Another reference to a similar issue [here](https://our.umbraco.com/forum/umbraco-forms/80826-hard-iis-worker-crash-on-circular-conditions-on-field-even-when-condition-is-disabled).  Looks like we need better detection of "circular" conditions.

**Comment by PBHansen** [comment]
> Another example [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/623) with some added detail about the issue occurring even if one of the conditions is disabled.

Hey @AndyButland thank you for replying, it seems the link you have provided is linking to this issue.

**Comment by AndyButland** [comment]
Thanks - have fixed the link to the related issue.
