### ISSUE TITLE
ValidateSettings field gets wrong setting if empty/no PreValue is chosen

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#627]
When you add more than one fields with PreValues, the ValidateSettings  methode gets the wrong setting value.
Hard to explain so here are some screenshots:

![afbeelding](https://user-images.githubusercontent.com/18665536/129889118-4f5e5234-e32f-4fe9-a1ba-fa5100602032.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/129889157-963a74b0-691d-46ac-82c1-190da0a7a83e.png)

The message appears, i choos "Emailaddress". Then i add an other field of the same type and call this "Lastname" and again choose no value for ProfileField.

![afbeelding](https://user-images.githubusercontent.com/18665536/129889352-f8329e66-c877-43f8-b625-7c746decad9c.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/129889366-af754a3d-898f-47db-a0ed-3f65f1c9147e.png)

Reproduction
------------
Here is an example class of the formfield:

```
    public class TestField : FieldType
    {
        [Setting("ProfileField", Description = "", View = "Dropdownlist", PreValues = "Name, Emailaddress, Phone")]
        public string ProfileField { get; set; }

        public TestField(IScopeProvider scopeProvider)
        {
            Id = new Guid("6e73befe-c39e-436f-ac45-240ed645889e");
            Name = "Testfield";
            Description = "Test";
            DataType = FieldDataType.String;
            FieldTypeViewName = "FieldType.Test.cshtml";
            Icon = "icon-user ";
            HideLabel = false;
            SupportsPreValues = false;
            SupportsRegex = false;
            SortOrder = 25;
        }

        public override List<Exception> ValidateSettings()
        {
            List<Exception> exceptions = new List<Exception>();

            if (string.IsNullOrEmpty(this.ProfileField))
                exceptions.Add(new Exception("Choose a value"));
            return exceptions;

        }

    }
```

### Expected result

I would expect that the setting value of ProfileField == null when no PreValue is chosen.

### Actual result
The prevalue of the first set field is passed

**Comment by AndyButland** [comment]
Thanks - I've been able to replicate, and have found a fix, so will include in the next release.
