### ISSUE TITLE
Migrate Events to work for V8

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Forms.Issues#63]
Will need to get some insight from Shan or Stephan or how to implement & migrate these.

Then the rest of the task is repetition x 30 :-P

**Comment by sussexrick** [comment]
If there's the opportunity to add a "new form created" event that would be helpful :-)

**Comment by warrenbuckley** [comment]
@sussexrick there is a `FormStorage.Creating` & `FormStorage.Created` event that you should already be able to use

**Comment by sussexrick** [comment]
Brilliant, I'll take a look - thank you @warrenbuckley.

**Comment by warrenbuckley** [comment]
Closing this as confirmed with @zpqrtbnk that this work has already been done, when we got Forms V6 ready to work with Deploy & Cloud.
