### ISSUE TITLE
Show a validation message when creating a file upload field that has no permitted extensions

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Forms.Issues#631]
Currently it's possible to create a file upload field, selected to "Allow only specified files", but then not select or add any file extensions.  This means all files will be rejected when a user tries to use the field in a form.

Given this isn't a valid setup, we should show a validation message here.

**Comment by elit0451** [comment]
The issue has been fixed and is due in the next release 🎊
