### ISSUE TITLE
NullReferenceException when a picked form is deleted (using forms in database)

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#635]
When using forms in the database, opening a form picker where one of the forms is removed results in a `NullReferenceException` that is displayed in the back-office.

Reproduction
------------

### Steps to reproduce
Ensure forms are stored in the database, then use a form picker (e.g. allowed forms) to select a form, save, delete the selected form (the complete form itself) and re-open the form picker.

![NullReferenceException](https://user-images.githubusercontent.com/1051287/131135908-1f442908-ccf8-4e6d-a4ec-69e20de998bc.png)

**Comment by elit0451** [comment]
Fixed in #568
