### ISSUE TITLE
It's not clear that a form group title is editable

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Forms.Issues#636]
It is often unclear for editors that the title of a form group is editable.
Maybe it should have a border and a white background or something similar.

I get a lot of questions about the title in the current state. (In this case "Contact Us")

![image](https://user-images.githubusercontent.com/29602162/132462022-573fdced-fe3d-4a65-9503-379dde9554aa.png)

**Comment by AndyButland** [comment]
Yes, agreed.  I've updated now to look like this, so it's clearer that both page and group names are editable.

![image](https://user-images.githubusercontent.com/1993459/132529753-be0767dc-f8f5-49ce-b85f-abfffd5876d0.png)

**Comment by FransdeJong** [comment]
Nice! That will save some support requests.
