### ISSUE TITLE
Prevalue array in settings being used in validation when current field type does not support prevalues

### ISSUE THREAD

**Issue by james-whittington1** [umbraco/Umbraco.Forms.Issues#637]
When changing the field type from a field that does support prevalues to a field that doesn't, the prevalues control is removed but the prevalues setting array is left in place. When the field is submitted the back end validation is still requiring that the submitted value matches a prevalue option. 

This is problematic because it is not something that the person filling in the form can resolve, and is also something that is reasonably easy to introduce when editing the form.

Reproduction
------------
Add a new umbraco form
Add a multiple choice field to the form and set a prevalue. 
save the form
(at this point you can submit the from and verify it works)
open the multiple choice field and change the input from multiple choice to a checkbox
save the form
test submitting the form again. A validation error will be shown
### Bug summary

Form will not submit when the checkbox has an inapplicable prevalues array set.

The back end validation is checking that the value is present in the prevalues array, even though the checkbox field doesn't support prevalues.
 

### Specifics

Step 1, create a field with prevalues.
![image](https://user-images.githubusercontent.com/37091895/132595901-a86c8391-5990-4bc4-9e07-21c1bf94580c.png)

Step 2, change it to a field that doens't support prevalues.
![image](https://user-images.githubusercontent.com/37091895/132595941-bc74e3a0-49b9-4948-bd7a-66bdc5de675b.png)

Step 3, you cannot submit the form.

 Unexpected value: 'on'. Expected one of these: 'my cool option'

![image](https://user-images.githubusercontent.com/37091895/132595199-6dffbf7a-6972-45e7-85b1-1b0234a52261.png)

**Note:** I have only tested a multiple choice field type being changed to a checkbox field type, but it would be worth investigating if this is a wider issue with prevalues and the backend validation. 

### Steps to reproduce

as above.

### Expected result

I expect that prevalues that are not applicable to the current field type would not be used to validate the field. 

### Actual result

The form fails to validate and is returned to the user with an error message that is not possible to resolve.

**Comment by AndyButland** [comment]
Hi @james-whittington1 - I'm not seeing that with the latest code, and it does sounds like something we fixed recently, in [issue 572](https://github.com/umbraco/Umbraco.Forms.Issues/issues/548), fixed in 8.7.2.

Can you confirm if you are running a version earlier than that please, and if so, then you should find a fix if you upgrade.

**Comment by AndyButland** [comment]
Will close this now as not heard further, and it seems this is an issue that's been resolved in later version.
