### ISSUE TITLE
RecordFetching event not triggering in the backoffice v2

### ISSUE THREAD

**Issue by DennisBoonkP** [umbraco/Umbraco.Forms.Issues#639]
Hi guys,

I'm working on an package do encrypt Umbraco Forms data in the db. The encryption is implemented but when retrieving the data in the backoffice we have a problem and hopefully you can take a look shortly, so we can fix this and release the new and improved package. This report is a follow up on https://github.com/umbraco/Umbraco.Forms.Issues/issues/29.

We hoped that we could decrypt the data when plugging into the event
`RecordStorage.RecordFetching += RecordStorage_RecordFetching;`
So if we clicked on "Entries" in the backoffice forms-section this would get called and we could decrypt every record. But this isn't triggered.

Could you think for just a moment how we could achieve the decryption in the backoffice without rewriting whole parts of the work you've done?

Thank you very much!

### Bug summary
RecordStorage.RecordFetching event not triggerd in the backoffice

### Specifics
Tested with Umbraco 7.15.7 and UmbracoForms 7.5.4

### Steps to reproduce
- Add an event handler, Example:

```csharp
namespace Test2.Code
{
    public class RecordEvents : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {

            RecordStorage.RecordFetching += RecordStorage_RecordFetching;
        }

        private void RecordStorage_RecordFetching(object sender, Umbraco.Forms.Core.RecordEventArgs e)
        {
            throw new NotImplementedException();
        }
    }
}
```
- Open the "Entries "of a form in the backoffice.
- Nothing happens but I expect the event to betriggerd.

### Expected result
The event is triggerd when retching a record.

### Actual result
Nothing

**Comment by AndyButland** [comment]
I've had a look into this.  The issue here is that actually, the `RecordStorage` class isn't used to populate the "Entries" screens in the back-office, hence the event associated with that class isn't going to fire.  Rather the `FormRecordSearcher` (V7) or `IFormRecordSearcher` (V8) is used.

This doesn't have an equivalent event, but it seems like we could add one, allowing to do the amends to the records as you are looking to do.  There's a couple of PRs linked for V7 and V8, so will see how they go through review.

**Comment by DennisBoonkP** [comment]
Hé Andy, 

Thank you for your effort! An event would be great. When do you expect the new version with the new event is released? Then I can give an update to the customer.

With kind regards,
Dennis Boonk

**Comment by AndyButland** [comment]
No set date yet I'm afraid @DennisBoonkP - but once the fix is reviewed and tested I'll make a nightly build available to you.  It'll come officially in the next minor, hopefully within the next few weeks.
