### ISSUE TITLE
Form fieldtype DataConsent missing

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco.Forms.Issues#640]
Hi,
After upgrading a clients Umbraco version (7.15.5 -> 7.15.7) and forms version (6.0.7 -> 6.0.10), the DataConsent field (and Recaptcha2 for that matter) is missing. Forms which already are using the fields are now not rendering in backoffice or on the web. After upgrade I compared to the backup and the fields was missing from following locations:

- App_plugins/UmbracoForms/Backoffice/Common/Fieldtypes
- Views/Partials/Forms/Fieldtypes
- Views/Partials/Forms/Themes/default/Fieldtypes

I copied the fields back from the backup but they are still not showing in the backoffice and the forms are not rendering. When installing a new Umbraco installation (7.15.7) and downloading Umbraco forms (6.0.10) via nuget, the fields are missing as well, even though DataConsent should be included since forms version 6+: https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Editor/Creating-a-Form/Fieldtypes/.

### Bug summary
DataConsent and Recaptcha2 missing after upgrade and in new test installation.

### Specifics
Umbraco version: 7.15.7
Umbraco forms version: 6.0.10
Tested in Chrome and Edge

### Steps to reproduce
- Install a new Umbraco (7.15.7) installation via nuget
- Use the starter kit and sql server CE for a quick install
- Install Umbraco forms (6.0.10) via nuget
- Create a contact form

The contact form should include the field "Consent for storing submitted data" from the start but it isn't included. the field is missing as well when trying to add a new field:

![image](https://user-images.githubusercontent.com/19406378/133094142-238658c0-92e6-49f4-9607-ef68fd584d20.png)

### Expected result
The field "Consent for storing submitted data" should be included:

![image](https://user-images.githubusercontent.com/19406378/133094632-a4bd2633-b928-4cb1-935e-b3c7605fd2fc.png)

### Actual result
The field "Consent for storing submitted data" is missing when creating a contact form and when adding a new field:
![image](https://user-images.githubusercontent.com/19406378/133094825-fc7db809-ffb6-4966-a89d-c845adc795b1.png)

**Comment by AndyButland** [comment]
Have had a look at this and as far as I can see - by checking tags and commits in the source code repository - the "data consent" field wasn't introduced until V7 of Forms.  So that note on the documentation looks to be wrong and I think you must have a project that's at some point in the past had some files from a V7 version copied over.

I've checked back at the NuGets and zips, and neither 6.0.7 (what you upgraded from) and 6.0.10 (what you upgraded to) as the data consent view file included.

**Comment by bjornnorlen** [comment]
@AndyButland Thanks for fast reply. Yeah it seems weird. I upgraded to V7.0.7 so now fields showed up again. Thanks!
