### ISSUE TITLE
Extending Form Question, to add Category dropdown list

### ISSUE THREAD

**Issue by nnahmed** [umbraco/Umbraco.Forms.Issues#641]
Hi 

Trying to extend the Umbraco form questions, to provide choose category option. 

Need to add Action button or Select list, once user click it should fill the values from one of the Umbraco datatype. see below the reference image 

![image](https://user-images.githubusercontent.com/8067853/133313902-013ca92f-ae16-4873-81a8-668358e1d50d.png)

Thanks

**Comment by AndyButland** [comment]
I think this is probably a question best suited for [the forum](https://our.umbraco.com/forum/umbraco-forms/) where others who have looked to build similar custom fields may be able to help further.  I'll also reference the documentation on creating custom fields in case you've not yet seen that.  It starts from [this page](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/).
