### ISSUE TITLE
V9: Umbraco.DropDown.Flexible casing error

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#643]
On Umbraco V9.0.0-RC003

Getting the following error message in the back office when running on Linux:-
"Request error: The URL returned a 404 (not found):
views/propertyeditors/dropdownFlexible/dropdownFlexible.html"

Reproduction
------------

1. Add a property to a docType of type Umbraco.DropDown.Flexible and save the docType
2. Refresh the docType editor
3. See the red error bar appear with the message "Request error: The URL returned a 404 (not found): views/propertyeditors/dropdownFlexible/dropdownFlexible.html"

### Bug summary

On inspection, the error is looking for "dropdownFlexible/dropdownFlexible.html" while the actual path is "dropdownflexible/dropdownflexible.html"
(should be lower case "f" in "dropdownFlexible")

**Comment by AndyButland** [comment]
Thanks @craigs100.  It doesn't look like this is Forms related, and in checking I can see this has already been raised on the CMS tracker [here](https://github.com/umbraco/Umbraco-CMS/issues/10937) if you'd like to follow progress,  So will close this one.

**Comment by craigs100** [comment]
Hi @AndyButland, Don't know why this ended up in Forms, nor why my search didn't come up with the previous submission. Serves me right for raising an issue so late at night. Glad it's covered and sorry to bother ;)

**Comment by AndyButland** [comment]
No problem... thanks for testing late at night!
