### ISSUE TITLE
Placeholder input fields not placed in same order

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#649]
In Umbraco Forms v9.0.0 I noticed the "Placeholder" and "Default Value" not have same order on the different field types, which is confusing.

For example.

**Short answer**

![image](https://user-images.githubusercontent.com/2919859/136473573-504f6aa7-36e5-4c18-a422-3793ae5f4ae5.png)

**Long answer**

![image](https://user-images.githubusercontent.com/2919859/136473616-639be5ec-ac9d-4d03-9ede-07183b2db16f.png)

Why not the same order of the fields?

I think it is the only core fields, which both have fields for default value and placeholder.

**Comment by bjarnef** [comment]
@AndyButland are the fields stored in database or just registered runtime? I had a look at the db tables, but it seems these mostly contain data for folders, forms, prevalues and records, but not the specific field types?

**Comment by AndyButland** [comment]
They are defined in code, so registered at runtime as you say.
