### ISSUE TITLE
Feature request - Content apps for Umbraco Forms

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco.Forms.Issues#653]
I would love to see the option to have content apps for Umbraco Forms as we already have for Content & Media. In that way we can extend the functionality of Forms in an easier way.

The specific use case for now is that we want to tag Umbraco Forms with the uMarketingSuite and give them a score for personas and customer journey steps. In that way we can show the most relevant form according to our algorithm for the visitor, depending on the assumed persona and customer journey step.

![afbeelding](https://user-images.githubusercontent.com/12457148/136941542-eaf7eeb0-67f5-4c7b-8bdd-b853ebcfe1db.png)

**Comment by elit0451** [comment]
We have added support for this and it is planned for 8.10.0 and 9.2.0 🎊

**Comment by JeffreyPerplex** [comment]
Thanks you @elit0451. Any idea when this is planned to be released?

**Comment by AndyButland** [comment]
Not exactly yet @JeffreyPerplex - this is going in the minor release after the one due next week, but we'll try not to leave it too long.
