### ISSUE TITLE
Feature request - Configure mandatory workflow steps

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco.Forms.Issues#654]
I would love to have a way to configure a mandatory / default workflow step when creating a new Umbraco Form. Now the workflow "Submit message / go to page" is configured by default and you cannot delete that. I would love to have this option configurable for other workflow steps as well. 

Two options:

1) Workflow step X is added by default to the workflow
2) Is is possible to delete that step or not

![afbeelding](https://user-images.githubusercontent.com/12457148/136941904-17a8a6f8-44d9-4435-afe8-79499f029c85.png)

Specific use cases that we're having is:

*) We want to always delete the data (for GDPR purposes) after 24 months via a workflow, but also give the editor the option to change the setting to 12 months, 1 month, 36 months, or what ever. 
*) In the uMarketingSuite we want that every form is attached to a specific goal in the uMarketingSuite so that as soon as the form is submitted you'll score points for specific personas or a goal value. Now the editor has to do that manually and of course they always forget this. If we would have an option to add in a workflow by default when creating new forms, that would be great!

**Comment by AndyButland** [comment]
This has been implemented for the next minor releases.
