### ISSUE TITLE
Constants class clash in recaptcha views (v9)

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#657]
If you have another package installed which contains a public class called Constants the Umbraco Forms views for the recaptcha 2 & 3 in the default theme break, and stop the publish working in Visual Studio.

You can an error saying Constants is an ambiguous reference.

Manually fixing these files does not work, as on every build they are overwritten with the files from the nuget file.

I suggest mapping the Constants in these files using the full namespace do the fact they cannot be edited without being overwritten, additionally the copy function should check for changes before overwriting.

**Comment by AndyButland** [comment]
Good point - thanks.  I've fully qualified these now, which will be in the next release.
