### ISSUE TITLE
E-mail validation not working in v9.0.1

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Forms.Issues#666]
When using the e-mail validation regex on a field, it does not work. 
The code is generated for the validation, i.e. data-val-regex, data-val-regex-pattern and so on. 
But, not entering anything in the field, or even entering an invalid e-mail, will not produce a validation error. 

Reproduction
------------

### Steps to reproduce
Using Umbraco Forms 9.0.1:
Create a form with a text field and set it's validation to e-mail. 
Insert the form on a page and go to that page. 
Try and produce a validation error on the e-mail field. 
It will not. 

### Expected result

The form will render a validation error on an invalid e-mail address entered into the field. 

### Actual result

It does not render a validation error.

**Comment by AndyButland** [comment]
Have checked this following the steps described and am not able to replicate.  Could you double-check please you have the necessary front-end dependencies are in place, as per the documentation [here](https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Prepping-Frontend/index-v9)?  If so, maybe there's some JavaScript console errors you have and could share that is blocking the validation?

Also just to confirm, I don't see a validation error if I enter nothing in the field, but that's as expected unless the field is also set to be mandatory.  If I do enter a value that doesn't match the regex though, I do see the validation message appear.

**Comment by aguyfromdenmark** [comment]
This is so wierd. I can't reproduce the error anymore. I will close.
