### ISSUE TITLE
404 when trying to copy form

### ISSUE THREAD

**Issue by benjiew** [umbraco/Umbraco.Forms.Issues#669]
When trying to copy a form with v9.0.1 I receive a 404 error when clicking "Copy".

Request error: The URL returned a 404 (not found):
/umbraco/backoffice/umbracotrees/applicationtree/GetApplicationTrees

After a bit of debugging, I believe this is related to the request being made to GetApplicationTrees:

/umbraco/backoffice/umbracotrees/applicationtree/GetApplicationTrees?application=forms&tree=form&use=dialog&foldersonly=1

The **tree** parameter value is lower case which is causing the error, changing the value to "Form" succeeds.

**Comment by AndyButland** [comment]
Thanks @benjiew - can replicate, and your fix resolves the problem.  I'll get this in for 9.1, which is currently planned for release on Tuesday 16th.
