### ISSUE TITLE
V8 - Testing

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.Forms.Issues#67]
After initial build & UI works a lot of testing will need to be done.

We will need to create a test notes/plan for this

There is a lot of unknowns and potentially new follow up tasks/bugs will need to be fixed.

**Comment by clausjensen** [comment]
We have done "developer testing" and it seems like Forms is working as it should with V8. If we are to do extensive testing of this, we should create separate tasks for that.
