### ISSUE TITLE
Use default language for field name that are using translation items

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#672]
I have a multilingual site and use dictionary items as fields names. What I would like is the translation of the field instead of the translation item name in the Entries list. 
See screen copy:
![2021-11-16_12-51-42](https://user-images.githubusercontent.com/2814461/141990544-921563aa-6100-4cd2-8891-35e1c0537bc2.png)

**Comment by AndyButland** [comment]
This will be available in 8.10.0 and 9.2.0.
