### ISSUE TITLE
Member fields not replaced when submitting a form

### ISSUE THREAD

**Issue by Biancae** [umbraco/Umbraco.Forms.Issues#674]
When using a hidden field with {member.email} set to pass the value using the "Save as Umbraco content node" workflow, the member properties are not replaced. In the the related column in the entries section, the output is simply "{member.email}".

**Reproduction:**
* Create a form with a hidden field where the default value is {member.email}
* Create a workflow using "Save as umbraco content node", where the dynamic value of a field is set to the hidden field
* Try submitting the form

**Specifics:**
Umbraco v9
Using Google Chrome version 96.0.4664.45

**Expected results:**
The feild in the new content node should contain the email of the member submitting the form.
This should also be crosscheckable through entries.

**Actual results:** 
The field in the new content node should have the value "{member.email}", not the member property.
This should also be crosscheckable through entries.

**Creating the question with hidden field and default value**
![Edit_question](https://user-images.githubusercontent.com/14293381/142438506-a56b7401-da15-48c0-9a8a-5bd39f020801.png)
**Adding the hidden field to the workflow**
![workflow](https://user-images.githubusercontent.com/14293381/142438503-b995bc6e-7394-43d8-8923-f403c53b94b8.png)
**Result in content node**
![content_node_results](https://user-images.githubusercontent.com/14293381/142438508-334c948a-e6e6-49d6-b192-b47207fab692.png)
**Result in entry database**
![database_of_entries](https://user-images.githubusercontent.com/14293381/142438499-c4a51dff-f700-4de0-a8b4-fc521f534a07.png)

**Comment by AndyButland** [comment]
Thanks for the clear report on this @Biancae - can confirm I can replicate and there is a bug in the V9 version of forms related to logged in members and submitting forms that's causing this.  We're preparing a fix for the next release.
