### ISSUE TITLE
9.0.1 Email Workflows with no Sender specified don't fallback to Umbraco__CMS__Global__Smtp__From Appsetting.json

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Forms.Issues#676]
umbraco 9.0.1 and uForms 9.0.1

```
 "Umbraco": {
    "CMS": {     
      "Global": {
        "Smtp": {
          "From": "your@email.here",
          "Host": "localhost",
          "Port": 25
        }
      },
```
set in appsettings.json with no sender set in the workflow...
      
![Screenshot 2021-11-26 165810](https://user-images.githubusercontent.com/12418214/143612645-455b8279-d90f-42fb-b766-5a0407013ec1.png)

PS also note the incorrect reference to u8 umbracoSettings.config

**Comment by AndyButland** [comment]
Thanks for reporting.  Having checked I can see it's actually configured to fall back to the email configured at `Umbraco:CMS:Content:Notifications:Email`.

That said, I don't see why if that's empty, we don't fall back further to the one you've completed at `Umbraco:CMS:Global:Smtp:From`, so we'll set that up for the next release.

Have also fixed the incorrect labelling of a legacy configuration file.

**Comment by mistyn8** [comment]
@AndyButland  Thanks for the response and the work that goes into forms.

I Wasn't aware of that new config for `content-notifications` ;-)
Though if you are revisiting this is it semantically correct that UForms piggy backs this setting? 
Content notifications are likely to be internal comms, where as uForms are external comms. Is there scope to include a uForms setting for the default sender so that we can separate these?
Also with it being external email a displayname would be nice for uForms sender (or does the "DISPLAYNAME &gt;EMAIL&lt;" work?)

Maybe also a default bcc would be nice?
 
Sorry for all the feature requests....

**Comment by Wiggee11** [comment]
> Thanks for reporting. Having checked I can see it's actually configured to fall back to the email configured at `Umbraco:CMS:Content:Notifications:Email`.
> 
> That said, I don't see why if that's empty, we don't fall back further to the one you've completed at `Umbraco:CMS:Global:Smtp:From`, so we'll set that up for the next release.
> 
> Have also fixed the incorrect labelling of a legacy configuration file.

Hi @AndyButland 

I do actually feel that this is still incorrect, as it should be using the global SMTP details for sending Umbraco Forms emails.

That is what is described in the [Umbraco Forms documentation](https://docs.umbraco.com/umbraco-forms/13.latest/tutorials/creating-a-contact-form#configuring-simple-mail-transfer-protocol-smtp)...

> By adding the **SMTP settings in the appsettings.json** file, you can send out emails from your Umbraco installation. It is required in order for your form to be able to send emails on submission.
>
> To configure the SMTP settings, see the [Global Settings](https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#smtp-settings) article.

... and also described in the [Umbraco CMS SMTP settings documentation](https://docs.umbraco.com/umbraco-cms/13.latest/reference/configuration/globalsettings#smtp-settings)

> By adding this settings to the appsettings.json you will be able to send out emails from your Umbraco installation. This could be notifications emails if you are using content workflow, **or you are using Umbraco Forms you also need to specify SMTP settings to be able use the email workflows**. The forgot password function from the backoffice also needs a SMTP server to send the email with the reset link.

We have a scenario where the `Umbraco:CMS:Content:Notifications:Email` is set to a different email address to that in the global SMTP from and so emails do not send (that's our/client email policy blocking it).

If the global SMTP settings are set, which are required, then Umbraco Forms should use those.

Umbraco Forms 13.4.0
Umbraco CMS 13.5.3
