### ISSUE TITLE
Uri.EscapeUriString is obsolete

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco.Forms.Issues#678]
In Script.cshtml, `EscapeUriString` is used. This can corrupt the Uri string in some cases and gives a warning.

**Comment by AndyButland** [comment]
Have had a look at this - it does seem this method is being used in a perhaps unexpected way in Umbraco Forms, in that it's escaping not a Uri, but a JSON structure (that is then unescaped and parsed in JavaScript when form conditions are being applied).  However as there's been in the past a number of subtle issues around this, I'm minded to leave as is.  And simply replacing `EscapeUriString` with `EscapeDataString` doesn't work, as it leads to JavaScript errors when working with the values - seemingly as they aren't equivalent (the latter doing some additional escaping of `%2C --> ,  %3A --> :   %5B --> [   %5D --> ]`.

**Comment by Nuklon** [comment]
Maybe another solution then? The warning is annoying.
