### ISSUE TITLE
Two case typos prevent form style.css loading

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#680]
A brief description of the issue goes here.
A Case typo somewhere prevents loading /App_Plugins/UmbracoForms/Assets/Themes/Default/style.css when running on a Linux machine. Forms V9.1.1.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Case typos somewhere prevents loading /App_Plugins/UmbracoForms/Assets/Themes/Default/style.css

### Specifics

Case typos somewhere prevents loading /App_Plugins/UmbracoForms/Assets/Themes/Default/style.css

### Steps to reproduce

With a V9.0.1 site running on Linux with Forms V9.1.1. installed: In a razor page insert a form using the following method:-
@await Umbraco.RenderMacroAsync("renderUmbracoForm", new {FormGuid="87d993d9-a49b-447e-85e9-e2032f58e4c6", FormTheme="myTheme", ExcludeScripts="0"})

	@if (TempData["UmbracoForms"] != null) {
		@Html.RenderUmbracoFormDependencies();
	}

### Expected result

Expected the form to display with sensible styling and no console errors.

### Actual result

A bare-bones version of the form is displayed with the following console error:-
[localhost/:320](http://localhost:56034/App_Plugins/UmbracoForms/Assets/Themes/Default/style.css net::ERR_ABORTED 404 (Not Found))

On inspection, the "Themes/Default" segments of the path appear to be trying to reference what is actually "themes/default".  So whatever is calling /App_Plugins/UmbracoForms/Assets/Themes/Default/style.css should be changed to /App_Plugins/UmbracoForms/Assets/themes/default/style.css.

A word of caution though. I also noted that the sibling umbracoforms.js is currently being called correctly, so that will need to be checked once any fix is put in place as I can get correct functionality with the following tree structure:-
![Screenshot from 2021-12-06 21-25-26](https://user-images.githubusercontent.com/1143883/144925188-e54057c3-81a2-424c-9b1d-57502c32872c.png)

**Comment by AndyButland** [comment]
I can see where this is requested @craigs100 and fixed up the casing.  Just in time to squeeze the fix into the 9.2.0 RC due out later today if you'd like to try it out.

**Comment by craigs100** [comment]
Upgrading to 9.2.0--rc001 did not fix the issue.  I may do if it's a fresh install, but upgrading from 9.1.1 doesn't fix it.

![Screenshot from 2021-12-07 18-45-49](https://user-images.githubusercontent.com/1143883/145088129-27215280-e929-44dc-b5f4-bcb4f971a73b.png)

**Comment by AndyButland** [comment]
Hmm.. could you check in your `Form.cshtml` file please what you have?  As that's where the fix to casing was made.  If I look in the NuGet package it looks like it's got the update OK, so I'm not sure why that didn't get overwritten when you upgraded.

**Comment by craigs100** [comment]
Aha, I was referencing my own theme, so you're right. Changed the Html.SetFormThemeCssFile argument AND uppercased the 'l' of /App_Plugins/UmbracoForms/lang and it all now works.

Thanks Andy
