### ISSUE TITLE
Upgrade from V9.1.1 to 9.2.0-rc001 fails

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#681]
A brief description of the issue goes here.

Umb V9.1.2 on Linux
Upgrade from V9.1.1 to 9.2.0-rc001 fails in Rider 2021.2.2

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Umb V9.1.2 on Linux
Upgrade from V9.1.1 to 9.2.0-rc001 fails in Rider 2021.2

### Specifics

Umb V9.1.2 on Linux
Upgrade from V9.1.1 to 9.2.0-rc001 fails in Rider 2021.2

### Steps to reproduce

Developing an Umbraco V9.1.2 site with Rider 2021.2.2 on Linux Mint. Site has Umbraco Forms V9.1.1 installed. 
In Rider's Nuget window, select Umbraco.Forms 9.2.0-rc001 and select upgrade.

### Expected result

Successful upgrade

### Actual result

Warning about failed upgrade:-
![Screenshot from 2021-12-07 11-54-04](https://user-images.githubusercontent.com/1143883/145026212-b3dfe9dd-5323-40be-a3f4-b6e0d0e4ae62.png)

Can supply a full log if required.

**Comment by nul800sebastiaan** [comment]
As discussed on Discord, no need to install `Umbraco.Forms.Core`, but if you do have it installed then you need to start there, the dependencies need to be updated before the main package can be. Advise is to uninstall `Umbraco.Forms.Core` as `Umbraco.Forms` already takes care of pulling that one in. :)
