### ISSUE TITLE
Case typo prevents use of email templates on Linux

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#682]
A brief description of the issue goes here.

9.2.0--rc001 on Linux fails to send email due to incorrect path to templates

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

9.2.0--rc001 on Linux fails to send email due to incorrect path to templates

### Specifics

9.2.0--rc001 on Linux fails to send email due to incorrect path to templates.

The call to "/views/partials/Forms/Emails/ " should be to "/Views/Partials/Forms/Emails/"

Also incorrect in the WorkFlow: Email Template help text:-

![Screenshot from 2021-12-08 13-18-40](https://user-images.githubusercontent.com/1143883/145215136-43d5855a-7a3f-46f9-926e-2d62be7c6a53.png)

### Steps to reproduce

On a Linux machine Install Umbraco Forms V9.2.0-rc001, create a form, select a template to use. Add form to a page and attempt to send an email.

### Expected result

Email is sent

### Actual result

Exception
System.InvalidOperationException: Could not render view to string. Controller: Umbraco.Forms.Core.Controllers.RazorEmailViewController, View Path: **/views/partials**/Forms/Emails/Enquiry-Template.cshtml.
   at Umbraco.Forms.Web.Extensions.ControllerExtensions.RenderViewAsync[TModel](Controller controller, String viewPath, TModel model)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail.ParseWithRazorView(Record record, String razorViewFilePath)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SendRazorEmail.Execute(WorkflowExecutionContext context)

**Comment by AndyButland** [comment]
Thanks again @craigs100 for finding and reporting this one.  Have fixed up ready for the full release.
