### ISSUE TITLE
Updating record in workflow throws error if any record exists in database

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco.Forms.Issues#684]
A self contained example can be found here: 
https://github.com/Migaroez/umbraco-forms-issue-684/tree/main

### Specifics
Umbraco version: 7.15.7
UmbracoForms version: 7.5.5

### Steps to reproduce
Create a new workflow in code and add the following code from [the documentation](https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Workflowtype-v7)
```
RecordStorage store = new RecordStorage();
store.UpdateRecord(record, e.Form);
store.Dispose();
```

create 2 form entries, the second will fail

### Expected result

A way to update records in a workflow as illustrated by the documentation

### Actual result

Records not showing up in the backend, frontend still says everything is ok

**Comment by AndyButland** [comment]
I don't think this would be expected to work, as you are looking to update a record that hasn't yet been saved (I've tried your workflow, and stepping through can see the record's ID is zero).  The documentation isn't very clear about this, but I think that sample - created several years ago now - was intended only if you are supporting editing of fields via the front-end (i.e. using the option permitted by the `AllowEditableFormSubmissions` setting).

I'll make a small PR to the docs repo to clarify that.
