### ISSUE TITLE
Html.RenderFormsScripts is rendering script tags with duplicate 'type' attributes

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco.Forms.Issues#690]
The Html helper `Umbraco.Forms.Mvc.RenderFormsScripts` is injecting script tags with duplicate `type` attributes which is causing parse/validation issues in Chrome (96.0.4664.110).

![image](https://user-images.githubusercontent.com/59481722/146935932-8c63a2c3-4e6d-4ed4-80b0-a7a51612078f.png)

Reproduction
------------

### Bug summary

Umbraco.Forms version 8.80 is injecting script tags with duplicated `type` attributes such as `umbracoforms.js`. 

This is causing issues in Chrome as it ignores certain attributes such as `nonce` (relating to Content security policy) when it encounters an invalid script definition e.g. two 'type' attributes.

### Specifics

- **URL:** This occurs on any page which includes an Umbraco form.
- **Version:** 8.80 
- **Browser:** Chrome 96.0.4664.110
- **Other browsers:** Bug confirmed in FF 95.0.2

See `Html.RenderFormsScripts` in file `\Views\Partials\Forms\Themes\default\Script.cshtml` line 54.

The reason we're getting two `type` attributes included is because `Model.JavaScriptAttributes` by default includes it's own type attribute to be appended:

![image](https://user-images.githubusercontent.com/59481722/146937465-c0c0ddc7-b175-4c28-9685-033a490129d9.png)

Whilst the implementation of `RenderFormsScripts` also includes a type attribute as standard:

![image](https://user-images.githubusercontent.com/59481722/146937759-c8ba9dd0-3042-4838-8951-9737254156e1.png)

### Steps to reproduce

- Load any page which includes an umbraco form
- Right click 'view source'
- Search for `umbracoforms.js`
- Observe that the `type` attribute is defined multiple times against the tag

### Expected result

Script tags should include one instance of the `type` attribute. Although ideally, it should be completely excluded for W3C compliance.

### Actual result

We see scripts on the page being rendered with more than 1 `type` attribute.

Example:

![image](https://user-images.githubusercontent.com/59481722/146935932-8c63a2c3-4e6d-4ed4-80b0-a7a51612078f.png)

**Comment by AndyButland** [comment]
Thanks for reporting, we've fixed that up in the code and will make available in the next patch release, expected in the new year.

**Comment by d-gibbs** [comment]
@AndyButland - thanks for the speedy fix!

**Comment by AndyButland** [comment]
You're welcome... but think you did most of the work!
