### ISSUE TITLE
Upgrading Umbraco Forms from 8.6.2 to 8.9.1 introduced issue with some values not being saved

### ISSUE THREAD

**Issue by stefanie27** [umbraco/Umbraco.Forms.Issues#695]
We recently upgraded Umbraco Forms from 8.6.2 to 8.9.1 and later also to 8.10.0 to check if issue was resolved in latest version. 

The upgrade caused some form submission values not being saved. This is caused by the code to consider conditions set even when the conditions are disabled.

![image](https://user-images.githubusercontent.com/9352024/148883487-b347d1ec-55c4-44d3-a57c-367a56d7f286.png)

Reproduction
------------

1) Have Umbraco Forms 8.9.1 or 8.10.0 installed
2) On existing form or new created form, update a field with condition that can't be met. Save the form. Go back into the form field and disabled conditions and save.
3) Submit form with all fields entered and check if the value for the field with condition (disabled) is present

Possible Solution
------------------

Update code to include check for condition being enabled. 
Method IsVisible in Umbraco.Forms.Core\FieldConditionEvaluation.cs

![image](https://user-images.githubusercontent.com/9352024/148883922-e23a84a1-21d8-43d7-b54c-84147d660208.png)

**Comment by AndyButland** [comment]
Thanks for reporting @stefanie27 and for your efforts in finding the solution.  I believe we've already fixed this in some other work we've done recently investigating and fixing an issue with conditions (and I can see we've found the same fix as you).  The code is currently pending review but once it's passed that we'll have it out in the next patch release.  I'll associate this issue with that PR such that this will be closed labelled with the release number when it's planned.
