### ISSUE TITLE
Forms V9 does not find/use default smtp From address

### ISSUE THREAD

**Issue by drsmithsoftware** [umbraco/Umbraco.Forms.Issues#696]
If the From address is not specified in a Forms workflow step no email is sent despite all defaults being supplied in appsettings.json. In addition, the text displayed on the workflow form incorrectly refers to settings in umbracosettings.config.

### Bug summary

Trying to set up Forms to work on a new installation of Umbraco V9. Everything works fine and we are able to create a form and collect and examine entries received. If a workflow step to send an email on the submission of an entry is added, the form continues to work but no email is sent despite the fact that the appsettings.json file contains all the correct information (attaching a copy of appsettings.json but with a txt extension as the github bug report interface does not seem to support json files).

It is possible to make the workflow step functional by adding the same email address that is found in appsettings.json to the 'Sender Email' field of the workflow. According to the text displayed there ('Enter the sender email (if blank it will use the settings from /config/umbracosettings.config)') this should not be necessary and the form should simply use the default from email as defined in appsettings.

I note that the helpful text 'Enter the sender email (if blank it will use the settings from /config/umbracosettings.config)' is not that helpful in V9 where there is no config file. A user who does not understand the new architecture of a .Net Core application will search a long time for the correct place to configure SMTP based on this message.

Clearly this bug is not a showstopper as it is still possible to make Forms work. At the same time, it would be nice to be able to use a default From address and not have to modify each and every form when that address changes.

Thank you.

[appsettings.json.txt](https://github.com/umbraco/Umbraco.Deploy.Issues/files/7846931/appsettings.json.txt)
![2022-01-11 08_20_29-](https://user-images.githubusercontent.com/12074046/148952935-6613f105-8b95-496b-b046-778abc9ccad5.png)

**Comment by AndyButland** [comment]
Thanks for reporting this.  I think what you are describing though replicates [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/676), which was resolved in release 9.2.0.

I'll close this in the expectation that upgrading to this version should resolve your issue, but if you are on 9.2.0 already please re-open and I'll take a look further.

**Comment by drsmithsoftware** [comment]
I confirm that we are only on version 9.0.1 so this is in fact a non-issue.
Thanks for the quick response and for a great product.


David


________________________________________
David Smith

phone: +1 514.945.2185
***@***.***
