### ISSUE TITLE
ContentApp: why is both package.manifest and by code necessary?

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco.Forms.Issues#698]
Let me start by saying that I am very happy with the support of ContentApps in the new version of Umbraco Forms!
What strikes me is that in contrast to "regular" ContentApps, where only a package.manifest is sufficient, it is necessary for Forms to also use the C# option as well to make it work.

Is there a reason why a package.manifest just like with ContentApps can't suffice , just like "regular" ContentApps ? 

Reproduction
------------
Create only a package.manifest like in https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/ContentApps/index-v8, the ContentApp won't showup.

### Expected result

I would expect that ContentApps for Forms woudl work like other ContentApps by only adding a packagemanifest.

### Actual result

You need to all the steps in https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/ContentApps/index-v8 to get it working. Only creating a package.manifest is not enough.

**Comment by AndyButland** [comment]
Hi - yes, I was hoping we'd be able to do this too, but unfortunately I ran into some problems in getting this to work.  It stems from the fact that Umbraco CMS has some code that assumes knowledge of the different "show" options available to use for content apps in the package manifest file.  You can see it [here](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/Manifest/ManifestContentAppFactory.cs#L50), in the `ManifestContentAppFactory` class, where there's a switch statement for the four Umbraco entities (content, media, member and contentType) that are supported for content apps within the CMS.

As such it would need some extension points adding to the CMS for Forms (or any other external package with their own "entities" for management in the back-office) to be able to allow for the package manifest approach to registering.

**Comment by mcl-sz** [comment]
Thanks for the explanation @AndyButland , which explains why both are needed. No problem!
