### ISSUE TITLE
Date picker incorrectly sets moment.locale

### ISSUE THREAD

**Issue by etharion** [umbraco/Umbraco.Forms.Issues#70]
Umbraco: 7.12.4
Forms: 7.0.4

I found a "bug" in DatePicker.cshtml.
The problem is the calender gets my 'CultureInfo.CurrentUICulture.Name' but the pikaday.js doesnt, it defaults to 'en'.
And that results in the date that the picker outputs to the input field has chinese letters in the date.

What I found that solved the localization is:
moving line 27 in DatePicker.cshtml (moment.locale("@CultureInfo.CurrentUICulture.Name");) into a script tag just before the pikaday.js script init:
This way .locale is defined for both pikaday.js and the datepicker field.

Is there a reason why the .locale line is after the pikaday.js script?
Or will you be able to fix that in the next Forms version?

The code Forms ships with:
![image](https://user-images.githubusercontent.com/15627835/50204586-a8cb8080-0365-11e9-9733-ff84832558f8.png)

After changing placement of the moment.locale statement:
![image](https://user-images.githubusercontent.com/15627835/50204501-62762180-0365-11e9-89e5-e633d222399e.png)

**Comment by nul800sebastiaan** [comment]
Seems like a bug, thanks for showing how to fix it!

**Comment by bergmania** [comment]
This is implicit resolved in `7.0.6`, in a refactoring of the scripts.
