### ISSUE TITLE
Issue with deleting form with many entries

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/Umbraco.Forms.Issues#700]
There is an issue with deleting a forms that has alot of entries.

I have a project on Umbraco Cloud - who has issues with deleting a form with alot of entries. This specific form has 5+ Entries. 

This is the stacktrace from the error when trying to delete:

[stacktracedeletionform.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/7881027/stacktracedeletionform.txt)

Reproduction

You can try re-produce this with creating a form, and then create 4-5k+ Entries for that form, and then try to delete it. 

### Bug summary

  I think the issue is related to the amount of entries. 

### Specifics

Where applicable:

https://dbu.dk/umbraco/#/forms/form/edit/ad732643-404b-4c7e-a57d-af776bd7c37d - this is the exact form on Cloud that cant be deleted 
    
What version are you using

CMS 8.17.1 - Forms 8.9.1 - Deploy 4.4.1.0
    
What browser and version you are using

Chrome

Please include *full error messages* and *screenshots* if possible

![image](https://user-images.githubusercontent.com/20074364/149751394-7197f929-6d7f-4d45-b02b-07f13c031660.png)
![image](https://user-images.githubusercontent.com/20074364/149751440-d74282b7-b280-4af7-ad62-395faccd058f.png)
![image](https://user-images.githubusercontent.com/20074364/149751490-70137568-af59-4e79-97af-875f959894e9.png)

### Steps to reproduce

    1. Create a form
    2. Create entries for that form must be around 4-5k +
    3. Delete the form through the backoffice

### Expected result

  The form and all its entries should be deleted

### Actual result

 Error when deleting (look stacktrace above)

**Comment by AndyButland** [comment]
Have found the issue here and prepared a fix, which will be available in the next patch release.
