### ISSUE TITLE
Unable to open form after adding "On Approve" workflow in Forms 8.10

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#701]
When the option "Enable post moderation" under settings is turned on and a workflow is added, the form won't open anymore after saving.

Is looks like something goes wrong when merging the OnSubmit with the OnApprove workflows:

![afbeelding](https://user-images.githubusercontent.com/18665536/149774682-5c474e1e-55f2-492f-be9b-d9ef53aabd7d.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/149774791-7989d271-7d70-488b-a920-e1e0e17a00aa.png)

The console error is:

TypeError: label is undefined
    labelIsTranslated https://localhost:xxxx/App_Plugins/UmbracoForms/js/umbraco.forms.js?cdv=1:6283
    applyLocalizationLabelsToFormWorkflows https://localhost:xxxx/App_Plugins/UmbracoForms/js/umbraco.forms.js?cdv=1:6322
    <anonymous> https://localhost:xxxx/App_Plugins/UmbracoForms/js/umbraco.forms.js?cdv=1:1360

Reproduction
------------

- Install Umbraco Forms 8.10.
- Create a form and turn the "Enable post moderation" under Settings on.
- Add a workflow under "On Approve".
- Save the form

**Comment by AndyButland** [comment]
Hi - thanks for reporting, and we're aware of this one having had it previously reported [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/692).  There's a JavaScript patch file attached to that issue if you need it urgently, otherwise it'll be fixed up in the next patch releases.
