### ISSUE TITLE
ContentApp not loading on new form

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#702]
When a new form is created, the ContentApps are not showing up.

Reproduction
------------

- Create a ContentApp like https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/ContentApps/
- Create a new form, the ContentApp is not shown.
- Save the form
- The ContentApp is shown

### Expected result

ContentApp should be shown on new (unsaved) forms as well.

### Actual result

The ContentApp is only showing when the form is saved.

**Comment by AndyButland** [comment]
I'm wasn't so sure about doing this when implementing the feature... as if the form isn't saved, I couldn't see what the point of a content app would be, as it wouldn't have a form record to relate to and present some contextual information.  Can you let me know the use case you have in mind here please, to consider whether it does make sense to have them presented also on as yet uncreated forms?  Thanks.

**Comment by inetzo** [comment]
We use ContentApps to set the number of retention days after which the Entries should be deleted and we have one to set the users that have acccess to the form. Both are save data via ApiControllers when saving the form by intercepting the PostSave.

**Comment by AndyButland** [comment]
Actually... ignore what I said above, but it looks to me that they do display both for new and existing forms.   The one I've got for testing is created like this:

```
    public class TestFormsContentApp : IContentAppFactory
    {
        public ContentApp GetContentAppFor(object source, IEnumerable<IReadOnlyUserGroup> userGroups)
        {
            // Only show app on forms
            if (source is FormDesign)
            {
                return new ContentApp
                {
                    Alias = "testFormsContentApp",
                    Name = "Test App",
                    Icon = "icon-calculator",
                    View = "/App_Plugins/TestFormsContentApp/testformscontentapp.html",
                    Weight = 0,
                };
            }

            return null;
        }
    }
```

And added via a component like this:

```
    public class TestSiteComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.ContentApps().Append<TestFormsContentApp>();
        }
    }
```

Can you see what's different with yours to perhaps explain why it's not showing for you?

**Comment by inetzo** [comment]
You're right. I did a fresh installation and indeed the content app is shown on a form that has not yet been saved.

My mistake, thank you very much for checking.
