### ISSUE TITLE
Disable escape sequence in Long Answer Field

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#703]
I have a Contact form with a long answer field. 
When an url is entered by the user (https://localhost:44305/Contact-us) the value I get via  a custom workflow has escaped characters like https:\/\/localhost:44305\/Contact-us.
Here is the function used to retrieve the field value in the workflow: record.GetRecordFieldByAlias("message").ValuesAsString()

How can I get a string without the escaped chars?

**Comment by AndyButland** [comment]
Looks like you can pass an `escaped` parameter to `ValuesAsString()`.  By default it's `true`, but if you provide `false` you should get back the unescaped version.
