### ISSUE TITLE
Get reCaptcha V3 score in Form Entries and Workflow

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#704]
Hello,

Is it possible to get reCaptcha V3 score in Form Entries and Workflow. I wan to tune the score and see what is the score of obvious spam enties.

**Comment by AndyButland** [comment]
We can perhaps look to add this in future, but I just thought to note now that you should find that form submissions that don't meet the score threshold are logged - with a message and placeholders of the following:

```
The Google reCAPTCHA v3 score {RecaptchaScore} did not meet the user defined threshold of {FieldThreshold} for the field {FieldAlias} on {FormName}
```

So you may be able to use that for your analysis.

**Comment by c9mbundy** [comment]
@AndyButland - Yes, that's very useful, but as mentioned in #664 when spam DOES continue to get through, it would be really useful to know what its score was, so you can raise the threshold just enough to block it, while trying to avoid blocking valid submissions.

While I'm at it, I'm still unclear what causes this INFO message, and how it's related to reCaptcha blocking:
`INFO | Umbraco.Forms.Core.Providers.FieldTypes.Recaptcha3 | The 'g-recaptcha-response' hidden field for reCAPTCHA v3 is missing/empty and thus unable to be verified`

While it typically happens within a "spam-attack" wave, there is no obvious pattern to when, and not enough info to deduce the why, and so I'm concerned of the possibility that valid submissions may be getting lost.

**Comment by AndyButland** [comment]
That second INFO message will be logged if when the field is validated server-side, there is no value in the hidden field named `g-recaptcha-response`.  This is populated client-side by the reCAPTCHA script when the page is loaded (on the `DOMContentLoaded` event - you can see this part in the `,cshtml` file).  So I suspect there are some cases where the form is submitted before this initialization has completed.

**Comment by AndyButland** [comment]
Thanks for noting that we have this in the issue tracker by the way.  As such I'll close this one so we avoid having a duplicate.  For further work on this or discussion please see [issue 664](https://github.com/umbraco/Umbraco.Forms.Issues/issues/704).

**Comment by c9mbundy** [comment]
@AndyButland - Yes, every time I test with a human, it works just fine, but I guess that scenario (submit before recaptcha token is initialized) is possible with a BOT filling in the form, as the sequence in the script is - enable the submit button before setting the recaptcha token - however it's nonetheless surprising that this event logs more often than the threshold-failure by a factor of around 5-1.

**Comment by hfloyd** [comment]
@c9mb & @AndyButland - I'm seeing this error (and thus the form is failing to submit) even if I fill it in manually myself.

`The 'g-recaptcha-response' hidden field for reCAPTCHA v3 is missing/empty and thus unable to be verified` is showing up in the Log. 

This occurs even if I have the ReCaptcha question configured with a threshold of "0" or "0.1"

**Comment by hfloyd** [comment]
I took a look at the field rendering file and saw this:

```
        @* Google JS reCAPTHA API and initialization scripts *@
        Html.AddFormThemeScriptFile("https://www.google.com/recaptcha/api.js?render=" + siteKey);
        Html.AddFormThemeScriptFile("~/App_Plugins/UmbracoForms/Assets/recaptcha.v3.init.js");
```
But when I view the page with the form on the front-end, and "View Source", I don't see those scripts referenced in the HTML.

I do have `@Html.RenderUmbracoFormDependencies()` in the master template, and I see these scripts rendered out:

```
<script src='/App_Plugins/UmbracoForms/Assets/promise-polyfill/dist/polyfill.min.js' type='application/javascript'></script><script src='/App_Plugins/UmbracoForms/Assets/aspnet-client-validation/dist/aspnet-validation.min.js' type='application/javascript'></script>
```

I'm not sure why those Recaptcha scripts aren't being included.

I created an override in my Form Theme for the rendering file (FieldType.Recaptcha3.cshtml) and swapped out the previous for a direct rendering of the scripts:

```
        var recaptchaScriptUrl = $"https://www.google.com/recaptcha/api.js?render={siteKey}";

        <!-- Google JS reCAPTHA API and initialization scripts -->
        <script src="@recaptchaScriptUrl" type="application/javascript"></script>
        <script src="~/App_Plugins/UmbracoForms/Assets/recaptcha.v3.init.js" type="application/javascript"></script>
```

And then my entry went through just fine.

**Comment by AndyButland** [comment]
@hfloyd - if you aren't seeing those scripts in the source, I think you must have the form being rendered with the "ExcludeScripts" parameter set, and don't have [this code](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Rendering-Scripts/#rendering-forms-scripts) in your template that can be used in conjunction with that setting to render out the script references at the bottom of the page.

**Comment by hfloyd** [comment]
Ah, I thought `@Html.RenderUmbracoFormDependencies()` would handle all the scripts... I will look into updating my template. Thanks!
