### ISSUE TITLE
Fix nullable reference warnings

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#705]
When nullable reference types are enabled, Umbraco Forms produces build warnings.

### Steps to reproduce

In Visual Studio 2022 create a new .NET 5 web application and install Umbraco 9.2 and Forms 9.2. 

On the Build > General tab of the project properties, enable nullable reference types and build the project.

![image](https://user-images.githubusercontent.com/1260550/150637294-4a528291-e719-4011-bb39-50fee79087a9.png)

### Expected result

There are no warnings related to Umbraco Forms.

### Actual result

![image](https://user-images.githubusercontent.com/1260550/150637217-2fff0b1a-300f-4974-9abf-789268256d75.png)

**Comment by AndyButland** [comment]
You should find this resolved for the version 10 release, currently available as a release candidate.
