### ISSUE TITLE
Typo in label description

### ISSUE THREAD

**Issue by md-hc** [umbraco/Umbraco.Forms.Issues#710]
_"Indicate whether **the the** field's label should be shown when rendering the form."_

Found in `en-US.xml` for keys:

- multipleChoiceShowLabelDescription
- dropdownShowLabelDescription
- singleChoiceShowLabelDescription
- longAnswerShowLabelDescription
- shortAnswerShowLabelDescription

Fixed on our version with `en-us.user.xml` using the new localization feature, but wanted to raise an issue so it's fixed for future versions :)

**Comment by AndyButland** [comment]
Thanks, will fix that up.  Will mark for release for the next minor but if there's another patch of 8.10 before then it'll be included in that too.
