### ISSUE TITLE
AllowEditableFormSubmissions is set to true by default when installing via NuGet

### ISSUE THREAD

**Issue by md-hc** [umbraco/Umbraco.Forms.Issues#711]
Just upgraded from v8.8.0 -> v.8.10.1 and noticed the NuGet upgrade changed allowEditableFormSubmissions to true (we had it set to false):

`<setting key="AllowEditableFormSubmissions" value="True" />`

My understanding is this should be `false` by default:

https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Configuration/index-v7#alloweditableformsubmissions

Might not be an issue but thought I'd flag just in case!

**Comment by AndyButland** [comment]
Thanks for letting us know.  And no, that shouldn't have happened, unfortunately this change was inadvertently checked in.  Will make sure to revert in the next patch release.
