### ISSUE TITLE
Form menu links cause errors when opened in new tab/window

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#717]
The links to the form editors in the tree navigation have an extra "/" that causes the the page to throw the following error when opened in a new tab or window. 

> Uncaught Error: [$location:badpath] Invalid url "//forms/form/edit/c796f357-4ea4-4d50-a3d6-4f3a225b9c71".

This is because the href starts with "#//" when it should start with "#/." There's an unneeded "/" somewhere that just needs to be removed to fix this issue. This isn't urgent by any means, since the click handling bypasses this issue when navigating normally. It just makes it a little easier to open a form in another tab/window to compare with the current form.

For reference I encounter this problem in umbraco 8.17.1 with umbraco forms 8.10.1

**Comment by AndyButland** [comment]
Thanks - that looks like an easy fix to remove the double slash.  I have a silly question though, how do you open the form in a new window?  As the usual right-click menu is disabled as it launches the menu with the move, copy, delete etc. actions.

**Comment by AndyButland** [comment]
Have fixed the links to remove the additional slash.  Will be updated in the next patch releases.

**Comment by jaandrews** [comment]
My mouse has a clickable mouse wheel that opens a link in a new tab when pressed.
