### ISSUE TITLE
CheckBoxList not being picked up in custom theme.

### ISSUE THREAD

**Issue by Rogn** [umbraco/Umbraco.Forms.Issues#718]
Hi,

When creating a custom theme, I noticed that the themed CheckBoxList, was not being picked up, when deployed to our K8s environment. It was working fine locally on my windows dev machine

And after quite some digging, I discovered that by renaming the file in the custom theme folder FieldType.Check**B**oxList.cshtml -> FieldType.Check**b**oxList.cshtml (Changed the B to a lowercase) it started working.

So I think there is a mismatch between the casing, which the default theme is using and the FieldTypeViewName of the CheckBoxList type. 

This issue might also apply for some of the other FieldTypes available in the default theme, for example FieldType.CheckBox.cshtml and FieldType.DropDownList.cshtml.

Umbraco 9.1.0
Umbraco Forms 9.2.1
Env: Linux

**Comment by AndyButland** [comment]
Thanks for letting us know, and yes, can see a few of these don't align.  Have made sure they are the same now which we'll update in the next patch release.
