### ISSUE TITLE
Issue with reCAPTCHA V3 with Score 

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/Umbraco.Forms.Issues#720]
Hey Guys - Muslim from umbraco support here :) 

If we want to change the Settings/Score Threshold value, we can only do it with 'drag to scroll' mode and if we want to change it by clicking on it, the changes has no effect.

Versions:
![image](https://user-images.githubusercontent.com/20074364/152774054-eafdb3ec-707b-4083-a6ef-136d53ba824d.png)

### Steps to reproduce

 Create a new project.
Create a new form
Add a question
use the recaptcha3 with score
click on a score value 
save
go back to the recaptcha3 -> value is not changed.

But if you slide it - then the value changes. 

### Expected result

   The value should be changed when clicking on a score. 

### Actual result

 Score us not changed.

I have attached a video on  this aswell. 

[Recaptcha_v3_bug.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/8014554/Recaptcha_v3_bug.zip)

**Comment by thejokerd3** [comment]
I have tested this on the latesat release of forms :)

**Comment by AndyButland** [comment]
Thanks for reporting - can replicate.  We are updating the underlying value when the slider reaches it's end position, and so missing if you set a value not using the slider itself (i.e. by clicking on a value).  Have switched to a different event to catch this as well as when you use the slider.  Due in the next patch.
