### ISSUE TITLE
When user is authorized using LDAP, Forms will require the user to be a member in the site

### ISSUE THREAD

**Issue by AnIslander** [umbraco/Umbraco.Forms.Issues#721]
This is a reopening of [https://github.com/umbraco/Umbraco.Forms.Issues/issues/707#issue-1112549760](https://github.com/umbraco/Umbraco.Forms.Issues/issues/707#issue-1112549760)

The issue was closed, but since then we upgraded forms to 8.7.6 as recommended in the mentioned issue, without any success.

We are running an Umbraco 8.7.0 website implementing an Intranet for a Danish Municipality. As this is an Intranet, users are authorized in an implementation of Single-Sign-On using LDAP authentication against the municipality's on site Active Directory.

When authenticated header is enriched with a claim based Identity of the current user.

When users are authenticated using SSO and we attempt to render a simpel form, Umbraco Forms throws an "Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'" exception and looking into stack trace of this exception, it shows that Umbraco Forms are throwing this Exception, because it assumes that the user is registered as an Umbraco Member of the site - we are not using the Member feature and would not expect Umbraco Forms to make assumptions on this in order to render the form.

In our test environment users are authenticated using IIS Forms Authentication and the forms rendering is working as expected.

This issue is apparently related to this one https://github.com/umbraco/Umbraco.Forms.Issues/issues/253. - This issue relates to Azure AD. Our solution is not authenticating against Azure AD, but against the municipality's onsite Active Directory. The Intranet website is running in a single Azure Web App.

Reproduction
If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

Bug summary
Specifics
We are currently running Umbraco Forms 8.7.6 in the site. This has been upgraded from Forms 8.5.3 as per request from Umbraco support.

The site is running Umbraco 8.7.0. It has been migrated from an Umbraco 7.3.8 using Umbraco migrations and proworks.Umbraco8.Migrations.

The site is working in Chrome, Edge, IE 11 and Firefox.

The form tested is rendered in the Macropartial InsertUmbracoForm.cshtml

InsertUmbracoForm.cshtml code

```
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@if (Model.MacroParameters["FormGuid"] != null)
{
    var s = Model.MacroParameters["FormGuid"].ToString();
    var g = new Guid(s);

    var recordGuid = Guid.Empty;

    if (string.IsNullOrEmpty(Request.QueryString["recordId"]) == false)
    {
        Guid.TryParse(Request.QueryString["recordId"], out recordGuid);
    }

    try
    {
        Html.RenderAction("RenderForm", "UmbracoForms", new { formId = g, recordId = recordGuid });
    }
    catch (Exception e)
    {
        <p>Exception message = @e.Message</p>
        <p>formid = @g</p>
        <p>Recordid = @recordGuid</p>

        if (Html == null)
        {
            <p>Html is null</p>
        }
    }
}
```

Log with stack trace for Exception thrown (from Umbraco log):

{"@t":"2021-12-01T08:50:09.5186431Z","@mt":"Failed {MsgIn}","@l":"Warning","@x":"System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n at Umbraco.Core.Persistence.Querying.ExpressionVisitorBase.VisitMethodCall(MethodCallExpression m) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Querying\\ExpressionVisitorBase.cs:line 416\r\n at Umbraco.Core.Persistence.Querying.ExpressionVisitorBase.Visit(Expression expression) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Querying\\ExpressionVisitorBase.cs:line 123\r\n at Umbraco.Core.Persistence.Querying.ExpressionVisitorBase.VisitLambda(LambdaExpression lambda) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Querying\\ExpressionVisitorBase.cs:line 158\r\n at Umbraco.Core.Persistence.Querying.ExpressionVisitorBase.Visit(Expression expression) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Querying\\ExpressionVisitorBase.cs:line 76\r\n at Umbraco.Core.Persistence.Querying.Query`1.Where(Expression`1 predicate) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Querying\\Query.cs:line 32\r\n at Umbraco.Core.Services.Implement.MemberService.GetByUsername(String username) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\MemberService.cs:line 456\r\n at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\AppCacheExtensions.cs:line 62\r\n at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\FastDictionaryAppCacheBase.cs:line 285\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at Umbraco.Core.Cache.HttpRequestAppCache.Get(String key, Func`1 factory) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\HttpRequestAppCache.cs:line 81\r\n at Umbraco.Core.Cache.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\AppCacheExtensions.cs:line 62\r\n at Umbraco.Web.Security.MembershipHelper.GetCurrentMember() in D:\\a\\1\\s\\src\\Umbraco.Web\\Security\\MembershipHelper.cs:line 359\r\n at Umbraco.Web.Security.MembershipHelper.GetCurrentMemberId() in D:\\a\\1\\s\\src\\Umbraco.Web\\Security\\MembershipHelper.cs:line 372\r\n at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GetFormModel(Guid formId, Nullable`1 recordId)\r\n at Umbraco.Forms.Web.Controllers.UmbracoFormsController.Render(Guid formId, Nullable`1 recordId, String view, String mode)\r\n at lambda_method(Closure , ControllerBase , Object[] )\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.<>c__DisplayClass5_0.<Wrap>b__0()\r\n at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func)\r\n at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)\r\n at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)\r\n at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage)\r\n at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)\r\n at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter)\r\n at System.Web.Mvc.Html.ChildActionExtensions.RenderAction(HtmlHelper htmlHelper, String actionName, String controllerName, Object routeValues)\r\n at ASP._Page_Views_MacroPartials_InsertUmbracoForm_cshtml.Execute() in C:\\home\\site\\wwwroot\\Views\\MacroPartials\\InsertUmbracoForm.cshtml:line 17\r\n at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()\r\n at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()\r\n at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)\r\n at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in D:\\a\\1\\s\\src\\Umbraco.Web\\Mvc\\ProfilingView.cs:line 25\r\n at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult) in D:\\a\\1\\s\\src\\Umbraco.Web\\Mvc\\ControllerExtensions.cs:line 80\r\n at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\PartialViewMacroEngine.cs:line 98\r\n at Umbraco.Web.Macros.MacroRenderer.<>c__DisplayClass17_0.<ExecuteMacroOfType>b__0() in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 342\r\n at Umbraco.Web.Macros.MacroRenderer.ExecuteProfileMacroWithErrorWrapper(MacroModel macro, String msgIn, Func`1 getMacroContent, Func`1 msgErr) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 313\r\n at Umbraco.Web.Macros.MacroRenderer.ExecuteMacroWithErrorWrapper(MacroModel macro, String msgIn, String msgOut, Func`1 getMacroContent, Func`1 msgErr) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 272\r\n at Umbraco.Web.Macros.MacroRenderer.ExecuteMacroOfType(MacroModel model, IPublishedContent content) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 339\r\n at Umbraco.Web.Macros.MacroRenderer.Render(MacroModel macro, IPublishedContent content, IDictionary pageElements) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 245\r\n at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.<>c__DisplayClass7_0.<RenderRteMacros>b__1(String macroAlias, Dictionary`2 macroAttributes) in D:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 64\r\n at Umbraco.Web.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback) in D:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroTagParser.cs:line 196\r\n at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview) in D:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 70\r\n at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.Convert(Object source, Boolean preview) in D:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 96\r\n at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview) in D:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 78\r\n at Umbraco.Core.Models.PublishedContent.PublishedPropertyType.ConvertInterToObject(IPublishedElement owner, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview) in D:\\a\\1\\s\\src\\Umbraco.Core\\Models\\PublishedContent\\PublishedPropertyType.cs:line 219\r\n at Umbraco.Web.PublishedCache.NuCache.Property.GetValue(String culture, String segment) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedCache\\NuCache\\Property.cs:line 211\r\n at Umbraco.Web.PublishedPropertyExtension.Value[T](IPublishedProperty property, String culture, String segment, Fallback fallback, T defaultValue) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedPropertyExtension.cs:line 39\r\n at Umbraco.Web.PublishedContentExtensions.Value[T](IPublishedContent content, String alias, String culture, String segment, Fallback fallback, T defaultValue) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedContentExtensions.cs:line 177\r\n at ASP._Page_Views_Dokument_cshtml.Execute() in C:\\home\\site\\wwwroot\\Views\\Dokument.cshtml:line 84\r\n at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()\r\n at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()\r\n at System.Web.WebPages.StartPage.ExecutePageHierarchy()\r\n at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)\r\n at Umbraco.Web.Mvc.ProfilingView.Render(ViewContext viewContext, TextWriter writer) in D:\\a\\1\\s\\src\\Umbraco.Web\\Mvc\\ProfilingView.cs:line 25\r\n at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)\r\n at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)\r\n at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","MsgIn":"Executing PartialView: MacroSource=\"~/Views/MacroPartials/InsertUmbracoForm.cshtml\".","SourceContext":"Umbraco.Web.Macros.MacroRenderer","ProcessId":43392,"ProcessName":"w3wp","ThreadId":71,"AppDomainId":2,"AppDomainAppId":"LMW3SVC538071486ROOT","MachineName":"dw1mdwk00000O","Log4NetLevel":"WARN ","HttpSessionId":"jg4trwhq3ax1gqe542uoa0oh","HttpRequestNumber":1342,"HttpRequestId":"145fd402-3e53-476c-a1e6-8b77fa750e7b"}

Steps to reproduce
Setup site to Authenticate using LDAP against an onsite Active Directory.
Login using Authentication setup
Try to render a form embedded in a RTE.

Expected result
Form is rendered and submit recorded in the Forms module.

Actual result
Rendering is throwing Exception (see above)

**Comment by AnIslander** [comment]
Related issue : [https://github.com/umbraco/Umbraco.Forms.Issues/issues/253#issue-535776771](https://github.com/umbraco/Umbraco.Forms.Issues/issues/253#issue-535776771)

**Comment by AnIslander** [comment]
Any news on this issue ?

**Comment by AnIslander** [comment]
Any news ?

**Comment by AndyButland** [comment]
Am just having a dig through the code and timing of updates.  I can see up until Forms 8.6.2 we had this code in the area where your exception is being thrown:

```
if (Members.IsUmbracoMembershipProviderActive())
{
	memid = Members.GetCurrentMemberId();
}
```

Which I can understand might through an exception if the Umbraco membership provider is still active, but you aren't actually using it.

As of Forms 8.7.0 though, we have this:

```
if (Members.IsUmbracoMembershipProviderActive())
{
	try
	{
		memid = Members.GetCurrentMemberId();
	}
	catch (Exception e)
	{
		Logger.Error(typeof(UmbracoFormsController), "Can't get the current members Id", e);
	}
}
```

Which seems to me it will log an exception, but not throw on it - and hence I can't understand how you get that stack trace if you are running this version.

Would suggest check a couple of things:

1. Make sure you are definitely upgraded to at least Forms 8.7.0.  You can check the File version on the `Umbraco.Forms.Web.dll` that's deployed to your server to be 100% sure.
2. If you aren't using the Umbraco membership provider, it seems like you could remove it from your `web.config` file, as discussed in [this comment](https://github.com/umbraco/Umbraco.Forms.Issues/issues/253#issuecomment-564578566) on the related issue you linked to above.

**Comment by AndyButland** [comment]
Will close this one now - as haven't been able to replicate or have had any further reports, and it seems the issue has been resolved in an earlier version.

**Comment by RasmusNohr** [comment]
Hi,

This is still a issue for us.
As mentioned in the last comment from @AndyButland, I have now checked and tried the suggestions:

1. _Make sure you are definitely upgraded to at least Forms 8.7.0. You can check the File version on the Umbraco.Forms.Web.dll that's deployed to your server to be 100% sure._

- I have checked the File version of Umbraco forms that is deployed to the production app service. We are using "8.7.6.0".

2. _If you aren't using the Umbraco membership provider, it seems like you could remove it from your web.config file, as discussed in https://github.com/umbraco/Umbraco.Forms.Issues/issues/253#issuecomment-564578566 on the related issue you linked to above._

- I have tried to remove the `UmbracoMembershipProvider` from the web.config, since we are not using it, but with no success. I get YSOD with error message: "System.InvalidOperationException: No membership provider found with name UsersMembershipProvider"
- If change the membership provider to use a `SqlMembershipProvider`, and use the Umbraco connectionstring. Then I can't log in to the Umbraco Backoffice.

I can see that this issue is been closed, is it possible to re-open it?

We are only facing the issue in production, where we are using the LDAP authentication against the municipality's on site Active Directory.

**Comment by AndyButland** [comment]
Will re-open, but to progress I think I'll need to ask if you'd be able to please provide me with a cut-down project that demonstrates the issue - or perhaps the minimum code/configuration you need to add to an clean Umbraco site running the same versions of CMS and Forms that you have to show it.  If I have that maybe I can see what I'm missing when I look over the code history and what was done previously to address this issue.

Would that be possible please?  If so I'm at abl AT umbraco DOT dk.  Thanks.

**Comment by AndyButland** [comment]
We'll re-close this issue now given there's been no further discussion.
