### ISSUE TITLE
Umbraco forms: Entries list in backoffice not showing correct date/timezone

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco.Forms.Issues#723]
Umbraco Forms 9.2.1

Replication steps
Submit a form on the website

Expected results
When looking at the record in the backoffice UI, the ‘created’ date shows the time the form was submitted, “11 feb 22 15:37”

Actual results
The UI shows a created date of “12 feb 22 04:37” which is in the future at the time of writing.

Is there some sort of UTC timezone conversion issue? When I look at the database record it has “2022-02-11 15:37:19.093” which is correct.

After writing up this ticket, I then noticed the following in the markup next to the date:
`<!-- TODO: Get the users locale & determine best time format for date filter -->`

Is there an existing ticket for this?
Thanks

**Comment by AndyButland** [comment]
It looks like there's two conversions going on here.  Firstly the user's local time offset is provided in the request to receive the records, and the created/updated date times are adjusted.  But then we're using an angularjs filter client-side that's adjusting it again.  I believe we only need the former so have removed the latter, which will be in the next release.

**Comment by shearer3000** [comment]
thanks - looks better in 9.3 :)
