### ISSUE TITLE
A more feature-rich API for getting records

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Forms.Issues#724]
As far as I know, the only viable way to get forms records is through the `IRecordReaderService`. But the exposed methods of that implementation leaves a lot to be desired. You could go directly to the database, but the data you want is spread over a number of tables, making querying hard. I would love to see a more feature-rich API for getting the records for a form. 

Suggestions for functionality: 
- Get records in a date range
- Sort the records by a field

This will be very helpful when developing features such as custom dashboards, where you aggregate form records, and allows the user to sort throug the data.

**Comment by AndyButland** [comment]
There is the `IFormRecordSearcher` available, which looks to give a bit more flexibility and may be what you are after.  Specifically the `EntrySearchResultCollection QueryDataBase(RecordFilter model);` method.

**Comment by aguyfromdenmark** [comment]
> 

As far as I can see, that method in particular is not exposed. 
![image](https://user-images.githubusercontent.com/6904597/153560813-ac37a89b-d267-47e6-b11a-018f1a1b1fff.png)

**Comment by AndyButland** [comment]
Hmm - it looks like it should be, and I can see `QueryDatabase` in your screenshot there?

**Comment by aguyfromdenmark** [comment]
> There is the `IFormRecordSearcher` available, which looks to give a bit more flexibility and may be what you are after. Specifically the `EntrySearchResultCollection QueryDataBase(RecordFilter model);` method.

That laves me with this error. 
![image](https://user-images.githubusercontent.com/6904597/153565067-c3cae46a-867e-40b2-b2dc-0800add0c8d1.png)

**Comment by AndyButland** [comment]
Are you calling this within the context of an Umbraco back-office request?  As there is a check in there to get the current user (in order to check access to sensitive data).  So it could be you are running into that.

If you'd like to share your code I can give it a try.

**Comment by aguyfromdenmark** [comment]
> Are you calling this within the context of an Umbraco back-office request? As there is a check in there to get the current user (in order to check access to sensitive data). So it could be you are running into that.
> 
> If you'd like to share your code I can give it a try.

No, I am running it from an UmbracoApiController, as I need the data on the frontend of the website. So that is probably why if fails then.

**Comment by AndyButland** [comment]
A null check has been added now around the code checking for a back-office user, which will be in the next release.
