### ISSUE TITLE
Form security view not found on case sensitive filesystems

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco.Forms.Issues#725]
Form security view not found on case sensitive filesystems

Reproduction
------------
Run a Umbraco and Umbraco forms installation on a case sensitive file system and navigate to Users --> Forms Security --> "A User" 

Url: umbraco#/users/formsecurity/edit/3?mculture=nl-NL
### System Information 

<html>
<body>

Category | Data
-- | --
Server OS | Linux 5.4.0-1056-azure 58~18.04.1-Ubuntu SMP Wed Jul 28 23:14:18 UTC 2021
Server Framework | .NET 5.0.14
Default Language | nl-NL
Umbraco Version | 9.3.0
Current Culture | en-GB
Current UI Culture | en-GB
Current Webserver | Kestrel
Browser | Chrome 98.0.4758.82
Browser OS | Win32
Forms Version | 9.2.1

</body>
</html>

### Expected result

![image](https://user-images.githubusercontent.com/7831614/153575427-8b7367e7-41a4-4fbc-b3cf-01af881cf36c.png)

### Actual result

![image](https://user-images.githubusercontent.com/7831614/153574884-4b178f36-302a-4922-995b-03f9cfa95ea0.png)

**Comment by AndyButland** [comment]
Thanks, have replicated this and fixed up for the next release.

**Comment by erikjanwestendorp** [comment]
@AndyButland Thanks 😄
