### ISSUE TITLE
Localization: two typos in language file. 

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco.Forms.Issues#727]
There are two small typos in the English (en-us.xml) language file.

`<key alias="licenseValidOnDomain">This license is valid on the curent domain</key>`
should be:
`<key alias="licenseValidOnDomain">This license is valid on the current domain</key>`

and
`<key alias="licenseNotValidOnDomain">This license is not valid on the curent domain</key>`
should be:
`<key alias="licenseNotValidOnDomain">This license is not valid on the current domain</key>`

**Comment by AndyButland** [comment]
Thanks, this will be fixed in the next release.

**Comment by erikjanwestendorp** [comment]
@AndyButland That's blazing fast! Thanks 😄
