### ISSUE TITLE
Form Picker - Folders don't display

### ISSUE THREAD

**Issue by rickbracedigital** [umbraco/Umbraco.Forms.Issues#729]
We have a website that contains approximately 500 Umbraco Forms. We store these forms in the database and as such, when an editor expands the "Forms" node in Umbraco Forms it takes a long time to display all the forms resulting in a poor editor experience. 

To mitigate this, we've placed the forms in associated appropriately named folders i.e. there's 10-20 forms in each folder. This helps the editor experience somewhat because the forms in that folder display much quicker.

There's an issue whereby when an editor uses a form picker (in Umbraco) to pick an Umbraco Form, the folders do not display and so we're back to the poor editing experience because the forms take a long time to display.

Umbraco 8.17.1
Umbraco Forms 8.10.0

**Comment by AndyButland** [comment]
You might want to checkout the upcoming 8.11 forms release, currently available in release candidate, which introduces "start folders" for users.  Could be you could use this feature to restrict certain editors to the form folders they are interested in, and then would see just those in the back-office Forms section as well as in the Forms picker.

**Comment by rickbracedigital** [comment]
Hi Andy,

Thanks for coming back... so in pickers within the content section, these would be visible because the forms permission are set per user?

**Comment by AndyButland** [comment]
Yes, that's the idea - user's would only see and pick from forms within their "start folder" (kind of like how content and media start nodes are defined).
