### ISSUE TITLE
Basic ajax/API style support for headless approaches

### ISSUE THREAD

**Issue by karlmacklin** [umbraco/Umbraco.Forms.Issues#730]
It would be useful to have decent support for using Umbraco Forms in a headless scenario of using Umbraco CMS.

Both supported by code via services for example, and by documentation. This should at least cover the following:

- How to get form get definitions for the purpose of outputting the form structure to JSON via an endpoint request. This is what your frontend would query to know how to build and display the form.
- How to submit a form via an endpoint POST request. Preferably something that takes a typical .NET Core API json POST request payload and can convert it to proper form request data.

Currently without this support you are forced to jump through many hoops trying to imitate what Umbraco Forms does behind the curtains and even then you end up in questionable technical debt with the risk of future updates to Umbraco Forms invalidating your current approach.

**Comment by fredrikpihlgren** [comment]
I concur. Would save us great pains if implemented.

**Comment by Lendzin** [comment]
This sounds like a super upgrade, we've already had similar issues in our earlier project.

**Comment by Trixterx** [comment]
We would save a lot of time with this support in our current project

**Comment by Svante-J** [comment]
Yes please!

**Comment by AndersJesperPersson** [comment]
definitely, our team could benefit from this as well!

**Comment by 84miklar** [comment]
Nice feature!

**Comment by AndyButland** [comment]
We've added this feature which will be part of 10.2.

If anyone interested wants to take a look to see some details and perhaps feedback any thoughts before we make this available in the release candidate, there's a [page in this documentation PR](https://github.com/umbraco/UmbracoDocs/pull/4281/files#diff-b3be246596b43587455ab4e537deba69564cf1c5eda30078f84fe24d04969d32) - `Add-ons/UmbracoForms/Developer/AjaxForms/index.md` - that describes what we have implemented as well as [a gist](https://gist.github.com/AndyButland/9371175d6acf24a5307b053398f08448) demonstrating how it can be used with vanilla js.

**Comment by karlmacklin** [comment]
Much rejoicing!!
