### ISSUE TITLE
Clean/rebuild might throw a build error

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Forms.Issues#732]
I noticed that if you clean or rebuild (which implicitly does a clean first) an already clean solution, the following build error is thrown:

```
The expression "[System.IO.Directory]::GetDirectories({PathToProject}\App_Plugins\UmbracoForms, *, System.IO.SearchOption.AllDirectories)" cannot be evaluated. Could not find a part of the path '{PathToProject}\App_Plugins\UmbracoForms'.
```

This should be easily fixed by conditionally running the `ClearUmbracoFormsAssets` MSBuild task/making sure the `GetDirectories()` isn't called when part of the path doesn't exist.

This seems to be introduced in Forms 9.2.0, because I can't reproduce it in Forms 9.1.0.

### Steps to reproduce
Clean the solution twice or do a clean and then rebuild.

### Specifics
Umbraco 9.3.1
Umbraco Forms 9.2.2

**Comment by AndyButland** [comment]
I've fixed this for the next release.
