### ISSUE TITLE
AllowEditableFormSubmissions does not work

### ISSUE THREAD

**Issue by gfyans** [umbraco/Umbraco.Forms.Issues#733]
Setting `AllowEditableFormSubmissions` to `true` does not return any data when providing a valid recordId.

Reproduction
------------

### Bug summary

If the recordId is a valid GUID, the form should be pre-filled with the information that was submitted.

You should be able to edit this data and re-submit the form.

However, the form is always empty. No data is pre-loaded.

Filling in the form again results in a new record being created.

### Specifics

Umbraco 9.3.1 (latest version)

Umbraco Forms 9.2.2 (latest version)

Chrome (latest version)

### Steps to reproduce

1. Set `AllowEditableFormSubmissions` to `true` in appSettings.json
2. Submit an Umbraco Form
3. Go into the Forms section of the CMS, locate your record, and copy the unique ID (GUID)
4. Go back to your form page, and in the querystring add "?recordId={unique ID}" (without the curly brackets)
5. Press enter to load the page

### Expected result

A form pre-filled with the data from the `recordId`.

### Actual result

An empty/new form.

![2022-02-23_09h39_12](https://user-images.githubusercontent.com/1040786/155373883-fffcad32-c39d-4baf-a7cd-a00cd8b95553.png)
![2022-02-23_09h40_04](https://user-images.githubusercontent.com/1040786/155373902-6ae666ba-26d0-41b0-b2be-b6abe843414e.png)
![2022-02-23_09h42_06](https://user-images.githubusercontent.com/1040786/155373916-cb1f99d9-f2f6-4552-9a36-4043ad8437b0.png)

**Comment by nul800sebastiaan** [comment]
Thanks @gfyans - this seems to have been a documentation error, it works with:

```
    "Forms": {
      "Options": {
        "AllowEditableFormSubmisisons": true
      }
    },
```

As a future hint, most IDEs like VS, VS Code and Rider give you autocompletion in the appsettings file so you know if you're getting the config right (even when the docs are wrong 😅 ).

https://user-images.githubusercontent.com/304656/155480907-5f2bab69-9a54-43e8-b408-a49c3e1dded8.mp4

**Comment by AndyButland** [comment]
Thanks @nul800sebastiaan - I was just investigating this too, and looks like that is part of the issue.

The other though is a rather annoying typo I've spotted.  We actually have the property set as `AllowEditableFormSubmisisons` in the code, not `AllowEditableFormSubmissions`.  

So for this feature to work you will need:

```
    "Forms": {
      "Options": {
        "AllowEditableFormSubmisisons": true
      }
    }
```

Unfortunately, as this is strongly typed, it would strictly be a breaking change to amend in V9, so we'll have to fix this to a correct spelling in V10.

Meantime I'll create a PR for the docs to ensure we have the right section name, and a note about the "typo version" that will need to be used for V9.

**Comment by gfyans** [comment]
I didn't know about the appSettings autocomplete
