### ISSUE TITLE
Previous button doesn't work in custom themes

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#740]
I just got hit with an issue like #547, but I had the version with the fix already. So, I dug a bit more into it, and found that the previous button only works, if it has the classes `prev` and `cancel`.

From line 199 in /App_Plugins/umbracoforms/Assets/themes/default/umbracoforms.js:
`var previousButtonElements = document.getElementsByClassName("prev cancel");`

I don't think its correct to rely on specific classes, `prev` or `cancel` could be in use already for something else. Instead it should be a data attribute, like the `data-umb="submit-forms-form"` that is already present on the next buttons.

So the above could be
`var previousButtonElements = document.querySelectorAll("[data-umb='forms-previous']");`

**Comment by AndyButland** [comment]
I agree this makes sense, though probably need to keep the class name checks as a fall-back (in case people with custom themes have the classes, but don't introduce the new data attributes that'll be added in the next release.

Am planning to update the default theme's rendering of the previous button to:

```
  <input 
      class="btn prev cancel" 
      type="submit" 
      value="@Model.PreviousCaption" 
      name="__prev"
      data-umb="prev-forms-form"/>
```

And then amend the code you've identified to:

```
var previousButtonElements = document.querySelectorAll("[data-umb='prev-forms-form']");
if (previousButtonElements.length === 0) {
    previousButtonElements = document.getElementsByClassName("prev cancel");
}
```

**Comment by skttl** [comment]
Woohoo - swapped out the bundled aspnet-validation with the new version of aspnet-client-validation, and it just works!
