### ISSUE TITLE
FieldViewModel does not have property for AllowedUploadTypes

### ISSUE THREAD

**Issue by lesley-w** [umbraco/Umbraco.Forms.Issues#744]
Umbraco Forms v8.10.0

The FieldViewModel used by Views -> Partials -> Forms -> Fieldtypes does not have a property for AllowedUploadTypes.

We have a custom file upload which uses dropzone.js to handle drag'n'drop of files. 

For dropzone to validate the file type we need access to the AllowedUploadTypes field setting in order to set a data attribute on the dropzone div.

**Comment by AndyButland** [comment]
From 8.12.0 and 9.4.0, these fields will be available on the view model.  You will be able to access them via e.g.:

```
<div>Allow multiple file uploads?: @Model.AllowMultipleFileUploads</div>

<div>Allow all extensions?: @Model.AllowAllUploadExtensions</div>

<div>Allowed extensions:</div>
<ul>
@foreach (var allowedUploadExtension in Model.AllowedUploadExtensions)
{
    <li>@allowedUploadExtension</li>
}
</ul>
```
