### ISSUE TITLE
Getting script error on form-page, and also 405 when submitting form

### ISSUE THREAD

**Issue by rhagstrand** [umbraco/Umbraco.Forms.Issues#746]
Im using umbracoforms 9.3.0 and Umbraco. Cms 9.3.1.
I have successfully created a simple forms with a few text fields.

I have two problems:

**1. When loading the page where the form is located, chrome dev-console shows the following error:**

Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at setFocusToFirstElementOnValidationError (umbracoforms.js:326:18)
    at applyFormAccessibility (umbracoforms.js:306:9)
    at init (umbracoforms.js:89:13)
    at initCollection (umbracoforms.js:66:13)
    at listen (umbracoforms.js:43:13)
    at umbracoforms.js:20:9
    at umbracoforms.js:749:3 

**2. When submitting the page all I get is a blank page saying (I have only show a simple message in my configured submit-workflow)**

Status Code: 405; Method Not Allowed   

Any ideas on this? Im using Visual studio 2022 and .net 5.0. Site is hosted on iisexpress

**Comment by CoopCodes** [comment]
I fixed it by removing the `form` tag surrounding my rendering of the form.
```
<form>
    @await Component.InvokeAsync("RenderForm", new { formId = Model.Content.Form, theme = "tailwind-forms", includeScripts = false })
</form>
```
I changed it too
```
<div>
    @await Component.InvokeAsync("RenderForm", new { formId = Model.Content.Form, theme = "tailwind-forms", includeScripts = false })
</div>
```
This is because umbraco creates a form tag for you.

**Comment by AndyButland** [comment]
That would certainly be likely to cause this issue - thanks for posting your solution and relating it to this issue.  I'll close this off now since that may well have been the problem the original poster was running into.
