### ISSUE TITLE
Upgrade from 8.10.3 to 8.11.0 breaks entry dashboard - Form entry values are gone from the entry view❗⚠️

### ISSUE THREAD

**Issue by ja0b** [umbraco/Umbraco.Forms.Issues#748]
Hi there,

I recently upgraded umbraco forms from 8.10.3 to 8.11.0 and since then all the forms entries are showing as empty values (see images) you could see the property values from the dashboard but not in the entry view.

**Entries Dashboard:**
![Screenshot 2022-03-16 234935](https://user-images.githubusercontent.com/11311685/158744562-6f48c707-afc5-416c-a247-4563a0389dbd.png)

**Entry View:**
![Screenshot 2022-03-16 235000](https://user-images.githubusercontent.com/11311685/158744581-f4b15a1c-7c7a-463a-a596-71007d58039b.png)

To fix this, I had to downgrade umbraco forms back to 8.10.3, while doing it, I found an issue related with "The migration plan does not support migrating from state "_ba25a043-550e-4776-bd9e-a0960619e309_" ".

I had to manually edit the umbracoKeyValue table to change the value from _ba25a043-550e-4776-bd9e-a0960619e309_ (8.11.0) to _6822cdca-1dc4-4983-b189-9c45314e8747_ (8.10.3) it took me AGES to solve this, so I hope this help somebody with the same issue.

Thanks,
Ale

**Comment by AndyButland** [comment]
Sorry to hear you had trouble Ale.

It looks like you might have hit a caching issue with your upgrade, so if you want to try it again, make sure to rebuild, [bump the client dependency](https://adolfi.dev/blog/umbraco-bump-cdf/) value and do a hard refresh.  If you are still having trouble from the screenshot it looks like there should be something in the developer tools console and perhaps we can debug with that.

I'll close this as there's no action to take on the down-grading issue - what you found is normal for Umbraco itself, and any Umbraco packages that use migrations.

**Comment by ja0b** [comment]
Hi Andy,

I tried your suggestions and not luck, the console is clean

![image](https://user-images.githubusercontent.com/11311685/158865913-6fe1cad5-8f42-4fb3-9ff5-3c12db46da66.png)

I would need to keep umbraco from on 8.10.3 unfortunately.

Thanks,
Ale

**Comment by AndyButland** [comment]
Hmm.... it's a bit odd.  If it's feasible to zip up your solution and a database backup, I can take a look to see if I can see what's wrong.  You can email me at abl AT umbraco DOT dk.

**Comment by AndyButland** [comment]
Will close this one now - as haven't been able to replicate or have had any further reports.
