### ISSUE TITLE
Umbraco forms start folder at group level

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco.Forms.Issues#749]
Would it be possible to add support for forms start folder in the Group permissions tree in the users section? If doing so, all users belonging to that user group will have that folder as a start node. As it is right now you need to set the startnode on each individual user, which btw is great, but it might be a bit time consuming if there are many users, all of which are going to have the same start node if they belong to the same user group. We are building a solution which will host several different websites and each website will have its own user groups(s) with different users. It would have been awesome if you then just could select forms start node for the entire group instead of each individual user.

**Comment by AndyButland** [comment]
Yes, I think this would make sense.  Will see if we can make this an option on the user groups too in a subsequent release.

**Comment by AndyButland** [comment]
Due in 8.12.0/9.4.0.
