### ISSUE TITLE
Magic strings on Umbraco Form 9.2 is not working

### ISSUE THREAD

**Issue by Sowndar-Karthi** [umbraco/Umbraco.Forms.Issues#750]
I am using Umbraco 9 in our local environment. We are trying to get the Magic strings on a hidden field

We have set Magic strings([@Url]) on default value. However Magic strings on the default value are not working. We have checked with other Magic strings as well. It doesn't work

`@await Umbraco.RenderMacroAsync("renderUmbracoForm", new {FormGuid="2ed8rf86-5774-4403-55ss-ff9b13ee2c28", FormTheme="", ExcludeScripts="1"})`

https://our.umbraco.com/forum/using-umbraco-and-getting-started/108200-magic-strings-on-umbraco-92-is-not-working

**Comment by AndyButland** [comment]
Thanks for reporting.  I believe magic strings are working in general on default values, but you have found a specific issue with the page URL one.  In V8 (and .NET Framework) this was available as a `Url` property on the request object.  But this has changed in V9/.NET 5, so we need to make a special case here to ensure the syntax from V8, and that you are using, still works.

This will be available in the next release.
