### ISSUE TITLE
Expose "AllowedUploadTypes" data to file upload view

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#752]
Umbraco: 8.17.1
Umbraco Forms: 8.11.0

I would like to be able to restrict the file types a user can select for the file upload field via the "accept" parameter. Unfortunately, the "AllowedUploadTypes" data isn't exposed by the "FieldViewModel" as far as I can tell. Would it be possible to expose this data in the near future? This was touched on in another thread a while back, but it seems to have fallen off the radar since that task was closed (see [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/293#issuecomment-719498821)). In the end, I would like to be to do something like.
```
@{
    var acceptedTypes = Model.GetSettingValue<string>("AllowedUploadTypes");
}
<input type="file" accept="@Model.AllowedUploadTypes" />
```
which would output as
```
<input type="file" accept=".docx,.doc" />
```
Doesn't have to be implemented this way, but it avoids additional one off properties on the FieldViewModel if it's tied into the standard setting setup.

**Comment by AndyButland** [comment]
I think this duplicates [issue 744](https://github.com/umbraco/Umbraco.Forms.Issues/issues/744) - which we are working on for the next release.  So I'll close, but please let me know if I've missed something that differs in what you are requesting.

I've not implemented it quite the way you've suggested*, but think it'll add the support you need still.

&ast; _Whilst hooking into settings would probably be cleaner, as it avoids adding these properties to the view model for all field types, most of which don't support file upload of course; this isn't how it's been handled historically - in the `IFieldType` interface, and in the view model, see e.g. `AllowMultipleFileUploads`, which does exist on `FieldViewModel`.  Hence have aligned with this to be consistent._
