### ISSUE TITLE
Created and Updated date/time entries are not shown in local timezone 

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco.Forms.Issues#756]
When a new entry is created, the Created and Updated date of the entry is not shown in local date/time format.
In my case the date/time of an entry shows 2 hours in the future. The datetime in the UFRecords table is correct.

Reproduction
------------

- Set your Windows timezone to for example "Amsterdam/Berlin/Rome" (UTC+01:00) 
- Fill in a form to create an entry
- Check the entry datetime in the backoffice, it runs 2 hours (due Daylightsaving) in the future

### Expected result

The date/time of an entry should be shown in local timezone.

### Actual result

The date/time of an entry is showed in the future.

**Comment by AndyButland** [comment]
This looks to be OK for me, at least running the latest code that will be part of the next release (8.12.0).  We have made some amends to date formatting in the back-office, so possibly have resolved this.

![image](https://user-images.githubusercontent.com/1993459/161240817-44f14a7e-1841-4a05-bdae-537ec61bb358.png)

I'll close - but if you have chance to check once the RC for this release out and still find an issue, please feel free to re-open for further investigation.
