### ISSUE TITLE
Forms saved into wrong folder

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco.Forms.Issues#759]
When users has been assigned a start folder in the forms permissions section, the users can't access the forms they create because the forms are created in the top level folder, the wrong folder. 

### Specifics

- Umbraco 9.2.0
- Umbraco forms 9.3.0

### Steps to reproduce

1. Install a new Umbraco solution
2. Install Umbraco forms
3. In appsettings.json, make sure the following properties are set for Forms: "DefaultAccessToNewForms": "Grant", "ManageSecurityWithUserGroups": true, "GrantAccessToNewFormsForUserGroups": "admin,editor,formsadmin"
5. Create a new user group
6. Create a new user belonging to the user group in previous step
7. Go to the group under forms security section in Umbraco and grant the created user group access to all
8. Go to the forms section and create and name a new folder in the tree
9. Go to the "Start folders" in the "forms security" tree in the user section and select the created user. Set the forms start folder to the one created in previous step
10. Sign as the user created in step 6 and go to the forms section
11. Collapse "Forms" in the tree. The folder created in step 8 isn't displayed
12. When clicking on "..." belonging to "Forms" in the tree and create a new form, the form is created in the root of the forms tree where the user won't be able to access it

The user group's permissions:
![image](https://user-images.githubusercontent.com/19406378/162774057-f16db354-661b-4ea5-b3fc-cea0cfa8d0ab.png)

Start folder for the created user:
![image](https://user-images.githubusercontent.com/19406378/162771826-08a46294-9384-4c1d-b7e4-203100a07013.png)

Created user creating a new form:
![image](https://user-images.githubusercontent.com/19406378/162771958-57a00f75-c0b1-4569-a95f-f4f3687650f1.png)

Error message when saving new form:
![image](https://user-images.githubusercontent.com/19406378/162772241-a4c99e0d-9bf0-4e7c-a844-1fddcda865a6.png)

When checking the forms section as admin, the form has been created in the wrong place:
![image](https://user-images.githubusercontent.com/19406378/162772358-42731519-6a0b-46f5-a576-ef4bd38a2068.png)

    "Forms": {
      "FormDesign": {
        "DisableAutomaticAdditionOfDataConsentField": false,
        "DisableDefaultWorkflow": false,
        "MaxNumberOfColumnsInFormGroup": 12,
        "DefaultTheme": "default",
        "Defaults": {
          "ManualApproval": false,
          "DisableStylesheet": false,
          "MarkFieldsIndicator": "MarkMandatoryFields",
          "Indicator": "*",
          "RequiredErrorMessage": "Please provide a value for {0}",
          "InvalidErrorMessage": "Please provide a valid value for {0}",
          "ShowValidationSummary": false,
          "HideFieldValidationLabels": false,
          "MessageOnSubmit": "Thank you",
          "StoreRecordsLocally": false,
          "AutocompleteAttribute": ""
        }
      },
      "PackageOptions": {
        "IgnoreWorkFlowsOnEdit": "True",
        "ExecuteWorkflowAsync": "False",
        "AllowEditableFormSubmisisons": false
      },
      "Security": {
        "DisallowedFileUploadExtensions": "config,exe,dll,asp,aspx",
        "EnableAntiForgeryToken": true,
        "SavePlainTextPasswords": false,
        "DisableFileUploadAccessProtection": false,
        "DefaultAccessToNewForms": "Grant",
        "ManageSecurityWithUserGroups": true,
        "GrantAccessToNewFormsForUserGroups": "admin,editor,formsadmin"
      },
      "FieldTypes": {
        "DatePicker": {
          "DatePickerYearRange": 10
        },
        "Recaptcha2": {
          "PublicKey": "",
          "PrivateKey": ""
        },
        "Recaptcha3": {
          "SiteKey": "",
          "PrivateKey": ""
        }
      }
    }

# ## Expected result

Forms created in the forms-section are created beneath the user's start folder

### Actual result

Forms are created beneath the root folder in the forms section so users with start a start node can't access their created forms

**Comment by AndyButland** [comment]
Thanks for the detailed report here, made it straightforward to replicate and find the cause of the issue.  We'll get this fixed up for the next release (which should be out tomorrow as a release candidate).

**Comment by AndyButland** [comment]
Yes, it's part of the RC.  And in testing this out I actually ran into the other issue you posted too, and found something that had got missed in the merge up from V8, so hopefully you should find that issue resolved too with the latest release.

**Comment by bjornnorlen** [comment]
@AndyButland It seems to be working great. However, now the "start folder" option is missing from the tree. I haven't done any changes to the configuration. I could add a start folder through our development environment (haven't pushed the update to that environment) to test where forms are created. However, when running locally (running release candidate), the option for start folder isn't showing. Should I create a new bug for that issue?

![image](https://user-images.githubusercontent.com/19406378/162974612-b15766dc-cd4c-464a-8db5-898ef4a44173.png)

**Comment by AndyButland** [comment]
That's actually deliberate... unless you've spotted a flaw in my thinking here.  Given we now support start folders on the user groups (this is new in 8.12), I don't think we need the specific menu item for "Start folders" any more.

I only added this separate menu item in 8.11 because you could _only_ set start folders on users.  And hence there needed to be a menu that listed all the users, not just the sub-set that have individual user permissions set that you find under "User permissions".

Now if you want to manage start folders on a per-user basis, then you can create records for them under "User permissions".

And if you prefer to do this on a group basis, they can be created under "Group permissions".

**Comment by bjornnorlen** [comment]
Ahh, that's why I was a little confused because there aren't any fields for selecting start folder at the Group permissions level (image below) or underneath User permissions. Any idea what might be the issue?
 
![image](https://user-images.githubusercontent.com/19406378/163110335-210c7d4a-585e-4d27-a779-d990d8029e67.png)

**Comment by AndyButland** [comment]
Hmm, you should be seeing a "Start folders" section here, like this, assuming you are running the RC of 8.12 or 9.4:

![image](https://user-images.githubusercontent.com/1993459/163112978-bf8130d9-eaee-44e4-b0d7-59fbc975b6f4.png)

Client-side caching perhaps?  Maybe try a hard reload with the Chrome dev tools open with the option there to disable caching.

**Comment by bjornnorlen** [comment]
Ahaa, it was the cache that was the culprit. Now the field for selecting start folder is shown both in User group permissions and User permissions. Thanks for the help and great work :)
