### ISSUE TITLE
Invalid object name 'UFUserStartFolders'.

### ISSUE THREAD

**Issue by frcieservices** [umbraco/Umbraco.Forms.Issues#762]
Hello

We have installed Umbraco Forms 8.12 and are having the above error when saving forms.

please advise.

Thanks

**Comment by AndyButland** [comment]
Thanks for reporting.  Looks like I've missed something here when you have your forms setup configured to store forms on disk ("start folders" are only supported when folders are available, and those only with form definitions stored in the database).  So it's looking to read from a table that doesn't exist in your setup.

We'll have this fixed for the full release of 8.12, and if you were up for testing before that is out please let me know as I can make available a patch for the version you have installed.

**Comment by frcieservices** [comment]
Hello
In fact I did a direct install from Umbraco 8.17 and it automatically installed Forms 8.12.0.
I got the error when saving an existing form.
Please advise.

Many thanks

**Comment by AndyButland** [comment]
8.12 isn't out yet in full release, only [as a release candidate](https://www.nuget.org/packages/UmbracoForms).  And you've found a bug with that.

I suggest you either downgrade to 8.11.0 and wait for the full release of 8.12.0 - due 26th April -  or, as I say, if you want to carry on with the release candidate I can share a patch update that will fix the bug you have found, that you can use whilst waiting for that full release.

**Comment by frcieservices** [comment]
Ok thank you. I will downgrade to 8.11. 
Will let you know how it goes.
Thanks

**Comment by frcieservices** [comment]
Hello

I have downgraded but having an issue as below:

TypeError: Cannot read properties of undefined (reading 'manageForms')

can you please advise?

thanks
