### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'manageForms') 

### ISSUE THREAD

**Issue by frcieservices** [umbraco/Umbraco.Forms.Issues#763]
Hello

Got the error above when downgrading forms form 8.12 to 8.11.

Can you plese advise?

thanks

**Comment by AndyButland** [comment]
Hi - I've tried to replicate this, installing the 8.12 RC via NuGet, then removing it and installing 8.11, and I'm not coming across this error.

It might be useful for you to ensure you have removed all traces of Forms before reinstalling it (I find sometimes NuGet will leave the odd file behind).

Would suggest:

- If you have installed via NuGet, uninstall the package.
- Remove the folder `App_Plugins\umbracoforms`, if it still exists
- Remove the folder `Views\Partials\Forms`, if it still exists
- Install 8.11
- Rebuild the project
- [Bump the client dependency version](https://adolfi.dev/blog/umbraco-bump-cdf/) just to make sure there's no cached client-side assets.
- Run the project

If you still see the problem please can you provide me with a bit more information on where the error is surfaced, such as steps to replicate and/or screenshots?  Thanks.

**Comment by frcieservices** [comment]
Ok thanks. In fact the error is when I inspect the page in the back office.
When I click on Forms, I see all the forms but nothing (a bloack page) when I try to see the entries or modify the form.

**Comment by frcieservices** [comment]
Hello
Managed to resolve the issue by dumping the client dependency version.
Thanks a lot for your help.
