### ISSUE TITLE
Suggestion: Contextual Help for Workflows

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#765]
I was updating a workflow today via the back-office and thought I'd like to add the form's email value to the "Reply-to" field. I knew it was possible with magic strings, but couldn't remember the syntax (square brackets? curly brackets? '@' symbol???). A google search turned up the documentation - https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Magic-Strings/... but it would be really cool if this link (target="_blank", please!) could be present in the Workflow editor area. 

First, it's quicker than googling. Secondly, probably most Content Editors probably don't even have an inkling that this is available at all.

If you want an example of some awesome "contextual" help via the back-office dialogs, check out @leekelleher's [Contentment](https://github.com/leekelleher/umbraco-contentment) package
One example using a link, from https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#country-picker :
![image](https://user-images.githubusercontent.com/1252593/164514785-e241c503-e25c-41e0-bd64-7988f3307368.png)

Another example, with a collapsable help area:
![image](https://user-images.githubusercontent.com/1252593/164515189-cdca1fa9-1e4e-4d28-a166-c07ba7bf88e8.png)

**Comment by AndyButland** [comment]
Yes, I agree this would be a good idea.  I'd like ideally to create some nice UX for this, so you could "pick" your magic strings and place them in the field.  In the meantime though, something like this to call them out will be useful.  As you say, many people simply won't know this feature exists.

Here's what I'm looking at adding (with a similar message on the field settings):

![image](https://user-images.githubusercontent.com/1993459/164728431-fcc79008-8442-4f1a-980a-594b8fc14418.png)

**Comment by hfloyd** [comment]
Your UX ides sounds cool, but one step at a time, eh! Thanks for the reply.
