### ISSUE TITLE
After upgrade to 8.12, edit view won't initialize

### ISSUE THREAD

**Issue by christerj** [umbraco/Umbraco.Forms.Issues#766]
A brief description of the issue goes here.

After an upgrade from 8.8 to 8.12

When opening a form in edit view, only a blank page is displayed. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
When opening a form in edit view, only a blank page is displayed. 

### Steps to reproduce

Just try to edit a form

### Expected result

Should render UI 

### Actual result

Renders a blank page

### Workaround
Add ng-init="init()" to top div in edit.html

**Comment by AndyButland** [comment]
I have seen this on occasion when working with the product and switching branches, but it's resolved by ensuring I'm not running with any cached client-side views from previous requests.  Can I suggest/check you have done a hard refresh and [bumped the client dependency version](https://adolfi.dev/blog/umbraco-bump-cdf/), just to ensure you don't have any cache related issues please?

**Comment by christerj** [comment]
I did test this initially but will give it another try

**Comment by christerj** [comment]
I had to open developer tools in the browser, then the cache updates. This could potentially be a problem for normal users of course, I mean if it's necessary to do it this way

**Comment by ja0b** [comment]
I'm also having this scenario when upgrading from 8.8.0 to 8.12.2, I tried you suggestion @AndyButland but is not working for me, unfortunately I had to roll back the upgrade until there is a working fix for this.

![image](https://user-images.githubusercontent.com/11311685/172363411-085dfddc-20f9-4122-b890-18ca9ebb5a3b.png)

**Comment by AndyButland** [comment]
Going to close this one now since I've not heard of further issues, and what I've seen is fixed by ensuring the browser cache is cleared and/or making sure to bump the client dependency (Umbraco 8)/Smidge (Umbraco 9+) version number.
