### ISSUE TITLE
.umb-forms__field-condition has unnecessary "white-space: nowrap;" rule

### ISSUE THREAD

**Issue by graealex** [umbraco/Umbraco.Forms.Issues#767]
Complex field conditions will spread the form editing page horizontally to ludicrous width because .umb-forms__field-condition specifies white-space: nowrap; - so the text can never wrap.

Reproduction
------------

Make a complex field condition in Umbraco forms that would be wider than the screen size.

### Expected result

Text should wrap.

Additional notes
------------

Another thing:
text-overflow: ellipsis;
overflow: hidden;
only works with absolute width. Especially "ellipsis" is very picky about that.

**Comment by AndyButland** [comment]
Resolved with the linked PR and due in the next release.
