### ISSUE TITLE
7.0.6: Using Dropdown datatype as Prevalue source shows 0 or 1 for the Enable multiple choice checkbox setting

### ISSUE THREAD

**Issue by cpevans** [umbraco/Umbraco.Forms.Issues#77]
When you create a Prevalue source from a Dropdown datatype (Umbraco.DropDown.Flexible), the Enable Multiple Choice checkbox value appears as the final item in the list of options, with 0 or 1 as the value (depending on whether the checkbox is enabled or not). 

This shouldn't be included as a selectable option for the prevalues. 

Inspecting the database table cmsDataTypePreValues there is a record for the datatype with an alias of "multiple", rather than an index like the other values. This would denote the chosen state of the Enable Multiple Choice checkbox on the data type.

Presumably rows with an alias of "multiple" aren't being filtered out when the Umbraco Form renders the select box, so it's adding the additional prevalue at the end with 0 or 1 as the value.

Reproduction
------------

Create a new Dropdown datatype that you'd like to use as a prevalue source for your forms. Add some values to it, e.g. Option 1, Option 2, Option 3

Go to your Forms admin, and create a new Prevalue source. Choose "Umbraco data type Prevalues" as the Type, and your new datatype you created in step 1 as the Datatype to use.

Create a new form (or edit an existing one), add a Dropdown question and choose your Prevalue source.

View your form on a page to see the items available in the dropdown. Notice that there is a final, extra choice which will have the following structure for its option tag:

`<option value="0">0</option>`

or, if the Enable Multiple Choice setting is true:

`<option value="1">1</option>`

This is happening in Umbraco Forms version 7.0.6 which is the latest version at the time of submitting this bug report. I have not tested it in earlier versions.

**Comment by bergmania** [comment]
Hi @cpevans.

I'm not sure whether this behavior is intended or a bug, but as a workaround you can use the data type `Umbraco.RadioButtonList` instead of `Umbraco.DropDown.Flexible`

**Comment by cpevans** [comment]
Good to know it won't be an issue in V8  :)  and I can confirm the workaround of using a Radio Button List fixes the issue in v7.

Just a shame as it's intuitive to use a Dropdown for something like this -- so many people might get confused about the 1 or 0 turning up at the bottom. 

Thanks for looking into it, and for the suggested workaround!
