### ISSUE TITLE
Update built in email workflows to include attachments from fields that extend FileUpload field type

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#770]
I created a custom field type to add file size validation to the file upload field. Unfortunately this means that these uploaded files can't be included as attachments because it only includes data from the **FileUpload** field type. The relevant line of code taken from SendRazorEmail can be seen below.

```
IEnumerable<KeyValuePair<Guid, RecordField>> enumerable = record.RecordFields.Where((KeyValuePair<Guid, RecordField> x) => x.Value.Field.FieldTypeId == Guid.Parse("84A17CF8-B711-46a6-9840-0E4A072AD000"));
```

Ideally, it would also allow any fields that extend **FileUpload**, but it would also work if we could pass in attachment fields via an alias or id if that's not possible.

Fortunately, I can work around this for now by including a links to the files in the email body. For your reference, there's an old forum post [here](https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/feedback-bugs/91582-upload-files-not-being-attached-when-choosing-the-send-email-with-template-razor-workflow#comment-289240) that discusses this problem. I don't think it made its way into the issue tracker though.

**Comment by jaandrews** [comment]
I figured out a hack to work around this. Basically involves replacing the fieldTypeId of the custom upload fields with the field type id of the built in upload field in a custom workflow. Not ideal, since I can't use the built in workflows, but it works for now. Further details can be seen [here](https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-on-perplex-steroids/feedback-bugs/91582-upload-files-not-being-attached-when-choosing-the-send-email-with-template-razor-workflow#338346).

**Comment by AndyButland** [comment]
That should do it, but as you say, won't be an ideal solution.  I've made a change now so we look up "upload" field types for attachment handling based on that property that signifies they support uploads, rather than the specific ID of the built-in type.  That'll be in the next release.

**Comment by jaandrews** [comment]
Fantastic. Thanks for resolving that.
