### ISSUE TITLE
Html.RenderUmbracoFormDependencies() should use asp-append-version

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#773]
To make form dependencies cacheable to the maximum, we need to version their urls. Can we have the outputted script tag include `asp-append-version="true"` to make .net append a version querystring?

---
_This item has been added to our backlog AB#38203_

**Comment by ronaldbarendse** [comment]
@AndyButland The `asp-append-version` uses the `WebRootFileProvider` to get access to the file contents, so it will only work in 9.3+ (see PR https://github.com/umbraco/Umbraco-CMS/pull/11783). Prior to this, the `App_Plugins` files were served by a separate `UseStaticFiles()`, thus not exposing the files via the `IFileProvider` abstraction... I should be safe to include this though, as it will be ignored if it can't find the file.

**Comment by bjarnef** [comment]
@AndyButland does the `Html.RenderUmbracoFormDependencies()` has any overloads?
The docs mention it here https://docs.umbraco.com/umbraco-forms/v/12.forms.latest/developer/prepping-frontend but with Forms v12.2.0 I only have this:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/2919859/68c3591c-8512-4c00-a5b7-df15ced8c153)

**Comment by AndyButland** [comment]
From 12.2 you should find the following available:

```
IHtmlContent RenderUmbracoFormDependencies(this IHtmlHelper htmlHelper, IUrlHelper urlHelper, object? htmlAttributes = null)
```

**Comment by bjarnef** [comment]
Yes, I just noticed that.
Maybe v12 docs should mention that since it wasn't available in v12.1.2, but in v12.2.0 it is :)
https://docs.umbraco.com/umbraco-forms/v/12.forms.latest/developer/prepping-frontend

**Comment by skttl** [comment]
`asp-append-version` is using IFileVersionProvider to add the file version to the url - maybe you can copy that logic into the `Html.RenderFormsScripts` helper. That would help me a lot :)

Or the simpler version, just add v=`current_umbraco_forms_version`

**Comment by AndyButland** [comment]
We've gone with your "simpler" version @skttl - so from 13.1 you should find these versioned URLs being output.
