### ISSUE TITLE
Conditional Workflows

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#775]
It would be great to have conditional workflows, there have been many times where depending on the answer to the questions in the form, I would like the email to either be sent elsewhere, or pushed to an api (hub spot or mailchimp for example)

**Comment by AndyButland** [comment]
Agreed this would be nice, and we're starting to think about it.  We already have this in the tracker [here](https://github.com/umbraco/Umbraco.Forms.Issues/issues/370) though, so I'll close this one.

**Comment by AaronSadlerUK** [comment]
@AndyButland Tim's one didnt exactly cover what i think it should do, so I've commented over there.

Any ideas when this will be worked on given it's been 2 years already 😅
