### ISSUE TITLE
Datepicker values shown in backoffice are broken

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Forms.Issues#777]
When using a Datepicker in your form, the values of the datepicker is very broken when shown in backoffice. 

Reproduction
------------
### Bug summary

The shown value of the datepicker as shown on the entries list is in a different format, depending on the date, and on some dates, it's even the wrong date shown. Some dates are shown as null when looking at the single entry. 
Here are two examples. 
The first image shows how the date is presented in the datepicker. 
The second image shows the values in the markup. 
The third image shows how the date is shown in the entries list in backoffice. 
The fourth image shows how the date is shown when looking at a single entry. 

First date: The 24th of May 2022.
![datepicker](https://user-images.githubusercontent.com/6904597/169820887-1abc67ad-d2aa-4a77-b113-ddba756d1468.png)
![datepickervalues](https://user-images.githubusercontent.com/6904597/169820915-01263ee8-46ee-4457-8e04-391352eb4892.png)
![datepickerinbo](https://user-images.githubusercontent.com/6904597/169820931-6e16b7e6-b0e4-44ec-8b45-7dfa7f20504f.png)
![datepickerinboentry](https://user-images.githubusercontent.com/6904597/169820956-0620ebdb-61b4-448a-9ce4-f35c485eaa5b.png)

Second date: The 10th of May 2022 (It thinks that it's in October)
![datepicker2](https://user-images.githubusercontent.com/6904597/169820992-ce60babf-9c25-4c16-b25d-2e1afa2a40db.png)
![datepickervalues2](https://user-images.githubusercontent.com/6904597/169821004-d9066050-0651-4bf2-b644-48f3b3817f35.png)
![datepickerinbo2](https://user-images.githubusercontent.com/6904597/169821030-7547708b-a0ed-418d-afa9-1ea6e2247b8e.png)
![datepickerinboentry2](https://user-images.githubusercontent.com/6904597/169821054-47e3b4cd-8858-4194-b187-d458a7334fa2.png)

### Specifics

I am running Umbraco 9.5 and Forms 9.4.1. This is a cloud site, but the test is done locally, running in IIS. 

### Steps to reproduce

1. Add a datepicker to a form
2. Submit the form
3. Look at the value in entry in backoffice

### Expected result

The correct date is always shown.

### Actual result

Incorrect or no date is shown.

**Comment by AndyButland** [comment]
A resolution to this will be available in the next minor releases.
