### ISSUE TITLE
Request error when "ManageSecurityWithUserGroups" is set to true

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco.Forms.Issues#778]
### Bug summary

I've been testing the feature that will allow you to set group-specific permissions in the Forms Security section.
However, when enabling the feature, "ManageSecurityWithUserGroups", it throws request errors (404s) in the backoffice whenever I try opening Group permissions for any of the Groups that aren't "Administrators".

### Specifics

Versions:
- Umbraco 9.5.0
- Umbraco Forms: 9.4.1
- Hosting: Umbraco Cloud (let me know if you need access to the project(s))
- Browser: Chrome (Version 101.0.4951.67 (Official Build) (64-bit))

Error:
```
Request error: The URL returned a 404 (not found): /umbraco/backoffice/umbracoapi/users/GetById
```

![image](https://user-images.githubusercontent.com/24529086/169825462-c0a2b7c0-c56a-4a0e-b720-18fcba53a30f.png)

I've been unable to find anything in the logs.

### Steps to reproduce

1. Set "ManageSecurityWithUserGroups" to `true`
2. Navigate to the Users > Forms Security section in the Umbraco Backoffice
3. Unfold "Group Permissions"
4. Select any group that isn't "Administrators"

### Expected result

That I would get to set the permissions on the selected Group.
And I am, it's just ALSO giving me the error.

### Actual result

I'm able to configure the permissions, but it also throws me an error indicating that something is wrong.
![image](https://user-images.githubusercontent.com/24529086/169825462-c0a2b7c0-c56a-4a0e-b720-18fcba53a30f.png)

**Comment by AndyButland** [comment]
Hi @sofietoft - yes please, could you invite me to the project so I can have a look?

**Comment by sofietoft** [comment]
> Hi @sofietoft - yes please, could you invite me to the project so I can have a look?

I've added you - let me know if I used the correct email or not 🙈

**Comment by AndyButland** [comment]
No problem.  As I said, I think it was just that when you switch the configuration, some paths to API calls change - you are editing a group rather than a user for example.  So if you still had the browser window open, it might still be trying to request a now invalid path.
