### ISSUE TITLE
Cannot delete form records programmatically in background job

### ISSUE THREAD

**Issue by MMartinezMusterd** [umbraco/Umbraco.Forms.Issues#779]
When trying to delete form records in a background job (Hangfire in my case), IRecordService.Delete() throws a null reference exception. 

Reproduction
------------

### Bug summary

See stacktrace below. RecordService.GetUsernameOfCurrentUser() doesn't mind if backOfficeSecurity.CurrentUser is null, but if backOfficeSecurity itself is null, presumably because there is no HttpContext available for the backoffice security accessor, an exception is thrown and the record is not deleted.

### Specifics

**Forms version** 
Tested in 9.4.1 and 9.3

**Stacktrace**
`
at Umbraco.Forms.Core.Services.RecordService.GetUsernameOfCurrentUser()
at Umbraco.Forms.Core.Services.RecordService.Delete(Record record, Form form)` 

### Steps to reproduce
Call IRecordService.Delete() from a Hangfire task

### Possible fix
Perform the null check on backOfficeSecurity as well:
![image](https://user-images.githubusercontent.com/6907009/171015576-4ca506c6-e560-4c28-8c4d-3b99d7daf732.png)

**Comment by AndyButland** [comment]
Thanks, your diagnosis looks correct to me.  I've fixed up this null check for V10 and for a patch of V9.
