### ISSUE TITLE
Unable to select and save images when using the 'File' setting type on a custom field type

### ISSUE THREAD

**Issue by MrJackWilson** [umbraco/Umbraco.Forms.Issues#78]
When using the 'File' setting type on a custom field type, selecting an image and trying to save the form throws an error.

### Bug summary

The problem is that when you pick an image, the setting's value is set to an object containing `src` and `crops`, whereas selecting a file sets it to a string (the file url). When trying to save the form, it doesn't like that the setting's value is an object. I've tried setting the c# type of the setting to `object`, `string` and a custom class which matched the image object's fields (`src` and `crops`).

### Specifics

Umbraco Version: 7.13.2
Forms Version: 7.0.6
Browser: Chrome 72.0.3626.96
Error: Unexpected character encountered while parsing value: {. Path 'pages[0].fieldSets[0].containers[0].fields[0].settings.Image', line 1, position 2564

The error comes from line 258 in umbraco.forms.js. I am able to add a temporary fix by using the following code:

`$scope.setting.value = 'src' in umbracoFileProp.value ? umbracoFileProp.value.src : umbracoFileProp.value;`

### Steps to reproduce

1. Create a blank form
2. Create a custom field type
3. Add the following setting:
`[Setting("Image", view = "File")]`
`public string Image { get; set; }`
4. Add the custom field type to the form.
5. Select an image as the 'Image' setting.
6. Try saving the form

### Expected result

I expected the setting to be set to the url of the image.

### Actual result

The actual result was the following error: 
Unexpected character encountered while parsing value: {. Path 'pages[0].fieldSets[0].containers[0].fields[0].settings.Image', line 1, position 2564

**Comment by bergmania** [comment]
PR: 
- V7: https://github.com/umbraco/Forms/pull/250
- V8: https://github.com/umbraco/Forms/pull/249

**Comment by bergmania** [comment]
Connects: https://github.com/umbraco/Umbraco.Forms.Issues/issues/6

**Comment by warrenbuckley** [comment]
V7 is all merged in but V8 contains too much in it's PR @bergmania about Content Picker Setting Type
