### ISSUE TITLE
Umbraco Forms Custom WorkFlowType Settings override access to Form Id

### ISSUE THREAD

**Issue by mognog1** [umbraco/Umbraco.Forms.Issues#781]
I'd like to have access to the current Form Id in the Settings override of a Custom WorkFlow. You can clearly see the form id in the URL  of the Form so it must be accessible somehow. However in Umbraco 9.4.3 this feature does not appear to exist.

Below is a code example taken from the Umbraco documentation then modified to override the settings to show how/why this would be used.

![image](https://user-images.githubusercontent.com/106950778/172128670-b44501a2-321e-4cf0-8e83-4e381a2319c1.png)

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using Umbraco.Forms.Core;
using Umbraco.Forms.Core.Attributes;
using Umbraco.Forms.Core.Enums;
using Umbraco.Forms.Core.Persistence.Dtos;
using Umbraco.Forms.Core.Services;

namespace MyFormsExtensions
{
    public class TestWorkflow : WorkflowType
    {
        [Setting("Account Number field", Description = "DropDownList", View = "DropDownList")]
        public string AccountNumberField { get; set; }

        private readonly ILogger<TestWorkflow> _logger;
        private IFormService _formService;

        public TestWorkflow(ILogger<TestWorkflow> logger, IFormService formService)
        {            
            _formService = formService;
            _logger = logger;

            this.Id = new Guid("ccbeb0d5-adaa-4729-8b4c-4bb439dc0202");
            this.Name = "TestWorkflow";
            this.Description = "This workflow is just for testing";
            this.Icon = "icon-chat-active";
            this.Group = "Services";
        }

        public override WorkflowExecutionStatus Execute(WorkflowExecutionContext context)
        {
            // first we log it
            _logger.LogDebug("the IP " + context.Record.IP + " has submitted a record");

            // we can then iterate through the fields
            foreach (RecordField rf in context.Record.RecordFields.Values)
            {
                // and we can then do something with the collection of values on each field
                List<object> vals = rf.Values;

                // or get it as a string
                rf.ValuesAsString();
            }

            //Change the state
            context.Record.State = FormState.Approved;

            _logger.LogDebug("The record with unique id {RecordId} that was submitted via the Form {FormName} with id {FormId} has been changed to {RecordState} state",
                context.Record.UniqueId, context.Form.Name, context.Form.Id, "approved");

            return WorkflowExecutionStatus.Completed;
        }

        public override List<Exception> ValidateSettings()
        {
            return new List<Exception>();
        }

        public override Dictionary<string, Setting> Settings()
        {
            var settings = base.Settings();
            var formFields = _formService.Get(Workflow.Form);  // Workflow.Form looks like it should return the forms GUID but it returns nothing. Where can we get the form ID from? I can see it on the Forms URL. We need a new feature to add this it seems.
                                                               //  var formFields = _formService.Get("My Test Form"); // This works fine with a hard coded form name but isn't useful as you would need to code a new workflow every time you created a new form.

            var accountNumberPreValues = string.Join(",", formFields.AllFields.Select(list => $"{{{list.Alias}}}").ToArray());  // get a list of alias to display in a drop down so the user can choose which one is the account value (in this example)
            
            settings["AccountNumberField"].PreValues = accountNumberPreValues;

            return settings;
        }
    }
}

**Comment by AndyButland** [comment]
I think I've fed this back through the support team too, but will add here for reference.

I don't think we have an easy way to expose this, and also not 100% sure it's the right approach anyway.

Firstly, when you associate a workflow with a form, it may be a new one that's not saved yet.  So in that case there's no form record in the database to retrieve (and no Form Id yet created).

If it's a form being edited, then an ID does exist, but I can't think of a way to retrieve it from this method.  It's in the URL, but only after the # so not available server-side.

I'd suggest though to have a look at an example we have [here](https://github.com/umbraco/Umbraco.Forms.Integrations/tree/main/src/Umbraco.Forms.Integrations.Crm.Hubspot): 

This is our HubSpot integration for forms where the workflow needs to know the fields of the form, and present them in a drop-down list to the editor.  The approach we've taken there is to create a custom field type interface, and retrieve the fields for the form being created or update client-side.  It looks to me that you could use a similar approach to achieve what you are looking for here.

**Comment by mognog1** [comment]
HubSpot seems like a lot of extra work when all I need is a Form ID and I'm done. 
I'll look into it anyway.
My alternative is to have a text field instead of the dropdown list and get the Umbraco back office forms user to enter the field alias name in manually. 

Thanks

**Comment by AndyButland** [comment]
Will close this issue now, as I haven't found a way to cleanly provide explicitly what is requested, but there is a way to achieve the same ends using the method linked from the comment above.
