### ISSUE TITLE
Make eventlistener for conditions configurable

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#784]
When having conditions based on simple text inputs, the condition is not taking effect until the user clicks away from the field.

This is because the conditions listen for the `change` event, which only happens when the user clicks away from input fields.

I guess changing the event being listened for, from `change` to `input` is too big of a change, and `change` works fine for things like select boxes or radio buttons. They do fire off the `input` event too though.

Would it be possible to make it configurable if the conditions should run on `input` instead of `change`?

Examle of `change` vs `input`: https://www.youtube.com/watch?v=g8Z4i8_vAHU

**Comment by AndyButland** [comment]
Sounds a good idea to me, and to have it as a configuration option so existing behaviour is maintained for upgrades.  I've prepared this for the next release.

**Comment by AndyButland** [comment]
This will be available in the next minor release.
