### ISSUE TITLE
Conditions for Workflow Steps

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.Forms.Issues#791]
I just talked to a client that asked:

"I have a radio list in the form and would like to send an email to different recipients based on the choice in the list".

So let's say that we have a Form with a radio-field like this:

Choose Department:
* [ ] Sales
* [ ] Support
* [ ] Marketing

Based on what the visitor chooses we want to send the email to a different recipient. I know I can build my own Workflow Type and use conditions for this and there is also probably some packages out there that solve this for a given type of Workflow (like email).

But I was thinking that this would be a lot better served as a core-feature in Umbraco Forms. That each Workflow-step could have optional "Conditions" (just like we can with conditional fields) and only be triggered if the conditions are fulfilled.

I guess this has been on the table before but wanted to throw out the idea.

All the best!

**Comment by AndyButland** [comment]
Will close this as it duplicates #370, but I agree it would be a good feature to have in Forms.  We're working on it, so it should be available in the next minor release.

**Comment by enkelmedia** [comment]
Ahh... I was sure I had seen that one before but could not find it... sorry for the duplicate. 

Thanks for letting me know!
