### ISSUE TITLE
Unable to save form containing Data Consent after upgrade from V9

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#794]
I have forms in my site which I have upgraded from V9 to V10.
Prior to the upgrade I was able to edit and save forms successfully.

Since the V10 upgrade any forms containing Data Consent fields fail to save, with the following error returned:

```
)]}',
{"Message":"The request is invalid.","ModelState":{"AllFields[6].PreValues":["The PreValues field is required."],"Pages[0].FieldSets[0].Containers[0].Fields[6].PreValues":["The PreValues field is required."]}}
```

If I remove all the Data Consent fields and then re-add them to the form, I am able to save the form however any data associated with the previous fields is lost (not ideal with data consent fields!)

**Comment by AndyButland** [comment]
Thanks @AaronSadlerUK - I spotted this one myself yesterday (there's an issue here with the nullability constraints added in V10, where for field types that don't have prevalues we expect to an empty array and not null.  I've ensured this is the case for the next patch release.

**Comment by AndyButland** [comment]
10.0.1, including a fix for this issue, is released now to NuGet .

**Comment by AaronSadlerUK** [comment]
@AndyButland sorry to re-open this, but I am still getting the same issue on 10.0.1

**Comment by AndyButland** [comment]
Hmm... would you mind just checking please that you don't have something cached (as the fix was in the JavaScript)?

**Comment by AaronSadlerUK** [comment]
Which file was changed so I can compare :)

**Comment by AndyButland** [comment]
`umbraco.forms.js` - you should find you have the following code:

```
        //ensure we have non-null prevalues
        var formFields = formService.getAllFields($scope.form);
        for (var i = 0; i < formFields.length; i++) {
          if (formFields[i].prevalues == null)
          {
            formFields[i].prevalues = [];
          }
        }
```

**Comment by AaronSadlerUK** [comment]
Yep, it's there

![image](https://user-images.githubusercontent.com/9937803/176182133-59de181d-6075-42d4-acee-8b7d0f691c27.png)

**Comment by AaronSadlerUK** [comment]
Ha!

I needed to purge the CDN 😅

I wonder why the update didn't bump smidge 🤔
