### ISSUE TITLE
Add support to distribute custom forms themes as part of a Razor class library

### ISSUE THREAD

**Issue by jhenkes** [umbraco/Umbraco.Forms.Issues#795]
Hello,

I noticed that Umbraco Forms v10 distributes the .cshtml files (including themes) as part of a Razor class library.
Would it be possible / Is it planned to also support the same mechanism for custom themes as part of a RCL?

I currently have a custom forms theme for bootstrap 5. Instead of having to add the physical files to every project I want to use this theme in, I'd like to distribute it as RCL.

Best regards,
Jeremy

---
_This item has been added to our backlog AB#44707_

**Comment by FrankSchutte** [comment]
We have a similar setup where we want to have a .cshtml as part of a Razor class library. For us the .cshtml file is a email template. We configured the RCL for Razor pages. Sadly the email template does not show up in the template picker when using the SendRazorEmail workflow.

**Comment by gmanrodt** [comment]
+1 

We are using Umbraco Cloud, where it is "best practice" to not mess with the default "UmbracoProject" but instead built customizations, components, extensions, etc. in separate projects (I would anyway, even if it wasn't recommended, FYI), then have the "UmbracoProject" reference the other projects as dependencies. It seems pretty silly that Umbraco Form's themes don't work correctly when included in an RCL. One fun thing to note, however: if you build your custom theme in an RCL project, but put it in a folder called "default" its works beautifully. 

It also seems silly to me that the Umbraco.Forms.Web.Api.ManagementApi.Theme.GetCollectionController, which uses DI for the ioHelper, loggerFactory, hostingEnvironment, and hostEnvironment doesn't also use DI for "PhysicalFileSystem", thereby giving developers the options to swap out where the theme files come from. I am sure there is a good reason for this, but it escapes me.

**Comment by AndyButland** [comment]
Thanks for the nudge on this one.  I've been looking into this today and can see we have a way to include themes and email templates from RCLs, so we'll include this in the upcoming releases.
