### ISSUE TITLE
Missing asset aspnet-validation.min.js.map throws 404 in browser console

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco.Forms.Issues#796]
A brief description of the issue goes here.

The JS file _aspnet-validation.min.js_ is missing its map file in all environments. The path being referenced is:

`/App_Plugins/UmbracoForms/Assets/aspnet-client-validation/dist/aspnet-validation.min.js.map`

### Specifics

Umbraco Forms 10.0.0 through 10.0.2 exhibit this behavior.

### Steps to reproduce

Build and launch a website with Umbraco Forms installed, then load the site in the browser and view the console.

### Expected result

In development the map file should be present. In production the JS file being used should not include the map file comment reference, so the map file is not requested.

### Actual result

Browser console issues a 404 for the requested map file.

**Comment by AndyButland** [comment]
Thanks for reporting.  It looks like this issue has been around for a while so I've resolved for the next releases of Forms 8, 9 and 10.
