### ISSUE TITLE
Recaptcha V3 'No reCAPTCHA clients exist.' error

### ISSUE THREAD

**Issue by TimmiX88** [umbraco/Umbraco.Forms.Issues#799]
We are facing an issue with Umbraco Forms in combination with Recaptcha V3.
Umbraco: 8.18.4
Umbraco Forms: 8.12.2

After a little time on a page with a form, a javascript error occurs. 
In the console.log it says: _Uncaught Error: No reCAPTCHA clients exist._

To reproduce:  [go to this page](https://www.agruniekrijnvallei.nl/actueel/bijeenkomsten/zomeravond-kennisbijeenkomst-rundveehouderij-lienden/) open the console and wait a little while.

The error seems to be initiated in **/App_Plugins/UmbracoForms/Assets/recaptcha.v3.init.js**

Initially on DOMContentLoaded it seems to work, but after the timerFunction is called again (which happens in row 8) both hiddenField as siteKey are undefined.

The RecaptchaV3SiteKey and RecaptchaV3PrivateKey are configured in the UmbracoForms.config

The bug occurs with both our custom theme as the default theme, and happens in multiple of our Umbraco websites and we tested in multiple browsers.

Do more people stumble across this issue?

**Comment by WizKi9d** [comment]
We have the same issue with versions:

Umbraco: 9.3.1
Umbraco Forms: 9.4.1

Same error, spent hours attempting to find a solution to something we believed was caused by our changes. After looking at a fresh Umbraco 9 website the same error was thrown.

**Comment by AndyButland** [comment]
Thanks for reporting, yes I can see an issue here with the script that the values aren't passed correctly in the timer call, so as you've seen it'll work on first load but fail if the form is kept open a while.  We'll get this fixed for the next release.

To apply manually the code on line 8 of the script you've referenced should be:

```
setTimeout(timerFunction, 60 * 1000, hiddenField, siteKey);
```

**Comment by WizKi9d** [comment]
@AndyButland Do you have a release scheduled that will include the fix?

**Comment by AndyButland** [comment]
It'll be included in the releases indicated with labels on this issue.  Am looking to get release candidates for these out next Tuesday, so you should be able to upgrade to that when it's out.  The full release will come about three weeks later.
