### ISSUE TITLE
Approval workflow is invisible in the UI when you turn off moderation

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#8]
First logged as http://issues.umbraco.org/issue/CON-1486 using Umbraco 7.6.12 and Forms 6.0.5:

### What did you do?

Enable moderation on a form, and add a workflow on approval. Disable moderation. Complete and submit the form.

### What did you expect to happen?

The workflow would not run, and would appear as disabled/greyed out in the form design UI. 

Or perhaps it should run as approval still happens automatically, but if so then it should be visible and configurable in the form design UI next to a prompt saying "Approval (automatic)".

### What actually happened?

The workflow runs, but is invisible in the form design UI.

**Comment by bergmania** [comment]
PR:
- V7: https://github.com/umbraco/Forms/pull/252
- V8: https://github.com/umbraco/Forms/pull/251

**Comment by warrenbuckley** [comment]
V8 is merged in @bergmania but looks like V7 contains too much as has change with RecordStorage as well in there (not sure if that was meant to come across or not with this PR ?)
