### ISSUE TITLE
Strict mode causes reference error in theme conditions when using CDF

### ISSUE THREAD

**Issue by gavinfaux** [umbraco/Umbraco.Forms.Issues#80]
Using CDF to load scripts in release mode the default themed umbraco forms java script can throw an error if the script block includes a `no script` directive; this prevents conditional fields from functioning.

Reproduction
------------

* Create a themed form that uses conditional fields, e.g. a check box to show additional field if checked.
* Amend form settings to render scripts using CDF
* Include a `no script` statement in a dependent script registered with page via CDF
* Run application in release mode (`debug=false` in web.config).
* Browse to form and check browser console for exceptions

![console_trace](https://user-images.githubusercontent.com/294737/52831178-9783c380-30cb-11e9-9b5b-b75c9636a081.png)

![console_sources](https://user-images.githubusercontent.com/294737/52831190-a1a5c200-30cb-11e9-88f9-9a49e67f3015.png)

### Specifics

    * Umbraco 7.12.4 and Umbraco Forms 7.0.6
    * Chrome 72
    * DependencyHandler.axd & \App_Plugins\UmbracoForms\Assets\themes\default\umbracoforms.js

### Workaround

```udiff

 App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js b/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js
index 03636958..3602f86b 100644
--- a/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js
+++ b/App_Plugins/UmbracoForms/Assets/themes/default/umbracoforms.js
@@ -381,7 +381,7 @@
                         success =    cachedResult;
                     }
            
-                    visible = !(success ^ show);
+                    var visible = !(success ^ show);
                 return visible;
             }
```

**Comment by bergmania** [comment]
PR: 
- V7: https://github.com/umbraco/Forms/pull/242
- V8: https://github.com/umbraco/Forms/pull/241
