### ISSUE TITLE
Remove field types

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco.Forms.Issues#801]
We want to be able to remove field types, for example, we wish to remove Recaptcha 3 as this does not work for us.
This would also be useful if we were to replace some built-in field types.

**Comment by AndyButland** [comment]
You can do this @Myster - for example with the following code (for Forms 9 and 10):

```
    public class TestSiteComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.WithCollectionBuilder<FieldCollectionBuilder>()
                .Exclude<Recaptcha3>();
        }
    }
```

There's an example [here](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105367-umbraco-forms-disable-core-property-editors#comment-328648) too for Forms 8.
