### ISSUE TITLE
Remove built in workflow steps

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco.Forms.Issues#802]
We want to alter what steps are available when you edit a workflow.
**Because:**
We want to simplify things for editors.
We want to remove things that won't work in our site.
eg: remove "Save as Umbraco Content node"

Also described in this [forum post](https://our.umbraco.com/forum/umbraco-forms/76563-disable-form-workflow)
Note: Alex misunderstands, but Dan replies with correct description.

**Comment by AndyButland** [comment]
You can do this in a similar way to field types, [as I responded on the other issue you raised](https://github.com/umbraco/Umbraco.Forms.Issues/issues/801#issuecomment-1177055709).  Here you would use `WorkflowCollectionBuilder` and exclude the ones you don't want.
