### ISSUE TITLE
Again Missing Key index on table UFRecordDataString

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Forms.Issues#803]
There is a maybe related closed issue #713 for version 8.x and previous.

I have notice a similar issue for version 10.0.0 / 10.0.1 Umbraco CMS Cloud project.

### Bug summary
Health Check for Forms reports four missing indexes:
- Index on table 'UFRecordDataBit', column 'Key' is missing.
- Index on table 'UFRecordDataDateTime', column 'Key' is missing.
- Index on table 'UFRecordDataInteger', column 'Key' is missing.
- Index on table 'UFRecordDataLongString', column 'Key' is missing.

![health-check-forms-10 0 4](https://user-images.githubusercontent.com/866917/177754109-e92f4c67-3ac7-4c4b-8996-3575530e6288.png)

But the database looks correct to me:
![health-check-forms-10 0 4-database](https://user-images.githubusercontent.com/866917/177763484-1eba9c46-31ed-4ff1-adee-6a92ec738e21.png)

Maybe this is not a Forms issue but a Health Check issue?

Reproduction
------------

1. I have created a v10 cloud project in trial mode three weeks ago.
2. I added a second language, some translations, one simple contact form and a simple document type.
    1. I realised an issue related to language variants in Deploy and reported it.
    2. This issue <https://github.com/umbraco/Umbraco.Deploy.Issues/issues/126> was fixed. Btw. @AndyButland your are still in the team if this helps😉Project is <https://www.s1.umbraco.io/project/idseefeld>
4. I missed the auto upgrade because trial mode expired. Today I did a manual upgrade to CMS version 10.0.1 and also latest versions of Deploy and Forms. All went well and seems to work.
5. While going through Health Checks I noticed the missing key indexes.

**Comment by AndyButland** [comment]
Thanks for the report.  Having checked it looks like this a false positive you get with clean Forms 10 installs (as opposed to upgrades from earlier versions).  Because of an inconsistency introduced some time back, here we get a differently named index on the same key, so the health check needs to look for both.

Fix due in 10.0.5.

**Comment by AndyButland** [comment]
You'll find a patch release 10.0.5 on NuGet now.

**Comment by idseefeld** [comment]
Now all health checks are green.
