### ISSUE TITLE
Missing translation for formProviderPrevalueSources_sQLDatabaseTableDescription

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#804]
I noticed in prevalue sources the translation for the description `formProviderPrevalueSources_sQLDatabaseTableDescription` is missing.

![image](https://user-images.githubusercontent.com/2919859/178224908-4cd76efa-58d8-416a-9ad7-b63a62bad31b.png)

Umbraco v10.0.1
Umbraco Forms v10.0.3

**Comment by AndyButland** [comment]
Thanks, I found this myself actually when working in this area, so it'll be fixed in the next release.
