### ISSUE TITLE
Prevalue sources also includes element types

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#805]
When defining a prevalue source it is also possible to select element types, but I don't think element types are supported - only nodes rendered in tree.

If both document types and element types where supported the property should probably say "Content Type" instead.

![image](https://user-images.githubusercontent.com/2919859/178231782-d4998091-deaa-40d5-a47c-93b299495fd0.png)

Umbraco v10.0.1
Umbraco Forms v10.0.3

Maybe this should also use the tree picker instead like in MNTP configuration to keep it a bit more consistent with core UI.

![image](https://user-images.githubusercontent.com/2919859/178233205-f6aeb061-2cee-4055-a966-cbd4837451dd.png)

**Comment by AndyButland** [comment]
Will remove element types and ensure this list is ordered for the upcoming release.
