### ISSUE TITLE
Custom field not found by name if it contains spaces

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#807]
The documentation here https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Developer/Extending/Adding-a-Fieldtype mention how to add a custom field type and a field with name `My Custom Field` should look for a partial view `MyCustom Field.cshtml`, but it doesn't seem to be the case.

In this case I have a custom field with name "Course Dates" which look for a partial view `/Views/Partials/Forms/Themes/default/Fieldtypes/FieldType.Course Dates.cshtml`:
![image](https://user-images.githubusercontent.com/2919859/178337871-832aa3e2-aae9-4dc2-945b-498b9b098927.png)

```
public class CourseDatesField : Umbraco.Forms.Core.FieldType
{
    public CourseDatesField()
    {
        this.Id = new Guid("f47696aa-7fb8-4972-85aa-e4083e68558c");
        this.Name = "Course Dates";
        this.Description = "Render course date fields for course.";
        this.Icon = "icon-diploma";
        this.DataType = FieldDataType.String;
        this.SortOrder = 10;
        this.SupportsRegex = true;
    }

    ...
}
```

When I change the field name to "CourseDates" without a space it does work.

Umbraco v10.0.1
Umbraco Forms v10.0.3

**Comment by AndyButland** [comment]
I'll review this and the docs but in any case I think it's better here that we don't rely on the name.

There's a property you can set to explicitly define the view name to use:

```
this.FieldTypeViewName = "FieldType.CourseDates.cshtml";
```

**Comment by AndyButland** [comment]
Docs PR [here](https://github.com/umbraco/UmbracoDocs/pull/4206).  Having reviewed I could see the fall back to using the name of the field was implemented for backward compatibility reasons some time ago.  Since then this `FieldTypeViewName` was introduced and it's best to use that, so I've updated the documentation to reference it.
