### ISSUE TITLE
Styling now override action icon colors and position

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#808]
It seems this styling now override action icon colors and position.

![image](https://user-images.githubusercontent.com/2919859/178431599-8faa21d0-99dd-48b4-bc08-b076b54622b7.png)

How it should look.

![image](https://user-images.githubusercontent.com/2919859/178431978-7e47274e-016e-4574-bd1d-5d5ecf624615.png)

Umbraco v10.0.1
Umbraco Forms v10.0.3

**Comment by AndyButland** [comment]
Thanks for letting us know @bjarnef.  This will be fixed for the upcoming minor release.
