### ISSUE TITLE
Data Consent field is missing show label feature

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#810]
The Data Consent field is missing the "Show Label" feature as other fields has.

![image](https://user-images.githubusercontent.com/2919859/178489554-c2c24775-ca69-4042-a3e1-19fd8451757f.png)

E.g. Short Answer field type has this  Show Label (enabled by default).

![image](https://user-images.githubusercontent.com/2919859/178489705-8c9aa9f0-7e51-4121-936c-b014ef01405b.png)

Umbraco v10.0.1
Umbraco Forms v10.0.3

**Comment by bjarnef** [comment]
I also think it would be useful in custom field type inheriting `Umbraco.Forms.Core.FieldType` by default included/show this property.

**Comment by AndyButland** [comment]
I've added this now, will be in the upcoming minor release.  I think we probably need to add it to all that need it as there's some that you wouldn't want to give the editor the option to show the label (e.g. recaptcha).

**Comment by bjarnef** [comment]
@AndyButland how do we add the "Show Label" to custom field types?
For example prevalue source is shown when setting `SupportsPreValues = true`.

Ideally I think fields inheriting from `Umbraco.Forms.Core.FieldType` should by default has "Show Label" property and set to true, but the option to hide it or set the value to false.

**Comment by AndyButland** [comment]
Like this:

```
        /// <summary>
        /// Gets or sets a value indicating whether the field label should be shown.
        /// PreValues are a single element, a boolean indicating whether the default for the the checkbox is "checked".
        /// </summary>
        [Setting("Show Label", Description = "Indicate whether the the field's label should be shown when rendering the form.", View = "checkbox", PreValues = "true", DisplayOrder = 20)]
        public string ShowLabel { get; set; } = string.Empty;

        /// <inheritdoc/>
        public override bool HideLabel => ShowLabel == "False"; // Checking explicitly for false so the backward compatible default is to show the label.
```

**Comment by bjarnef** [comment]
Thanks, it would has been great it this was inherited though the get same label and description.
But I this is how it works at the moment and to be backward compatible.
