### ISSUE TITLE
Magic String adds duplicate value in Workflow

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Forms.Issues#811]
If you select the "Comment Form" from the premade templates for creating a Form, and then change the name to match one of the other question's alias', you get a duplicate value if you use it via a Magic string in the Subject field.

Reproduction
------------
### Bug summary
If you change a question's name to be the same as another question's `alias`, you will get a duplicate value if you use Magic strings to output the value.

### Specifics
- CMS: 9.5.2
- Forms: 9.4.2
- Deploy: 9.4.0

### Steps to reproduce
1. Create a Form and select the "Comment Form" template.
2. Change the "Email" name to be "Name". This way it has a Name that is equal to the alias of the above question:
![image](https://user-images.githubusercontent.com/2794633/178491177-579574ca-8931-441f-94eb-8ba7533376dc.png)
3. Configure the Workflow to include a "Send email with template (Razor)". Make sure you have the Magic strings for the questions in the "Subject" field. In this case it would be `name `and `email`:
![image](https://user-images.githubusercontent.com/2794633/178491542-30d8f51f-5fbe-4c9b-91bf-75c851b98b5f.png)
4. Render the Form however you like. Here I do it with a Formpicker:
![image](https://user-images.githubusercontent.com/2794633/178492001-d2ef071b-bfd5-483c-a6fc-3dbf39268bc1.png)
5. Submit the Form:
![image](https://user-images.githubusercontent.com/2794633/178492305-6ae42f66-985d-4530-9ceb-c3ed09ecb136.png)
6. Email contains duplicate value in the "Subject" field:
![image](https://user-images.githubusercontent.com/2794633/178492452-974c7f74-bf27-4a92-917c-b5f307e89a10.png)
7. The Magic string for `email `has been rendered twice

The same issue happens if you create a Form from scratch that mirrors the "Comment Form" template.

### Expected result
A single value from the Magic string is returned.

### Actual result
The Magic string is returning the value twice.

**Comment by AndyButland** [comment]
Thanks for writing this up so clearly.  I've found the issue and we'll resolve it for the upcoming release.
