### ISSUE TITLE
Form field wrapper use name in class instead of alias

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#812]
In form field wrappers (usually from `form-group` class) these also has a class based on field name.

I would probably expect it to use class based on form field alias as the name/label/caption may change - alias mostly don't after being added.

![image](https://user-images.githubusercontent.com/2919859/178511672-8ac02074-cdbb-4933-aab0-cd8a2a3fd42b.png)

Umbraco v10.0.1
Umbraco Forms v10.0.3

**Comment by AndyButland** [comment]
I agree that would have made more sense.  However I don't think we can really change this until we have a new major due as it would potentially break the styling of customer's forms.

I'll keep a note to consider this for V11.

**Comment by bjarnef** [comment]
Yeah, is there a way to change it from `Html.GetFormFieldClass(Model.FieldTypeName)` or would it require a custom method?

**Comment by AndyButland** [comment]
You would need to create a custom theme view if you didn't want that method being called when rendering the form.

**Comment by bjarnef** [comment]
It was actually set as part of the `f.CssClass` on the parent `form-group`. I could add `f.Alias` here.

There a theoretically to get duplicate class names by default in form from `f.CssClass`, e.g. adding a field with name `Mandatory` which is Mandatory, then you'll get a duplicate `mandatory` class.

![image](https://user-images.githubusercontent.com/2919859/178673631-67e7af56-37c2-493f-8c36-2060ca2cd402.png)

And if I added `f.Alias` I could potentially get it three times.

I think it would be great if Forms when generated `CssClass` property here only add distinct values. We don't want duplicate CSS classes anywhere and it doesn't have any difference whether it is added once or 10 times to same element.

**Comment by AndyButland** [comment]
We'll update to render out the field's alias instead of the caption in V11.

**Comment by bjarnef** [comment]
@AndyButland does this also fix redundant classes as shown in https://github.com/umbraco/Umbraco.Forms.Issues/issues/812#issuecomment-1182857467 ?

**Comment by AndyButland** [comment]
Yes, I've also updated the implementation to remove any duplicates that could get generated like in the scenario you describe.
