### ISSUE TITLE
Umbraco forms not saving after upgrading from 9 to 10

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco.Forms.Issues#813]
Hello

After upgrading Umbraco Forms from 9 to 10 (10.0.4) in our Umbraco 10 website, we get the following sort of error when saving any of our existing forms:

/umbraco/backoffice/UmbracoForms/Form/SaveForm 
Status code 400
`{"Message":"The request is invalid.","ModelState":{"FormWorkflows.OnSubmit[0].Settings[3].Value":["The Value field is required."],"FormWorkflows.OnSubmit[0].Settings[4].Value":["The Value field is required."],"FormWorkflows.OnSubmit[0].Settings[6].Value":["The Value field is required."],"FormWorkflows.OnApprove[0].Settings[3].Value":["The Value field is required."],"FormWorkflows.OnApprove[0].Settings[4].Value":["The Value field is required."],"FormWorkflows.OnApprove[0].Settings[6].Value":["The Value field is required."]}}
`

We have followed the version specific upgrade guid notes https://our.umbraco.com/documentation/add-ons/umbracoforms/Installation/Version-Specific, and the backoffice health check reports no problems for the Forms section.

No amount of editing the workflow or form will rectify the error, and creating and saving a brand new form succeeds.

Is there a known issue with upgrading/migrating to umbraco forms 10, and what other info can I provide to pinpoint what is causing this error?

Thanks

**Comment by AndyButland** [comment]
Could you check that you have deleted the files that were shipped in Forms 9 from `App_Plugins/UmbracoForms` that are now distributed as part of a razor class library please?

If you've done that, and ensured to restart and do a hard browser refresh afterward, would it be possible to share with me please a definition of a form that you have this error with, so I can debug and see what's going on?  If you've got any custom workflows or field types, I'd likely need the code definitions of those too.

You can get the form's Guid from the URL of the back-office when editing a form, and retrieve it's definition using this SQL:

```
select Definition from UFForms where [Key] = '<id of form>'
select Name, Definition from UFWorkflows where FormId = '<id of form>'
```

And I'm at abl AT umbraco DOT dk.  Thanks.

**Comment by AndyButland** [comment]
Thanks, I can replicate.  It's related to some nullability checks we updated in Forms 10.  I believe it's happening for workflow settings that were introduced after the form was originally saved.

So for example the "Reply To Email" field was added at some point after this form was originally created.  Hence it has a value of null, but we expect when it is posted to be an empty string (which it would be when created from scratch).

Will arrange a fix for this and a patch release.

**Comment by AndyButland** [comment]
You'll find a patch release 10.0.5 on NuGet now.

**Comment by shearer3000** [comment]
great thanks for getting that patch out the door so quickly @AndyButland 
upgraded to 10.0.5 and our forms now save successfully once more.
thanks

**Comment by AndyButland** [comment]
You're welcome. Glad we got it sorted.
