### ISSUE TITLE
Support caption/label in checkbox field type

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#816]
Currently the checkbox field type doesn't support a caption, but only the general label.
However this label has by default `col-sm-2` class.

Sometimes we want the label next to the checkbox like in Data Consent, which use `acceptCopy` as label value.

```
@model Umbraco.Forms.Web.Models.FieldViewModel
@{
     var acceptCopy = string.Empty;
     Model.AdditionalSettings.TryGetValue("AcceptCopy", out acceptCopy);
}

<div class="form-check">
  <input type="checkbox" name="@Model.Id" id="@Model.Id" value="true" data-umb="@Model.Id" class="form-check-input"
          @if (Model.Mandatory) { <text> data-val="true" data-val-required="@Model.RequiredErrorMessage" data-rule-required="true" data-msg-required="@Model.RequiredErrorMessage" </text> }
          @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on")) { <text> checked="checked" </text> } />
  <input type="hidden" name="@Model.Id" value="false" />

  <label class="form-check-label" for="@Model.Id">@acceptCopy</label>
</div>
```

Something like this would be great (modified a bit for Bootstrap 5).

```
@model Umbraco.Forms.Web.Models.FieldViewModel

<div class="form-check">
    <input type="checkbox" name="@Model.Name" class="form-check-input" id="@Model.Id" value="true" data-umb="@Model.Id"
           @if(Model.Mandatory){<text> data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage"</text>}
           @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on"))
           {<text>checked="checked"</text>}                                                                                                                                      
    />
    <label class="form-check-label" for="@Model.Id">@Model.Caption</label>
    <input type="hidden" name="@Model.Name" value="false" />
</div>
```

However using `Caption` both in group label and next to checkbox render same label and since checkbox field type doesn't have the "Show Label" feature, it is not possible OOTB to hide this label (but we can of customize this by overriding the "Checkbox" field type or modify the themes). I still think it makes sense to have "Show Label" feature on Checkbox field type though.
https://getbootstrap.com/docs/5.0/forms/checks-radios/#checks

I have previous have use-cases where we wanted a from group label and a different label text next to the checkbox.

Umbraco v10.0.1
Umbraco Forms v10.0.3

---
_This item has been added to our backlog AB#34004_

**Comment by snerpton** [comment]
+1 for this 👍

**Comment by AndyButland** [comment]
We'll add this option for the next feature release.  There's already a `ShowLabel` toggle, and we'll add a `Caption` one so you can have a label next to the checkbox instead of, or even as well as, the main one.
