### ISSUE TITLE
Text area with only whitespace is passing Mandatory requirement 

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco.Forms.Issues#818]
Adding a Long Text question, which renders a text area out on the form is passing validation even when the question is set as mandatory and no content has been added to the form.

If you modify the partial view `FieldType.Textarea` and move the `@Model.ValueAsHtmlString` onto a new line with indents, those indents end up in the rendered output. This results in the TextArea having "white space" on initial render.

I believe that if the TextArea field is mandatory being only populated with whitespace should fail validation.

Work arounds are:

* Use a RegEx to validate the field `(?!^$)([^\s])`
* Ensure that the @Model.ValueAsHtmlString is output directly after the `>` and before the `</textarea>`

**Comment by AndyButland** [comment]
I agree.  Coincidentally, I believe I've just resolved this in the process of fixing #817, so this will be fixed in the upcoming release.
