### ISSUE TITLE
Form label is always hidden in Title and Description field

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#823]
When using the Title and Description field the form label is always hidden (unlike other field types, where it is enabled by default).
I think this should be consistent and have a "Show Label" toggle as well.

![image](https://user-images.githubusercontent.com/2919859/179241059-31f53fff-63eb-4146-b797-f6bde9fbb70a.png)

Umbraco v10.0.1
Umbraco Forms v10.0.4

**Comment by AndyButland** [comment]
Have added this option for the upcoming release.
