### ISSUE TITLE
Add more input types to settings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#825]
Current following input types are supported.

![image](https://user-images.githubusercontent.com/2919859/179474962-e0b38269-0257-43d8-85b2-b7ef7984250f.png)

But there are more like `time` (time only) and `week` (week number) which could be useful:
https://www.w3schools.com/html/html_form_input_types.asp

Umbraco v10.0.1
Umbraco Forms v10.0.4

**Comment by AndyButland** [comment]
Yes, I didn't want to make this too overwhelming by including too many options, but I agree these could be useful.  There'll be there from the upcoming releases.
