### ISSUE TITLE
Missing Open / Edit / Remove since upgrade to 8.12.2

### ISSUE THREAD

**Issue by afinn-tech** [umbraco/Umbraco.Forms.Issues#827]
Recently upgrade from 8.7.3 to 8.12.2 
Seems to be missing the inline Open / Edit / Remove in form sections

Before
![image](https://user-images.githubusercontent.com/65241024/179773865-3ac141e7-3526-40f2-8af0-8ab7be1bba34.png)

After

![image](https://user-images.githubusercontent.com/65241024/179774166-697e7d2c-e56d-4649-af55-56f16a06579f.png)

Not sure if it was corrected in the RC ? 

Thanks
Andy

**Comment by AndyButland** [comment]
Thanks for reporting.  It looks like this went missing in the last update related to form permissions.  I hadn't found it to fix for the 8.13 RC but it will be for the full release of this minor version.

**Comment by afinn-tech** [comment]
@AndyButland  Thanks do you know when approx the RC will a full Release . Also any reason why 8.12.2 is SOOO slow to open forms tab ? compared to 8.7.6  .

**Comment by AndyButland** [comment]
Aiming for 9th August for the full release.  And no, not aware of why that would be but if you can share anything with regard network requests or similar can try to investigate.

**Comment by afinn-tech** [comment]
Thanks @AndyButland 
Here is the network view (8.12.2
![image](https://user-images.githubusercontent.com/65241024/182326277-0ceb0929-8da0-4680-913b-22f41e621a2e.png)

8.7.3
![image](https://user-images.githubusercontent.com/65241024/182326556-0925495a-a8e6-47fc-ad10-81185e3d9a43.png)

**Comment by AndyButland** [comment]
Could you give me an idea of how many records you have stored here please @afinn-tech - via `select count(*) from UFRecords`?  Thanks.

It could be an index we should have that's missing would resolve at least the first one, but I'd like to setup a similar database to text against to confirm.

**Comment by afinn-tech** [comment]
Thanks @AndyButland 
It quite Small ( 41)
![image](https://user-images.githubusercontent.com/65241024/182562213-6ba1a133-1b4d-4e02-bb93-4170e58b74ee.png)
As this is our Staging env

**Comment by AndyButland** [comment]
OK, that is very weird then.  If it's staging, I don't suppose it would be possible for me to have a copy would it (along with a back-office login)?  If so, I'm at abl AT umbraco DOT dk.  Thanks if so.

**Comment by afinn-tech** [comment]
@AndyButland  Sorry probably not as it contains data from Production 
I had a look at the other tables UFUserFormSecurity , 10704 
Forms we have 248 , and approx 78 users .  
We can jump on call if that helps

**Comment by afinn-tech** [comment]
Database

**Comment by afinn-tech** [comment]
The only long "1.4 s Average " query seems to be
 SELECT [Id] AS [Id], [User] AS [User], [Form] AS [Form], [HasAccess] AS [HasAccess], [AllowInEditor] AS [AllowInEditor], [SecurityType] AS [SecurityTypeInt] FROM [UFUserFormSecurity]
 Not sure if that helps @AndyButland

**Comment by AndyButland** [comment]
Yes, that helps - thanks.  I think I can see the problem... clearly that query should have a WHERE clause on it, so there's a case here we we've inadvertently introduced a query that's pulling all records back and then filtering in memory.  Will get this fixed up for the next releases, and it likely came in (or became more prominent) when we did work on the permissions in the last couple of updates.

As you have a fair few users and forms, the the user/form security table will have quite a few records to pull back, and that's why you are seeing this issue in particular.

**Comment by afinn-tech** [comment]
Thanks @AndyButland for update
