### ISSUE TITLE
Format magic strings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#828]
It is possible to use magic strings in e.g "Title and desription" field.
E.g. `[#price]` which in this case is a decimal value.

![image](https://user-images.githubusercontent.com/2919859/180203710-81d7dfb3-5833-49d1-a515-9cfc4e903d12.png)

However a decimal price on 18.500 is just rendered as 18500. It would be nice it we could do a bit formatting, e.g. format as currency for int/decimal/double/float values, maybe truncate a string (with ellipsis) etc.

Umbraco v10.0.1
Umbraco Forms v10.0.4

**Comment by AndyButland** [comment]
This has been prepared for the next release.  The format strings will follow the angularjs filter pattern, and we'll ship with the following:

```
[#title | upper]
[#title | lower]
[#title | truncate: 10]
[#price | number: C] (or [#price | currency] as a friendly alternative)
[#price | number: #0.##%]
[#date| date: dddd dd-MM-yyyy HH:mm]
[#number | bound: 5 : 10]
```

The implementation will be extensible too so it'll be possible to create your own format functions.
