### ISSUE TITLE
Checkbox Answer Type needs to enable the Editor to align tick box left

### ISSUE THREAD

**Issue by Ultradata-CXP** [umbraco/Umbraco.Forms.Issues#83]
**Issue**

Checkboxes are often used to get acceptance to statements.

The checkbox is often displayed as the first item with the statement appearing to the right (see below).

![image](https://user-images.githubusercontent.com/32289029/53136622-aee31500-35d3-11e9-8e5b-204343d17266.png)

This is the current behaviour of the Umbraco Forms Multiple Choice Answer Type but not the Checkbox Answer Type.  We are unable to align the check box to the left of the Checkbox Answer Type.

**Required**

Would it be possible to enable the Editor to align the checkbox to the right of the text.

**Comment by nul800sebastiaan** [comment]
Hey there @Ultradata-CXP - you can style it in any way you want in your custom themes. Alternatively, you could create a multiple choice answer with just one prevalue, which would look like your picture but with just one checkbox.
