### ISSUE TITLE
v 7.5.9 performance degradation when fetching forms on multiple threads.

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco.Forms.Issues#830]
In investigating the performance issues that led to #829, we found that when multiple users are requesting forms simultaneously the site's performance is seriously degraded.

The cause of this looks to be that `Umbraco.Forms.Data.Storage.FormStorage.GetForms()` locks (on a static object) before each call to `IFileSystem.OpenFile(string path)`. This means that only a single form can be fetched from the `IFileSystem` at a given time across the whole application. 

Because the lock happens before every call to `OpenFile` inside of `Umbraco.Forms.Core.Data.BaseFileSystemStorage<T>GetAll.()` multiple threads can end up waiting on each other for calls to `OpenFile` to complete. In the case that multiple pages with forms on are requested in close succession, the requests will be synchronised by the lock, causing each request to take much longer.

When the `IFileSystem` is a the `Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem` provider, calls to OpenFile() happen over the network so this exacerbates the problem.

I don't think this locking is necessary.

**Comment by JasonElkin** [comment]
his looks to also be the case in latest v8 when using the IFileSystem for storage (as opposed to the database).

**Comment by AndyButland** [comment]
Will close as per discussion on #829 (as I understand this is a re-formulation of the same underlying issue that was being reported).

**Comment by JasonElkin** [comment]
Hi @AndyButland, irrespective of the caching problem I think this is still an issue in some scenarios - specifically in high traffic sites with lots of forms.

It's less of an issue if forms are in the database.

If the locking is still there, necessary?

**Comment by AndyButland** [comment]
It's a bit hard to say.  Have done a little excavation and can see it was added back in 2017, presumably for a reason.  The lock is only around each single file though, which doesn't seem so unreasonable... you wouldn't want something else writing to it when loading for example.
