### ISSUE TITLE
Multiple choice, Single choice and Dropdown answer types do not validate Item/Answer length

### ISSUE THREAD

**Issue by ChrisMIntuitiv** [umbraco/Umbraco.Forms.Issues#832]
Multiple choice, Single choice and Drop down answer types do not validate Item/Answer length on creation which causes a truncation error to occur when submitting a form with a selection with length longer than 255 characters.

Umbraco Forms version: 9.4.2

Reproduction
------------
### Steps to reproduce
Create a form with a question using one of the following answer types:

- Multiple choice
- Single choice
- Dropdown

Add any number of items but ensure at least one of the items has a length in excess of 255 characters.

Example:
`This is an extremely long question that is totally unnecessary but the system will allow me to enter it any way so needs to be validated for length as the database field its being placed in is limited to 255 characters. Might seem a little silly on the face of things but causes an error and no record to be saved.`

![Forms setup](https://user-images.githubusercontent.com/109789984/181546894-e8e3d016-1872-415a-8909-dcd1fbcbde9f.PNG)

Save the form.

Add the form to any page.

Navigate to the form on the website and submit the form having selected the long answer.

This will result in a truncation error. In our instance the SQL error generated was as below:

`System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.`

### Specifics

I am fairly certain this is due to the selections being stored in the 'UFRecordDataString' table where the value field has a max char length of 255.

### Expected result

Either:

- The item answer length is validated on creation and the form is deemed in valid when the answer length exceeds 255. or;
- The items length can exceed the current 255 char limit and a record can be created successfully. Perhaps by saving the response as a long sting rather than a string where required.

### Actual result

Results in an exception and no record is stored in the database. Other workflows like sending an email still take place.

**Comment by ChrisMIntuitiv** [comment]
Aliases for questions also result in the same error when being saved into the UFRecordFields table. This can be reproduced by entering a very long alias for any question type.

Example:
`
thisIsAnExtremelyLongQuestionThatIsTotallyUnnecessaryButTheSystemWillAllowMeToEnterItAnyWaySoNeedsToBeValidatedForLengthAsTheDatabaseFieldItsBeingPlacedInIsLimitedTo255CharactersMightSeemALittleSillyOnTheFaceOfThingsButCausesAnErrorAndNoRecordToBeSaved.Longer.
`
![Alias Setup](https://user-images.githubusercontent.com/109789984/181565661-37996e66-bd8b-4e17-99d7-2ed09420fabc.PNG)

**Comment by AndyButland** [comment]
Thanks for reporting.  I've added some validation now on prevalue values and field aliases to prevent them being created with values that are too long for their respective database columns.  Due in the next releases.
