### ISSUE TITLE
localizationService error breaking form editing v 8.13.0

### ISSUE THREAD

**Issue by stuartbray-linney** [umbraco/Umbraco.Forms.Issues#836]
Hi,

Wonder if you could help. Having an issue on both stage and live servers.
Umbraco version: 8.8.0
Forms version: 8.13.0
Browser: Chrome or Edge.

When you load a form to edit in the back office.
![image](https://user-images.githubusercontent.com/10560164/183098343-461fa089-547a-41b8-953a-b238e6b2403b.png)

ReferenceError: localizationService is not defined at UmbRadiobuttonController.onInit [as $onInit] 

Umbraco.directives.js - line 7064.
if (vm.labelKey) {
                    localizationService.localize(vm.labelKey).then(function (data) { // <------------ ERROR HERE.
                        if (data.indexOf('[') === -1) {
                            vm.text = data;
                        }
                    });
                }

Pressing the dustbin or copy icon on a question does nothing. Icon just moves left and right slightly.

Have tried commenting out the offending lines but no dice. 

Forms was installed via the big forms button (not packages or nuget). Is it worth trying installing forms another way?
Have fiddled with the permissions too.

Any clues?

**Comment by AndyButland** [comment]
I'm not 100% sure I'm afraid but am actually not finding the code you've outlined in the code base, so maybe something has gone awry with your installation.  I'd suggest downloading the `UmbracoForms.Files.8.13.0-rc001.zip` from [here](https://our.umbraco.com/packages/developer-tools/umbraco-forms/) and copy all the files within it into your installation.

Be careful with `UmbracoForms.config` to not overwrite settings in your project that want different to the defaults.

**Comment by stuartbray-linney** [comment]
Hi, thanks for the assistance. We solved this by upgrading umbraco from 8.8.0 to 8.8.3. Cheers.

**Comment by AndyButland** [comment]
Good to hear, thanks.
