### ISSUE TITLE
Access form context within field types

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#837]
When working with custom field types, e.g. a compare field, it would be great to have access to form context or current form.
E.g. the `Umbraco.Forms.Web.Models.FieldViewModel` could have a `FormGuid` property or similar, so you know the `Guid` of the current form rendered.
This could be used to get current form and access other fields in the form.

As in the example https://github.com/umbraco/UmbracoDocs/pull/4215 I needed a reference to another field to compare the value, either using jQuery validation or `aspnet-validation`.

Umbraco v10.0.1
Forms v10.0.5

**Comment by AndyButland** [comment]
Makes sense, and easy to do.  We'll have this available in the next release.

**Comment by bjarnef** [comment]
@AndyButland is there a planned release date for v10.2.0 🚀

**Comment by AndyButland** [comment]
Not, not yet I'm afraid.  We're wrapping up a few other features but will likely look at preparing and releasing an RC in a few weeks.
