### ISSUE TITLE
Workflow Retry regardless of result

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco.Forms.Issues#838]
With the latest updates to forms you can now "Workflow Retry", however it only works for failed workflows.

There are scenarios that you would want to trigger the workflow regardless if it was successful. 

Because there is framework for retry already, can there be a button/action to trigger the workflow again in general? (UI can be improved) 

![image](https://user-images.githubusercontent.com/3933562/183855080-a5e55abb-3cdb-434c-803f-c04234424a79.png)

**Comment by AndyButland** [comment]
Yes, we can add this.  I thought initially it only made sense to retry failed ones but as you say there could be cases where you want to re-run a successful one.  This will be available in the next patch releases.
