### ISSUE TITLE
Umbraco Forms - VS Publish in v9 and Above

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco.Forms.Issues#840]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.2

### Bug summary

Hello,

I imagine someone has already flagged this. But when you are adding custom fields etc into Umbraco Forms. You need to add certain HTML files to underneath App_Plugins/UmbracoForms. This has been standard for a number of years. However, in v9 (and I imagine v10) when you do a rebuild and a publish in Visual Studio, it overwrites the contents of this folder back to the NuGet original version. Likewise with /views/partials/forms/default/. So when you add custom files in, they get deleted, However, they are required. 

Is there any advice on this, or perhaps does Umbraco Forms need a rethink of how to approach this going forwards? 

There is a workaround of manually copying the files to your server, which is fine for if you are publishing and then manually FTPing files up (and not deleting) however obviously isn’t really feasible with a publish to Azure. ( I imagine the same problem is true for Umbraco Cloud?) 

Maybe I’ve missed something new to the approach in .net core? (old habits die hard haha) 

Cheers
Ric

### Steps to reproduce

https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype

**Comment by AndyButland** [comment]
Hi @Ric-Carey - yes, this is a bit of a change from how things worked in the past.  As you've noted a `dotnet clean` will remove the folders installed with Forms.

It should be possible to work around this though by using root relative paths to the various assets.  Here's an example of an illustrative custom field that I've used for testing:

```
using System;
using Umbraco.Forms.Core.Attributes;
using Umbraco.Forms.Core.Enums;

namespace Umbraco.Forms.Core.Providers.FieldTypes
{
    [Serializable]
    public class ColorfulTextfield : FieldType
    {
        public ColorfulTextfield()
        {
            Id = new Guid("f51895e4-75fe-482e-9d02-0ab88cc3874b");
            Name = "Coloured Text Field";
            Icon = "icon-autofill";
            DataType = FieldDataType.String;
            SortOrder = 10;
            FieldTypeViewName = "/Views/Partials/Forms/Custom/FieldType.ColorfulTextfield.cshtml";
        }

        [Setting("My Setting", View = "~/App_Plugins/UmbracoFormsExtensions/backoffice/Common/SettingTypes/greensettingfield.html", DisplayOrder = 10)]
        public string MySetting { get; set; }

        public override string GetDesignView() => "~/App_Plugins/UmbracoFormsExtensions/backoffice/Common/FieldTypes/bluefield.html";

        public override string RenderView => "~/App_Plugins/UmbracoFormsExtensions/backoffice/Common/RenderTypes/redrenderfield.html";

        public override string EditView => "~/App_Plugins/UmbracoFormsExtensions/backoffice/Common/EditTypes/rededitfield.html";
    }
}
```
