### ISSUE TITLE
Email Workflow - Default Settings/Template

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco.Forms.Issues#841]
Hey,

Would it be possible to add a config setting to set the path to the default email template which is used in the workflow which sends an email. Clients regularly get really annoyed when the emails are branded in the Umbraco Forms default one and not a custom one created for them. 

Also, on the default email template, no offence to the people in the photo but could that be changed to something more generic Umbraco please than a photo of female developers. Most clients don’t have a clue who these people are, and makes it look like its a photo of friends that the developer working on the project has put in there on purpose. 

In Umb 8 and below, we used to just be able to completely overwrite this email template and avoid confusion for editors, but this is no longer the case anymore with .net Core reverting to the default. I would suggest that this increases the need to make this email template as generic as possible and think of the UX from an editor receiving that email's POV. 

Cheers
Ric

**Comment by AndyButland** [comment]
You should be able to take a copy of the provided template, modify it and save it with a new name in the same folder.  Then editors can select this template instead of the example when setting up the form.

Unless I've missed something - and please let me know if so - the provided example email isn't really a default, it's just the only one provided out of the box and hence the only one an editor can selected.  But if you provide another one, they can choose that instead,

**Comment by AndyButland** [comment]
Ah, I get you now.  Yes, that would be a good idea.... and actually, it's one someone already had (which I'd forgotten about with my first reply to you)!  Sorry about that.

There's a [DefaultEmailTemplate setting](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Configuration/#defaultemailtemplate) you can provide.

Just to add too, if you want more control here, we've added an abstraction you can override to replace the default behaviour of applying workflows to newly created forms, that [you can override](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/Customize-default-workflows).

**Comment by Ric-Carey** [comment]
ah perfect, nice one Andy!
