### ISSUE TITLE
Forms: 8.13.0 --> 8.12.1 Downgrade - The migration plan does not support migrating from state "6e692c5d-c670-4c34-af17-28d8dbf0dcd2" 

### ISSUE THREAD

**Issue by wjvankesteren** [umbraco/Umbraco.Forms.Issues#845]
I installed UmbracoForms 8,13 through NuGet.
I didn't compile and run the site yet (as far as I can remember).

I found out that there where some breaking changes in 8.13, so I wanted to downgrade back to 8.21.1, which went successfully.

Then after compiling and starting the site, it shows a boot failure:

**The migration plan does not support migrating from state "6e692c5d-c670-4c34-af17-28d8dbf0dcd2"**

Reproduction
------------

### Bug summary

Migration state error after downgrading UmbracoForms from 8.13 to 8.12.1 without compiling/starting site with UmbracoForms 8.13.

### Specifics

 * Have a site migrated from Umbraco 7.15.3 / UmbracoForms 7.x to Umbraco 8.14.8/Umbraco Forms 8.12.1 (I don't know whether this actually will matter)
 * Have the form definitions still on disk

### Steps to reproduce

 * Upgrade UmbracoForms to 8.13
 * Then directly downgrade UmbracoForms back to 8.12.1

### Expected result

no boot failure with migration state error

### Actual result

<html>
<body>

[BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.  -> Umbraco.Core.Exceptions.BootFailedException: Boot failed.  -> System.InvalidOperationException: The migration plan does not support migrating from state "6e692c5d-c670-4c34-af17-28d8dbf0dcd2".    at Umbraco.Core.Migrations.MigrationPlan.ThrowOnUnknownInitialState(String state) in D:\a\1\s\src\Umbraco.Core\Migrations\MigrationPlan.cs:line 278    at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) in D:\a\1\s\src\Umbraco.Core\Migrations\MigrationPlan.cs:line 306    at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) in D:\a\1\s\src\Umbraco.Core\Migrations\Upgrade\Upgrader.cs:line 67    at Umbraco.Forms.Core.Components.UmbracoFormsComponent.ExecuteDatabaseUpgrades()    at Umbraco.Forms.Core.Components.UmbracoFormsComponent.Initialize()    at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32    at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 219]    Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) in D:\a\1\s\src\Umbraco.Core\Exceptions\BootFailedException.cs:64    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +94
--

</body>
</html>

**Comment by wjvankesteren** [comment]
In the table [dbo].[umbracoKeyValue] I found that state value back:

key	value	updated
Umbraco.Core.Upgrader.State+UmbracoForms	6e692c5d-c670-4c34-af17-28d8dbf0dcd2	2022-08-19 11:53:57.600

If I change this value back to ba25a043-550e-4776-bd9e-a0960619e309 and then start the site, the boot failure is gone...

**Comment by AndyButland** [comment]
Yes, that's expected and you found the solution.  The downgraded site doesn't know about the state identifier for an update made in 8.13.

I'll close this as it's expected behaviour but if you have any more specifics about the breaking changes you ran into please let me know and will see if it's something we can resolve so you can upgrade.  Could be I've missed something we can fix for you in a patch to 8.13.
