### ISSUE TITLE
Recaptcha2 not working when using Linux Docker Container due to file naming

### ISSUE THREAD

**Issue by mennomout** [umbraco/Umbraco.Forms.Issues#846]
Using a Linux Docker Container to host V10 causes the following error to occur when adding a recaptcha2 to a form:

Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/backoffice/Common/FieldTypes/recaptcha2.html

changing the filename to Recaptcha2.html should fix this issue

Reproduction
------------

Host a V10 Umbraco site using Linux Docker Container. 
Create a form with recaptcha2. 
Navigating to the form in the backoffice should give the error message.

### Bug summary

Hosting an Umbraco V10 site using Linux Docker Container causes recaptcha2 not to work due to the ```recaptcha2.html``` filename.

### Specifics

Forms version: 10.0.5
Only checked it in Chrome
Full error message:
Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/backoffice/Common/FieldTypes/recaptcha2.html

### Expected result

Use recaptcha2 with forms
### Actual result

It does not load recaptcha2 due to the html file not being found (see error message)

**Comment by AndyButland** [comment]
Thanks for reporting (and finding the solution).  This will be fixed in the next patch release.
