### ISSUE TITLE
Exclude example email template from workflows

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#849]
Now that default themes, export and email templates are served via static assets, there doesn't seem to be a way to exclude default example email template, which may not be relevant to use, when custom email templates are added.

![image](https://user-images.githubusercontent.com/2919859/185900899-d1f6d079-20ef-459c-8238-19ede578970d.png)

**Comment by bjarnef** [comment]
@AndyButland I wonder if something has broken this in recent update?

In a Umbraco Cloud project on Umbraco 13.7.0 and Forms 13.4.0 I am able to pick the `Example-Template`.

```
"Forms": {
  "FormDesign": {
    "Defaults": {
      "DisableStylesheet": true
    },
    "DefaultEmailTemplate": "Standard",
    "RemoveProvidedFormTemplates": true
  },
  "Options": {
    "EnableFormsApi": true,
    "AppendQueryStringOnRedirectAfterFormSubmission": true,
    "DisableRelationTracking": true
  },
  "Security": {
    "EnableAntiForgeryTokenForFormsApi": false
  }
}
```

![Image](https://github.com/user-attachments/assets/374a570b-96ca-4e6c-bd08-4c8ceacb6006)

**Comment by AndyButland** [comment]
I don't see that you have `RemoveProvidedEmailTemplate` configured?  That's the one you need for the email templates.  `RemoveProvidedFormTemplates` is the one for the form templates (the default contact form, comment form etc.).

**Comment by bjarnef** [comment]
> I don't see that you have `RemoveProvidedEmailTemplate` configured? That's the one you need for the email templates. `RemoveProvidedFormTemplates` is the one for the form templates (the default contact form, comment form etc.).

Hmm, I seems I don't get intellisense for that property, only `RemoveProvidedFormTemplates`.

![Image](https://github.com/user-attachments/assets/82521f05-8725-4a3c-9af8-c2fc5a202f97)

**Comment by AndyButland** [comment]
It has been obsoleted, so maybe that's what it doesn't show up:

```
[Obsolete("Use the EmailTemplateCollectionBuilder to remove built-in templates. Will be removed in a future version.")]
```

As there is an alternative, and more standard way of removing these templates now (documented [here](https://docs.umbraco.com/umbraco-forms/developer/themes#email-templates)).

**Comment by bjarnef** [comment]
@AndyButland I have this instead:

```
public class StandardEmailTemplate : IEmailTemplate
{
    public virtual string FileName => "Standard.cshtml";
}
```

```
builder.EmailTemplates()
    .Exclude<DefaultEmailTemplate>()
    .Add<StandardEmailTemplate>();
```

When creating a new form from empty template, it still has `Forms/Emails/Example-Template.cshtml` on workflow though.

Am I missing something?

**Comment by AndyButland** [comment]
My guess is that you have a mix here of email templates being provided on disk - i.e. in `\Views\Partials\Forms\Emails\` - and using the more recently supported method of [providing via a Razor Class library](https://docs.umbraco.com/umbraco-forms/developer/themes#shipping-themes-in-a-razor-class-library).

If you have a copy of `Example-Template.cshtml` on disk and you don't want it, you should remove it.  Similarly if your custom "Standard" email template is both on disk and provided via an RCL, you would only want to use one method.

**Comment by bjarnef** [comment]
@AndyButland it only has this on disk:

![Image](https://github.com/user-attachments/assets/c0282c3d-bb7f-464a-bb64-e6814b23c604)

and the then this part:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/849#issuecomment-2714003382

nothing else :)

**Comment by bjarnef** [comment]
Okay, it makes sense.

The `DefaultEmailTemplate` in appsettings.json with file on disk, seems to have no effect. Not sure if that is expected, but I probably have noticed before as the project has been minor upgraded severral times.

It was what is initially mentioned https://github.com/umbraco/Umbraco.Forms.Issues/issues/849#issuecomment-2710113582 before I attempted with C# class.

**Comment by bjarnef** [comment]
@AndyButland I removed the C# for email template again and `Standard` is only shown up once in picker.

However I don't see it respect `DefaultEmailTemplate` configuration with value `Standard`.

From "Empty Form" template it assign `Forms/Emails/Example-Template.cshtml` and configure new workflow doesn't assign any template.

**Comment by AndyButland** [comment]
Not sure I'm afraid @bjarnef, it seems OK for me.

With this config:

```
"Forms": {
  "FormDesign": {
    "DefaultEmailTemplate": "Forms/Emails/Test-Template.cshtml",
    ...
```

I see this when creating a new form:

![Image](https://github.com/user-attachments/assets/84088698-5769-410e-b5fb-a764ae2f699c)

**Comment by AndyButland** [comment]
Yes, you can see the default value here: https://docs.umbraco.com/umbraco-forms/13.latest/developer/configuration#editing-configuration-values

**Comment by bjarnef** [comment]
Thanks.. now it works with form created from "empty form" template. I probably mixed it with default theme.

However when configure new workflow it seems to be empty:

https://docs.umbraco.com/umbraco-forms/13.latest/developer/configuration#settingscustomization

It doesn't seem it is possible to set `EmailTemplate` here?

```
"SettingsCustomization": {
  "WorkflowTypes": {
    "sendEmailWithRazorTemplate": {
      "EmailTemplate": "Forms/Emails/Standard.cshtml"
    }
  }
}
```
