### ISSUE TITLE
Adding Multiple file upload questions does not work.

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco.Forms.Issues#850]
Creating a form that has multiple file upload questions does not work correctly. Only the upload for the first file input is submitted to the server and saved subsequent uploads are ignored/lost.

This means you cannot have different questions asking for different things, along with the upload issue around a single file upload input that allows multiple files #769 it limits the ability to effectively use the file input question.

Form setup:
![image](https://user-images.githubusercontent.com/13313745/185931051-c6c8c2ec-aaa2-4fb1-9b39-8cf408c2cba5.png)

Form renderd:
![image](https://user-images.githubusercontent.com/13313745/185930798-507f690e-1f8b-4460-a67c-2c3b27ff68d9.png)

Email:
![image](https://user-images.githubusercontent.com/13313745/185930860-cfa21a51-fa44-4d53-9d46-a358f68f4cd6.png)

Entry in back office:
![image](https://user-images.githubusercontent.com/13313745/185930927-970c8f24-21b4-4938-9580-71e31a84ab0d.png)

Thanks

### Expected result

I would expect each instance of the file upload control to work and upload the appropriate files and associate them correctly with the appropriate question.

### Actual result

Only the first file upload actually submits the file.

**Comment by AndyButland** [comment]
Sorry @NikRimington, but I'm afraid I'm not able to replicate this, at least with the latest version of Forms 10.  Could you confirm what version you are using please?  Perhaps also if you can replicate with a clean install of the product.  Thanks.

**Comment by AndyButland** [comment]
Closing this one now given no further feedback and the issue not being able to be verified.
