### ISSUE TITLE
Upgrade from 10.0.5 to 10.1.0 causes issues with the responses list view 

### ISSUE THREAD

**Issue by jamesrichardbrett** [umbraco/Umbraco.Forms.Issues#852]
Hi 

Umbraco v10.0.1

I've just upgraded a project using Umbraco Forms from 10.0.5 to 10.1.0 and all is fine with the exception of the responses list view. 

![image](https://user-images.githubusercontent.com/108122423/186187485-876e65f3-5345-4089-88fa-f4efd26575a0.png)

From what I can see the data is stored correctly in the database 

![image](https://user-images.githubusercontent.com/108122423/186188038-35ebc1b6-2007-47a9-b046-cc0d83a8ba62.png)

and clicking on an item renders the correct results in the main view

![image](https://user-images.githubusercontent.com/108122423/186188252-105f6fee-9da2-4b32-9e7a-c0a803880645.png)

Are they any know issues or is there something else I need to do apart from just update the nuget package?

Cheers
James

**Comment by AndyButland** [comment]
I think you may be seeing some client-side caching.  Can you try ensuring you have cleared the cache please (e.g. open Chrome dev tools, disable the cache, and do a hard refresh)?

**Comment by jamesrichardbrett** [comment]
Hi Andy

Thanks for the insight, that's done the trick.

Cheers
James
