### ISSUE TITLE
Extend workflow send e-mail message with tempate (razor) with a message field

### ISSUE THREAD

**Issue by ralphvanvugt** [umbraco/Umbraco.Forms.Issues#853]
Workflow "Send e-mail message with template (razor)" has a lot of options, but it would be nice if you could enter a message which will be included in the e-mail.

**Comment by karlmacklin** [comment]
This is something we as well have tried to get working with not very good luck.

Currently resorting to some crazy idea of using form css class as a free form text field used within the razor template.

**Comment by karlmacklin** [comment]
@ralphvanvugt 

We did find a workaround.. sort of.

By extending the SendRazorEmailWorkflow, we can copy that behavior and also introduce a new field "Message".

Then we create a service, which we during the Execute function of our custom workflow "fill" with the Message, and then we can inject the same service within the template during the call to base::Execute.
After that's done, we just null the message string in the service again.

Messy, but straightforward and works clearly.

**Comment by AndyButland** [comment]
We'll be adding this for the next feature release.  We're planning to add two fields for formatted header and footer copy.  In the example template we'll render these, if populated. above and below the form submission details respectively (though in a custom Razor template they could of course be rendered anywhere).

![image](https://user-images.githubusercontent.com/1993459/216910466-9dfb1ec2-e54d-40d0-bf4d-bf16e3e3bb97.png)

New fields on the email's `FormsHtmlModel` model will be `HeaderHtml` and `FooterHtml`, both of type `HtmlString`, rendered as, e.g.:

```
@if (Model.HeaderHtml != HtmlString.Empty)
{
    <div>@Html.Raw(Model.HeaderHtml)</div>
}
```

**Comment by c9mb** [comment]
@AndyButland - are these are new fields being added to the Workflow? 
If so, would then not now also be auto-added as text values in
`Model.WorkflowSettings.HeaderHtml and Model.WorkflowSettings.FooterHtml`

**Comment by AndyButland** [comment]
They will, yes.  We had started working on this feature to add two new fields to the workflow before also working on the issue you raised about exposing all settings to the view model.

So they'll be available as strings via `Model.WorkflowSettings` and as `IHtmlContent` via the specific properties of `Model.HeaderHtml` and `Model.FooterHtml`.
