### ISSUE TITLE
Potential code smell on form details view

### ISSUE THREAD

**Issue by Attackmonkey** [umbraco/Umbraco.Forms.Issues#854]
I've recently upgraded a bunch of sites from older V8 versions of forms to 8.13, and most worked apart from one site, where everything was working, APART from the details view. When you clicked the view, the labels were there and the basic meta data (id, date submitted etc) but each of the form values was empty.

At first I thought it might be a permissions thing, but after some digging, I was able to track it down to the following issue. I'm not sure why it's an issue on some upgrades but not others. The detail object in the directive wasn't being passed through. In the umb-forms-entry-detail.html file there's the following code:

```
<umb-forms-render-type field="detail.displayValue"
                               name="detail.name"
                               view="detail.view"
                               detail="detail"
                               sensitive="detail.containsSensitiveData"
                               has-access="sensitiveDataAccess"
                               allow-edit="allowEdit">
        </umb-forms-render-type>
```
And then in the umb-forms-render-type.html file we have this code:

```
<div>
    <div ng-if="sensitive && !hasAccess" class="sensitive-data" data-umb="{{name}}">{{field}}</div>
    <div ng-if="!sensitive || hasAccess" ng-include="(allowEdit && detail.editView ? detail.editView : detail.view)" data-umb="{{name}}"></div>
</div>
```
Note that it's using the detail object to get the views here, rather than the view property that's been passed in in the directive above it. Would it make more sense to not pass the whole detail object around and just add an editView property in the directive above? At the moment the view property isn't being used. The convention on the other properties is just to pass in what's needed, so it looks like details should be taken off and replaced with the edit view.

When I made the suggested change, my details view started working again as expected.

**Comment by AndyButland** [comment]
Thanks @Attackmonkey - and yes, I agree with your suggestion so will make this update for the next patch release.

It's not really obvious how it caused the issue you ran into - at least to me - but it's definitely cleaner as you suggest.

We'll update this with the next patch releases.
