### ISSUE TITLE
v8.10.2 Workflow email contains internal Umbraco link to media file

### ISSUE THREAD

**Issue by gerard-mcmurtrie** [umbraco/Umbraco.Forms.Issues#855]
Using the "Select Link" feature to add a link to a Media file into a Forms workflow email results in the following link being sent in the email: 

**/{localLink:umb://media/ca1331d7b0d34c2d95b78084523ed2a7}**

Rather than:

**https://www.website.com/media/s3yhqmnd/filename.pdf**

Is this fixed in a newer version of Forms for Umbraco 8?

A workaround is editing the underlying HTML for the email and instead of adding the full link (https:// etc.), entering [/website.com/media/s3yhqmnd/filename.pdf] (http://website.com/media/s3yhqmnd/filename.pdf) which works but isn't a great solution for website editors.

**Comment by AndyButland** [comment]
I'm not quite following here how you are adding media to the workflow I'm afraid... would you mind elaborating a bit on what you are looking to do, perhaps with a screenshot or two so I can understand please?  Thanks.

**Comment by gerard-mcmurtrie** [comment]
Here's the Umbraco Forms workflow...
![image](https://user-images.githubusercontent.com/72869464/186940117-5eb606e2-fbde-4c0e-acab-c63d3f45c194.png)

Inserting a link into the Message for the "Send email to supporter" workflow email…

![image](https://user-images.githubusercontent.com/72869464/186939434-12889fe6-ba17-4455-b2f4-2db4adbc4336.png)

Select a .pdf file published on the website from Media as the link...

![image](https://user-images.githubusercontent.com/72869464/186939531-c10b1cba-c1d6-4b68-82c2-80a9d21fb544.png)

The received HTML email looks like..
![image](https://user-images.githubusercontent.com/72869464/186939561-41f3410d-757c-499b-bc3c-746141026d11.png)

This link in the email above is:
/{localLink:umb://media/ca1331d7b0d34c2d95b78084523ed2a7}

Rather than something like:
https://www.website.com/media/s3yhqmnd/filename.pdf

**Comment by AndyButland** [comment]
Thanks.  As far as I can see though, the "Send Email" workflow that ships with Forms only has a standard text area for entering the message.  It's not a rich text editor.  Could it be that you have a custom field type being used, either built by yourselves or from another package?

**Comment by AndyButland** [comment]
Will close this one now given there's not been any further discussion.
