### ISSUE TITLE
Umbraco Forms configuration enableantiforgerytoken doesn't do anything

### ISSUE THREAD

**Issue by martijnbeumers** [umbraco/Umbraco.Forms.Issues#859]
A brief description of the issue goes here.

A AntiForgeryToken is still beging created even when EnableAntiForgeryToken is set to false.
https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Configuration/#enableantiforgerytoken

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

A .AspNetcore.AntiForgery cookie is being placed even if the setting EnableAntiForgeryToken is set to false.
Als the cookie .AspNetcore.Mvc.CookieTempDataProvider is placed. 

### Specifics

Occurs with all major browsers (Chrome, Edge).
Umbraco Version 9.5.2
Umbraco Forms 9.2.2

The cookies are only set on pages that include a Form.  

### Steps to reproduce

Place a Umb Form on a page. 

### Expected result

Preferably no extra cookies are set at all.

### Actual result

See above.

**Comment by AndyButland** [comment]
This currently works to disable the check on the antiforgery token.  It doesn't prevent the creation of it in the first place, it's just that the check done on it when the form is posted is disabled.

You're right though that if we aren't doing the check we could remove the output of the token from the default theme, so we'll look at doing that in a future update.

**Comment by martijnbeumers** [comment]
Great! This helps in achieving full GDPR compliance.

**Comment by AndyButland** [comment]
Unfortunately this wasn't as straightforward as I thought, at least for V9 and up.  We can do this for V8 as the instruction to generate the antiforgery token is in the theme, but for V9+ [it's added automatically](https://github.com/umbraco/Umbraco-CMS/blob/d6b60cfc88c956c13959e99229eaf06fb1ff6ec1/src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs#L823) via Umbraco's `BeginUmbracoForm` method.

So we'll resolve this in the next patch release for V8, but for higher versions it will need to wait for V11, assuming an update to CMS is accepted to allow passing a parameter to disable the generation of the antiforgery token.  The framework's `BeginForm` method allows this, so it seems reasonable to add it to `BeginUmbracoForm` as well.

**Comment by AndyButland** [comment]
Will close this as the amend will be available in CMS and Forms 11.
