### ISSUE TITLE
Entires List View

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco.Forms.Issues#862]
Hey,

Just upgraded to the latest version 9.5.1 (on Umb 9.5.4) and all of the entries list view are now like the below, once you click into them to view, they are fine to see the entry, but on the list view its appearing as the same. 

Any ideas, if I am missing a new setting or something?

Showing in Console a typescript error:

TypeError: value.substr is not a function in umbraco-backoffice-js

Weirdly, not an error locally, but showing on production.   

Cheers
Ric

![image](https://user-images.githubusercontent.com/20398415/188717951-bb3ac14b-4dde-4465-a33f-513c1b945b86.png)

**Comment by AndyButland** [comment]
This has come up before and look like a caching issue.  Could you make sure you've done a hard refresh (e.g. with Chrome dev tools open and the browser cache disabled) please?

**Comment by AndyButland** [comment]
I just discovered this myself after seeing an update on another issue... but [incrementing this value](https://our.umbraco.com/Documentation/Reference/Configuration/RuntimeMinificationSettings/#manually-changing-the-cache-buster-version) in configuration should also resolve the problem.

**Comment by Ric-Carey** [comment]
Finally got to the bottom of this, for some reason either VS or Azure, didn’t publish the latest code from app_plugins, so it was running on latest version of forms, but didn’t have the relevant code on production. very weird. I had to manually upload the app_plugins/umbracoforms folder up to Azure, and then change the cache settings as you described. 

I was tearing my hair out with that one, as it was the first thing tried the cache settings. 

Nothing to action I suppose, just something to be aware of...

Cheers
Ric
