### ISSUE TITLE
Field options doesn't support custom icons

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#863]
Custom icons added via App_Plugins/**/backoffice/icons doesnt work for custom field types.

![image](https://user-images.githubusercontent.com/3726467/188850340-60905eaf-1f53-489d-8a31-59c03069f683.png)

They still use the old icon font
![image](https://user-images.githubusercontent.com/3726467/188850488-c52402f1-e147-4d73-9852-8d24c1f3c82f.png)

Same problem is in the answer type picker
![image](https://user-images.githubusercontent.com/3726467/188850645-b1d88afa-38ad-44f0-9205-8735ea828db4.png)

Reproduction
------------

Add some icons to App_Plugins/test/backoffice/icons, add a field type using the custom icon.

**Comment by AndyButland** [comment]
This has been updated and will be supported from the next release.
