### ISSUE TITLE
Umbraco Forms Picker Not Working Properly

### ISSUE THREAD

**Issue by asweeneymarathon** [umbraco/Umbraco.Forms.Issues#867]
### Bug summary

Upgraded Umbraco to Umbraco 10.2 and Umbraco Forms to Umbraco Forms 10.1.1 and the forms picker data type does not function correctly. Form Picker will render list of forms within it's own section, and not in it's own pop-out blade. The list can't be fully viewed or scrolled. Tabbing through the content works, but is not user friendly.

### Steps to reproduce

Install Umbraco 10.2
Install Umbraco Forms 10.1.1
Attempt to use Form Picker to choose a Form anywhere inside the Back Office.

### Expected result

List of forms opens in a new side blade menu, similar to how other pickers works.

### Actual result

List of forms does not open in new side blade menu. Opens in section when form picker is in.
![Form](https://user-images.githubusercontent.com/41925838/189705387-5f06f77e-8a95-4049-9b60-b34889057c63.png)

**Comment by AndyButland** [comment]
Thanks for reporting, I can replicate and we're investigating the issue.

**Comment by AndyButland** [comment]
This will be resolved in the upcoming patch release.  We'll get this out as soon as possible and update here when it's ready.  We have arranged Umbraco Cloud automatic upgrades for Tuesday 20th September,

**Comment by LennardF1989** [comment]
@AndyButland Could you make a preview release of this on NuGet? I really cannot wait a week to get this fix.

**Comment by AndyButland** [comment]
Yes, I'm releasing it today... we'll just schedule the Cloud automatic upgrades for next Tuesday, as they have a bit of lead time needed.

**Comment by LennardF1989** [comment]
Awesome, thanks! Than I won't waste any further energy on this :)

**Comment by AndyButland** [comment]
There's an update now available here: https://www.nuget.org/packages/Umbraco.Forms/10.1.2

**Comment by AndyBoot** [comment]
Can confirm this update fixed the issue. Odd one though because one our developers applied the update, cleaned & rebuilt with the same results. However, I pulled his commit, cleaned & rebuilt with more postitive results. I suspect there may have been browser caching at his end causing this so to those who also face the same issue after updating, try clearing your browser cache or at the very least attempt it within an incognito window to rule out it's your browser causing the issue and not Umbraco / Umbraco Forms itself.

**Comment by kinless** [comment]
Sorry to report that I'm having this issue with Umbraco 10.2 and Forms 10.1.2, even after clearing all cache and using browsers (both Mac and PC) I don't normally sign in with Umbraco just to rule out the browser.

In a Form Picker datatype, if I try and "Add" an allowed form, nothing happens. Same if I try and use the Form Picker in a content tab. On Mac, the content section dims a little bit, so I assume a side menu should be popping out but there's nothing. If I click anywhere in the dimmed area then it returns to normal.

I can provide a login to my beta website if replication is needed.

**Comment by LennardF1989** [comment]
> Sorry to report that I'm having this issue with Umbraco 10.2 and Forms 10.1.2, even after clearing all cache and using browsers (both Mac and PC) I don't normally sign in with Umbraco just to rule out the browser.
> 
> In a Form Picker datatype, if I try and "Add" an allowed form, nothing happens. Same if I try and use the Form Picker in a content tab. On Mac, the content section dims a little bit, so I assume a side menu should be popping out but there's nothing. If I click anywhere in the dimmed area then it returns to normal.
> 
> I can provide a login to my beta website if replication is needed.

Did you clear the Smidge cache?

**Comment by AndyButland** [comment]
Hi @kinless - yes, I would suggest as @LennardF1989 has, this could be the reason you aren't seeing the latest client-side assets.  There's a `Version` number documented [here](https://our.umbraco.com/documentation/Reference/Configuration/RuntimeMinificationSettings/#manually-changing-the-cache-buster-version) that you can use to do this.

**Comment by kinless** [comment]
Thanks @LennardF1989 and @AndyButland, didn't realize Smidge was caching the Umbraco side of things. Updated to 10.2.1 and applied the minification config in appsettings, now it works dandy. Learned something new yet again. As you were...
