### ISSUE TITLE
Missing separator before reload action

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#869]
A minor thing I noticed is the reload action should have a separator before the menu action at datasources tree.

![image](https://user-images.githubusercontent.com/2919859/190331569-445c9ae0-f600-4689-9ba3-1fc575e30abc.png)

![image](https://user-images.githubusercontent.com/2919859/190331603-ad5bddd8-29f5-483c-9eb3-dec435e90af4.png)

![image](https://user-images.githubusercontent.com/2919859/190331704-ffd5e476-4c8c-435c-880c-b7227b79804f.png)

this is pretty consistent in core although I noticed is it missing at Media Types tree. I think we should fix that as well just to be consistent.

![image](https://user-images.githubusercontent.com/2919859/190332113-e073e64f-8cb7-464c-bd27-9a2f6e3be106.png)

Umbraco v10.2.0
Umbraco Forms v10.1.2

**Comment by AndyButland** [comment]
Will be resolved in the next patch release.
