### ISSUE TITLE
On approve icon is squeezed

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#870]
I noticed the "On approve" icon is a bit squeezed.

![image](https://user-images.githubusercontent.com/2919859/190336199-bb678e16-9195-4fab-bf06-f01928c28fa3.png)

This fix is simple. Add `flex-shrink: 0` to avoid the text shrink the size of the icon.

![image](https://user-images.githubusercontent.com/2919859/190336079-7790f6ef-32db-40ae-bf10-03108919d275.png)

**Comment by bjarnef** [comment]
@AndyButland a quick one ;)

**Comment by AndyButland** [comment]
Thanks, I've applied this and it fixes the issue as you suggested.  Will be in the next patch release.
