### ISSUE TITLE
Magic strings doesn't work after form submission and validation errors

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#872]
It seems when a forms using magic strings and after form submission and when validation errors occurs, the magic strings no longer works, e.g when reCAPTCHA validation fails.

![image](https://user-images.githubusercontent.com/2919859/190584573-d2f53851-bb35-4656-a909-0849531c0b95.png)

Umbraco v10.2.0
Umbraco Forms v10.1.2

**Comment by AndyButland** [comment]
Will be resolved in the next patch releases.
