### ISSUE TITLE
Use richtext in Message on submit

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#873]
Now we have richtext in Umbraco Forms, could we update the "Message on submit" to use richtext field instead?
It may be a breaking change though.

![image](https://user-images.githubusercontent.com/2919859/190588988-a5f93179-4fdd-4290-8548-a3727e8f0eea.png)

It would also be great to update the node picker to be more consistent with Umbraco core UI.

Umbraco v10.2.0
Umbraco Forms v10.1.2

**Comment by bjarnef** [comment]
I wonder if it would be possible to override "Message on submit workflow" and replace textarea with richtext field type? And then always handle it has richtext? It may break using default theme, but I guess it would be fine if always using a custom theme or override the default FormSubmitted partial?

**Comment by AndyButland** [comment]
I don't think that would work, as this isn't a "setting" type in the sense of the ones that are associated with fields, workflows etc.  But the config option you suggested sounds promising to be able to update this without breaking anyone.  It's something we'll look into when planning the next release with new features.

**Comment by AndyButland** [comment]
This will be available as an option for the editor in the next Forms 10+ minor releases.

![Editor interface](https://user-images.githubusercontent.com/1993459/220340086-da6ac8ee-65a2-4700-afa0-e75d68db1679.png)
