### ISSUE TITLE
SendRazorEmail - An item with the same key has already been added

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#874]
I get an error in SendRazorEmail of duplicate keys in a dictionary.
The form has a field for course data using a prevalue source.

![image](https://user-images.githubusercontent.com/2919859/190595980-9622f58d-c9fc-4cc9-a453-5df5c4abc278.png)

![image](https://user-images.githubusercontent.com/2919859/190596105-ae6f5458-7b9f-43f8-8661-1cc1462d6a15.png)

It seems Forms somewhere may be using `Value` property from prevalue as a key instead of `Id`?

![image](https://user-images.githubusercontent.com/2919859/190596374-ca5e8cde-cf51-40d2-b5bb-fce0da8bf0fb.png)

![image](https://user-images.githubusercontent.com/2919859/190596187-19989bd9-3c4e-4847-b436-91504666b0ba.png)

Umbraco v10.2.0
Umbraco Forms v10.1.2

**Comment by AndyButland** [comment]
I think it's reasonable here that values for prevalues should be unique.  Given they'll be used for selection, if you had two items with the same value it wouldn't be possible to know which one the user picked in the form.

Will have a look though to make sure we don't error here in case there are duplicates.

**Comment by bjarnef** [comment]
The use-case here is that the client want a single form, but they have multiple course nodes, which each of them have course dates (elements).

So all the elements are combined in a single prevalue source. The Id property is unique though. I would probably have expexted it used the Id as key.

Alternatively we need a prevalue souce for each course and use PageId to get current page, but then it would also require multiple forms.

**Comment by bjarnef** [comment]
Okay, I included element key in the value, but now I get this error:

![image](https://user-images.githubusercontent.com/2919859/190626961-b8ae0a66-237d-44e8-a987-3bd420c966cb.png)

The prevalue value has 62 characters.

**Comment by bjarnef** [comment]
Okay the issue above was because I did a check if template on char instead of string.

```
@if (field.Alias == 'date')
{
    var fieldValue = field.GetValue();
    if (fieldValue != null && !string.IsNullOrEmpty(fieldValue.ToString()))
    {
        <span>@fieldValue</span>
    }
}
```

This works now:

```
@if (field.Alias == "date")
{
    var fieldValue = field.GetValue();
    if (fieldValue != null && !string.IsNullOrEmpty(fieldValue.ToString()))
    {
        <span>@fieldValue</span>
    }
}
```

But I don't really need this anyway as I trim the suffix in the field type.

So now I have this in prevalue source:

```
return dates
        ?.Select(x => new PreValue
        {
            Id = x.Item.Key.ToString(),
            Caption = x.Content.Name,
            Value = x.Item.StartDate.ToShortDateString() + " - " + x.Item.EndDate.ToShortDateString() + $" | {x.Content.Id}",
            SortOrder = x.Index
        })
        ?.ToList() ?? new();
```

and in the special field type:

```
var value = pv.Value.Split("|")[0].Trim();
```

**Comment by AndyButland** [comment]
With the next patch release any duplicate values within prevalues will be handled in this step.  It's used when replacing the values stored with the captions for the prevalues in sending emails and exporting to Excel.  Should there be any duplicate values, then the first caption will be used for a replacement and this error when transforming to a dictionary won't occur.
