### ISSUE TITLE
Conditionally shown fields are not included in form record

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#875]
I noticed when submitting a form the entry is created and labels looks correct.

However when editing form entry it shows `[object Object]`

![image](https://user-images.githubusercontent.com/2919859/190628942-29b430df-eb4f-4633-a124-ec9d7bfd1b5b.png)

![image](https://user-images.githubusercontent.com/2919859/190628978-c1355041-f6df-4d69-99b0-9c44f716f4b6.png)

Furthermore I noticed fields which are conditionally shows based on a value of another field (in this case a checkbox) are not stored in the record properties. I did fill out these form fields yes :)

![image](https://user-images.githubusercontent.com/2919859/190629219-e1ef2141-e556-40be-9daf-4ee67d6c280f.png)

![image](https://user-images.githubusercontent.com/2919859/190629525-a4d06f6f-81a4-41bf-b005-423fd7d1053b.png)

Umbraco v10.2.0
Umbraco Forms v10.1.2

**Comment by bjarnef** [comment]
Okay, the `[object Object]` issue was because I added a suffix to prevalue to make it unique.

```
return dates
                ?.Select(x => new PreValue
                {
                    Id = x.Item.Key.ToString(),
                    Caption = x.Content.Name,
                    Value = x.Item.StartDate.ToShortDateString() + " - " + x.Item.EndDate.ToShortDateString() + $" | {x.Item.Key}",
                    SortOrder = x.Index
                })
                ?.ToList() ?? new();
```

In that case I also needed to trim it is the field type.

```
var value = pv.Value.Split("|")[0].Trim();
```

However I am still seeing the conditionally fields to be missing on submission.

**Comment by AndyButland** [comment]
What are you using for your condition rule here please?  I.e. what value are you checking against to determine that the checkbox is ticked?

**Comment by bjarnef** [comment]
We have this condition on the group (fieldset):

![image](https://user-images.githubusercontent.com/2919859/190642411-6d81e8cc-455f-47da-a75c-c2168e3cdae7.png)

We then have a groups/fieldset initially hidden, but clicking a button change the value of the hidden field to `False`.

![image](https://user-images.githubusercontent.com/2919859/190642920-93530d08-f1ca-4efb-b882-d80fc09b2e73.png)

and when this value is `False` and user has checked this checkbox, the group/fieldset above is shown.

![image](https://user-images.githubusercontent.com/2919859/190643127-a14ac907-7fdf-442b-b680-c5636cbbea68.png)

I should mention that we have some special JS logic in the button to more more fields as it didn't seem Forms reacted on just changing value of the hidden field via JS.

```
@model Umbraco.Forms.Web.Models.FieldViewModel
@using Umbraco.Forms.Web

@{
    var settings = Model.AdditionalSettings;
    var hasCaption = settings.ContainsKey("Caption") && !string.IsNullOrEmpty(settings["Caption"]);
}

<button type="button"
    class="@Html.GetFormFieldClass(Model.FieldTypeName).ToString().Replace("form-control", string.Empty) btn btn-secondary"
    id="@Model.Id"
    name="@Model.Name" 
    data-umb="@Model.Id"
    value="@Model.ValueAsHtmlString">
    @(hasCaption ? settings["Caption"] : "Tilmeld")
</button>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("@Model.Id").addEventListener("click", showFields);
    });

    function showFields(e) {
        let btn = e.target;
        let group = btn.closest(".umbraco-forms-field");
        let collapseGroup = group.previousElementSibling;
        let collapse = collapseGroup.querySelector('input[type=hidden]');
        if (collapse) {
            collapse.value = 'False';
            btn.style.display = 'none';
            // Workaround for now
            
            var elements = Array.from(document.querySelectorAll('.umbraco-forms-fieldset'))
                .filter(item => item.id !== '0675d0e0-6455-49ff-a8af-3322973c047e');

            elements.forEach(elem => elem.style.display = 'block');
            document.querySelector(".umbraco-forms-navigation").classList.remove("hidden");
            document.querySelector(".block-list.block-list-main").classList.add("hidden");
        }
    }
</script>
```

**Comment by bjarnef** [comment]
For this usecase nested groups/fieldset would be useful and make complex forms easier to manage conditionally shown groups.
https://github.com/umbraco/Umbraco.Forms.Issues/issues/824

**Comment by AndyButland** [comment]
As far as I can tell from my tests you should find this works OK if you use "true" as your value to match with, rather than "True".  I'll  have a look though at making this case insensitive.  Either works client-side so we should have the same behaviour server-side.

**Comment by bjarnef** [comment]
@AndyButland regarding the `[object Object]` this seems to work fine:

```
return dates
        ?.Select(x => new PreValue
        {
            Id = x.Item.Key.ToString(),
            Caption = x.Content.Name,
            // Add suffix to ensure value is unique as Forms use this as key in a dictionary.
            // Ensure the replace suffix in the CourseDates field type.
            Value = $"{x.Item.StartDate.ToShortDateString()} - {x.Item.EndDate.ToShortDateString()} [{x.Item.Key}]",
            SortOrder = x.Index
        })
        ?.ToList() ?? new();
```

I guess it may be a deserialization issue when I before used a `|` as a separator.

```
Value = $"{x.Item.StartDate.ToShortDateString()} - {x.Item.EndDate.ToShortDateString()} | {x.Item.Key}"
```

**Comment by bjarnef** [comment]
@AndyButland you are right about this. It works when we use "true" / "false"  instead of "True" or "False".

However it seems it isn't enough changing hidden field value from `true` to `false` via JS and with the conditional rules.

So in this button field which change value of the hidden field "Collapse", we also needed to change fieldsets manually from `style="display: none;"` to `style="display: block;"` (or just removing the inline style).

I guess Forms isn't watching a value change in this case when changed via JS - at least not from outside.

```
@model Umbraco.Forms.Web.Models.FieldViewModel
@using Umbraco.Forms.Web

@{
    var settings = Model.AdditionalSettings;
    var hasCaption = settings.ContainsKey("Caption") && !string.IsNullOrEmpty(settings["Caption"]);
}

<button type="button"
    class="@Html.GetFormFieldClass(Model.FieldTypeName).ToString().Replace("form-control", string.Empty) btn btn-secondary"
    id="@Model.Id"
    name="@Model.Name" 
    data-umb="@Model.Id"
    value="@Model.ValueAsHtmlString">
    @(hasCaption ? settings["Caption"] : "Tilmeld")
</button>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("@Model.Id").addEventListener("click", showFields);
    });

    function showFields(e) {
        let btn = e.target;
        let group = btn.closest(".umbraco-forms-field");
        let collapseGroup = group.previousElementSibling;
        let collapse = collapseGroup.querySelector('input[type=hidden]');
        if (collapse) {
            collapse.value = 'false';
            btn.style.display = 'none';
            // Workaround for now
            
            var elements = Array.from(document.querySelectorAll('.umbraco-forms-fieldset'))
                .filter(item => item.id !== '0675d0e0-6455-49ff-a8af-3322973c047e');

            elements.forEach(elem => elem.style.display = 'block');
        }
    }
</script>
```

**Comment by bjarnef** [comment]
But then happens before the confirmation email, when the form is submitted and the record is created. As long the record hasn't the submitted data, I wouldn't expect the values to flow into other workflows like in SendRazorEmail workflow/template.

Anyway it should probably handle the invariant value on both client and service side as @AndyButland mentioned, so it doesn't matter whether "True" og "true" is entered.

**Comment by AndyButland** [comment]
Resolved to make this check case insensitive for the next patch release.
