### ISSUE TITLE
Page conditions do not work

### ISSUE THREAD

**Issue by ChrisMIntuitiv** [umbraco/Umbraco.Forms.Issues#878]
Rendering pages, or more specifically rendering the correct next/submit button does not appear to function.
![image](https://user-images.githubusercontent.com/109789984/191466995-0cf66005-67ab-4562-8e72-a1447e473651.png)

Umbraco forms version: 9.5.2 & 8.10.2

Reproduction
-----------------
### Steps to reproduce
Create a form with more than one page with at least a single question on the first page.
On the second page opt in to add a page condition based on the answer to the question in the first page.

Example:
![image](https://user-images.githubusercontent.com/109789984/191467667-2f680433-b8f2-414c-8b9f-4abb2edefe1e.png)

Add the form to any page via the grid editor:
![image](https://user-images.githubusercontent.com/109789984/191467868-ce4357d3-ab6e-457c-b86d-f98a27e32f09.png)

Template used in example for ref:
![image](https://user-images.githubusercontent.com/109789984/191468060-ee789969-1698-4de8-aeed-5dfeb5f33da4.png)

### Specifics

Having browsed through the Javascript it appears as though this functionality in version 8.10.2 is assuming that all pages are rendered onto the view as it looks for a "page" element in the document and attempts to show hide the buttons at the base of the form based on the conditional logic, however when it cannot find the page element it does nothing.

![image](https://user-images.githubusercontent.com/109789984/191470560-45d2cae6-631d-4af1-b7c7-578f67b6578c.png)

This logic appears to have been removed entirely in the later version 9.5.2.

Since the rendering of the form no longer works like this, i can only assume that this is some legacy functionality that was broken at some stage and never re-implemented perhaps.

### Expected result

The page conditions should render a submit button when the conditions for the following page are not met or a next button when the conditions are fulfilled allowing the user to progress to the next form page.

### Actual result
The next button always appears and a user can always navigate to the following page regardless of page conditions set.

### Alternative

Remove the ability to specify page conditions within the admin if the functionality is not supported.

**Comment by ChrisMIntuitiv** [comment]
Any feedback on the intention of the described functionality would be greatly appreciated as we have a client trying to use this feature in a production environment and trying to assess best course of action. Thanks.

**Comment by AndyButland** [comment]
If I've understood correctly, I think you are reporting the same issue as [#833](https://github.com/umbraco/Umbraco.Forms.Issues/issues/833).  If so, please see my comment there.

Please see also [#38](https://github.com/umbraco/Umbraco.Forms.Issues/issues/833) which may describe what you are looking for/expecting to see.  And if so, that feature is due in the next release for Forms 10.

**Comment by ChrisMIntuitiv** [comment]
Thanks Andy, I think overall i was unclear as to how the feature should work so my report was a bit of a mix of both the issues you have linked. Reading through your comments to those other issues I now understand the idea behind it I believe.

Assuming from your remark re: forms 10 there is no intention to back port this new functionality to previous versions of forms, do you have any advise on the best way we could hide the options from the UI ourselves to avoid confusion from clients.

**Comment by AndyButland** [comment]
There's not a configuration option to switch it off I'm afraid.  There are ways to inject your own CSS into the back-office (e.g. [this example](https://www.jondjones.com/learn-umbraco-cms/umbraco-7-tutorials/umbraco-backend-customisation/how-to-use-your-own-custom-css-styles-in-the-umbraco-backend/)), so I'd imagine you could find a way to hide it via that if you needed to.

And yes, even if it's almost certainly a better behaviour, we can't really back-port it to V8 and V9 without doing a new minor release (i.e. it would be considered a change to functionality that some people may be relying on, which wouldn't be appropriate in a patch).  And we aren't planning new minors now for these versions (see under "Minor releases moving forward" [here](https://umbraco.com/blog/umbraco-forms-81395101-release/)).

**Comment by AndyButland** [comment]
Closing this one then given we have other issues covering the points raised here.
