### ISSUE TITLE
Filter to resolve form name when used in block list

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#879]
In Umbraco core we can use `ncNodeName` filter to resolve the Guid as a node name when used in block labels.
https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/common/filters/nestedcontent.filter.js

```
{{form | ncNodeName}}
````

But this won't work for Form Picker.

Looking at `umbraco.forms.js` from the static assets https://nuget.info/packages/Umbraco.Forms.StaticAssets/10.1.2 it seems there are a few filters, but not one to resolve form name from guid.

Currently using `{{form}}` in label expression isn't pretty.

![image](https://user-images.githubusercontent.com/2919859/191477608-b19d8f62-b205-4d13-a051-8628cf5fa3a6.png)

We couldn't of course write our own filter, but it would be great if it was included in Umbraco Forms.

**Comment by AndyButland** [comment]
This will be available in 10.2, you'll be able to use `{{form | umbFormsFormName}}`.
