### ISSUE TITLE
Forms gets overwritten when deploying to the next environment on cloud

### ISSUE THREAD

**Issue by mikkelbrusen** [umbraco/Umbraco.Forms.Issues#88]
### Bug summary
A cloud project with 3 environments - Development, Staging and Live. The client has access only to Live. This is where they edit all the content, be it text or images. And lately they've started using Umbraco Forms.

The client is happily working on their form on the prod environment. This form exist on the dev env as well. He has added a new property, short answer, to the form. He then saves it and all is well.

The developer is working on a new feature on the dev env. He is now ready to deploy this feature to the live environment. The client is happy with what the developer has done, and he now gets the new feature on his prod env.

When the client goes into the backoffice to see if all is well, he notices that the changes has he done on form is now gone.

### Specifics
Umbraco version 7.13.2
Forms version 7.0.6

This only occurs on UaaS with deploy.

### Steps to reproduce
You need at least 2 environments on UaaS to reproduce this.
Create a form on Dev env and deploy it to Live.
When the deployment is done on Live, go to the Live backoffice and add a new field to the form.
Save the form.

Now go to the Dev backoffice and create a new document type. Don't touch the form.
When you are happy with the document type, deploy it to live, and wait for the deployment to be done.
When it is done, go to the lives backoffice and see how the form has reverted back to it's original state.

### Expected result
Would have expected that the form has kept its changes.

### Actual result
Form got overwritten with the form from the dev environment.

The reason why this happen is because the way Umbraco Forms is structured. It is based around .json files for the forms themselves, so unless the new changes on the Form comes from dev, the form on live will always be overwritten, making it pointless to make changes on live.

To actually solve this, The forms would have to saved in the database rather than .json files.

**Comment by nul800sebastiaan** [comment]
Duplicates https://github.com/umbraco/Umbraco.Cloud.Issues/issues/23
