### ISSUE TITLE
Creating comment or contact form doesn't set email field type

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#880]
I noticed when creating a comment or contact form from default templates these add an email field, but these are just regular `text` input field.

I think these should set `email` as type by default instead.

Btw. is it possible to customize the templates if a specific project need another standard set of form fields?

Umbraco v10.2.0
Forms v10.1.2

**Comment by bjarnef** [comment]
Furthermore it seems comment or contact form doesn't respect `DisableStylesheet` in appsettings.json, but empty form does.

```
"Forms": {
  "FormDesign": {
    "Defaults": {
      "DisableStylesheet": true
    }
  },
  "Options": {
    "AppendQueryStringOnRedirectAfterFormSubmission": true
  }
}
```

![image](https://user-images.githubusercontent.com/2919859/191495813-f39497ca-6553-4cd7-9563-dbe8822a390d.png)

**Comment by AndyButland** [comment]
I've made a couple of updates due in 10.2 related to this:

- Added the "email" field type setting for the two email fields.
- Added a configuration option: _Umbraco : Forms : FormDesign : RemoveProvidedFormTemplates_ which can be set to `true` to remove the out of the box templates, provided via a Razor class library, from the list.

Can confirm you can create your own templates if you add them on disk at: `\App_Plugins\UmbracoForms\Data\Templates\`.

Not taking account of the configuration for `DisableStylesheet` is expected.  The form template used has a setting for `"disableDefaultStylesheet": false`, and so this is used in preference to the configuration default (which is really only for when you create an empty form).

**Comment by bjarnef** [comment]
@AndyButland okay, then I we want to keep e.g. the default contact form template, but remove the comment form template is that possible? Furthermore can we modify `"disableDefaultStylesheet": true` of these standard templates? It seems we can't modify these directly as these are shipped with the static assets.

https://nuget.info/packages/Umbraco.Forms.StaticAssets/10.1.2

![image](https://user-images.githubusercontent.com/2919859/192454108-90f00a72-c6de-4dcd-8f0d-331a865668b5.png)

**Comment by AndyButland** [comment]
Yes, I'd suggest you would set the new configuration value `RemoveProvidedFormTemplates` to true.  Copy the ones you want to keep to `\App_Plugins\UmbracoForms\Data\Templates\` and modify them as you prefer.
