### ISSUE TITLE
Request error when "ManageSecurityWithUserGroups" is set to true

### ISSUE THREAD

**Issue by laurengore42** [umbraco/Umbraco.Forms.Issues#882]
This is essentially a re-opening of issue 778, as I think I have a reliable reproduction of it.

Reproduction
------------

### Bug summary

Clicking the text instead of the arrow in the Group Permissions dropdown produces a harmless, but worrying to users, error.

### Specifics

Umbraco 9.5.4 (local, not cloud)
Umbraco Forms 9.4.2
Windows 11
Firefox latest version

### Steps to reproduce

Turn on ManageSecurityWithUserGroups = true in appsettings.json
Navigate to 'Users' in backoffice
Click the arrow next to 'Forms Security', opening the Forms Security dropdown
Click the arrow next to 'Group permissions', opening the Group Permissions dropdown (no error on this step)
Now click on the text itself of 'Group permissions', or the text of 'User permissions' underneath (error is produced)

### Expected result

No response from clicking on the text
No error message when clicking the text

### Actual result

![image](https://user-images.githubusercontent.com/12659154/191983431-a404611a-f96c-4e97-b18c-34afb9b82500.png)

**Comment by AndyButland** [comment]
Thanks for reporting this Lauren.  However, I've just checked as I'm not seeing this in the latest version of Forms 9, and can see we fixed it for 9.5.  So it looks to me if you upgrade to the latest version of Forms 9 you'll no longer encounter this issue.
