### ISSUE TITLE
Email fails to send when large file is attached

### ISSUE THREAD

**Issue by jamesrichardbrett** [umbraco/Umbraco.Forms.Issues#883]
We have an email (plain text) workflow notification that attaches the uploaded file on submission

![image](https://user-images.githubusercontent.com/108122423/192007209-ba14a3f0-1301-4cec-acbc-f906d8880fee.png)

When a file is uploaded around 1mb everything work fine 

![image](https://user-images.githubusercontent.com/108122423/192008322-e235e99c-b2ce-4936-bb0a-ed81ca599165.png)

but the client has tested this with an 80mb file and the email is not sent, Here's the message from the logs

![image](https://user-images.githubusercontent.com/108122423/192008498-55df0bdc-86d8-4aa9-970a-ecb32b81dbfc.png)

![image](https://user-images.githubusercontent.com/108122423/192007494-231d9f83-2ee6-4896-b013-59471e2cc06a.png)

we have the request length set high enough to handle this 

 "Runtime": {
        "MaxRequestLength": 150000
      },

Are there any other settings I need to update?

Umbraco 10.1.1
Umbraco Forms 10.1.1

**Comment by AndyButland** [comment]
My thought here is that you are running into a limit with the SMTP service you are using, as 80Mb is quite large for an attachment and maybe is being blocked.

Forms doesn't really do anything special with email sending.  It just uses the underlying method exposed by the CMS, which is implemented with [this](https://github.com/umbraco/Umbraco-CMS/blob/e626fca2432582f052cb13654eedd9e60ef8723f/src/Umbraco.Infrastructure/Mail/EmailSender.cs#L75).

I'd suggest looking to write a small test application, using similar code to that shown here and the same SMTP server, and see if  you run into the same issue.  If so, you can maybe speak with whoever is managing your SMTP server to see if there are limits you are running into.

**Comment by AndyButland** [comment]
Closing this one now due to lack of further activity, and the issue seemingly existing outside of Forms.
