### ISSUE TITLE
Show "empty" when using condition comparing empty value

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#886]
When using a condition to show a field comparing an empty value, it seems a bit odd the message says:

"Show this question if **all** of the following match: **Company** is not" (I have translated the Danish word "Firma" to English "Company").

![image](https://user-images.githubusercontent.com/2919859/192726339-c32f576c-601e-4946-aa70-a1a5fb58791c.png)

I think it would be better with: "Show this question if **all** of the following match: **Company** is not empty"

It seems it isn't possible to compare whitespaces, but with a value the message says.

"Show this question if **all** of the following match: **Company** is not **Test**"

Forms v10.1.2
Umbraco v10.2.0

**Comment by AndyButland** [comment]
We've added the "empty" suffix onto this message now, when the value being compared is empty.  Agree that's a bit clearer and certainly a more grammatically correct sentence!
