### ISSUE TITLE
Self-closing <input /> elements flagged as invalid under W3C HTML5 validation

### ISSUE THREAD

**Issue by kinless** [umbraco/Umbraco.Forms.Issues#889]
While running my Umbraco v10 pages through the W3C HTML validator, I've discovered that any page using Umbraco Forms (v10.1.2 in my case) is getting flagged due to the self-closing `<input />` elements sprinkled throughout the rendering process, which is deemed "widely discouraged" within an HTML5 document. I don't see any way to change that in the backoffice (unless there's a secret config setting somewhere).

Obviously this isn't a deal-breaker or any sort of high priority, in fact it might be more of a feature request than a bug. But it would be nice having the option to turn off XHTML-based rendering that would trigger normal `<input>` elements so full W3C validation can be achieved.

![umbraco_forms_invalid_html](https://user-images.githubusercontent.com/5661056/193442587-08bf1dd3-6e45-41c2-9171-c2ce567b7c98.png)

**Comment by AndyButland** [comment]
Interesting... from a quick read this seems to be a relatively recent change, with a little bit of debate going on about it.  See:

- https://github.com/validator/validator/issues/1433
- https://github.com/orgs/mdn/discussions/242

I can't see that removing these self-closing `input` tags would do any harm though, so am not averse to changing it in the default theme we ship with.

In the meantime it is possible to [create your own theme](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Themes/), copying and adapting the default one, if you were minded to remove them now.

**Comment by kinless** [comment]
@AndyButland thanks for the links! I tend to forget that W3C is comprised of regular folk and not some deity from the far reaches of cyberspace putting standards into place. With those discussions in context, the warning does sound rather opinionated, but I can see why they're trying to standardize the syntax due to the risks of adjacent malformed code.

I believe you're right about the recent change. This wasn't getting flagged a few months ago, but with the last round all of a sudden my `<br />` and `<link />` tags were discouraged. Had to adjust TinyMCE's config to fix some of them.

I was under the impression Umbraco Form themes only took care of styles, but if they allow me to construct a form without self-closing tags, that should be adequate. Like I said, not a high-priority for me right now, but if unclosing the input tags could be the default theme in a later version with no ill-effects, that will benefit everyone sensitive to 100% validation.

**Comment by AndyButland** [comment]
We've discussed this one internally and have decided that actually it's best we don't update these files.  As these are partial view templates, we don't know whether they are hosted within an XHTML or HTML document.

If it does matter to people, there is as discussed the option of taking copies of the view files, saving them on disk in the expected locations, and updating them to your preference.  For Forms 10, the default theme views are shipped as part of a Razor Class Library, but you can get copies of them for reference/adapting [via the documentation](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Themes/#creating-a-theme).

Maybe we can revisit this in future if what's currently a perhaps slightly opinionated view of one validator becomes much more of a standard, or of course if there are any issues found with browser rendering (currently my understanding is that there isn't any practical issue with using one style or other).  But for now I'll close and recommend the custom them file approach if people want to make these changes.

**Comment by kinless** [comment]
@AndyButland just to follow up on this, there's been further discussion on the [W3C side](https://github.com/validator/validator/issues/1433) (with most objecting to the change), and as a result the validator has officially downgraded the "Warning" to an "Info" tag with a less-harsh tone to trailing slashes, so while it technically still discourages its use in conjunction with unquoted attributes, it's no longer recognized as invalid.

**Comment by AndyButland** [comment]
Thanks for the update @kinless.
