### ISSUE TITLE
Upload file value doesn't persist after validation

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Forms.Issues#89]
A brief description of the issue goes here.

When you have a form with validation on a field that saves, then the upload file is not persisting and fails on a second try.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

When you have a form with validation on a field that saves, then the upload file is not persisting and fails on a second try.
### Specifics
Running these version:
Umbraco.Core.dll: 7.13.2
Umbraco.Forms.Core.dll: 7.0.6
Umbraco.Deploy.dll: 2.0.15

But has been confirmed on lower versions as well.
Has only been tested in Chrome (72.0.3626.109)

### Steps to reproduce

* Create a document type with a forms picker
* In the template for it, show the form:
```
@Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid="@Model.Content.FormsPicker", FormTheme="bootstrap3-horizontal", ExcludeScripts="1"})
```
* Create a form that has a mandatory text field with validation as a number
* Add an upload file field to the form
* Go to the form on the frontend, fill in **text** in the text field
* Fill in a file in the upload field (tested with a pdf)
* Submit - the validation will fail since it has text not numbers, at this point it will look like this:
![capture](https://user-images.githubusercontent.com/36075913/53421018-2d2d2600-39dd-11e9-83eb-207e4fcdc8a3.PNG)
* Correct the text value to a number and resubmit

### Expected result

As the frontend lists "Current files" I would expect it to not have to be reuploaded

### Actual result
It gave an error saying no file was uploaded:

**Comment by bergmania** [comment]
PR:
- V7: https://github.com/umbraco/Forms/pull/239
- V8: https://github.com/umbraco/Forms/pull/238
