### ISSUE TITLE
Allow "Folder" selection when defining Form Picker DataType configuration

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#891]
Now that we have folders in Umbraco Forms, I think it would be great to be able to use a folder as the source for defining the Form picker datatype - so you could have datatypes which are "folder-specific"

For example, I have two Forms folders: "Active" and "Disabled". I'd like to have a Form Picker which only allows selections from the "Active" folder, and if I create a new form in the "Active" folder, it should automatically be available to that Picker. Right now there is no way to specify the **folder root** as the source - you have to individually select forms:
![image](https://user-images.githubusercontent.com/1252593/193918091-891ebf51-94a8-4360-866c-7c694c6c9e1f.png)
 
Which means, unless I want to continually update the Datatype every time I add a new Form, the Folders don't have much practical value outside the "Forms" management section.

**Comment by AndyButland** [comment]
I've realised that we've tackled this in the latest releases by adding the option to set "allowed folders" as well as "allowed forms" in a form picker data type.

https://docs.umbraco.com/umbraco-forms/developer/property-editors

**Comment by hfloyd** [comment]
Nice! Is this available in forms for v13 also? (no doc page for https://docs.umbraco.com/umbraco-forms/13.latest/developer/property-editors)

**Comment by AndyButland** [comment]
We'll include this in the next minor for Forms 13 too.
