### ISSUE TITLE
Conditions applied to form navigation don't work

### ISSUE THREAD

**Issue by Attackmonkey** [umbraco/Umbraco.Forms.Issues#893]
When adding conditional logic to the page buttons in 10.1.2, the conditions are NOT applied and the buttons are always shown regardless of whether the conditions are satisfied.

Reproduction
------------

### Bug summary

If you add conditions to page buttons in forms, the conditions being met DO NOT cause the buttons to be hidden.

### Specifics

Using the latest version of Forms (10.1.2) in Umbraco 10, page button conditions are broken.

### Steps to reproduce

Create a simple form and add a condition to the page to show/hide the buttons. Display the form on a page and meet the condition, the buttons for the form will not be hidden. It doesn't seem to matter if the form is single or multi-page. Other conditions, e.g. field level ones, work as expected.

### Expected result

If I apply a condition to the form buttons and that condition is met, the buttons should be hidden.

### Actual result

Buttons are not hidden and are still visible, despite conditions having been met.

**Comment by AndyButland** [comment]
Thanks @Attackmonkey - I could replicate and think I've found the issue here, so will include a fix in the upcoming patch release.

**Comment by Attackmonkey** [comment]
Awesome! Thanks @AndyButland, much appreciated!
