### ISSUE TITLE
DataConsent Checkbox injects validation value as an Additional Label

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.Forms.Issues#895]
In addition to the actual label/Accept Copy, the validation message whether set at the property level or not shows up next to the checkbox as well. Even you check the "Hide Label" option

**Comment by AndyButland** [comment]
I think this is as expected, even if a little confusing for this field type.

The "Hide Label" setting controls the display of the field's caption, and is consistent across all field types:

![image](https://user-images.githubusercontent.com/1993459/194803336-a9e5d4db-30ce-419c-a4ed-9c02ed34974a.png)

As you say the specific "data consent" field type renders a second HTML `label`, used for the text that goes alongside the check-box.  And this always displayed,  I think that makes sense, as you would seem to be unlikely to want to hide that, as a checkbox with no explanatory copy, in most cases, wouldn't be useful.  My expectation is that users of this field would want that label being displayed, even if the label for the field's caption has been removed.

If that really doesn't work for your requirements, it's possible to override the partial view for just this one field type via [theming](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Themes/).
