### ISSUE TITLE
Mandatory data consent isn't being validated correctly where conditions are set

### ISSUE THREAD

**Issue by git-wizard** [umbraco/Umbraco.Forms.Issues#897]
Description
------------
When a form has a mandatory data consent field type with conditions set (tested with conditions for: show if {question} is {radio option}), when the condition is not met and the user submits the form, validation prevents you from submitting.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I believe that the data consent isn't accounting for met/ unmet conditions before issuing a validation error when it is set to mandatory.

### Specifics

My application is running forms version: 9.4.2

### Steps to reproduce

To reproduce the bug:
   * Create a new form
   * Add a question with radio button options (2 or more)
   * Add a new question with data consent
   * Make data consent mandatory
   * Add a condition to show if {first question} is {radio option}
   * Fill the form out, without selecting the radio option that will show the data consent
   * Submit form

### Expected result

I expect to see the form submit as the data consent isn't visible and should not be mandatory when hidden.

### Actual result

The actual result is the form not displaying any validation errors (unless validation summary is turned on) but the form does not submit.

**Comment by AndyButland** [comment]
Thanks for reporting.  I can replicate and once reviewed we'll fix in the next available patch release.

**Comment by git-wizard** [comment]
@AndyButland that's great thank you. We also have a custom data consent field type that uses an RTE which has the same issue. You wouldn't by any chance be able to share the code behind checking conditions before validation?

**Comment by AndyButland** [comment]
Yes. I don't see why not.  This is what we have (now - I refactored a little in fixing this bug) in the base `FieldType` class, that wasn't in `DataConsent` as it overrode the `ValidateField` method and was missing this check.

We check to see if a field is mandatory and the value provided is empty.  If that's the case, before adding a validation error we check to see if the field is visible due to conditions.

That uses the following function, which after this fix is out, will be available to call from any derived field types (as `DataConsent` will do):

```
protected static bool IsFieldVisible(Form form, Field field, IFieldTypeStorage fieldTypeStorage)
{
    var isVisible = true;

    if (field.HasCondition())
    {
        // If we have a circular condition, assuming it's not visible as otherwise we get into infinite loops in the visibility checks.
        if (field.Condition.IsCircular(form))
        {
            isVisible = false;
        }
        else
        {
            var allValues = form.AllFields.ToDictionary(f => f.Id, f => string.Join(", ", f.Values ?? new List<object>()));
            isVisible = field.Condition.IsVisible(form, fieldTypeStorage, allValues);
        }
    }

    return isVisible;
}
```

This code is for Forms 8, as I've added the fix there and, once it's reviewed will up to 9 and 10 so we can patch all versions from 8+.  You may need to adapt a little for 9.

**Comment by git-wizard** [comment]
@AndyButland Amazing, thank you :)

**Comment by git-wizard** [comment]
@AndyButland Works like a charm! Thank you very much for getting back so quick and for the code behind it :)

**Comment by AndyButland** [comment]
Will be resolved in the patch releases indicated by the associated labels for Forms 8 and 9, and the next minor release for Forms 10.
