### ISSUE TITLE
Override Submitted partial for specific form

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Forms.Issues#898]
It is possible to override form fields for a specific form:
https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/custom-markup/#customizing-for-a-specific-form

I tried the same for default Submitted.cshtml as we want to list the data from the record below the message.

However it doesn't quite seem to work?

I tried with:

```
~\Views\Partials\Forms\115dd2b5-1eeb-421a-bf20-d96023482750\Submitted.cshtml
~\Views\Partials\Forms\themes\standard\115dd2b5-1eeb-421a-bf20-d96023482750\Submitted.cshtml
```

However it works fine it placed inside 

```
~\Views\Partials\Forms\themes\standard\Submitted.cshtml
```

Not sure if it should work, but I think I saw another issue or discussion on https://our.umbraco.com that overriding by Form ID (Guid) didn't work.

Umbraco v10.2.1
Forms v10.1.2

**Comment by AndyButland** [comment]
I believe this functionality was removed yes (at least I see no evidence in the code that this should work), but I don't know the history behind it I'm afraid.  Could be something we look to reinstate though.

**Comment by bjarnef** [comment]
Okay, it would be great to mention this in the documentation here for now: https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/custom-markup/#customizing-for-a-specific-form

However I workaround it to put it in `~\Views\Partials\Forms\themes\standard\Submitted.cshtml`

Then I have this:

```
@if (Model.FormId == Guid.Parse("115dd2b5-1eeb-421a-bf20-d96023482750"))
{
    @await Html.PartialAsync("Forms/CourseRegistration", Model)
}
```

where `Model` is `Umbraco.Forms.Web.Models.FormViewModel`

and in the partial `CourseRegistration` I have something like this for now:

```
@model Umbraco.Forms.Web.Models.FormViewModel

@inject Umbraco.Forms.Core.Data.Storage.IRecordStorage _recordStorage;

@{
    var record = _recordStorage.GetRecord(Model.RecordId);
}
```

In the email templates these inherits `Umbraco.Forms.Core.Models.FormsHtmlModel` though.

```
@inherits UmbracoViewPage<Umbraco.Forms.Core.Models.FormsHtmlModel>
```

Is there service to get the the form / record as `Umbraco.Forms.Core.Models.FormsHtmlModel`?

**Comment by bjarnef** [comment]
I noticed when I output `@Model.RecordId` in `Submitted.cshtml` is returns an empty guid.

Is that expected?

However `@TempData["Forms_Current_Record_id"]` returns a guid.

![image](https://user-images.githubusercontent.com/2919859/196382030-90e4ee1a-fb9c-4b9b-a742-98e0a70759d7.png)

**Comment by bjarnef** [comment]
I think it could have something like this:

```
@inject Umbraco.Forms.Web.Services.IFormRenderingService _formRenderingService;

@{
    Guid.TryParse(TempData["Forms_Current_Record_id"]?.ToString(), out Guid recordId);
    
    var record = _formRenderingService.GetRecord(recordId);
}
```

However I found it a bit inconsistent in this service: `Umbraco.Forms.Web.Services.IFormRenderingService`

![image](https://user-images.githubusercontent.com/2919859/196386847-9a192d6d-955f-47f6-8ff2-a4398dc6172d.png)

where `Record` is a dto class while `Form` and `FormViewModel` are more intended to use in views.

Sometimes I am missing a `GetRecordModel()`or similar.

**Comment by AndyButland** [comment]
Will close this one as the original issue is duplicated by #860.
