### ISSUE TITLE
Can't view Entry Detail if first field is blank

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco.Forms.Issues#9]
First logged as http://issues.umbraco.org/issue/CON-1218 using Umbraco 7.4.3 and Forms 4.3.2. Still present in Forms 6.0.8.

When viewing the Form Entries report, I expect to be able to view the Entry Detail overlay for any of the records shown, regardless of field values.

What actually happens is that the link to view the Entry Detail is constructed around the value of the first column. If the first field on the form is a non-mandatory field, and is blank for some of the entries, I am unable to view the Entries Detail for those records.

A workaround is to create a new folder  `~/App_Plugins/UmbracoFormsEntries/`  and within it create two files:

**package.manifest**

```
{
    css: [ "~/App_Plugins/UmbracoFormsEntries/umbraco-forms-entries.css" ]
}    
```
**umbraco-forms-entries.css**

```
 .umb-table-body__link[ng-click^='vm.viewEntryDetails']:empty::before { content: '(no answer)'}
```

Now you can click on '(no answer)' to view the form entry where there is no form data.

**Comment by warrenbuckley** [comment]
Reviewing the PR here
https://github.com/umbraco/Forms/pull/222
