### ISSUE TITLE
DynamicRecord.HasField(string caption) returns true for any argument

### ISSUE THREAD

**Issue by ThoughtProcess** [umbraco/Umbraco.Forms.Issues#90]
While building out a new feature for a client's website, I noticed that the `Umbraco.Forms.Mvc.DynamicObjects.HasField()` method doesn't appear to return `false` if a non-existent field name is provided as an argument.  As far as I can tell, it will return `true` for any string input.

It is likely that the same problem exists for the `bool HasField(Guid fieldId)` method, but I haven't checked.

Reproduction
------------

```
var recordGuidString = "b0d5ce04-c59a-465d-b405-c23ceca68d2f" // Change this to a valid GUID for a particular record coming from your form.

using (var recordStorage = new RecordStorage())
{
    var result = recordStorage.GetRecordByUniqueId(Guid.Parse(recordGuidString));
    var targetRecord = new DynamicRecord(result);

    var hasField = targetRecord.hasField("someFakeField"); // Always returns true
}
```
### Bug summary

I took a look at the implementation of `DynamicObjects.HasField()` using DotPeek, and saw the following:

```
public bool HasField(string caption)
{
  return this._record.RecordFields.Where<KeyValuePair<Guid, RecordField>>(
  	(Func<KeyValuePair<Guid, RecordField>, bool>) (f => f.Value.Field.Caption == caption)) != null;
}
```

If this is accurate to the original implementation, I _think_ that this method will always return true.  If no items match the `f.Value.Field.Caption == caption` predicate, shouldn't the `Where()` clause return an empty IEnumerable<T>, instead of null?

### Specifics

I think a quick-fix solution would be to alter the implementation of HasField() as follows:
```
public bool HasField(string caption)
{
  return this._record.RecordFields.Where<KeyValuePair<Guid, RecordField>>(
  	(Func<KeyValuePair<Guid, RecordField>, bool>) (f => f.Value.Field.Caption == caption)).Any();
}
```

### Steps to reproduce

See Reproduction section above.

### Expected result

For fields that exist on the record:  Return true.
For fields that do not exist on the record:  Return false.

### Actual result

Any arbitrary string value fed into `HasField()` returns `true`.

**Comment by ThoughtProcess** [comment]
Quick update to my previous suggested fix... how about something like:
```
public bool HasField(string caption)
{
  return this._record.RecordFields.Any(f => f.Value.Field.Caption == caption);
}
```

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/246

**Comment by bergmania** [comment]
Hi @ThoughtProcess ,

Thanks for reporting. I have made a PR fixing this.
