### ISSUE TITLE
Rebuilding UmbracoFormsRecordsIndex with no members hangs in back office. 

### ISSUE THREAD

**Issue by Pauldubbya** [umbraco/Umbraco.Forms.Issues#900]
**Bug summary**
When rebuilding the UmbracoFormsRecordsIndex in the back office (settings > examine management) the rebuild hangs unless you have 1 or more records present. 

**Specifics**
Tested as an issue in Umbraco 10.2.1 with Umbraco forms 10.1.2 and 10.1.3. When rebuilding the index with no records in the rebuild page appears to persist until you change screen. 

**Steps to reproduce**
Blank install of Umb 10.2.1 with Forms 10.1.2, then attempt to rebuild the UmbracoFormsRecordsIndex index in the back office.

**Expected result**
Index to rebuild and the three dot/circles at the foot of the page disappear as soon as it's complete. 

**Actual result**
The index does get rebuilt, but the interface in the backoffice hangs with the three dots/circles continuing until you change page.

**Comment by Pauldubbya** [comment]
Actually guys this is happening on Umb 9.5 as well for us and on the MembersIndex, so this is an Umbraco bug not a forms bug. I'll raise it there.

**Comment by AndyButland** [comment]
OK, thanks for the update.  I'll close this one then but of course re-open if you do find on further investigation that it's something Forms specific.
