### ISSUE TITLE
Conditions on form navigation does not work

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Forms.Issues#902]
I am experiencing the exact same thing as on [this](https://github.com/umbraco/Umbraco.Forms.Issues/issues/893) issue, so I will use the text from that as base. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

If you add conditions to page buttons in forms, the conditions being met DO NOT cause the buttons to be hidden.

### Specifics

Using the latest version of Forms (9.5.3) in Umbraco 9.5.4 page button conditions are broken.

### Steps to reproduce

Create a simple form and add a condition to the page to show/hide the buttons. Display the form on a page and meet the condition, the buttons for the form will not be hidden. It doesn't seem to matter if the form is single or multi-page. Other conditions, e.g. field level ones, work as expected.

### Expected result

If I apply a condition to the form buttons and that condition is met, the buttons should be hidden.

### Actual result

Buttons are not hidden and are still visible, despite conditions having been met.

**Comment by aguyfromdenmark** [comment]
I can confirm that the umbracoforms.js code looks exactly like that, and that the buttons also match the selectors.

**Comment by AndyButland** [comment]
Hmm... in that case, would it be possible to export your form definition, and if you have a default theme, share that too please? I'd like to be able to spin it up locally to see if I can see what the problem is.  I'm at _abl AT umbraco DOT dk_ if that would be OK to share.

**Comment by aguyfromdenmark** [comment]
Oops! Found it!
It turned out that our custom theme, that has been carried over from older versions, had a single thing missing: The id on the .umbraco-forms-page wrapper. I added that in, and now it works.

**Comment by AndyButland** [comment]
Good to hear, thanks for letting me know.

**Comment by aguyfromdenmark** [comment]
No problem. Thanks for helping me notice the error 😅
