### ISSUE TITLE
Missing prevalue sources Type "Umbraco Docs from Xpath" in form version 8.13.2

### ISSUE THREAD

**Issue by mitraganesh** [umbraco/Umbraco.Forms.Issues#904]
Hi,

I have updated my old umbraco site to version 8 latest. And also updated umbraco form "6.0.9" to 8.13.2 but some forms return error due to prevalue sources Type "Umbraco Docs from Xpath" is missing on form version 8.13.2.

How can I get old forms working with version 8.13.2?

Thanks!

**Comment by AndyButland** [comment]
I think you will need to amend your forms to use a prevalue source of type "Umbraco Documents".  This is going back a while (before my time!) but as far as I can see this will also allow you to retrieve Umbraco documents via XPath queries, I expect "Umbraco Docs from Xpath" was removed in one of the major versions you've migrated between as it's functionality was supported now by the "Umbraco Documents" one.

**Comment by mitraganesh** [comment]
Thanks @AndyButland 

My previous Xpath query returns all node like with "Umbraco Docs from Xpath" 
//homePage/contentPage/centresListingPage/*[@isDoc][toursAvailable = '1']

But "Umbraco Documents" does not return any node. How can get that query work?

**Comment by AndyButland** [comment]
OK, it doesn't look like that's supported I'm afraid.  I realise that the XPath expression in "Umbraco Documents" is only used for defining the root node, it doesn't define a full query for retrieving the nodes themselves.

My guess is that this was removed when Umbraco 8 was released, as in that the XML cache that existed for Umbraco 7 was removed.

You might need to look at [creating a custom prevalue source](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Extending/), that you can build to return the nodes that you need using the [querying options](https://our.umbraco.com/documentation/reference/querying/) available in Umbraco 8.

You can use "Umbraco Documents" if your requirement is limited to retrieving nodes of a particular type, within a particular root.  But from your XPath it looks like you need something that's a bit beyond that.
