### ISSUE TITLE
The security configuration setting "DefaultAccessToNewForms" does not appear to have any affect when set to "Deny".

### ISSUE THREAD

**Issue by ChrisMIntuitiv** [umbraco/Umbraco.Forms.Issues#907]
The security configuration setting "DefaultAccessToNewForms" does not appear to have any affect when set to "Deny".

https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Configuration/#defaultaccesstonewforms

Umbraco version: 9.5.4
Umbraco Forms version: 9.5.3

Reproduction
------------
### Steps to reproduce
Append the following config to the app settings file as per the documentation linked above.
"Security": {
        "DefaultAccessToNewForms": "Deny"
      }
Create a user (must have access to the forms section)
![image](https://user-images.githubusercontent.com/109789984/199454287-a02f5fe4-1027-40b7-bf36-e270dca068df.png)

Create a new form and save.

Login in as new user and visit the forms section. You will be able to see the new form and have full access.

### Alternative steps to reproduce

Follow the above but before logging into the new user navigate to the forms security area.

Here you will notcie the newly created form has been flagged as "HasAccess" for every user in the system.

### Specifics
I have tried with various versions of umbraco forms: 9.3.0, 9.4.2,9.5.4 in an attempt to get this working. The first due to it being references in the documentation. The second was the version our site was running on already and the latest version.

In each case the setting did not appear to be in the app settings schema. I dont know if this reflects that its not available?

### Expected result

- An admin should have to manually mark a form as "HasAccess" in forms security section for any newly created form for any user they wish this to be the case.

- By default the user should not be able to see/access any newly created form in the admin system.

- When visiting the forms security section before a user has been granted access manually the toggle should reflect they have no access.

Thanks in advance for any assitence getting this up and running.

**Comment by AndyButland** [comment]
Hi @ChrisMIntuitiv - it looks like we might have a typo in the docs.  I just went to try to replicate this and found the setting named `DefaultUserAccessToNewForms`, not `DefaultAccessToNewForms`.

Could you try that and let me know if that looks to resolve the issue for you? Meanwhile I'll prepare an update to fix the documentation.

**Comment by ChrisMIntuitiv** [comment]
I shall give it a go.

**Comment by ChrisMIntuitiv** [comment]
Hi @AndyButland Changing the setting name does appear to have solved it. I have noticed that administrator accounts still get access by default regardless of which setting I use. I assume this was a design choice?

**Comment by ChrisMIntuitiv** [comment]
I tried setting the user group permissions as below to see if this was conflicting but it is still true that administrtor accounts get access by defaault:

```
"DefaultUserAccessToNewForms": "Deny"
"GrantAccessToNewFormsForUserGroups": "form-creator",
"ManageSecurityWithUserGroups": true
```

**Comment by AndyButland** [comment]
Yes, that is the case when individual user accounts are used for permissions - the administrator accounts will get access to all.

**Comment by ChrisMIntuitiv** [comment]
Okie doke, seems to be working as expected then. Thanks for the help.

**Comment by AndyButland** [comment]
Good to hear, you're welcome.
