### ISSUE TITLE
Dot notation on DynamicRecord does not work correctly when target fields have spaces in their names

### ISSUE THREAD

**Issue by ThoughtProcess** [umbraco/Umbraco.Forms.Issues#91]
The Umbraco Forms "Working With Data" page describes how developers can iterate through `DynamicRecord` objects and dereference arbitrary fields on those records, as shown below:

> In order to access custom form fields you can simply use the dot notation, using the field caption but removing all spaces and non alphanumeric characters.

The sample script shown in the file illustrates one such example of this in action:

```
@using Umbraco.Forms.Mvc.DynamicObjects

<ul id="comments">
	@foreach (dynamic record in Library
			.GetApprovedRecordsFromPage(@CurrentPage.Id))
	{
		<li>
			@record.Created.ToString("dd MMMM yyy")
			@if(string.IsNullOrEmpty(record.Website)){
				<strong>@record.Name</strong>
			}
			else{
				<strong>
				<a href="@record.Website" target="_blank">@record.Name</a>
				</strong>
			}
			<span>said</span>
			<p>@record.Comment</p>
		</li>
	}
</ul>
```

However, it seems that several users have [reported](https://our.umbraco.com/forum/umbraco-pro/contour/46262-Get-record-info-using-Razor) some [challenges](https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/63136-GetRecordsFromForm-Umbraco-Forms) when they [try](https://our.umbraco.com/forum/umbraco-pro/contour/57789-Trying-to-display-form-records-if-the-caption-for-the-field-has-a-space-it-will-not-resolve) to retrieve field names which have spaces.

Reproduction
------------

Create an Umbraco form that has two or more fields, one of which has a one-word name, and the other which has one or more spaces.  For example:
* Model Number
* Age

Then, try to dereference the fields in your Razor code, such as the following example:

```
@using Umbraco.Forms.Mvc.DynamicObjects

<ul id="comments">
	@foreach (dynamic record in Library
			.GetApprovedRecordsFromPage(@CurrentPage.Id))
	{
		<li>
			@record.ModelNumber - @record.Age
		</li>
	}
</ul>
```

In my testing, `record.Age` will be correctly resolved, but `record.ModelNumber` will not.

### Bug summary

I took a look at the implementation of the `DynamicRecord.TryGetMember()` override using DotPeek, and saw the following: 

```
public override bool TryGetMember(GetMemberBinder binder, out object result)
{
  string name = binder.Name;
  if (this._record != null)
  {
    Regex Cleanregex = new Regex("[^a-zA-Z0-9 -]");
    if (this._record.RecordFields.Any<KeyValuePair<Guid, RecordField>>((Func<KeyValuePair<Guid, RecordField>, bool>) (f => Cleanregex.Replace(f.Value.Field.Caption, "").ToLower() == name.ToLower())))
    {
      result = (object) this._record.RecordFields.First<KeyValuePair<Guid, RecordField>>((Func<KeyValuePair<Guid, RecordField>, bool>) (f => Cleanregex.Replace(f.Value.Field.Caption, "").ToLower() == name.ToLower())).Value.ValuesAsString(true);
      return true;
    }
    try
    {
      result = this._record.GetType().InvokeMember(binder.Name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.GetProperty, (Binder) null, (object) this._record, (object[]) null);
      return true;
    }
    catch (Exception ex)
    {
      LogHelper.Error<DynamicRecord>("", ex);
    }
    result = (object) null;
    return true;
  }
  result = (object) null;
  return true;
}
```

I suspect that the problem lies in the regular expression:

```
"[^a-zA-Z0-9 -]"
```
...Should probably not have a space in it...
```
"[^a-zA-Z0-9-]"
```

### Steps to reproduce

See "Reproduction" above.

### Expected result

If a field exists, I should be able to access its value by removing spaces from its name, as the documentation suggests.

### Actual result

Only fields that have a one-word name are accessible.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/237

**Comment by ThoughtProcess** [comment]
Hi guys!  I tried using this method against 7.1.0 this afternoon, but I'm still experiencing the bug using the same reproduction steps I reported above.  Can you guys confirm if you see the same on your end?  Thanks!

**Comment by bergmania** [comment]
@ThoughtProcess . Sadly this also looks to be rolled back in a merge 👎 

I have fixed again and built a new nightly for you:
http://nightly.umbraco.org/?container=umbraco-forms-nightlies

Name: `7.1.1-alpha-20190328-002`
