### ISSUE TITLE
Elements are not processed when using 'multiple choice' in combination with conditional logic

### ISSUE THREAD

**Issue by martijnbeumers** [umbraco/Umbraco.Forms.Issues#910]
When using a multiple choice (radiobuttons) in a form and conditional logic to render form elements, the values of those elements are not processed, causing empty values. The values are not stored in the DB or rendered in emails.  

![image](https://user-images.githubusercontent.com/30809240/201329820-c919c52d-370a-4a7f-8583-c2494c796a78.png)
![image](https://user-images.githubusercontent.com/30809240/201329849-3071ed9e-9ba6-4786-8d54-bba57ee41f89.png)

The value of element 'straatnaamNieuw' is not processed when submitting the form. So you cannot use it in a email or store it in the DB.

**Comment by AndyButland** [comment]
Thanks for reporting.  I think really here you should be using the "contains" option for the condition, as for a check box list, semantically really we are saying that to show the field we want the user to have selected one of the options from within the set.  But having said that, I still found a problem with how this was being validated.

We'll fix this for the next patch and then you should find "contains" works as expected.
