### ISSUE TITLE
When HoneyPot trap is sprung it still shows the success message/page

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Forms.Issues#911]
When testing recaptchav3 via a junkfiller, noticed the honeypot functionality was triggered, but this still processes the submit workflow (message or page) is shown (302 rather than a 200 status).

Is that the correct functionality (doesn't process any other workflows or save the submission in the entries) or should it report an error?

Perhaps the hope is that the bot moves on thinking it has done its work?

Also, I can't see that it logs the honeypot having caught its victim, which would be good to see if there is a problem with bots targeting the site?

**Comment by AndyButland** [comment]
I've checked over this and what you describe does look to be the intention of this feature - i.e. the form looks like it's been submitted, but actually hasn't.  A line written to the log would make sense, so we'll add this for the next releases.
