### ISSUE TITLE
Add api key support to forms api for ajax requests

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#915]
The new 10.2.0 release introduced a new api for working with the forms with ajax. It works, but I've run into a security issue because I'm sending the request between servers, which means I can't use the antiforgery token approach in the documentation (umbraco is being used as a headless cms in this case). It would be nice if I could use an api key instead for this use case, similar to what the heartcore version of umbraco forms does. I'm not using heartcore as the solution needs to integrate with the client's on premise setup and I have a lot of custom code that would likely need to be reworked to work with the heartcore apis.

**Comment by AndyButland** [comment]
This has been added for inclusion in the next release.  You'll have the ability to switch off the antiforgery token validation for API requests, and introduce an API key that needs to be provided in the header instead.  That should support these server-to-server integrations.

**Comment by jaandrews** [comment]
Sounds good. Will keep an eye out for the new release.

**Comment by andersonrosilva** [comment]
It worked, I did several tests but I had not changed this option. 
I looked at the documentation [here](url) and it says it should be set to **true** 

`Setting the value of EnableAntiForgeryTokenForFormsApi to true will disable the anti-forgery protection for the Forms Headless/AJAX API. You need to do this for server-to-server integrations where it's not possible to provide a valid anti-forgery token in the request.`

And in this other [link](url) it says to set it to **false**.

`Firstly, with server-to-server integrations you will want to disable the antiforgery token protection.
This is done by setting the Umbraco:Forms:Security:EnableAntiForgeryTokenForFormsApi configuration key to a value of false.
You should then configure an API key Umbraco:Forms:Security:FormsApiKey. This can be any string value, but shouldn't be easily guessable by a brute force attack.
With this in place any request to the Forms API will be rejected unless the configured value is provided in an HTTP header named Api-Key.`

Thanks.

**Comment by jaandrews** [comment]
@andersonrosilva Not sure where you saw the first one, as your links aren't pointing to the documentation (checked documentation for umbraco 10 and 11 and it's correct in both of them). The correct documentation for this api is the second one that is found [here](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms).

**Comment by andersonrosilva** [comment]
@jaandrews Oops, wrong formatting.
I edited the previous post.

**Comment by jaandrews** [comment]
@andersonrosilva Hmm, yeah that looks like a mistake in the documentation, as "enable" is the opposite of "disable."

**Comment by AndyButland** [comment]
> _"Setting the value of `EnableAntiForgeryTokenForFormsApi` to true will disable the anti-forgery protection"_  

Yes, this is incorrect... thanks for flagging and I'll get it fixed up.

**Comment by ProNotion** [comment]
Simply setting `EnableAntiForgeryTokenForFormsApi` to false does not seem to work for me in the latest v12 version. In order for it to work you also have to set `EnableAntiForgeryToken` to `false` but surely that would mean that the anti-forgery tokens are disabled on traditional  forms then?

**Comment by AndyButland** [comment]
That doesn't sound correct @ProNotion - I've just double checked on my local 12 site, and with these settings I'm getting back the API responses:

```
      "Options": {
        "EnableFormsApi": true,
      },
      "Security": {
        "FormsApiKey": "<my api key>",
        "EnableAntiForgeryToken": true,
        "EnableAntiForgeryTokenForFormsApi": false,
      }
```

**Comment by ProNotion** [comment]
Strange. I've tried again and it is now working. Perhaps I'd made a change to my config and not recycled the application for it to take effect. Thanks @AndyButland
