### ISSUE TITLE
Headless api returns an empty string for the "ShowLabel" setting of a field when it's left on by default.

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#916]
**Umbraco:** 10.3.2
**Umbraco Forms:** 10.2.0

When a new field is added to a form, the "ShowLabel" toggle is turned on by default if the field type supports it. This is not reflected in the data returned by the new [headless api](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/AjaxForms/) though, as it results in empty string instead of "True" or "False."

Reproduction
------------

1. Create a form.
2. Add a new short answer field to it, making sure not to modify the "Show Label" setting.
3. Retrieve the data with an ajax call to /umbraco/forms/api/v1.0/definitions/{id}?contentId={contentId}.
4. Check the data 

### Expected result
```json
{
    "id": "02e8afd7-22fd-470a-eabb-11f1c2339e5b",
    "caption": "Name",
    "helpText": "",
    "placeholder": "",
    "cssClass": null,
    "alias": "name",
    "required": true,
    "requiredErrorMessage": "Please provide a value for Name",
    "pattern": "",
    "patternInvalidErrorMessage": "Please provide a valid value for Name",
    "condition": {
        "actionType": 0,
        "logicType": 0,
        "rules": []
    },
    "preValues": [],
    "settings": {
        "DefaultValue": "",
        "Placeholder": "",
        "ShowLabel": "True", 
        "MaximumLength": "",
        "FieldType": "text",
        "AutocompleteAttribute": ""
    },
    "type": {
        "id": "3f92e01b-29e2-4a30-bf33-9df5580ed52c",
        "name": "Short answer"
    }
}
```

### Actual result

```json
{
    "id": "02e8afd7-22fd-470a-eabb-11f1c2339e5b",
    "caption": "Name",
    "helpText": "",
    "placeholder": "",
    "cssClass": null,
    "alias": "name",
    "required": true,
    "requiredErrorMessage": "Please provide a value for Name",
    "pattern": "",
    "patternInvalidErrorMessage": "Please provide a valid value for Name",
    "condition": {
        "actionType": 0,
        "logicType": 0,
        "rules": []
    },
    "preValues": [],
    "settings": {
        "DefaultValue": "",
        "Placeholder": "",
        "ShowLabel": "", 
        "MaximumLength": "",
        "FieldType": "text",
        "AutocompleteAttribute": ""
    },
    "type": {
        "id": "3f92e01b-29e2-4a30-bf33-9df5580ed52c",
        "name": "Short answer"
    }
}
```
"ShowLabel" is an empty string instead instead of "True," which is an issue because an empty string is treated as false in javascript.

This isn't hard to work around, as turning it off and back on sets the value, but user's won't know to do that unless they are aware this is an issue.

**Comment by AndyButland** [comment]
This will be resolved for the next patch release.  It's not so much an API issue, more that previously if saving a setting based on a check box, the value was only set if changed.  If not it kept it's default value of empty string.  So we've modified this to ensure an explicit "True" or "False" is saved.

That will only work for newly added fields - existing forms with an empty string saved in the definition will still have that until re-saved.

**Comment by jaandrews** [comment]
Sounds good. Will keep an eye out for the next release.
