### ISSUE TITLE
Umbraco Forms 8.13 doesn't work under authentication against azure B2C

### ISSUE THREAD

**Issue by antonio-nb** [umbraco/Umbraco.Forms.Issues#917]
Hi, we are using Azure B2C authentication for the frontend of our site and we work with User Claims to get the data of the user. 
This issue involve only the frontend. no backend or backoffice involved. the user are external users (logged with B2C)

The problem is that pages with Umbraco Forms which work before the login to Azure B2C stop working after the login.
The error we get:

Error loading partial view scripts (View: ~/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml)

-----------------
Umbraco Forms Version 8.13.4
-----------

**Comment by AndyButland** [comment]
Are you able to get any more detail on the error please?  I'd expect there should be something more in the logs.

**Comment by antonio-nb** [comment]
Hi. the issue seems the same as:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/721
https://github.com/umbraco/Umbraco.Forms.Issues/issues/253

as indicated in the issues #253. 
adding:
`var current = HttpContext.Current;
    if (current?.User?.Identity != null && current.User.Identity.IsAuthenticated)
    {   //Authenticated user
        var currentUser = current.User; 
	    HttpContext.Current.User = null; //temporary empty user object
        Html.RenderAction("RenderForm", "UmbracoForms", new { formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });
        HttpContext.Current.User = currentUser; // reset user object
    }`
to Views\MacroPartials\InsertUmbracoFormWithTheme.cshtml , the user authenticated can see the form. but when the user try to submit the form this is the error:


[InvalidOperationException: Sequence contains more than one matching element]
   System.Linq.Enumerable.SingleOrDefault(IEnumerable`1 source, Func`2 predicate) +370
   System.Web.Helpers.AntiXsrf.ClaimUidExtractor.GetUniqueIdentifierParameters(ClaimsIdentity claimsIdentity, String uniqueClaimTypeIdentifier) +405
   System.Web.Helpers.AntiXsrf.ClaimUidExtractor.ExtractClaimUid(IIdentity identity) +141
   System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken) +291
   System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext) +128
   Umbraco.Forms.Core.Attributes.ValidateFormsAntiForgeryTokenAttribute.OnAuthorization(AuthorizationContext filterContext) +186
   System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor) +168
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState) +1082
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +463
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +48
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +73
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +787
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +630
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +99
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +73
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +163
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +524
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +1128
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +40
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +155
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

**Comment by AndyButland** [comment]
I found [this reference](https://stackoverflow.com/questions/20614954/mvc5-antiforgerytoken-claims-sequence-contains-more-than-one-element) to the same problem, and some discussion on a solution, which is really related to ASP.NET MVC's antiforgery token validation rather than Umbraco Forms itself (as this just uses the framework's functionality for this).

That may help identify the issue with your implementation using Azure B2C.

**Comment by AndyButland** [comment]
We'll close this one now given there's not been further discussion following the suggestion above.
