### ISSUE TITLE
Send Email Workflow - Caption in Definition List

### ISSUE THREAD

**Issue by DrKirk84** [umbraco/Umbraco.Forms.Issues#919]
Hello

Since Version 10 of Umbraco Forms the captions for the field records used in the Send Email Workflow get's cleaned.
For Example "Full Error" will get "fullerror" in the Email. 
In Version 9 the Workflow and the caption get's not cleaned.

The issue is in ToXml(RecordField recordField, XmlDocument xmlDocument), the name for the xml tag will be used as caption instead of recordField.Field.Caption.

Another small issue is in the Umbraco.Forms.Core.Providers.WorkflowTypes.SendEmail.Execute(WorkflowExecutionContext context). There is no closing tag for the <dt>-Element, which produces invalid markup.

### Specifics

Umbraco Forms Version 10.2

### Steps to reproduce

- Create a empty form
- add a field with caption e.g. "Full Error"
- add the send email workflow
- add the form to a node and submit
- check emails and the caption

### Expected result

Caption for field in email should be "Full Error"

### Actual result

Caption for field in email should be "fullerror.

**Comment by AndyButland** [comment]
Thanks, I can replicate and see where this issue crept in.  Will resolve for the next patch release.

The invalid markup fix will also be included in the next patch releases of Forms 8 and 9.
