### ISSUE TITLE
'Umbraco.Forms.GridEditors.FormPickerController' is not registered in Umbraco 8 install

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Forms.Issues#92]
When trying to add a form to the Grid in Umbraco 8 the option via the macro works great.
But when using the 'forms' grid element it returns an empty block.
The console error is:  'Umbraco.Forms.GridEditors.FormPickerController' is not registered.

### Specifics

Fresh new Umbraco Cloud environment:
- Umbraco 8.0.0
- Forms 8.0.0

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/240

**Comment by sstottelaar** [comment]
> PR: [umbraco/Forms#240](https://github.com/umbraco/Forms/pull/240)

Any indication on when this will be released?

**Comment by bergmania** [comment]
@sstottelaar, Not today but probably one of the upcoming Tuesdays
