### ISSUE TITLE
Possibility validate the template of the form throught of the parent blocklist.

### ISSUE THREAD

**Issue by andersonrosilva** [umbraco/Umbraco.Forms.Issues#921]
I've a feature to build about the use with forms and sections. I'm feeling miss of the a way of bind a form with (blocklist) element to got a validation when used a template.

_I'll add many pictures in this request._

![image](https://user-images.githubusercontent.com/4675914/203171158-92358b21-900a-4167-80fc-8c1bb8759a02.png)

To this, I created a blocklist with elements. This elements has differents properties and one Form Picker.

![image](https://user-images.githubusercontent.com/4675914/203171452-045e329c-76fa-4954-882a-b0785d6e1504.png)

Each form has a field **captureType**, this field contains the value with the alias value from form.

![image](https://user-images.githubusercontent.com/4675914/203171851-b66627a6-62fa-48ee-80b3-a709729c9691.png)

I created template forms and I would like that this forms had in your settings the way to bind a element or other parent type.

![image](https://user-images.githubusercontent.com/4675914/203173392-ad658c3e-067a-47ad-9f64-787f9ad6c01a.png)

Form settings with hidden field.

![image](https://user-images.githubusercontent.com/4675914/203171926-951809ab-0ac1-4650-8c17-b7da9caec53c.png)

By the way, I got the validate type and form for the user doesn't use wrong types.

![image](https://user-images.githubusercontent.com/4675914/203172367-68439b58-d5c0-4dc5-a7b1-deddff8e1d7f.png)
Error on image above: **formSimple (form)**

My question and suggestion for new versions is.

Already exists a way the validate this types at Umbraco? If not, it's possible add in news versions? Today, I can validate using event handlers when saving content.

I hope that got help someone.

PS.: I Don't to go paste the code of the my Handler right now, but I can share the who interest.

**Comment by AndyButland** [comment]
Sorry we haven't got back to you earlier on this @andersonrosilva, but we're doing a review of pending issues at the moment and I haven't been able to follow what the request is here.  Would you be able to try to explain again please?  If there's actually more than one thing you are raising here, it would be useful to break them off into separate issues.

**Comment by andersonrosilva** [comment]
@AndyButland Thanks.

I already resolved with other way.

:)

**Comment by AndyButland** [comment]
OK, will close this issue then.
