### ISSUE TITLE
How to upload a file with the headless API?

### ISSUE THREAD

**Issue by karlmacklin** [umbraco/Umbraco.Forms.Issues#922]
As title asks - can we see an example on how to upload a file using the headless API?

We are trying to do this, but we're unsure on how to format/encode files and send via JSON requests.

**Comment by karlmacklin** [comment]
We have tried the standard json approach and for the file upload field we have tried sending base64 encoded strings, but no luck.

We get stuck on some form of encryption-step:

```
"type": "https://httpstatuses.io/500",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "The provided payload cannot be decrypted because it was not protected with this protection provider. For more information go to http://aka.ms/dataprotectionwarning",
    "exceptionDetails": [
        {
            "message": "The provided payload cannot be decrypted because it was not protected with this protection provider. For more information go to http://aka.ms/dataprotectionwarning",
            "type": "System.Security.Cryptography.CryptographicException",


[... stacktrace here]
```

**Comment by AndyButland** [comment]
This will be possible with the next update by sending a base64 encoded string. [This page](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms) of the documentation will be updated with the details, as will the example vanilla js gist linked from that page.
