### ISSUE TITLE
Default field types missing the "Show Label" setting

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#925]
The following default field types are missing the Show Label option (at least in Forms 10.1.3). Can we get that setting on these?

- Date Picker
- Checkbox
- File Upload
- Password
- Hidden Field
- reCAPTCHA v2
- reCAPTCHA v3

**Comment by AndyButland** [comment]
We've added this option now to all of the above other than the two that are invisible fields - Hidden Field and reCATCHA v3 - just as for those I can't see there would be a reason why you'd want to turn the label on and hence we can have just a fixed behaviour of hiding the label on those.  Due in the next feature release.
