### ISSUE TITLE
Conditional rules don't work on Groups.

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco.Forms.Issues#929]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When using conditional rules on forms, they seem to work fine for individual questions but the rules don't work when you try and apply them to groups.

### Specifics

We are running Forms 10.2 and this applies to all browsers. 

### Steps to reproduce
- Create a new form and add a "single choice" question to the form and add options "yes" and "no" 
- Add a new question and set a conditional rule that this question is shown when previous question is "yes".
- The new question will display as expected.
![workingCondition](https://user-images.githubusercontent.com/9438758/204306437-8677033f-d72e-4614-85b6-040b096b1901.gif)

- Now create a new group and add a question in this group e.g. "long answer". 
- Set a conditional rule on this entire group and make it show only when the question is answered "yes" (remove the conditional rule on the previous question.

![image](https://user-images.githubusercontent.com/9438758/204306008-58b9370d-573c-4fc3-8c0d-a75d1d0206fb.png)

The rule is completely ignored, it shows the group even if the answer hasn't been selected. 
It only seems to be an issue with groups. 

### Expected result

I would expect the group to be hidden until the correct conditional rule is met.

### Actual result

The conditional rule on the group isn't applied.

**Comment by OwainWilliams** [comment]
Hi, 
Is there any work around for this just now? I have a client that is having this issue. Thanks :)

O.

**Comment by AndyButland** [comment]
It's noted @OwainWilliams... we've scheduled looking into this issue for the current sprint (starting today), so hopefully we'll get to figuring out what's going on here.

**Comment by OwainWilliams** [comment]
Amazing. Thanks @AndyButland

**Comment by AndyButland** [comment]
Hi @OwainWilliams - I'm having trouble replicating this I'm afraid.

I've created a test form which you could replicate into your instance with the following SQL.

```
declare @formId uniqueidentifier
set @formId = NEWID()

insert into UFForms([Key],Name,Definition,Created,Updated)
values (
  @formId,
  '929 Test',
  '{"name":"929 Test","pages":[{"fieldSets":[{"caption":"Group One","sortOrder":0,"id":"ea82fbbd-6440-4cba-8782-4027263a9e42","page":"00000000-0000-0000-0000-000000000000","containers":[{"caption":null,"width":12,"fields":[{"caption":"Select","tooltip":null,"placeholder":null,"cssClass":null,"alias":"select","id":"203ba8b0-c3e6-4ad4-e4bd-b0dfe099ff05","fieldTypeId":"903df9b0-a78c-11de-9fc1-db7a56d89593","prevalueSourceId":"00000000-0000-0000-0000-000000000000","dataSourceFieldKey":null,"containsSensitiveData":false,"mandatory":false,"regex":null,"requiredErrorMessage":null,"invalidErrorMessage":null,"condition":{"id":"e3b158b9-fe86-4734-b82e-475b77c1e876","enabled":false,"actionType":"Show","logicType":"All","rules":[]},"settings":{"DefaultValue":"","ShowLabel":""},"preValues":["yes","no"],"parsedPreValues":[{"value":"yes","caption":null},{"value":"no","caption":null}],"allowedUploadTypes":null,"allowMultipleFileUploads":true},{"caption":"Test 1","tooltip":null,"placeholder":null,"cssClass":null,"alias":"test1","id":"a9fdfdc8-49d0-450b-b3fb-04b4b888a81f","fieldTypeId":"3f92e01b-29e2-4a30-bf33-9df5580ed52c","prevalueSourceId":"00000000-0000-0000-0000-000000000000","dataSourceFieldKey":null,"containsSensitiveData":false,"mandatory":false,"regex":null,"requiredErrorMessage":null,"invalidErrorMessage":null,"condition":{"id":"854d9164-b43c-4853-8017-3760c1929b43","enabled":true,"actionType":"Show","logicType":"All","rules":[{"id":"00000000-0000-0000-0000-000000000000","field":"203ba8b0-c3e6-4ad4-e4bd-b0dfe099ff05","operator":"Is","value":"yes"}]},"settings":{"DefaultValue":"","Placeholder":"","AutocompleteAttribute":"","ShowLabel":"","MaximumLength":"","FieldType":""},"preValues":[],"parsedPreValues":[],"allowedUploadTypes":null,"allowMultipleFileUploads":true}]}],"condition":null},{"caption":"Group Two","sortOrder":0,"id":"85ffc6ee-7db7-420f-a004-e04a50dcf97d","page":"00000000-0000-0000-0000-000000000000","containers":[{"caption":"","width":12,"fields":[{"caption":"Test 2","tooltip":null,"placeholder":null,"cssClass":null,"alias":"test2","id":"608ee3a8-6681-4069-b8b5-29449454ecba","fieldTypeId":"3f92e01b-29e2-4a30-bf33-9df5580ed52c","prevalueSourceId":"00000000-0000-0000-0000-000000000000","dataSourceFieldKey":null,"containsSensitiveData":false,"mandatory":false,"regex":null,"requiredErrorMessage":null,"invalidErrorMessage":null,"condition":{"id":"e40606c0-a916-4e8f-ae5e-e3d1bef19a4c","enabled":false,"actionType":"Show","logicType":"All","rules":[]},"settings":{"DefaultValue":"","Placeholder":"","AutocompleteAttribute":"","ShowLabel":"","MaximumLength":"","FieldType":""},"preValues":[],"parsedPreValues":[],"allowedUploadTypes":null,"allowMultipleFileUploads":true}]}],"condition":{"id":"69dc16fe-144e-49e1-b384-d3d4e4908c38","enabled":true,"actionType":"Show","logicType":"All","rules":[{"id":"00000000-0000-0000-0000-000000000000","field":"203ba8b0-c3e6-4ad4-e4bd-b0dfe099ff05","operator":"Is","value":"yes"}]}}],"caption":null,"sortOrder":0,"id":"6d81a483-cbcb-45bc-9c94-f4d1067e1abb","form":"00000000-0000-0000-0000-000000000000","buttonCondition":null}],"fieldIndicationType":"MarkMandatoryFields","indicator":"*","showValidationSummary":false,"hideFieldValidation":false,"requiredErrorMessage":"Please provide a value for {0}","invalidErrorMessage":"Please provide a valid value for {0}","messageOnSubmit":"Thank you","goToPageOnSubmit":0,"xPathOnSubmit":null,"manualApproval":false,"storeRecordsLocally":true,"autocompleteAttribute":"","cssClass":null,"disableDefaultStylesheet":false,"useClientDependency":false,"workflows":null,"datasource":null,"submitLabel":"Submit","nextLabel":"Next","prevLabel":"Previous","folderId":null,"Id":405,"Key":"83b6fcb5-ea5e-496e-b08b-0b817b61bbe4","CreateDate":"2022-12-06T07:34:18.123Z","UpdateDate":"2022-12-06T07:35:19.7647699+01:00","DeleteDate":null,"HasIdentity":true}',
  GetDate(),
  GetDate())
```

Would you mind giving that a try please, and see if you still see the issue?

If you don't then, we need to try to spot what the significant difference is between my test and yours.

And if you don't, then it's something installation specific.  Perhaps related to a custom theme if you have one?  If so, would be worth checking with the default theme just to see if it works with that.

**Comment by OwainWilliams** [comment]
Hi @AndyButland - this is awkward, sorry to have wasted your time. It looks like we do have a custom template running on this and the ids / classes required for conditional behaviors to work have been missed out of our version. 
I should have checked this before reporting it as a "bug".

**Comment by AndyButland** [comment]
No problem @OwainWilliams, thanks for letting me know.  I'll close this then, as hopefully you'll have this working once you apply the same attributes from the default them into your custom one.
