### ISSUE TITLE
Location of selected go to/thankyou page isn't visible

### ISSUE THREAD

**Issue by robbintendolle** [umbraco/Umbraco.Forms.Issues#931]
When selecting a Go to page in Umbraco Forms it's not visible what the exact location/slug is of the selected page. Due to that it's hard to check if the selected Go to page is the right one.

![image](https://user-images.githubusercontent.com/119611109/205093376-010ab568-2c42-4f6c-b22a-59a5091bda0e.png)

**Comment by robbintendolle** [comment]
@ronaldbarendse is the ticket already done? Since you completed the task.

**Comment by ronaldbarendse** [comment]
> @ronaldbarendse is the ticket already done? Since you completed the task.

We've indeed implemented a fix for version 8 and up that will be included in the next release of Forms :+1: 

Below the name, you'll get a small description text containing the URL (for published content) or a path (of parent content names, if unpublished), similar to other content pickers in the CMS.
