### ISSUE TITLE
CSS Validation Errors (Umbraco.Forms v 9.5.4)

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#932]
I have been checking all .css files in my site's App_Plugins folder because of the back-office Smidge failure issue (https://github.com/umbraco/Umbraco-CMS/issues/11374)

To check, I use [The W3C CSS Validation Service](https://jigsaw.w3.org/css-validator/)

And got this error report for the file "\App_Plugins\UmbracoForms\css\umbraco.forms.css" (Umbraco.Forms v 9.5.4)
![image](https://user-images.githubusercontent.com/1252593/205129994-ce1177d9-d742-4b89-88df-d84b56fa4b18.png)

Additionally, an error reported on "\App_Plugins\UmbracoForms\Assets\pikaday\pikaday.css":
![image](https://user-images.githubusercontent.com/1252593/205135446-58b8d1bc-2ca1-4512-b6d6-58689773130c.png)

**Comment by AndyButland** [comment]
Thanks - these will be resolved in the next patch updates.

**Comment by hfloyd** [comment]
Great! (Btw - these errors weren't causing the back-office smidge issue, but I figured I'd point them out anyway). ❤
