### ISSUE TITLE
Umbraco Forms deletes entire media folder when storing incorrect data when data type is File Upload

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#933]
Saving Umbraco Forms records programatically, when the form has a property of type File Upload, if an incorrect value is stored, when deleting a record causes deleting the entire media folder.
This bug was discovered when fixing this issue:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/930

If no upload is selected what is coming is an empty object of FileList in javascript from the client.
As no upload is found, it is storing the string "[object FileList]" in the FileUpload field, i have fixed it storing null instead.

The bug is that if storing "[object FileList]" in the fileupload field, if you view the record in Umbraco Forms entries, the field is blank and if you delete the record, i dont know why the entire "media" folder is deleted.
So i guess the bug is that if an incorrect value is stored in the FileUpload field, deleting the record, may cause delete the entire media folder.

**Comment by AndyButland** [comment]
Thanks for reporting.  We'll have a fix to prevent this occurring with the next set of patch releases.
