### ISSUE TITLE
Form usage information

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco.Forms.Issues#937]
It would be great to get form usage information like we have for content and media:

![image](https://user-images.githubusercontent.com/3933562/207333658-eeae18e7-4f03-402b-a883-03af6365a734.png)

This would allow identify quickly if it's safe to change/remove form or to findcontext that it's used in.

---
_This item has been added to our backlog [AB#32363](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32363)_

**Comment by AndyButland** [comment]
We'll have this feature included in the next minor release of Form.  It's modelled on what you see under "Media" in Umbraco, so there'll be an "Info" tab with some general information about the form, along with any tracked content items that the form is used on:

![form-info](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/eef4d9bb-7e11-4be2-8149-a41ec13c030b)

![form-info-general](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/d3440f61-eccf-45a2-b42e-003b1e687ef0)

![form-info-relations](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/ad8b35ee-e837-44b6-820e-411697665a82)

**Comment by richarth** [comment]
Thanks Andy. That's going to be a huge help.

**Comment by kdx-perbol** [comment]
Using Umbraco Forms 12.2, on subsequent saves of a content item with a form in a form picker in a property, I get this error:

**Cannot insert duplicate key row in object 'dbo.umbracoRelation' with unique index 'IX_umbracoRelation_parentChildType'.** 

I have an element type ("composition") with a form picker property, and a document type using the composition.

Incidentally, after upgrading to 12.2, I got "relation type umbForm does not exist" until several application restarts and upgrading to Umbraco 12.3.4 (in development).
