### ISSUE TITLE
Form Entries selection checkbox does not update state correctly

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco.Forms.Issues#94]
I have installed Umbraco Forms on a new Umbraco 8 + Starter Site installation via NuGet and after enabling it in the theme I also changed the default Contact Form settings to "Enable Post Moderation".

I then went to the contact page and submitted a new entry before going back to the form Entries list and attempted to approve it.

When I select the entry directly I see the Delete and Approve actions appear replacing the filter and Export action; but when I try to use the checkbox above the list to select the items nothing happens until I clear the checkbox again.

Screenshot 1: checkbox checked:
![image](https://user-images.githubusercontent.com/818101/53507993-abd0b300-3b04-11e9-8743-05efe1c138ae.png)

Screenshot 2: checkbox cleared:
![image](https://user-images.githubusercontent.com/818101/53508053-c571fa80-3b04-11e9-9f9b-a6fd037a44e4.png)

I would expect the reverse action on the checkbox - all entries selected/highlighted when the checkbox is checked, and cleared when it's cleared.

Versions: Umbraco 8.0 and Forms 8.0

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Forms/pull/245

**Comment by bergmania** [comment]
Hi @robertjf,
Thanks for reporting. I have created a fix for that.

**Comment by warrenbuckley** [comment]
Merged in
