### ISSUE TITLE
Large number of forms causes main Umbraco Search and Umbraco Forms section to become very slow (Umbraco and Forms v10)

### ISSUE THREAD

**Issue by sean-p-m** [umbraco/Umbraco.Forms.Issues#940]
**We've noticed that:**

* the main Umbraco search (magnifying class) is taking around 10 seconds to run, e.g. /umbraco/backoffice/umbracoapi/entity/SearchAll?query=xxx
* individual forms are very slow to load (form designer), e.g. /umbraco#/forms/Form/edit/xxx
* the form security screen for individual users also takes about 10 seconds to run, e.g. umbraco#/users/FormSecurity/edit/user-xx

We have a 152 forms on the site with an average of 13 fields. The problem is not affected by the number of form submissions, solely the number of forms.

**How do we know this is Umbraco Forms related?**

I uninstalled Umbraco Forms and the problem disappeared. I re-installed Umbraco Forms and the problem was still gone. I imported the forms back into the database (without the submissions) and the problem re-occurred. I repeated this in three environments.

I managed to locate the code that runs when a search is performed in FormTreeController.SearchAsync() and run it in isolation:

`     var results = _formService.Get().Where(f => f.Name.Contains("test") || f.AllFields.Any(f => f.Caption.Contains("test"))).ToList();`

This line of code takes about 10 seconds to run. It seems to pull down the JSON for all forms, deserialize and then search, which runs very slowly.

Reproduction
------------

Umbraco version: 10.3.2
Umbraco Forms version: 10.2.0

1. Install a clean version of Umbraco 10.3.2 with Umbraco Forms 10.2
2. Create a form with 13 fields.
3. Copy that form ~150 times, either through the UI or just copying the in database triggers the issue too
4. Observe the speed of the main Umbraco search, User Form Security sheet, clicking into a form to design it

### Expected result

I expect no delay search performing a site search, loading a form, editing user form security.

### Actual result

Performing a search / editing user form security takes about 10 seconds.

**Comment by AndyButland** [comment]
We'll have an update in the next patches that optimizes the search routine here.  It seems that since the introduction of storing form definitions in the database it's not been sufficiently performant.
