### ISSUE TITLE
Magic strings are not resolved in "Send form to URL" workflow

### ISSUE THREAD

**Issue by GertKnuts** [umbraco/Umbraco.Forms.Issues#948]
I am currently experiencing an issue with the "Send form to URL" workflow in Umbraco Forms, where magic strings are not being replaced when used in the fields mapping. When the form is submitted, the magic strings are being sent to the URL as-is, instead of being replaced with the actual values from the form submission.

Steps:
Umbraco: 10.3.2
Forms: 10.2.1

1. Create a form
2. Add a new workflow of type "Send form to URL"
3. In the "Send form to URL" settings, add a valid URL (e.g. Postman mock server) and set the method to "POST"
4. In the fields section of the "Send form to URL" settings, add a mapping with alias: "name", form value: blank and static value "[#pageName]"
5. Place the form on a page and submit the form from the front-end

The result is a POST to the URL with name "[#pageName]" instead of the name of the containing page.

This problem did not occur in Forms version 10.1.3

**Comment by AndyButland** [comment]
Thanks for the report @GertKnuts.  Looks like we've missed a case here when we introduced the magic string formatters and tried to make that work with JSON values held in workflow settings.  I've made a fix that will restore the behaviour you had before, due in an upcoming patch release.
