### ISSUE TITLE
Custom Export Type causes null reference exception

### ISSUE THREAD

**Issue by tony-gledhill** [umbraco/Umbraco.Forms.Issues#949]
A custom export type causes a null reference exception when being used to download from the entries table. The user will experience a infinite spinner as the code has crashed silently. 

Initially I thought the error could be down to a custom property on a form, so I created a blank CMS instance with Umbraco forms installed. Within the instance, I created a single form with a short field property. When The data as downloaded, the null reference was still thrown. 

The data can be successfully extracted from the formRecordSearcher and has a full list of properties and data. 

        public override string ExportRecords(RecordExportFilter filter)
        {
            var view = "~/Views/Partials/Forms/Export/html-report.cshtml";
            EntrySearchResultCollection model = _formRecordSearcher.QueryDataBase(filter);
            return ViewHelper.RenderPartialViewToString(view, model);
        }

The exception is thrown on `ViewHelper.RenderPartialViewToString`

Recreation steps - Tested in 10.3.1 and 11

- Create a blank installation of Umbraco
- Install Umbraco forms
- Create a new export type from the [documentation example ](https://docs.umbraco.com/umbraco-forms/developer/extending/adding-a-exporttype)
- Create a blank form with one field
- Create a document type with a template that can display the form
- Submit data to the form
- View the entry has been submitted to the form
- Click export in the top right corner of the entries page
- Click on custom download option

**Comment by AndyButland** [comment]
Hi @tony-gledhill - I've had a look at this, and you're right, this isn't working correctly.  It's partly due to the documentation not being fully up to date, but there's also a bug that prevents this from working as it should.  We have a fix ready for review and will make sure to resolve this for the next patch release.

**Comment by tony-gledhill** [comment]
Hi @AndyButland - Thanks for the update and putting the fix in! 👍
