### ISSUE TITLE
V11 recCAPTCHA3 score 

### ISSUE THREAD

**Issue by jonas-jaderberg** [umbraco/Umbraco.Forms.Issues#955]
In V11 it's not possible to change the score in reCAPTCHA3 field. 
To reproduce the problem 
1. Add a reCAPTCHA3 field to a form
2. For me the default score is 0.5
3. Submit
4. Save the form
5. Configure the reCAPTCH field, set score to 0.8
6. Submit and save the form
7. Refresh/reload the form
8. Configure the reCAPTCHA field
9. Now the score is 0.5 again

I have this problem on two sites.

**Comment by AndyButland** [comment]
Thanks for letting us now.  I can replicate this and we'll get a fix out in the next patch release.
