### ISSUE TITLE
Allowed forms not responding when configuring Form Picker

### ISSUE THREAD

**Issue by ThomasAdams2** [umbraco/Umbraco.Forms.Issues#957]
Using Umbraco `11.1.0` and Forms `11.0.1`, when configuring a Form Picker datatype the add allowed forms button does not do anything.

![image](https://user-images.githubusercontent.com/34098429/213488852-b3ecb3d4-dd2a-410d-ac13-06d9ebbc48a4.png)

Testing this with Umbraco `11.1.0` and Forms `11.0.0` the add Allowed forms button opens an overlay as expected.

So it appears this was introduced in Forms `11.0.1`

**Comment by AndyButland** [comment]
Thanks for letting us know, and you're right, this has come about with the changes for 11.0.1.  We'll get them fixed for the next patch update.
