### ISSUE TITLE
The "Include Sensitive Data" toggle defaults to "false" when opening a workflow for the second time

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [umbraco/Umbraco.Forms.Issues#958]
I am using Umbraco 10.4.0 with Umbraco Forms 10.2.2. When adding the 'Send email' or 'Send email with template (Razor)' workflow, the 'Include Sensitive Data' toggle is acting strange. The first time when setting this toggle to 'true' and submitting the workflow, and saving the form is working correctly. However opening a workflow for the second time will affect the toggle to the default 'false' value. Also whenever you open a workflow for the second time, and NOT submit the changes, but save the form, the toggle has been saved as the value: 'false'. This behaviour is not how you would expect the workflow settings to work.

Reproduction
------------

1. Clean install Umbraco 10.4.0, and clean install Umbraco Forms 10.2.2
2. Create a form (blank or snippet doesn't matter)
3. Create the Send email workflow with the required fields, and set the 'Include Sensitive Data' toggle to 'true'
4. Submit the workflow, and save the form
5. Click on the workflow (the 'Include Sensitive Data' toggle should be set to 'true')
6. Click on the workflow again, the 'Include Sensitive Data' toggle should be set to 'false'

This also occurs on different version of Umbraco, and Umbraco Forms, and using a different browser should not matter.

Expected behaviour
------------

The 'Include Sensitive Data' toggle should always fetch the correct value from the database, no matter how often the workflow dialog is opened.

**Comment by AndyButland** [comment]
Thanks for the clear report.  I can replicate and see why this is happening, so we'll have a fix for this for the next release.  Looks like it's been an issue back to Forms 8, so we'll patch back to there.
