### ISSUE TITLE
Validation error when editing form entry with checkbox list

### ISSUE THREAD

**Issue by tenshi04** [umbraco/Umbraco.Forms.Issues#960]
A brief description of the issue goes here.

When going to the backoffice to edit a form entry that contains a checkbox list, a validation error occurs when trying to save the entry, even if no edits were done. This error should not be displayed.

Reproduction
------------

### Bug summary

The validation is not working correctly and is displaying the message below. 
ERROR Message: Unexpected value: 'Value 1, Value 4'. Expected one of these: 'Value 1', 'Value 2', 'Value 3', 'Value 4'

### Specifics

Umbraco 8.18.5
Umbraco Forms 8.13.5

### Steps to reproduce

1. Create a new form
2. Add a new question using a Multiple Choice control. 
3. Add some prevalues to the control ex) Value 1, Value 2, Value 3, Value 4
4. Save the form
5. View the form on an umbraco page and select a few values (ex. Value 1 and Value 3) from the checkbox list (multiple choice control)
6. Submit the form
7. Login to the back office, go to the form and view the entries. Edit the entry that was just submitted.
8. Do not do any edits, but just click save.
9. A validation error will be displayed.

![image](https://user-images.githubusercontent.com/6784842/214450414-2a5402ef-cdd1-4c0a-98b9-dffc43589602.png)

10. ERROR Message: Unexpected value: 'Value 1, Value 4'. Expected one of these: 'Value 1', 'Value 2', 'Value 3', 'Value 4'

### Expected result

The entry should save without issue as the values are valid.

### Actual result

The validation is not working correctly and is displaying the message below. 
ERROR Message: Unexpected value: 'Value 1, Value 4'. Expected one of these: 'Value 1', 'Value 2', 'Value 3', 'Value 4'

**Comment by AndyButland** [comment]
Thanks for reporting this issue.  We can replicate and have found a fix, which will be released in the next patch updates.
