### ISSUE TITLE
Wrong path to static assets on 10.2.2 and 11.0.1

### ISSUE THREAD

**Issue by PezCo** [umbraco/Umbraco.Forms.Issues#962]
The path for the static assets in the Forms backoffice is wrong causing forms to not load there.

e.g https://localhost:44327/App_Plugins/UmbracoForms/Backoffice/Form/views/settings/settings.html
should be https://localhost:44327/App_Plugins/UmbracoForms/backoffice/Form/views/settings/settings.html

lower case b in **_backoffice_** is the correct URL.
Reverting 1 patch version down too 10.2.1 or 11.0.0 fixes this error.

Reproduction
------------

### Specifics

Running on Mac Os 13.1
using vs code so i imagine its using Kestrel as the server?

### Steps to reproduce

I had existing forms in v8 that upgraded to v9 then v10.
but i imagine it would error on a fresh install with empty data just the same

### Actual result
getting 404 error for static assets used to render umbraco forms in back end e.g

```
Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/Backoffice/Form/views/design/design.html
```

**Comment by AndyButland** [comment]
Thanks for reporting.  It looks like we have a regression here, coming in when preparing the last release and merging updates from Forms 8 and up.  I've resolved, and we'll get this updated in the next patch releases.
