### ISSUE TITLE
Forms (11.0.1): not able to locate backoffice templates after install on Mac OS

### ISSUE THREAD

**Issue by Alion** [umbraco/Umbraco.Forms.Issues#964]
Reproduction
------------

### Bug summary

After doing a clean install of Umbraco (11.1.0) on Mac OS and doing an install of Forms (11.0.1) using dotnet cli or Nuget cli Forms is unable to find the backoffice templates:

Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/Backoffice/Form/views/design/design.html

Otherwise Forms seems to install fine, as far as i can see the only thing is the missing

### Specifics

Umbraco v11.1.0
Forms 11.0.1
Mac OS Big Sur 11.6.8
VS 2022 v17.4.3 (build 21) 
Url: https://localhost:44331/umbraco#/forms
![Screenshot 2023-01-26 at 14 40 08](https://user-images.githubusercontent.com/1685005/214849997-3ccfc31d-fa2b-43c3-97a8-bc293230f84b.png)
![Screenshot 2023-01-26 at 14 39 39](https://user-images.githubusercontent.com/1685005/214850013-6d558c33-ea7f-4320-9c09-43dfa3219ec6.png)

### Steps to reproduce

1. Install a clean Umbraco (11.1.0) on Mac Os (Catelina)
2. Build and run from VS 2022
3. Install Umbraco.Forms using dotnet cli or nuget cli following Umbraco instructions
4. Run umbraco
5. Log in to backoffice
6. go to forms tab and Create form
7. Form gets created
8. Error: "Request error: The URL returned a 404 (not found):
"/App_Plugins/UmbracoForms/Backoffice/Form/views/design/design.html"

### Expected result

Expected to be able to edit content and settings for the newly created form.

### Actual result

Error: "Request error: The URL returned a 404 (not found):
"/App_Plugins/UmbracoForms/Backoffice/Form/views/design/design.html"

**Comment by Alion** [comment]
Sebastiaan confirmed the issue in the Forms channel on Umbraco discord

**Comment by AndyButland** [comment]
Thanks for reporting... we are aware of this one, and are tracking via [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/962) that was reported earlier.
