### ISSUE TITLE
Form Design and Settings screens inaccessible after upgrade to 11.0.1

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco.Forms.Issues#965]
Upgrading Umbraco Forms from 11.0 to 11.0.1 causes a red 404 error warning to be displayed.

On an Umbraco 11.1.0 site upgrading Umbraco Forms from 11.0 to 11.0.1 causes a red 404 error warning to be displayed in the back office when trying to access the form designer or form settings screens.  This is on a Linux Mint dev platform but it has also been reported in the Discord channel as being the case on a Mac but ok on Windows.

Reproduction
------------
On a Linux (or maybe even a Mac) open an Umbraco V11.1 site with UF 11.0 installed and upgrade UF to 11.0.1. Log into the back office and attempt to view or create a form.

### Expected result
View the form designer and settings as normal

### Actual result
A read warning bar stating:

Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/Backoffice/Form/views/design/design.html

And 

Request error: The URL returned a 404 (not found):
/App_Plugins/UmbracoForms/Backoffice/Form/views/settings/settings.html

Attempting to downgrade the installation back to UF 11.0 doesn't fix the issue.

**Comment by AndyButland** [comment]
Hi @craigs100 - yes, sorry about this one, but we're [aware of it](https://github.com/umbraco/Umbraco.Forms.Issues/issues/962).  Something went awry merging up some changes to earlier versions for this patch.  We're preparing a new one that'll be available next week.

**Comment by craigs100** [comment]
Thanks Andy. Stupidly I upgraded 2 sites at once. Downgrading doesn't help unless there's something I can do to force it to downgrade properly?

**Comment by AndyButland** [comment]
You should be fine to go back to Forms 11.0.0.  Might need to clean and build, and [make sure the back-office isn't caching anything](https://www.andybutland.dev/2022/09/backoffice-cache-busting-with-umbraco.html).

**Comment by craigs100** [comment]
Thanks for that. For Dev I have minification version change on timestamp which I'm not convinced works very well. However, changing to Version number, as you suggest in the article, has sorted it, so panic over :)
