### ISSUE TITLE
Field won't span all columns

### ISSUE THREAD

**Issue by Trobeloo** [umbraco/Umbraco.Forms.Issues#968]
I have a form that begins with a two column group. I have created another group with only one column and a long answer field. 
Unfortunately the field is restricted to the same width of the previous field and don't occupy all form width.

**Comment by Trobeloo** [comment]
If it is a bug will it be fixed?

**Comment by AndyButland** [comment]
Thanks for the nudge on this one.  I just tried to replicate though - on latest Forms 10 - and don't immediately see the problem.  I've set up a form as described and can see the mark-up looks as expected:

![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/1993459/d1925797-0592-45af-83a2-c43fc901b847)

The `col-md-6` and `col-md-12` classes should give you the styling hooks to render this layout as you'd expect.

So I'll close, but please re-open and let me know if I've missed something.
