### ISSUE TITLE
Magic strings parsing member properties are not resolved in "Send form to URL" workflow

### ISSUE THREAD

**Issue by GertKnuts** [umbraco/Umbraco.Forms.Issues#969]
I am currently experiencing an issue with the "Send form to URL" workflow in Umbraco Forms, where magic strings parsing member properties are not being replaced when used in the fields mapping. When the form is submitted, the magic strings are being sent to the URL as-is, instead of being replaced with the actual values.

Steps:
Umbraco: 10.3.2
Forms: 10.2.3

1. Create a form
2. Add a new workflow of type "Send form to URL"
3. In the "Send form to URL" settings, add a valid URL (e.g. Postman mock server) and set the method to "POST"
4. In the fields section of the "Send form to URL" settings, add a mapping with alias: "email", form value: blank and static value "{member.email}"
5. Place the form on a secure page and, after login, submit the form from the front-end
6. The result is a POST to the URL with email "{member.email}" instead of the email of the logged in user

This problem did not occur in Forms version 10.1.3

**Comment by AndyButland** [comment]
This should be sorted with the next release.  We've had a couple of related issues here incurred having introduced "formatters" for the magic strings.  I've found a way now to not have this interfere with the use of the strings within complex settings types, like the one used here for mapping fields.  The one downside is that the formatters aren't supported with these types, but we can at least ensure the unformatted strings people have been using for a while continue to work.

I'll mark this to be included in the next patch release, but, depending on timings, it might just get rolled up into the next minor.
