### ISSUE TITLE
Conditinally displayed form group is initially visible

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco.Forms.Issues#970]
Display bug when a form has conditional display for a form group set.
Forms v10.2.1

### Bug summary
There is no initial display: none style set in form.cshtml for form groups. When loading the page, the group and all questions in it will 'flash' shortly before being hidden by scripting.  

### Steps to reproduce

- Create a group on a form and set it to show/hide based on a previous answer.
- Add the form to a page ensuring it is at the very top and visible without scrolling.
- Load the page and withnes a 'flash' before the questions are hidden.

### Expected result

The page and contained form load with an initial state for the group of either being visible or not.

### Actual result

A notible 'flash' of the content being hidden is seen

**Comment by niekvanderreest** [comment]
I've fixed the issue on a custom theme by adding a style="display:none" tag based on show condition.
This change is made in the view Form.cshtml at line: 36 (ish), see attached screenshot.

![image](https://user-images.githubusercontent.com/28493458/217579309-1140f29d-aa5c-44d3-857a-8700391639b2.png)


The logic is a copy paste from the same Form.cshtml on line: 52 (ish), where it is used to set initiall hidden state on individual questions.

**Comment by AndyButland** [comment]
Thanks for the report @niekvanderreest (and the fix!).  Looks quite correct what you have done to me, and seems we've just missed applying this initial visibility to the fieldsets as we have done with fields.

Your fix will be applied to the default theme from the next release.

I'll mark this to be included in the next patch release, but, depending on timings, it might just get rolled up into the next minor.
