### ISSUE TITLE
Unable to create folders in Umbraco Forms

### ISSUE THREAD

**Issue by tenshi04** [umbraco/Umbraco.Forms.Issues#971]
A brief description of the issue goes here.

In previous versions of Umbraco Forms, I was able to create folders to organize forms. 
I am using Umbraco Forms 8.13.5 and Umbraco 8.18.5

I can no longer create a folder in Forms section of Umbraco.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

There is no ability to create folders in Umbraco forms. I was able to do this in earlier versions of Forms (8.8.0)

### Specifics

Umbraco Forms 8.13.5 and Umbraco 8.18.5

### Steps to reproduce

1. Go to the Forms section in Umbraco
2. Right click on the ... next to the Forms root folder
3. There is no option to create a folder (even though the title says otherwise)
![image](https://user-images.githubusercontent.com/6784842/217667432-4343880e-6bc1-4c71-8546-aca823b6ddbd.png)

### Expected result

Folders should be able to be created to organize forms

### Actual result

There is no menu option to create a new folder.

**Comment by AndyButland** [comment]
I'm running 8.13.6, and I'm not immediately able to replicate this (nor heard of the issue on 8.13.5).  Would probably be worth checking for a few things.

- Any errors in the browser tools console?
- Have you fully cleared cache? - See here for [bumping the client dependency version](https://adolfi.dev/blog/umbraco-bump-cdf/).
- Maybe something hasn't updated properly in your client-side files.  Might be worth downloading the "hotfix" zip from [our](https://our.umbraco.com/packages/developer-tools/umbraco-forms/), and just making sure you have all the files updated.

**Comment by tenshi04** [comment]
hi @AndyButland 
Thanks for the tips.
On right click to create - no browser tool console messages appear
I bumped up the client dependency version and it doesnt seem to fix it
I updated to 8.13.6 and the issue still appears.

It is as if the menu option just doesn't appear, so it cannot be selected.

**Comment by AndyButland** [comment]
One further possibility is that storing forms in folders is only supported if you have configured your installation to store form definitions in the database.  That means this setting in `UmbracoForms.config` needs to be configured to `True`:

```
<setting key="StoreUmbracoFormsInDb" value="True" />
```

Possibly that has been reset following the upgrade.  It doesn't seem obvious that is the problem as I can see you can see forms in folders in your screenshot.  But it's worth checking.

Failing that, would it be possible to have a copy of your project to debug/take a look?  If so, I'm at abl AT umbraco DOT dk.  Thanks.

**Comment by tenshi04** [comment]
My project currently is set as: <setting key="StoreUmbracoFormsInDb" value="False" />
I have been not been storing my files in the DB at all.
I checked on one of our servers that had an older version of forms (8.13.1) and it too seems to have the same issue.

I'll try go get a copy of our project for you. Do you need just the project files, or DB too?

**Comment by AndyButland** [comment]
Could you just confirm the setting first please? It doesn't seem to have been pasted into the GitHub comment above.

**Comment by tenshi04** [comment]
StoreUmbracoFormsInDb is set to False in my project.

**Comment by AndyButland** [comment]
OK, in that case what you see is expected.  I believe may have been was a feature with form files stored on disk in Umbraco 7 or earlier, which is probably where you saw it, but it wasn't in Umbraco 8 until the feature was reintroduced in 8.8 (but only for the mode where form definitions are stored in the database).
