### ISSUE TITLE
Local links not working in the RTE field/question type

### ISSUE THREAD

**Issue by AdoPasa** [umbraco/Umbraco.Forms.Issues#975]
I am using an RTE question type on a form to add some text and links in sections of the form. After adding the link, the link is displayed in the form but the href attribute is rendered as an root link. Looking in the back office and using the "source code" option in the RTE editor the link is setup correctly.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I am using an RTE question type on a form to add some text and links in sections of the form. After adding the link, the link is displayed in the form but the href attribute is rendered as an root link. Looking in the back office and using the "source code" option in the RTE editor the link is setup correctly.

### Specifics

Current installed version of Umbraco Forms: 10.2.2

This bug occurred because of the placeholders/magic strings. The local link has the following format "{localLink:umb://document/93df531efdd84d75a575ed1349f67b33}" and the rich text field type tries to parse the local link as an placeholder (placeholder also uses the same format, an example of an member placeholder is "{member.email}"). Because there is no value for the "{localLink:umb://document/9...}" placeholder value the link string is replaced with an empty string. 

I order to avoid behavior I have created an RTE question type with disabled placeholder on the html property.

### Steps to reproduce

1. Add an RTE question type on a form
![image](https://user-images.githubusercontent.com/18100258/218675008-b41672df-44ce-46fc-881d-88a89360d126.png)

2. Add an local link in the RTE editor
![image](https://user-images.githubusercontent.com/18100258/218675482-3974eab1-ec05-4bc1-88ca-f670e52a62c8.png)

3. See how the link is added using the "View source code" option
![image](https://user-images.githubusercontent.com/18100258/218675647-91e54896-42bb-4881-98fc-5574c9142a70.png)

4. See how the link is rendered in the form
![image](https://user-images.githubusercontent.com/18100258/218676290-b6afad5a-1291-4762-ab6f-99daa871d89e.png)

### Expected result

I expected to get an link that redirect to a local page on the umbraco instance
![image](https://user-images.githubusercontent.com/18100258/218676646-837330e5-16b5-444e-8a3e-d5f045454920.png)

### Actual result

I got an link that redirect to the root page of the umbraco instance (the href attribute is set to "/")
![image](https://user-images.githubusercontent.com/18100258/218676340-f72056f1-c5e1-4a18-8232-4be768dd611e.png)

**Comment by AndyButland** [comment]
Hi @AdoPasa - thanks for the report and the clear reproduction steps.  Your diagnosis is quite right too. We've already had this problem reported though [issue 972](https://github.com/umbraco/Umbraco.Forms.Issues/issues/972).  It's fixed now and will be updated in the next releases.

**Comment by AdoPasa** [comment]
Thank for the quick reply,  I was searching for this issue but didn't find that it is already reported
