### ISSUE TITLE
Umbraco throws Authorization error after marking a field as non sensitive data

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [umbraco/Umbraco.Forms.Issues#976]
Whenever a field in Umbraco Forms is marked as sensitive data you can save the form without any problems. However if you remove the sensitive data flag from this same field, Umbraco throws an Authorization error after saving the changes.

This issue can be reproduced by using a clean install of Umbraco 10.4.0 with Umbraco Forms 10.2.3.

1. Create a new form
2. Mark a field as sensitive data
3. Save the changes
4. Uncheck the sensitive data toggle on a field
5. Submit the changes

![image](https://user-images.githubusercontent.com/105918931/218775668-8a345ff6-c718-4818-bb0b-a79e36c7f0fd.png)

**Comment by AndyButland** [comment]
Thanks for the report, can replicate.  We'll get this fixed up for the next releases.

**Comment by RGV2ZWxvcGVy** [comment]
@AndyButland Do you happen to know if there is a workaround to uncheck the sensitive data flag on a field without recreating the entire form?

**Comment by AndyButland** [comment]
Not that I can see from a UI or code perspective I'm afraid - it seems there was simply a bug in a check used to determine if the current user is allowed to remove this flag based on their permissions, that we'll need to patch.

The only option I can see would be to - carefully! - update the information on the form directly in the database - it's in the `UFForms` table, there's a field called `Definition` that contains the JSON representation of the form details.  You'll find this flag on the field and could update the value.

**Comment by RGV2ZWxvcGVy** [comment]
@AndyButland Okay thanks for the info!
Is there any news on when version 10.2.4 of Umbraco Forms is gonna get released? Or could this take a few weeks?

**Comment by AndyButland** [comment]
Not scheduled yet, but in the next 2-3 weeks I expect.
