### ISSUE TITLE
Umbraco forms workflow validation message user improvements.

### ISSUE THREAD

**Issue by shaniacorbishley2** [umbraco/Umbraco.Forms.Issues#977]
When selecting 'Send email with template (razor)' and filling out all fields mandatory apart from the template then pressing 'Submit', a non-user friendly error message appears to ensure a template is selected (see image):

![image](https://user-images.githubusercontent.com/44789714/218805138-024ef576-1e6f-4d81-bdf2-5383e0b3d25e.png)

We've had a few users find this a bit confusing, especially if they don't have knowledge of razor files. It would be useful to have this error message mention the word template and or have a better indication on where the validation issue is.

**Comment by AndyButland** [comment]
Yes, agree we can certainly improve the messaging here to ensure we reference the field by the name the user sees, i.e. "Email Template" instead of "RazorViewFilePath".  We'll do that for the next releases.
