### ISSUE TITLE
Undocumented breaking change

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Forms.Issues#978]
An undocumented breaking change is causing issues for users of my uCaptcha package...

Could I have a reason as to why the following was removed from the `Partials/Forms/Themes/THEMENAME/Render.cshtml` file

```
@if (Model.CurrentPage.JavascriptCommands.Any())
{
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        @foreach (var javascriptCommand in Model.CurrentPage.JavascriptCommands)
        {
            @Html.Raw(javascriptCommand)
        }
    });
</script>
}
```

It means developers need to manually create this file now, to add back in what was once core code

**Comment by AndyButland** [comment]
Looking through the git history it seems this was removed back around April 2017.  Are you of the impression you've seen this block of code within the file you mention more recently than that please?

**Comment by AaronSadlerUK** [comment]
Also in April 2020 a year earlier:
https://github.com/AaronSadlerUK/UmbracoForms.uCaptcha/blob/c87fa96745a6e9b98f39d059544b666539f91431/TestSite/Views/Partials/Forms/Themes/default/Render.cshtml#L59

So I can safely say it may have been moved into a partial, but no removed entirely in 2017

**Comment by AaronSadlerUK** [comment]
The issue is less visible now that the theme is a Razor Class Library (not something I agree with, downloading the zip is an easy to miss step)

The documentation doesn't make it clear, but it looks like it may have been replaced with:
`@Html.RenderUmbracoFormDependencies()`

However in some circumstances the older way is still preferred:

```
@if (Model.CurrentPage.JavascriptCommands.Any())
{
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        @foreach (var javascriptCommand in Model.CurrentPage.JavascriptCommands)
        {
            @Html.Raw(javascriptCommand)
        }
    });
</script>
}
```

Either way [I've updated my readme](https://github.com/UmbHost/Our.Umbraco.Forms.uCaptcha#required-theme-changes) to advise that either of the above ways of loading the dependencies are required, the changelog however should be clearer about large breaking changes like this.

Also, the documentation is extremely unclear around loading dependencies whether only this:
https://docs.umbraco.com/umbraco-forms/developer/prepping-frontend

or both that and this:
https://docs.umbraco.com/umbraco-forms/developer/rendering-scripts

are required when loading dependencies.

**Comment by AndyButland** [comment]
I may be missing something, but that partial is "Script.cshtml", and I don't see reference to the original code you posted in that, even going back to early V8.  Do you have a link to an example where you see that please?

**Comment by AaronSadlerUK** [comment]
I can't remember when I got that, it's a snippet I've had lying around for a while which I copied from the base theme at the time (not sure when that time was though) which worked to fix the missing scripts in my packages
