### ISSUE TITLE
Thank you message being displayed on form page when navigating back to it

### ISSUE THREAD

**Issue by mitraganesh** [umbraco/Umbraco.Forms.Issues#980]
We have a situation to show multiples thank you page conditionaly. So we have created a custom workflow and redirect to pages conditionaly. Its working fine but when user click on browser back button after sumitted the form its showing Thnak you message except loading the form with pre select data. 

Can anyone help me on this?

**Comment by AndyButland** [comment]
Can you share some more details please?  In particular what versions you are running and how you are triggering the redirect from your custom workflow?  That should help us reproduce the issue and see if there's a resolution.  Thanks.

**Comment by mitraganesh** [comment]
@AndyButland Thanks for your quick response.

Form version 8.13.3

![Screenshot](https://user-images.githubusercontent.com/42875097/219299939-9db8a41b-d23c-4505-a320-40a9a9463ad7.png)


On last workflow "Redirect to Category thank you page" code as follows
```
if (category == "xxxx")
                {
                    
                    HttpContext.Current.Response.Redirect("/careers/careers-thank-you-centre/");
                   
                }
                else if (category == "yyyy")
                {
                    
                    HttpContext.Current.Response.Redirect("/careers/careers-thank-you-childrens-therapies/");
                    
                }
                else
                {
                    
                    HttpContext.Current.Response.Redirect("/careers/thank-you-for-applying/");
                   
                }
return WorkflowExecutionStatus.Completed;

```

**Comment by AndyButland** [comment]
I'm not 100% sure this will resolve the problem, but there are downsides to how you are doing it via a redirect in the workflow itself, as this cuts short some of the processing of the form submission (as well as any subsequent workflows if you had any configured).

I'd suggest looking to implement it via the supported method which is documented [here](https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Extending/#customizing-post-submission-behavior), and available in the version you are using.

If having done that you still see the issue, please let us know and we'll take a deeper look.

**Comment by mitraganesh** [comment]
It working fine now.

Thanks for your help :)
