### ISSUE TITLE
Ajax api doesn't include width of columns when retrieving a form

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#981]
Umbraco Version: 10.4.0
Umbraco Forms Version: 10.2.3

When I call the api to get form data via an api call, all of the column widths are 0 (api call to "/umbraco/forms/api/v1.0/definitions/{id}?contentId={contentId}"). This issue can even be seen in the example response data in the [documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms), which has 0 instead of 12 for the column width.

Reproduction
------------
### Bug summary
Width property of columns in form data is always 0.

### Specifics
It looks like it's just a data point that was left out when structuring the data returned by the api in the **FormDtoFactory** class. The code below doesn't set the width property.

```csharp
private FormFieldsetColumnDto BuildFormColumnDto(Form form, Hashtable? pageElements, FieldsetContainer container) {
    Form form2 = form;
    Hashtable pageElements2 = pageElements;
    return new FormFieldsetColumnDto {
        Caption = _placeholderParsingService.ParsePlaceHolders(container.Caption ?? string.Empty, null, form2, pageElements2),
        Fields = from x in container.Fields
                 select BuildFormFieldDto(form2, pageElements2, x) into x
                 where x != null
                 select (x)
    };
}
```

### Steps to reproduce

1. Create a form
2. Add a property to a group.
3. Save the form.
4. Check the results of the api call to see whether the width is set.

### Expected result

I expect the value of width to be 12 for a one column layout, 6 for a two column layout, etc.

### Actual result

All column widths are set to 0.

**Comment by AndyButland** [comment]
Thanks @jaandrews - looks like you've identified the oversight here.  We'll get this fixed for the next releases.
