### ISSUE TITLE
Rich Text form field link always goes to root even when another content node is picked

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco.Forms.Issues#983]
Reproduction
------------

### Bug summary

When adding a link within the form field "Rich Text", the link will always navigate to the root site URL ("/"), regardless of whether a specific content item has been chosen or not.

### Specifics

Running Umbraco 10.3.2 using Umbraco Forms 10.2.1. Any browser/device (several people have tested and got the same results).

### Steps to reproduce

1. Add the rich text form field type into a form
2. Add a link and select a page in the content tree (one that isn't the home page)
3. Save the form
4. Pick this form for any test page
5. Save, publish and view the page 
6. Click the link on the test page in question

![image](https://user-images.githubusercontent.com/1649855/221886842-c66fba47-b9ef-447b-95c3-9024f0884d81.png)

### Expected result

Link should go to the link as picked in the Rick Text Editor form field.

### Actual result

Link goes to home page instead of the inserted link.

The source view of the Rich Text Editor content looks similar to this:

`<p><a href="/{localLink:umb://document/720b95f97e474aad9e87f7eccfdd9dab}" title="Anything">Anything</a></p>`

**Comment by AndyButland** [comment]
Thanks for the report @emmagarland, but I think this duplicates #972. We've found the cause and will be patching in the next releases, due next week.

**Comment by emmagarland** [comment]
Great, thanks @AndyButland
