### ISSUE TITLE
Configuration of form button texts

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco.Forms.Issues#985]
As a developer I want to add default values for the Captions of all forms. 

Our client want's to have default values for the "Submit", "Next" and "Previous" button labels. 

As a developer I would expect that I can configure them the same as ohter fields like the RequiredErrorMessage. For the developer there is no easy way to add these to every form. However, the validation fields are configuable. We would like to see configs for that. 
The client now has to add the same texts for every form he creates, which is a tedious task to perform.

**Comment by AndyButland** [comment]
Makes sense that these are included in the defaults that can be set via configuration, I agree.  We'll include this in the upcoming minor release for Forms 10+.
