### ISSUE TITLE
Send Email workflow has extra character in subject line if single quote is found in text using magic strings

### ISSUE THREAD

**Issue by tenshi04** [umbraco/Umbraco.Forms.Issues#988]
A brief description of the issue goes here.

In the Send Email workflow, if we set up the subject line to be:
**Email sent from {username}**
but username on the form has the value: **John O'donnell**
the Subject line in the actual email sent says: **Email sent from John O\\'donnell**

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

In the Send Email workflow, if using magic strings in the subject field, and the magic string contains a single quote, the email sends \\' in the subject line of the email.

### Specifics

Umbraco 8.18.5
Umbraco Forms 8.13.6

### Steps to reproduce

1. Create a new form
2. Create a text input with an alias 'username'
3. Add a workflow step using 'Send email'
4. Set a recipient email address to send the mail to
5. Pick a default template
6. Set the subject to be: Email sent from {username}
7. Save the form
8. Now go to the form to fill it out
9. Under username, enter : Jack O'Donnell
10. Submit the form
11. View the email, especially the subject line. You will see the subject say: Email sent from Jack O\\'Donnell

### Expected result

The email should say : Email sent from Jack O'Donnell

### Actual result

View the email, especially the subject line. You will see the subject say: Email sent from Jack O\\'Donnell

**Comment by AndyButland** [comment]
Thanks for the report.  This issue was actually found and fixed recently in a more significant update and will be resolved in the next minor releases of Forms 10+ (due out as a release candidate tomorrow).  We'll also patch Forms 8 and 9 with this specific fix in the next round of patch releases.

**Comment by tenshi04** [comment]
Thanks for the update @AndyButland - and glad to hear that it will be patched in Forms 8. Will 8 also be patched at the same time that 10+ is fixed?

TY!

**Comment by AndyButland** [comment]
We haven't scheduled yet, but I would expect it will be a week or two afterward.
