### ISSUE TITLE
Some magic strings don't work when using ajax api because culture can't be passed in

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#989]
The current [api](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms) doesn't allow the culture to be passed in, so sites with multiple cultures will only receive the content for the default language when using [magic strings](https://docs.umbraco.com/umbraco-forms/developer/magic-strings) for dictionaries and content properties.

There are a couple ways to address this.
1. Add ability to pass in the culture to the api, allowing this data to be replaced with the content from the correct culture.
2. Move responsibility for processing magic strings to the front end.

I recommend the former approach, since that will keep how the magic strings are processed consistent across installations. Some thought will need to be given to how to handle data only available on the front end like cookies though.

Reproduction
------------

#### Versions
- Umbraco : 10.4.0
- Umbraco Forms: 10.2.4

### Steps to reproduce

1. Create a dictionary item and set a value for the default language and non default language.
2. Add magic string to a form that points to that dictionary.
3. View the form on the front end in the non default language.

### Expected result

The form will include the content for the non default language when visiting a page that uses the non default language.

### Actual result

The form displays the content from the default language instead.

**Comment by AndyButland** [comment]
Thanks for this suggestion @jaandrews.  This came up as a support request today actually, perhaps from you, so I was already looking into it.  I agree we should add support for this and think your first suggestion is the best approach.  I've had a look into it and it seems to be reasonably straightforward - we need to add this parameter and set the culture on the thread and variation context appropriately, and with that we get the appropriately translated content and dictionary values coming through.

**Comment by jaandrews** [comment]
@AndyButland Yeah. That was me.

**Comment by AndyButland** [comment]
This has been added as a parameter option now and will be added to the next minor releases for Forms 10+.
