### ISSUE TITLE
Incorrect casing for UFRecordFields table in SQL in RecordFieldsStorage class

### ISSUE THREAD

**Issue by pmeliesIology** [umbraco/Umbraco.Forms.Issues#99]
Incorrect casing of UFRecordFields table in code.

Reproduction
------------

### Bug summary

The Umbraco.Forms.Data.Storage.RecordFieldStorage class (in the Umbraco.Forms.Core assembly) references the UFRecordFields table name as "URrecordFields" in the InsertRecordField(RecordField) and UpdateREcordField(RecordField) methods.  The actual table name is UFRecordFields ("R" in "Records" is capitalized).  This causes a "Table 'database_name.UFrecordFields' doesn't exist" error when using a MySQL database on a Linux flavor whose file system is case sensitive.   The RecordFieldValueStorage class correctly uses "UFRecordFields".  Please update the RecordFieldStorage class to use the proper casing.

### Specifics

We're still on UmbracoForms version 7.0.6.

### Steps to reproduce

Use a MySQL database on a Linux system whose file system is case sensitive.  This is not an issue in SQL Server or on Linux systems whose files systems are NOT case sensitive.

Setup a basic contact us form and try to submit the form.  See the attached file to view the asp.net error page reporting this unhandled exception.

I am able to replicate the same error by issuing a basic ``SELECT * FROM UFrecordFields``  query directly against the database using DBeaver.  Executing ``SELECT * FROM UFRecordFields`` works as expected.

### Expected result

No errors when using an Umbraco Forms form.

### Actual result

See attached error page with call stack.  Rename to .html extension to view it in a browser".  

[Table 'Iology_CMS.UFrecordFields' doesn't exist.html.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/2928043/Table.Iology_CMS.UFrecordFields.doesn.t.exist.html.txt)

**Comment by bergmania** [comment]
Fixed in:
- V7: https://github.com/umbraco/Forms/commit/406d60ac5c30a965bdf747d07c07b9392b69febc
- V8: https://github.com/umbraco/Forms/commit/699d0d1350a88d438f6c85bdbd4823a88b0bdfd0
