### ISSUE TITLE
Conditions that have been previously added are still applied after conditions are disabled

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco.Forms.Issues#993]
I have a field that previously had conditions. When I toggle off "Enable conditions," the conditions are still applied (at least for the ajax forms version, haven't tested with the standard form embed). This can be worked around by deleting the conditions before toggling it off.

Reproduction
------------

### Specifics
- Umbraco: 10.4.0
- Umbraco Forms: 10.2.4

### Steps to reproduce

1. Enable conditions on a form field.
2. Add condition to that form field.
3. Save the form.
4. Disable conditions for that form field.
5. Check the data returned by the [form definition api](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms) or test the condition on the front end for non ajax form implementations.

### Expected result

The conditions would be removed from the data used to render the field when conditions are turned off.

### Actual result

The conditions are still applied.

**Comment by AndyButland** [comment]
It looks like we could, and perhaps should, be clearing the previously selected condition on save of the form if it's subsequently disabled.  However there's a chance people might be relying on that behaviour (to be able to temporarily turn a condition off, and then on again later without having to reconfigure it).

So I think the best resolution here is that we expose the `enabled` property that exists on the condition, such that it can be read and used to decide whether to act on the configured condition.  This will be included in the next release.

**Comment by jaandrews** [comment]
@AndyButland I agree it's better to leave the condition data on the fields. Not sure there is a good reason to return enabled as a flag though instead of just emptying the array in the data returned by the api. Only reason I can think of is that the user would want to toggle the conditions on/off on the front end, which I doubt is a common need. Something like
```csharp
Conditions = field.ConditionsEnabled ? field.Conditions : null
```
would handle this server side.

This would make the api a little easier to use since that wouldn't have to add a check for whether they are enabled in the front end code. In the end, it's not a big deal though, and either approach will work.

**Comment by AndyButland** [comment]
Thanks @jaandrews - yes, I agree and prefer your approach.  I'll update the implementation to do that.
